### ISSUE TITLE
[Migration] Default hash generator class in ESB481 should be change when migrating to a latest version

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1009]
When migrating cache mediator scenario in ESB 481 to a later version, '**org.wso2.caching.digest.DOMHASHGenerator**' is not considered as a valid interface, artifacts should be changed to use '**org.wso2.carbon.mediator.cache.digest.DOMHASHGenerator**' as the hash generator.

ex: 
ESB 481 support - org.wso2.caching.digest.REQUESTHASHGenerator but later versions  support "org.wso2.carbon.mediator.cache.digest.REQUESTHASHGenerator"

Better to include this into the migration guide

**Comment by praneesha** [comment]
Added the following note under the section "Migrating artifacts" in the respective pages related to upgrading from WSO2 ESB 4.8.1 to later versions. 

"The org.wso2.caching.digest.REQUESTHASHGenerator interface, which is supported by WSO2 ESB 4.8.1 is not supported by later versions. Therefore, change the artifacts to use the org.wso2.carbon.mediator.cache.digest.DOMHASHGenerator as the hash generator when migrating artifacts related to the Cache mediator from WSO2 ESB 4.8.1 to a later version."

Therefore, this note was added in docs of WSO2 ESB 4.9.0 and below.
