### ISSUE TITLE
Build error. One or more certificates rejected. Cannot proceed with installation.

### ISSUE THREAD

**Issue by uleming** [wso2/product-ei#1011]
Same as in here. 
http://wso2-oxygen-tank.10903.n7.nabble.com/One-or-more-certificates-rejected-Issue-on-product-Build-td135367.html#a135368
Reinstall of oracle jdk didn't help.

**Ubuntu 16.04**
**Oracle jdk 1.8.0_144**
**product-ei (branch release-6.1.1-rc )**
**Unable to build on openjdk1.8.0_133 as well.**
Didn't found any mention of https in pom.xml as well as nothng in documentation about https. Only thing i could imagine is that wso2 repository redirects from http to https, or i miss something.

Fall on step 
[

> INFO] WSO2 MSF4J Runtime ................................. FAILURE [  6.888 s]
> 
> [INFO] Copying resources
> [INFO] Running Equinox P2 Publisher Application for Repository Generation
> [INFO] Command line:
> 	/bin/sh -c cd /home/lleming/temp/product-ei/p2-profile/msf4j-profile && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/lleming/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/plugins/org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher -source /home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/tmp.1505310257046/featureExtract -metadataRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -metadataRepositoryName msf4j-feature-installation -artifactRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -artifactRepositoryName msf4j-feature-installation -publishArtifacts -publishArtifactRepository -compress -append
> Generating metadata for ..
> Generation completed with success [0 seconds].
> [INFO] Completed running Equinox P2 Publisher Application for Repository Generation
> [INFO] 
> [INFO] --- carbon-feature-plugin:2.0.1:publish-product (publishing products) @ msf4j-feature-installation ---
> [INFO] Command line:
> 	/bin/sh -c cd /home/lleming/temp/product-ei/p2-profile/msf4j-profile && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/lleming/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/plugins/org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.publisher.ProductPublisher -metadataRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -artifactRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -productFile /home/lleming/temp/product-ei/p2-profile/msf4j-profile/carbon.product -executables /home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/org.eclipse.equinox.executable_3.5.0.v20110530-7P7NFUFFLWUl76mart -publishArtifacts -configs gtk.linux.x86 -flavor tooling -append
> Generating metadata for ..
> Generation completed with success [0 seconds].
> [INFO] 
> [INFO] --- carbon-feature-plugin:2.0.1:generate-profile (materialize-product) @ msf4j-feature-installation ---
> [INFO] Command line:
> 	/bin/sh -c cd /home/lleming/temp/product-ei/p2-profile/msf4j-profile && /usr/lib/jvm/java-8-oracle/jre/bin/java -jar /home/lleming/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/plugins/org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.director -metadataRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -artifactRepository file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/p2-repo -installIU carbon.product.id -profileProperties org.eclipse.update.install.features=true -profile profiles/default -bundlepool file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/wso2msf4j-2.2.2/osgi -shared file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/wso2msf4j-2.2.2/osgi/p2 -destination file:/home/lleming/temp/product-ei/p2-profile/msf4j-profile/target/wso2msf4j-2.2.2/osgi/profiles/default -p2.os linux -p2.ws gtk -p2.arch x86 -roaming
> Installing carbon.product.id 5.1.2.
> Installation failed.
> One or more certificates rejected. Cannot proceed with installation.
> Application failed, log file location: /home/lleming/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/configuration/1505310260968.log
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 

Eventually disable(comment) module in product-ei/p2-profile/pom.xml 

`<!--module>msf4j-profile</module-->`

**Comment by uleming** [comment]
Solve by downloading and manual install oracle jdk-1.8.0-121 and configuring environment JAVA_HOME and PATH

**Comment by mbouchar** [comment]
You can also import the missing certificate to the java default keystore. It is explained in the following pull request:
https://github.com/wso2/product-ei/pull/779/files

**Comment by Nirothipan** [comment]
Closing as this will be tracked in https://github.com/wso2/product-ei/issues/3763
