### ISSUE TITLE
[Bug] Error when trying retrieve data in json format in dataservice

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/product-ei#1016]
In EI 6.1.1, when there is a dataservice with two operations (and also two resources), the second resource fails with the error [1] in the console when we try to call the rest endpoint of for the second resource with the header set as "Accept: application/json". This passes when the same is set for the first resource.

IMO this should be a L1 bug since there is no workaround other than creating separate dataservice for the second resource.

[1] -
> [2017-09-14 13:58:38,778] [EI-Core]  INFO - DeploymentInterceptor Removing Axis2 Service: dataservice2 {super-tenant}
> [2017-09-14 13:58:38,798] [EI-Core]  INFO - DeploymentInterceptor Deploying Axis2 service: dataservice2 {super-tenant}
> [2017-09-14 13:58:38,798] [EI-Core]  INFO - DeploymentEngine Deploying Web service: dataservice2.dbs - file:/Users/nira/wso2/qsp/inc-research/products/wso2ei-6.1.1/repository/deployment/server/dataservices/dataservice2.dbs
> [2017-09-14 13:58:46,452] [EI-Core] ERROR - JsonStreamFormatter Error occurred while writing to application/json
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:107)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:573)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:264)
> 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> 	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
> 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.axis2.AxisFault: Error while writing to the output stream using JsonWriter
> 	at org.apache.axis2.json.gson.JsonFormatter.writeTo(JsonFormatter.java:104)
> 	... 17 more
> Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPostNormalQuery': DS Fault Message: Error in XML generation at StaticOutputElement.execute
> DS Code: UNKNOWN_ERROR
> Nested Exception:-
> javax.xml.stream.XMLStreamException: Invalid Staring element
> 
> DS Code: DATABASE_ERROR
> Source Data Service:-
> Name: dataservice2
> Location: /dataservice2.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> Current Request Name: _getall
> Current Params: {}
> Nested Exception:-
> DS Fault Message: Error in XML generation at StaticOutputElement.execute
> DS Code: UNKNOWN_ERROR
> Nested Exception:-
> javax.xml.stream.XMLStreamException: Invalid Staring element
> 
> 
> 	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:102)
> 	at org.wso2.carbon.dataservices.core.engine.DSOMDataSource.serialize(DSOMDataSource.java:107)
> 	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:691)
> 	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.serializeAndConsume(OMSourcedElementImpl.java:754)
> 	at org.apache.axis2.json.gson.JsonFormatter.writeTo(JsonFormatter.java:100)
> 	... 17 more
> [2017-09-14 13:58:46,457] [EI-Core] ERROR - PassThroughHttpSender Failed to submit the response
> org.apache.axis2.AxisFault
> 	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:573)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:264)
> 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> 	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
> 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> [2017-09-14 13:58:46,458] [EI-Core] ERROR - ServerWorker Error processing GET request for : /services/dataservice2/all
> org.apache.axis2.AxisFault: Failed to submit the response
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:632)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:266)
> 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> 	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
> 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.axis2.AxisFault
> 	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:573)
> 	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:264)
> 	... 10 more

**Comment by chanikag** [comment]
Hi Niranjan,

Is it possible to mention the dataservice config? Since this is a generic exception, by looking at the error, it is difficult to identify the actual root cause. 

Thanks

**Comment by klastereq** [comment]
We have a similiar issue - in our case reason is in element which in XML response is generated as

<addrID>000304000</addrID>

but JSON type response fail.
When we remove attribute - response is generated properly in all formats.

**Comment by Niranjan-K** [comment]
@chanikag : As mentioned above, you can easily reproduce this by creating a dataservice with two operations and two resources. As I remember the resource which was created second, does not work (set the header as "Accept: `application/json").

**Comment by chanikag** [comment]
This issue happens when both the result group name and row name are exactly same in both the resources. When you define two queries (and two resources to map those), with the same group name, row name with the same namespace, then only one complex element for that row name is added in the generated WSDL for the service. In a WSDL, we can't have two complex element for same name  unless the namespace is different. In other words, in order to differentiate the group name and row name pair in two different queries you need to have two namespaces.

In JSON formatter, when the XML payload converts to JSON, it validates against the generated schema of that service. The schema is generated according to the WSDL of the service. The error that you got has happened, as there is no complex type related to the second resource is added in the generated schema.

As a solution you can follow either,
1. Change the output type as JSON and give the JSON mapping. In that way, the namespace is automatically get the query name appended to make it unique for that particular query. 
           OR
2. Change the row namespace of the query.

**Comment by valponi** [comment]
> This issue happens when both the result group name and row name are exactly same in both the resources. When you define two queries (and two resources to map those), with the same group name, row name with the same namespace, then only one complex element for that row name is added in the generated WSDL for the service. In a WSDL, we can't have two complex element for same name unless the namespace is different. In other words, in order to differentiate the group name and row name pair in two different queries you need to have two namespaces.
> 
> In JSON formatter, when the XML payload converts to JSON, it validates against the generated schema of that service. The schema is generated according to the WSDL of the service. The error that you got has happened, as there is no complex type related to the second resource is added in the generated schema.
> 
> As a solution you can follow either,
> 
> 1. Change the output type as JSON and give the JSON mapping. In that way, the namespace is automatically get the query name appended to make it unique for that particular query.
>    OR
> 2. Change the row namespace of the query.

It worked for me. My API had several resources with the same group name and row. After creating a unique group name and row name for each resource, the error no longer occurs. Thank you.

**Comment by noah2031** [comment]
you can add 
Request header : Accept: application/xml , Content-Type: application/json
