### ISSUE TITLE
JMS Transport is not setting the "ReplyTo" header when used in multi-tenant environment

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-ei#1036]
This issue happens in a multi tenanted environment when we set the "ReplyTo" header.
Following sample[1]  synapse configuration can be used to reproduce this scenario with a JMS broker.

I did some debugging and found that the issue occurs due to the fact that TenantTransportSender is overriding the axisoperation when sending a message over JMS transport. 

The below code segment in JMSSender.java  (wso2-axis2-transports) is causing this problem. 
```
        // should we wait for a synchronous response on this same thread?
        boolean waitForResponse = waitForSynchronousResponse(msgCtx);
        Destination replyDestination = jmsOut.getReplyDestination();

        // if this is a synchronous out-in, prepare to listen on the response destination
        String replyDestName;

        if (waitForResponse) {
```

According to this logic, We only set the "JMSReplyTo" header if the "waitForResponse" parameter is true. This is checked inside following method in the AbstractTransportSender.Java class (wso2-axis2-transports)

```
    protected boolean waitForSynchronousResponse(MessageContext msgCtx) {
        return msgCtx.getOperationContext() != null && "http://www.w3.org/ns/wsdl/out-in".equals(msgCtx.getOperationContext().getAxisOperation().getMessageExchangePattern());
    }
```
When this check happens, it checks the axisoperation and it does not match with the desired message exchange pattern (Out-In). The reason for this mismatch is that within the invoke method of TenantTransportSender.java (carbon-kerner->carbon-core) class, we are overriding the axisoperation set by the synapse mediation engine.

```
        AxisOperation axisOperation = axisService.getOperation(
                MultitenantConstants.MULTITENANT_DISPATCHER_OPERATION);
        OperationContext operationContext = serviceContext.createOperationContext(axisOperation);
        operationContext.addMessageContext(superTenantOutMessageContext);

        superTenantOutMessageContext.setOperationContext(operationContext);
```
This method overrides the correct axisoperation with a wrong message exchange pattern (In-Out) and this causes the JMSSender to skip setting the replyDestination property.

We need to fix this properly at the TenantTransportSender side and set the proper axisOperation.

Another option we can use to fix this issue is change the way JMSSender is written to configure "JMSReplyTo" header. Instead of using "axisOperation" to decide on whether to set the "JMSReplyTo" header and waiting for a response, we can use "replyDestination" parameter. I have attached a diff which fixes the issue using this approach.

[1] 
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="JMSSender"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <property name="FORCE_SC_ACCEPTED" scope="axis2" value="true"/>
         <send>
            <endpoint>
               <address uri="jms:/SimpleStockQuoteService?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&amp;java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory&amp;java.naming.provider.url=tcp://localhost:61616&amp;transport.jms.DestinationType=queue&amp;transport.jms.ReplyDestination=SMSReceiveNotificationStore"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <send/>
      </outSequence>
   </target>
   <description/>
</proxy>
```

**Comment by chanakaudaya** [comment]
[jms-tenant-replyto-fix.diff.zip](https://github.com/wso2/product-ei/files/1324067/jms-tenant-replyto-fix.diff.zip)

**Comment by chanakaudaya** [comment]
This issue is also reported against WSO2 API Manager.

https://wso2.org/jira/browse/APIMANAGER-5892

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/wso2-axis2/pull/127
