### ISSUE TITLE
Update carbon-identity-framework version in product-ei to 5.8.x

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#1038]
We are still on 5.7.x. 5.8.x has gone out. Need to resolve any osgi version issues when p2-profile generation stage.

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1138

**Comment by himasha** [comment]
Latest identity.framework.version upgrade gives an error on IDN_ASSOCIATED_ID table not found. Following PR fix this issue https://github.com/wso2/carbon-identity-framework/pull/1143
