### ISSUE TITLE
[Analatics] Issue with running the Stockquote sample with Integrator server

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#105]
**Environment**
OS-ubuntu 14.04
JAVA-jdk 1.7.0_51
Browser Chrome 51.02, Firefox 47.0
wso2ei-6.0.0-SNAPSHOT  27th of Feb

**Steps**

1. Enable analytics in Integrator server.
2.  Deploy the required ESB artifacts 
3. Issue the following command from the <EI>/samples/axis2Server/src/SimpleStockQuoteService directory
ant
4. Issue the following command from the <ESB_HOME>/samples/axis2Server directory.
./axis2server.sh

**Error**
./axis2server.sh: 187: ./axis2server.sh: java: Argument list too long

**Comment by madhawa-gunasekara** [comment]
Fixed with https://github.com/wso2/product-ei/pull/147
