### ISSUE TITLE
When a groove dependent car file is placed, management console is not accessible 

### ISSUE THREAD

**Issue by bsenduran** [wso2/product-ei#1054]
**Description:**
A car file with groove dependency (i.e a script mediator uses a groove ) is added to the `EI-HOME/repository/deployment/server/carbonapps` When the server is started it doesn't complain any errors but the mgt console is not accessible

**Affected Product Version:**
EI 6.1.1
 
**Steps to reproduce:**
* Create a car file which uses a groove script mediator.
* Upload the car file to the EI 611 
  * You will get a class not found exception. but the car file cannot be deleted from the UI and it will not even shown as a fault car file. 
* restart the EI server
  * there wont be any errors in the start up but the mgt console is not accessible

This can be solved by adding the `groovy-all_2.3.9.jar`  to the dropins directory. But this jar is already available in plugins directory 

The above mentioned scenario revels  two issues 
* groovy-all_2.3.9.jar is not correctly getting added to the runtime 
* missing dependency in a car file doesn't expose the error.

**Comment by Emmerson-Miranda** [comment]
The problem to fix is to able to see the mgt console after restart and in the fault application list see the faulty car file. 

Cheers.
