### ISSUE TITLE
[EI620][ESB] Leave-as-is HTTP method for HTTPEndpoint is not working

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1079]
HTTPEndpoint documentation includes support for HTTP methods[1] including 'Leave-as-is' Http method, where Request's initial HTTP method will be used according to the scenario. Though users can add this HTTP method through management console UI (When creating an HttpEndpoint) the functionality is not working. 

Steps to reproduce:
1. Create HttpEndpoint from UI with Http method selected as 'Leave-as-is'.
2. Create a sample API with GET resource and invoke the endpoint created in step 1.
3. Expected GET results are not obtained.

Depending on the solution to this issue, Documentation also needs to be updated. (The list of HTTP methods)

**Comment by praneesha** [comment]
Closed the doc issue in [1].

Please create a new doc issue or reopen it once the implementation of the "Leave-as-is" method is finalized.

[1] https://github.com/wso2/product-ei/issues/1080

**Comment by himasha** [comment]
Tested with EI -6.1.1 and debugged the flow. You can only add the property 'Leave-as-is' through design view of management console. The idea is to not set any value to HTTP method since in [1] Http method property can be null. This will simply ignore Http method property and the incoming request's method will be sent.
