### ISSUE TITLE
[Documentation[EI620] Need to update the list of Http methods in HttpEndpoint

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1080]
In [1] the list of Http methods are as below.

Get
Post
Push
Put
Delete
Options
Head
Leave-as-is

Push needs to be replaced with PATCH. Need to check the support of 'Leave-as-is'(refer 2) and update as well.
[1] https://docs.wso2.com/display/ESB500/HTTP+Endpoint
[2] https://github.com/wso2/product-ei/issues/1079

**Comment by praneesha** [comment]
Replaced PUSH with PATCH in docs of WSO2 ESB 4.7.0 & above and of all WSO2 EI versions.

Closing this doc issue since the implementation of the "Leave-as-is" method is not yet finalized. We have [1] to track that.

[1] https://github.com/wso2/product-ei/issues/1079
