### ISSUE TITLE
Cannot Access the management console with a different Host

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#110]
Try to access the management console with a HostName it will throw the following error.

e.g : https://abc.com:8243/carbon

> [2017-02-01 08:37:32,296] [EI-Core] ERROR - TargetHandler I/O error: Host name verification failed for host : abc.com
> javax.net.ssl.SSLException: Host name verification failed for host : abc.com
> 	at org.apache.synapse.transport.http.conn.ClientSSLSetupHandler.verify(ClientSSLSetupHandler.java:171)
> 	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:308)
> 	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:410)
> 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by mpmunasinghe** [comment]
@yasassri Can you try adding the certificates for abc.com to key stores

**Comment by madhawa-gunasekara** [comment]
@yasassri please add abc.com host to /etc/hosts

**Comment by yasassri** [comment]
@madhawa-gunasekara This issue is fixed when I created a new certificate with the CN abc.com, and also as you mentioned abc.com should be added to /etc/hosts as well. Can we add these to documentation?

**Comment by yasassri** [comment]
Another workaround is to disable hostname verification. Can add this too.

**Comment by madhawa-gunasekara** [comment]
@yasassri  :+1:

**Comment by nandika** [comment]
This is  only applicable to EI 6.0.0. In 6.1.0 management console is on 9443.
