### ISSUE TITLE
WARNs when navigating through the management console

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#111]
Following WARNs were observed when navigating through the management console.

> 017-02-01 09:06:12,553] [EI-Core]  WARN - SourceHandler I/O error (Probably the connection was closed by the remote party):Broken pipe
> [2017-02-01 09:06:12,804] [EI-Core]  WARN - SourceHandler I/O error (Probably the connection was closed by the remote party):Broken pipe
> [2017-02-01 09:06:40,959] [EI-Core]  WARN - TargetHandler Connection closed by target host while receiving the response  Remote Address : localhost/127.0.0.1:9443
> [2017-02-01 09:06:40,959] [EI-Core]  WARN - SynapseCallbackReceiver Synapse received a response for the request with message Id : urn:uuid:370afa2d-9611-4802-abdc-aa9d1a389263 But a callback is not registered (anymore) to process this response

**Comment by vinok88** [comment]
This is no longer reproducible. I have checked in the latest 6.1.0-SNAPSHOT. @yasassri, shall we close the issue?

**Comment by yasassri** [comment]
Closing since its not reproducible.
