### ISSUE TITLE
Update docs to reflect maximum retries on JMS transport consumer error

### ISSUE THREAD

**Issue by MaryamZi** [wso2/product-ei#1110]
**Description:**
With the fix for ESBJAVA-5128 (wso2/wso2-axis2-transports#127), we introduce a new parameter in the JMS transport, transport.jms.MaxConsumeErrorRetryCount, specifying the maximum number of times the consumer should retry upon consumer error.

This parameter needs to be introduced only when used with brokers that have issues in notifying the Exception Listeners of exceptions occurred.

**Suggested Labels:**
Docs

**Affected Product Version:**
EI 6.2.0

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5128

**Comment by praneesha** [comment]
Added the "transport.jms.MaxConsumeErrorRetryCount" parameter as a new row in the table under the "JMS connection factory parameters" section in [1].

This will be applicable from WSO2 EI 6.2.0 onwards.

[1] https://docs.wso2.com/display/EI620/JMS+Transport
