### ISSUE TITLE
[Doc] Creating a Form in a BPMN user task

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1121]
**Description:**
Currently creating a Form in BPMN user tasks is not added to the docs. Please find a sample guide on adding a user task with relevant form fields [here](https://docs.google.com/document/d/1JSgP_FBhJZiW8D0i7X4bs6BzAlZeA2-SBAw7r-AB1qg/)

**Suggested Labels:**
EI 611, Business Process, BPMN

**Suggested Assignees:**

**Affected Product Version:**
EI 611

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Related Issues:**

**Comment by Drifftr** [comment]
This [doc](https://docs.wso2.com/display/BPS350/BPMN+Guide) on BPS 3.5.0 also describes the $subject but that has been omitted  in EI docs.

**Comment by Drifftr** [comment]
This [doc](https://docs.wso2.com/display/BPS350/BPMN+Guide) on BPS 3.5.0 also describes the $subject but it seems that has not been used in EI docs.

**Comment by Nashaath** [comment]
Added the content from the BPMN quick start guide of BPS 3.5.0 as a tutorial [1] in EI 6.1.1.
[1] https://docs.wso2.com/display/EI611/Working+with+User+Tasks
