### ISSUE TITLE
[Doc] Add BPMN Statistics API doc into EI

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1123]
**Description:**
BPMN Statistics API doc can be found [here](https://docs.wso2.com/display/BPS360/BPMN+Statistics+REST+API). Its better if this can be added to EI docs too.

**Suggested Labels:**
Business-Process, BPMN

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
N/A

**Related Issues:**

**Comment by Nashaath** [comment]
Added the BPMN Statistics REST API doc [1] to EI611.

[1] https://docs.wso2.com/display/EI611/BPMN+Statistics+REST+API
