### ISSUE TITLE
[Doc] Using BPMN boundary events

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1130]
**Description:**
Boundary events are frequently used in BPMN business processes. So its better to add about it to the docs. Please find a sample guide [here](https://docs.google.com/document/d/1NRyb2lkkcK2xjwKsiEIXV16MU83Fk9-4HP0PZKcvYXg/edit) 

**Suggested Labels:**
Business Process, BPMN

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Added a not on the purpose of Boundry Events and how a boundry event can be used in the scenario that is documented in [1].
[1] https://docs.wso2.com/display/EI611/Working+with+User+Tasks
