### ISSUE TITLE
[Doc] Add details about versioning inside EI business process docs

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1147]
**Description:**
Add details about versioning inside EI business process docs. This detail can be added to [this](https://docs.wso2.com/display/EI611/Managing+BPMN) doc.

**Suggested Labels:**
Business-Process, BPMN

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Added a note with details on versioning in [1].
[1] https://docs.wso2.com/display/EI611/Managing+BPMN

**Comment by VijithaEkanayake** [comment]
Closing the issue since the document has been updated.
