### ISSUE TITLE
Folder path in documentation needs to be amended 

### ISSUE THREAD

**Issue by srsharon** [wso2/product-ei#1166]
**Description:**
https://docs.wso2.com/display/EI611/Quick+Start+Guide#QuickStartGuide-DownloadandsetupWSO2EI page has a sample folder does not have a database folder 
![image](https://user-images.githubusercontent.com/10986966/31606484-d60c9e2a-b286-11e7-9ac9-9523ef906983.png)
database should be addressed as **dbs** 

**Suggested Labels:**
Docs

**Affected Product Version:**
EI 6.1.1

**Comment by srsharon** [comment]
Sorry this folder gets created with **ant -Ddshome=PATH_TO_EI_HOME** script. 
It would be best if we could reword this para/sentence.

**Suggestions** 
Lets create a database in **<EI_HOME>/samples/data-services** by downloading (dataServiceSample.zip ) and running it in the following manner. 

then The steps to run the script..

**Comment by praneesha** [comment]
Updated the "Set up the back-end database" section in [1] accordignly.

This is done in docs of WSO2 EI 6.1.0 and above.

[1] https://docs.wso2.com/display/EI620/Quick+Start+Guide#QuickStartGuide-Setuptheback-enddatabase
