### ISSUE TITLE
Unable to create database with the following instructions 

### ISSUE THREAD

**Issue by srsharon** [wso2/product-ei#1171]
**Description:**
As per the [documentation](https://docs.wso2.com/display/EI611/Quick+Start+Guide#QuickStartGuide-DownloadandsetupWSO2EI) followed this path to create a database**ant -Ddshome=PATH_TO_EI_HOME** 
when running the command "**curl -v http://localhost:8280/services/DOCTORS_DataService/getDoctors?SPECIALITY=surgery**" the following error comes up. 

Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processPreNormalQuery': DS Fault Message: Error in 'createProcessedPreparedStatement'
DS Code: UNKNOWN_ERROR
Nested Exception:-
org.h2.jdbc.JdbcSQLException: Table "DOCTORS" not found; SQL statement:
SELECT NAME, HOSPITAL, SPECIALITY, AVAILABILITY, CHARGE FROM PUBLIC.DOCTORS WHERE SPECIALITY=? [42102-175]

DS Code: DATABASE_ERROR
Source Data Service:-
Name: DOCTORS_DataService
Location: /DOCTORS_DataService.dbs
Description: N/A
Default Namespace: http://ws.wso2.org/dataservice
Current Request Name: _get_getdoctors
Current Params: {SPECIALITY=surgery}
Nested Exception:-
DS Fault Message: Error in 'createProcessedPreparedStatement'
DS Code: UNKNOWN_ERROR
Nested Exception:-
org.h2.jdbc.JdbcSQLException: Table "DOCTORS" not found; SQL statement:
SELECT NAME, HOSPITAL, SPECIALITY, AVAILABILITY, CHARGE FROM PUBLIC.DOCTORS WHERE SPECIALITY=? [42102-175]

**Suggested Labels:**
Docs,  Component/Integrator

**Suggested Assignees:**
Praneesha, Nilmini

**Steps to reproduce:**
Follow the documentation steps

**Comment by praneesha** [comment]
Got confirmed from Sharon that this got resolved.
