### ISSUE TITLE
Rename  dataServiceSample.zip extracted folder name

### ISSUE THREAD

**Issue by srsharon** [wso2/product-ei#1172]
**Description:**
In the [Documentation](https://docs.wso2.com/display/EI611/Quick+Start+Guide#QuickStartGuide-DownloadandsetupWSO2EI)  the dataServiceSample.zip can be downloaded from **https://github.com/wso2-docs/WSO2_EI/blob/master/Back-End-Service/Hospital-Service-2.0.0.jar** once the folder is extracted the name of the folder extracted should carry the same name not **"qsg"**

![image](https://user-images.githubusercontent.com/10986966/31655391-56dd8716-b346-11e7-9e0e-e1b73ac55665.png)

**Suggested Labels:**
Docs 

**Suggested Assignees:**
Praneesha

**Comment by praneesha** [comment]
Renamed the folder named "qsg" to "dataServiceSample" that was inside the dataServiceSample.zip file in [1].

[1] https://github.com/wso2-docs/WSO2_EI/blob/master/Quick_Start_Guide_Artifacts/dataServiceSample.zip
