### ISSUE TITLE
Properties work only when value is ASCII

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2/product-ei#1175]
Hello.

I want to pass UTF-8 symbols into properties and then assign them into payload. This is my sequence:

    <?xml version="1.0" encoding="UTF-8"?>
    <sequence name="script_seq_in" trace="enable" xmlns="http://ws.apache.org/ns/synapse">
         <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
        <property name="TEST" scope="default" type="STRING" value="Привет привет"/>
        <payloadFactory media-type="json">
            <format>{"prop": "$1"}</format>
            <args>
                <arg evaluator="xml" expression="get-property('TEST')"
                literal="false" xmlns:ns="http://org.apache.synapse/xsd"/>
            </args>
        </payloadFactory>
        
        <respond/>
    </sequence>

When I try to make request that uses this sequence it returns me this:

![image](https://user-images.githubusercontent.com/8684688/31664714-65eb0c8e-b368-11e7-89b6-e2c61ba448bd.png)

Instead of UTF-8 kyrillic symbols, it shows simple question mark symbols. 

Is it possible to use non ASCII symbols as properties? Are there another solutions?

**Comment by SuperMasterBlasterLaser** [comment]
Is there any solution?

**Comment by SuperMasterBlasterLaser** [comment]
Even if I create text file in config registry and reference it in Payload factory. It still responds with question marks

**Comment by himasha** [comment]
@SuperMasterBlasterLaser  could you try adding CHARACTER_SET_ENCODING property like below to your sequence? I have tested this with ESB 5.0.

```
<property name="CHARACTER_SET_ENCODING"
                   scope="axis2"
                   type="STRING"
                   value="UTF-8"/>
         <property name="messageType"
                   scope="axis2"
                   type="STRING"
                   value="application/json"/>
         <property name="TEST" scope="default" type="STRING" value="Привет привет"/>
         <payloadFactory media-type="json">
            <format>{"prop": "$1"}</format>
            <args>
               <arg xmlns:ns="http://org.apache.synapse/xsd"
                    evaluator="xml"
                    expression="get-property('TEST')"/>
            </args>
         </payloadFactory>
         <respond/>
```

**Comment by VijithaEkanayake** [comment]
Solution shared, hence closing the issue.
