### ISSUE TITLE
Misleading topic in BPMN REST tasks doc

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#1177]
**Description:**
The topic in [1], "Invoking a BPMN REST Endpoint" is misleading. There is no such thing as "BPMN REST endpoint". We are talking about invoking REST endpoints within a BPMN workflow. My suggestion is to use a topic like "Invoking a REST endpoint within BPMN" 

[1] - https://docs.wso2.com/display/EI611/Invoking+a+BPMN+REST+Endpoint

**Suggested Labels:**
doc
**Suggested Assignees:**
@praneesha 
**Affected Product Version:**
EI 6.x, BPS 3.6.x
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Renamed the pages as follows:

- Invoking a BPMN REST Endpoint -> Invoking a REST Endpoint from a BPMN Workflow

- Invoking a BPMN SOAP Endpoint -> Invoking a SOAP Endpoint from a BPMN Workflow

This is done in docs of all WSO2 EI versions and in WSO2 BPS 3.5.1 and above.
