### ISSUE TITLE
[Critical] Cannot access the Mgt console when Nginx is fronted

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#118]
When I try to access carbon console through NginX I'm getting the following error.

>  ERROR - NativeWorkerPool Uncaught exception
> java.lang.ArrayIndexOutOfBoundsException: 2
> 	at org.wso2.carbon.integrator.core.Utils.rewriteLocationHeader(Utils.java:229)
> 	at org.wso2.carbon.integrator.core.handler.IntegratorSynapseHandler.handleResponseInFlow(IntegratorSynapseHandler.java:115)
> 	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.invokeHandlers(Axis2SynapseEnvironment.java:1077)
> 	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:242)
> 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554)
> 	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262)
> 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by madhawa-gunasekara** [comment]
Fixed with https://github.com/wso2/product-ei/pull/119
