### ISSUE TITLE
Fix the Dynamic Router Sample

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#1191]
**Description:**
Adding the getProperty()method as a case regex value within a switch mediator is not supported in WSO2 ESB/EI.

 <switch source="get-property('tt')">
            <case regex="get-property('tt')">
               <log level="custom">
                  <property name="foo" value="*************"/>
               </log>
            </case>
         </switch>

Therefore, we need to change the sample[1] and [2] accordingly. 

For more information, please refer email[3]. Also, please open a doc issue once the sample is updated.

[1] https://docs.wso2.com/display/EIP/Dynamic+Router
[2] https://docs.wso2.com/display/IntegrationPatterns/Dynamic+Router
[3] "Switch Mediator regex does not appear to recognise the use of 'get-property'"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Documentation has been updated with the correct configurations.
https://docs.wso2.com/display/IntegrationPatterns/Dynamic+Router
