### ISSUE TITLE
Add product deployment guidelines that match EI directory structure

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#1203]
**Description:**
Add product deployment guidelines that can be find in [1]  to match EI directory structure. Those information are not available in EI docs or Product Administration guide EI related sections

**Affected Product Version:**
WSO2 EI 6.1.x Documentation

[1] https://docs.wso2.com/display/ADMIN44x/Production+Deployment+Guidelines#ProductionDeploymentGuidelines-Runningtheproduct

**Comment by praneesha** [comment]
Assigning to Nilmini since this is related to administration topics of ESB/EI.

**Comment by praneesha** [comment]
Added this information in [1].

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product
