### ISSUE TITLE
Introducing transform.xslt.result.disableBuild property for XSLT mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1215]
**Description:**
With the fix at https://github.com/wso2/wso2-synapse/pull/878, we have introduced **transform.xslt.result.disableBuild** property for xslt mediator, which allows to escape building message at the xslt transform.

Synapse configuration
<property name="transform.xslt.result.disableBuild" value="true" scope="default" type="STRING" />
<xslt key="gov:/sample.xslt" target="XSLT_OUTPUT"/>

[1] - https://docs.wso2.com/display/EI620/XSLT+Mediator

**Affected Product Version:**
EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/1195

**Comment by praneesha** [comment]
Added this information in an info macro in the "Properties of the XSLT mediator" row in the table under the "UI Configuration topic" in [1].

[1] https://docs.wso2.com/display/EI620/XSLT+Mediator
