### ISSUE TITLE
Update docs with valid configs

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#1217]
**Description:**
Please update docs with correct config path. Refer admin services doc [1]. It having invalid paths and invalid configurations.

` <PRODUCT_HOME>/repository/conf/carbon.xml`

`<PRODUCT_HOME>/bin/wso2server.sh -DosgiConsole`

[1] https://docs.wso2.com/display/EI611/Calling+Admin+Services+from+Apps

**Suggested Labels:**
Doc

**Suggested Assignees:**
@praneesha 

**Affected Product Version:**
EI 6.x.x

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by nilminiwso2** [comment]
Fixed in EI 610 and 611.

[1] https://docs.wso2.com/display/EI611/Calling+Admin+Services+from+Apps
