### ISSUE TITLE
Creating Data Service using Management console is not working with JAVA 1.8.0_151

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1219]
**Description:**
When following the [tutorial](https://docs.wso2.com/display/EI611/Sending+a+Simple+Message+to+a+Datasource)  
under section
Exposing a data source through a data service
under creating the data service using the management console.
in step 1 and 2 when I create a data service with the name given in the tutorial it worked fine with JDK 1.8.0_121 & JDK 1.8.0_141 but with JDK 1.8.0_151 it is showing as "Error 403 - Forbidden"

Following warn is thrown in console

WARN - JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/ds/serviceDetailsProcessor.jsp, error:required token is missing from the request)

And in the documentation, asking to enter data service name twice ( n step 1 and 2) is a bit confusing.

**Suggested Labels:**
Bug, Documentation

**Affected Product Version:**
EI-6.1.0

**Steps to reproduce:**
Follow the tutorial linked above having  JDK as 1.8.0_151

**Comment by MiniMaw544** [comment]
Thanks for this report, I'm waiting for the issue

**Comment by Nirothipan** [comment]
This is due to a [known issue](https://bugs.openjdk.java.net/browse/JDK-8189789) in JDK 1.8.0_151.
Hence closing the issue.
