### ISSUE TITLE
[EI Analytics] Message flow trace properties view is not loaded

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1232]
**Description:**
If you are viewing a message flow through Analytics dashboard and when you click on a mediator in message flow to view the mediator trace properties, only the property titles are visible. Trace details about the mediator are not shown.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Go to analytics dashboard, click on a message id to view its message flow. Then click on a mediator in the message flow to view the trace properties of that mediator. The trace details are not loaded.

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/product-ei/pull/1233
