### ISSUE TITLE
Message broker - SSL JMS Reader hangs because of deadlock

### ISSUE THREAD

**Issue by riyafa** [wso2/product-ei#1246]
**Description:**
In the message broker the when a SSL JMS reader is used to read from one node of a 2 nodes' cluster with a 1000 reads per second and the server is restarted suddenly SSL exceptions occur due to handshake failure and the reader hangs due to a deadlock in andes:
[jms-test-threaddumps-20171023.txt](https://github.com/wso2/product-ei/files/1438155/jms-test-threaddumps-20171023.txt)

**Suggested Labels:**
Component/Broker,  Type/Bug

**Affected Product Version:**
MB 3.2.0 and upwards

**Steps to reproduce:**
N/A as it is deadlock scenario

**Related Issues:**
https://wso2.org/jira/browse/MB-1876

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/andes/commit/5962ced8bb818803600fb297dd84652508f8b5b5
