### ISSUE TITLE
Changing states of message processors in the UI does not reflect in the source view

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#1249]
**Description:**
When changing the state of a message processor in the UI and then when the source view is opened, the is.active parameter still shows the previous state. For example, if we activate the processor from the deactivated state and then if we check the source view, the is.active param is still false. If we save the config from the source view, the processor gets deactivated. 

**Affected Product Version:**
EI 6.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**    
Ubuntu 16.04

**Comment by Nirothipan** [comment]
Relates to https://github.com/wso2/product-ei/issues/1245.
