### ISSUE TITLE
[Doc] Error in Dynamic Load-balance Endpoint Configuration

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#1254]
**Description:**
In the EI documentation, the syntax of the configuration of dynamic load-balance endpoint is having the tag as 'dynamicLoadBalance'. But in the code, it is built as 'dynamicLoadbalance'. Therefore, following the syntax given in the documentation is throwing an error.

https://docs.wso2.com/display/EI611/Dynamic+Load-balance+Endpoint

https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointFactory.java

**Comment by praneesha** [comment]
Assigning to Nisrin since this is related to general topics of ESB/EI.

**Comment by Nashaath** [comment]
Fixed in all EI doc versions as well as in ESB doc versions 4.7.0 through 5.0.0.

**Comment by praneesha** [comment]
Fixed in all versions of WSO2 EI & WSO2 ESB docs.

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Dynamic+Load-balance+Endpoint
