### ISSUE TITLE
[Documentation] Symbolic link should be pointed to Analytics runtime

### ISSUE THREAD

**Issue by aparnawso2** [wso2/product-ei#127]
Current doc says it should be pointed to analytics home, in EI it should point to Analytics runtime. So these things should be documented.

e.g:
ln -s /home/debian/analytics2/wso2ei-6.0.0/wso2/analytics /usr/share/das/das_symlink

[1] https://docs.wso2.com/display/CLUSTER44x/Minimum+High+Availability+Deployment+-+DAS+3.1.0

**Comment by mpmunasinghe** [comment]
Also when running DAS analytics in a clustered environment along with providing the above symlink in <DAS_HOME>/repository/conf/analytics/spark/spark-defaults.conf 
carbon.das.symbolic.link /home/ubuntu/das/das_symlink/

Users should add the below system properties in wso2server.sh files to use the altered directory paths.
 
-Dcarbon.das.symlink.config.dir.path=<Symlink path>/conf
carbon.das.symlink.external.lib.dir.path=<Symlink path>/../../lib
carbon.das.symlink.dropins.dir.path=<Symlink path>/../../dropins
carbon.das.symlink.internal.lib.dir.path=<Symlink path>/../lib
das.symlink.components.repo=<Symlink path>/../components/plugins

**Comment by mpmunasinghe** [comment]
Alongside above parameters below line should be replaced 
export CARBON_CONFIG_DIR_PATH=$CARBON_HOME/conf 
with following in load-spark-env-vars.sh
export CARBON_CONFIG_DIR_PATH=<SYM_LINK_PATH>/conf

**Comment by Dilshani** [comment]
Im working with analytics cluster in EI 6.1.0 SNAPSHOT. Following fixes were not needed to run the analytic cluster:

Adding system properties in wso2server.sh files to use the altered directory paths.

-Dcarbon.das.symlink.config.dir.path=<SYM_LINK_PATH>/conf
-Dcarbon.das.symlink.external.lib.dir.path=<SYM_LINK_PATH>/../../lib
-Dcarbon.das.symlink.dropins.dir.path=<SYM_LINK_PATH>/../../dropins
-Dcarbon.das.symlink.internal.lib.dir.path=<SYM_LINK_PATH>/../lib

Adding followings in bin/load-spark-env-vars.sh
export CARBON_CONFIG_DIR_PATH=<SYM_LINK_PATH>/conf
-Ddas.symlink.components.repo=<SYM_LINK_PATH>/../components/plugins

**Comment by praneesha** [comment]
Added the above information in the note in step 4 under the "Required Configurations" section in [1].

[1] https://docs.wso2.com/display/CLUSTER44x/Minimum+High+Availability+Deployment+-+DAS+3.1.0
