### ISSUE TITLE
Incorrect behavior of call mediator in non-blocking mode

### ISSUE THREAD

**Issue by riyafa** [wso2/product-ei#1285]
**Description:**
The call mediator in the non-blocking mode behaves incorrectly by calling sequences that are not relevant in the message flow.

**Suggested Labels:**
ESB 4.9.0, bug/improvement

**Affected Product Version:**
ESB 4.9.0

**OS, DB, other environment details and versions:**    
Ubuntu 17.10 java 1.7

**Steps to reproduce:**

- Create a [proxy](https://github.com/wso2/product-ei/files/1456475/BFSFundsCheckEP.txt) that calls a [sequence](https://github.com/wso2/product-ei/files/1456508/GTSFundsCheckValidationErrorSequence.txt)
 that calls a [template](https://github.com/wso2/product-ei/files/1456487/someTemp.txt) which adds a message to a [message store](https://github.com/wso2/product-ei/files/1456489/queue.txt). Create  a custom [message processor](https://github.com/wso2/product-ei/files/1456492/GTSISDLogProcessor.txt) that calls [another sequence](https://github.com/wso2/product-ei/files/1456502/GTSISDLogSequence.txt) when a message was added to the message store. This sequence has a call mediator. 
- Add the following property to the `log4j.properties` file in `ESB_HOME/repository/conf` folder and restart the server: `log4j.category.org.apache.synapse.mediators=DEBUG`
-Invoke the proxy and see the logs.
-Change the call mediator to blocking and invoke the proxy and observe the logs
-Observe the logs for the same invocation (non-blocking) in a different version of ESB in (ESB 5.0.0 and ESB 4.8.1) and observe the logs.
- A difference is observed where a new call to the first sequence is made after termination of the 2nd sequence in ESB 4.9.0

**Comment by hastef88** [comment]
Already fixed in synapse master with : https://github.com/wso2/wso2-synapse/pull/640/files for versions >= ESB 5.0.0.
