### ISSUE TITLE
Introduce sap.escape.error.handling property for SAP implementation

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1290]
**Description:**
sap.escape.error.handling property was introduced to allow sending the original SAP error message without handling and throwing as an AxisFault.

**Suggested Labels:**
Implemented in https://github.com/wso2/carbon-mediation/pull/901

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/1282

**Comment by nilminiwso2** [comment]
Added the following content under the step for creating the 'Sender' proxy service (for BAPI and IDoc both):
"If you set the property shown below (use the Property mediator before the Send mediator in the above sequence), any business-level error messages that are sent back from the SAP endpoint will be successfully passed through the out flow sequence. Without this property, the business-level errors from SAP can get detected as faulty messages and passed to the Fault sequence.
```<property name="sap.escape.error.handling" scope="axis2" value="true"/>```"
