### ISSUE TITLE
Utils.checkForLog() of tests, accepts the timeout in seconds event though they are passed in millisconds

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#1301]
**Description:**
Utils.checkForLog() of tests, accepts the timeout in seconds event though they are passed in millisconds. This will increase the timout for a test case to complete in the case of a failure.

**Steps to reproduce:**
See method, 'checkForLog' of org.wso2.esb.integration.common.utils.Utils class. Need to look into other similar methods of the same class.

**Comment by abeykoon** [comment]
This is duplicated by https://github.com/wso2/product-ei/issues/1306
