### ISSUE TITLE
Readme files for each sample in git

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#131]
We need to organize the samples in git (perhaps into separate folders?) so that we have a separate readme file for each sample.

**Comment by himasha** [comment]
Moved samples into separate folders with blank readme files. https://github.com/wso2/product-ei/commit/c6b64bfd331caeb9bb9c7b8ed68fa321269d089c

**Comment by nandika** [comment]
It is better to document all samples in a single README file. That way it's easy to locate information. All samples will be moved to wso2ei-6.0.0/samples location
