### ISSUE TITLE
Unable to access VFS root on FTP location

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#1321]
**Description:**
VFS has an issue of accessing root location on FTP. This is happening due to a Nullpointer in the resolveFile method in [1]. The issue can be fixed by adding a null check for the filename. However, this should be fixed properly.

[1] - https://github.com/wso2/wso2-commons-vfs/blob/master/core/src/main/java/org/apache/commons/vfs2/provider/AbstractFileSystem.java

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 5.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ljuillerat** [comment]
Thanks Vinod,
Issue happens with cache disabled (NullFileCache).

**Comment by nandika** [comment]
Merged https://github.com/wso2/wso2-commons-vfs/pull/40
