### ISSUE TITLE
[Documentation] Remove additional note on receiving JSON response for REST resource

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1338]
**Description:**
In [1] we have mentioned that the possibility of receiving messages in JSON format is enabled by default in the ESB profile. However we still have a note on enabling a property for it as below. Need to verify and remove it. 

The possibility of receiving JSON responses is enabled by the following settings in the axis2.xml and axis2_client.xml files (stored in the <EI_HOME>/conf/axis2 directory):
<parameter name="httpContentNegotiation">true</parameter>

[1] https://docs.wso2.com/display/EI611/Using+JSON+Messages+with+RESTful+Services#UsingJSONMessageswithRESTfulServices-ReceivingaJSONresponsefromaRESTresource

**Affected Product Version:**
EI 6.0.0/EI 6.1.1

**Comment by nilminiwso2** [comment]
Verified.
Removed the note from EI 6.2.0, 6.1.1, 6.1.0, and DSS 3.5.1.
