### ISSUE TITLE
[Documentation] Invalid information on invoking POST/PUT Data as a Rest Resource

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1340]
**Description:**
Check section ' Invoking the REST resource  ' of [1]. For PUT/POST invocations we have mentioned about a <REST_RESOURCE> as well. We only need the <REST_PATH> and it doesn't make sense what we mean by <REST_RESOURCE> here. Please verify and fix. 

_HTTP POST: _post<RESOURCE_PATH>_<RESOURCE_NAME> (E.g. _postwso2_employee)
HTTP PUT: _put<RESOURCE_PATH><RESOURCE_NAME> (E.g. _putwso2_employee)_

[1] https://docs.wso2.com/display/DSS351/Exposing+Data+as+a+REST+Resource

**Affected Product Version:**

EI 6.1.1/6.0,DSS 3.5.1

**Comment by nilminiwso2** [comment]
Changed the content in DSS 351, EI 610, 611, and 620.

[1] https://docs.wso2.com/display/DSS351/Exposing+Data+as+a+REST+Resource
[2] https://docs.wso2.com/display/DSS351/Using+JSON+Messages+with+RESTful+Services
