### ISSUE TITLE
RabbitMQ prefetch count is not updated with the QoS value

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1342]
**Description:**
RabbitMQ consumer's channel prefetch count is not updated with the QoS value defined as follows in the RabbitMQ inbound endpoint.

` <parameter name="rabbitmq.channel.consumer.qos">1</parameter>`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
This is fixed by following RPs:
https://github.com/wso2-support/carbon-mediation/pull/105
https://github.com/wso2-support/carbon-mediation/pull/106

**Comment by abeykoon** [comment]
This is related to https://github.com/wso2/devstudio-tooling-ei/issues/98
