### ISSUE TITLE
[Documentation] E.I. Docs 'Working with Email Task' points at the wrong location to copy JAR files

### ISSUE THREAD

**Issue by viduras** [wso2/product-ei#1352]
**Description:**
'Working with Email Task' on the latest (6.1.1) E.I. Docs [1] point at the wrong location to copy the JAR files. Under 'Sample Email Configuration' - Task 2, it is mentioned to copy it to <EI_HOME>/wso2/lib where as it should be <EI_HOME>/lib
 
[1] https://docs.wso2.com/display/EI611/Working+with+the+Email+Task

**Suggested Labels:**
Docs, Priority/High, Component/BPS, Type/Bug, 

**Suggested Assignees:**

**Affected Product Version:**
E.I. 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Follow the current docs as is [1]. 

**Related Issues:**

**Comment by praneesha** [comment]
Corrected the folder path as follows in [1].

"Copy the following jar files into the <EI_HOME>/lib directory and restart the server. "

This is done in docs of all WSO2 EI versions.

[1] https://docs.wso2.com/display/EI611/Working+with+the+Email+Task
