### ISSUE TITLE
Reviewing PRs in product-ei repository

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#1353]
**Description:**
This task is to review PRs in the https://github.com/wso2/product-ei

The PR list is https://github.com/wso2/product-ei/pulls

**Comment by chanikag** [comment]
Merged following PRs

https://github.com/wso2/product-ei/pull/1320
https://github.com/wso2/product-ei/pull/1347
https://github.com/wso2/product-ei/pull/1346
https://github.com/wso2/product-ei/pull/1316
https://github.com/wso2/product-ei/pull/1163
https://github.com/wso2/product-ei/pull/1074
https://github.com/wso2/product-ei/pull/1070

Closed following PRs
https://github.com/wso2/product-ei/pull/1319

Reviewed following PRs
https://github.com/wso2/product-ei/pull/1318
https://github.com/wso2/product-ei/pull/1310

**Comment by sdkottegoda** [comment]
Closing since this task has been completed
