### ISSUE TITLE
Invalid profile path given for where Activiti database is stored

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1358]
**Description:**
Profile path provided in [1] is for Broker profile. This line needs to be updated to point to business-process profile.

> 
These databases are stored in the <EI_HOME>/wso2/broker/repository/database directory.

[1]https://docs.wso2.com/display/EI611/Changing+the+Default+Databases+for+BPMN+and+BPEL

**Affected Product Version:**
EI 6.1.1

**Comment by Nashaath** [comment]
Fixed this in EI 6.1.0, EI 6.1.1 and EI 6.2.0 doc spaces.
