### ISSUE TITLE
Three channels are created for a rabbitMQ inbound endpoint connection

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1360]
**Description:**
When we create a rabbitMQ inbound endpoint (https://docs.wso2.com/display/ESB490/Sample+907%3A+Inbound+Endpoint+RabbitMQ+Protocol+Sample), three channels are created for the connection. 
And, if we set the `<parameter name="rabbitmq.channel.consumer.qos">1</parameter>` parameter, prefetch count is updated only in one of these channels.

Before the fix https://github.com/wso2/carbon-mediation/pull/910, the prefetch count updated channel was not assigned as the queue's consumer's channel. With the fix,  prefetch count updated channel was assigned to the relevant consumer.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/910
