### ISSUE TITLE
[Documentation] Document the use of the new Synapse property synapse.commons.enableXmlNullForEmptyElement

### ISSUE THREAD

**Issue by chamilad** [wso2/product-ei#1364]
**Description:**
Document the use and the implementation details of the newly introduced Synapse property `synapse.commons.enableXmlNullForEmptyElement`.

Please find the implementation and usage in the wso2/wso2-synapse PR [1]

[1] - wso2/wso2-synapse#904

**Suggested Labels:**
Documentation

**Suggested Assignees:**
@VijithaEkanayake

**Comment by praneesha** [comment]
Assigning to Nisrin since this is related to general topics of ESB/EI.

**Comment by nilminiwso2** [comment]
Doc WIP: https://docs.wso2.com/display/EI6xx/Working+with+JSON+Message+Payloads#WorkingwithJSONMessagePayloads-Exceptions:JSONrepresentationofXMLelements

**Comment by nilminiwso2** [comment]
Updated from EI 6.2.0 upto EI 6.5.0.

Example: https://docs.wso2.com/display/EI6xx/Working+with+JSON+Message+Payloads
