### ISSUE TITLE
Support Message Resequencing  

### ISSUE THREAD

**Issue by pamod** [wso2/product-ei#1384]
**Description:**
When the messages are sent to the ESB in an unordered manner, it would be essential for the ESB to re-order the messages as elaborated in message re-sequencer EIP

http://www.enterpriseintegrationpatterns.com/patterns/messaging/Resequencer.html 

**Suggested Labels:**
Feature

**Suggested Assignees:**
Pamod

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by sdkottegoda** [comment]
Resolved by https://github.com/wso2/wso2-synapse/pull/968
