### ISSUE TITLE
Implement Resquencer EIP in WSO2 ESB/EI

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#1385]
**Description:**
We need to implement the Resequencer EIP in all WSO2 ESB and EI versions.

Currently, it is implemented only for WSO2 ESB 4.9.0 (through a WUM update) and can be used only via the Management Console.

We have [1] to provide the tooling support for it.

[1] https://github.com/wso2/devstudio-tooling-ei/issues/99
[2] https://docs.wso2.com/display/IntegrationPatterns/Resequencer

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Corresponding Tooling issue is addressed in https://github.com/wso2/product-ei/issues/2458
