### ISSUE TITLE
[Documentation]Better to  specify p2 repository url when installing HL7 features

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1426]
**Description:**
In [1] a link is provided for the user to select the necessary p2 repo url. This is not very helpful as the user needs to find out the appropriate url based on the version. It is better if we can add a note on the repository that is applicable for each version.

[1] https://docs.wso2.com/display/ESB490/Installing+the+HL7+Transport

**Affected Product Version:**
ESB/EI versions

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4228

**Comment by shavidissa** [comment]
Thank you for the suggestion! Update the docs with the repo URL so that they can copy it and add the feature.

[1] https://docs.wso2.com/display/ESB490/Installing+the+HL7+Transport
[2] https://docs.wso2.com/display/ESB500/Installing+the+HL7+Transport
