### ISSUE TITLE
Could not set value for rabbitmq.channel.consumer.qos in management cconsole

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#1429]
**Description:**
When adding/modifying RabbitMQ inbound endpoint through the management console, it doesn't support to set value for rabbitmq.channel.consumer.qos.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
esb-5.0.0, ei-6.0.0, ei-6.1.0, ei-6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create RabbitMQ inbound endpoint
Go to advance option
There is no provision to set value for rabbitmq.channel.consumer.qos

**Related Issues:**

**Comment by Nirothipan** [comment]
Will be tracked in https://github.com/wso2/product-ei/issues/2431
