### ISSUE TITLE
ESB endpoint timeout parameters are not working with Call mediator when blocking="true"

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-ei#1472]
**Description:**
ESB endpoint timeout parameters are not working with Call mediator blocking="true"

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
ESB 5.0.0  

**Steps to reproduce:**
Create an API.
Create a MockService as the endpoint and set a script as sleep(70000) to delay the response from the backend. 
Set the timeout of the endpoint to 60000ms.
Send a request.
A timeout occurs after 30 seconds, not after the 60 seconds.
It means endpoint timeout parameters are not working with call mediator blocking="true"

**Comment by GDLMadushanka** [comment]
fixed in https://github.com/wso2/wso2-synapse/pull/1331/files
