### ISSUE TITLE
[Documentation] Tuning the JMS Transport

### ISSUE THREAD

**Issue by fshomou** [wso2/product-ei#1476]
**Description:**
It seems that this documentation [1] is not up to date. 

You have mentioned that we have to change the values of the properties as follows after opening integrator.sh or integrator.bat file :
	     -Dlst_t_core=200
	     -Dlst_t_max=250 
	     -Dsnd_t_core=200
	     -Dsnd_t_max=250

**The error is : these properties are not available in integrator.sh or integrator.bat file**.

[1] https://docs.wso2.com/display/EI611/Tuning+the+JMS+Transport#TuningtheJMSTransport-IncreasethemaximumnumberofJMSproxies

**Suggested Labels:**
JMS
MessageBroker
Integrator
Docs

**Affected Product Version:**
EI-6.1.1

**Comment by praneesha** [comment]
Added the following tip in docs of all WSO2 EI versions.

"If you do not have the following properties in the integrator.sh or integrator.bat files, add them with the given values."

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Tuning+the+JMS+Transport
