### ISSUE TITLE
[Documentation][EI-BPS] Need to update the File location  of database cleanup scripts

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#148]
We need to update the new location of BPS cleanup scripts in the doc.

New location
wso2ei-6.0.0-m2/wso2/business-process/repository/resources/cleanup-scripts

**Comment by praneesha** [comment]
Updated the correct folder path in [1].

[1] https://docs.wso2.com/display/EI600/Database+Clean-up+Scripts
