### ISSUE TITLE
[Documentation] Update steps for monitoring JMX based Statistics in EI

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1480]
**Description:**
When following the steps given in [1] , server startup gives following error since analytics profile is not started. Therefore, we need to include a step to start the analytics profile before starting integrator profile for above purpose. 

**Affected Product Version:**
EI- 6.1.1

**Steps to reproduce:**
1. Follow step 1 of [1] enabling mediation statistics in synapse.properties.
2. Start integrator profile. 

[1] https://docs.wso2.com/display/EI611/Monitoring+JMX+Based+Statistics

**Comment by praneesha** [comment]
Added the following as step 2 and 3.

1. 

Start the Analytics profile of WSO2 EI. For more information, see Starting the Analytics profile.

Start the Integration profile of WSO2 EI. For more information, see Starting the Integration profile.

This is done in docs of all WSO2 EI versions. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Monitoring+JMX+Based+Statistics
