### ISSUE TITLE
Sequence Name and Error Sequence Name not validated when deploying rabbitmq inboundEndpoint via CAPP

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1509]
**Description:**
I created an rabbitmq Inbound endpoint like follows in the Dev Studio and could deploy it `successfully.

`<inboundEndpoint xmlns="http://ws.apache.org/ns/synapse" name="test2" sequence="" onError="" protocol="rabbitmq" suspend="false">`

Where as in Management console these are mandatory fields. Refer the screenshot attached.

**Suggested Labels:**
Bug, EI tooling

**Steps to reproduce:**
mentioned in the description.

![pic](https://user-images.githubusercontent.com/24619763/33830814-b8c575ee-de9b-11e7-8190-760a8b8f8a3b.png)

**Comment by prabushi** [comment]
We have already fixed this in https://github.com/wso2/devstudio-tooling-esb/pull/213 for the latest devstudio pack.

Related issue https://github.com/wso2/devstudio-tooling-ei/issues/61
