### ISSUE TITLE
Doc corrections for calling mysql functions in data service 

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1529]
**Description:**
Current mysql function configurations does not seem to work.
```
   <query id="NewfunctionQuery" useConfig="mynew">
      <sql>select myFunction('WSAS') as ABC</sql>
      <result element="wsas" rowName="wsas">
         <element column="ABC" name="n_param" xsdType="string"/>
      </result>
      <param name="imparam" sqlType="STRING"/>
   </query>
```

SQL query should be corrected as above in https://docs.wso2.com/display/EI611/Calling+MySQL+or+Oracle+Functions+in+a+Query

Column name should be equal to the resulting value of the function.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed in EI 6xx series and DSS 351
