### ISSUE TITLE
Description on EI 7 in README needs fixing 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1531]
**Description:**
It says 
_WSO2 EI is a unified distribution of Ballerina which works as a single runtime (Integrator) along with the optional runtime for Message Broker._

This is not what EI 7 is all about. Please pick the right message in discussion with product architects. 

We need to be clear on, what EI 7 is and what problem it is solving. 

**Suggested Labels:**

EI7

**Suggested Assignees:**

**Affected Product Version:**
EI 7
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
PR submitted for review,
#1541
