### ISSUE TITLE
Known issues link in README should be fixed

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1532]
**Description:**
Should be https://github.com/wso2/product-ei/labels/EI7
and not https://github.com/wso2/product-ei/issues

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
PR submitted for review,
#1541

**Comment by isudana** [comment]
Closing as PR is merged.
