### ISSUE TITLE
Errors in LICENSE.txt file

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1533]
**Description:**
Some of the jars listed in the LICENSE.txt file is not shipped with the pack. 
We need to generate the file right

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
PR submitted https://github.com/wso2/product-ei/pull/1543

**Comment by isudana** [comment]
PR merged.
