### ISSUE TITLE
slf4j and netty jars are duplicated in the pack 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1536]
**Description:**
Both broker and ballerina folders ship them. 

We should find a way to unify. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
This is mainly because ballerina and broker uses difference versions of jars and we have dedicated isolated class paths. 
Yes, we need to find a way to unify them.

**Comment by samisawso2** [comment]
We need to upgrade all these jas to latest and sync up

Thanks,
Samisa...


Samisa Abeysinghe

Chief Engineering and Delivery Officer

WSO2 Inc.
http://wso2.com
