### ISSUE TITLE
Crypto Notice section in README defines some Apache projects that may not apply

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1537]
**Description:**
I do not think EI 7 uses 
   Apache Rampart   : http://ws.apache.org/rampart/
   Apache WSS4J     : http://ws.apache.org/wss4j/

Also, do we use the following? 
   Apache Santuario : http://santuario.apache.org/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
PR submitted for review,
https://github.com/wso2/product-ei/pull/1541

**Comment by isudana** [comment]
Closing as PR is merged.
