### ISSUE TITLE
README needs to point to a doc link on broker

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-ei#1538]
**Description:**
I want to know how to configure broker yaml to tune to my needs. 
Where are the docs? 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
Added a link to message broker documentation. 
Created a new issue in message-broker to add documentation on tuning broker.xml.
