### ISSUE TITLE
Improve integrator and broker executable scripts

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#1544]
**Description:**
Need to improve integrator.sh and integrator.bat to handle unhappy paths (ex: no .balx file given)

Cleanup broker.sh file
Add missing broker.bat

**Suggested Labels:**
EI7

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
When no .balx file given it says

```
ballerina: no ballerina program given
Run 'ballerina help' for usage.
```

When ran "ballerina help" it did not work.

**Comment by isudana** [comment]
It is not correct to expose ballerina command line arguments through integrator.sh
