### ISSUE TITLE
Adding HTTP 2.0 support for WSO2 EI

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [wso2/product-ei#1545]
**Description:**

HTTP 2.0 specification support for WSO2 ESB

HTTP/2 is the newest version of hypertext transport protocol (HTTP) that is mainly focused on a more efficient use of network resources and a reduced perception of latency. Multiplexing, header compression, server push, stream priority, flow control and error handling are the core features of HTTP/2 protocol

To provide HTTP/2 support for WSO2 ESB, a TransportSender and an Inbound endpoint[1] that support HTTP/2 features have been implemented with test cases [2].

[1] https://github.com/wso2/carbon-mediation/pull/773
[2] https://github.com/wso2/product-esb/pull/632

**Comment by amerireza** [comment]
Which version does it affect?
