### ISSUE TITLE
HL7 Sends no ACK via HTTP

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [wso2/product-ei#1546]
**Description:**
We created a Proxy Service which only task is to receive HL7-Messages over HTTP (as XML), store them into a message queue and send an ACK back to the sender (before or after storing the messages in the queue, does not matter) . I configured the proxy as explained in the documentation.
I tried every possible setup of the following properties/parameters which are suggested to create ACK messages:
```
<property name="HL7_RESULT_MODE" value="ACK" scope="axis2"/>
<property name="HL7_GENERATE_ACK" value="true" scope="axis2"/>
<property name="HL7_APPLICATION_ACK" value="true" scope="axis2"/>

<parameter name="transport.hl7.AutoAck">true</parameter>
```
My current attempt is this:
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
name="HL7Store"
transports="http,hl7"
statistics="disable"
trace="disable"
startOnLoad="true">
<target>
<inSequence>
<property name="HL7_APPLICATION_ACK" value="true" scope="axis2"/>
<log level="full"/>
<property name="messageType" value="application/edi-hl7" scope="axis2"/>
<clone>
<target sequence="StoreSequence"/>
</clone>
</inSequence>
</target>
<parameter name="transport.hl7.AutoAck">false</parameter>
<parameter name="transport.hl7.Port">55557</parameter>
<parameter name="transport.hl7.ValidateMessage">false</parameter>
<description/>
</proxy>
```

Maybe I've just missed one step in my setup, but I tried nearly everything.

**Affected Product Version:**

ESB 4.8.1

**Comment by marcses** [comment]
Hi VijithaEkanayake,
try with `<property name="HL7_APPLICATION_ACK" value="false" scope="axis2"/>`
and
`<parameter name="transport.hl7.AutoAck">true</parameter>`
