### ISSUE TITLE
Support High availability for MailTo Transport listen proxies

### ISSUE THREAD

**Issue by VijithaEkanayake-zz** [wso2/product-ei#1547]
**Description:**

At the moment Only way is configure MailTo listener proxy in the single ESB instance. In the cluster environments, all proxies will consume the same message(Please check this) but the problem is high availability. 

We cannot overcome this by configuring listener proxy in the cluster setup because we need to use pinned server configuration to overcome the message duplication. So with the pinned server, we cannot achieve the high availability.

**Comment by manuelgomezsuarez** [comment]
@VijithaEkanayake
Same problem here, message duplication in the cluster environments.
Did you found any solution ?
