### ISSUE TITLE
Create separate Connection Factory for XA and NonXA

### ISSUE THREAD

**Issue by uthaiyashankar** [wso2/product-ei#1548]
**Description:**
Moved from https://wso2.org/jira/projects/MB/issues/MB-1936

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhawa-gunasekara** [comment]
This is fixed in https://github.com/wso2/product-ei/issues/847
