### ISSUE TITLE
High CPU usage in MB-3.1.0

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1551]
**Description:**
High CPU usage in MB-3.1.0 due to the used waiting strategy of Disruptor which is BlockingWaitingStrategy need to change it to SleepingBlockingWaitStrategy.

**Affected Product Version:**
MB-3.1.0

**Comment by a5anka** [comment]
This is fixed in https://github.com/wso2/andes/commit/f98f60c2a4e2a1eac128af53bccb9c494367d347
