### ISSUE TITLE
When starting wso2ei.6.1.1 as a windows service or via runConsole  a classnot found is thrown

### ISSUE THREAD

**Issue by shavantha** [wso2/product-ei#1552]
When starting wso2ei.6.1.1 as a windows service or via runConsole the below exception[2] is thrown. Reference[1].  I copied the wrapper.conf from <product-home>\bin\yajsw and attempted to start as run console but I see the errors as on[3].

**I got the below exception[2] once I copied the wrapper.conf from <product-home>\wso2\business-process\bin\yajsw**

[1]https://docs.wso2.com/display/EI611/Installing+as+a+Windows+Service

setup
OS:Windows 2012-R2
JAVA:JDK.1.8.0.101

[2] exception
==========
INFO|4552/3|"WSO2 Carbon"|17-12-19 03:03:21|    at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:36)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|Controller State: WAITING -> PROCESS_KILLED
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|restart process due to default exit code rule
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|restart internal RUNNING
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|set state RUNNING->RESTART
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|set state RESTART->RESTART_STOP
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|stopping process with pid/timeout 4552 45000
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|Controller State: PROCESS_KILLED -> USER_STOP
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|process exit code: 1
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:22|set state RESTART_STOP->RESTART_WAIT
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|set state RESTART_WAIT->RESTART_START
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|Controller State: USER_STOP -> UNKNOWN
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|Controller State: UNKNOWN -> WAITING
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|working dir C:\solution\wso2ei-6.1.1
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|create script: scripts/trayMessage.gv
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|found script scripts/trayMessage.gv
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|started process with pid 15656
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:27|set state RESTART_START->RUNNING
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|[INFO] StandardFileSystemManager - Using "C:\solution\wso2ei-6.1.1\..\tmp\vfs_cache" as temporary files store.
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|java.lang.ClassNotFoundException: org.wso2.carbon.server.Main
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|Trigger found: Exception in line:
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|platform null
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|java.lang.ClassNotFoundException: org.wso2.carbon.server.Main
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|start script scripts/trayMessage.gv
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|end script scripts/trayMessage.gv
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:65)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:50)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at java.lang.reflect.Method.invoke(Method.java:498)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:53)
INFO|15656/4|"WSO2 Carbon"|17-12-19 03:03:29|   at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:36)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|Controller State: WAITING -> PROCESS_KILLED
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|restart process due to default exit code rule
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|restart internal RUNNING
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|set state RUNNING->RESTART
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|set state RESTART->RESTART_STOP
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|stopping process with pid/timeout 15656 45000
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:29|Controller State: PROCESS_KILLED -> USER_STOP
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:30|process exit code: 1
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:30|set state RESTART_STOP->RESTART_WAIT
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|set state RESTART_WAIT->RESTART_START
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|Controller State: USER_STOP -> UNKNOWN
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|Controller State: UNKNOWN -> WAITING
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|working dir C:\solution\wso2ei-6.1.1
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|create script: scripts/trayMessage.gv
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|found script scripts/trayMessage.gv
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|started process with pid 16544
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:35|set state RESTART_START->RUNNING
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:36|[INFO] StandardFileSystemManager - Using "C:\solution\wso2ei-6.1.1\..\tmp\vfs_cache" as temporary files store.
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|platform null
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|java.lang.ClassNotFoundException: org.wso2.carbon.server.Main
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|Trigger found: Exception in line:
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|java.lang.ClassNotFoundException: org.wso2.carbon.server.Main
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|start script scripts/trayMessage.gv
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|end script scripts/trayMessage.gv
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:65)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:50)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at java.lang.reflect.Method.invoke(Method.java:498)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:53)
INFO|16544/5|"WSO2 Carbon"|17-12-19 03:03:37|   at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:36)
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|Controller State: WAITING -> PROCESS_KILLED
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|too many restarts
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|set state RUNNING->STATE_ABORT
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|process not in state RUNNING -> Delaying stop
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|set state STATE_ABORT->IDLE
INFO|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|Shutting down Wrapper
WARNING|wrapper|"WSO2 Carbon"|17-12-19 03:03:37|[id: 0x5a285661, /127.0.0.1:52741 => /127.0.0.1:15002] exception java.io.IOException: An existing connection was forcibly closed by the remote host

[3]Errors

INFO|wrapper|"WSO2 Carbon"|17-12-19 05:50:38|started process with pid 15156
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:50:38|set state STARTING->RUNNING
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:40|[INFO] StandardFileSystemManager - Using "C:\solution\wso2ei-6.1.1\wso2\tmp\vfs_cache" as temporary files store.
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:40|platform null
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:40|Controller State: WAITING -> ESTABLISHED
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:40|Controller State: ESTABLISHED -> LOGGED_ON
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: bcprov_jdk15on_1.56_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: BPMNAnalyticsUDF_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: bpmn_sample_jars_6.1.1_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: esapi_2.0.1_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: mysql_connector_java_5.1.42_bin_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: org.wso2.carbon.logging.propfile_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: process_tools_6.1.1_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: sample_utils_6.1.1_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:41|[2017-12-19 05:50:41,150] ERROR {org.wso2.carbon.server.extensions.DropinsBundleDeployer} -  Invalid Bundle found in the dropins directory: sqljdbc41_1.0.0.jar
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:45|log4j:WARN No appenders could be found for logger (com.atomikos.logging.LoggerFactory).
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:45|log4j:WARN Please initialize the log4j system properly.
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:50:45|log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:46|Shutting down Wrapper
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:46|set state RUNNING->STATE_USER_STOP
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:46|stopping process with pid/timeout 15156 45000
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:52:46|Controller State: LOGGED_ON -> USER_STOP
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:52:46|Controller State: USER_STOP -> WAITING_CLOSED
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:52:46|wrapper manager received stop command
INFO|15156/0|"WSO2 Carbon"|17-12-19 05:52:50|Controller State: WAITING_CLOSED -> PROCESS_KILLED
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:50|set state STATE_USER_STOP->IDLE
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:50|shutdown wrapper due to exit code rule
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:51|process exit code: 0
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:51|set state IDLE->STATE_SHUTDOWN
INFO|wrapper|"WSO2 Carbon"|17-12-19 05:52:51|set state IDLE->STATE_SHUTDOWN

PS C:\solution\yajsw-stable-11.03\bat>

**Comment by milindaperera** [comment]
already reported and fixed in https://github.com/wso2/product-ei/issues/1683
