### ISSUE TITLE
Unable to add Conditional Router Mediator

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-ei#1553]
**Description:**
When trying to add a conditional route mediator via the web UI, it will throw the below exception.

```
[2017-12-19 11:00:37,096] [EI-Core] ERROR - ApplicationDispatcher Servlet.service() for servlet bridgeservlet threw exception
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [14] in the generated java file: [/home/sachith/Issues/Issue_GOTWOGROUPDEV-46/wso2ei-6.1.1.1513335096103/wso2ei-6.1.1/wso2/lib/tomcat/work/Catalina/localhost/_/proxytemp/hc_185093707/org/apache/jsp/conditionalroute_002dmediator/update_002dmediator_jsp.java]
Only a type can be imported. org.wso2.carbon.mediator.router.RouteMediator resolves to a package
```

**Suggested Labels:**
Bug

**Affected Product Version:**
EI-6.1.1 

**Steps to reproduce:**
When trying to add a Conditional Router Mediator using the web UI, it will generate the above-mentioned error.

**Comment by sameeragunarathne** [comment]
This mediator is deprecated[1] hence closing.
[1] - https://docs.wso2.com/display/EI650/Conditional+Router+Mediator
