### ISSUE TITLE
BPS getInstanceInfo admin service return 500 when processID doesn't exist

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#1558]
**Description:**
Invoking BPS getInstanceInfo admin service with processId which doesn't exist return 500.

```
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>soapenv:Server</faultcode>
            <faultstring>unknown</faultstring>
            <detail/>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
BPS 3.5.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Set `<HideAdminServiceWSDLs>false</HideAdminServiceWSDLs>` in `wso2bps-3.5.1/repository/conf/carbon.xml`
- Start the server
- Open https://localhost:9443/services/InstanceManagementService?wsdl in SoapUI
- Invoke getInstanceInfo with processId set to some random number
- This will return HTTP 500 with axis fault. It doesn't give a proper error message.
- No error logs in the wso2carbon.log
- This should be fixed with proper error message and correct HTTP status code

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/carbon-business-process/pull/493
