### ISSUE TITLE
OOM issue when cache mediator is used with ESB-4.8.1

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1571]
**Description:**
OOM issue when cache mediator is used with ESB-4.8.1 this is occurring because of building the OMElements when transforming json to xml while caching. 

**Affected Product Version:**
ESB-4.8.1

**Steps to reproduce:**
Send a request, for which back end responds with a JSON payload of size 40mb. In few requests the OOM exception occurs.

**Related Issues:**
ESBJAVA-5221

**Comment by Drifftr** [comment]
This is fixed and added to commons caching 4.0.3 support branch with svn revisions 55231,55232
