### ISSUE TITLE
Error in broker while running async message patterns sample

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#1592]
**Description:**
Please refer https://github.com/wso2/message-broker/issues/101

**Suggested Labels:**
EI7

**Suggested Assignees:**

**Affected Product Version:**
EI 7.0.0 m4
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Follow steps in Topics usage scenario of [1].

**Related Issues:**
This depends on https://github.com/wso2/message-broker/issues/101

[1] https://github.com/wso2/product-ei/blob/7.0.x/samples/async-messaging-patterns/README.md

**Comment by a5anka** [comment]
Please use a message-broker version equal or greater than v1.0.46 to resolve this.
