### ISSUE TITLE
Unable to update 'maximum redelivery attempts' value of message processor

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1609]
**Description:**
When 'maximum redelivery attempts' field of message processor is updated/saved, it still displays the default value 4. 

**Affected Product Version:**
EI 6.1.1

**Steps to reproduce:**
1. Create sample message store through management console.
2. Add a new message processor.
3. Update field 'maximum redelivery attempts' under additional parameters. (Both source/design view gives the same result)
4. Save the configuration and click on edit to view the created message processor configurations. Value of step 3 is updated back to '4'.

**Comment by abeykoon** [comment]
Checked the code. 
Backend saves and returns the re-delivery attempts correctly. 
But in  the UI at [1] it is not set correctly. 

[1]. https://github.com/wso2/carbon-mediation/blob/master/components/mediation-ui/org.wso2.carbon.message.processor.ui/src/main/resources/web/message_processor/manageMessageForwardingProcessor.jsp

**Comment by Nirothipan** [comment]
This issue is no longer reproducible in EI 6.1.1 update 23.

Fixed with https://github.com/wso2/carbon-mediation/pull/824/files

https://wso2.org/jira/browse/ESBJAVA-5090
