### ISSUE TITLE
VFS Transport documentation page points to links in ESB 5.0.0 documentation samples

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#1614]
**Description:**
VFS Transport page from EI 6.1.1 documentation https://docs.wso2.com/display/EI611/VFS+Transport should point to relevant samples from EI 6.1.1 samples. However, the links points to ESB 5.0.0 samples.

**Suggested Labels:**
Documentation

**Affected Product Version:**
EI 6.1.1

**Comment by Nashaath** [comment]
Fixed the sample links to point to EI 6.1.1 sample pages.
