### ISSUE TITLE
transport.jms.CacheLevel Parameter Default value should be 0 (NONE)

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1615]
**Description:**
The default value of the transport.jms.CacheLevel should be 0 (NONE cache)[1]. Currently its stated as 3 (CONSUMER cache). Further 0 - None should be added as a possible value to the table.

[1]. https://docs.wso2.com/display/EI611/JMS+Inbound+Protocol

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nashaath** [comment]
Fixed this in all EI doc versions as well as in ESB 5.0.0 and ESB 4.9.0 doc versions.

**Comment by praneesha** [comment]
Updated the "possible Values" and "Default Value" fields of the "transport.jms.CacheLevel" row in the table under "JMS inbound endpoint parameters" section.

This is done in docs of all WSO2 EI & ESB versions. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/JMS+Inbound+Protocol
