### ISSUE TITLE
[Docs] libs needs to copy when configure EI with Tibco EMS 8.4 version

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#1627]
**Description:**
I tried to integrate the EI with Tibco EMS 8.4 version. I followed the doc in [1]. According to the 3rd step following jar files has to be copied to $EI-HOME/extensions folder.

- tibcrypt.jar
- tibjms.jar
- tibjmsadmin.jar
- tibjmsapps.jar
- tibrvjms.jar

But for 8.4 version the tibcrypt.jar is not available, but instead jms-2.0.jar has to be coped. Therefore the jars list is,
- jms-2.0.jar
- tibjms.jar
- tibjmsadmin.jar
- tibjmsapps.jar
- tibrvjms.jar

[1] https://docs.wso2.com/display/EI611/Configure+with+Tibco+EMS

**Comment by nilminiwso2** [comment]
Added the following to the docs:
"tibcrypt.jar or jms-2.0.jar (If Tibco EMS 8.4 version is used, be sure to use jms-2.0.jar)"
Please reopen, if anything this is incorrect.
