### ISSUE TITLE
Incorrect transport names getting listed in the UI

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#1630]
**Description:**
When creating a proxy service, if we give some incorrect name for the transports attribute, it's anyway getting listed when switching to design view. When saving the proxy with that incorrect value, the proxy is not marked as faulty. It's getting deployed. 

**Steps to reproduce:**
1. Create a custom proxy service in the management console.
2. Switch to source view and give some incorrect value for the transport attribute and save the proxy.
3. Now go to the design view of the proxy. The incorrect transport name will be listed under transports.

**Comment by Nirothipan** [comment]
Here even though the proxy is getting saved and deployed successfully, it only has the supported transports. We need to validate this when saving.
