### ISSUE TITLE
Product EI JMS/VFS Inbound test cases are failing intermittently 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#1649]
**Description:**
JMS/VFS Inbound test cases are failing intermittently  under EI Integration profile tests. 

**Suggested Labels:**
EI 6

**Affected Product Version:**
EI 6.1.1 Update 15

**OS, DB, other environment details and versions:**    

Jenkins test environment 

**Steps to reproduce:**

Run the test suite a several times to verify. Failures are intermittent and no pattern is found. Reading logs to verify the test is passed might be a reason.

**Comment by a5anka** [comment]
They are not failing anymore after the fixes.
