### ISSUE TITLE
Mediation continues even after a call mediator defined with an invalid endpoint is executed

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#1651]
**Description:**
When having the OUT_ONLY property set to true and when defining a call mediator with an invalid endpoint, the mediators defined after the call mediator are getting executed. But it should not happen. The mediation should stop then and there if no error handling is defined for invalid endpoint.

**Steps to reproduce:**
1. Create a proxy service.
2. Set OUT_ONLY to true.
3. Define a call mediator with an invalid address endpoint.
4. Define a log mediator after the call mediator.

Now call the proxy. The log mediator will be executed and the log message will be printed.

**Comment by Nirothipan** [comment]
Is call mediator in blocking mode or non-blocking?

**Comment by ThishaniLucas** [comment]
Non-blocking
