### ISSUE TITLE
In Endpoint Error Handling need to change the default value of responseAction

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1654]
**Description:**
In Endpoint Error Handling need to change the default value of responseAction into Never Timeout since it is listed as "Never" in tooling.

**Affected Product Version:**
EI-6.2.0

**Comment by praneesha** [comment]
Updated the sample configuration with the following:

 <responseAction>discard|fault|never</responseAction>

Also, updated the Values, Default and  Description fields of the "responseAction" row in the table under "Timeout" settings".

This is done in al versions of WSO2 ESB & EI docs. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Endpoint+Error+Handling
