### ISSUE TITLE
[Documentation] Obsolete content is in documentation 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#1657]
**Description:**
According to [1] and [2], service level configurations are not in EI web UI now. 
They came from Carbon kernel in earlier versions.
Thus the documentation pages are obsolete. 

[1]. https://docs.wso2.com/display/EI611/Using+the+Service+Dashboard
[2]. https://docs.wso2.com/display/EI611/Reliable+Messaging

**Affected Product Version:**

EI 6.1.1

**OS, DB, other environment details and versions:**    

N/A

**Steps to reproduce:**

N/A

**Related Issues:**

N/A

**Comment by nilminiwso2** [comment]
Fixed in EI 6.x.x.
Separate git issue created to 'Remove 'wso2carbon-sts' service': https://github.com/wso2/product-ei/issues/1670
