### ISSUE TITLE
Remove transport.jms.SessionTransacted property from JMS Inbound endpoint docs

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1659]
**Description:**
Remove transport.jms.SessionTransacted property from JMS Inbound endpoint docs[1]. Since this property is deprecated[2] in next versions. This is replaced by SESSION_TRANSACTED value for transport.jms.SessionAcknowledgement property. 
Issue  -https://github.com/wso2/product-ei/issues/1453

[1]. https://docs.wso2.com/display/EI611/JMS+Inbound+Protocol
[2]. https://github.com/wso2/product-ei/issues/1612

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Removed the property from both the table and the Synapse configuration given in the doc.

The property has been removed from WSO2 EI 6.2.0 onwards. Therefore, did this in docs of WSO2 EI 6.2.0 and above. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/JMS+Inbound+Protocol
