### ISSUE TITLE
XPATH expression not working which is mentioned in the doc.

### ISSUE THREAD

**Issue by Bhashinee** [wso2/product-ei#1669]
**Description:**
In this document [1] , it is given that $body/getQuote refers to the first getQuote element in a SOAP body. And 
<property xmlns:m0=" http://services.samples " name="stock prop" expression="$body/m0:getQuote"/>
can be used to retrieve the first element. 
It should be corrected as 
<property xmlns:m0=" http://services.samples " name="stock prop" expression="$body//m0:getQuote"/>

After '$body' there should be two '//' instead of one '/'.

[1] https://docs.wso2.com/display/EI620/Synapse+XPath+Variables 

**Suggested Labels:**
EI 

**Steps to reproduce:**

Run below API.

`<api xmlns="http://ws.apache.org/ns/synapse" name="test" context="/xpath">`
  `<resource methods="POST GET">`
     `<inSequence>`
         `<payloadFactory media-type="xml">`
            `<format>`
               `<soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">`
                  `<CUSTOMER_EMAIL xmlns="">bhashinee@wso2.com</CUSTOMER_EMAIL>`
               `</soapenv:Body>`
            `</format>`
            `<args/>`
         `</payloadFactory>`
         `<log level="full"/>`
         `<property xmlns:m0="http://ws.wso2.org/dataservice" name="EmailID" expression="//m0:CUSTOMER_EMAIL"/>`
         `<log level="custom">`
            `<property name="***********Body********" expression="$body"/>`
            `<property name="EmailIDNotWorking" expression="$body/CUSTOMER_EMAIL/text()"/>`
`<property name="EmailIDWorking" expression="$body//CUSTOMER_EMAIL/text()"/>`
         `</log>`
      `</inSequence>`
   `</resource>`
`</api>`

**Comment by praneesha** [comment]
Fixed the 3 instances under the "$body" section in docs of all WSO2 EI & ESB versions.

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Synapse+XPath+Variables#SynapseXPathVariables-$body
