### ISSUE TITLE
[Doc] Incorrect InsertEmployeeQuery given for Handling Distributions page of Data Services

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1675]
**Description:**
Query provided in "InsertEmployeeQuery" of [1] is incorrect, as the value count does not match the column count. Need to be updated to below.

insert into Employees (employeeNumber,firstName,lastName,email,jobtitle,OfficeCode) values(:employeeNumber,:firstName,:lastName,'test','test',:OfficeCode)

[1] https://docs.wso2.com/display/EI611/Handling+Distributed+Transactions

**Affected Product Version:**
EI-6.1.1

**Comment by nilminiwso2** [comment]
Tested and Fixed in EI and DSS 3.5.1.
