### ISSUE TITLE
[Doc] Incorrect properties specified for XA datasource definition

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1678]
**Description:**
In [1] under 'Adding the datasources to a data service' section it suggests to add a property named 'USER' . Data-service deployment fails with an error where a setter method for 'USER' cannot be found.

`<property name="user">root</property>`

[1] https://docs.wso2.com/display/EI611/Handling+Distributed+Transactions

**Affected Product Version:**
EI-6.1.1

**OS, DB, other environment details and versions:**    
MYSQL

**Steps to reproduce:**
1. Create XA datasource as mentioned in [1].
2. Add property 'USER' as mentioned and deploy the dataservice. 

[1] https://docs.wso2.com/display/EI611/Handling+Distributed+Transactions

**Comment by nilminiwso2** [comment]
Tested and Fixed in EI and DSS 3.5.1.
