### ISSUE TITLE
When running BPS profile in EI 6.1.1 as a windows service a 'java.lang.ClassNotFoundException' occurs

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-ei#1683]
**Description:**
When running BPS profile in EI 6.1.1 as a windows service a 'java.lang.ClassNotFoundException' occurs as the relative path of the property 'wrapper.java.additional.32 = -Dcarbon.dropins.dir.path=${carbon_home}\\..\\..\\dropins ' is misconfigured in wrapper.conf file inside <EI_home>/wso2/business-process/bin/yasjw folder.

**Affected Product Version:**
EI-6.1.1 WUM updated pack (wso2ei-6.1.1.1515305858299.zip)

**OS, DB, other environment details and versions:**    
Windows12
JDK 1.8.x

**Comment by milindaperera** [comment]
Already fixed in https://github.com/wso2/product-ei/commit/1a0e82d6fbb63f3a00020eec0eac15ec6c00ac30
