### ISSUE TITLE
Throttle mediatr is not aware of "X-Forwarded-For" HTTP header in Load Balanced Requests.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1692]
**Description:**
When throttling policies are applied for mediator based on IPs, in cluster setups, the mediator is not aware of "X-Forwarded-For" HTTP header.
 The [remoteIP ](https://github.com/wso2/wso2-synapse/blob/master/modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java#L340)obtained here is of LB's Ip but not of actual client IP. We need to improve this.

**Suggested Labels:**
Improvements

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
What would be a throttling policy would look like with X-forwarded herders?

**Comment by vinok88** [comment]
There is no difference, we need to identify the correct client IP. In the existing code, it uses the remote address, which causes not to evaluate the actual client IP in the policy when used with another proxy/LB. We need to consider the x-forwarded headers if available as that gives the original client IP.
