### ISSUE TITLE
[Doc][DSS] Incorrect statement under the query mode section is DSS

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-ei#1694]
**Description:**
The statement below is vary vague and incorrect. It says you cannot use SQL statements to query data and in the next sentence it says you can retrieve data. 

"If query mode is disabled for the spreadsheet, **you cannot use SQL statements to query data in the excel sheet.** Note that in non-query mode, you can only get data from the sheet and you cannot insert, update or modify any data"

Doc link  - https://docs.wso2.com/display/DSS351/Exposing+Excel+Data+as+a+Data+Service#ExposingExcelDataasaDataService-Ifquerymodeisdisabled

**Suggested Labels:**
Bug, Doc

**Affected Product Version:**
DSS 3.5.1

**Comment by nilminiwso2** [comment]
Fixed in DSS 3.5.1, EI 6.0.0, EI 6.1.0, EI 6.1.1, and EI 6.2.0.
Please reopen if anything is unclear. Thanks!
