### ISSUE TITLE
Throttle policy editor is not loading to define in-lined policy

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1699]
**Description:**
Unable to load the throttle policy editor in Throttle mediator

**Affected Product Version:**
EI 6.1.1 - wso2ei-6.1.1.1515433152613.zip

**OS, DB, other environment details and versions:**    
Ubuntu 15.10
JDK 1.8
DB - H2

**Steps to reproduce:**
1. Create a proxy service
2. Include throttle mediator 
3. Select In-lined policy and click 'Throttle policy Editor'

**Observations**
Policy Editor not loading.

![screenshot from 2018-01-10 15-19-00](https://user-images.githubusercontent.com/14962228/34773917-5e179aaa-f633-11e7-8e58-1446a9c52f93.png)

**Comment by SuperMasterBlasterLaser** [comment]
I have the same exact error.

**Comment by Nirothipan** [comment]
This is not reproducible in EI-6.1.1 update 24.

**Comment by Nirothipan** [comment]
This is not reproducible with 6.2.0 SNAPSHOT ( 15/03/2018 )
![image](https://user-images.githubusercontent.com/24619763/37463125-41f805a2-287a-11e8-82ae-fa096351f39a.png)

**Comment by Nirothipan** [comment]
FIxed with https://github.com/wso2/product-ei/issues/1784
