### ISSUE TITLE
Add latest Soap connector to the EI-7

### ISSUE THREAD

**Issue by erandacr** [wso2/product-ei#1707]
**Description:**
Soap connector 0.95.1 contains new features and bug fixes, include it into EI-7 distribution

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by riyafa** [comment]
Resolved in https://github.com/wso2/product-ei/pull/1701 and https://github.com/wso2/product-ei/pull/1704
