### ISSUE TITLE
Data Service Password Secret Alias Configuration Doesn't Get populated in Management Console when created  in dss tooling.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1724]
**Description:**
When creating a data service with dss tooling, if we create the password with secret Alias it is not getting populated in the management console.

**Suggested Labels:**
EI 6.1.1

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
This was introduced for the devstudio fix provided for https://github.com/wso2/devstudio-tooling-ei/issues/109
