### ISSUE TITLE
Add ESB Artifact Deployment order to docs

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1727]
**Description:**
When deploying a CApp ESB artifacts are deployed in the order below.

1.  Local_entry_type
2.  Endpoint_type
3.  Sequence_type
4.  Message_store_type
5.  Template_type
6.  Proxy_service_type
7.  Task_type
8.  Event_source_type
9.  Message_processor_type
10.  Api_type
11.  Inbound_endpoint_type
12.  Other_types

Its better if we can add this order to the docs as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Added a note in [1] with this information.

[1] https://docs.wso2.com/display/ADMIN44x/Deploying+Composite+Applications+in+the+Server
