### ISSUE TITLE
$ctx variable with enrich mediator is not working properly 

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-ei#1728]
**Description:**
When using the $ctx variable to get the property value with the enrich mediator, It will be modified the proxy definition while invoking that proxy service. 

**Suggested Labels:**
ESB, EI

**Affected Product Version:**
ESB 5.0.0, EI 6.1.1

**Steps to reproduce:**
You could able to reproduce this issue by using the below sample proxy service and the request payload. Then, you can see that proxy definition will change when invoked that proxy service. 

***Proxy service*** -
```<?xml version="1.0" encoding="UTF-8"?>```
```<proxy xmlns="http://ws.apache.org/ns/synapse"```
       ```name="test"```
       ```startOnLoad="true"```
       ```statistics="disable"```
       ```trace="disable"```
       ```transports="http,https">```
   ```<target>```
      ```<inSequence>```
         ```<property name="payload" scope="default">```
            ```<response xmlns="">```
               ```<xml>text</xml>```
               ```<xml>text</xml>```
            ```</response>```
         ```</property>```
         ```<foreach expression="$body/request/*">```
            ```<sequence>```
               ```<enrich>```
                  ```<source clone="true" type="body"/>```
                  ```<target action="child" xpath="$ctx:payload"/>```
               ```</enrich>```
               ```<log level="full">```
                  ```<property expression="$ctx:payload" name="payload"/>```
               ```</log>```
            ```</sequence>```
         ```</foreach>```
         ```<enrich>```
            ```<source clone="true" property="payload" type="property"/>```
            ```<target type="body"/>```
         ```</enrich>```
         ```<respond/>```
      ```</inSequence>```
   ```</target>```
   ```<description/>```
```</proxy>```

***Request payload*** -

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">`
   `<soapenv:Body>`
   `<request>`
   `<xml>text1234444</xml>`
   `</request>`
   `</soapenv:Body>`
`</soapenv:Envelope>`

***Output*** - Has changed the proxy definition as follows

`<?xml version="1.0" encoding="UTF-8"?>`
`<proxy xmlns="http://ws.apache.org/ns/synapse"`
       `name="test"`
       `startOnLoad="true"`
       `statistics="disable"`
       `trace="disable"`
       `transports="http,https">`
   `<target>`
      `<inSequence>`
         `<property name="payload" scope="default">`
            `<response xmlns="">`
               `<xml>text</xml>`
               `<xml>text</xml>`
               `<xml>text1234444</xml>`
               `<xml>text1234444</xml>`
               `<xml>text1234444</xml>`
            `</response>`
         `</property>`
         `<foreach expression="$body/request/*">`
            `<sequence>`
               `<enrich>`
                  `<source clone="true" type="body"/>`
                  `<target action="child" xpath="get-property('payload')"/>`
               `</enrich>`
               `<log level="full">`
                  `<property expression="$ctx:payload" name="payload"/>`
               `</log>`
            `</sequence>`
         `</foreach>`
         `<enrich>`
            `<source clone="true" property="payload" type="property"/>`
            `<target type="body"/>`
         `</enrich>`
         `<respond/>`
      `</inSequence>`
   `</target>`
   `<description/>`
`</proxy>`

Please invoke the proxy multiple times and you can reproduce the issue. Then you can see that proxy definition also change while invoking the proxy service. But, if we used the get-property(property_name) method instead of the $ctx: property_name, then the output will come as expected manner.

**Comment by Nirothipan** [comment]
I could observe the same
