### ISSUE TITLE
Allow retrieving the values of multiple HTTP headers, in the mediation sequence, when they have the same header name

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#1733]
**Description:**
Currently a transport header can be retrieved in the mediation sequence as follows
eg: <property expression="$trp:Set-Cookie" name="CookieHeader" scope="default" type="STRING" xmlns:ns="http://org.apache.synapse/xsd"/>

But if we have multiple headers with the same name, there is no way to retrieve all of them. Only one of the headers can be retrieved. 
This behavior is not correct and is unpredictable. Currently the solution is to use a custom mediator for this. But this should be inherently supported.

**Comment by GDLMadushanka** [comment]
According to the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) we need to send header values in a comma-separated list

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]

**Comment by GDLMadushanka** [comment]
Class mediator solution
org.apache.axis2.context.MessageContext axis2MessageContext = ((Axis2MessageContext) messageContext).getAxis2MessageContext();
axis2MessageContext.getProperty("EXCESS_TRANSPORT_HEADERS")
