### ISSUE TITLE
Write a sample for a scenario where it is required to retrieve multiple headers which have the same name, in the mediation sequence

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#1734]
**Description:**
An example use case would be as follows. There are two DSS nodes fronted by an LB. Boxcarring is enabled. ESB initiates boxcarring session. Here, as all the requests belonging to same boxcarring session should be sent to the same DSS nodes, sticky sessions need to be enabled. Therefore, ESB needs to keep track of the session stickiness cookie sent by the LB and the JSESSIONID cookie sent by DSS in order to maintain the boxcarring session. Since it is not possible to retrieve multiple headers with the same name inside ESB mediation sequence, it is required to write a custom mediator to achieve the requirement.

**Comment by GDLMadushanka** [comment]
can use this [blog](http://lahirumadushankablog.wordpress.com/2019/09/14/handling-identical-transport-headers-in-wso2-ei/)
