### ISSUE TITLE
Check the artifact type in CApps when undeploying 

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-ei#1737]
**Description:**
According to [1], when deploying artifacts with CApps, the artifacts type will be resolved. So, we can declare the artifacts in any random order and it will deploy them in the correct order. But, this feature is not available for undeploying the artifacts. The solution we have currently will only undeploy them in the reverse order. Therefore, we cannot declare them in any random order, so the feature in [1] is not useful. Therefore, will need an ordering mechanism as done in [1] for undeploying artifacts.

[1] https://github.com/wso2/carbon-mediation/pull/900

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB, EI

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by milindaperera** [comment]
related : https://github.com/wso2/product-ei/issues/1261
