### ISSUE TITLE
[Doc Improvements ] - Setting Input and output types for Data Mapper Mediator.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1741]
**Description:**
- Currently in https://docs.wso2.com/display/EI611/Using+Data+Mapper+Mediator+in+the+ESB+Profile
we mention "If your mapping failed during runtime, check if the input type and output type are set correctly in the mediator configuration." under step 5 of Deploying the configurations in an indirect way.
This needs to be moved to the previous block and to be mentioned explicitly as a step.

**Suggested Labels:**
Documentation

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/113

**Comment by praneesha** [comment]
Removed this step from the "Deploying the configurations" section and added it as step 20 under the "Creating the ESB configuration project" section.

This is done in docs of WSO2 Ei 6.x.x and 6.1.1. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Using+Data+Mapper+Mediator+in+the+ESB+Profile
