### ISSUE TITLE
[Doc] Missing Documentation content related to transports

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1744]
**Description:**
1. Default number of HTTP/HTTPS listeners in Passthrough transport: 4 listeners including 2 PassThroughHttpListener and 2 PassThroughHttpSSLListener threads [1]. We can configure the number of listeners at  passthru-https.properties file using io_threads_per_reactor property. There is no maximum limit to the number of listeners in code level.
Total number of listener threads will be the double of the value defined for io_threads_per_reactor property, because there will be same number of PassThroughHttpListener and PassThroughHttpSSLListener threads created at the server.

2. At [2], if we define -Dlst_t_core values at the startup script, defined values will be applied as System Properties. However lst_t_core, lst_t_max, snd_t_core and snd_t_max values are only used by the JMS and NHTTP transports

[1] https://docs.wso2.com/display/EI611/PassThrough+Transport
[2] https://docs.wso2.com/display/EI611/Tuning+the+JMS+Transport#TuningtheJMSTransport-IncreasethemaximumnumberofJMSproxies

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you! 
Update the content.

[1] https://docs.wso2.com/display/EI611/Tuning+the+JMS+Transport
[2] https://docs.wso2.com/display/EI611/PassThrough+Transport - Configuring listners
