### ISSUE TITLE
TryThisService gives an Error

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1745]
**Description:**
When using the TryThisService option it gives following error
"Uncaught ReferenceError: editAreaLoader is not defined
    at HTMLDocument.<anonymous> (Version:882)"

![screenshot from 2018-01-17 15-27-22](https://user-images.githubusercontent.com/8380732/35036639-f7bf1fea-fb9a-11e7-83ef-fa939ce1bab8.png)

**Affected Product Version:**
EI-6.2.0
**OS, DB, other environment details and versions:**    
firefox-57.0.4
**Steps to reproduce:**
Use the TryThisService and it will load a corrupted ui.

**Related Issues:**
https://github.com/wso2/product-ei/issues/1605

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/carbon-commons/pull/291
