### ISSUE TITLE
Unable to create RabbitMQ inbound endpoint in developer studio

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#1751]
**Description:**
Unable to save an inbound endpoint which gives a NPE with no additional details.

**Affected Product Version:**
EI- 6.1.1

**Steps to reproduce:**
1. Create a Rabbitmq inbound endpoint from tooling.
2. Add a sequence for 'onError' block and try to save it.

**Comment by Nirothipan** [comment]
This issue not reproducible in fresh setup.
