### ISSUE TITLE
Implement Http to Data Abstraction using a connector

### ISSUE THREAD

**Issue by erandacr** [wso2/product-ei#1752]
**Description:**
Implement Http-to-Data abstraction that is similar to Odata. ATM when a user wants to map Http requests to CRUD operations, it becomes a very tedious process. 

This has to be simplified 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nandika** [comment]
This requirement is no longer valid.
