### ISSUE TITLE
[Doc] Definition of RabbitMQ Exchange Auto Delete

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1772]
**Description:**
The description of RabbitMQ Exchange Auto Delete is given as Whether to keep the queue even if it is not used anymore.
This need to be corrected as "Whether to keep the **exchange** even if it is not bound to any queue anymore."

**Suggested Labels:**
Type/Doc

**Suggested Assignees:**

**Affected Product Version:**
EI and ESB

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Changed the description of the "rabbitmq.exchange.auto.delete" property as follows in docs of all WSO2 EI & ESB versions.

"Whether to keep the exchange even if it is not bound to any queue anymore."

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/RabbitMQ+AMQP+Transport
