### ISSUE TITLE
Document new parameters for Scheduled failover message processor

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#1776]
**Description:**

Add descriptions for following 3 new parameters 

1.   <parameter name="max.store.connection.attempts">-1</parameter>
2.   <parameter name="store.connection.retry.interval">1000</parameter>
3. <parameter name="message.processor.failMessagesStore"></parameter>

Please note default values. Please not what (-1) does for "max.store.connection.attempts". 

Refer below RRs for description. 

1. https://github.com/wso2/wso2-synapse/pull/1009
2. https://github.com/wso2/carbon-mediation/pull/951
3. https://github.com/wso2/devstudio-tooling-esb/pull/309

**Affected Product Version:**

EI 6.2.0

**OS, DB, other environment details and versions:**    

N/A

**Steps to reproduce:**

N/A

**Related Issues:**
N/A

**Comment by Nashaath** [comment]
Added the new parameters and descriptions in [1]. 
[1] https://docs.wso2.com/display/EI620/Scheduled+Message+Forwarding+Processor

Regarding the property "Fail messages store", it sounds a bit incorrect.
Would it make sense to rename it to Backup message store in the UI?
