### ISSUE TITLE
No specific permission to manage CApp deployment via management console

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1777]
**Description:**
No specific permission level to manage CApp deployment permissions

**Affected Product Version:**
EI 6.1.1 , ESB 5.0.0 (wum updated)

**OS, DB, other environment details and versions:**    
Ubuntu 15.10
DB - H2

**Steps to reproduce:**
1. Create a user
2. Create a role and provide permission to deploy CApps

Observations
There is no specific permission to enable cApp deployment via Management Console.
Need to enable to enable "Add" parent permission to enable CApp deployment via management console

EI 6.1.1
![ei611](https://user-images.githubusercontent.com/14962228/35207756-c4e06b28-ff6a-11e7-924e-e422228b9db2.png)

ESB 5.0.0
![esb500](https://user-images.githubusercontent.com/14962228/35207762-c97abbb6-ff6a-11e7-97ed-1897f57b3a77.png)

**Comment by prabushi** [comment]
We have already add the granular permission to deploy and list CApps at https://github.com/wso2/carbon-commons/pull/280

Permission comes under manage/capps/list and manage/capps/add 
![permission](https://user-images.githubusercontent.com/5234623/36025484-3a211214-0db9-11e8-9da6-e069e70758c3.png)
