### ISSUE TITLE
[ESB 4.9.0] - Publish mediator data will not be publish to DAS when the connection failure. 

### ISSUE THREAD

**Issue by ksdperera** [wso2/product-ei#1793]
**Description:**
Suspected Reason:

The 'queueSemaphore' acquire in [1] has to release in [2], but before release it there is logic in [3] check the event poll from the queue is null or not. In the above incident, we noticed the followings(we added a couple of debug logs before acquire and release queueSemaphore):
If the 'queueSemaphore' acquire in [1] before connection lost occurred.
After connection failure:
Its throw the "ERROR - EventPublisher Cannot get a client to send events to" exception.
Then the notifyConnectionFailure method in EventPublisher executed and in [4] eventQueue is rest.
 After that, logic in [3] checking the eventQueue nullity(head is null)
As the eventQueue is already null queueSemaphore.release not executed and exist from the loop.
Then the other threads are waiting for 'queueSemaphore' acquire.

Solution:
we need to have the semaphore.release() within the notifyConnectionFailure() method.

**Affected Product Version:**
ESB 4.9.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Setup single node ESB and DAS servers(with Publisher medeator proxy) and redicuce the DAS databridge event receiver queue to minimum value.
Using JMeter script and 100 threads send the event in burst manner to the ESB server.
Then it has logged the event queue full log in the ESB server, a similar error we have seen in the ESB log provided on the ticket as well[2]
After that, we have shut down the DAS server to reproduce the connection lost issue.
Then in the ESB server its throw the connection refused issue, yet to be verify this in the customer logs:
ERROR - EventPublisher Cannot get a client to send events to TCP,localhost:7612,TCP,localhost:7712
org.wso2.carbon.databridge.agent.thrift.exception.AgentException: Cannot borrow client for TCP,localhost:7612,TCP,localhost:7712
	at org.wso2.carbon.databridge.agent.thrift.internal.publisher.client.EventPublisher.getClient(EventPublisher.java:426)
	at org.wso2.carbon.databridge.agent.thrift.internal.publisher.client.EventPublisher.publishEvent(EventPublisher.java:129)
	at org.wso2.carbon.databridge.agent.thrift.internal.publisher.client.EventPublisher.run(EventPublisher.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
After the above error log we have restart the DAS server againe, and observe the similar issue whether customer reported, data publishing has stopped totally.

**Comment by wggihan** [comment]
This issue already fixed in the master branch. A WUM update issued for the ESB-4.9.0.
