### ISSUE TITLE
[Doc][BPS] Server shutdown option is applicable only when deleting active instances

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-ei#1799]
**Description:**
This document says 

> Do not execute the cleanup script when the server is running. Server should be shutdown before executing the cleanup scripts.

But, shutting down the server option is only applicable if the script is used to **delete active process instances.** Please fix the document with the correct explanation.

https://docs.wso2.com/display/BPS351/Database+cleanup+sql+scripts

**Suggested Labels:**
Doc, Improvement, BPS

**Affected Product Version:**
BPS 3.5.1 and above

**Comment by praneesha** [comment]
Changed the note as follows in all versions of WSO2 BPS and EI docs:

"If you are using the clean-up script to delete the active process instances, stop the server before executing the clean-up scripts."

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts
