### ISSUE TITLE
Failed to load the jndi.properties file due to the changes in the provider path

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#180]
**Issue**
In the axis2.xml file under the JSM transport receiver configuration, "java.naming.provider.url" parameter is set as "repository/conf/jndi.properties". Hence the server failed to load the property files with below errors.

TID: [-1234] [] [2017-02-14 17:40:51,870]  WARN {org.wso2.andes.jndi.PropertiesFileInitialContextFactory} -  Unable to load property file specified in Provider_URL:repository/conf/jndi.properties
Due to:repository/conf/jndi.properties (No such file or directory) {org.wso2.andes.jndi.PropertiesFileInitialContextFactory}
TID: [-1234] [] [2017-02-14 17:40:51,930] ERROR {org.apache.axis2.transport.jms.JMSConnectionFactoryManager} -  Error setting up connection factory : myTopicConnectionFactory {org.apache.axis2.transport.jms.JMSConnectionFactoryManager}
org.apache.axis2.transport.jms.AxisJMSException: Cannot acquire JNDI context, JMS Connection factory : TopicConnectionFactory or default destination : null for JMS CF : myTopicConnectionFactory using : {java.naming.provider.url=repository/conf/jndi.properties, java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory, transport.jms.ConnectionFactoryType=topic, transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory}

**Note**
"java.naming.provider.url" parameter should set to the correct jndi.properties file location as below.
 <parameter name="java.naming.provider.url" locked="false">conf/jndi.properties</parameter>

**Comment by nandika** [comment]
corrected axis2.xml
