### ISSUE TITLE
[Doc] Disabling JMX thread view

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1800]
**Description:**
Add documentation related to disabling JMX thread view for https://docs.wso2.com/display/EI611/JMX+Monitoring

By configuring **synapse.jmx.thread.view.enabled=false** at the **synapse.properties**, we can avoid dumping all threads at https://github.com/wso2/wso2-synapse/blob/master/modules/commons/src/main/java/org/apache/synapse/commons/jmx/ThreadingView.java#L268 which will affect the CPU consumption when there are more thread at the process. Dumping threads is an expensive operation which can cause high CPU utilization. Therefore, we can disable JMX thread viewing when it is not required for the usecase. By default this property is enabled in ESB. 
 
Disabling JMX server as defined in https://docs.wso2.com/display/Carbon440/JMX-Based+Monitoring#JMX-BasedMonitoring-DisablingJMXfortheserver, will not disable the issue of dumping threads. Have to configure above mentioned property.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you!
Updated docs with this info.

[1] https://docs.wso2.com/display/EI611/JMX+Monitoring#JMXMonitoring-DisablingtheJMXthreadview
[2] https://docs.wso2.com/display/EI620/JMX+Monitoring#JMXMonitoring-DisablingtheJMXthreadview
[3] https://docs.wso2.com/display/EI6xx/JMX+Monitoring#JMXMonitoring-DisablingtheJMXthreadview
