### ISSUE TITLE
Create excel Data service error (xlsx)

### ISSUE THREAD

**Issue by Jame-Chen** [wso2/product-ei#1810]
Create excel Data service error (xls) is possible
Specific errors are as follows：
DS Fault Message: java.lang.reflect.InvocationTargetException DS Code: CONNECTION_UNAVAILABLE_ERROR Source Data Service:- Name: ExcelTests Location: \ExcelTests.dbs Description: N/A Default Namespace: Test Nested Exception:- java.sql.SQLException: java.lang.reflect.InvocationTargetException at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.(RDBMSConfig.java:45) at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getRDBMSConfig(ConfigFactory.java:92) at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:60) at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:159) at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:797) at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152) at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201) at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136) at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807) at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144) at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377) at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254) at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371) at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59) at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67) at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93) at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLException: java.lang.reflect.InvocationTargetException at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:290) at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182) at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701) at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635) at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:188) at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.createConnection(SQLConfig.java:188) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.createConnection(SQLConfig.java:173) at org.wso2.carbon.dataservices.core.description.config.SQLConfig.initSQLDataSource(SQLConfig.java:151) at org.wso2.carbon.dataservices.core.description.config.RDBMSConfig.(RDBMSConfig.java:43) ... 23 more Caused by: org.apache.poi.POIXMLException: java.lang.reflect.InvocationTargetException at org.apache.poi.POIXMLFactory.createDocumentPart(POIXMLFactory.java:65) at org.apache.poi.POIXMLDocumentPart.read(POIXMLDocumentPart.java:601) at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:174) at org.apache.poi.xssf.usermodel.XSSFWorkbook.(XSSFWorkbook.java:249) at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:211) at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:170) at org.wso2.carbon.dataservices.sql.driver.TExcelConnection.createConnectionToExcelDocument(TExcelConnection.java:74) at org.wso2.carbon.dataservices.sql.driver.TExcelConnection.(TExcelConnection.java:58) at org.wso2.carbon.dataservices.sql.driver.TConnectionFactory.createConnection(TConnectionFactory.java:32) at org.wso2.carbon.dataservices.sql.driver.TDriver.connect(TDriver.java:51) at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278) ... 32 more Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at org.apache.poi.xssf.usermodel.XSSFFactory.createDocumentPart(XSSFFactory.java:56) at org.apache.poi.POIXMLFactory.createDocumentPart(POIXMLFactory.java:62) ... 42 more Caused by: java.lang.NoSuchMethodError: org.apache.xmlbeans.XmlOptions.setLoadEntityBytesLimit(I)Lorg/apache/xmlbeans/XmlOptions; at org.apache.poi.POIXMLTypeLoader.(POIXMLTypeLoader.java:50) at org.apache.poi.xssf.model.ThemesTable.(ThemesTable.java:85) ... 48 more

**Comment by nandika** [comment]
Hi Jeme Chen,
Can you list the product version you are using and the exact steps to reproduce this issue.

Regards
Nandika

**Comment by Jame-Chen** [comment]
I now use the version wso2 ei 6.1.0, I follow this tutorial to build excel example error, xls format file is successful, xlsx format reported above error;
https://docs.wso2.com/display/EI610/Exposing+Excel+Data+as+a+Data+Service
