### ISSUE TITLE
Class cast exception is thrown when using a proxy service with custom mediator

### ISSUE THREAD

**Issue by Megala21** [wso2/product-ei#1812]
**Description:**
**ERROR - addSignature Exception occured - org.jcp.xml.dsig.internal.dom.DOMXMLSignatureFactory cannot be cast to javax.xml.crypto.dsig.XMLSignatureFactory** 

in the line javax.xml.crypto.dsig.XMLSignatureFactory fac = javax.xml.crypto.dsig.XMLSignatureFactory.getInstance("DOM");

of the custom mediator.

**Suggested Labels:**
ESB 4.8.1, Bug

**Suggested Assignees:**
N/A

**Affected Product Version:** 4.8.1

**OS, DB, other environment details and versions:**    Ubuntu

**Steps to reproduce:**
Create a custom mediator with the line
in the line javax.xml.crypto.dsig.XMLSignatureFactory fac = javax.xml.crypto.dsig.XMLSignatureFactory.getInstance("DOM");

Deploy and call the custom mediator in  a proxy service.
Call the proxy service.

**Related Issues:**
https://issues.apache.org/jira/browse/SANTUARIO-358

**Comment by Nirothipan** [comment]
We can avoid this by explicitly preventing the import of the conflicting package from the custom mediator jar while packaging it as an OSGi bundle.

<Import-Package>
    !javax.xml.crypto.*; version="1.4.2.patched",
    org.apache.xml.security;version="0.0.0",
    *
</Import-Package>
