### ISSUE TITLE
Cancel the edit proxy service from Sequence & Endpoint directs to add sequence page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-ei#1813]
**Description:**
Cancel the edit proxy service from Sequence & Endpoint directs to add sequence page

**Suggested Labels:**
Type/bug
UX
Priority/normal
Sevirity/major

**Affected Product Version:**
ei-6.1.1 wum updated pack downloaded 8th Jan

**OS, DB, other environment details and versions:**    
standalone

**Steps to reproduce:**
- Add a simple proxy service with an EP and outsequence as below
`<outSequence xmlns="http://ws.apache.org/ns/synapse">
    <send/>
</outSequence>`
- Go to edit proxy in UI and goto step3
- Click edit on define inline
- Switch to source view and click on cancel button 
=> navigate the user to home->sequence page
but expecting to direct back to the edit page step3
![edit1](https://user-images.githubusercontent.com/15671620/35508875-0ce30964-0518-11e8-9f6e-727a13bd0ee9.jpeg)

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/968 in 6.2.0
