### ISSUE TITLE
When a groove dependent proxy service is deployed management console is not accessible

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#1820]
**Description:**
A proxy with groove dependency (i.e a script mediator uses a groove ) is added to the EI-6.1.1 then the server is started it doesn't complain any errors but the mgt console is not accessible

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI-6.1.1

**Steps to reproduce:**
Create a proxy file which uses a groove script mediator.
Add the proxy file into proxy_services folder and start the server
there wont be any errors in the start up but the mgt console is not accessible

**Comment by bsenduran** [comment]
Related to https://github.com/wso2/product-ei/issues/1054
