### ISSUE TITLE
[Doc] [EI] Add descriptions on Data Services Server in 'Running the Product' doc

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-ei#1827]
**Description:**
There's no mention of Data Services Server in 'Running the Product' doc [1]. Once the integrator started, DSS will also work as part of the integrator.

[1] https://docs.wso2.com/display/EI611/Running+the+Product

**Suggested Labels:**
Docs, Ei-6.1.1

**Affected Product Version:**
EI 6.1.1

**Comment by praneesha** [comment]
Added the following sentence in docs of all WSO2 Ei versions.

"The data integration functionalities of WSO2 EI comes with the ESB profile. Therefore, you need to start the ESB profile to use them."

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product
