### ISSUE TITLE
Responses swapped across multiple requests when FORCE_SC_ACCEPTED is used with another respond mediator

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#1829]
**Description:**
When FORCE_SC_ACCEPTED is used and a respond mediator used in fault sequence sometimes the responses get mixed up. The issue occurs when one proxy uses FORCE_SC_ACCEPTED and in its fault sequence uses respond mediator. If an error prone backend is referred from this proxy and it delays in responding while a another proxy get the response correctly the response in the new proxy can be swapped with the response from error prone backend.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.8.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by bsenduran** [comment]
Fixed with wso2/wso2-synapse#1043 and wso2/carbon-mediation#979
