### ISSUE TITLE
[DOC] [DSS] Documendation for exposing excel data as a data service

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#1832]
**Description:**
[https://docs.wso2.com/display/EI611/Exposing+Excel+Data+as+a+Data+Service](https://docs.wso2.com/display/EI611/Exposing+Excel+Data+as+a+Data+Service)
Insert query in the doc given in 2 lines.

"INSERT INTO sheet1 (ID, Model, Classification)
VALUES(?,?,?)"

When user copy paste the query from doc it gives following exception 
**java.sql.SQLException: Syntax Error : VALUE/VALUES keyword missing**

So we need to change it to a single line as below
INSERT INTO sheet1 (ID, Model, Classification) VALUES(?,?,?)

**Suggested Labels:**
Type/Docs

**Affected Product Version:**
EI 6.0.0, 6.1.0, 6.1.1

**Comment by nilminiwso2** [comment]
Checked and fixed in EI 6xx series + DSS 351.
