### ISSUE TITLE
Add Newly added properties for WSS inbound endpoints to Dev Studio Tooling.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1834]
**Description:**
Recently the two properties, "wss.ssl.protocols" and "wss.ssl.cipher.suites" have been added to WSS inbound endpoints. These are missing from dev studio tooling WSS inbound endpoint creation wizard. 
These need to be added to it.

Depends on :- https://github.com/wso2/product-ei/issues/1855

**Suggested Labels:**
Dev Studio Tooling

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
moved to tooling repo https://github.com/wso2/devstudio-tooling-ei/issues/194
