### ISSUE TITLE
Fix the Incompatibility With Some JDK Versions

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#1844]
**Description:**
When using WSO2 products with some JDK versions, we are getting an error and will be unable to access the Management Console.

We need to fix this in WSO2 EI.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
@praneesha  can you please mention the JDK versions and also the error in order to reproduce the error

**Comment by praneesha** [comment]
You can find the versions in [1].

The error is as follows:

WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/admin/login_action.jsp, error:required token is missing from the request)

[1] https://docs.wso2.com/display/compatibility/Known+Incompatibilities
