### ISSUE TITLE
[Doc] Avoid endpoint suspension at dynamic URL or change endpoint status to active

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#1846]
**Description:**
Dynamic Endpoint Failover Management

When we are using a dynamic URL for a particular endpoint, if one URL fails the endpoint will be suspended even though we change the URL dynamically. We can follow one of the following to avoid suspension or to re-enable the endpoint.

1. Can define error codes that cause endpoint failure eg:
 `<errorCodes>-1</errorCodes>` to disable suspension for the endpoint 
 `<errorCodes>101504, 101505</errorCodes>` to exclude the error codes from suspendOnFailure and markForSuspension under endpoint configuration, so that the endpoint will not get suspended for those error codes.

2. If you have defined the endpoint as a registry resource, you can activate the endpoint through the Java Management Extension(JMX). For example, you can use switchOn operation for that particular endpoint in jconsole which comes under MBeans -> org.apache.synapse -> Endpoint , which will activate the endpoint again.

3. If you have defined the endpoint under endpoints list in the management console, you can manually activate the endpoint by clicking on Switch On

[1] - https://docs.wso2.com/display/EI611/Endpoint+Error+Handling

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you, for the detailed information!
Updated the 611, 620, and 6xx docs.

[1] https://docs.wso2.com/display/EI611/Endpoint+Error+Handling#EndpointErrorHandling-Dynamicendpointfailovermanagement
