### ISSUE TITLE
[Doc] Some properties from WSS inbound endpoint are missing in the docs.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1854]
**Description:**
The following properties are there in WSS inbound endpoints but I couldn't find them in the relevant docs.

ws.default.content.type
ws.shutdown.status.code 
ws.shutdown.status.message

![screenshot from 2018-02-14 12-20-52](https://user-images.githubusercontent.com/24619763/36191067-8780fb2a-1181-11e8-9221-9c42a3761fc8.png)

https://docs.wso2.com/display/ESB500/Secure+WebSocket+Inbound+Protocol

**Suggested Labels:**
Doc/ Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Added descriptions of these 3 properties in docs of WSO2 ESB 5.0.0 and all WSO2 EI versions.

For example, see [1] and [2].

[1] https://docs.wso2.com/display/EI6xx/WebSocket+Inbound+Protocol
[2] https://docs.wso2.com/display/EI6xx/Secure+WebSocket+Inbound+Protocol
