### ISSUE TITLE
[Dev Studio Tooling ESB] - Secure Web Socket Inbound endpoint is missing in Dev Studio Tooling

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1855]
**Description:**
WSS inbound endpoint is missing from dev studio tooling ESB.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/1834

**Comment by sohaniwso2** [comment]
moved to tooling repo https://github.com/wso2/devstudio-tooling-ei/issues/194
