### ISSUE TITLE
[ Dev Studio Tooling ESB] Need to add select all button for updates in dev studio tooling

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1856]
**Description:**
When updating the tooling, for the first time, we have to manually select all the updates if we need them.
Better to have a
![2screenshot from 2018-02-14 14-09-06](https://user-images.githubusercontent.com/24619763/36194670-a964bf56-1190-11e8-9a35-dc234f900a08.png)
 select all option in the menu.

**Suggested Labels:**
Dev Studio Tooling/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Duplicated issue https://github.com/wso2/devstudio-tooling-ei/issues/62.

**Comment by sohaniwso2** [comment]
Please refer https://github.com/wso2/devstudio-tooling-ei/issues/62
