### ISSUE TITLE
Update redirection URL of the userguide for Message store/processor

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#1864]
**Description:**
When you click on help in management console in message store/processor [1], user will be redirected to the doc page for 4.9.0 version, 
Update it to the latest.

[1] https://localhost:9443/carbon/message_store/docs/userguide.html

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    
Environment Independent

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/983
