### ISSUE TITLE
Adding keystores from the UI

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#1866]
Do we need the functionality in [1] any longer? If not, shall we remove this from the UI?
In older versions of WSO2 ESB, we had a use case for [1] because it was possible to enable authentication/authorization for WS-Security scenarios through the UI. But now that we no longer support WS-security in the UI, maybe we can remove the functionality of [1].

[1] https://docs.wso2.com/display/ADMIN44x/Managing+Keystores+with+the+UI

**Affected Product Version:**
ESB 500 onwards. 

**Related Issues:**
https://wso2.org/jira/browse/DOCUMENTATION-7710

**Comment by Tomas-Mrazek** [comment]
Late for party, but does that mean, that the management console for keystore does not work at all? I mean, it would make sense. 
1) Console shows only wso2carbon.jks completely ignoring client-truststore.jks
2) I uploaded another keystore via console and it's nowhere to be found in the actual system folder

EI 6.4.0
