### ISSUE TITLE
[Windows][EI] When shutting down the EI server backend shows some error logs

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#187]
**Environment**
Os-Windwos 2012 Rc2
JAVA -jdk 1.8.0_21
Firefox 47

**Steps**

1. Start the EI alpha pack using start_all script
2. After sometime shutdown all servers one by one
3. While shutting down the EI server, backend shows following errors

**Error**
`[2017-02-14 22:40:28,539] [] ERROR - DataHolder Before activating javax caching
 bundle, an instance of ServerConfigurationService should be in existence
[2017-02-14 22:40:28,571] [] ERROR - DataHolder Before activating javax caching
 bundle, an instance of ServerConfigurationService should be in existence
[2017-02-14 22:40:28,571] [] ERROR - DataHolder Before activating javax caching
 bundle, an instance of ServerConfigurationService should be in existence
[2017-02-14 22:40:28,571] [] ERROR - DataHolder Before activating javax caching
 bundle, an instance of ServerConfigurationService should be in existence`

**Comment by nandika** [comment]
checked this issue. However, could not reproduce it
