### ISSUE TITLE
Message Content cannot be viewed in Message Broker Queue

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-ei#1872]
**Description:**
Unable to view the message content in the Message Broker Queue, which was sent through ESB as they are in the Object Format. It displays "The operation is not supported", whenever tried to open the messages through Message Broker.

**Suggested Labels:**
EI 6.1.1

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vitorstabile** [comment]
Hello! Any news about this issue? I'm passing through this problem too in my work with WSO2 EI 6.1.1.
