### ISSUE TITLE
Update docs msmq tranport jar

### ISSUE THREAD

**Issue by madhawa-gunasekara** [wso2/product-ei#1881]
**Description:**
Current attached jar is not working with ei-6.1.1, Please update the jar with documentations.
[jar.zip](https://github.com/wso2/product-ei/files/1747717/jar.zip)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Updated the step as follows in the below docs in all versions of WSO2 EI.

"Download the axis2-transport-msmq-2.0.0-wso2v2.jar file and add it to the <EI_HOME>/dropins/ directory. This file provides the JNI invocation required by MSMQ bridging. "

[1] https://docs.wso2.com/display/EI6xx/MSMQ+Transport
[2] https://docs.wso2.com/display/EI6xx/Sample+270%3A+Transport+switching+from+HTTP+to+MSMQ+and++MSMQ+to+HTTP
[3] https://docs.wso2.com/display/EI6xx/Configure+with+MSMQ
