### ISSUE TITLE
Duplicated subscriptions in message broker when database restarts. (disconnect - connect again)

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#1885]
**Description:**
![document 1 2](https://user-images.githubusercontent.com/8251118/36717906-e6d58368-1bc5-11e8-8a0d-119f785e6db0.png)

Suppose EI 1 connected to MB1 and it have some subscriptions. 
Now when DB fails MB1 remove those subscriptions from memory
` Remove Local Subscription AMQP subscriptionId=9de18544-b606-4530-92fc-23362f4a2971`
But it cannot remove updates from DB since its failed.
`WARN {org.wso2.andes.kernel.subscription.AndesSubscriptionManager} -  Cannot not remove subscription from store since the store is non-operational `

Upon receiving the notification MB2 also remove the subscription from its memory
Now after DB connection establish EI 1 re-create the subscriptions with MB1 ( now DB have 2 entries since earlier entry is not removed )
Later, memory of DB nodes are re-loaded with data from database. 
Now memory of DB nodes have 2 entries and since management console is loaded by the data in memory it shows doubled entries.

**DB Sync Task** is there to remove these inconsistencies. But after a DB failure this task failed to run and give following WARN
`WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store.`  

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.1.1 MB 3.2.0 

**Steps to reproduce:**
Create EI 6.1.1 MB cluster and create a JMS subscription from another ESB node.
Now restart the mysql service **service mysql restart**
Upon finishing the re-start you can see doubled entries for queues in Management console.

And following error in logs 
`WARN {org.wso2.andes.kernel.AndesRecoveryTask} -  AndesRecoveryTask was paused due to non-operational context store.`

**Comment by lkokila** [comment]
Updated PR: https://github.com/wso2/andes/pull/1045/files
