### ISSUE TITLE
[ Doc Imrovements] Clustering the ESB Profile

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1891]
**Description:**
Following steps need to be updated.

Issue One

**Configuring the load balancer**

In 5 -e ) -- The default password need to be given ( wso2carbon )

Issue Two

**Configuring the ESB profile node**

In 1 )

For the URL append  useSSL=false if SSL is not enabled.
<url>jdbc:mysql://carbondb.mysql-wso2.com:3306/REGISTRY_LOCAL1?autoReconnect=true</url>

Issue Three

In 4 )

Following need to be divided into 2 steps and mentioned explicitly.

Uncomment and edit the WSDLEPRPrefix element under org.apache.synapse.transport.passthru.PassThroughHttpListener and
org.apache.synapse.transport.passthru.PassThroughHttpSSLListener in the transportReceiver section.

Issue Four

In 6 )

<HostName>esb.wso2.com</HostName>
<HostName>**ei.**wso2.com</HostName> Need to confrm whether we need ei.wso2.com as host name or esb.wso2.com as host name. In nginx conf we mention the ei.wso2.com.

Issue Five

In 8 ) Edit the <EI_HOME>/conf/tomcat/catalina-server.xml file as follows to

Please mention explicitly to add the proxy port to both of the existing blocks.

**Suggested Labels:**
Type/Doc

**Suggested Assignees:**

**Affected Product Version:**
EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Better if we can add some troubleshooting guides for mysql errors like

Too many connections
root permission denied 
useSSL

**Comment by praneesha** [comment]
Fixed the following:

1. Issue One - Done
2. Issue Two - Done
3. Issue Three - Done
4. issue Four - It is fine to have "wso2.esb.com" just as an example. If we change it, we need to change it in a lot of other occurrences.
5. Issue Five - Done
