### ISSUE TITLE
Document the alternative methods to start broker, bps and analytics profiles

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1902]
**Description:**
Document the alternative methods to start the following profiles

- Broker profile
- Analytics profile
- BPS profile

As documented in the README.txt this information should go to the official documentation [1] 
Ex: Optionally, you can start the runtimes using scripts located at wso2ei-6.1.1-update8/bin directory. Scripts
available are analytics.sh/analytics.bat for analytics profile , broker.sh /broker.bat for broker profile and
business-process.sh / business-process.bat for business process profile.

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product

**Comment by praneesha** [comment]
Added this information at the end of the "Starting the ESB profile" in [1].

This is done in docs of WSO2 EI 6.x.x and 6.1.1.

[1] https://docs.wso2.com/display/EI6xx/Running+the+Product
