### ISSUE TITLE
[Doc] [Inbound Endpoints] Update docs regarding some parameters

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1903]
**Description:**

The default value of coordination is **true**. It is  given as **false** in all places

https://docs.wso2.com/display/EI620/Polling+Inbound+Endpoints

**Suggested Labels:**
Type/Doc

**Suggested Assignees:**

**Affected Product Version:**
EI -6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
The parameters interval and coordination are common to all polling inbound endpoints. For descriptions of these parameters, see Common polling inbound endpoint parameters.
 in https://docs.wso2.com/display/EI620/JMS+Inbound+Protocol .

**Comment by shavidissa** [comment]
Thank you! 
Updated as discussed.

[1] https://docs.wso2.com/display/EI6xx/Polling+Inbound+Endpoints
[2] https://docs.wso2.com/display/EI620/Polling+Inbound+Endpoints

[3]https://docs.wso2.com/display/EI6xx/Event-Based+Inbound+Endpoints
[4] https://docs.wso2.com/display/EI620/Event-Based+Inbound+Endpoints
