### ISSUE TITLE
[Doc ] tasks-config.xml location in EI 6.2.0

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1905]
**Description:**
The location of tasks-config.xml in EI 6.2.0 is  <PRODUCT_HOME>/conf/etc/ .

Need to include a note in https://docs.wso2.com/display/ADMIN44x/Configuring+the+Task+Scheduling+Component

which links from 
https://docs.wso2.com/display/EI620/Adding+and+Scheduling+Tasks

**Suggested Labels:**
Type/Doc

**Suggested Assignees:**

**Affected Product Version:**
EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed.
