### ISSUE TITLE
Incorrect directory path for the analytic datasources file

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1906]
**Description:**
Incorrect product path for analytics data source in the doc [1].

The path for the analytics-datasources.xm is provided as ` <API-M_ANALYTICS_HOME>/repository/conf/datasources/analytics-datasources.xml` in the doc, which should be corrected with the correct file location according to the EI product.

[1] https://docs.wso2.com/display/EI6xx/Prerequisites+to+Publish+Statistics

**Comment by praneesha** [comment]
Fixed in docs of all WSO2 EI versions. For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Prerequisites+to+Publish+Statistics
