### ISSUE TITLE
Outdated product version information in 'About' page

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1907]
**Description:**
"About" product page contains outdated information about the product update version. Which should be updated according to the latest released update version.

![screenshot from 2018-03-06 10-24-03](https://user-images.githubusercontent.com/14962228/37014717-87db3e6c-2128-11e8-8267-c73aed6b2f50.png)

**Affected Version**
EI 6.1.1 update 23

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/1947/commits/514841a89d9ea94597f92fdd3f40d2458eb5a580 in update 24.
