### ISSUE TITLE
[Doc ] Missing documentation related to some message stores. 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1909]
**Description:**
Documentation related to WSO2 MB Message store and Resequence message Store are missing from 
https://docs.wso2.com/display/EI620/Adding+a+Message+Store .

![smkams](https://user-images.githubusercontent.com/24619763/37024881-2516d570-2150-11e8-9c62-77eab4b427cd.png)

**Suggested Labels:**
Type/Doc

**Suggested Assignees:**

**Affected Product Version:**
EI 6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Added [1] & [2] in WSO2 EI 6.x.x doc space. Also, added these 2 to the messages stores list mentioned in [3].

[1] https://docs.wso2.com/display/EI6xx/Resequence+Message+Store
[2] https://docs.wso2.com/display/EI6xx/WSO2+MB+Message+Store
[3] https://docs.wso2.com/display/EI6xx/Message+Stores
