### ISSUE TITLE
[ Doc ] Update the java.naming.provider.url for Message Broker profile of WSO2 EI  in JMS Message store

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1912]
**Description:**
In https://docs.wso2.com/display/EI620/JMS+Message+Store  under the section named as "Following is a sample JMS message store configuration that uses the Message Broker profile of WSO2 EI as the message broker:"

<parameter name="java.naming.provider.url">repository/conf/jndi.properties</parameter> 

need to be updated as 

<parameter name="java.naming.provider.url">conf/jndi.properties</parameter>

**Comment by nilminiwso2** [comment]
fixed
