### ISSUE TITLE
Failed to anonymize the username in the carbon logs using the given script

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1913]
**Description:**
"identity-anonymization-tool" does not remove the PII from the log files.

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
OS - ubuntu 15.10
DB - mysql 5.6
JDK  - 1.8

**Steps to reproduce:**
1. Create a simple proxy
```
<inSequence>
         <property expression="get-property('transport', 'user')"
                   name="user"
                   scope="default"
                   type="STRING"/>
         <log level="full">
            <property expression="get-property('user')" name="USERNAME"/>
         </log>
```
2. Configure the "ei-patterns.xml" file as follows

```
<pattern key="pattern3">
		<detectPattern>(.)*(USERNAME)(.)*${username}(.)*</detectPattern>
		<replacePattern>${username}</replacePattern>
	</pattern>
```
3. Configure config.json
```
{
  "processors" : [
    "log-file"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "/home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/repository/logs",
      "log-file-name-regex" : "wso2carbon.log"
    },
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "/home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/repository/logs",
      "log-file-name-regex" : "audit.log"
    },
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "/home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/repository/logs",
      "log-file-name-regex" : "warn.log"
    }
  ]
}

```
4. Execute the script to replace the username from the configuration files
```
./forget-me.sh -U peter
```

**Observations**
1. Following information available in the wso2carbon.log file. After executing the script the username "peter" has not replaced with the uuid.
```
TID: [-1234] [] [2018-03-06 12:26:35,271]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: /services/SampleProxy, MessageID: urn:uuid:d1fdab95-b571-40ac-b4fa-17ecd7750088, Direction: request, ===== SAMLE====== = ====== TEST =========, USERNAME = peter {org.apache.synapse.mediators.builtin.LogMediator}
TID: [-1234] [] [2018-03-06 12:38:36,870]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: /services/SampleProxy, MessageID: urn:uuid:03948940-6795-4269-918c-8900875aeafc, Direction: request, ===== SAMLE====== = ====== TEST =========, USERNAME = sashika {org.apache.synapse.mediators.builtin.LogMediator}
```

**Expected Result**
Username 'peter' should not be available in the logs

**Comment by milanperera** [comment]
Please change the config.json to following.
```
{
  "processors" : [
    "log-file"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "PATH_TO_LOG",
      "log-file-name-regex" : "(.)*(log|out)"
    }
  ]
}
```

**Comment by sashikamw** [comment]
@milanperera I 'll verify this. We need to add this to the documentation as well.

**Comment by sashikamw** [comment]
@milanperera I have verified this scenario. If I define the regex pattern as below i could replace the user information with the defined pseudonym. 

```
{
  "processors" : [
    "log-file"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "/home/sashika/.wum-wso2/products/wso2esb/EI/wso2ei-6.1.1-update23/repository/logs",
      "log-file-name-regex" : "(audit.log*|warn.log|wso2carbon.log|Sample-proxyservice.log)"
    }
  ]
}
```

This will create another set of temp files for the above logs and the existing logs were still maintained.

Since the requirement is to replace the username with a pseudonym, what actions needs to take for the original log files that contain the user information?

Further, this will only replace the log files without the timestamp. How can we manage to replace all the log files? IMO the default configuration should manage to replace all the log files

**Comment by milanperera** [comment]
To remove logs with the timestamp, the regex pattern has to be modified as below.
`"log-file-name-regex" : "(audit.log|warn.log|wso2carbon.log|Sample-proxyservice.log)(.)*"`

As per the initial discussions, we do not remove the original log files, rather we create a new one with anonymized content. The responsibility of removing original logs is passed to the organization.

**Comment by milanperera** [comment]
Modified the default config.json [1] to run log anonymization by default.

[1] https://github.com/wso2/identity-anonymization-tool/pull/63

**Comment by sashikamw** [comment]
@nilminiwso2 we need to add the following points to the doc, hence reopening the issue.
1) Update the existsing config.json given in the doc [1]
2) Document the process of replacing the information. As you mentioned above we need to document that the tool will replace the PII and create a set of new files, but not replacing the original files

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-RemovingPIIfromtheESBprofile

**Comment by milanperera** [comment]
Updated the config.json samples in the doc [1] to adhere to the new changes of the identity-anonymization-tool.

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-RemovingPIIfromtheESBprofile

**Comment by nilminiwso2** [comment]
Content about temporary log files added.
