### ISSUE TITLE
Document the purpose of metircs-datasources in analytics profile

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1919]
**Description:**
Are we using the 'metrics-datasources.xml' in the analytics profile in <EI_HOME>/wso2/analytics? The document does not contain the required information about the purpose of configuring this data sources for analytics.

**Comment by praneesha** [comment]
This information is documented in the "Monitoring using WSO2 metrics" row in [1].

[1] https://docs.wso2.com/display/EI6xx/Product+Administration#ProductAdministration-Monitoring
