### ISSUE TITLE
Unable to login to BPS and MB management console when JDK1.8.0_151/152/161 and 162 is used

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-ei#1920]
**Description:**
While using JDK1.8.0_151/152/161 and 162, unable to login to the management console of BPS and Broker. 
Error 403 - Forbidden will occur in the browser.
For the same JDKs, Integrator will work fine, able to login to the management console.

**Suggested Labels:**
Bug / Blocker

**Affected Product Version:**
WSO2EI-6.1.1

**Steps to reproduce:**
Use one of above mentioned JDKs and start the BPS or MB. 
Try to login to the management console.
Error 403 - Forbidden will occur in the browser

**Comment by Nirothipan** [comment]
There had been an issue with 1.8.0_151 https://bugs.openjdk.java.net/browse/JDK-8189789.

We could observe this behaviour in EI-6.1.1 vanilla pack.

This is not observed in EI-6.2.0 snapshot pack.

**Comment by Nirothipan** [comment]
There was a similar issue reported related to this version of JDK https://github.com/wso2/product-ei/issues/1219 for EI
