### ISSUE TITLE
Provide the support to replace user information in UserDB using a pseudonym

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1921]
**Description:**
Unable to replace the user identification information with a pseudonym.

If a particular party use the management console or the admin service to create users in the EI, there should be a possible way to replace the user identification information in the Database tables (usually user information maintained in UM_USER and UM_USER_ATTRIBUTE tables) using a pseudonym. This support should be embedded in the "identity-anonymization-tool" packed with EI.

Steps to recreate the issue
1. Create  a user from the management console (or using admin service)
2. Forget-me tool is configured with the default configurations in config.json
3. Run the tool with "./forget-me.sh -U remoteuser"

**Observations**
No impact to the user information
Default configuration resulted in error [1] as the sql is configured only for the bpmn related tables

Note - It is important to provide the support to replace the user information, even when the users are created via management console because we provide the support to manage user's via management console as well.

[1] https://github.com/wso2/product-ei/issues/1910

**Comment by milanperera** [comment]
The purpose of this tool is to anonymize PII if and only if a particular user is removed from the organization. That means user related information should not be there in the UM tables at the time of executing the tool. Hence it is unnecessary to provide the support replacing user information from UM tables.

**Comment by sashikamw** [comment]
As mentioned above, since the tool is provided to replacing user information, in case of user deletetion all relevant information will be cleared from the UM_USER and UM_USER_ATTRIBUTE tables, hence the information will not be maintained in the tables.

Also in EI, since we do not maintain third-party user information, considered that user information does not maintain unless particular data service or proxy logs the user PII in logs or DB.

**Comment by milanperera** [comment]
Yes, indeed.
