### ISSUE TITLE
Samples are linked to previous version in EI 6.2.0 Docs

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1929]
**Description:**
In Doc https://docs.wso2.com/display/EI620/Scheduled+Message+Forwarding+Processor

the samples in the bottom of the page are leading to ESB 500 pages.

**Comment by praneesha** [comment]
Fixed this in docs of WSO2 EI 6.1.1 and 6.x.x.

**Comment by Nirothipan** [comment]
In this also https://docs.wso2.com/display/EI620/Prioritizing+Messages sample is linked to ESB 600 page.

**Comment by praneesha** [comment]
Fixed this also in docs of all WSO2 EI versions.
