### ISSUE TITLE
Do we need to consider pseudonymizing trace information that appears in EI analytics?

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1931]
**Description:**
If tracing is enabled for a service that might contain user identification information in transport properties or context properties, that information is available in the analytics if a user who has access to the analytics dashboard, go deep into mediator level tracing. 

For example:
If a proxy service invoked with user information in the transport header (username:peter) trace logs contain user identification information as below.

![screenshot from 2018-03-07 18-36-27](https://user-images.githubusercontent.com/14962228/37093752-79387e10-2236-11e8-8695-28d1a7533a97.png)

From DB level, this information is maintained in an encoded format.

Could there be a valid use case whether we need to consider replacing user identification information that appears in the trace logs?

**Affected Version**
EI 6.1.1 update 23

**Comment by milanperera** [comment]
Enabling tracing or debug logs does not usually happen in a production scenario. However, if someone wants to enable them and anonymize, they will have to configure the tool. What we can do is to provide some example in the documentation.

**Comment by sashikamw** [comment]
@milanperera is it possible to anonymize the above information appearing in mediator trace? From the DB side, above information maintained in an encoded format.

**Comment by milanperera** [comment]
Yes, it is possible using the stream extension of the tool.
