### ISSUE TITLE
Invalid policy reference for cookie policy in BPMN and Human task UI

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1934]
**Description:**
WSO2 Cookie policy is not properly linked to the BPMN explorer and HumanTask explorer.

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
DB - Mysql 5.6
JDK - 1.8
Browser - Chrome Version 58.0.3029.96

**Steps to reproduce:**
1. Start the BPS profile
2. Go to BPMN and Human task UI (https://10.100.8.9:9445/humantask-explorer/ , https://10.100.8.9:9445/bpmn-explorer )
3. Click the "WSO2 cookie policy" to view the policy information

**Observations**
Failed to load the policy due to the incorrect reference

```
<div class="alert alert-warning" role="alert">This site uses cookies. By logging in to the site, you are agreeing on the usage of cookies. For more information, refer
--
  | <a href="%https.host%">WSO2 cookie policy</a>.
  | </div>
```

![screenshot from 2018-03-08 11-46-54](https://user-images.githubusercontent.com/14962228/37136579-379a5b4e-22c8-11e8-9e3f-ffc3bc75bcc3.png)

**Comment by milanperera** [comment]
This is fixed in [1]

[1] https://github.com/wso2/carbon-business-process/pull/513

**Comment by sashikamw** [comment]
Verified in EI 6.2.0 snapshot pack
