### ISSUE TITLE
High CPU usage in request error path due to a regex pattern matching

### ISSUE THREAD

**Issue by kasunbg** [wso2/product-ei#1940]
**Description:**
The AbstractListMediator's error path logic does a pattern matching to identify whether the thrown exception is due to a some woodstox exception. The regex pattern here searches the entire exception stack trace. If the stack trace is too large, this lead to high CPU usage.

In one scenario, we noticed that the entire payload was there in the exception message. Therefore, the total size of the stacktrace was 32KB. This lead to loads of runnable HTTPClientWorker threads which consume about 10% of CPU each. This is quite costly.

Therefore, we need to fix this issue. 

From my limited perspective, one option may be we should limit the maximum content length of the pattern matching.

[1] https://github.com/wso2/wso2-synapse/blob/968baa03f804d329a78cdee75a9fc12b2fcafff5/modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java#L104-L111

**Affected Product Version:**
ESB 5.0.0 / EI 6.1.1

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
In our test, we noticed that the stack trace can be as big as 32K.
Therefore, easiest way to re-produce this is to send a message of this much size to the pattern matching logic in [1]. 

**Related Issues:**
N/A

**Comment by malakaganga** [comment]
Duplicate with : https://github.com/wso2/product-ei/issues/1939
