### ISSUE TITLE
Include a note that PII should not be logged within the services

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1941]
**Description:**
Provide instructions to the developers, about the properties that should be logged and should not log. For example: when developing a proxy service as a best practice should not log any PII in the service. Better to include this information in the docs to guide the service developers.

https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
Added a note to [1] about the 'proxy service' example. Checking for other examples.

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
Note added.
