### ISSUE TITLE
Forced xml parser to build the xml message to validate bad xml document

### ISSUE THREAD

**Issue by nuwanw** [wso2/product-ei#1943]
EI uses AXIOM as a xml parser in message builders and This limitation is there because Axiom is doing streaming (pull) parsing, so parser will not read beyond what it needs to read (once it saw the end xml tag, there is no reason for parser to try reading beyond that since It identify it as well formed xml). So It process the first root element and continue the mediation flow with out throwing an error.

When a xml is not well formed(multi root xml document), message builder should throws an error and goes to fault sequence. using below property in passthru-http.properties, we can make ESB to force build message and validate. By default this value is false. 

force.xml.message.validation=true

**Comment by nuwanw** [comment]
Resolves https://github.com/wso2/wso2-synapse/pull/1061

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1061
