### ISSUE TITLE
HT_TASK_ATTACHMENT table maintained the information related to removed task instances

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1955]
**Description:**
The "HT_TASK_ATTACHMENT" table should not maintain the attachment details related to the removed human task.

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
OS - ubuntu 15.10
DB - mysql 5.6
JDK - 1.8

**Steps to reproduce:**
1. Deploy claimapproval human task
2. Invoke the task and complete a task (use an attachment for the task)
3. Execute the script to remove all the completed instances (mysql_clean.sql)

**Observations**
Information related to the completed instances got removed from the database
Attachment-related information maintained in the 'HT_TASK_ATTACHMENT' table for the deleted instances.

![screenshot from 2018-03-09 12-17-01](https://user-images.githubusercontent.com/14962228/37197291-3a30581c-23a0-11e8-8248-a4e20c5fda2d.png)

**Expected Behaviour**
We should remove the attachment-related from the database for the removed instances, as there is no purpose of maintaining attachments for the remove task instances

Note - Task information removed from the following tables, but human task explorer seems broken
HT_EVENT
HT_TASK_COMMENT
HT_ORG_ENTITY
HT_TASK_ATTACHMENT - X
HT_PRESENTATION_PARAM
HT_MESSAGE - X
HT_PRESENTATION_ELEMENT

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/wso2/product-ei/pull/1964/files

**Comment by sashikamw** [comment]
Verified the fix in EI 6.2.0 snapshot pack
