### ISSUE TITLE
ATTACHMENT table maintained the information related to removed task instances

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1958]
**Description**:
The "ATTACHMENT" table should not maintain the attachment details related to the removed human tasks.

**Affected Product Version**:
EI 6.1.1 update 23

**OS, DB, other environment details and versions**:
OS - ubuntu 15.10
DB - mysql 5.6
JDK - 1.8

**Steps to reproduce**:

1. Deploy claimapproval human task
2. Invoke the task and complete a task, (use an attachment for the task)
3. Execute the script to remove all the completed instances (mysql_clean.sql)

**Observations**
Information related to the completed instances got removed from the database
Attachment-related information maintained in the 'ATTACHMENT' table for the deleted instances.

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/wso2/product-ei/pull/1964

**Comment by sashikamw** [comment]
Verified the fix in EI 6.2.0 snapshot pack
