### ISSUE TITLE
Process initiated user should be updated according to the sample

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1959]
**Description:**
According to the LoanApprovalProcess.bar the process should be initiated by the "clerk" user and not by the 'client' user. Sample documentation should be corrected accordingly.

![screenshot from 2018-03-09 15-33-37](https://user-images.githubusercontent.com/14962228/37202033-687b6eaa-23af-11e8-8bef-c2ad5a70e7f1.png)

![screenshot from 2018-03-09 15-33-45](https://user-images.githubusercontent.com/14962228/37202038-6b54e4da-23af-11e8-8f00-bc1b9483e891.png)

[1] https://docs.wso2.com/display/EI6xx/Conditional+Branching

**Comment by praneesha** [comment]
Fixed in docs of all WSO2 Ei and WSO2 BPS versions. For example, see [1].

[1] https://docs.wso2.com/display/Ei6xx/Conditional+Branching
