### ISSUE TITLE
[Doc] Configuring with the Broker Profile -  EI 620

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#1965]
**Description:**

With the issue https://github.com/wso2/product-ei/issues/777 and fix https://github.com/wso2/product-ei/pull/938 do we still need to copy the jars from broker to EI libs as mentioned in Step 3 of https://docs.wso2.com/display/EI620/Configuring+with+the+Broker+Profile 
to configure the broker?

**Comment by praneesha** [comment]
This step is already removed in [1], as per the change mentioned in [2].

[1] https://docs.wso2.com/display/EI6xx/Configuring+with+the+Broker+Profile
[2] https://github.com/wso2/product-ei/pull/938
