### ISSUE TITLE
Document the parameters supported by identity-anonymization-tool for EI use cases

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1966]
**Description:**
Provide instructions on the parameters support by the identity-anonymization-tool for EI

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
OS - Ubuntu 15.10
DB - mysql 5.6

Include the parameters supported by identity-anonymization-tool tool for EI use cases.

**Comment by nilminiwso2** [comment]
Did some changes to [1]: Added some links and bookmarks.

[1] https://docs.wso2.com/display/EI6xx/Removing+References+to+Deleted+User+Identies
