### ISSUE TITLE
Maintainability become difficult when the number of log files increased

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1969]
**Description:**
Removing the original file after temp file generation will create a new wso2carbon.log. Execution of the tool will replace the information in the latest wso2carbon.log and wso2carbon.log.temp.txt and create a set of temp files for these two. When the number of log files growing it will become difficult to maintain.

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
OS - ubuntu 15.10
DB - Mysql 5.6

**Steps to reproduce:**
1. Start the server and perform some login operations from user A, user B
2. Stop the server and execute the tool to replace user A -> this will create wso2carbon.log.temp.txt
3. Remove the wso2carbon.log which contains the user information
4. Restart the server (new wso2carbon.log will be created ) and login with User B (Related user login will be logged in the new wso2carbon.log)
5. Execute the tool to replace user B, 

**Observations**
This will create a temp log in the following format.
wso2carbon.log -> wso2carbon.log.temp.txt
wso2carbon.log.temp.txt -> wso2carbon.log.temp.txt.temp.txt

When the number of log files growing it will be difficult to maintain the logs in the log run.  Better to come up with a proper mechanism to maintain the logs.

**Comment by milanperera** [comment]
This should be supported from the identity-anonymization-tool itself. In EI, we are just packaging the tool.

**Comment by sashikamw** [comment]
Moved the issue to https://github.com/wso2/identity-anonymization-tool/issues/70
