### ISSUE TITLE
Observed a  Invalid default value for 'UPDATED' error when running activiti.mysql.create.substitute.sql against MYSQL 5.7

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-ei#1981]
**Suggested Labels:**
Type/Bug
Priority/High
Affected wso2-ei-6.2.0 SNAPSHOT

**Affected Product Version:**
Affected wso2-ei-6.2.0 SNAPSHOT
**OS, DB, other environment details and versions:**    
Ubuntu 16.04
MYSQL 5.7

**Steps to reproduce:**
Follow the doc in [1]. When running dbscripts against MYSQL 5.7 for activiti.mysql.create.substitute.sql
Observed the following ERROR in the mysql 5.7 server backend

ERROR 1067 (42000): Invalid default value for 'UPDATED'

Also there is no  mysql5.7 script in following locations
wso2ei-6.2.0-SNAPSHOT/wso2/business-process/dbscripts/bps/bpel
wso2ei-6.2.0-SNAPSHOT/wso2/business-process/dbscripts/bps/bpmn

[1].https://docs.wso2.com/display/EI611/Changing+the+Default+Databases+for+BPMN+and+BPEL#5b9d0fc8509c414d9fe316541eaab04f

**Comment by himasha** [comment]
This seems to be an issue with SQL_MODE default configuration in MySQL 5.7.8 Removing NO_ZERO_DATE from SQL_MODE seems to resolve the issue. 

[1] https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-8.html#mysqld-5-7-8-sql-mode

**Comment by ShanikaWickramasinghe** [comment]
Executed the script as below against MYSQL 5.7 and this resolves the issue

create table ACT_BPS_SUBSTITUTES (
USERNAME varchar(255) not null,
SUBSTITUTE varchar(255) not null,
TASK_LIST varchar(1000),
UPDATED timestamp DEFAULT CURRENT_TIMESTAMP,
SUBSTITUTION_START timestamp not null DEFAULT CURRENT_TIMESTAMP,
SUBSTITUTION_END timestamp null,
ENABLED tinyint default 1,
CREATED timestamp not null DEFAULT CURRENT_TIMESTAMP,
TRANSITIVE_SUBSTITUTE varchar(255) null,
TENANT_ID int NOT NULL,
primary key (USERNAME, TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/carbon-business-process/pull/517
