### ISSUE TITLE
Update the product version for EI analytics

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1982]
**Description:**
Update the product version in EI analytics pack

![screenshot from 2018-03-13 12-30-25](https://user-images.githubusercontent.com/14962228/37326950-5758a652-26ba-11e8-9151-b4d36cd9662c.png)

**Affected Product** 
EI 6.2.0 snapshot pack (13/03/2018)

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/product-ei/pull/1998
