### ISSUE TITLE
Clean up script does not consider the time as mentioned in the doc

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1985]
**Description:**
According to the documentation, clean-up script can be used to remove processes older than 30 days. But there is no particular restriction in the script, we can clean all the completed tasks irrespective of the date.

![screenshot from 2018-03-13 14-06-16](https://user-images.githubusercontent.com/14962228/37330642-c3a2562a-26c7-11e8-8e35-7e0fb26a7398.png)

**Comment by nilminiwso2** [comment]
Fixed
