### ISSUE TITLE
Explain the structure and purpose of clean up scripts

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1986]
**Description:**
Explain the structure of database scripts maintained for BPEL, HUMAN TASK and BPMN [1]. According to the current documentation, it does not contain the information related to the cleanup scripts per given ID.

Current GDPR doc [2] does not instruct the user on where to find the per id scripts and how to use those.

Therefore please document following points
1. There are 3 main folders inside clean up script (bpel, bpmn, humantask)
2. Explain what scripts are maintained in humantask directory
3. Explain why we maintained separate human task folder related to per id scripts
4. Explain that for per id scripts, bpel and human task is separated but for the original script this is not the case

[1] https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts
[2] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
Added the content to [1].

[1] https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts
