### ISSUE TITLE
Privacy Policy and Cookie policy goes to error page in Analytics Server

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1988]
**Description:**
Cookie policy and the Privacy policy in Analytics Dashboard resulted in 405 error

**Affected Product Version:**
EI 6.2.0 snapshot - 13/03/2018

**OS, DB, other environment details and versions:**    
OS - Ubuntu 15.10
DB - mysql 5.6

**Steps to reproduce:**
1. Start the analytics server
2. Go to analytics Dashboard

**Observations**
1. Cookie Policy directed to 405 error page
2. Privacy Policy directed to 405 error page

![screenshot from 2018-03-13 15-54-45](https://user-images.githubusercontent.com/14962228/37336266-e354874a-26d6-11e8-99f5-ff037de9b65f.png)

**Comment by sashikamw** [comment]
Issue moved to https://github.com/wso2/product-das/issues/309

**Comment by milanperera** [comment]
Also, in EI, we don't expose the analytics dashboard to external users. Only system administrators and specific users from the organization are only allowed to use the analytics. Hence reducing the severity level.

**Comment by sashikamw** [comment]
In EI analytics dashboard cater to EI statistics as well as BPMN statistics, we need to consider both these use cases.

**Comment by Nirothipan** [comment]
Closing as moved to wso2/product-das#309
