### ISSUE TITLE
Correct the command to execute the identity-anonymization-tool 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1991]
**Description:**
The method to execute the identity-anonymization-tool has changed therefore correct the doc accordingly. For example previously it was "./forget-me.sh -U Sam" now ".**/forgetme.sh -U Sam**", adjust the doc [1] accordingly

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
Fixed.
