### ISSUE TITLE
Include a step to add the relevant driver when executing the identity-anonymization-tool

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1992]
**Description:**
It is mandatory to add the relevant driver to execute the identity-anonymization-tool. For example, to replace the params for BPMN in MySQL, mysql driver should be added to "<EI_HOME>/wso2/tools/identity-anonymization-tool/lib directory.  This should be documented as a step in [1].

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-BPMN(activiti)component

**Comment by nilminiwso2** [comment]
The Anonymization tool is used for RDBMS data in the BPMN component, as well as the Analytics profile. Therefore added the following to the two sections:
- Add the relevant drivers for your BPMN-specific database to the <EI_HOME>/wso2/tools/identity-anonymization-tool/lib directory. For example, if you have changed your BPMN database from the default H2 database to MySQL, copy the MySQL driver to this given directory.
- Add the relevant drivers for your Analytics-specific databases to the <EI_HOME>/wso2/tools/identity-anonymization-tool/lib directory. For example, if you have changed your Analytics databases from the default H2 instances to MySQL, copy the MySQL driver to this given directory
