### ISSUE TITLE
Instruct the user to configure the log-file-path according to the product location

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1994]
**Description:**
Document the 'log-file-path' in the config.jsn should be adjusted depending on the product path that user wants to execute.

For example: To execute the scripts for BPS profile "log-file-path" should be configured as below

```
 {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "<EI_HOME>/wso2/business-process/repository/logs",
      "log-file-name-regex" : "(audit.log|warn.log|wso2carbon.log|Sample-proxyservice.log)(.)*"
    }
```

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-BPMN(activiti)component

**Comment by nilminiwso2** [comment]
AFAIU, the log-file-path should always be the absolute file path. 

Therefore, I changed the log-file-path values in the config.json file to the following:
- "log-file-path" : "<EI_HOME>/wso2/business-process/repository/logs"
- "log-file-path" : "<EI_HOME>/repository/logs"

Also, added the following note:
"Be sure to replace <EI_HOME> in the "log-file-path" with the actual directory path."

Please reopen if anything is incorrect.

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information
