### ISSUE TITLE
Failed to publish BPMN statistcs

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1999]
**Description:**
Unable to publish BPMN statistics 

**Affected Product Version:**
EI 6.2.0 snapshot (13/03/2018)

**OS, DB, other environment details and versions:**    
OS - Ubuntu 15.10
DB - mysql 5.6

**Steps to reproduce:**
1. Configure BPMN analytics as documented in [1]
2. Invoke a sample [2] to get statistics

**Observations**
Statistics not published in EI server
[1] https://docs.wso2.com/display/EI6xx/Prerequisites+to+publish+BPMN+Statistics
[2] https://docs.wso2.com/display/EI6xx/Conditional+Branching

**Comment by sameeragunarathne** [comment]
Closing this issue since we have deprecated bpmn analytics component with new stream processor integration.
