### ISSUE TITLE
Query Param is not Working with Dataservices

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#2001]
**Description:**
Query params are not working with Dataservices when we invoke the request through Passthrough transport (8280). It's working fine with Tomcat Transport (9763).

This was identified while trying out [1] in a WSO2 EI 6.2.0 vanilla pack downloaded from [2].

The following cURL command does not work:
curl -v http://localhost:8280/services/DOCTORS_DataService/getDoctors?SPECIALITY=surgery

It gives the following error:
<axis2ns14:DataServiceFault xmlns:axis2ns14="http://ws.wso2.org/dataservice">
    <axis2ns14:current_params>{}</axis2ns14:current_params>
    <axis2ns14:source_data_service>
        <axis2ns14:data_service_name>DOCTORS_DataService</axis2ns14:data_service_name>
        <axis2ns14:description>N/A</axis2ns14:description>
        <axis2ns14:location>/DOCTORS_DataService.dbs</axis2ns14:location>
        <axis2ns14:default_namespace>http://ws.wso2.org/dataservice</axis2ns14:default_namespace>
    </axis2ns14:source_data_service>
    <axis2ns14:ds_code>INCOMPATIBLE_PARAMETERS_ERROR</axis2ns14:ds_code>
    <axis2ns14:current_request_name>_get_getdoctors</axis2ns14:current_request_name>
</axis2ns14:DataServiceFault>

Works correctly for the following commands:

curl -v http://localhost:8280/services/DOCTORS_DataService/getDoctors?SPECIALITY=surgery -H "Content-Type:application/x-www-form-urlencoded"

curl -v http://localhost:9763/services/DOCTORS_DataService/getDoctors?SPECIALITY=surgery

[1] https://docs.wso2.com/display/EI6xx/Sending+a+Simple+Message+to+a+Datasource
[2] https://wso2.org/jenkins/job/products/job/product-ei/404/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
FIxed with https://github.com/wso2/wso2-synapse/pull/1066.
