### ISSUE TITLE
Format of the log file path in windows

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#2005]
**Description:**
Include to the document [1] that the path for the log file in windows should be appearing in the below format

Ex: C:/Users/Administrator/Desktop/wso2ei-6.2.0-SNAPSHOT/repository/log 

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
Added a note stating that the front slash should be used, instead of the back slash (for Windows directory path).
