### ISSUE TITLE
Instance data records related to a completed human task does not get deleted in ODE_XML_DATA Table in ORACLE

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-ei#2006]
**Description:**
Instance data records related to the completed human task are still available in the ODE_XML_DATA when tested against Oracle DB

**Suggested Labels:**
Type/Bug
Compliance/GDPR
Priority/High

**Affected Product Version:**
EI 6.2.0 snapshot (13/03/2018)

**OS, DB, other environment details and versions:**    
DB - Oracle  12c
OS ubuntu 16.04

**Steps to reproduce:**
1. Deploy claimapproval human task as in [1]
2. Invoke the task and complete a task
3. Execute the script to remove all the completed instances  (oracle_clean.sql)
/wso2ei-6.2.0-SNAPSHOT/wso2/business-process/repository/resources/cleanup-scripts/bpel/oracle_clean.sql 

**Observation**
Instance data records related to the completed Human task are still available in the ODE_XML_DATA 

[1]. https://docs.wso2.com/display/EI611/Claims+Approval+Task+Sample

**Comment by nandika** [comment]
The correct script to execute for GDPR compliance is to oracle_clean_by_id.sql script. The oracle_clean.sql is for bulk delete option to reduce the db growth.

**Comment by ShanikaWickramasinghe** [comment]
In doc [1] under the heading **Human Task and BPEL components** it has mentioned two methods to remove process and task instances as below
1. Remove all completed tasks/processes. This can be configured to a particular period.
2. Remove a specific task/process of a given user ID.
In [2] it has listed oracle_clean.sql as a script that can be used to remove all instances of completed BPMN, BPEL, and Human Task processes. So this information will be a misguide for the users if we are not using the  oracle_clean.sql script in a scenario as mentioned in the issue.


[1]. https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information
[2]. https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts

**Comment by nilminiwso2** [comment]
The doc already explains the two different sets of scripts that should be used for deleting process in bulk, as opposed to deleting individual tasks. Did some changes to the doc to make the point more clear [1]. 

[1] https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts
