### ISSUE TITLE
Impossible to visualize the Mediation Flow inside a Call Template 

### ISSUE THREAD

**Issue by ajanthan** [wso2/product-ei#2009]
**Description:**
It is impossible to track the message flow in Analytics when a call template is used. Whole contents of call template are displayed as an InvokeMediator box.It is helpful debugging issues or tracing messages.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    
OSX 10.13.3

**Steps to reproduce:**
Try [sample 751](https://docs.wso2.com/display/EI611/Sample+751%3A+Message+Split+Aggregate+Using+Templates with EI analytics enabled and view analytics dashboard.See the attached image for more details.
<img width="1142" alt="screen shot 2018-03-14 at 11 45 00 am" src="https://user-images.githubusercontent.com/525801/37424321-6829e69e-277d-11e8-8d82-4e6f122e0f98.png">
This issue applicable to dynamic sequences and endpoints as well.

**Related Issues:**

**Comment by Nirothipan** [comment]
Similiar issue : https://github.com/wso2/product-ei/issues/2018
