### ISSUE TITLE
Add missing details related to Remove the process instances per user

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-ei#2012]
**Description:**

**Suggested Labels:**
Type/Docs
GDPR/Compliance
Priority/High

**Affected Product Version:**
EI 6.2.0 snapshot (13/03/2018)

**Description**
Refer to doc [1]. Under the heading **Remove the process instances per user** Include that we need to find the related id according of a task and include that id value in the script manually before running the following clean up scripts

mssql_clean_by_id.sql
mysql_clean_by_id.sql
oracle_clean_by_id.sql
postgresql_clean_by_id.sql

Eg :- If theres a completed human task in BPEL Profile we need to login to BPEL management console > Access Instances (BPEL) > Take the instance id from there related to the particular task and include that id value in the 
wso2ei-6.2.0-SNAPSHOT/wso2/business-process/repository/resources/cleanup-scripts/bpel/oracle_clean_by_id.sql 
script and need to run the script. 
Likewise can obtain the human task id for the relavent task by accessing humantask explorer and include that id value in the wso2ei-6.2.0-SNAPSHOT/wso2/business-process/repository/resources/cleanup-scripts/humantask/oracle_clean_by_id.sql 

[1]. https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts

**Comment by nilminiwso2** [comment]
We can only "identify the processes/tasks that are specific to a given user ID, and remove them individually". Therefore, we need to give the Process/Task ID in the new clean-up script. 

Updated [1] and [2].
[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-RemovingHumanTaskandBPELprocessinstances
[2] https://docs.wso2.com/display/EI6xx/Database+Clean-up+Scripts
