### ISSUE TITLE
Remove the per service log from the default config.json

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#2013]
**Description:**
Default config.json of the EI contains the sample per service proxy that used for testing purpose. Better to remove this from the default config.json to avoid confusions for the users.

**Affected Product Version:**
EI 6.2.0 snapeshot (15/03/2018)

**OS, DB, other environment details and versions:**    
DB - h2
OS - ubuntu 15.10

```
{
  "processors" : [
    "log-file"
  ],
  "directories": [
    {
      "dir": "log-config",
      "type": "log-file",
      "processor" : "log-file",
      "log-file-path" : "repository/logs",
      "log-file-name-regex" : "(audit.log|warn.log|wso2carbon.log|Sample-proxyservice.log)(.)*"
    },
    {
      "dir": "sql",
      "type": "rdbms",
      "processor" : "rdbms"
    }
  ],
  "extensions": [
    {
      "dir": "datasources",
      "type": "datasource",
      "processor" : "rdbms"
    }
  ]
}
```

**Comment by himasha** [comment]
Updated version to incorporate fix with https://github.com/wso2/product-ei/pull/2015
