### ISSUE TITLE
Cannot Start a Process in the BPMN Explorer

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#2017]
**Description:**
As per the instructions mentioned under the "Canceling appointments using the BPMN explorer" section in [1], when you click Start as per step 4, the "Start Process" form does not load.

Instead, a message box is displayed as shown in the screenshot attached. A screenshot of the Browser error is also attached herewith.
![screen shot 2018-03-15 at 12 31 24 pm](https://user-images.githubusercontent.com/11707273/37449117-19737a9c-284f-11e8-9abb-37fb9d6179aa.png)
![screen shot 2018-03-15 at 12 45 56 pm](https://user-images.githubusercontent.com/11707273/37449118-19a77518-284f-11e8-9d1a-1206dc9c4812.png)

[1] https://docs.wso2.com/display/EI6xx/Managing+a+business+process 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by himasha** [comment]
Looks like [1] is missing the step where form properties need to be added to bpmn start element

**Comment by praneesha** [comment]
Updated the step 7 in [1] to add the form for the Start Event and then the form is correctly displayed in the BPMN Explorer now.

[1] https://docs.wso2.com/display/EI6xx/Managing+a+business+process
