### ISSUE TITLE
Can not Visualize the Mediation flow inside Call template

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#2018]
**Description:**
When using a call template mediator with dynamic sequence or dynamic endpoint, In the analytics mediation flow visualizer, the details inside those call template or dynamic sequence are not displayed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Same issue found in: https://github.com/wso2/product-ei/issues/2009
