### ISSUE TITLE
Modify Step 5 under BPMN (activiti) component to include command for running forgetme tool according to the operating system

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-ei#2022]
**Suggested Labels:**
Type/Docs
GDPR/Compliance
Priority/High

**Affected Product Version:**
EI 6.2.0

**Description**
In [1] Under **"BPMN (activiti) component"** under step 5 modify the given information as below

Execute one of the following commands depending on your operating system:
On Linux/Mac OS: ./forgetme.sh -U <username>
On Windows: forgetme.bat -U <username>

[1]. https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information

**Comment by nilminiwso2** [comment]
[1] https://docs.wso2.com/display/EI620/General+Data+Protection+Regulation+%28GDPR%29+for+WSO2+EI
