### ISSUE TITLE
Stream configurations required to support BPMN analytics via identity-anonymization-tool

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#2023]
**Description:**
Provide the stream definition required to configure the BPMN statistics in the "identity-anonymization-tool" in [1]. 

According to the current documentation, we have provided the sample stream configuration, rather than that we need to provide the information to configure the BPMN analytics streams.

Sample configurations used can be found in https://github.com/wso2/product-ei/issues/2002

Also if we define the directory name as "stream", config.json should be configured as below.

```

{    "processors": [        "analytics-streams"    ],    "directories": [        {            "dir": "streams",            "type": "analytics-streams",            "processor": "analytics-streams"        }    ]}
--



```

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-RemovingPIIfromtheAnalyticsprofile

**Comment by nilminiwso2** [comment]
Done.
