### ISSUE TITLE
Output mismatch When trying Request doctors' information in QSG

### ISSUE THREAD

**Issue by mathuriga** [wso2/product-ei#2030]
**Description:**
When I'm trying to Request doctors' information as mentioned in QSG, I'm getting different output which is not similar output mentioned in QSG.

Output Which I got :
`<DOCTORSLIST
	xmlns="http://ws.wso2.org/dataservice">
	<DOCTOR>
		<NAME>thomas collins</NAME>
		<HOSPITAL>grand oak community hospital</HOSPITAL>
		<SPECIALITY>surgery</SPECIALITY>
		<AVAILABILITY>9.00 a.m - 11.00 a.m</AVAILABILITY>
		<CHARGE>7000</CHARGE>
	</DOCTOR>
	<DOCTOR>
		<NAME>anne clement</NAME>
		<HOSPITAL>clemency medical center</HOSPITAL>
		<SPECIALITY>surgery</SPECIALITY>
		<AVAILABILITY>8.00 a.m - 10.00 a.m</AVAILABILITY>
		<CHARGE>12000</CHARGE>
	</DOCTOR>
	<DOCTOR>
		<NAME>seth mears</NAME>
		<HOSPITAL>pine valley community hospital</HOSPITAL>
		<SPECIALITY>surgery</SPECIALITY>
		<AVAILABILITY>3.00 p.m - 5.00 p.m</AVAILABILITY>
		<CHARGE>8000</CHARGE>
	</DOCTOR>
</DOCTORSLIST>`

**Steps to Reproduce **
Follow the QSG

**Comment by praneesha** [comment]
Verified and updated the docs of all WSO2 EI versions with the following output.

<DOCTORSLIST xmlns="http://ws.wso2.org/dataservice">
<DOCTOR>
    <NAME>thomas collins</NAME>
    <HOSPITAL>grand oak community hospital</HOSPITAL>
    <SPECIALITY>surgery</SPECIALITY>
    <AVAILABILITY>9.00 a.m - 11.00 a.m</AVAILABILITY>
    <CHARGE>7000</CHARGE>
</DOCTOR>
<DOCTOR>
    <NAME>anne clement</NAME>
    <HOSPITAL>clemency medical center</HOSPITAL>
    <SPECIALITY>surgery</SPECIALITY>
    <AVAILABILITY>8.00 a.m - 10.00 a.m</AVAILABILITY>
    <CHARGE>12000</CHARGE>
</DOCTOR>
<DOCTOR>
    <NAME>seth mears</NAME>
    <HOSPITAL>pine valley community hospital</HOSPITAL>
    <SPECIALITY>surgery</SPECIALITY>
    <AVAILABILITY>3.00 p.m - 5.00 p.m</AVAILABILITY>
    <CHARGE>8000</CHARGE>
</DOCTOR>
</DOCTORSLIST>

For example, see [1].

[1] https://docs.wso2.com/display/EI6xx/Quick+Start+Guide#QuickStartGuide-Requestdoctors'information
