### ISSUE TITLE
ei-patterns.xml should include all the possible patterns

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-ei#2031]
**Description:**
ei-patterns.xml of the forget me tool should include all the possible patterns without letting the user to add them as the user might not know what regex patterns to add here. (One such instance is documented in [1] 
where the regex pattern to anonymize the username is mentioned)

All other occurrences should be supported out of the box from the product, hence pre-configured in the ei-patterns.xml. IS is also providing this support out of the box

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information#RemovingPersonallyIdentifiableInformation-how_PII_is_stored

**Comment by milanperera** [comment]
@dilinisg: EI does not print any username's OOB unless otherwise, a user does so. 
Please refer the document[1] carefully.

[1] https://docs.wso2.com/display/EI6xx/Removing+Personally+Identifiable+Information
