### ISSUE TITLE
Documentation issue in Inbound Endpoint Kafka Protocol

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#2032]
**Description:**
In Kafka Inbound Protocol page change the directory which jaas.conf file should be copied to 
<EI_HOME>/repository/conf/identity (Need to create the directory structure)

Also in
Sample 904: Inbound Endpoint Kafka Protocol Sample add the following note as well

Note
If you are using kafka_2.x.x-0.8.2.0 or later, you also need to add the kafka-clients-0.8.x.x.jar file to the <EI_HOME>/lib  directory.

If you are using a newer version of ZooKeeper, add the jaas.conf file to the <EI_HOME>/repository/conf/identity directory. This is required because Kerberos authentication is enforced on newer versions of ZooKeeper.

**Comment by praneesha** [comment]
Updated the note accordingly and added the updated note to the Sample 904 doc.

This is done in docs of all WSO2 EI versions.

For example, see [1] & [2].

[1] https://docs.wso2.com/display/EI6xx/Kafka+Inbound+Protocol
[2] https://docs.wso2.com/display/EI6xx/Sample+904%3A+Inbound+Endpoint+Kafka+Protocol+Sample
