### ISSUE TITLE
[Doc] Add "enableCacheControl" and "includeAgeHeader" for cache mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2036]
**Description:**
Update cache mediator documentation [1] with "enableCacheControl" and "includeAgeHeader" support which were introduced in https://github.com/wso2/carbon-mediation/pull/970

[1] - https://docs.wso2.com/display/EI620/Cache+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Updated this in [1].

[1] https://docs.wso2.com/display/EI6xx/Cache+Mediator
