### ISSUE TITLE
[Doc] Quick start quide

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2037]
**Description:**
1. Broker client jars are already packed within EI-HOME/lib. Therefore, no need to copy them again in [1]. 

2. andes-client-3.2.13.jar should be corrected to andes-client-3.2.45.jar

3. With in the HealthcareAPI inside the SampleServicesCompositeApplication_1.0.0.car [2] file payload factory should be corrected as follows. Should add quotations for type json.

```
         <payloadFactory media-type="json" description="">
            <format>{     "appointmentNumber":"$1",     "doctor":"$2",     "patient":"$3",     "fee":"$4",     "confirmed":"false",     "card_number":"$5"     }</format>
            <args>
               <arg evaluator="xml" expression="$ctx:uri.var.appointment_id"/>
               <arg evaluator="xml" expression="$ctx:doctor_details"/>
               <arg evaluator="xml" expression="$ctx:patient_details"/>
               <arg evaluator="xml" expression="$ctx:actual_fee"/>
               <arg evaluator="xml" expression="$ctx:card_number"/>
            </args>
         </payloadFactory>
```

[1] - https://docs.wso2.com/display/EI620/Quick+Start+Guide#QuickStartGuide-DownloadandsetupWSO2EI
[2] - https://docs.wso2.com/display/EI620/Quick+Start+Guide#QuickStartGuide-Definethemessagemediationsequence

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
1. the step to copy the Broker client JAR files is removed now.
2. We need not mention the andes-client-3.2.13.jar as per step 1 above.
3. Uploaded the updated CAR file in [1].

[1] https://github.com/wso2-docs/WSO2_EI/blob/master/Quick_Start_Guide_Artifacts/SampleServicesCompositeApplication_1.0.0.car

**Comment by prabushi** [comment]
It is not required to change to quotations in payload. Therefore, reverted the change in https://github.com/wso2-docs/WSO2_EI/pull/49
