### ISSUE TITLE
[QSG/Tutorials] - Cancellation Logic is Not Getting Applied

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#2043]
**Description:**
When following both [1] and [2], the cancellation logic that's given is not getting applied.

1. Even though we set the appointment date with a gap of more than 3 days, as follows, we receive an email saying the cancellation is rejected.

```
{ "name": "John Doe",
  "dob": "1940-03-19",
  "ssn": "234-23-525",
  "address": "California",
  "phone": "8770586755",
  "email": "praneesha@wso2.com",
  "doctor": "thomas collins",
  "hospital": "grand oak community hospital",
  "cardNo": "7844481124110331",
  "appointment_date": "2018-03-14"
}
```

2. Also, the Task mentioned in [2] is not being created.

[1] https://docs.wso2.com/display/EI6xx/Quick+Start+Guide
[2] https://docs.wso2.com/display/EI6xx/Managing+a+business+process

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by himasha** [comment]
In  the steps of [1] there are no instructions to apply conditional expressions to gateway elements. Also the gateway type used should be exclusive gateway. Refer the screenshot of deployed bar from [2].
<img width="905" alt="bpmn_model" src="https://user-images.githubusercontent.com/9687840/37635866-3d8b2924-2c24-11e8-8cee-e3243f6968d0.png">


[1] https://docs.wso2.com/display/EI6xx/Quick+Start+Guide
[2] https://github.com/wso2-docs/WSO2_EI/blob/master/Quick_Start_Guide_Artifacts/AppointmentCancellation.bar

**Comment by praneesha** [comment]
Updated [1] and verified the output.

Logics of all the 3 scenarios are working fine now,

[1] https://docs.wso2.com/display/EI6xx/Managing+a+business+process
