### ISSUE TITLE
Internal Server Error on logout (SSO management console)

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-ei#2050]
**Description:**
When EI is configured to participate in SSO with wso2 products, Upon logout it throws Error 500 - Internal Server Error with following Error in stack trace:
java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by org.wso2.carbon.identity.authenticator.saml2.sso.common_5.2.0

**Suggested Labels:**
saml,ei,sso

**Affected Product Version:**
EI - 6.1.1

**OS, DB, other environment details and versions:**    
Windows

**Steps to reproduce:**
Setup EI Mangement console SSO with Identity Server.
Login and logout

**Comment by malakaganga** [comment]
Fixed with : https://github.com/wso2-extensions/identity-carbon-auth-saml2/pull/46

**Comment by prabushi** [comment]
Relevant identity-carbon-auth-saml2 version with the public fix is not upgraded for EI 6.3.0-Mxx yet.
