### ISSUE TITLE
[Bug] WSO2 MB Connection URL (JMS) is not working with service proxy to publish a message in a Topic

### ISSUE THREAD

**Issue by fshomou** [wso2/product-ei#2052]
**Description:**
I’m using a service proxy in order to publish a message to a Topic.

I’m facing this issue, with service proxy (code A) I’m not able to publish a message to a Topic, instead of that a queue in the queue list has been created, it is a strange behavior.

If I use service proxy (code B), I can publish a message to the Topic.

It seems that (connectionfactory.TopicConnectionFactory=a**mqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675**') is not working.

Code A: 
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"  name="TestProxy" startOnLoad="true"        statistics="disable"  trace="disable"  transports="http">
   <target>
      <inSequence>
         <property name="OUT_ONLY" scope="default" type="STRING" value="true"/>
         <property name="FORCE_SC_ACCEPTED"
                   scope="axis2"
                   type="STRING"
                   value="true"/>
         <log level="custom">
            <property name="Message"
                      value="************** Start PublisherProxy**************"/>
         </log>
        <send>
            <endpoint name="test">
               <address uri="jms:/testtopic?transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory&amp;java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory&amp;connectionfactory.TopicConnectionFactory=amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'&amp;transport.jms.ConnectionFactoryType=topic"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </target>
   <description/>
</proxy>
```

Code B 
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"  name="TestProxy"  startOnLoad="true"        statistics="disable" trace="disable" transports="http">
   <target>
      <inSequence>
         <property name="OUT_ONLY" scope="default" type="STRING" value="true"/>
         <property name="FORCE_SC_ACCEPTED"
                   scope="axis2"
                   type="STRING"
                   value="true"/>
         <log level="custom">
            <property name="Message"
                      value="************** Start PublisherProxy**************"/>
         </log>
        <send>
            <endpoint name="test">
               <address uri="jms:/testtopic?transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory&amp;java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory&amp;java.naming.provider.url=conf/jndi.properties&amp;transport.jms.DestinationType=topic"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </target>
   <description/>
</proxy>
```
**Affected Product Version:**
EI-6.1.1
MB-3.2.0

**Steps to reproduce:**
- create Topic testtopic in the MB broker
- use code A

**Suggested Labels:**
Bug, Integrator, MB

**Comment by mathieubouchard** [comment]
The problem is probably caused by the encoding of the second "?" character.

jms:/testtopic **?** transport.jms.ConnectionFactoryJNDIName=TopicConnectionFactory&amp;java.naming.factory.initial=org.wso2.andes.jndi.PropertiesFileInitialContextFactory&amp;connectionfactory.TopicConnectionFactory=amqp://admin:admin@clientID/carbon **?** brokerlist='tcp://localhost:5675'&amp;transport.jms.ConnectionFactoryType=topic

The parsing will probably fail after the second `?` is read. Since the `transport.jms.ConnectionFactoryType=topic` parameter is added after the second `?`, it is probably not read and the default (queue) is used instead.

**Comment by PetteriPertola** [comment]
Was this ever solved? I can't get any of the connection URI properties to work after the first ? e.g.:
jms:/queueName?transport.jms.ConnectionFactoryJNDIName=<NAME> 
is never working for me
