### ISSUE TITLE
License header is appended to pop up window

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2054]
**Description:**
When enabling debug following the path Configure -> Logging -> Edit Log Level, WSO2 License header is appended to the pop up window.

![licence-append](https://user-images.githubusercontent.com/5234623/37886428-fc8a76a0-30d8-11e8-8248-58a791ead2c3.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Similiar issue https://github.com/wso2/product-ei/issues/469

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/carbon-commons/pull/303
