### ISSUE TITLE
Migration client for data, encrypted using Optimal Asymmetric Encryption Padding.

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#2055]
**Description:**
Crypto util uses a modified crypto algorithm (RSA+OAEP). Due to this change, we migrate the passwords which are encrypted using old (RSA) using the new algorithm.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.9.0, ESB 5.0.0, EI 6.0.0, EI 6.1.0 & EI 6.1.1

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/product-ei/pull/2033
