### ISSUE TITLE
Expected response not generated from a SOAP to REST proxy in a WUM updated ESB 4.9 pack

### ISSUE THREAD

**Issue by amandaJayanetti** [wso2/product-ei#2056]
**Description:**
Expected response not generated from a SOAP to REST proxy when a WUM updated ESB 4.9 pack is used. This issue is not present in a vanilla pack.

**Suggested Labels:**
Type/bug

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.9.0 (WUM updated)

**OS, DB, other environment details and versions:**    
JDK 1.8

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
This issue has arisen by not specifying the contentType header properly and was sorted after specifying it correctly. Hence closing.
