### ISSUE TITLE
[Urgent] Producer caching is not working in failover scennario

### ISSUE THREAD

**Issue by cgchamath** [wso2/product-ei#2073]
**Description:**
In ESB 4.9.0 the document states parameters to configure producer caching [1]. However when testing although this is enabled the functionality is not as expected. Connections are still being created although the created connections are not closed.

[1] - https://docs.wso2.com/display/ESB490/JMS+Transport

**Suggested Labels:**
Severity/Critical

**Suggested Assignees:**
nandika@wso2.com

**Affected Product Version:**
4.9.0
5.0.0

**Comment by milindaperera** [comment]
Enable Producer caching

Add connection factory definition under JMS transportSender element in <ESB_HOME>/repository/axis2/axis2.xml as follows:

```xml
<transportSender name="jms" class="org.apache.axis2.transport.jms.JMSSender">
          <parameter name="stockquote2QueueCon" locked="false">
              <parameter name="java.naming.factory.initial" locked="false">org.wso2.andes.jndi.PropertiesFileInitialContextFactory</parameter>
              <parameter name="java.naming.provider.url" locked="false">repository/conf/jndi.properties</parameter>
              <parameter name="transport.jms.ConnectionFactoryJNDIName" locked="false">QueueConnectionFactory</parameter>
              <parameter name="transport.jms.CacheLevel">producer</parameter>
              <parameter name="transport.jms.MaxJMSConnections">20</parameter>
              <parameter name="transport.jms.Destination">stockquote2</parameter>
          </parameter>
</transportSender>
```

Then add “transport.jms.ConnectionFactory“ URI parameter as follows:

```xml
<send>
    <endpoint>
        <address uri="jms:/stockquote2?transport.jms.ConnectionFactory=stockquote2QueueCon"/>
    </endpoint>
</send>
```

**Comment by milindaperera** [comment]
Following are not working with above configuration:
1. Connections, Sessions, and producers get destroyed and recreated in failover scenario seamlessly.
2. Test destination in URI query parameters.
