### ISSUE TITLE
CDATA tag in Developer studio source view disapears after save changes.

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-ei#2080]
**Description:**
 CDATA tag in the source editor, it appears that it works when I save the change (CTRL-S) but if close the editor and reopens (switch to design view and again switch to source view) the file with the change where the CDATA tag disappeared. 

**Suggested Labels:**
Dev Studio 

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Add configuration with CDATA  in source view and save the changes. 
Restart the editor or switch to design view and again switch to source view.

**Related Issues:**
Reported in https://wso2.org/jira/browse/TOOLS-2730 as well.

**Comment by sohaniwso2** [comment]
moved the issue to https://github.com/wso2/devstudio-tooling-ei/issues/171
