### ISSUE TITLE
Developer Studio (Eclipse) not starting on mac book Pro

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-ei#2086]
**Description:**
The latest version of the dev studio does not work for mac book Pro. But it works well on mac book air.
[1] https://github.com/wso2/product-ei/releases/tag/v6.2.0-rc2

**Affected Product Version:**
6.2.0 and 6.3.0

**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by prabushi** [comment]
Have to start devstudio using following command for mac book Pro.

`xattr -d com.apple.quarantine Eclipse.app`

**Comment by shavidissa** [comment]
Figured out the issue. Updated doc [1] with the steps and added a note in all the tutorials so users know where to look if they get an error. Therefore resolving the JIRA.

[1] https://docs.wso2.com/display/EI6xx/Installing+Enterprise+Integrator+Tooling
[2] Example: https://docs.wso2.com/display/EI6xx/Sending+a+Simple+Message+to+a+Service

**Comment by Miggleness** [comment]
Thanks. I spent 2 hours trying to find a solution until I ran into your issue.
