### ISSUE TITLE
Config projects can be created from the File menu even though it is removed from the dev studio dashboard

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-ei#2088]
**Description:**
Config projects can be created from the File menu even though it is removed from the dev studio dashboard

**OS, DB, other environment details and versions:**    
Dev studio - https://github.com/wso2/product-ei/releases/tag/v6.2.0-rc2
OS - Linux 15.10
JDK - 1.8

**Steps to reproduce:**
1. Go to file menu -> Other -> search config
You can create a config project from here

**Comment by dakshika** [comment]
this is needed for certain cases. Now you can get it from the dashboard page
