### ISSUE TITLE
No compatibility between 6.1.1 base version and eula version in DataServices

### ISSUE THREAD

**Issue by pknetbcn** [wso2/product-ei#2096]
**Description:**
We have found and incompatibility between WSO2 EI 6.1.1 base version and updated version and EULA version in DataServices that use Request_Box option.

The base version uses the element "DATA_SERVICE_RESPONSE" meanwhile the EULA version uses "DATA_SERVICE_REQUEST_BOX_RESPONSE" when sending the response. This affects any client that uses the service

**Affected Product Version:**
6.1.1

**OS, DB, other environment details and versions:**    
Ubuntu 16.04, H2

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
This is changed when introducing json support for request box. This is to avoid xmlSchema conflicting. You can find the complete changes fro [1]

[1] https://github.com/wso2/carbon-data/pull/147
