### ISSUE TITLE
[Doc] Add cache-schema attribute for validate mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2116]
**Description:**
Add documentation related to cache-schema attribute of validate mediator which was introduced in https://github.com/wso2/wso2-synapse/pull/1031 for https://github.com/wso2/product-ei/issues/1722 

[1] - https://docs.wso2.com/display/EI620/Validate+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Updated the Validator Mediator [1] doc from EI 6.2.0 to EI 6.5.0
Added description for 'Enable Cache Schema'  + updated the sample code with the default enable cache schema setting.

[1] https://docs.wso2.com/display/EI6xx/Validate+Mediator
