### ISSUE TITLE
request_box in service wsdl with optional operations?

### ISSUE THREAD

**Issue by srajaee** [wso2/product-ei#2127]
when trying to use request_box in a php wsdl soap call I should pass all operations in soap call since all operations are listed under request_box in generated service wsdl.
```
<xs:element name="request_box">
  <xs:complexType>
    <xs:all minOccurs="0">
      <xs:element ref="ns0:operaion1"/>
      <xs:element ref="ns0:operaion2"/>
      <xs:element ref="ns0:operaion3"/>
      <xs:element ref="ns0:operaion4"/>
      <xs:element ref="ns0:operaion5"/>
    </xs:all>
  </xs:complexType>
</xs:element>
```
if I save the wsdl as an xml file and modify it adding minOccurs="0" to each element then I can pass only the operations that I need and ignore the rest in a request_box.
```
<xs:element name="request_box">
  <xs:complexType>
    <xs:all minOccurs="0">
      <xs:element ref="ns0:operaion1" minOccurs="0"/>
      <xs:element ref="ns0:operaion2" minOccurs="0"/>
      <xs:element ref="ns0:operaion3" minOccurs="0"/>
      <xs:element ref="ns0:operaion4" minOccurs="0"/>
      <xs:element ref="ns0:operaion5" minOccurs="0"/>
    </xs:all>
  </xs:complexType>
</xs:element>
```
in a case I might need to use only operation1 and operation2 in a request_box while in another case I might need to use only operation4 and operation5...
shouldn't the operations be optional by default for request_box?

**Comment by chanikag** [comment]
It is not required to pass all the operations. You can pass any operations within request_box (verified in 6.2.0). <xs:all minOccurs="0"> is for the complex type.

**Comment by srajaee** [comment]
Well, if I call the web service in Non-WSDL mode then everything is working fine but when I call the web service with WSDL, it is not working as expected. 

There are 2 problems:

1. I have to pass all the operations and <xs:all minoccurs="0"> is not helping there. Please check these two stackoverflow questions and they confirm the same:
[https://stackoverflow.com/questions/50187813/php-soap-error-object-has-no-test2-property/50206915](url)
https://stackoverflow.com/questions/5677154/how-do-i-make-items-optional-in-xsall

2. No matter in what order I call the operations in my request, they are being passed to the server and executed in the order they appeared in the WSDL file under request_box and it is causing problems. An example is when I insert some data and export the generated id to the next query. in this case the second query which is using the generated id from first query should be executed after the first query. but sometimes in WSDL file the operation of second query is listed before the operation of first query in request_box operations in WSDL file and therefore it is being executed first and breaking the program. the listing order of operations of request_box in WSDL is not sorted by name or date of creation. It seems they are just listed there randomly. So I couldn't figure out a way to bypass this problem.

So the WSDL mode of request_box seems to have some problems and the only way I could prevent these problems was to use the Non-WSDL mode for request_box. In Non-WSDL mode I can call only the operations that I need and they are being executed in the order I call them without any problems.
