### ISSUE TITLE
Iterate Mediator: Inadvertent conversion of array into object and string to integer.

### ISSUE THREAD

**Issue by Sanketh-Learning-Tech** [wso2/product-ei#2132]
->Before the Iterate mediator the payload I have is as follows:
{
	"data": [{
			"uuid": "01_2018_46584200",
			"brand": "01",
			"timeStamp": "2018-04-18T09:55:28Z",
			"inventoryVals": [{
					"sku": "46584200",
					"storeId": "2018",
					"quantity": "15"
				}
			]
		}, {
			"uuid": "01_2018_36584235",
			"brand": "01",
			"timeStamp": "2018-04-18T09:55:28Z",
			"inventoryVals": [{
					"sku": "36584235",
					"storeId": "2018",
					"quantity": 15
				}
			]
		}
	]
}

->But after passing the above payload through Iterate mediator, it gets divided into two parts:  
1.{
	"data": {
		"timeStamp": "2018-04-18T09:41:11Z",
		"inventoryVals": {
			"quantity": 15,
			"sku": 46584200,
			"storeId": 2018
		},
		"uuid": "01_2018_46584200",
		"brand": "01"
	}
}

2.{
	"data": {
		"timeStamp": "2018-04-18T09:41:11Z",
		"inventoryVals": [{
				"quantity": 15,
				"sku": 36584235,
				"storeId": 2018
			}
		],
		"uuid": "01_2018_36584235",
		"brand": "01"
	}
}

So, here what's happening , Iterate mediator by itself converts "inventoryVals" array into object in the 1st part of request and transforming "sku" and "storeId" into integer value which were initially string in both the parts. 

That's the problem as Iterate is meant for splitting the data but not to change the structure of Payload. Please comeback with some solution ASAP.

Thanks in advance.

**Comment by venkatesh-yr** [comment]
[log.txt](https://github.com/wso2/product-ei/files/1931967/log.txt)
Actual Payload
 ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  =

	TID: [-1234][][2018 - 04 - 18 11: 56: 17, 658]INFO {
	org.apache.synapse.mediators.builtin.LogMediator
}
 - To: /integration/celect / inventoryUpdate, MessageID: urn: uuid: a1c386bf - 997b - 44c1 - aeb5 - f42e41da6be1, Direction: request, Payload: {
	"Output": [{
			"data": {
				"uuid": "01_2018_46584200",
				"brand": "01",
				"timeStamp": "2018-04-18T11:56:17Z",
				"inventoryVals": [{
						"sku": "46584200",
						"storeId": "2018",
						"quantity": 15
					}
				]
			}
		}, {
			"data": {
				"uuid": "02_2019_36584235",
				"brand": "02",
				"timeStamp": "2018-04-18T11:56:17Z",
				"inventoryVals": [{
						"sku": "36584235",
						"storeId": "2019",
						"quantity": 15
					}
				]
			}
		}
	]
} {
	org.apache.synapse.mediators.builtin.LogMediator
}

1st part of the payload
 ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  =

	TID: [-1234][][2018 - 04 - 18 11: 56: 17, 689]INFO {
	org.apache.synapse.mediators.builtin.LogMediator
}
 - To: /integration/celect / inventoryUpdate, MessageID: urn: uuid: fd728fde - 9123 - 4b98 - 8312 - 9ae00c12dbff, Direction: request, Envelope:  <  ? xml version = '1.0' encoding = 'utf-8' ?  >  < soapenv : Envelope xmlns : soapenv = "http://schemas.xmlsoap.org/soap/envelope/" >  < soapenv: Body >  < Output >  < data >  < uuid > 01_2018_46584200 <  / uuid >  < brand > 01 <  / brand >  < timeStamp > 2018 - 04 - 18T11: 56: 17Z <  / timeStamp >  < inventoryVals >  < sku > 46584200 <  / sku >  < storeId > 2018 <  / storeId >  < quantity > 15 <  / quantity >  <  / inventoryVals >  <  / data >  <  / Output >  <  / soapenv: Body >  <  / soapenv: Envelope > {
	org.apache.synapse.mediators.builtin.LogMediator
}

TID: [-1234][][2018 - 04 - 18 11: 56: 17, 720]INFO {
	org.apache.synapse.mediators.builtin.LogMediator
}
 - To: /integration/celect / inventoryUpdate, MessageID: urn: uuid: fd728fde - 9123 - 4b98 - 8312 - 9ae00c12dbff, Direction: request, Payload: {
	"data": {
		"timeStamp": "2018-04-18T11:56:17Z",
		"inventoryVals": {
			"quantity": 15,
			"sku": 46584200,
			"storeId": 2018
		},
		"uuid": "01_2018_46584200",
		"brand": "01"
	}
} {
	org.apache.synapse.mediators.builtin.LogMediator
}

2nd part of the payload
 ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  ===  =

	TID: [-1234][][2018 - 04 - 18 11: 56: 25, 517]INFO {
	org.apache.synapse.mediators.builtin.LogMediator
}
 - To: /integration/celect / inventoryUpdate, MessageID: urn: uuid: d8b529c7 - 595d - 410d - a098 - add88807526e, Direction: request, Envelope:  <  ? xml version = '1.0' encoding = 'utf-8' ?  >  < soapenv : Envelope xmlns : soapenv = "http://schemas.xmlsoap.org/soap/envelope/" >  < soapenv: Body >  < Output >  < data >  < uuid > 02_2019_36584235 <  / uuid >  < brand > 02 <  / brand >  < timeStamp > 2018 - 04 - 18T11: 56: 17Z <  / timeStamp >  < inventoryVals >  < sku > 36584235 <  / sku >  < storeId > 2019 <  / storeId >  < quantity > 15 <  / quantity >  <  / inventoryVals >  <  / data >  <  / Output >  <  / soapenv: Body >  <  / soapenv: Envelope > {
	org.apache.synapse.mediators.builtin.LogMediator
}

TID: [-1234][][2018 - 04 - 18 11: 56: 25, 549]INFO {
	org.apache.synapse.mediators.builtin.LogMediator
}
 - To: /integration/celect / inventoryUpdate, MessageID: urn: uuid: d8b529c7 - 595d - 410d - a098 - add88807526e, Direction: request, Payload: {
	"data": {
		"timeStamp": "2018-04-18T11:56:17Z",
		"inventoryVals": [{
				"quantity": 15,
				"sku": 36584235,
				"storeId": 2019
			}, "uuid": "02_2019_36584235", "brand": "02"
		}
		]
	} {
		org.apache.synapse.mediators.builtin.LogMediator
	}
