### ISSUE TITLE
[Doc] Add messageType and ContentType to convert to CSV output

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2137]
**Description:**
Update the doc [1] for adding following properties to the synapse configurations to get the CSV content. If not, the output will be sent within the `<text>` tags.
```
         <property name="messageType" value="text/plain" scope="axis2"/>
         <property name="ContentType" value="text/plain" scope="axis2"/>
```

Further, for special characters like `&`, `&amp;`, etc. returned output will be as follows without the above properties when converting from CSV to CSV. With the messageType, ContentType properties, exact characters will be returned.
```
& -> &amp;
&amp; -> &amp;amp;
< -> &lt;
&lt; -> &lt;lt;
```

[1] - https://docs.wso2.com/display/EI6xx/Data+Mapper+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/2129

**Comment by praneesha** [comment]
Doc[1] is updated with the following information.

If you specify special characters (e.g., & ,  &amp;)within the <text> tag when converting from CSV to CSV, they will be displayed as follows by default.

& -> &amp;
&amp; -> &amp;amp;
< -> &lt;
&lt; -> &lt;lt;
To avoid this and to display the exact special characters as text in the returned output, add the following properties in the Synapse configuration.
<property name="messageType" value="text/plain" scope="axis2"/>
<property name="ContentType" value="text/plain" scope="axis2"/>

[1] https://docs.wso2.com/display/EI6xx/Data+Mapper+Mediator
