### ISSUE TITLE
Support Odata $expand option

### ISSUE THREAD

**Issue by madhawa-gunasekara** [wso2/product-ei#2144]
**Description:**
Odata $expand option is not working in ei 6.1.1.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1) Create two sql tables as student and student data.
2) student data needs to have a foreign key relationship with student table.
3) Create data service and enable Odata option.
4) When getting the student record data we should able to retrive the student data with $expand option.

ex.
https://localhost:8243/odata/student_Database/default/stu_data?$expand=student

**Related Issues:**

**Comment by warunalakshitha** [comment]
We need to also fix issue with OData does not correctly mapping composite keys as well.
