### ISSUE TITLE
Fail-over scenario doesn't work when network partition occurs

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#2158]
**Description:**

When JMS Inbound end-point(with consumer caching enabled) is used with WSO2 MB  cluster and when A network partition occurs and minimum node count become less than the configured number the  Fail-over scenario doesn't work as expected.

**Affected Product Version:**
ESB-4.9.0

**Steps to reproduce:** 
Configure 2 node MB cluster with minimum node count given as 2.
Create a JMS inbound endpoint with failover
and While consuming stop single node in MB cluster
The fail-over scenario will not work as expected.

**Comment by abeykoon** [comment]
This Issue is related to https://github.com/wso2/product-ei/issues/999

**Comment by abeykoon** [comment]
This is fixed by https://github.com/wso2/carbon-mediation/pull/874/files on master
