### ISSUE TITLE
Make DSS XML payload validation to compatible with earlier version requests

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#2163]
**Description:**
Currently Rest Data services request payloads are validated as per this doc[1]. But it is not compatible with the migrations or updates since vanilla packs didn't have this validation. So its good to have backward compatibility on this.

[1]. https://docs.wso2.com/display/DSS351/Exposing+Data+as+a+REST+Resource
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a data service
2. Make a curl request to the data service.
ex : - curl -X PUT -k https://DSS_HOST:9766/services/patient_DataService/patient/getall/crud -d '<_put_patient_getall_crud/>' -H "Content-Type: application/xml"

The root tag should be same as <_put_patient_getall_crud/> for this resource path. Other root tags in request payloads are not allowed.

**Related Issues:**
https://wso2.org/jira/browse/DS-1271

**Comment by chanikag** [comment]
@nilminiwso2, we have to document about the system property
