### ISSUE TITLE
[EI600 - BPS] Unable to run the processcleanuptool script

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#217]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI 600 (17/02/2017)
DB - mysql 5.6.31

**Steps**
1. Configure process-cleanup.properties 
2. Run the proccesscleanuptool.sh located at <EI_HOME>/wso2/business-process/bin location to clean the retired processes

**Observation**
1. Failed to run the script due to following error

Error: Could not find or load main class org.wso2.bps.samples.processcleanup.CleanupExecutor

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/product-ei/commit/19be4b16c785627e77a63b0a533db725ecfe6e80

**Comment by sashikamw** [comment]
Verified the fix in 20/02/2018 latest build pack. User should adjust the "process-cleanup.properties" file with the correct username, password and clientTrustStore details.
