### ISSUE TITLE
NPE when using expand option when  expand item is Empty

### ISSUE THREAD

**Issue by warunalakshitha** [wso2/product-ei#2188]
**Description:**
We can observe null pointer exception in the server log and request get failed with using expand option. This happens when we have a expand item which has a foreign key to primary table and value get Null. The foreign key can be duplicate or null. Null scenario has not been handled properly.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ei-6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Steps to reproduce:

1. Create two sql tables as student and student_data.
2. Student_data needs to have a foreign key relationship with student table.
3. Add some students and student_data to the tables. Add some student_data with null student ids.
4. Create data service and enable Odata option.
5. When getting the student record data we should able to retrive the student data with $expand option. 

ex.. https://localhost:8243/odata/student_Database/default/stu_data?$expand=student

**Related Issues:**

**Comment by abeykoon** [comment]
Fixed with https://github.com/wso2/carbon-data/pull/192
