### ISSUE TITLE
OOM with call mediator which continuously throws an AxisFault

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2197]
**Description:**
When the axissFault is thrown at [1], messageContext that were already registered to the ConfigurationContext are not getting unregistered. When there are continuous errors, ConfigurationContext continually grows until it goes OOM.

[1] - https://github.com/wso2/wso2-axis2/blob/master/modules/kernel/src/org/apache/axis2/description/ClientUtils.java#L81

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Use an api as follows.
```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse" name="test" context="/test">
   <resource methods="POST GET">
      <inSequence>
         <log>
            <property name="Message"
                      value="************* in api ***"/>
         </log>
         <header name="To" scope="default" value=""/>
         <call blocking="true">
            <endpoint>
               <default>
                  <timeout>
                     <duration>120000</duration>
                     <responseAction>fault</responseAction>
                  </timeout>
                  <suspendOnFailure>
                     <errorCodes>-1</errorCodes>
                     <initialDuration>0</initialDuration>
                     <progressionFactor>1.0</progressionFactor>
                     <maximumDuration>0</maximumDuration>
                  </suspendOnFailure>
                  <markForSuspension>
                     <errorCodes>-1</errorCodes>
                  </markForSuspension>
               </default>
            </endpoint>
         </call>
         <respond/>
      </inSequence>
   </resource>
</api>
```
Add load to the api (eg: `loadtest -c 20 --rps 200 -n 20000 http://172.17.0.1:8280/test -H Content-Type:application/xml`)

If you take a heapdump, we can see the growth of ConfigurationContext. It will eventually go OOM.

**Related Issues:**

**Comment by Nirothipan** [comment]
FIxed with https://github.com/wso2/wso2-axis2/pull/138
