### ISSUE TITLE
Improve Odata performance for large dataset

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/product-ei#2201]
**Description:**
When it comes to a large dataset(2 million), OData doesn't perform as expected.  Filtering queries take a considerable amount of time than a query which uses a primary key. The root cause of the issue is loading dataset to memory for filtering operations. Which takes a considerable amount of time and can lead to an out of memory as well. We can improve the performance by doing operations at SQL level instead of loading data to memory. 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI-6.1.1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Jame-Chen** [comment]
I also encountered the same problem

**Comment by mb1969** [comment]
Same problem here. This shoud really be done on the SQL server side.

**Comment by Jame-Chen** [comment]
我监测数据库发现总是先查询全表,select * from table

**Comment by chanikag** [comment]
This is fixed by https://github.com/wso2/micro-integrator/pull/2765
