### ISSUE TITLE
Update ESB documentation on Inbound Transport registry sharing

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#2203]
**Description:**

ESB 4.9.0 documentation [1] states that we need to share registry as

Manager node - readonly false
Worker nodes - readonly true

With this configuration, when a **JMS inbound transport configuration is deployed on the sever**, it get deployed, but task does not get executed. (JMS inbound endpoints work on task framework). 

On editing the config, it gives an error when re-deploying. 

We need to fix the documentation. 

[1]. https://docs.wso2.com/display/CLUSTER44x/Clustering+ESB+4.9.0#ClusteringESB4.9.0-Settingupthedatabases

  it directs to 

https://docs.wso2.com/display/CLUSTER44x/Setting+up+the+Database

there it has

```
<remoteInstance url="https://localhost:9443/registry">
    <id>instanceid</id>
    <dbConfig>sharedregistry</dbConfig>
    <readOnly>true</readOnly>
    <enableCache>true</enableCache>
    <registryRoot>/</registryRoot>
    <cacheId>regadmin@jdbc:mysql://carbondb.mysql-wso2.com:3306/REGISTRY_DB?autoReconnect=true</cacheId>
</remoteInstance>
```

   - 

**Affected Product Version:**

ESB 4.9.0

**OS, DB, other environment details and versions:**    

Java 8

**Steps to reproduce:**

Please refer description

**Related Issues:**
N/A

**Comment by a5anka** [comment]
@abeykoon Is there a workaround for this?
