### ISSUE TITLE
EI remove the messages of RabbitMQ even if SET_ROLLBACK_ONLY is used

### ISSUE THREAD

**Issue by robertonav20** [wso2/product-ei#2210]
**Description:**
When the variable SET_ROLLBACK_ONLY exist  the message is deleted equally from the server.
In the fault sequence i've set the property SET_ROLLBACK_ONLY for don't remove the message from the RabbitMQ server, but the message is removed.

```
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Rabbit_ReadMessage"
       transports="rabbitmq"
       startOnLoad="true">
   <description/>
   <target>
      <inSequence>
             ---- Consume Message ----
      </inSequence>
      <faultSequence>
         <property name="SET_ROLLBACK_ONLY" value="true" scope="axis2"/>
         <log level="full" category="ERROR">
            <property name="message" value="Message could not be delivered"/>
            <property name="error_code" expression="$ctx:ERROR_CODE"/>
            <property name="error_message" expression="$ctx:ERROR_MESSAGE"/>
            <property name="error_detail" expression="$ctx:ERROR_DETAIL"/>
         </log>
      </faultSequence>
   </target>
   <parameter name="rabbitmq.queue.routing.key">Log</parameter>
   <parameter name="rabbitmq.exchange.name">amq.direct</parameter>
   <parameter name="rabbitmq.queue.name">LogQueue</parameter>
   <parameter name="rabbitmq.connection.factory">AMQPConnectionFactory</parameter>
   <parameter name="rabbitmq.message.content.type">application/xml</parameter>
</proxy>
```

With the variable SET_ROLLBACK_ONLY setted in the fault sequence, I expect that the message will not be removed, but  it doesn't happen

**Suggested Labels:**
I suggest adding the tested following lines of code to the class RabbitMQMessageReceiver.java

```
 Object o = msgContext.getProperty(BaseConstants.SET_ROLLBACK_ONLY);
            if (o != null) {
                if ((o instanceof Boolean && ((Boolean) o)) ||
                        (o instanceof String && Boolean.valueOf((String) o))) {
                            return false;
                }
            }
```

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.3.0-M9

**OS, DB, other environment details and versions:**    
Windows, JDK 8

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/wso2-axis2-transports/issues/166
wso2-axis2-transports

**Comment by isudana** [comment]
Fixes done in wso2/wso2-axis2-transports. Updating to 2.0.0-wso2v23 or later will resolve this.
