### ISSUE TITLE
When creating an Inbound Endpoint using Developer Studio, it shows  a warning before anything is done

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#2227]
**Description:**
Create an Inbound Endpoint using developer studio , select the inbound endpoint type as File or JMS and client finish. 

The inbound endpoint will be created and immediately a warning message will be shown as the attached image. This does not happen with HTTP inbound endpoint type
![inbounderror](https://user-images.githubusercontent.com/2908631/40852242-707eeb8e-65e7-11e8-8bdc-c924a949c6b6.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
moved to tooling repo at https://github.com/wso2/devstudio-tooling-ei/issues/195
