### ISSUE TITLE
Offer default values for selection in JMS inbound endpoint configuration parameters

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#2228]
**Description:**
Since we know the support message broker types and relevant configuration parameters, we could offer a drop down list to select configuration details such as initial context factory, depending on the message broker type

See attached image.
![jmsinbound](https://user-images.githubusercontent.com/2908631/40852834-832b103a-65e9-11e8-8446-099d84ca38ba.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sohaniwso2** [comment]
moved to tooling repo at https://github.com/wso2/devstudio-tooling-ei/issues/196
