### ISSUE TITLE
Issues on the document of 'Applying Security to an API'

### ISSUE THREAD

**Issue by chaminda** [wso2/product-ei#2237]
**Description:**
1. The link of 'add a service provider' in [1] is invalid; which is under 'Getting the OAuth token' sub section.
2. Class name is invalid in create API section; see below.
![image](https://user-images.githubusercontent.com/7115693/40977837-b2f5e03e-68ef-11e8-9a5f-605b51c3fdd9.png)
This should be corrected as org.wso2.handler.SimpleOauthHandler according to the sample in [2]
[1]
https://docs.wso2.com/display/EI6xx/Applying+Security+to+an+API
[2]
https://github.com/wso2-docs/ESB/tree/master/ESB-Artifacts/OAuthHandler_Sample

**Comment by shavidissa** [comment]
Thank you! Updated docs for 6.2.0 and 6.x.x.
[1] https://docs.wso2.com/display/EI6xx/Applying+Security+to+an+API
