### ISSUE TITLE
Error in handling complex objects (elements with sub elements) inside the payload factory mediator. 

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-ei#2255]
**Description:**

Below error occurs when adding an argument to extract a complex object (using JSON path or XML path) 

**Error**
[2018-06-05 17:33:55,230] [EI-Core] ERROR - JsonUtil #toXml. Could not convert JSON Stream to XML. Cannot handle JSON input. Error>>> null
[2018-06-05 17:33:55,232] [EI-Core] ERROR - PayloadFactoryMediator Error converting JSON to XML, please check your JSON Path expressions return valid JSON:

**Sample Payload**
{"pizza":{"id":3485,"name":"Meat Sizzler","price":500}}

**payload factory configuration**
```
<payloadFactory media-type="xml">
           <format>
              <pizza>$1</pizza>
           </format>
           <args>
              <arg evaluator="json" expression="$.pizza"/>
           </args>
</payloadFactory>
<property name="messageType" scope="axis2" type="STRING" value="text/xml"/>
```

**Suggested Labels:**
BUG

**Affected Product Version:**
wso2ei-6.2.0.1528222329000.zip

**OS, DB, other environment details and versions:**   
Mac OS, H2 db

**Comment by chanikag** [comment]
@GDLMadushanka , Is this fix available in the public master branch?

**Comment by GDLMadushanka** [comment]
Yes [](https://github.com/wso2/wso2-synapse/pull/1085)
