### ISSUE TITLE
RabbitMQ message store configurations cannot be saved from the design view of EI tooling

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2270]
**Description:**
By default, RabbitMQ store SSL enabled is coming as true, and store configuration are not allowed at save from the design view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create RabbitMQ message store at Developer Studio using following configs.

```
<messageStore class="org.apache.synapse.message.store.impl.rabbitmq.RabbitMQStore" name="RMStore" xmlns="http://ws.apache.org/ns/synapse">
  <parameter name="store.rabbitmq.host.name">localhost</parameter>
  <parameter name="store.rabbitmq.queue.name">EIStore</parameter>
  <parameter name="store.rabbitmq.host.port">5672</parameter>
</messageStore>
```

2. Switch to design view. By default, SSL enabled is coming as "true". (should be corrected as "false")

3. Then, select SSL enabled as "false" from the dropdown at design view, and try to save. It does not allow to save from the design view. Only allow to save from the source view.

**Related Issues:**

**Comment by sohaniwso2** [comment]
Regarding "Then, select SSL enabled as "false" from the dropdown at design view, and try to save. It does not allow to save from the design view. Only allow to save from the source view.". 

The page becomes dirty when we select values from dropdown and if we click on the dropdown or formeditor we can save the config. Also, we can save the page from save button in the editor as well. (when pressing Ctrl+S only we can see this issue)
