### ISSUE TITLE
Deploying same carbon app in Micro Integrator throws errors.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2272]
**Description:**
Created carbon app with schedule task and deployed in ESB profile, deleted from it and then deploying in Micro Integrator profile throws errors.

**Affected Product Version:**
EI 6.3.0

**Steps to reproduce:**
1- Deploy the given carbon app in ESB profile. ( rename as .car )
2 - Delete it from there.
3 - Stop the ESB profile and start Micro Integrator profile after placing the same carbon app in 
/EI-6.3.0/wso2ei-6.3.0-m11/wso2/microIntegrator/repository/deployment/server/carbonapps.
4- Following error is thrown on the startup itself.

```
ERROR - StartupTaskDeployer StartupTask Deployment from the file : /home/nirothipan/Desktop/EI-6.3.0/wso2ei-6.3.0-m11/wso2/microIntegrator/tmp/carbonapps/-1234/1528607254116capp1_1.0.0.car/testTask1_1.0.0/testTask1-1.0.0.xml : Failed.
org.apache.synapse.task.SynapseTaskException: Name with ' testTask1 ' is already there


```
[capp1_1.0.0.txt](https://github.com/wso2/product-ei/files/2087560/capp1_1.0.0.txt)

**Comment by Nirothipan** [comment]
Here multiple deployments are happening for same carbon app.
I could see 3 car files in the tmp directory.

**Comment by madhawa-gunasekara** [comment]
This issue is fixed,
