### ISSUE TITLE
Document force json validation properties

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#2274]
**Description:**
This is related to [1]. The following propertu\yt have to be documented 
force.json.message.validation=true
[1] https://github.com/wso2/product-ei/issues/2051

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
The force xml validation property is introduced by https://github.com/wso2/wso2-synapse/pull/1061 and we need to document that too.

**Comment by nilminiwso2** [comment]
[1] https://docs.wso2.com/display/EI6xx/Working+with+Message+Builders+and+Formatters
