### ISSUE TITLE
Docs link point to 620 documentation in broker profile

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#2289]
**Description:**
"Docs" link loads the EI 620 documentation in broker profile 

**Affected Product Version:**
wso2ei-6.3.0-m11

**Steps to reproduce:**
1. Start the broker profile
2. Log in to management console
3. Click "Docs" link

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/2269 in RC-2.
