### ISSUE TITLE
Introduce a way to obtain the modified raw count for a DB Report mediator update or insert query

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#2330]
**Description:**
Introduce a way to obtain the modified raw count for a DB Report mediator update or insert query. The modified raw count from the query can be added as a property to message context.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by milindaperera** [comment]
The DBReport Mediator will populate the property "DBREPORT_MODIFIED_RAW_COUNT" with the updated table row count

Doc update required to : DBReport mediator doc
