### ISSUE TITLE
[Doc] Missing namespace in throttle mediator sample

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2344]
**Description:**
Missing namespace in "Example for a rates-based policy" at [1], which ended up throwing an error at the server.

[1] - https://docs.wso2.com/display/EI6xx/Throttle+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you! Updated docs [1]

[1] https://docs.wso2.com/display/EI6xx/Throttle+Mediator
