### ISSUE TITLE
Cannot select collector/finder options for cache mediator via properties pane

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2346]
**Description:**
It was allowed to select collector/finder options from the properties pane in 6.2.0 released tooling distribution. But, this is broken with a provided update.
Now, there is no option in the properties pane to select the collector true/false value in the updated distribution.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/166
https://github.com/wso2/devstudio-tooling-ei/issues/175

**Comment by Nirothipan** [comment]
Fix added with https://github.com/wso2/devstudio-tooling-esb/pull/381.
Update Need to be created.
