### ISSUE TITLE
6.3 RC2   developer studio eclise ei corrupted zip

### ISSUE THREAD

**Issue by dartigue** [wso2/product-ei#2351]
**Description:**
Error is thrown when unzipping the developer-studio-ei-eclipse-jee-oxygen-win64-x86_64-6.3.0-rc2.zip
![wso2 6 3 zip issue](https://user-images.githubusercontent.com/32332175/41694596-9b1f9c16-753d-11e8-9368-3585177724ae.JPG)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.3 rc2
**OS, DB, other environment details and versions:**    
windows
**Steps to reproduce:**
extract the file developer-studio-ei-eclipse-jee-oxygen-win64-x86_64-6.3.0-rc2.zip

**Related Issues:**

![Uploading wso2 6.3 zip issue.JPG…]()

**Comment by Nirothipan** [comment]
Hi @dartigue 

We couldn't observe this issue with the pack. Could you please try again with the pack in https://github.com/wso2/product-ei/releases/tag/v6.3.0-rc2 and let us know the actual error you are getting and the OS version you are trying this. We will look more into this.

Thanks

**Comment by Nirothipan** [comment]
Hi @dartigue 

We couldn't observe this issue with the pack ( We verified again in a windows environment). Could you please try again with the pack in https://github.com/wso2/product-ei/releases/tag/v6.3.0-rc2 and let us know the actual error you are getting and the OS version you are trying this. We will look more into this.

Thanks
