### ISSUE TITLE
Task not re-scheduled in the other node of a cluster when one node is shut down.

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#2353]
**Description:**
When we have a scheduled task in a non-worker-manager cluster, when one node is shut down, the task is not scheduled to the other node. This happens only when the hazelcast shut down hook is disabled.

**Affected Product Version:**
EI 6.2.0

**Steps to reproduce:**

- Set up a 2 node non-worker-manager cluster.
- Deploy a scheduled task via a capp.
- Configure the hazelcast properties file as in [1].
- When cluster is up, shut down the node where the task is running.
- The task will not be scheduled to the second node.

[1] https://docs.wso2.com/display/EI620/Clustering+the+ESB+Profile#ClusteringtheESBProfile-ConfiguringHazelcastproperties

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1131
