### ISSUE TITLE
Hash generator name of Cache mediator is not updated when creating a .CAR using Developer Studio

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#2354]
**Description:**
1. Create an API with cache mediator hash generator set to 'org.wso2.carbon.mediator.cache.digest.HttpRequestHashGenerator' in developer studio.
2. Create a deployable Carbon Application out of step 1 artifacts.
3. Deploy this Carbon Application and check the deployed API content. Hash generator of Cache mediator has been changed to 'org.wso2.carbon.mediator.cache.digest.REQUESTHASHGenerator'.

**Affected Product Version:**
EI-6.2.0 Wum updated pack ( 
**OS, DB, other environment details and versions:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/252

**Comment by Nirothipan** [comment]
This issue is not reproducible with Mars or Oxygen with 6.2.0 wum pack. We will check further on this
