### ISSUE TITLE
Message Processors are not working in clustered env. when one node is shutdown.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2358]
**Description:**
When we have a message Processor in a clustered environment and when one node is shut down, the message processors are getting deleted.

**Steps to reproduce:**

- Setup a 2 node non-worker-manager cluster.
- Create A message processor.
- Configure the hazelcast properties file as in [1].
- When the cluster is up, shut down the node where the mp is running.
- It will delete the registry entry and mp will not work thereafter.

[1] https://docs.wso2.com/display/EI620/Clustering+the+ESB+Profile#ClusteringtheESBProfile-ConfiguringHazelcastproperties

**Comment by sdkottegoda** [comment]
Could not reproduce with WSOEI-6.5.0-M4. Setup a 2 node cluster and brought down the node with the task in a cycle for 10 attempts continuously. Still the behaviour was not reproduced.
