### ISSUE TITLE
Deactivating one Message processor in cluster which has two and shutting down the node, deactivate other MP also in another node.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2359]
**Description:**
After deactivating one message processor in the cluster, shut down one node and another message processor is also getting deactivated.

**Affected Product Version:**
EI 620 WUM update pack

**Steps to reproduce:**

- Create a Non-worker manager cluster with 2 nodes.
- Configure the hazelcast properties file as in [1].
- Create two message processors ( say A and B ) and make sure they are working properly. ( I tried with one JDBC and one InMemory )
- Deactivate one message processor ( say A ).
- Shut down the one node.

**OutCome:** From the Management console of another node, we could observe that both message processors are deactivated.

**Expected:** That message processor we deactivated is still not active in another node and other processor is active.

[1] https://docs.wso2.com/display/EI620/Clustering+the+ESB+Profile#ClusteringtheESBProfile-ConfiguringHazelcastproperties

**Related Issues:**
https://github.com/wso2/product-ei/issues/2358
https://github.com/wso2/product-ei/issues/849

**Comment by Nirothipan** [comment]
This issue seems to be the consequence of https://github.com/wso2/product-ei/issues/2358

**Comment by abeykoon** [comment]
I tested the scenario with attached CAR application. 

1. Setup a 2 node EI cluster
2. Deploy the CAR app to both nodes
3. Deactivate MP on the node1, which is running the task. 
4. Shutdown node1
5. Node2 picked up the MP that is not deactivated and it is working.

**Comment by abeykoon** [comment]
Rename the CAR file and use. 

[testProjectCompositeApplication_1.0.0.zip](https://github.com/wso2/product-ei/files/3066890/testProjectCompositeApplication_1.0.0.zip)

Conf of Node1

[conf.zip](https://github.com/wso2/product-ei/files/3066891/conf.zip)

**Comment by abeykoon** [comment]
This issue happens when artifacts are added from management console 

Change the setup as follows

1. Create a sim link to EI node01's deployment folder from node02's deployment folder. 
2. when node01 is shut down, deactivated message processors are automatically getting activated at node02.
