### ISSUE TITLE
Invalidate the mediation cache when validate mediator redeployment

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-ei#2361]
**Description:**

When the registry resource get change, ESB should be restart or wait until cachableDuration to clear the mediation cache which is used in validate mediator(when cachableDuration in ESB/repository/deployment/server/synapse-configs/default/registry.xml is large this will be a significant issue).
To Invalidate the mediation cache when at validate mediator redeployment(proxy redeployment). init method we can invalidate the mediation cache for the given registry schema resources.

**Affected Product Version:**
WSO2 ESB 4.8.1

**Comment by ThishaniLucas** [comment]
Need to fix this in the latest versions of EI.
