### ISSUE TITLE
FTP in passive mode is not working

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#2362]
**Description:**
When we define a file inbound endpoint with an ftp url, appending vfs.passive=true as a query param, the passive mode does not come in to effect. Because, synapse is not appending the query params when doing the fail file check. Therefore, an active ftp client instance is created to do the fail file check.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a File inbound endpoint by pointing to a FTP Server and append 'vfs.passive=true' to the FTP url.
2. Enable the Firewall in the machine and block incoming traffic.
3. Start ESB Server.
4. Files will not be polled from the server.

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1097/files
