### ISSUE TITLE
Tooling - The sequence get corrupted easily when adding Gmail connector methods

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-ei#2369]
**Description:**
I was following [1]. The sequence gets corrupted if you miss the arrow  (between the log mediator and drop mediator ) and add a Gmail connector method a bit below the arrow or away from the arrow. Afterward, you can't delete the mediator you added.The only workaround is to delete the sequence and start again.

[1] https://docs.wso2.com/display/EI6xx/Using+the+Gmail+Connector

**Affected Product Version:**
EI 6.3.0
Tooling - Oxygen

**Comment by Nirothipan** [comment]
Basically, we are not supposed to add anything after drop mediator. We will introduce some error validation mechanism to validate this in the future.

**Comment by Nirothipan** [comment]
Related Issue https://github.com/wso2/product-ei/issues/2417

**Comment by Nirothipan** [comment]
Drop mediator validation added with https://github.com/wso2/product-ei/issues/2518.
