### ISSUE TITLE
[Doc] Add documentation to create a registry collection using the tooling support

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2381]
**Description:**
Add documentation on how to create a registry collection and bundle them into a CApp using the EI tooling support.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you! As discussed updated [1].

[1] https://docs.wso2.com/display/EI6xx/Working+with+Registry+Artifacts
