### ISSUE TITLE
Overriding HTTP SC field being ignored by the Axis2 Engine...

### ISSUE THREAD

**Issue by pats-john** [wso2/product-ei#2387]
**Description: Cant Change the HTTP Status code as it is being ignored by the Apache Axis Engine**

**Suggested Labels: WSO2 E.I, WSO2 ESB**

**Suggested Assignees:**

**Affected Product Version: WSO2 E.I 6.2**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:HTTP_SC not `being` set on the Outbound of the Api Pipeline **
`<api xmlns="http://ws.apache.org/ns/synapse" name="Test" context="TestService/api/1.0" hostname="localhost" port="8280">
   <resource methods="POST" protocol="http">
      <inSequence>
         <property name="FORCE_SC_ACCEPTED" value="true" scope="axis2" type="STRING"/>
         <property name="OUT_ONLY" value="true" scope="default" type="STRING"/>
         <property name="SC_ACCEPTED" value="false" scope="axis2"/>
         <log level="custom" separator="," description="Input Message">
            <property name="Payload" expression="$."/>
            <property name="messageID" expression="json-eval($.messageid)"/>
         </log>
         <payloadFactory media-type="xml" description="Building the XML Payload">
            <format/>
            <args/>
        </payloadFactory>
         <property name="messageType" value="application/xml;charset=UTF-8" scope="axis2" type="STRING"/>
         <log level="full" description="Input Message"/>
         <header name="To" action="remove"/>
         <property name="RESPONSE" value="true" scope="default" type="STRING"/>
         <property name="SC_ACCEPTED" value="false" scope="axis2"/>
         <property name="NO_ENTITY_BODY" scope="axis2" action="remove"/>
         <property name="HTTP_SC" value="200" scope="axis2"/>
      </inSequence>
      <outSequence>
         <property name="HTTP_SC" value="200" scope="axis2" type="STRING"/>
         <property name="RESPONSE" value="true"/>
         <header name="To" action="remove"/>
         <property name="messageType" value="application/json" scope="axis2"/>
         <send/>
      </outSequence>
      <faultSequence/>
   </resource>
</api>`

**Related Issues:**

**Comment by keerthu** [comment]
This is fixed in https://github.com/wso2/wso2-synapse/pull/466.
