### ISSUE TITLE
[Doc] Enable configuring secure vault password regular expression

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2397]
**Description:**
1. Correct "Using aliases in your configurations" at [1] by specifying, it is only applicable for defining passwords, values within the synapse configuration. This is not applicable for other configuration files.

[1] - https://docs.wso2.com/display/ESB490/Working+with+Passwords

2. Introduced the System property "org.wso2.SecureVaultPasswordRegEx" to define the preferred regular expression to validate the password. For example, following value can be defined at "wso2ei-6.2.0/conf/carbon.properties" and expand the password length up to 60. The default regular expression used for password validation is `^[\\S]{5,30}$` which will only allow a password within length 5 to 30 [2].
`org.wso2.SecureVaultPasswordRegEx=^[\\S]{5,60}$`

This property is added as a wum update for WSO2 EI 6.2.0, and will be included in EI 6.4.0.

[2] - https://docs.wso2.com/display/EI620/Working+with+Passwords+in+the+ESB+profile

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.2.0
WSO2 EI 6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/2396

**Comment by shavidissa** [comment]
Thank you! Updated the following docs. 

[1] https://docs.wso2.com/display/EI620/Working+with+Passwords+in+the+ESB+profile
[2] https://docs.wso2.com/display/EI6xx/Working+with+Passwords+in+the+ESB+profile
[3] https://docs.wso2.com/display/ESB490/Working+with+Passwords
