### ISSUE TITLE
Add Nonce and Created tags to UsernameToken policy with PasswordText.

### ISSUE THREAD

**Issue by piriyas** [wso2/product-ei#2398]
**Description:**
Need to include Nonce and Created tags to UsernameToken Policy with PasswordText.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed added with https://github.com/wso2/wso2-rampart/pull/71

**Comment by prabushi** [comment]
We need to merge the public fix and upgrade the rampart version in EI.

**Comment by Nirothipan** [comment]
Since rampart is being packed from carbon-identity- framework we need to up the version there also

**Comment by Nirothipan** [comment]
This fix is available in 1.6.1-wso2v17 version itself.

**Comment by arunans23** [comment]
I'll change synapse, carbon-mediation and product-ei to use rampart 1.6.1-wso2v28
