### ISSUE TITLE
Setting <Content> field for specific Attributes in ESB/EI entitlement mediator

### ISSUE THREAD

**Issue by selakap** [wso2/product-ei#2401]
**Description:**
Need to set Content field for specific Attributes to entitlement mediator as below,
   
    [e28]       <Attributes

    [e29]         Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource">

    [e30]         <Content>

    [e31]           <md:record xmlns:md="urn:example:med:schemas:record"

    [e32]             xsi:schemaLocation="urn:example:med:schemas:record

    [e33]             http://www.med.example.com/schemas/record.xsd">

    [e34]             <md:patient>

    [e35]               <md:patientDoB>1992-03-21</md:patientDoB>

    [e36]               <md:patient-number>555555</md:patient-number>

    [e37]               <md:patientContact>

    [e38]                 <md:email>b.simpson@example.com</md:email>

    [e39]               </md:patientContact>

    [e40]             </md:patient>

    [e41]           </md:record>

    [e42]         </Content>

    [e43]         <Attribute IncludeInResult="false"

    [e44]             AttributeId="urn:oasis:names:tc:xacml:3.0:content-selector" >

    [e45]           <AttributeValue

    [e46]             XPathCategory="urn:oasis:names:tc:xacml:3.0:attribute-category:resource"

    [e47]             DataType=" urn:oasis:names:tc:xacml:3.0:data-type:xpathExpression"

    [e48]             >md:record/md:patient/md:patientDoB</AttributeValue>

    [e49]         </Attribute>

    [e50]         <Attribute IncludeInResult="false"

    [e51]             AttributeId="urn:oasis:names:tc:xacml:2.0:resource:target-namespace" >

    [e52]           <AttributeValue

    [e53]             DataType="http://www.w3.org/2001/XMLSchema#anyURI"

    [e54]             >urn:example:med:schemas:record</AttributeValue>

    [e55]         </Attribute>

    [e56]       </Attributes>

It is restricted by wso2 current implementation. Please refer (1) 
1. https://github.com/wso2-extensions/identity-agent-entitlement-proxy/blob/1d68e6a0d322e1893ec3c6135fdb7ba0c68ac5f4/components/org.wso2.carbon.identity.entitlement.proxy/src/main/org/wso2/carbon/identity/entitlement/proxy/Attribute.java#L25

**Affected Product Version:**
EI

**Comment by Nirothipan** [comment]
Fix https://github.com/wso2-extensions/identity-agent-entitlement-proxy/pull/22
