### ISSUE TITLE
Bad Policy reference error not clear when deploying multiple proxyServices

### ISSUE THREAD

**Issue by SLAVEH3R0** [wso2/product-ei#2415]
**Description:**
When i'm deploying multiple Proxy Service and 1 or N of them refer to a bad policy registry reference, I need to pass through all of them to find the wrong reference

**Affected Product Version:**
WSO2-EI 6.2.0

**OS, DB, other environment details and versions:**
Win 7, H2 and Java 8    

**Steps to reproduce:**
Deploy any .car that contain a proxy Service with a wrong or non existent Policy reference in governance registry

Pull request : https://github.com/wso2/wso2-synapse/pull/1139

**Comment by isudana** [comment]
Closing since PR is merged
