### ISSUE TITLE
[ EI Tooling ] Service get corrupted if some connector method is dropped in wrong place.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2417]
Create a service.

Add some mediators like log etc.

Drag and drop a connector method ( The method is not always getting connected properly)

We should add some validation for this. 

![error](https://user-images.githubusercontent.com/24619763/42815476-194a4a4e-89e5-11e8-80b5-176c677f9a18.png)

All other stuff done from this point doesn't behave as expected.

**Comment by rosensilva** [comment]
fixed : https://github.com/wso2/devstudio-tooling-esb/pull/446
