### ISSUE TITLE
EI 6.3.0 Profile-creator looks for DISTRIBUTION="wso2ei-6.3.0-SNAPSHOT"

### ISSUE THREAD

**Issue by robbla** [wso2/product-ei#2422]
**Description:**
Running the profile-creator on linux throws an error when run since the script looks for the directory with a -SNAPSHOT suffix 
i.e. 
DISTRIBUTION="wso2ei-6.3.0-SNAPSHOT"

The windows version is correct
set DISTRIBUTION=wso2ei-6.3.0

**Comment by Nirothipan** [comment]
Hi @robbla 

This was reported in https://github.com/wso2/product-ei/issues/2389 also and fixed in https://github.com/wso2/product-ei/pull/2416. 

**Workaround Solution**
Open the <EI_HOME>/bin/profile-creator.sh and modify following line

> DISTRIBUTION="wso2ei-6.3.0-SNAPSHOT"

as follows

> DISTRIBUTION="wso2ei-6.3.0"

Thanks

**Comment by robbla** [comment]
Hi Nirothipan,

Ok thanks. I shall search better  for errors already mentioned.

Rob


Yenlo
Rob Blaauboer
Integration Consultant & WSO2 Trainer, Yenlo
P: +31 202 700 700 | M: +31 6 83 44 23 89
E: rob.blaauboer@yenlo.com | W: www.yenlo.com
This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Read our full disclaimer: www.yenlo.com/en/disclaimer
