### ISSUE TITLE
EI cannot re-connect to MB after DB failure

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#2432]
### Description

EI JMS proxies cannot resume work after MB after DB failure

### Affected Product Version

EI 6.1.1

### Steps to reproduce

1. Created a MB 2 node cluster.
2. Configure wso2 EI 6.1.1to connect to MB cluster.
3. Created different subscriber proxies and queues.
4. Published messages to queues using Jmeter(1000 requests), meanwhile Shutdown the database server (MySQL server). Then it showed errors as "The channel was closed using the broker's management interface" and "com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure" on the EI log.
5. Then after a time restart the database server (while publishing messages), but EI will not recover the messages and it showed following failover messages as the customer observed.

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/andes/pull/991
