### ISSUE TITLE
[Tooling] Unable to delete a part when error happens.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2433]
**Description:**
When an error happens, from tooling the erroneous part cannot'be removed. 
The only way is to close it and open it again to remove it from there.

![screenshot from 2018-07-23 17-27-03](https://user-images.githubusercontent.com/24619763/43075269-e85e42d8-8e9d-11e8-9ce6-10c177cf770e.png)

**Comment by rosensilva** [comment]
fixed : https://github.com/wso2/devstudio-tooling-esb/pull/446
