### ISSUE TITLE
Define Property Palette

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2436]
**Description:**
Currently we don't have a way to just drag and drop the properties that are define in the flow to DM using palette. This will enhance the data mapping from the usability perspective

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

Originally reported at https://github.com/wso2/developer-studio/issues/153

**Comment by prabushi** [comment]
There is no such requirement at the moment.
