### ISSUE TITLE
Source view is not updated according to the Design View when you press Ctrl+Z

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2441]
**Description:**
reported at https://github.com/wso2/product-ei/issues/400

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Can be related to issue #2460

**Comment by prabushi** [comment]
Similar issue https://github.com/wso2/product-ei/issues/2550

**Comment by dakshika** [comment]
closing the issue due to possible duplicates
