### ISSUE TITLE
ESB Tooling installation from p2/hosted p2 shows 2 certificates

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2443]
**Description:**
When installing ESB tooling pack to Eclipse it shows 2 different certificates. In further investigation, found that this other certificate comes from 3 dependency jars(org.milyn.smooks.osgi_1.5.0.SNAPSHOT.jar, org.smooks.edi.editor_1.0.1.201105031731.jar, org.smooks.edi.editor.model_1.0.1.201105031731.jar ) which was already signed with an old certificate and hosted. But if we try to unsign the hosted jars their md5 hashes change and hence will fail to fetch the dependency.

These jars are hosted at http://product-dist.wso2.com/p2/developer-studio-kernel/dependencies/other/p2/plugins/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/162

**Comment by sohaniwso2** [comment]
As we are releasing the installed distributions reducing the priority to low

**Comment by dakshika** [comment]
No longer valid with 6.5.0 release
