### ISSUE TITLE
[Doc] Using SecretAlias in data services with developer-studio

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2446]
**Description:**
We have to follow below mentioned steps when creating a data service with secret alias using the developer studio.

1. Before generating the final Carbon Application, Right click on the data service(dataservice.dbs) in Project Explorer -> Open With -> Text Editor
2. Make sure you have svns:secretAlias attribute with svns qualified name in password property and xmlns:svns="http://org.wso2.securevault/configuration" namespace at top data element.

```
<data xmlns:svns="http://org.wso2.securevault/configuration" enableBatchRequests="xx" name="xx" serviceNamespace="xx" transports="http https local">
    <config id="xx" enableOData="false">
        <property name="driverClassName">xx</property>
        <property name="url">xx</property>
        <property name="username">xx</property>
        <property name="password" svns:secretAlias="xx"/>
    </config>
    <query id="xx" useConfig="xx">
        ........
    </query>
    <operation name="xx">
        .........
    </operation>
</data>
```
3. If these values are not there, add them manually
4. Then, save the data service configuration in Text Editor view (Save the configuration even though you have not made any changes there)
5. Finally, generate the Carbon Application

Please note that, you can edit the secret alias related values (username and secretAlias) using the Source view or Outline view. However, if you want to change from secretAlias enabled to disabled (define username and password), you need to manually change it in the source view. If you switch to outline view after correctly changing the synapse configuration, changes will be reflected there and you will be able to edit from the outline view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/109

**Comment by sohaniwso2** [comment]
originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/119

**Comment by nilminiwso2** [comment]
Docs updated in EI 6.3.0 [1].https://docs.wso2.com/display/EI630/Managing+Data+Integration+Artifacts+via+Tooling
