### ISSUE TITLE
[Crtical] Cannot enable a connector

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#245]
*Steps*

1. Upload a connector.
2. Try to enable the connector.

*Issue* : The page redirects to : https://localhost:8243/carbon/mediation_library/import_lib.jsp?libQName={org.wso2.carbon.connector}fileconnector&status=enabled&libName=fileconnector&packageName=org.wso2.carbon.connector

and the browser gives a HTTP 400 - Bad request.

**Comment by madhawa-gunasekara** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/796
