### ISSUE TITLE
[6.1.1]When you close dev studio with the dashboard tab open, when you restart, it will be blank

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2452]
**Description:**
[6.1.1]When you close dev studio with the dashboard tab open, when you restart, it will be blank.
You have to reopen a new dashboard tab.
![d](https://user-images.githubusercontent.com/6566181/43181034-d8f6f752-8ff8-11e8-8672-85de307f2ec1.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
this dashboard will no longer using in latest RCP packs. hence closing the issue
