### ISSUE TITLE
[DOC] Demonstrate data service creation via dev studio

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2453]
**Description:**
Demonstrate a sample on creating the basic data service via Developer Studio.

The page [1] does not include any sample on creating a data service via developer studio since the structure of the parameters is different to that of the Management Console UI, it is really important to add a sample with screen shots.

[1] https://docs.wso2.com/display/EI610/Managing+Data+Integration+Artifacts+via+Tooling

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/63

**Comment by nilminiwso2** [comment]
Docs updated in EI 6.3.0 [1].https://docs.wso2.com/display/EI630/Managing+Data+Integration+Artifacts+via+Tooling
