### ISSUE TITLE
Add more meaningful description for mediators at the tool palette

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2454]
**Description:**
Need to update values at https://github.com/wso2/devstudio-tooling-esb/blob/master/plugins/org.wso2.developerstudio.eclipse.gmf.esb.diagram/messages.properties

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/87

**Comment by Nirothipan** [comment]
This issue will be tracked in https://github.com/wso2/product-ei/issues/2568
