### ISSUE TITLE
Imply that the endpoint name is getting extended when it is too long

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2455]
**Description:**
Currently endpoint name is getting cutoff at the container width. But, full endpoint name is visible at the properties pane. Better to imply as "..." at the end of endpoint name in the diagram.

![c](https://user-images.githubusercontent.com/6566181/43182336-99de938a-8ffe-11e8-9ace-5c774115c644.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/86

**Comment by dakshika** [comment]
fixed in latest master
