### ISSUE TITLE
Improve Proxy Service "Proxy Service Configuration" window 

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2456]
**Description:**
Eg:
- providing list down and search facility for parameter names (need to allow having custom values as well)
- increasing wizard size or make it adjustable
![s](https://user-images.githubusercontent.com/6566181/43183589-4578dd1e-9003-11e8-9da4-1fa30fa3a31d.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a proxy
2. Go to properties view and click on the Service Parameters

**Related Issues:**

**Comment by dakshika** [comment]
<img width="1397" alt="Screen Shot 2019-04-02 at 5 49 03 PM" src="https://user-images.githubusercontent.com/6497326/55401871-a0dbc900-556f-11e9-8a3e-8bd4c117ebd3.png">

RCP version has improved view
