### ISSUE TITLE
Provide help option with mediator parameters in properties pane

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2457]
**Description:**
Related implementation

wso2/devstudio-tooling-bps@deeca40#diff-7ff95daa7a29086bddb6917d09e1df21
NatashaWso2/devstudio-tooling-bps@4e82ab3

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Original issue https://github.com/wso2/devstudio-tooling-ei/issues/90

**Comment by dakshika** [comment]
possible duplicate https://github.com/wso2/product-ei/issues/3380
