### ISSUE TITLE
Provide Tooling Support for the Resequencer EIP

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2458]
**Description:**
We need to provide WSO2 ESB/EI Tooling support for the Resequencer EIP.

Currently, this is implemented to be used via the Management Console only in WSO2 ESB 4.9.0.

Please refer [1] for further details.

[1] https://docs.wso2.com/display/IntegrationPatterns/Resequencer

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/99

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/285
