### ISSUE TITLE
Provide Tooling Support for Xpath Expressions in Store Mediator

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2459]
**Description:**
From WSO2 EI 6.1.1 update 10 onwards, we can enable dynamic routing by defining the Message Store in the Store Mediator as an XPath expression.

As per [1], we have added this in WSO2 Ei 6.2.0 docs in [2]. The draft doc was shared in [3].

However, this is only implemented via the Management Console, and we need to provide this via WSO2 EI Tooling.

[1] https://wso2.org/jira/browse/DOCUMENTATION-6332
[2] https://docs.wso2.com/display/EI620/Store+Mediator
[3] https://docs.google.com/document/d/15fBMPqVqL9QKVFMntvZW93-kPnOr_calk_4XWdVzfEE/edit

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/104

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/396
