### ISSUE TITLE
Dev-studio code base needs to be refactored.

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2461]
**Description:**
When adding or removing parameters or attributes of an element in EI and auto-generating the required code, some other lines of codes that are not relevant are getting either added or removed. Possible reasons for this may be is that when adding or removing attributes or properties in the past, we had committed some part of code and missed some other or hadn't put 'generated NOT' when modifying generated code. We need to analyze what attributes and properties each element in the EI has and generate a stable version of auto-generated code.

One such example is that in the commit wso2/devstudio-tooling-esb@72083b9, cache mediator related values in the EsbPackageImpl.java has edited manually

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/106

**Comment by Nirothipan** [comment]
Currently, the auto-generating code doesn't add extra files in the master branch.

We have removed the redundant ones with https://github.com/wso2/devstudio-tooling-esb/pull/383/files

We have committed autogenerated necessarry codes with  https://github.com/wso2/devstudio-tooling-esb/pull/384/commits/59085598bf4db13bc853843cecac96dda54425a8.

**Comment by dakshika** [comment]
Seems this is not a viable solution. So we need to keep going forward with current codebase and continue. we are maintain the quality on new feature addition
