### ISSUE TITLE
Cannot switch to design view when validate mediator is added to sequence

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2462]
**Description:**
When a validate mediator is added to sequence we cannot switch to design view afterwards. And the error message is given below. 

![f](https://user-images.githubusercontent.com/6566181/43189947-8294c3ae-9015-11e8-8e61-b517a6946896.png)

Note: Validate mediator requires a 'Schema key' which specifies the key for the schema location and also we must add 'fail' sequence as a child of validate mediator using the "Fault" mediator. Those two are mandatory fields for the validate mediator and that is why it gives this syntax error.

After drag and drop the validate mediator to the graphical editor, we can configure the schema key using the properties view to solve this issue. Also need to add a Fault mediator from the Palette into the Validate Mediator but we need to properly validate this

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create new sequence
2. Add validate mediator
3. Switch to source view and switch back to design view.

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/108

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/385
