### ISSUE TITLE
API handlers cannot be added via design view

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2463]
**Description:**
In Dev Studio tool, there's no any UI available to add handlers to a particular API. However, developers still can add handlers via source view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-3395
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/117

**Comment by sohaniwso2** [comment]
In the design view we display the resources in the API and the properties view is associated with each resource. API Handlers are added in the API level and not in resource level hence there is a limitation in viewing those in the graphical view.

The properties related to API (hostname, port etc) are added at the time of creating the API via the API creation wizard, and if we want to change the values we need to edit the source view. Similarly we can allow users to add the handlers in the creation wizard at the time of creating the API, and later change the values in the source view if needed

**Comment by dakshika** [comment]
This is working in latest RCP version. hence closing this. 
<img width="1060" alt="Screen Shot 2019-03-27 at 4 34 06 PM" src="https://user-images.githubusercontent.com/6497326/55071278-2cf07b00-50ae-11e9-869e-d0ce158ac2be.png">
