### ISSUE TITLE
Fix losing whole synapse config at an error

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2467]
**Description:**
Need to save partial synapse content for each drag/drop.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
fixed : https://github.com/wso2/devstudio-tooling-esb/pull/446

**Comment by prabushi** [comment]
We have only addressed this issue for main sequences related canvas areas for now. We have to fix this for complex mediator (eg: Aggregate, Filter, Switch, etc.) related canvas areas.

**Comment by dakshika** [comment]
fixed in latest master
