### ISSUE TITLE
[DOC] No steps defined on how to add cases to switch Mediator in design view

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2468]
**Description:**
You can add cases by right click on the mediator select 'Add/Remove Case' and then add the no of cases needed

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
The process of using these mediators (the main ones) in Tooling are covered in the Integration Tutorials [1]. The usage of the Switch mediator is covered in tutorial [2]. This already explains the Add/Remove Case. Therefore, closing this git issue.

Note: We have generic reference docs on the mediators [3], which currently uses the management console to explain the usage. All these will be translated to the Tooling approach. This will be a further improvement that will explain Mediators through EI Tooling.

[1] https://docs.wso2.com/display/EI630/Integration+Tutorials
[2] https://docs.wso2.com/display/EI630/Routing+Requests+Based+on+Message+Content
[3] https://docs.wso2.com/display/EI630/ESB+Mediators
