### ISSUE TITLE
Improve REST API creation wizard

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2470]
**Description:**
With the current level of implementation we cannot add parameters related to Resources (eg: Methods, URL Style via the wizard. ). It's better to have a separate page in the wizard to add those for the initial resource.  Need to support adding handlers as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
We have added handler support in latest RCP

**Comment by dakshika** [comment]
This is already support with new view. 6.5.0
