### ISSUE TITLE
Improve Proxy Service Creation Wizard to add Transport Settings

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2471]
**Description:**
Need to add all transports (http, https, vfs, etc) to the creation wizard. Currently this is supported via properties panel only 

An improvement to properties view is reported at https://github.com/wso2/product-ei/issues/2487

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
###

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/404
