### ISSUE TITLE
XML editing preferences are not working in ESB Graphical Editor

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2473]
**Description:**
Some of the XML editing preferences eg: indentation changes are not working in ESB editor

As a workaround we need to open the artifact with the XML editor instead of ESB editor and then do the changes and save.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
fixed in latest master
