### ISSUE TITLE
Cannot add comments as the first line in a sequence or a template

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2474]
**Description:**
In sequence of a Proxy or API can have comments as the first line but not in a sequence or template.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Related issue https://github.com/wso2/product-ei/issues/2597

**Comment by rosensilva** [comment]
Fixed with wso2/wso2-synapse#1298 & wso2/devstudio-tooling-esb#827
