### ISSUE TITLE
Incorrect InputType/outputType is set for data mapper

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2475]
**Description:**
When we try to map JSON to CSV using a data mapper, inputType/outputType is set as "XML" for both cases by default.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a data mapper to map JSON to CSV using the attached configuration. inputType/outputType is getting set as XML at synapse source.
[datamapper-issue.zip](https://github.com/wso2/product-ei/files/2240101/datamapper-issue.zip)

**Related Issues:**
Refer https://github.com/wso2/devstudio-tooling-ei/issues/113

**Comment by sohaniwso2** [comment]
As a workaround for this issue, we need to manually set the inputType/outputType for the datamapper at the properties pane. Hence priority has been set to low

**Comment by dakshika** [comment]
closing since possible duplicate #3712
