### ISSUE TITLE
DevStudio fault in space calculation

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2477]
**Description:**
The calculation method for in-sequence and out-sequence, is not logically correct.
Space allocation should be done only when a mediator is dragged and dropped in the canvas, space should not be allocated unnecessarily.

This screen dump shows the filter mediation without the allocated space.
![v](https://user-images.githubusercontent.com/6566181/43383847-e78705aa-93f9-11e8-9173-5de87679b8a1.png)

Once a mediator is dragged it to the filter mediation the out sequence automatically allocates space which in IMO is not necessary
![v](https://user-images.githubusercontent.com/6566181/43383865-f4617e54-93f9-11e8-8b13-069eb96bb47d.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/81

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/773
