### ISSUE TITLE
When you Select the project to save artifact it displays an arrow sign to expand

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2478]
**Description:**
When you Select the project to save artifact it displays an arrow sign to expand

E.g., when you create a proxy as given in the attached screenshot it shows an arrow to expand. But when you click on the arrow it dissapears. This might give a user a wrong understanding.
![cc](https://user-images.githubusercontent.com/6566181/43384348-69943760-93fb-11e8-9d92-b6a5dceba5fe.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Originally reported at https://github.com/wso2/devstudio-tooling-ei/issues/38

**Comment by dakshika** [comment]
this can be fix by removing the arrow head. Currently even you select the project file will be added into relevant folder in synapse config. so simply we can remove the arrow

**Comment by rosensilva** [comment]
Fixed with commit: https://github.com/wso2/developer-studio/commit/e623a36d584dce7d6cfe52be8e9c67dda265d791

P.S.: The arrowheads are coming from the eclipse tree implementation.
