### ISSUE TITLE
Migrate Tooling to Eclipse Photon

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2479]
**Description:**
    -   Check for GMF compatibility
     -  Improvements from Oxygen to Photon
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Now we deliver the RCP distribution from Integration Studio onward. Hence, there is no requirement to upgrade the eclipse platform.
