### ISSUE TITLE
[Doc] Add data-mapper mediator for mediators list 

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2482]
**Description:**
Missing data-mapper mediator at https://docs.wso2.com/display/EI620/Mediators

This should be added to all the documentation from ESB 5.0.0 on wards. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Also, Builder mediator and PublishEvent mediator is also missing in [1].

[1] - https://docs.wso2.com/display/EI620/Mediators

**Comment by praneesha** [comment]
Added the following to the list of mediators. This is done in docs of WSO2 ESB 5.0.0 and all versions of WSO2 EI.

- Data Mapper mediator
- Builder mediator
- Publish Event mediator

For example, see [1] and [2].

[1] https://docs.wso2.com/display/ESB500/Mediators
[2] https://docs.wso2.com/display/EI6xx/ESB+Mediators
