### ISSUE TITLE
Typo in Mediator creation wizard

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2485]
**Description:**
The wizard page comes under  'Import from Workspace' option has a typo as 'Create a Mediator Artifact using a existing Mediator file'. This should be corrected as 'Create a Mediator Artifact using **an** existing Mediator file

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/400/files
