### ISSUE TITLE
Proxy Type 'Log Forward Proxy' needs to be renamed as 'Logging Proxy'

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2489]
**Description:**
![c](https://user-images.githubusercontent.com/6566181/43439102-166b67fc-94af-11e8-9aca-026c71c68f1a.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/389 
https://github.com/wso2/devstudio-tooling-platform/pull/64
https://github.com/wso2/devstudio-tooling-platform/pull/65
