### ISSUE TITLE
Old version of SAP transport is packed with the distribution

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#2492]
**Description:**
The SAP transport jar version should be the latest carbon mediation version 4.6.*. But still the org.wso2.carbon.transports.sap_1.0.0.jar is packed with the product. Therefore, bug fixes and improvements done to the SAP transport are not available in the product.

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5306

**Comment by Nirothipan** [comment]
duplicate of https://github.com/wso2/product-ei/issues/870
