### ISSUE TITLE
Missing Task implementation properties in the Scheduled Task Form Editor

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2494]
**Description:**
'registryKey' property is missing in the Task Properties window of the Scheduled Task Form Editor

![v](https://user-images.githubusercontent.com/6566181/43447644-83eaa012-94c9-11e8-886b-2133f3ec370a.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Related Issues: https://github.com/wso2/product-ei/issues/2500 & https://github.com/wso2/product-ei/issues/2501

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/388
