### ISSUE TITLE
Implement a Splash Screen with WSO2 EI tooling logo

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2499]
**Description:**
This can be done by replacing the splash.bmp image at {eclipse.dir}/plugins/org.eclipse.platform_3.3.200.v200906111540/splash.bmp

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
This is fixed in latest mater
