### ISSUE TITLE
Enterprise Integration Server and Tooling

### ISSUE THREAD

**Issue by marcnorris** [wso2/product-ei#250]
Hi,

From within mars2 with ei tooling when adding a server their are two issues.
1. When adding a wso2 remote server clicking test or validate in the new server wizard response is:-
java.lang.Exception: Server is has not fully started or incorrect URL
However if I ignore error server will show as started
Server URLs tried https://localhost:8243/ and https://localhost:9443/ with and without carbon on the end

2. Adding a server and creating an EI instance the server fails to start from tools with console report of 
[2017-02-22 08:57:02,091] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2017-02-22 08:57:02,091] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

However the server will start from the terminal with integrator.sh

OS Ubuntu 16.04
Java Oracle 8
Eclipse mars2
No deployments have been made to these server clean installs

Best Regards,
Marc

**Comment by leon001** [comment]
I come across the same error, with the same platform and environment setting.

**Comment by leon001** [comment]
Another question, with this setting, how to develop SOAP based Web services? All widgets in previous Developer Studio are gone.

**Comment by madhawa-gunasekara** [comment]
Hi @leon001 and @marcnorris 

We will do a tooling update soon. 
Thanks, 
Madhawa

**Comment by madhawa-gunasekara** [comment]
Thanks for reporting, 
We are releasing a tooling update soon.

Thanks,
Madhawa

**Comment by leon001** [comment]
Dear Madhawa,
  Could you help me to solve another issue with developer studio and AS at https://github.com/wso2/developer-studio/issues/146?
  There is no echo there.
  Thanks a lot.

**Comment by vinok88** [comment]
Above issues are fixed and verified in the 6.1.0 Alpha tooling release. However this is compatible with 6.1.x versions only.

**Comment by norgealberto09** [comment]
I had the same error, but it worked for me when I checked the proxy server config
