### ISSUE TITLE
"registryKey" Property of Scheduled Tasks are Not documented.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2501]
**Description:**
The property **registryKey** which was introduced with https://github.com/wso2/wso2-synapse/pull/559 is not documented.

It needs to be added to docs 
https://docs.wso2.com/display/EI620/Scheduling+Tasks+using+the+Management+Console

Please add to other relevant versions also.

**Related Issues:**
https://github.com/wso2/product-ei/issues/2500

**Comment by nilminiwso2** [comment]
Will fix this through [1].

[1] https://github.com/wso2/product-ei/issues/2500
