### ISSUE TITLE
Get rid of the 'Error Reporting Dialog' which pop ups frequently

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2503]
**Description:**
We can get rid of this issue by adding the "--launcher.suppressErrors" to eclipse.ini file

More info on the property : http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
@prabushi  Shall we close this

**Comment by dakshika** [comment]
this is fixed in latest master
