### ISSUE TITLE
[Doc] Expression support for class mediator properties

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2504]
**Description:**
Add documentation related to adding expressions for class mediator properties.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-3777
https://github.com/wso2/product-ei/issues/2335

**Comment by shavidissa** [comment]
Hi Prabushi,

Thank you for helping with the content. Doc [1] is now updated with this information.

[1] https://docs.wso2.com/display/EI6xx/Class+Mediator
