### ISSUE TITLE
Incorrect dependency order in CAPP's pom.xml

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2505]
**Description:**
When building the CAPP using maven it refers the dependencies in the CAPP's pom.xml and the artifacts are ordered for the .car file based on the dependency order defined in the CAPP's pom.xml. Seems this order has some issues. Eg: In some cases, if JMS proxy refers a sequence, then the sequence should get deployed first. But in the CAPP's pom.xml, the proxy is defined first and then the sequence(under dependencies)  hence proxy is listed above the sequence in the artifacts.xml file of the .car file. 

As a workaround we can export the CAPP to create the .car file instead of building, as when exporting the CAPP the artifacts are listed in the correct order in artifacts.xml file. But we need to fix the issue by maintaining the correct dependency order in the CAPP's pom.xml file. So that we can create a valid .car file using maven.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
The order of artifact deployment should be handled at the server deployer level, not at the tooling level.
