### ISSUE TITLE
Add HTTP log rotation configuration to docs

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#2506]
**Description:**
We recently enabled HTTP access logs rotation capability for ESB 4.9.0 
After enabling the log rotation it will create log file for each day as in carbon logs.
We can enable log rotation be adding nhttp.is.log.rotatable=true property to <ESB_HOME>/repository/conf/nhttp.properties file. 

Doc change should be applied to [https://docs.wso2.com/display/ESB490/Access+Logs](https://docs.wso2.com/display/ESB490/Access+Logs)

**Suggested Labels:**
Docs

**Affected Product Version:**
EI 6.4.0
ESB 4.9.0 WUM updated

**Comment by shavidissa** [comment]
Added the content to the 6.4.0 docs [1]. Since the WUM is not released yet (4.9.0), I did not update the 4.9.0 docs yet. Please let me know if any other details are required.

[1] https://docs.wso2.com/display/EI6xx/Monitoring+Access+Logs
