### ISSUE TITLE
[Tooling] When Copy Pasting, Same Text gets Pasted Twice

### ISSUE THREAD

**Issue by isurulucky** [wso2/product-ei#2510]
**Description:**
Followed a tutorial to create datasources with EI 6.3.0 tooling. When I copy paste from the docs, the copied text is pasted twice. Note the data source column name in the screenshot below:

![ei_copy_paste_issue](https://user-images.githubusercontent.com/2777052/43564721-731006c4-9645-11e8-9b00-5c70c8da328d.png)

**Suggested Labels:**
EI Tooling

**Comment by dakshika** [comment]
Cannot reproduce in latest master

**Comment by prabushi** [comment]
Similar issue https://wso2.org/jira/browse/DEVTOOLEI-969
