### ISSUE TITLE
registryKey property selection can be improved.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2512]
**Description:**
Currently, in tooling, we need to type the registry key path for scheduled tasks. Which is the same in the Management Console. This can be improved by adding a button and allowing to select registry resources from there.

![schd](https://user-images.githubusercontent.com/24619763/43571726-51ba4f00-965b-11e8-88af-1516122f853f.png)

**Related Issue**
https://github.com/wso2/product-ei/issues/2494

**Comment by dakshika** [comment]
Duplicate issue
