### ISSUE TITLE
Improve Tooling intellisense

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2517]
**Description:**
eg: auto population for auto parsing of WSDL, auto-generation from OAS files etc

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Added Content Assist capability using Eclipse org.eclipse.wst.xml.core.catalog.catalogContributions extensions.
