### ISSUE TITLE
Database folder is missing for data integration samples

### ISSUE THREAD

**Issue by gilliandass** [wso2/product-ei#252]
Sample: https://docs.wso2.com/display/EI600/OData+Sample

In the above sample, there is reference to the <EI_HOME>/samples/database folder. However this folder is not available in the EI product distribution.

**Comment by madhawa-gunasekara** [comment]
Hi @gilliandass , 

I have fixed the path for the all the sample dataservices [1], Are you using the GA pack?

[1] https://github.com/wso2/product-ei/blob/master/samples/data-services/dbs/odata/ODataSampleService.dbs#L22

**Comment by gilliandass** [comment]
Sorry was looking for a folder named 'database' like in the old DSS.
