### ISSUE TITLE
JsonStreamFormatter fail to convert XML to JSON in a Data Service

### ISSUE THREAD

**Issue by jsdjayanga** [wso2/product-ei#2523]
**Description:**
A data service is created and Result (Output Mapping) was as follows;
Grouped by element=Employees
Row name=Employees
So, it will generate an output like below,

`<Employees xmlns="www.wso2.org/dss">
    <Employees>
        <FirstNameValue>B</FirstNameValue>
        <LastNameValue>B</LastNameValue>
        <TeamName>B</TeamName>
    </Employees>
</Employees>`

When the request is made with the header "Accept application/json", the request fails with following stack trace

[2018-08-03 18:58:24,979] [EI-Core] ERROR - JsonStreamFormatter Error occurred while writing to application/json
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:107)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StackOverflowError
	at org.apache.ws.commons.schema.XmlSchema.getElementByName(XmlSchema.java:260)
	at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:129)
	at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
	...
	at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
	at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:138)
[2018-08-03 18:58:24,998] [EI-Core] ERROR - PassThroughHttpSender Failed to submit the response
org.apache.axis2.AxisFault
	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-08-03 18:58:25,001] [EI-Core] ERROR - ServerWorker Error processing GET request for : /services/MYSqlSP/mySQL?empID=2
org.apache.axis2.AxisFault: Failed to submit the response
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:657)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:281)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.AxisFault
	at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
	... 10 more

But if the Result (Output Mapping) changed as follows it work fine
Grouped by element=Employees
Row name=Employee

**Suggested Labels:**
Bug

**Suggested Assignees:**
@isudana 

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    
ALL

**Steps to reproduce:**
1. Create a DataService with a query like below

`<query id="Q2" useConfig="MysqlSP">
      <sql>SELECT FirstName, LastName, Team from Employees where EmployeeID = :eid</sql>
      <result element="Employees" rowName="Employees">
         <element column="FirstName" name="FirstName" xsdType="string"/>
         <element column="LastName" name="LastName" xsdType="string"/>
         <element column="Team" name="Team" xsdType="string"/>
      </result>
      <param name="eid" sqlType="STRING"/>
   </query>`

2. Invoke it with "Accept application/json"

**Related Issues:**
N/A

**Comment by SangeethKarunaratne** [comment]
Hi, the your facing the error because the output mapping had been generated for xml. Refer this documentation for JSON output mapping.
https://docs.wso2.com/display/EI640/Using+JSON+with+Data+Services

**Comment by SangeethKarunaratne** [comment]
> **Description:**
> A data service is created and Result (Output Mapping) was as follows;
> Grouped by element=Employees
> Row name=Employees
> So, it will generate an output like below,
> 
> `<Employees xmlns="www.wso2.org/dss"> <Employees> <FirstNameValue>B</FirstNameValue> <LastNameValue>B</LastNameValue> <TeamName>B</TeamName> </Employees> </Employees>`
> 
> When the request is made with the header "Accept application/json", the request fails with following stack trace
> 
> [2018-08-03 18:58:24,979] [EI-Core] ERROR - JsonStreamFormatter Error occurred while writing to application/json
> java.lang.reflect.InvocationTargetException
> at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:107)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.StackOverflowError
> at org.apache.ws.commons.schema.XmlSchema.getElementByName(XmlSchema.java:260)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:129)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
> ...
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:138)
> [2018-08-03 18:58:24,998] [EI-Core] ERROR - PassThroughHttpSender Failed to submit the response
> org.apache.axis2.AxisFault
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> [2018-08-03 18:58:25,001] [EI-Core] ERROR - ServerWorker Error processing GET request for : /services/MYSqlSP/mySQL?empID=2
> org.apache.axis2.AxisFault: Failed to submit the response
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:657)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:281)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.axis2.AxisFault
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> ... 10 more
> 
> But if the Result (Output Mapping) changed as follows it work fine
> Grouped by element=Employees
> Row name=Employee
> 
> **Suggested Labels:**
> Bug
> 
> **Suggested Assignees:**
> @isudana
> 
> **Affected Product Version:**
> 6.2.0
> 
> **OS, DB, other environment details and versions:**
> ALL
> 
> **Steps to reproduce:**
> 
> 1. Create a DataService with a query like below
> 
> `<query id="Q2" useConfig="MysqlSP"> <sql>SELECT FirstName, LastName, Team from Employees where EmployeeID = :eid</sql> <result element="Employees" rowName="Employees"> <element column="FirstName" name="FirstName" xsdType="string"/> <element column="LastName" name="LastName" xsdType="string"/> <element column="Team" name="Team" xsdType="string"/> </result> <param name="eid" sqlType="STRING"/> </query>`
> 
> 1. Invoke it with "Accept application/json"
> 
> **Related Issues:**
> N/A

Hi, the your facing the error because the output mapping had been generated for xml. Refer this documentation for JSON output mapping.
https://docs.wso2.com/display/EI640/Using+JSON+with+Data+Services

**Comment by SangeethKarunaratne** [comment]
> **Description:**
> A data service is created and Result (Output Mapping) was as follows;
> Grouped by element=Employees
> Row name=Employees
> So, it will generate an output like below,
> 
> `<Employees xmlns="www.wso2.org/dss"> <Employees> <FirstNameValue>B</FirstNameValue> <LastNameValue>B</LastNameValue> <TeamName>B</TeamName> </Employees> </Employees>`
> 
> When the request is made with the header "Accept application/json", the request fails with following stack trace
> 
> [2018-08-03 18:58:24,979] [EI-Core] ERROR - JsonStreamFormatter Error occurred while writing to application/json
> java.lang.reflect.InvocationTargetException
> at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:107)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.StackOverflowError
> at org.apache.ws.commons.schema.XmlSchema.getElementByName(XmlSchema.java:260)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:129)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
> ...
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processSchemaType(XmlNodeGenerator.java:167)
> at org.apache.axis2.json.gson.factory.XmlNodeGenerator.processElement(XmlNodeGenerator.java:138)
> [2018-08-03 18:58:24,998] [EI-Core] ERROR - PassThroughHttpSender Failed to submit the response
> org.apache.axis2.AxisFault
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> [2018-08-03 18:58:25,001] [EI-Core] ERROR - ServerWorker Error processing GET request for : /services/MYSqlSP/mySQL?empID=2
> org.apache.axis2.AxisFault: Failed to submit the response
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.handleException(PassThroughHttpSender.java:657)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:281)
> at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:45)
> at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:337)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:158)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.axis2.AxisFault
> at org.wso2.carbon.integrator.core.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:113)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:595)
> at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:279)
> ... 10 more
> 
> But if the Result (Output Mapping) changed as follows it work fine
> Grouped by element=Employees
> Row name=Employee
> 
> **Suggested Labels:**
> Bug
> 
> **Suggested Assignees:**
> @isudana
> 
> **Affected Product Version:**
> 6.2.0
> 
> **OS, DB, other environment details and versions:**
> ALL
> 
> **Steps to reproduce:**
> 
> 1. Create a DataService with a query like below
> 
> `<query id="Q2" useConfig="MysqlSP"> <sql>SELECT FirstName, LastName, Team from Employees where EmployeeID = :eid</sql> <result element="Employees" rowName="Employees"> <element column="FirstName" name="FirstName" xsdType="string"/> <element column="LastName" name="LastName" xsdType="string"/> <element column="Team" name="Team" xsdType="string"/> </result> <param name="eid" sqlType="STRING"/> </query>`
> 
> 1. Invoke it with "Accept application/json"
> 
> **Related Issues:**
> N/A
Hi,
change <result element="Employees" rowName="Employees"> to <result element="Employees" rowName="Employee">
