### ISSUE TITLE
Input stream has being already consumed during Fault Handler

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/product-ei#2527]
**Description:**

When using the BinaryRelayBuilder, a message is streamed into the backend without building or formatting. Hence the message will not be stored in the APIM.

If network connection failure occurs between the backend and the APIM, message flow will be interrupted.

In this case, if the response from the backend is not received by the APIM, APIM will execute the fault sequence. In the fault sequence, there are content-aware mediators and since the message is not stored in the APIM, it will throw this error “Input stream is already consumed”.

**Suggested Labels:**

APIM 2.1.0

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1154
