### ISSUE TITLE
Cross site scripting security vulnerability

### ISSUE THREAD

**Issue by ctienshi** [wso2/product-ei#2529]
**Description:**
There is a Cross-site scripting vulnerability when creating a data service. When a Javascript code is entered as the service name, the script would run every time the data service or the data service list is loaded.
![image](https://user-images.githubusercontent.com/19943177/43755211-866d4d5e-9a2c-11e8-9b28-5260aa2c3598.png)
![image](https://user-images.githubusercontent.com/19943177/43755237-a463d1fc-9a2c-11e8-8086-774b99405cb0.png)

**Affected Product Version:**
WSO2 EI - 6.1.1

**Steps to reproduce:**
Start the Integrator profile.
Under the services tab, click "create".
Enter the following script as the service name.
""></a><script>alert("ALERT!!!!!!")</script><a>

**Comment by ThishaniLucas** [comment]
Already fixed in the latest product version.
