### ISSUE TITLE
Data services quick start guide has wrong endpoint urls and the screen shot needs to be updated

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#253]
In data services quick start guide, following url is given as the endpoint.

 https://10.100.5.65:9443/services/MyFirstDS/,

The port should change to 8243. Similarly , the screenshot needs to change as well.

![image](https://cloud.githubusercontent.com/assets/2908631/23353756/1467ec54-fcf4-11e6-9141-f154bac3c8ea.png)

**Comment by nilminiwso2** [comment]
Removed the screen shots for now. Will add them after testing.

**Comment by nilminiwso2** [comment]
Updated the URLs. Screenshots with wrong URLs are removed.
This quickstart will be further improved with [1].

[1] https://github.com/wso2/product-ei/issues/285
