### ISSUE TITLE
Update tooling docs on bundling third party libraries into a Class Mediator

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/product-ei#2531]
**Description:**
Currently we don't have proper steps on bundling third party libraries into a Class Mediator. Need to update docs with the usage of maven plugins to bundle the external libraries. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Added a note on the shade plugin [1].

[1] https://docs.wso2.com/display/EI6xx/Creating+Custom+Mediators
