### ISSUE TITLE
Dynamic support for from address in Proxy

### ISSUE THREAD

**Issue by shyabithd** [wso2/product-ei#2538]
**Description:**
From Address in proxy is static which has to be configured in axis config file and user is unable to change it dynamically. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shyabithd** [comment]
PR has been merged (https://github.com/wso2/wso2-axis2-transports/pull/184 )

**Comment by ThishaniLucas** [comment]
Fixed with https://github.com/wso2/wso2-axis2-transports/pull/185
