### ISSUE TITLE
BPMN tutorial screenshot needs to be updated.

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#254]
In document, https://docs.wso2.com/display/EI600/Creating+a+BPMN+Process, following image should be updated as it shows port 9443.

![image](https://cloud.githubusercontent.com/assets/2908631/23353985/1f7b14c6-fcf5-11e6-8c9d-cd3f0808040d.png)

**Comment by praneesha** [comment]
Updated the screenshot, which shows the correct port (9445) in [1].

[1] https://docs.wso2.com/display/EI600/Creating+a+BPMN+Process
