### ISSUE TITLE
Durable subscriber failed to connect after database recovery when using inbound transport 

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#2543]
**Description:**
When using an inbound endpoint to create a subscription with the MB, durable subscriber fails to reconnect after database recovery. Subscriber became inactive and the messages were stranded without being processed after database recovery. 

**Suggested Labels:**
Bug 

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    
Database - MS-SQL 
Environment Details - Two node MB cluster and two node EI cluster 

**Steps to reproduce:**
1) Publish 30 messages to a topic
2) Disconnect the MS-SQL database during the publishing process 
3) Reconnect the MS-SQL database after one minute

**Comment by Asitha** [comment]
fixed with https://github.com/wso2/product-ei/issues/999
