### ISSUE TITLE
API resources are not properly selecting when the resource methods are same

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-ei#2544]
**Description:**

From the below two resources, for all the POST requests, all the requests(http://10.100.5.39:8280/contacts/005, http://10.100.5.39:8280/contacts) are processed by the second request only.

The request should processed by first request but it is being processed by the second request
http://10.100.5.39:8280/contacts 
   <resource methods="POST" protocol="http">
   <resource methods="POST" uri-template="/{contactId}" protocol="http">

**Suggested Labels:**
ESB 

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
Refer description

**Comment by Nirothipan** [comment]
This issue was due to missing uri-template.

Adding  <resource methods="POST" uri-template="/" protocol="http"> and re-ordering the resources sorted this.
