### ISSUE TITLE
[Tooling] [Windows] Need to Test Developer Studio End To End Functionalities in Windows

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2549]
**Description:**

There are many issues reported in windows environment which are not present in Linux.
We need to do an end to end testing in Windows and fix them.
Apart from that, we need to test all the scenarios in windows also.

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/85
https://github.com/wso2/product-ei/issues/2449
https://github.com/wso2/product-ei/issues/2448

**Comment by prabushi** [comment]
Windows related issues:
https://github.com/wso2/product-ei/issues/2541

**Comment by Nirothipan** [comment]
We need to test all the Inbound Endpoints too, especially File Inbound Endpoint.

**Comment by Nirothipan** [comment]
Windows related issues: 
https://github.com/wso2/product-ei/issues/2572

**Comment by abeykoon** [comment]
Issues reported can be found under the labels "EI Tooling" and "windows" [1].  Hence closing the issue.

[1]. https://github.com/wso2/product-ei/issues?q=is%3Aopen+is%3Aissue+label%3A%22EI+Tooling%22+label%3Awindows
