### ISSUE TITLE
Google Spread sheet sample documentation screenshots need to be updated

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#255]
In document, https://docs.wso2.com/display/EI600/Exposing+a+Google+Spreadsheet+as+a+Data+Service

Following screenshots need to be updated

![image](https://cloud.githubusercontent.com/assets/2908631/23354297/80e2e01c-fcf6-11e6-8eff-0c07239026ac.png)

![image](https://cloud.githubusercontent.com/assets/2908631/23354312/986c9138-fcf6-11e6-8fbe-8ca82060b1bb.png)

**Comment by nilminiwso2** [comment]
Removed the screen shots for now. Will add them after testing.

**Comment by nilminiwso2** [comment]
Removed the screenshots from [1]. This issue will be completed after [2] is fixed.

[1] https://docs.wso2.com/display/EI600/Exposing+a+Google+Spreadsheet+as+a+Data+Service
[2] https://github.com/wso2/product-ei/issues/278.

**Comment by nilminiwso2** [comment]
Fixed in EI 6.1.0.
