### ISSUE TITLE
Improve Inbuilt Guidance in the Tooling

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2553]
**Description:**
When creating some artifacts from the tooling, currently we need to refer many documents and create them.
It would be a good improvement if we can add some inbuilt guidance like 

- Hovers 
- Short and brief descriptions about functionalities
- Templates
- We need to provide greyed descriptions in the text fields etc. to improve the usability.

in the tooling itself for the mediators etc. then we don't need to leave tooling space to create simple artifacts.

**Comment by dakshika** [comment]
fixed in latest master
