### ISSUE TITLE
Add Embedded Servers to Test The Tooling Flows

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2554]
**Description:**
Currently, when we implement some flows in the tooling, we need to add a server and then deploy the service as a CAPP and test it in the tooling. Though we can **redeploy** when make some changes, the initial part of adding a server and deploying a CAPP is bit time consuming and the person doing that need to know those configs also.

If we add an embedded server ( we need to configure the version for very first time ) to test the artifacts, it will increase the usability of tooling.

With the embedded server we can improve it to start in debug mode itself so that debugging can be facilitated easily and effectively.

**Comment by dakshika** [comment]
this is fixed in latest releases
