### ISSUE TITLE
Improve Data Mapping Capability of EI Tooling.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2556]
**Description:**

With EI Tooling, we need to manually map the input and output schemas. We can improve this as follows,

when we drag and drop a data mapper in between a flow, based on the input type of the message we can automatically detect the input schema and then define the output schema. Also, we can facilitate to view the input and output mappings in the tooling itself.

**Comment by prabushi** [comment]
Input/Output type selection issue is addressed in https://github.com/wso2/product-ei/issues/3712
Viewing input output is available via the introduced 'Realtime Datamapper Preview'
