### ISSUE TITLE
Improve the process of adding DB drivers to the Tooling.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2557]
**Description:**

Currently, we need to deploy the deploy the DB driver to the runtime otherwise there's a runtime exception.
We can improve this process to deploy it in the startup itself and establish the connection to the DB.

**Comment by dakshika** [comment]
@SangeethKarunaratne can you update the progress

Current Open PR:https://github.com/wso2/devstudio-tooling-esb/pull/722
