### ISSUE TITLE
[Tooling] Provide Guidance/Warn when using mutually exclusive properties.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#2559]
**Description:**

In Tooling, when we configure some artifacts, we need to provide proper guidance or warns when we use mutually exclusive properties.

Currently, we don't have any clue of it and figure it out when something goes wrong only.

**Comment by prabushi** [comment]
Tooling cannot consider the property mediator behaviors in runtime, as it doesnot consider the synapse configurations as a whole (for example properties can be there in dependency sequences etc.) Tooling only addresses the development aspects of the property mediator.
