### ISSUE TITLE
Need to update screenshot

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#256]
Screenshot in https://docs.wso2.com/display/EI600/Exposing+Data+as+an+OData+Service document needs to be updated.

![image](https://cloud.githubusercontent.com/assets/2908631/23355477/e178bb68-fcfb-11e6-8373-0a540c15d249.png)

**Comment by nilminiwso2** [comment]
Fixed in EI 6.1.0 [1]. 

[1] https://docs.wso2.com/display/EI610/Exposing+Data+as+an+OData+Service
