### ISSUE TITLE
Add a configuration "max idle time" when configuring pass-through sender HTTP connections

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-ei#2563]
**Description:**
\- Need to remove the connections when no input is detected on the relevant connection over a maximum period of inactivity (when the connection is idle). 
\- To do that, need to add a configuration "**max idle time**" when configuring pass-through sender HTTP connections.

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
ESB

**Comment by Nirothipan** [comment]
Related issue :- https://github.com/wso2/product-ei/issues/4863

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1472
