### ISSUE TITLE
Save could not be completed when multiple tooling open

### ISSUE THREAD

**Issue by SLAVEH3R0** [wso2/product-ei#2572]
**Description:**
When we open multiple instances of eclipse EI Tooling and then create some stuff in both at same time, when we try to save, we get "Save could not be completed reason: resources\XXX.esb_diagram(Access Denied)

This append only when Tooling is open by right clicking on eclipse in the taskbar to start the new instances of eclipse EI Tooling (if you open eclipse EI Tooling by clicking on .exe, it will work correctly).

**Suggested Labels:**
Tooling

**Affected Product Version:**
EI Tooling 6.1.1 +

**OS, DB, other environment details and versions:**
Windows 7    

**Steps to reproduce:**
Open 2 EI Tooling at the same time (with 2 different workspace) and make a project (ESB Config project containing a empty custom proxy) in each at the same time. When you try to save you will get the error

**Comment by prabushi** [comment]
What option did you try with right click on task bar? (Is it right click -> New Task)?

Apparently eclipse will start a new jvm with .exe file [1]. It is recommended to use .exe if you need two instances of eclipse at the same time.
 
 [1] - https://wiki.eclipse.org/FAQ_How_do_I_run_Eclipse%3F

**Comment by GayanChinthaka** [comment]
I also faced this problem. 

Run the program as administrator. Issue will fix.
