### ISSUE TITLE
Integrating with other technologies section should be updated to new structure

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#258]
https://docs.wso2.com/display/EI600/Integrating+with+Other+Technologies

https://docs.wso2.com/display/EI600/WSO2+EI+Tools

https://docs.wso2.com/display/EI600/Extending+WSO2+EI

**Comment by nilminiwso2** [comment]
Fixed [1]. Others are in progress.

[1] https://docs.wso2.com/display/EI600/WSO2+EI+Tools

**Comment by nilminiwso2** [comment]
Fixed all.
