### ISSUE TITLE
[backport fix] [VFS] Sever goes OOM after SoftRefFilesCache accumulating 

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-ei#2582]
**Description:**
The server goes OOM memory after several hours when there were heavy VFS transfers. This is mainly due to SoftRefFileCache not cleaning properly in common-vfs2.

**Suggested Labels:**
Type/bug
Priority/Highest
Type/patch

**Affected Product Version:**
ESB-5.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- using a sample proxy configured vfs transport and pointing to a local file location which has 1000 around input files and there were some .lock files created manually. 
- doc : https://docs.wso2.com/display/ESB500/VFS+Transport ,sample : 254
- observed that the lock count increased and also CLOSE_WAIT increased by 1 intermittently
- we should increase the file size to test further
[sampleProxy.txt](https://github.com/wso2/product-ei/files/2314336/sampleProxy.txt)

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5212

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2-support/wso2-commons-vfs/pull/1
