### ISSUE TITLE
[Doc] [EI620] Links for all listed samples in script mediator page are pointing to older esb version

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-ei#2583]
**Description:**
As $subject, please see doc in[1], those should be corrected to point ei-6.2.0 sample's pages.

[1] https://docs.wso2.com/display/EI620/Script+Mediator

**Suggested Labels:**
Type/Documentation

**Suggested Assignees:**
@praneesha 

**Affected Product Version:**
EI-6.2.0

**Comment by nilminiwso2** [comment]
Fixed in EI 6.0.0 to 6.5.0.
