### ISSUE TITLE
No Error Code in WSO2 ESB for nack from RabbitMQ

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/product-ei#2584]
**Description:**
When using the call mediator (non-blocking) to publish a message to RabbitMQ queue which has "x-overflow: reject-publish" and "x-max-length" set, the amqp-client throws an IOException with the message "nacks received" when the queue is full. When this happens, the error is no catch in the CallMediator [1], thus no error code is set in the synapse and therefore it is hard to handle this error in ESB onError sequence.

[1] - https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java#L276

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.1.1, WSO2 EI 6.3.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04, Oracle JDK 1.8.0_60

**Steps to reproduce:**
Steps to reproduce this is mentioned in [2].

**Related Issues:**
[2] - https://github.com/wso2/wso2-synapse/issues/1157
Dev Mail Subject: "[Dev] No Error Code in WSO2 ESB for nack from RabbitMQ"

**Comment by milindaperera** [comment]
Doc update required
