### ISSUE TITLE
[Doc] Add documentation on removing tooling artifacts.

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2588]
**Description:**
We need to save and re-open the CApp pom file after removing a specific artifact, otherwise we will have the corrupted pom file with the removed artifact. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you! Added the content to [1]. 
Once the page is finalized, I will move it to 630 and 640 too.
[1] https://docs.wso2.com/display/EI6xx/Tooling+Troubleshooting+Guide
