### ISSUE TITLE
EBS 5.0.0 need to restart to consume the messages from kafka IEP

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-ei#2591]
**Description:**

ESB 5.0.0 do not consume the messages from kafak IEP which is deployed as a carbon artifact until restarting the ESB.

**Affected Product Version:**

ESB-5.0.0

**Steps to reproduce:**

Create kafka IEP as a  carbon artifact using EI tooling and deploy to the ESB 5.0.0 then publish messages to the kafka. We can observe the messages will not consume, to consume the messages  restart the ESB.

**Comment by Nirothipan** [comment]
Fix https://github.com/wso2-support/carbon-mediation/pull/174
