### ISSUE TITLE
Add configuration "connection idle time" and "maximum connection lifespan" to passthru-http.properties

### ISSUE THREAD

**Issue by hasithajayasundara** [wso2/product-ei#2592]
**Description:**
We need to add "connection idle time" and "maximum connection lifespan" parameters to passthru-http.properties. When the connection is idle for a time of "connection idle time"  or a connection persisted for a time more than "maximum connection lifespan", then the connection need to be removed from the connection pool.

**Comment by indikasampath2000** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1162
