### ISSUE TITLE
Invalid White Space Character

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-ei#2594]
**Description:**
This issue occurs when there are non-printable characters available in the payload. If a non-printable character exists in the payload, it will give an error.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
WSO2EI-6.1.1

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-axiom/pull/40/files.

Referhttps://github.com/wso2/product-ei/issues/2784 for further details
