### ISSUE TITLE
Cannot switch to source view of a sequence template.

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#2599]
**Description:**
When we open the source view of a created sequence template, it pops up with the error.
<img width="825" alt="screen shot 2018-08-29 at 1 33 46 pm" src="https://user-images.githubusercontent.com/2033965/44777242-b7641100-ab97-11e8-94e8-7bab5eaf3a5d.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/411/commits/515e46a8db6b0f2b79d7b2f845ccfb789e1a9b2f
