### ISSUE TITLE
Include in docs how to run MSF4J microservices

### ISSUE THREAD

**Issue by gilliandass** [wso2/product-ei#260]
Include in docs that if a user wants to run an MSF4J microservice in WSO2 EI, the user can take a Maven dependency on it and create an executable jar.

**Comment by praneesha** [comment]
Linked to MSF4J docs in GitHib from [1].

More information on MSF4J will be added to the WSG and also to titorials.

[1] https://docs.wso2.com/display/EI610/Key+Concepts#KeyConcepts-MicroservicesFramework
