### ISSUE TITLE
Password visible in WSDL after securing password using cipher tool 

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#2602]
**Description:**
After securing VFS password in a proxy service, password is visible in WSDL

**Suggested Labels:**
Bug

**Affected Product Version:**
ESB 5.0.0 

**Steps to reproduce:**
1. Create and deploy a simple VFS proxy pointing to a SFTP location.
2. Secure SFTP password using cipher tool and obtain encrypted value for the password as mentioned in the ticket
3. Update encrypted password in proxy service 
4. Click on the WSDL link in the respective proxy service shown in the ESB management console
5. Finally you can observe the actual password of the SFTP server instead of asterisk or encrypted value

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-axis2/pull/142/files
