### ISSUE TITLE
Fix product-ei/issues/2617

### ISSUE THREAD

**Issue by shyabithd** [wso2/product-ei#2617]
**Description:**

CAR file pom.xml needs to be updated when the artifact is renamed or deleted. But in actual scenario this is not updated.

**Suggested Labels:**

**Suggested Assignees:**

shyabith

**Affected Product Version:**

**Steps to reproduce:**

Create an ESB Configure project. Create any of the following: api, inbound-endpoint, endpoint, etc.
And see whether Composite Application Project is update with newly added artifact. Rename this artifact and see wether the POM of Composite Application Project is updated. Actual scenario pom is not updated.

**Related Issues:**

**Comment by Nirothipan** [comment]
https://github.com/wso2/devstudio-tooling-platform/pull/77
