### ISSUE TITLE
POST with no body scenario fail

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#262]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI600 GA
DB - H2

**Prerequisites**
1. jaxrs_basic service is deployed

**Steps** 
The scenario, 'POST with nobody' [1] failed with 400 Bad request

When invoking using "curl -v -H "Content-Type: text/xml" -d "" http://localhost:8280/customerservice/customers" it throws "HTTP/1.1 400 Bad Request" as below,

HTTP/1.1 400 Bad Request
Content-Type: text/plain
Date: Thu, 02 Mar 2017 07:50:26 GMT
Transfer-Encoding: chunked
Connection: Close

99
JAXBException occurred : Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]. Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]. 
0

[1] https://docs.wso2.com/display/EI600/Unusual+Scenarios+for+HTTP+Methods+in+REST

**Note** - in the document command is given as "curl -v -H "Content-Type: application/xml" -d "" http://localhost:8280/customerservice/customer" but this should be corrected as "curl -v -H "Content-Type: text/xml" -d "" http://localhost:8280/customerservice/customers"

**Comment by madhawa-gunasekara** [comment]
Hi @sashikamw,
Actually, why are you setting content-type if there is no-content in the request ? This should work. you have to remove the content-type header :)

**Comment by sashikamw** [comment]
Hi Madhawa,

We have to keep the content type, otherwise you will experience 405 exception. However, this scenario is working without an issue from the EI side. AS backend is unable to support this empty body, hence "Unexpected EOF" expection observed.
