### ISSUE TITLE
Error in the profile-creator script when creating the analytics profile

### ISSUE THREAD

**Issue by dilee** [wso2/product-ei#2636]
**Description:**
The following error occurs when creating the analytics profile from the profile-creator script.

> ./profile-creator.sh: line 91: ./../wso2/components/analytics-default/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info: No such file or directory

This occurs due to the recent changes in the analytics profile directory structure.

**Affected Product Version:**
6.4.0

**Steps to reproduce:**
1. Run the profile-creator.sh script from the {EI_HOME}/bin directory.
2. Select the analytics profile by entering option 2.

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/2637/files

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/2637/files
