### ISSUE TITLE
Issue with the artifactID of securevault dependency in wso2 message broker documentation

### ISSUE THREAD

**Issue by Ishuamali** [wso2/product-ei#2641]
**Description:**

artifactID for the securevault dependency in the Simple MQTT Client sample in wso2 message broker documentation should be changed from " securevault "   to  "org.wso2.securevault "

https://docs.wso2.com/display/MB320/Setting+up+the+MB+Samples#SettinguptheMBSamples-Prerequisites

**Suggested Labels:**
 type/DOC

**Suggested Assignees:**

**Affected Product Version:**

WSO2 message broker Version 3.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
fixed.
