### ISSUE TITLE
Management Console - Configuration registry button not working in design sequence page

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/product-ei#2658]
**Description:**
When creating a sequence or editing a sequence using the management console, an html code (`<div class="ajax-loading-message"> <img src="../resources/images/ajax-loader.gif" align="top"/> <span>Resource tree loading please wait ..</span> </div>`) get written in top of the page and nothing else happens.

Screenshot:
![bug_in_sequence_create](https://user-images.githubusercontent.com/25482980/45532239-ed002f80-b810-11e8-9347-056547b71138.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** 6.4.0

**OS, DB, other environment details and versions:**    Ubuntu 16.04

**Steps to reproduce:** 

1. Run the integrator.
2. Open the management console.
3. Click on sequences under the service bus.
4. Click on add sequence button.
5. Click on configuration registry or governance registry button. Then the mentioned html code block will appear on top of the window.

**Related Issues:**

**Comment by DMadhuranga** [comment]
Also both configuration registry button and governance registry button gives the same error in the Spring mediator when attempting to select the key.

![spring_2](https://user-images.githubusercontent.com/25482980/45532728-bd522700-b812-11e8-9ae1-5e41c1d311cc.png)

**Comment by DMadhuranga** [comment]
When click on the throttle policy editor in the throttle mediator similar behavior occurs.

![throttle_editor](https://user-images.githubusercontent.com/25482980/45549574-ea6bfd00-b845-11e8-9bfb-cf20c786ab9a.png)

**Comment by DMadhuranga** [comment]
When click on the editor in the rule mediator similar behavior occurs.
![rule_mediator](https://user-images.githubusercontent.com/25482980/45549627-0f607000-b846-11e8-838a-604cd4dc098a.png)

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/1855
