### ISSUE TITLE
Cannot create secure proxy using management console

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#2661]
**Description:**
The Security Policy filed is not editable in the management console UI, and cannot load from the registry.

![image](https://user-images.githubusercontent.com/6702569/45534612-5be18680-b819-11e8-8858-06fc6aba09c4.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Duplicate of issue #2658
