### ISSUE TITLE
Data Services CAR Issue

### ISSUE THREAD

**Issue by dlight20** [wso2/product-ei#267]
Deploying a data service (e.g. .dbs) inside of a CAR will act differently than if you simply drop the .dbs file on the file system.  

For example, returning JSON from the .dbs works if the file is dropped on the file system and passing the content type accept header.  If deployed through a CAR file ONLY xml will ever be returned.  The DBS files for both deployments were identical, the only difference was how it was deployed.

**Comment by madhawa-gunasekara** [comment]
Thanks fro reporting this issue, We have fixed this with https://github.com/wso2/product-ei/pull/273
