### ISSUE TITLE
Unable to parameterize the retriesBeforeSuspension in tooling

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#2687]
**Description:**
Unable to parameterize the retriesBeforeSuspension as documented in [1]. It says this field must be a number.

<img width="721" alt="screen shot 2018-09-18 at 9 00 55 am" src="https://user-images.githubusercontent.com/2033965/45662972-c8160000-bb21-11e8-98d5-6ccee35c114a.png">

[1] https://docs.wso2.com/display/ESB500/Endpoint+Template

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
possible duplicate https://github.com/wso2/product-ei/issues/3550
