### ISSUE TITLE
EI Not handling Single Element JSON Array

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#2688]
**Description:**
When processing JSON array (payload) with a single element EI drops it. To prevent that we need to add below property to synapse.xml. We need to set it by default

synapse.json.to.xml.processing.instruction.enabled=true

**Affected Product Version:**

EI 6.1.1

**OS, DB, other environment details and versions:** 

All   

**Steps to reproduce:**

Send a json payload like below

```
{{ "phoneNumbers": [

{ "type": "mobile", "value": "+947721123" }
]
}}
```

It gets converted to

```
{{ "phoneNumbers": 
{ "type": "mobile", "value": "+947721123" }
}}
 
```

**Related Issues:**
N/A

**Comment by sameeragunarathne** [comment]
Since to preserve the backward compatibility and the existing use cases, we need to use the synapse property. Hence cannot achieve this as the default behaviour.
