### ISSUE TITLE
Management Console - Governance Registry button not working after pressing "escape" button

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/product-ei#2693]
**Description:**

When creating a sequence or editing a sequence using the management console, If configuration registry button clicked first and pressed "Escape" button, then clicked on configuration registry or governance registry button an html code (`<div class="ajax-loading-message"> <img src="../resources/images/ajax-loader.gif" align="top"/> <span>Resource tree loading please wait ..</span> </div>`) get written on the pop up window.

ScreenShot:

![resourcetree](https://user-images.githubusercontent.com/25482980/45764015-60f66980-bc4f-11e8-826b-86d569c92d10.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** 6.4.0

**OS, DB, other environment details and versions:**    Ubuntu 16.04

**Steps to reproduce:**

1.    Run the integrator.
2.    Open the management console.
3.    Click on sequences under the service bus.
4.    Click on add sequence button.
5.    Click on configuration registry button. This will open a pop-up window.
6.    Press the "escape" button. This will close the pop-up window. 
7.    Then click on the governance registry button (or configuration registry button) and the pop-up window with mentioned code block will appear.

**Related Issues:**

**Comment by Nirothipan** [comment]
This happens in Linux when escape button is used to close the first pop up.

**Comment by Vathsan** [comment]
Fixed in [#1148](https://github.com/wso2/carbon-mediation/pull/1148#issue-262344089)
