### ISSUE TITLE
Unable to set multiple groups to be potential owners of a task for approval

### ISSUE THREAD

**Issue by KosalaHerath** [wso2/product-ei#2701]
**Description:**
Unable to set multiple groups(roles) to be potential owners of a task for approval. Unable to give multiple groups(roles) as arguments in a human task file. As given in following example, need to define multiple groups to be potential owners of a task for approval.

    <htd:potentialOwners>
        <htd:from logicalPeopleGroup="regionalClerks">
                <htd:argument name="role">
                        regionalClerksRole
                </htd:argument>
                <htd:argument name="role">
                        regionalClerksRole2
                </htd:argument>
        </htd:from>
    </htd:potentialOwners>

**Suggested Labels:**
BPS

**Affected Product Version:**
BPS

**Steps to reproduce:**
1. In the human task file define multiple groups to be potential owners of a task for approval.
2. It will take only first argument(group) as a potential owners form multiple groups that are defined in the human task file.

**Comment by shavidissa** [comment]
Added the info to docs too [1].

[1] https://docs.wso2.com/display/EI6xx/Writing+a+Human+Task+Artifact
[2] https://docs.wso2.com/display/EI640/Writing+a+Human+Task+Artifact
