### ISSUE TITLE
Directed to the fault sequence when using call mediator which calls an endpoint which returns 204 - No Content

### ISSUE THREAD

**Issue by dilan-premarathna** [wso2/product-ei#2709]
**Description:**
When the call mediator is used in the proxy and when the response from the back is 204 no content, it is directed to the fault sequence.

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
1. Crate the following proxy
2. Call the proxy

`<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="test1"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log level="full">
            <property name="in_sequence" value="===in sequence before endpoint =="/>
         </log>
         <call blocking="true">
            <endpoint>
               <http method="GET"
                     uri-template="http://www.mocky.io/v2/5bacab4831000075006548c6"/>
            </endpoint>
         </call>
         <respond/>
         <log level="full">
            <property name="in_sequence" value="===in sequence after end point=="/>
         </log>
      </inSequence>
      <outSequence>
         <log level="full">
            <property name="out_sequence" value="===out sequence =="/>
         </log>
      </outSequence>
   </target>
   <description/>
</proxy>`

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2-support/wso2-axis2/pull/54
