### ISSUE TITLE
Issue in Comparison of the sorted list of values

### ISSUE THREAD

**Issue by malshaniS** [wso2/product-ei#2716]
**Description:**
In sorting, the values are sorted according to the alphabetical order without considering the lower case and upper case letters. Tests use compareTo method to compare two strings lexicographically. With compareTo, strings are compared based on their ordinal values. In ASCII, uppercase letters have lower values than lowercase ones. Therefore the comparison gives a failure, even though the list sorted in the correct order.

**OS, DB, other environment details and versions:**    
OS: Windows, CentOS
DB: sqlserver-se - 13.00

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/product-ei/pull/2743/files
