### ISSUE TITLE
Avoid "Save could not be completed error" in MacOS 

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2720]
**Description:**
Getting the following error with MacOS while trying to save the artifacts with MacOS.
<img width="724" alt="screen shot 2018-09-28 at 11 10 25 am" src="https://user-images.githubusercontent.com/5234623/46520170-9ed2cf00-c898-11e8-9ff3-2c83c2d20f82.png">

To avoid this error, mac users **should copy the Eclipse.app into Applications directory**. The Eclipse link outside the Applications directory does not have the permission to write files, Hence causing this error.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.3.0
EI 6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shavidissa** [comment]
Thank you! Added the content to the 6xx space [1].
Will move to the 640 and 630 space too.

[1] https://docs.wso2.com/display/EI6xx/Tooling+Troubleshooting+Guide
