### ISSUE TITLE
Invalidate the mediation cache of the registry resources, when the registry resources getting redeployed

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-ei#2725]
**Description:**
Even if we redeploy the registry resources, It will not invalidate the mediation cache If we keep a higher cachableDuration value in registry.xml under ESB/repository/deployment/server/synapse-configs/default. It should immediately invalidate the mediation cache when the registry resources are getting redeployed.
 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 4.8.1, 4.9.0, 5.0.0 
EI 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushadhanushka** [comment]
Fixed with
https://github.com/wso2/product-ei/pull/2965
https://github.com/wso2/wso2-synapse/pull/1213
https://github.com/wso2/carbon-mediation/pull/1114
