### ISSUE TITLE
Embed the server runtime (Micro Integrator) into the tool

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#2739]
**Description:**

To try out developed synapse artifacts in WSO2 tooling, we can use Micro Integrator runtime. It is a light weight profile which starts under 5s. Task is to embed micro integrator into tooling platform

- Modify packaging scripts to pack micro integrator on build 
- Register Micro Integrator as a "server runtime" in eclipse tooling 

**Affected Product Version:**

EI 6.4.0 tooling 

**OS, DB, other environment details and versions:**   

Linux/Mac/Windows  

**Steps to reproduce:**

N/A

**Related Issues:**

N/A

**Comment by dakshika** [comment]
Fixed in latest master
