### ISSUE TITLE
Allow systemd service for CentOS installation

### ISSUE THREAD

**Issue by etalaq** [wso2/product-ei#2742]
**Description:**
To install the product as a service, need to create systemd service file to allow autostart of services and better manageability.

**Suggested Labels:**
wso2ei,centos,service

**Affected Product Version:**
WSO2EI-6.4.0

**OS, DB, other environment details and versions:**    
OS=CentOS

A sample file can be:
/usr/lib/systemd/system/wso2ei-integrator.service
other files can be created for other profiles of the product (broker,bp,microservices,analytics)

`[Unit]
Description=WSO2 Enterprise Integrator
After=network.target 

[Service]
Type=fork
Environment=JAVA_HOME=/usr/lib64/wso2/wso2ei/6.4.0/jdk/jdk1.8.0_192
ExecStart=/usr/lib64/wso2/wso2ei/6.4.0/bin/integrator.sh &
ExecReload=/usr/lib64/wso2/wso2ei/6.4.0/bin/integrator.sh restart
ExecStop=/usr/lib64/wso2/wso2ei/6.4.0/bin/integrator.sh stop
KillSignal=SIGCONT
PrivateTmp=true

[Install]
WantedBy=multi-user.target

`

**Comment by asepsudirman** [comment]
how to check this code is working? and can u add some image step by step?
