### ISSUE TITLE
Malformed json payload factory issue

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#2757]
**Description:**
Custom fault sequences are not hitting when sending the invalid JSON payloads.

Relates to https://github.com/wso2/wso2-synapse/issues/1183

```
<api xmlns="http://ws.apache.org/ns/synapse" name="newAPI" context="/newapi">
   <resource methods="POST">
      <inSequence>
         <log>
            <property name="lang" expression="//hello"/>
         </log>
         <property name="Accept" scope="transport" action="remove"/>
         <drop/>
      </inSequence>
      <faultSequence>
         <log>
            <property name="FAULT" value="CUSTOM_SEQUENCEE"/>
         </log>
         <payloadFactory media-type="json">
            <format>{"aaaa": {"errors": {    "bbbbb": ["dddd"]}}}  </format>
            <args/>
         </payloadFactory>
         <property name="HTTP_SC" value="500" scope="axis2"/>
         <respond/>
      </faultSequence>
   </resource>
</api>

```
This happens as the malformed json payload is evaluated again in the fault sequence. Even though the http status code is set to 500 as the default fault sequence is executed here after, the final status code is set as 202.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1186
