### ISSUE TITLE
String output Resource type for JSON doesn't work in data mapper in the Response

### ISSUE THREAD

**Issue by Thivya01** [wso2/product-ei#2762]
**Description:**
The Final response of a datamapper which is having output String when invoking via the ESB is returned again as a Numeric. String output Resource type for JSON doesn't work.

**Suggested Labels:**
EI 

**Affected Product Version:**
EI 6.4.0 , EI 6.3.0

**Steps to reproduce:**
1. Define an input message as follows with XML resource type.

<**Helloo**>
   <**LengthsOfStay**>
      <**element**>
         <**MessageType**>Hi</**MessageType**>
         <**Time**>2</**Time**>
         <**TimeUnit**>Day</**TimeUnit**>
      </**element**>
      <**element**>
         <**MessageType**>Hi</**MessageType**>
         <**Time**>1</**Time**>
         <**TimeUnit**>Day</**TimeUnit**>
      </**element**>
   </**LengthsOfStay**>
</**Helloo**>

 
2. Design the output for data mapper configurations for JSON resource type with a String
Eg:

{
    "Helloo": {
        "LengthsOfStay": [
            {
                **"Time": "2",**
                "TimeUnit": "Day",
                "MessageType": "SetMinLOS"
            },
            {
                **"Time": "1",**
                "TimeUnit": "Day",
                "MinMaxMessageType": "SetMaxLOS"
            }
        ]
    }
}

**### Time is defined as String here**
2. Design the API/Proxy and add the Capp to the EI server and Invoke with the input payload.
3. You can see the output of the particular element designed as string is not preserved in the final response.
Eg: Response
 "LengthsOfStay"
{code}
            {
                **"Time": 2**,
                "TimeUnit": "Day",
                "MinMaxMessageType": "SetMinLOS"
            }
{code}
### Finally in the response we can see the time appears as integer/numeric again

**Comment by Maninda** [comment]
Fixed in commit 5040d1da8b431529885a6b062b97641096a0fdc6 in trunk
