### ISSUE TITLE
The receiving payload is in test/plain format when using IBM-MQ through a listener proxy

### ISSUE THREAD

**Issue by hasithajayasundara** [wso2/product-ei#2776]
**Description:**
When receiving messages from IBM-MQ through a jms proxy  transport headers are getting removed. The header removal is happening from IBM-MQ side. Since the Content-Type header is not available in the receiving payload esb treats this as a palin text and the response payload is wrapped around a CDATA tag.

**Comment by Nirothipan** [comment]
Related Issue https://github.com/wso2/product-ei/issues/2858

Fixed with https://github.com/wso2/wso2-axis2-transports/pull/194/files
