### ISSUE TITLE
onError fault handler not working for sequence template

### ISSUE THREAD

**Issue by bsenduran** [wso2/product-ei#2783]
**Description:**
When an _On Error Sequence_ is defined for a sequence template it is not getting saved to the sequence template's xml file. hence can not define a specific error sequence for a sequence template

**Suggested Labels:**
bug

**Affected Product Version:**
ESB 5.0.0 - latest (EI 6.4.0)

**Steps to reproduce:**
* Create a sequence. 
* Create a sequence template and add the above created sequence as a _onError_ sequence. (either from developer studio or EI management console)
* Save the sequence template.
* Now if you reopen it. the onError attribute will not be there

**Reason**
onError is not getting serialized, so the fault handler is not getting added to the faultStack

**Comment by isudana** [comment]
PR merged.
