### ISSUE TITLE
Handling Illegal XML Characters In Plain Text Payloads

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#2784]
**Description:**

We need to add the following property to the code base of the next WSO2 EI GA release (6.5.0).

com.ctc.wstx.outputInvalidCharHandler.char=\u0020

This should be added to the <EI_HOME>/XMLOutputFactory.properties file. Need to create the file if it doesn't exist.

This was issued as a WUM update (3201 issued on 14th  Sept 2018) for WSO2 EI 6.0.0, 6.1.0, 6.2.0 and 6.3.0.

Need to update docs once this is added to the code base of 6.5.0.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fix added with https://github.com/wso2/wso2-axiom/pull/40/files.

Original Issue https://github.com/wso2/wso2-axiom/issues/39

Documentation need to be updated.

**Comment by nilminiwso2** [comment]
Updated the docs for EI 6.5.0 [1] as well as 600, 610, and 620.

The **description**: 

**Handling illegal XML characters in plain text payloads**
Plain text payloads that contain illegal XML characters (such as unicodes) will not be successfully processed by the ESB. Therefore, you must configure the system to replace the illegal characters in the payload with an actual character. To enable this configuration, add the parameter shown below (with a suitable unicode value) to the XMLOutputFactory.properties file (stored in the <EI_HOME>/ directory). If this file does not exist in your product by default, be sure to create a new file. 

When this configuration is enabled, all the illegal characters found in a payload will be replaced with the actual character that is represented by the unicode value that you specify for the parameter. The below example uses whitespaces (represented by by the '\u0020' unicode value) to replace illegal characters in payloads.
com.ctc.wstx.outputInvalidCharHandler.char=\u0020

[1] https://docs.wso2.com/display/EI6xx/Working+with+Message+Builders+and+Formatters#WorkingwithMessageBuildersandFormatters-HandlingillegalXMLcharactersinplaintextpayloads
[2] https://docs.wso2.com/display/EI620/Working+with+Message+Builders+and+Formatters
