### ISSUE TITLE
Two 'Task Scheduling' UI's for Data Services and Service Bus

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#279]
We currently have two places in the UI for task scheduling. [1] is relevant to task scheduling for data services. [2] is relevant to task scheduling for service bus (ESB functionality). Even though the functionality is slightly different, there should ideally have just one Task Scheduling UI. Please check.

[1]
![screen shot 2017-03-09 at 6 48 44 pm](https://cloud.githubusercontent.com/assets/21237558/23751847/1952888e-04f9-11e7-9f40-fa0afba3ba21.png)

[2] 
![screen shot 2017-03-09 at 6 41 18 pm](https://cloud.githubusercontent.com/assets/21237558/23751727/90ac9150-04f8-11e7-8d1e-e89f2ea0f61e.png)

**Comment by praneesha** [comment]
The Working with Schedules section [1] and the Scheduling Tasks [2] section should be combined after this is fixed in the product UI.

[1] https://docs.wso2.com/display/EI600/Adding+and+Scheduling+Tasks
[2] https://docs.wso2.com/display/EI600/Scheduling+Tasks

**Comment by vinok88** [comment]
One of these UIs are specific to DSS and other one is to Integrator. Since one of them is under "Data services" section I don't think it is confusing. Maybe we can rename one of them to "Scheduled Data Service task". @nilminiwso2 WDYT?

**Comment by vinok88** [comment]
Renamed data service related UI to "DS Scheduled task" in https://github.com/wso2/carbon-data/pull/151. Please update the docs as appropriate. Let's call in "Data Services Scheduled task".

**Comment by praneesha** [comment]
Updated the info in [1].

[1] https://docs.wso2.com/display/EI620/Scheduling+Tasks

**Comment by bsenduran** [comment]
Current icon doesn't have a transparency background and the name is too long, hence reopening the issue
![DSS_task](https://user-images.githubusercontent.com/1879762/31541496-774107ca-b02c-11e7-84ec-90debabc09fb.png)

**Comment by vinok88** [comment]
@bsenduran, please suggest a new name to use.

**Comment by praneesha** [comment]
Please refer the email [1].

[1] Fixing Scheduled Tasks Menu Icon
