### ISSUE TITLE
Error messages are not consistent when JSON is malformed

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-ei#2793]
**Description:**
When the JSON payload is malformed, this customer has received the different type of errors>

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
EI 6.2.0

**Steps to reproduce:**
Created an API with a POST method.
Invoke the API sending the malformed JSON payloads.

**Comment by prabushi** [comment]
Related issue https://github.com/wso2/product-ei/issues/2051

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1074
