### ISSUE TITLE
JMS dual channel scenario dropping message type 

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#2795]
**Description:**
Custom formatter is not invoked when message type is set to application/bts in ESB proxy service. It is returned as text/xml instead. 

**Suggested Labels:**
Bug

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
Refer [1]

**Related Issues:**
[1] https://github.com/wso2/product-ei/issues/1798

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1193/files
