### ISSUE TITLE
[Bug] The default fault sequence is invoked when the Call mediator is used in non blocking mode. , 

### ISSUE THREAD

**Issue by menakaj** [wso2/product-ei#2808]
**Description:**

When the call mediator is used in non-blocking mode, the errors which occur in the lower levels of the mediation scenario are not handled by the defined error handler.
   
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Inbound EP with onError defined
2. First sequence with/ without onError defined
3. The second sequence without onError defined and using a non-blocking call mediator
4. Template sequence: where the error occurs.

When an error occurred in the template, the default fault handler is used instead of the defined onError handler.

**Related Issues:**

**Comment by Shakila** [comment]
This issue still remains for some protocols except http.

**Comment by Shakila** [comment]
Please find the fix:
https://github.com/wso2-support/carbon-mediation/pull/196

**Comment by Nirothipan** [comment]
Fix added to master with https://github.com/wso2/carbon-mediation/pull/1140
