### ISSUE TITLE
[Improvement] Implement file untouched x milliseconds by looking at last modified time

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/product-ei#2809]
**Description:**
VFS listener starts to read the file once it copied to the *transport.vfs.FileURI* folder. There are some situation file has been writing directly into the *transport.vfs.FileURI* folder. In such cases, VFS listener should not read the file until it completed. The improvement should have VFS listener wait x milliseconds un touch looking at the last modified time. If it passed the time gap, then start to read the file. We must introduce a new parameter to define the value.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
We

**Comment by Shakila** [comment]
We have to make this improvement in tooling as well.
