### ISSUE TITLE
Exception occurs in payload factory when using payload with special characters

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-ei#2810]
**Description:**

The issue occurred due to the mentioned payload since it contains special characters (escaped characters). These characters are valid for XML format but in here this XML formatted payload contains JSON message. The payload factory mediator used to takes that JSON message. When that that JSON message going through the clone mediator it will throw an exception (The clone mediator is a content aware mediator it will try to build the message and it will fail with an exception due to that escape characters which are valid in for XML but not valid for JSON).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

ESB 4.9.0 EI 6.3.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- [ ] Create a Proxy service as follows.
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="Test"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log level="full"/>
         <payloadFactory media-type="json">
            <format>$1</format>
            <args>
               <arg evaluator="json" expression="$.text"/>
            </args>
         </payloadFactory>
         <log level="full"/>
         <clone continueParent="true">
            <target>
               <sequence>
                  <log level="custom">
                     <property name="testClone" value="Inside Clone Mediator"/>
                  </log>
               </sequence>
            </target>
         </clone>
         <drop/>
      </inSequence>
   </target>
   <description/>
</proxy>
```

- [ ] Invoke the proxy service with the following payload.

```
<text>{"adress" : "20,&#xd;
Colombo 3,&#xd;
Palm Grove"}</text>
```

**Related Issues:**

**Comment by milindaperera** [comment]
@Drifftr : This fix requires documentation update. Please create documentation issue for this improvement
