### ISSUE TITLE
Support for dynamic parameters with inbound endpoints

### ISSUE THREAD

**Issue by hisamith** [wso2/product-ei#2813]
**Description:**
Currently EI does support [specifying inbound endpoint parameters as registry values](https://docs.wso2.com/display/EI640/WSO2+EI+Inbound+Endpoints#WSO2EIInboundEndpoints-Specifyinginboundendpointparametersasregistryvalues). 
But in real production environment we cannot use this features for some parameters such as "transport.vfs.FileURI", since we have to save the passwords in the registry to use the aforementioned feature. Therefore IMO we should provide the support to generate such parameters dynamically
ex: 
`<parameter name="transport.vfs.FileURI">ftp://USER_NAME_FROM_REGISTRY:{wso2:vault-lookup('my.password')}@PATH_FROM_REGISTRY</parameter>
`

**Affected Product Version:**
EI 6.*

**Comment by yasirjanjua** [comment]
Any Solution for this?
