### ISSUE TITLE
[Dev Studio Tooling] Data mapper not loading complex xml input

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/product-ei#2859]
**Description:**

When loading a complex XML to the datamapper diagram in the developer studio, an incorrect diagram was generated.

**Affected Product Version:**
6.4.0

**OS, DB, other environment details and versions:**    
OS : Ubuntu 16.04

**Steps to reproduce:**
1. Open the developer studio.
2. Create a proxy or an API.
3. Add a datamapper mediator.
4. Open the datamapper mediator diagram by clicking on the datamapper mediator.
5. Load the attached xml file(inputXML.xml file) into a datamapper diagram (As an input or an output).

Then the loaded diagram will look like following.

6. In the above XML file, there is an array of members. Then there is an array of members in each of those members(First level members). In side of 2nd level members, is an array of two members. Let them be 3rd level members. First member of 3rd level members does not contain any more members. But the second member of 3rd level members contain an array of members. In the developer studio datamapper diagram, it shows only the first member of the 3rd level members.

**Comment by dakshika** [comment]
@DMadhuranga Can you reupload the file again.

**Comment by dakshika** [comment]
Cannot reproduce this
