### ISSUE TITLE
[DOCS] Update location of default event publishers 

### ISSUE THREAD

**Issue by diegobrock** [wso2/product-ei#286]
In the ["Prerequisites to Publish Statistics"](https://docs.wso2.com/display/EI600/Prerequisites+to+Publish+Statistics#PrerequisitestoPublishStatistics-ConfiguringWSO2EIAnalytics) refer to the MessageFlowConfigurationPublisher and MessageFlowStatisticsPublisher files in the <EI_HOME> / wso2 / analytics / repository / deployment / server / eventpublishers / folder, but the correct folder is <EI_HOME> / repository / deployment / server / Eventpublishers /

Best regards

Diego Brock

**Comment by nandika** [comment]
Hi Diego,

Corrected the mentioned docs. Thanks for reporting this issue.

Nandika
