### ISSUE TITLE
Error in aggregate mediator when aggregating JSON responses with spaces

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#2898]
**Description:**
Exception occurs when aggregating json payloads with spaces. 

**Suggested Labels:**
Bug

**Affected Product Version:**
6.1.1 - WUM updated

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

- Create a synapse configuration with these configs (clone mediator with two target endpoints which responses JSON payload to aggregate)

- Add an aggregate mediator to aggregate mediator aggregate messages and log(with json-eval(.$)) them at on Complete sequence. Add the expression property to OnComplete sequence with ita value pointing to a string with spaces.

- com.google.gson.stream.MalformedJsonException:Use JsonReader.setLenient(true) to accept malformed JSON will occur with a socket timeout exception

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1229
