### ISSUE TITLE
Statistic/tracing not visible in search data

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-ei#2899]
**Description:**
Create an API --> enable statistics and tracing --> search the API through search box --> statistics/ tracing details are not visible/ update.

**Suggested Labels:**
ESB 5.0.0

**Affected Product Version:**
ESB 5.0.0

**Comment by isudana** [comment]
PR merged 
https://github.com/wso2/carbon-mediation/pull/1112
