### ISSUE TITLE
Secret alias is not working while deploying data source via capp

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#2938]
**Description:**
Getting an error while deploying a data source which has a secret alias as the password via a capp.

We have disabled the secret alias evaluation at [1] with the false value. Need to make it true.
[1] - https://github.com/wso2/carbon-commons/blob/master/components/ndatasource/org.wso2.carbon.ndatasource.capp.deployer/src/main/java/org/wso2/carbon/ndatasource/capp/deployer/DataSourceCappDeployer.java#L183

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2EI-6.4.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Add the org.wso2.carbon.ndatasource.capp.deployer_4.6.49.jar to dropins directory
2. Configure secure vault and add a secret alias for the data source password
3. Create a data source with a secret alias and try to deploy the capp

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/carbon-commons/pull/333
