### ISSUE TITLE
Intermittent test failure in JMSEndpointTestCase

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#2941]
**Description**
Intermittent test failure in JMSEndpointTestCase of 4.9.0 jenkins build.

**Error message**
Message not received at SimpleStockQuoteService

**Stacktrace**
junit.framework.AssertionFailedError: Message not received at SimpleStockQuoteService
at junit.framework.Assert.fail(Assert.java:47)
at org.wso2.carbon.esb.jms.transport.test.JMSEndpointTestCase.testJMSProxy(JMSEndpointTestCase.java:61)

Affected Product Version
WSO2 ESB 4.9.0/ EI 6.4.0
[Logfile.log](https://github.com/wso2-support/product-esb/files/2561534/JMSEndpointTestCaseFullLog.log)

**Comment by ThishaniLucas** [comment]
This issue still persists. Now the exception is
```
org.awaitility.core.ConditionTimeoutException: Condition returned by method "isMessagesConsumed" in class org.wso2.carbon.esb.jms.transport.test.JMSEndpointTestCase was not fulfilled within 300 seconds
```
