### ISSUE TITLE
[6.1]When you offset, the hosted web apps directed to the default ports in mgt console

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#295]
1. Set an offset as 20 in carbon.xml
2. Deploy a webapp/jaxrs and click on go to url or find service.
3. It should open a page as http://192.168.124.1:8300/example/.  But it opens as http://192.168.124.1:8280/example/.
4. It is just a bug in direction url. Because when you type it explicitly, you can see it is hosted on offset port.

**Comment by ushanib** [comment]
WADL files also open with the default ports

**Comment by nandika** [comment]
we will be removing web app hosting features. Service hosting will be supported via micro-services with msf4j. If web applications or jax-rs applications should be hosted, we recommend tomcat to be used
