### ISSUE TITLE
[Tooling] [RCP] Change the menu order

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#2986]
**Description:**
Change the current menu order to match UX

**Suggested Labels:**
improvement

**Suggested Assignees:**
Heshitha

**Affected Product Version:**
6.5.0

**OS, DB, other environment details and versions:**    
![screen shot 2018-12-12 at 4 16 02 pm](https://user-images.githubusercontent.com/6497326/49864835-623bca80-fe29-11e8-88f9-a798ece4b8a0.png)

**Comment by dakshika** [comment]
Order

1. ESB Solution Project
2. ESB Config Project
3. Composite Application Project
4. Project...

**Comment by dakshika** [comment]
we are planning to add ESB solution project to the menu

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/816 and https://github.com/wso2/devstudio-tooling-platform/pull/149
