### ISSUE TITLE
Backend shows some unwanted log when accessing the API section.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#30]
**Environment**

- OS-Ubuntu 14.04
- JDK- 1.8.0_121
- Browser-Chrome Version 51.0.2704
- EI default M1 pack

**Steps**

1. Start the server with integrator.sh 
2. Login to the management console
3. Access the API section. 
You could see the below unwanted log in the backend

**java.io.FileNotFoundException: ./repository/conf/axis2/axis2.xml (No such file or directory)**

**Comment by madhawa-gunasekara** [comment]
This was fixed with https://github.com/wso2/carbon-mediation/pull/774

**Comment by madhawa-gunasekara** [comment]
This issue is fixed.

**Comment by chalitha87** [comment]
Verified in EI alpha pack on 14th of feb and issue got resolved.
