### ISSUE TITLE
[Tooling] Artifact.xml file will not be updated once an artifact is deleted from the synapseConfigProject

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#3018]
**Description:**
Once we delete an artifact from synapseConfig, only pom will be updated. Artifact.xml will not be updated.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI - 6.4.0

**OS, DB, other environment details and versions:** 
OS - macOS High Sierra
JDK - 1.8   

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
fixed in the latest master
