### ISSUE TITLE
[Tooling] Test creating a project out of the workspace

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#3019]
**Description:**
Creating a project out of the workspace results in a number of errors.
1. The ConnectorExporter project and the Registry Resources project still get created in the workspace.
2. A project gets created inside the **same** project. e.g. the following directory structure gets created intermittently.
     - synapseCompositeApplication
            - synapseCompositeApplication

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/820
