### ISSUE TITLE
Issue with the value of message processor's redelivery attempts

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#3020]
**Description:**
It always shows the default value 4 in the management console.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
https://github.com/wso2-support/carbon-mediation/pull/205/

**Comment by pramodya1994** [comment]
This issue fixed in the master branch
https://github.com/wso2-support/carbon-mediation/commit/11dc3991b3e3e717bc050646a2648f48c615e18f

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/824
