### ISSUE TITLE
[Tooling] EI 6.4.0 updater discovery task stuck around 50% and shows no updates

### ISSUE THREAD

**Issue by Drifftr** [wso2/product-ei#3033]
**Description:**
When we try to update with updater tool it's update discovery task stuck around 50% and won't find any updates whether there are new updates. This discovery task continues once we fire any diagram event in ESB diagram such as drag and drop a mediator. 

**Affected Product Version:**
EI Tooling 6.4.0

**Steps to reproduce:**
1. Start EI Tooling updater tool (Developer Studio -> Check for updates)

**Comment by dakshika** [comment]
possible duplicate
