### ISSUE TITLE
[Tooling] Eclipse unable to detect running state in remote server after restart

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#3038]
**Description:**
User can create a remote server on Developer Studio to deploy CAPP in a remote server. Once Developer studio stops and starts it again, It stays in "Starting, Synchronized" state. Each time Eclipse restarted, it should be able to identify the running EI servers and update it's state into "Started" state.

**Suggested Labels:**
Bug

**Affected Product Version:**
WSO2 EI tooling 6.4.0 and below

**Steps to reproduce:**
1) Create remote server in Developer Studio.
2) Deploy CAPP into the remote server by using Developer Studio.
3) Restart the Developer Studio.
4) Remote server state in "Starting, Synchronized".

**Comment by dakshika** [comment]
@madushadhanushka Can you elaborate this
