### ISSUE TITLE
[Query] Including proxyPort in caterlina-server.xml

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#304]
**Environment**
EI610 build pack- 16/03/2014

Is there any specific reason for adding the "proxyPort="8280" in the default catalina-server.xml file?

**Comment by madhawa-gunasekara** [comment]
We have added it to show the correct URL in service URL in the UI

**Comment by nandika** [comment]
Remove default proxyPort setting. This should be added if needed
