### ISSUE TITLE
[EI610] Change the default clustering pattern to 'nonWorkerManager'

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#305]
Since we are not recommending the worker manager cluster for EI610 [1] it is better to set the default clustering pattern to 'nonWorkerManager' in axis2.xml
<parameter name="clusteringPattern">nonWorkerManager</parameter>

If we set this property as the default clustering pattern we do not need to ask the user to change the clustering pattern when configuring "Setting up scheduled tasks" section in document [1] 

[1] https://docs.wso2.com/display/EI600/Clustering+the+Integration+Profile

**Comment by sashikamw** [comment]
Description provided in the axis2.xml [2] should also be changed accordingly

[2]

**Comment by nandika** [comment]
Fixed
