### ISSUE TITLE
[Tooling] Proxy request failed in Proxying a SOAP Service Template 

### ISSUE THREAD

**Issue by pramodya1994** [wso2/product-ei#3065]
**Description:**
Proxy request failed in Proxying a SOAP Service Template due to wrong content type text/xml. Content type should be application/xml.

**Suggested Labels:**
Bug

**Affected Product Version:**
WSO2 EI tooling 6.4.0 and below    

**Steps to reproduce:**
1. Create a project using Proxying a SOAP Service Template.
2. Deploy the soapServiceCarbonApplication.
3. Follow the instructions in the tutorial and try to send the request.

**Comment by dinuish94** [comment]
The issue is with the Request body and not the content type. 

Request body should be wrapped inside a SOAP envelope as below in order to comply with SOAP 1.1 and 1.2 standards.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Header/>
<soapenv:Body>
    <echo:echoString xmlns:echo="http://echo.services.core.carbon.wso2.org">
        <in>Hello</in>
    </echo:echoString>
</soapenv:Body>
</soapenv:Envelope>
```
