### ISSUE TITLE
Incorrect default bundle for Micro Integrator Profile in profile-creator.bat

### ISSUE THREAD

**Issue by zblue89** [wso2/product-ei#3066]
**Description:**
Micro integrator profile created using `profile-creator.bat` script cannot be started due to missing some libraries. After comparing with `profile-creator.sh`, I found that the value of the DEFAULT_BUNDLES for micro-integrator profile are different. The DEFAULT_BUNDLES in `profile-creator.bat` is using `business-process-default` bundle info.

**Affected Product Version:** 6.4.0

**OS, DB, other environment details and versions:**  Windows 10

**Steps to reproduce:**
1. Run `profile-creator.bat`
2. Select `6.Micro Integrator profile`
3. Run `micro-integrator.bat`

**Related Issues:**
none

**Comment by arunans23** [comment]
@zblue89 Thank you for reporting the issue. This will be fixed in our next release.
