### ISSUE TITLE
Inconsistent behavior of XSLT mediator output method 

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/product-ei#3073]
**Description:**
Inconsistency behavior in XSLT mediator output method.

When using an XSLT mediator in ESB5.0.0 the " output method " property set as "text" and then invoke SOAP message. It will return the output text file with the plain text content **without namespaces**. But in EI 6.4.0 the " output method " property set as "text" and then invoke SOAP message. It will return the output text file with the plain text content **with namespaces**.

**Suggested Labels:**
XSLT mediator / EI 

**Affected Product Version:**
EI 6.4.0 

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**

When we using the ESB 5.0.0 :
 a) In XSLT file  " output method " property set as "text"  
 b) Invoke SOAP message.

**Expected Output**
It will return the output text file with the plain text content **without namespaces**.
**Actual Output**
It will return the output text file with the plain text content **without namespaces**.

When we using the EI 6.4.0 :
 a) In XSLT file  " output method " property set as "text"  
 b) Invoke SOAP message.

**Expected Output**
It will return the output text file with the plain text content **without namespaces**.
**Actual Output**
It will return the output text file with the plain text content **with namespaces**.

**Comment by indikasampath2000** [comment]
The above behavior due to https://github.com/wso2/wso2-synapse/pull/952. You should be able to fix the problem by adding the following property.

```xml
<property name="messageType" scope="axis2" value="text/plain"/>
```

We have to set correct formatter to write the expected output as above. It has more control than the behavior which was previously by looking at payload and selecting the formatter.
