### ISSUE TITLE
Missing docs for enforcing XML declarations in xml outputs

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#3078]
**Description:**
Feature to enforce xml declaration in xml outputs using a axis2 scope property does not have any documentation. 

**Related PR:**
https://github.com/wso2-support/wso2-axis2/pull/59
 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
ESB 5.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/1629

**Comment by nandika** [comment]
please check whether relevant documentation is available in EI 6.5.0

**Comment by Shakila** [comment]
Please give priority to this ticket as customers use this property in EI 6.4.0.
`<property name="WRITE_XML_DECLARATION" scope="axis2" type="STRING" value="true"/>`
