### ISSUE TITLE
[6.1] build.xml in samples/axis2Client should be updated according to the new folder structure

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#308]
When you run below ant command, build will fail since the lib folder is no longer inside components folder-
BUILD FAILED
/home/ushani/WSO2_WORK/Products/EI/6.1.0-Release/16-3-2017/wso2ei-6.1.0-SNAPSHOT/samples/axis2Client/build.xml:307: /home/ushani/WSO2_WORK/Products/EI/6.1.0-Release/16-3-2017/wso2ei-6.1.0-SNAPSHOT/repository/components/lib does not exist.
 
ant stockquote -Daddurl=http://localhost:8280/services/StockQuoteProxy

Please fix all the applicable places according to the new structure.

   <fileset dir="../../repository/components/lib">
                <include name="*.jar"/>
            </fileset>

**Comment by vinok88** [comment]
Already reported in https://github.com/wso2/product-ei/issues/306. Hence closing this issue.
