### ISSUE TITLE
Colossal EI Tooling outline view space for REST APIs

### ISSUE THREAD

**Issue by abhishekdesilva** [wso2/product-ei#3085]
**Description:**
When creating a REST API through the EI Tooling, it was observed that the outline space allocated is unnecessarily large and inconvenient to use. 

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
This should be fixed in the future releases of the EI Tooling. 

**OS, DB, other environment details and versions:**  
N/A  

**Steps to reproduce:**
This can be observed when a new REST API is created through the EI Tooling or when opening an existing REST API.

**Related Issues:**
N/A

**Comment by dakshika** [comment]
Fixed in master
