### ISSUE TITLE
Remove deepCheck section in payload factory mediator from documents

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#3096]
**Description:**
Although DeepCheck attribute in payload factory mediator has been reverted, the documents are not updated yet. 
URL : [https://docs.wso2.com/display/EI640/PayloadFactory+Mediator]

**Suggested Labels:**
Doc[Product-excellance]

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
As per mail thread [1], this seems to have been removed in ESB 5.0.0, and later in EI 6.4.0. I removed the content from those releases.

[1] "conflicting VFS file merging with payloadFactory"
