### ISSUE TITLE
Cannot login to MB Management console due to CSRF validation

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#31]
When accessing the management console following error was observed, which prevent console access.

> WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.112, method:GET, uri:/error.html, error:request token does not match page token) {org.owasp.csrfguard.log.JavaLogger}

**Comment by himasha** [comment]
Same issue as https://github.com/wso2/product-ei/issues/21.
