### ISSUE TITLE
[6.1] The whole screen flickers when you click on a link in Chrome.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#310]
The whole screen flickers when you click on a link in Chrome. See the attached screen cast vedio.
Chrome Version 50.0.2661.86 (64-bit)

[Screencast from 03-17-2017 02:38:12 PM.webm.zip](https://github.com/wso2/product-ei/files/850089/Screencast.from.03-17-2017.02.38.12.PM.webm.zip)

**Comment by himasha** [comment]
Unable to reproduce in  EI-6.2.0-m3 pack. (Chrome Version 59.0.3071.115)
