### ISSUE TITLE
Cannot deploy a CApp through Dev Studio remote server

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-ei#311]
Cannot deploy a CApp from Dev Studio through the remote server feature. When trying to deploy a CApp, the following error message appears in the EI Server side.

[EI-Core]  WARN - JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri://services/CarbonAppUploader, error:required token is missing from the request

**Comment by erandacr** [comment]
Hi,

I tried deploying a Capp from dev studio remote server and it worked fine without any issue. I didn't observe above.

But however, can you update 
_org.owasp.csrfguard.UnprotectedMethods_ parameter in <PROD_HOME>/conf/security/Owasp.CsrfGuard.Carbon.properties as follows,

> org.owasp.csrfguard.UnprotectedMethods=GET,POST

and try again. Please refer [1] for more info.

[1]. https://wso2.org/jira/browse/ESBJAVA-4848

Thanks,
Eranda

**Comment by vinok88** [comment]
Verified in 6.1 alpha pack.
