### ISSUE TITLE
Cannot have an empty value for CallTemplate parameters

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-ei#3129]
**Description:**
In the CallTemplate mediator it is possible to leave the value parameter null in Design mode and able to save the project as well, however when you switch to source XML due to that null value we are not able to save the project or switch back to Design view.

**Suggested Labels:**
EI Tooling, 6.4.0

**Suggested Assignees:**
@prabushi @rosensilva 

**Affected Product Version:**
6.4.0

**Comment by dakshika** [comment]
fixed in latest master
