### ISSUE TITLE
[Samples] Failed to execute sample clients

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#315]
milinda@milinda-ThinkPad-T540p:~/WSO2/Integration/EI/GIT/wso2ei-6.1.0-SNAPSHOT/samples/axis2Client$ 
milinda@milinda-ThinkPad-T540p:~/WSO2/Integration/EI/GIT/wso2ei-6.1.0-SNAPSHOT/samples/axis2Client$ ant stockquote -Daddurl=http://localhost:8280/services/StockQuoteProxy
Buildfile: /home/milinda/WSO2/Integration/EI/GIT/wso2ei-6.1.0-SNAPSHOT/samples/axis2Client/build.xml

init:

BUILD FAILED
/home/milinda/WSO2/Integration/EI/GIT/wso2ei-6.1.0-SNAPSHOT/samples/axis2Client/build.xml:307: /home/milinda/WSO2/Integration/EI/GIT/wso2ei-6.1.0-SNAPSHOT/repository/components/lib does not exist.

Total time: 0 seconds

**Comment by erandacr** [comment]
Already reported in #306. Hence closing this issue.
