### ISSUE TITLE
[Doc] Correct the load balancing configurations in the clustering documents 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#316]
Following should be updated in the nginx configuration section.

1. Step one in the nginx configuration contains irrelevant host names
2. Nginx configurations provided in the clustering document [1] should be correct according to the clustering pattern.
3. For the "Create SSL certificates as follows" section, we should mention the user to add the cert to the clienttruststore.jks file

[1] https://docs.wso2.com/display/EI600/Clustering+the+Integration+Profile#ab91c48c7f894b8da7f18d381c175c96

**Comment by praneesha** [comment]
1. Updated the hostnames.
2. Updated accordingly.
3.Added the step.
