### ISSUE TITLE
Management console become unresponsive and frozen while undeploying the inbound endpoint

### ISSUE THREAD

**Issue by nuwanw** [wso2/product-ei#3164]
When the inbound endpoint has the coordination set to false and while undeploying the inbound endpoint, Server become unresponsive, due to the thread join call in the undeployment code. if the inbound runner thread busy with work, it has to wait until if finish the work.

**Comment by nuwanw** [comment]
Similer issue https://github.com/wso2/product-ei/issues/3048

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/1119
