### ISSUE TITLE
[EI610][DOC] Improvements to Clustering EI profile Document

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#317]
Some of the required steps are missing in the clustering doc [1]. Follow the below suggestions to improve the EI profile document.

1 . As per the step 4 in the "**_Configuring the integration profile node_**" section, following section should be removed from the doc.

```
Change the following clustering properties.
<parameter name="properties">
            <property name="backendServerURL" value="https://${hostName}:${httpsPort}/services/"/>
            <property name="mgtConsoleURL" value="https://${hostName}:${httpsPort}/carbon"/>
</parameter>
```

2. Instruct the user on how to set up rsync for the EI cluster profile

3. Configuring proxy port in the caterlina-server.xml

4. Configure "WSDLEPRPrefix" in the axis.xml

5. "**_Setting up scheduled tasks_**" section is not required to document specifically, if we pack the product with default clustering pattern as 'nonWorkerManager'

[1] https://docs.wso2.com/display/EI600/Clustering+the+Integration+Profile#ab91c48c7f894b8da7f18d381c175c96

**Comment by praneesha** [comment]
1. Removed it.
2.Added docs on rsync.
3.

**Comment by sashikamw** [comment]
To share the tenant artifacts across the cluster, rsync should be configured for the <EI_HOME>/repository/tenant/ location. Better to include this into the documentation

**Comment by praneesha** [comment]
Added the following tip in clustering docs.

"Configure rsync in the <EI_HOME>/repository/tenant/ directory to share the tenant artifacts across the cluster."

**Comment by praneesha** [comment]
3. Removed the "Setting up Scheduled Tasks" section from EI 6.1.0 doc in [1], because the following property is shipped with the NonWorkerManager value by default in 6.1.0, so that user doesn't have to change it.

<parameter name="clusteringPattern">nonWorkerManager</parameter>

[1] https://docs.wso2.com/display/EI610/Clustering+the+Integration+Profile
