### ISSUE TITLE
[EI610] Failed to browse h2 database 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#318]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI610 PreAlpha Pack
DB - h2

Scenario 1
---------------
**Steps**
1. Configure the carbon.xml with h2 configuration
```
<H2DatabaseConfiguration>
        <property name="web"/>
        <property name="webPort">8082</property>
        <property name="webAllowOthers"/>        
</H2DatabaseConfiguration>
```
2. Go to <EI_HOME>/bin and run ./h2.sh to browse the h2 database

**Observations**
Error: Could not find or load main class org.h2.tools.Server

Note - 
Adding the  "h2-1.3.175.jar" to <EI_HOME>/bin locaton will fix the issue

Scenario 2
---------------
**Steps**
1. Configure the carbon.xml with h2 configuration for other products in EI (Analytics, BPS, Broker)
2. Browse the h2 database using " http://localhost:8082"

**Observation**
Failed to browse the databse

**Comment by nandika** [comment]
Added wso2/components/plugins directory to script classpath
