### ISSUE TITLE
Generating log files per Inbound Endpoint

### ISSUE THREAD

**Issue by Nipunich** [wso2/product-ei#3182]
**Description:**
When there are two inbound endpoints it's required to have separate log files for each endpoint.

Ex: If there are  two JMS inbound endpoints named IE_SAMPLE1 and IE_SAMPLE2,  two separate log files have to be generated for each Inbound Endpoint as IE_SAMPLE1.log and IE_SAMPLE2.log.

**Comment by v-scottbechtel** [comment]
-1

This would deviate away from the central single log approach we have with wso2carbon.log. 

Perhaps https://github.com/wso2/product-ei/issues/4702 addresses the above concern?
