### ISSUE TITLE
No_Keep_Alive property not working when using a blocking call

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-ei#3195]
**Description:**
When using a blocking call with the "no_keep_alive" property, the connection won't close.  

**Affected Product Version:**
EI 6.2.0

**Related Issues:**
https://github.com/wso2-support/wso2-synapse/pull/193

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2/wso2-axis2/pull/143/commits/4b71b05ce67ed01aa6b69f34c3cf8620e82bde9a
