### ISSUE TITLE
Regression issue on native JSON support for enrich mediator

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#3203]
**Description:**
When enrich mediator has inline XML and input payload has a JSON payload following error occurs

> Source failed to get inline JSONinlineJSONNode=<dat:insert_pmr_post_miles_req_rep_detail_operation 

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.1.1 WUM updated

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
`    <inSequence>
         <enrich>
            <source type="inline" clone="true">
               <a>1234</a>
            </source>
            <target type="property" property="prop"/>
         </enrich>
         <log level="custom">
            <property name="bla" expression="get-property('prop')"/>
         </log>
         <respond/>
      </inSequence>`

**Related Issues:**
https://github.com/wso2/product-ei/issues/2885

**Comment by ThishaniLucas** [comment]
Fixed with https://github.com/wso2/wso2-synapse/commit/a60fe247ad40649c1fdf1c3d4ca949803ff02146
