### ISSUE TITLE
Document issue in "Clustering the ESB Profile

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#3214]
**Description:**

Doc - [https://docs.wso2.com/display/EI640/Clustering+the+ESB+Profile](https://docs.wso2.com/display/EI640/Clustering+the+ESB+Profile) 

The document mensions `If you are using MySQL 5.7 you need to use the mysql5.7.sql script instead of the mysql.sql script.`. It should be recorrected as `If you are using MySQL 5.7 or above`.

**Suggested Labels:**
[Type/Docs](/wso2/product-ei/labels/Type%2FDocs)  
[Doc[Product-excellance]](/wso2/product-ei/labels/Doc%5BProduct-excellance%5D)

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Modified the note in EI 6.4.0 and EI 6.x.x as discussed [1].

[1] https://docs.wso2.com/display/EI640/Clustering+the+ESB+Profile
