### ISSUE TITLE
Publishing ESB statistic data to Prometheus

### ISSUE THREAD

**Issue by MalshaL** [wso2/product-ei#3229]
**Description:**
Prometheus is an open source system monitoring tool that is widely used as it can be easily integrated to monitor system behavior. It makes use of statistic data of a system exposed over an HTTP endpoint to build a highly dimensional data model, that can be queried to generate graphs and alerts. 

The main objective of this attempt is to enable users to make use of a widely used system monitoring tool to analyze the behavior of WSO2 ESB.

**Suggested Labels:**
enhancement

**Affected Product Version:**
6.5.0

**Comment by Nirothipan** [comment]
We need to check whether we need to keep the internal APIs enabled by default https://github.com/wso2/product-ei/pull/3399/files#diff-44c59681fb962c36a0c0f85366b45c18R76

**Comment by MalshaL** [comment]
Please refer [here](https://docs.google.com/document/d/1OFzsxwljuXC6CxmefmT3DQAXEHEQs7s5MtmLwzuoFFM/edit?usp=sharing) for the document briefing about the feature and required configuration changes.

**Comment by Nirothipan** [comment]
The PRs related to the feature is merged. We need to update the docs.

**Comment by RukshiW** [comment]
Added the documentation in [1].

[1] https://docs.wso2.com/display/EI650/Monitoring+the+ESB+Profile+with+Prometheus

**Comment by Nirothipan** [comment]
@RukshiW The port seems to be not correct . It has to be 9191.

**Comment by RukshiW** [comment]
Corrected the port as mentioned.
