### ISSUE TITLE
Problems Starting wso2 enterprise integrator server from EI Tool

### ISSUE THREAD

**Issue by willamesyano** [wso2/product-ei#325]
Hi guys, 

I have some issues starting a new project with Enterprise Integrator 6.0 and so far I'm unable to start a server from within the eclipse distribution that comes with the EI Tool.

When I was working with ESB, I used to create a server and create a Runtime environment pointing the CARBON_HOME variable to <ESB_INTALLATION_DIR>/bin, but if I do the same with Enterprise Integrator I get the following error:

```
Configuration error
    java.io.FileNotFoundException: C:\Users\...\wso2ei-6.0.0\repository\conf\etc\logging-bridge.properties (The system cannot find the path specified)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(Unknown Source)
    at java.io.FileInputStream.<init>(Unknown Source)
    at java.io.FileInputStream.<init>(Unknown Source)
    at 
```

So apparently the default arguments used by eclipse in the launch configuration was all wrong.It was using the file structure for ESB projects, and that's what caused the FileNotFoundException.For example, the default server configuration would have something like

`-Dconf.location="<CARBON_HOME>/repository/conf"`

When it should be:

`-Dconf.location="<CARBON_HOME>\conf"`

I found this after some digging with the integrator.bat script. Information about the configuration differences between ESB and EI can be found [here](https://docs.wso2.com/display/EI600/Upgrading+from+WSO2+Enterprise+Service+Bus).

There is something that could be done? 

 I'm running on java version "1.8.0_121", windows 10.

**Comment by vinok88** [comment]
Hi,
Yes, those changes are required due to the folder structure changes introduced in the EI. Great that you identified the required changes. EI tooling also will be updated according to these changes. I'm closing the issue since it works now.

**Comment by Abhishek2kr** [comment]
I have downloaded the latest release of API manager still facing the above issue. Please help.
