### ISSUE TITLE
serviceGroup is not work in Data Service

### ISSUE THREAD

**Issue by Sunzhuokai** [wso2/product-ei#3251]
**Description:**

we can not edit the serviceGroup when add a new data service.   
when edit the existing data service with xml,we add a serviceGroup,but it does't work
**Suggested Labels:**

bug
**Suggested Assignees:**

**Affected Product Version:**
6.4.0
**OS, DB, other environment details and versions:**    
windows 10 H2
**Steps to reproduce:**
![image](https://user-images.githubusercontent.com/8599906/53483401-6092b200-3abc-11e9-80c6-b3d1a5f0f8aa.png)
![image](https://user-images.githubusercontent.com/8599906/53483529-a0599980-3abc-11e9-86f3-b7e060162d31.png)

**Related Issues:**

**Comment by nandika** [comment]
Hi Sunzhuokai,
This service group concept comes from axis2 web services engine we are using to publish services and service group concept is not used practically. Hence by default, service group name and service name will be the same. Can you explain your requirement for service groups

**Comment by Sunzhuokai** [comment]
@nandika But in Deployed Services list page，we use service group to group services
![image](https://user-images.githubusercontent.com/8599906/53545041-187a9a80-3b63-11e9-808e-a4a589248cd5.png)
