### ISSUE TITLE
Docker containers for ESB

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#3262]
**Description:**
Issue with IndexDocumentCreator on how it handles Collections in Carbon-registry. 
If the resource is a collection, no need to check for media type mapping. 

**Affected Product Version:**
4.9.0

**Comment by prabushi** [comment]
Related issue https://www.wso2.org/jira/browse/REGISTRY-3639

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2-support/carbon-registry/pull/162
