### ISSUE TITLE
[Dev Studio New] Issue when adding a new argument for Payload factory mediator

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3277]
**Description:**
I tried to create a Payload Factory Mediator in the new EI tool and tried to add an argument. I gave the argument type as expression and tried to enter the expression. When I clicked on the value field, suddenly XPath Property Editor popped up.

<img width="525" alt="screen shot 2019-03-04 at 1 29 11 pm" src="https://user-images.githubusercontent.com/17047910/53719194-6fde7a80-3e83-11e9-9f89-076e4262167f.png">

<img width="641" alt="screen shot 2019-03-04 at 1 29 28 pm" src="https://user-images.githubusercontent.com/17047910/53719170-5806f680-3e83-11e9-8db6-812a729dcf4f.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a RESTAPI
2. Drag and drop a payload factory mediator
3. Try to add an argument and give type as expression and try to enter an expression.

**Related Issues:**

**Comment by dakshika** [comment]
@dilee We need to do few things here..

1. we need to add button with each filed and make popup appear after the button click. 
2. In the Xpath property editor, we need to move the xpath field into the top of the window and make it prominent.

**Comment by dakshika** [comment]
this will be fix with #3731, hence closing
