### ISSUE TITLE
Cache mediator return empty response when Content-Type:application/json

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-ei#3287]
**Description:**
In ESB 5.0.0 cache mediator return empty response when content-type is application/json

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
1. Create API to call a mock backend with JSON response.
2. In API IN sequence add a cache mediator to cache the response.
3. In API OUT sequence add the cache collector
4. Send the GET request to the API with headers content-type:application/json and accept:application/json
5. Invoke the API and get the response.
6. The second request does not return the response from the cache

Note: content-type:application/json and accept:application/json headers with XML response working properly. 

Currently using the following workaround to overcome the issue.

<onCacheHit>
         <log>
            <property name="debug_log" value="IN CACHE - READ RESPONSE FROM CACHE"/>
         </log>
         <filter xmlns:ns="http://org.apache.synapse/xsd" source="get-property('transport','Accept')"
                 regex="application/json">
            <then>
               <property name="NO_ENTITY_BODY" scope="axis2" action="remove"/>
               <property name="messageType" expression="$trp:Accept" scope="axis2"/>
               <respond/>
            </then>
            <else>
               <respond/>
            </else>
         </filter>
</onCacheHit>

**Comment by keerthu** [comment]
This issue is fixed in EI 6.1.1 with the pr https://github.com/wso2/carbon-mediation/pull/965.
