### ISSUE TITLE
sonarqube build of carbon-mediation fail.

### ISSUE THREAD

**Issue by maheshika** [wso2/product-ei#3290]
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project carbon-mediation: Can not execute Findbugs: This project contains Java source files that are not compiled. -> [Help 1]

**Comment by nandika** [comment]
Can you check the solutions suggested here?

https://github.com/spotbugs/sonar-findbugs/issues/49
