### ISSUE TITLE
Payload factory mediator does not function correctly for XML arrays

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-ei#3296]
**Description:**
Getting &lt; and &gt; instead of < and > when getting the XML payloads as arrays. This issue has happened after applying the WSO2-CARBON-PATCH-4.4.0-0424 patch and the WSO2-CARBON-PATCH-4.4.0-3151 patch. This was reproduced in ESB 5.0.0 wum pack also. 

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
ESB 5.0.0

**Comment by nandika** [comment]
Verify for 6.5.0 release
