### ISSUE TITLE
Support dynamic names for property mediator

### ISSUE THREAD

**Issue by maheeka** [wso2/product-ei#3300]
**Description:**
Property mediator does not allow dynamic names at the moment. It is supported for other mediators - e.g. sequence mediator. This is a useful feature to have. 

**Affected Product Version:** ESB 5.0.0, EI 6.0.0 - 6.3.0

**OS, DB, other environment details and versions:**    N/A

**Steps to reproduce:**
Try the following configuration
```
<property name="propertyName" expression="HelloMessage" />
<property name="propertyValue" expression="This is a hello message" />
<property name="{get-property('propertyName')}" expression="$ctx:propertyValue" />
```
In sequence mediator, following works.
`<sequence key="{get-property('sequence')}"/>`

Similar support is required.

**Fix**
Use `createValue` method in `ValueFactory` to get the property name[1] instead of using the `name` attribute value in [2].

[1] https://github.com/wso2/wso2-synapse/blob/f5e7d024f16b8d526404905c930d304de3b7ca60/modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java#L51
[2] https://github.com/wso2/wso2-synapse/blob/f5e7d024f16b8d526404905c930d304de3b7ca60/modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java#L75

**Comment by yairhdz** [comment]
It would be very useful. Please add this functionality.
