### ISSUE TITLE
Cache content read after a registry resource updated using a property mediator

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-ei#3303]
**Description:**
In ESB 5.0.0, when a registry resource update using a property mediator, it is updated in the registry. but when we try to read the registry content. It is not retrieving the updated values until 15 seconds (registry cache expiry duration).

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
1. Add a resource file to the registry. eg. test.xml
2. Create an API to update the resource using a property mediator.
3. Get the content of the registry resource to a property.
4. log the content of the registry resource.
5. log does not contain the updated content of the registry.
(If wait more than 15 sec and log it will contain the updated content)

**Comment by madushadhanushka** [comment]
Related issue https://github.com/wso2/product-ei/issues/2725

**Comment by nandika** [comment]
This issue has been fixed in issue #2725
