### ISSUE TITLE
Handle NULL values in JSON payload

### ISSUE THREAD

**Issue by lkokila** [wso2/product-ei#3305]
**Description:**
When a JSON  payload is processed in order to retrieve its elements via the json-eval() method or by evaluating the JSON path, the NULL value is processed as a string (i.e. "null")

For example, the following JSON payload is processed while considering the "object" element has the string "null" as its value.

`{"object":null}`

**Suggested Labels:**
critical

**Affected Product Version:** EI-6.1.1

**Steps to reproduce:**
1. Send a JSON payload to the EI server (to an API or a proxy service) with a null element. (ex: {"object":null})
2. Retrieve the value of the above "object" via the following expression. 
`expression="$.object"`

**Comment by arunans23** [comment]
Sample configuration to reproduce this issue.

```
<api xmlns="http://ws.apache.org/ns/synapse" name="SampleAPI" context="/sample" version-type="context">
   <resource methods="POST">
      <inSequence>
         <payloadFactory media-type="xml">
            <format>
               <Person xmlns="">
                  <name>$1</name>
                  <id>$2</id>
               </Person>
            </format>
            <args>
               <arg evaluator="json" expression="$.name"/>
               <arg evaluator="json" expression="$.id"/>
            </args>
         </payloadFactory>
         <respond/>
      </inSequence>
   </resource>
</api>
     
```

**Input payload** 
```
{
	"name": "Alice",
 	"id": null
}
```

**Expected output**

```
<Person>
    <name>Alice</name>
    <id/>
</Person>
```
 
**Actual output**

```
<Person>
    <name>Alice</name>
    <id>null</id>
</Person>
```
