### ISSUE TITLE
Tooling does not switch to correct perspective when importing a project

### ISSUE THREAD

**Issue by a5anka** [wso2/product-ei#3317]
## Description

I used the latest tooling to import a project. But after importing the window was blank and showed nothing. I had to switch to the default perspective to get the project view. A new user can get confused with this behavior.

## Steps to reproduce

1. Download the latest EI tooling
2. Go to File -> import and import existing WSO2 project

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/138
