### ISSUE TITLE
Management console application dashboard doesn't list down all the artifacts in car file, UI bug

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-ei#3321]
**Description:**
Management console, application dashboard doesn't list down the Templates within carbon application. (refer below image, templates are misssing from there)

<img width="1680" alt="screen shot 2019-03-08 at 3 49 01 pm" src="https://user-images.githubusercontent.com/13187638/54022979-c3b9ce00-41b9-11e9-850d-37c093cd6fe7.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1) Create a car file with Templates using EI Tooling
2) Deploy the car file in Enterprise Integrator
3) Click on Home --> List Carbon Applications --> Click on deployed carbon application

It does list down all the artifacts except Templates

**Related Issues:**

**Comment by Nirothipan** [comment]
related PR https://github.com/wso2/carbon-mediation/pull/1142

**Comment by Nirothipan** [comment]
Fix added in https://github.com/wso2/carbon-mediation/pull/1146

**Comment by Nirothipan** [comment]
Since the original PR is causing issues https://github.com/wso2/product-ei/issues/3360 we have reverted it and this is not fixed yet .
