### ISSUE TITLE
[Documentation] [Micro Integrator] The profile creator documentation does not specify the location of the zip file which is getting created

### ISSUE THREAD

**Issue by chanakaudaya** [wso2/product-ei#3327]
**Description:**
The current documentation page does not specify the location of the zip file which is created after running the profile-creator script. 

**Suggested Labels:**
documentation

**Comment by nilminiwso2** [comment]
Doc updated [1].
[1] https://docs.wso2.com/display/EI640/Working+with+the+Micro+Integrator
