### ISSUE TITLE
[Kerberos Authentication]jaas.conf file is read from non-existing folder

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3338]
**Description:**
Once it is trying to configure a Kerberos secured datasource in WSO2 EI, it provides the following exception. 
```
ERROR {org.wso2.carbon.ndatasource.core.DataSourceRepository} -  Error establishing data source connection: [Cloudera][ImpalaJDBCDriver](500164) Error initialized or created transport for authentication: java.io.IOException: C:\WSO2EI~1.0\bin\..\repository\conf\identity\jaas.conf (No such file or directory). {org.wso2.carbon.ndatasource.core.DataSourceRepository}
```

As per the issue it searches for jaas.conf file inside <EI_HOME>/repository/conf/identity folder which does not actually exist. 
Therefore this needs to be corrected to read the jaas.conf file from <EI_HOME>/conf/identity folder. 

**Suggested Labels:**
6.2.0/6.4.0
Priority/High
Severity/critical
Type/Bug

**Affected Product Version:**
WSO2 EI 6.2.0

**Comment by Nirothipan** [comment]
Hi @isuruuy429 ,

This is happening since the url of the data source is configured as **repository/conf/identity/jaas.conf**.

It need to be modified to **conf/identity/jaas.conf**. 

If this issue still persists, please share with us the relevant datasource.xml file.

Thanks
Nirothipan
