### ISSUE TITLE
[Tooling] Unable to add new case branch in switch mediator in developer studio design view

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3345]
**Description:**
Unable to add a new case branch after creating a CAPP with switch mediator in design view. If the user wants to add a new case branch only after he creates the CAPP, it's unable to add the branches when he tried to add in design view. If the user tried by adding a case in source view it's adding in design view. When you add the branch its removing the created branches. 

<img width="200" alt="Screen Shot 2019-03-14 at 3 26 13 PM" src="https://user-images.githubusercontent.com/40847371/54347787-b7c48500-466d-11e9-9061-49b8112542e8.png">

**Suggested Labels:**
EI Tooling
6.5.0

**Steps to reproduce:**
- Create a CAPP with switch mediator by adding 1 or more cases. 
- Try to add more case in design view by right click on the mediator and click on "Add/Remove Branches"

**Comment by dinuish94** [comment]
Issue not reproducible.
