### ISSUE TITLE
[Tooling] Duplicate the model won't duplicating everything in the original model

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3349]
**Description:**
Duplicate the model won't duplicating everything in the original model. Coping the model with missing sub model as weel as flow arrows also not appling correctly. 
<img width="500" alt="Screen Shot 2019-03-14 at 5 13 39 PM" src="https://user-images.githubusercontent.com/40847371/54355058-227dbc80-467e-11e9-9d85-07fd76483f64.png">

**Suggested Labels:**
EI Tooling
6.5.0
 
**Steps to reproduce:**
- Create a CAPP
- Right click on the created model and select Edit --> Duplicate

**Comment by dakshika** [comment]
we have removed this feature due to the user experience issue. Now users cannot duplicate
