### ISSUE TITLE
Getting Java errors when running the carbondump.sh command

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#335]
Check below stack trace:

sankav@asankav-ThinkPad-T540p:~/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT/bin$ sh carbondump.sh -carbonHome /home/asankav/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT -pid 26869

carbondump.sh##Generating the java memory dump...
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.PMap.main(PMap.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)

Dumping heap to /home/asankav/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT/carbondump/carbondump-2017-03-23_11-09-45/memoryinfo/java_heap_memory_dump.jmap ...
Heap dump file created
Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.FinalizerInfo.main(FinalizerInfo.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)

Error attaching to process: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.execute(LinuxDebuggerLocal.java:163)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach(LinuxDebuggerLocal.java:278)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:671)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:611)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.HeapSummary.main(HeapSummary.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.tools.jmap.JMap.runTool(JMap.java:201)
	at sun.tools.jmap.JMap.main(JMap.java:130)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$100(LinuxDebuggerLocal.java:62)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1AttachTask.doit(LinuxDebuggerLocal.java:269)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalWorkerThread.run(LinuxDebuggerLocal.java:138)

Usage:
    jmap [option] <pid>
        (to connect to running process)
    jmap [option] <executable <core>
        (to connect to a core file)
    jmap [option] [server_id@]<remote server IP or hostname>
        (to connect to remote debug server)

where <option> is one of:
    <none>               to print same info as Solaris pmap
    -heap                to print java heap summary
    -histo[:live]        to print histogram of java object heap; if the "live"
                         suboption is specified, only count live objects
    -clstats             to print class loader statistics
    -finalizerinfo       to print information on objects awaiting finalization
    -dump:<dump-options> to dump java heap in hprof binary format
                         dump-options:
                           live         dump only live objects; if not specified,
                                        all objects in the heap are dumped.
                           format=b     binary format
                           file=<file>  dump heap to <file>
                         Example: jmap -dump:live,format=b,file=heap.bin <pid>
    -F                   force. Use with -dump:<dump-options> <pid> or -histo
                         to force a heap dump or histogram when <pid> does not
                         respond. The "live" suboption is not supported
                         in this mode.
    -h | -help           to print this help message
    -J<flag>             to pass <flag> directly to the runtime system

carbondump.sh##Generating the thread dump...

carbondump.sh##Capturing OS information...
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)

carbondump.sh##Capturing the list of running task in the system...

carbondump.sh##Capturing OS Environment Variables...

carbondump.sh##Generating the checksums of all the files in the CARBON_HOME directory...
md5sum: /home/asankav/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT/repository/resources/reports/Activity: No such file or directory
md5sum: Search: No such file or directory
md5sum: Report.jrxml: No such file or directory

carbondump.sh##Copying log files...

carbondump.sh##Copying conf files...

carbondump.sh##Copying database...

carbondump.sh##Getting a directory listing...

carbondump.sh##Compressing the carbondump...
  adding: carbondump-2017-03-23_11-09-45/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/shared_object_mappings.txt (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/java_heap_memory_dump.jmap (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/objects_awaiting_finalization.txt (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/java_permgen_statistics.txt (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/java_heap_histogram.txt (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/memoryinfo/java_heap_summary.txt (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/thread_dump.txt (deflated 93%)
  adding: carbondump-2017-03-23_11-09-45/repository/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/database/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/database/WSO2CARBON_DB.lock.db (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/database/WSO2CARBON_DB.h2.db (deflated 92%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2-ei-trace.log (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/audit.log (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2carbon.log (deflated 85%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2carbon-trace-messages.log (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2-ei-service.log (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/patches.log (deflated 85%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/http_access_management_console_2017-03-23.log (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2carbon.log.2017-03-20 (deflated 86%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/wso2-ei-errors.log (deflated 78%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/http_access_management_console_2017-03-20.log (deflated 93%)
  adding: carbondump-2017-03-23_11-09-45/repository/logs/tm.out (deflated 95%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/multitenancy/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/multitenancy/usage-throttling-agent-config.xml (deflated 61%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/multitenancy/stratos.xml (deflated 61%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/multitenancy/cloud-services-desc.xml (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/multitenancy/multitenancy-packages.xml (deflated 77%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/logging-config.xml (deflated 66%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/bundle-config/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/mime.types (deflated 70%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/osgi-debug.options (deflated 71%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/launch.ini (deflated 73%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/tasks-config.xml (deflated 59%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/jmx.xml (deflated 50%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/mime.mappings (deflated 48%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/logging-bridge.properties (deflated 68%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/config-validation.xml (deflated 67%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/etc/carboncontext-osgi-services.properties (deflated 42%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/synapse-handlers.xml (deflated 42%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/data-bridge/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/data-bridge/data-agent-config.xml (deflated 74%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/registry.xml (deflated 74%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/datasources.properties (deflated 69%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tenant-mgt.xml (deflated 59%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/output-event-adapters.xml (deflated 80%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/nhttp.properties (deflated 48%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/datasources/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/datasources/master-datasources.xml (deflated 69%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/datasources/custom-datasources.xml (deflated 74%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/log4j.properties (deflated 71%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/event-broker.xml (deflated 73%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/email/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/email/email-admin-config.xml (deflated 46%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/Owasp.CsrfGuard.Carbon.properties (deflated 70%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/xss-patterns.properties (deflated 54%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/authenticators.xml (deflated 66%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/cipher-tool.properties (deflated 53%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/secret-conf.properties (deflated 69%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/cipher-text.properties (deflated 46%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/security/integrator-whitelist.properties (deflated 41%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/sec.policy (deflated 76%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/core.properties (deflated 8%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/scripts.conf (deflated 43%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/elevate.xml (deflated 47%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/stopwords.txt (deflated 43%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/lang/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/lang/stopwords_en.txt (deflated 45%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/synonyms.txt (deflated 46%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/schema.xml (deflated 74%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/currency.xml (deflated 63%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/spellings.txt (deflated 42%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/protwords.txt (deflated 46%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/registry-indexing/conf/solrconfig.xml (deflated 73%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/solr/solr.xml (deflated 51%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/synapse.properties (deflated 58%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/identity/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/identity/identity.xml (deflated 80%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/user-mgt.xml (deflated 80%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/context.xml (deflated 51%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/web.xml (deflated 85%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/carbon/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/carbon/WEB-INF/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/carbon/WEB-INF/web.xml (deflated 78%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/carbon/META-INF/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/carbon/META-INF/context.xml (deflated 47%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/catalina-server.xml (deflated 67%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/webapp-classloading-environments.xml (deflated 65%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/webapp-classloading.xml (deflated 47%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/tomcat/tomcat-users.xml (deflated 57%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/hl7.properties (deflated 39%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/access-log.properties (deflated 49%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/axis2_client.xml (deflated 79%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/axis2_pt.xml (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/axis2_blocking_client.xml (deflated 80%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/tenant-axis2.xml (deflated 80%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/axis2.xml (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/axis2/axis2_nhttp.xml (deflated 83%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/carbon.xml (deflated 70%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/passthru-http.properties (deflated 47%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/jndi.properties (deflated 46%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/rule-engine-config.xml (deflated 61%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/sample-server-wrapper.conf (deflated 68%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/README (deflated 61%)
  adding: carbondump-2017-03-23_11-09-45/repository/conf/event-processor.xml (deflated 76%)
  adding: carbondump-2017-03-23_11-09-45/directory_listing.txt (deflated 95%)
  adding: carbondump-2017-03-23_11-09-45/carbon_server_info.txt (deflated 32%)
  adding: carbondump-2017-03-23_11-09-45/checksum_values.txt (deflated 86%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/ (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_module_info.txt (deflated 85%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_open_ports.txt (deflated 88%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_installed_software_redhat_fedora.txt (stored 0%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_cpuinfo.txt (deflated 90%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_installed_software_unix_linux.txt (deflated 84%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_module_list.txt (deflated 73%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_running_tasks.txt (deflated 77%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_meminfo.txt (deflated 61%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_network_cards.txt (deflated 78%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_system_up_time.txt (deflated 48%)
  adding: carbondump-2017-03-23_11-09-45/osinfo/os_env_variables.txt (deflated 58%)

carbondump: /home/asankav/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT/carbondump-2017-03-23_11-09-45.zip

asankav@asankav-ThinkPad-T540p:~/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT/bin$

**Comment by milindaperera** [comment]
> sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the process

This caused due to new security policy added to Ubuntu, It can be solved by following instructions in [1]

@praneesha  let's add this instruction to the doc

[1] http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7050524

**Comment by praneesha** [comment]
Updated the follwoing docs.

[1] https://docs.wso2.com/display/ADMIN44x/Capturing+System+Data+in+Error+Situations
[2] https://docs.wso2.com/display/EI600/Product+Administration
[3] https://docs.wso2.com/display/EI600/Troubleshooting+the+Message+Broker+Profile
[4] https://docs.wso2.com/display/EI600/Troubleshooting+the+business+process+Profile

**Comment by milindaperera** [comment]
Not yet committed fix hence reopenning
