### ISSUE TITLE
Manipulation jar file at runtime

### ISSUE THREAD

**Issue by keremcankabadayi** [wso2/product-ei#3351]
**Description: I'm using Class Mediator as .jar file. Manupilations methods at runtime isn't option.**
I need to make some changes in my code at runtime but once wso2 up, there is no change at my runtime. It's using from cache previous .jar file that deployed when wso2 started up.

OS: Win10
DB: Postgresql

**Comment by nandika** [comment]
Your observation is correct for the current ei runtime. When a jar file is deployed to lib directory, when the server starts up, the jar file will be wrapped as an OSGi bundle and get deployed into the dropins directory. This OSGi bundle is used by the runtime.

Can you explain the use-case where you required the runtime manipulation of methods?

Regards
Nandika

**Comment by keremcankabadayi** [comment]
Hi again, I was trying to use class mediator for this. My issue about manipulating jar at runtime is that in production we cant interrupt for tiny changes. So, we need to change java codes inside .jar file. When it builds up, it should be overwrite at runtime without any reset or interruption. Hence, I changed my strategy to script mediator but this .jar issue can be improved.

Best regards,
Kerem.

**Comment by Tomas-Mrazek** [comment]
@nandika How about OSGi bundles, is it possible to add them at runtime?
