### ISSUE TITLE
Add connector for peoplesoft

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3355]
**Description:**

Oracle's PeopleSoft Human Capital Management enables you to architect a global foundation for HR data and improved business processes. PeopleSoft Human Capital Management delivers a robust set of best-in-class human resources functionality that enables you to increase productivity, accelerate business performance, and lower your cost of ownership. If needed we can get access to the relavant envirnments.

Deliverables
WSO2 ESB connector for PeopIe soft and the corresponding documentation.

References
[1] https://docs.oracle.com/cd/E52319_01/infoportal/opc.html

**Comment by lpastor74** [comment]
HI team 
wanted to check where we are with this WSO2 ESB connector for PeopIe soft. Have we built it?

**Comment by abeykoon** [comment]
Nope. Until we find account facility and Devs, this will be in icebox.
