### ISSUE TITLE
carbon_server_info.txt file inside carbondump.sh generated dump does not have product details

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#336]
Steps:
1. Generate carbon dump file using shell script carbondump.sh
2. Unzip the dump file and check the carbon_server_info.txt file

Issue:
Product name and product version variables haven't evaluated correctly

Product                 : ${product.name} v${product.version}
WSO2 Carbon Framework   : WSO2 Carbon Framework v4.4.14
Carbon Home             : /home/asankav/servers/releasetest/ei/wso2ei-6.1.0-SNAPSHOT
Operating System Info   : Linux asankav-ThinkPad-T540p 4.4.0-62-generic #83~14.04.1-Ubuntu SMP Wed Jan 18 18:10:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Java Home               : /usr/local/java/jdk1.8.0_45
Java Version            : "1.8.0_45"
Java VM                 : Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by milindaperera** [comment]
Fixed in #375
