### ISSUE TITLE
[Tooling] Other Project name autofilling not working

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3368]
**Description:**
![Screen Shot 2019-03-19 at 11.00.51 AM.png](https://images.zenhubusercontent.com/5c906993aa8dca0a81398552/6744ef73-aa00-4050-b7dd-147a167e9e18)

**Steps to reproduce:**
1. Click create New on welcome perspective
2. Select "Create registry resource Project" & and type project name
3. Only "Create Composite" field get filled with the text

**Comment by rosensilva** [comment]
fixed with https://github.com/wso2/devstudio-tooling-esb/pull/775
