### ISSUE TITLE
[Tooling] Payload Factory Argument Window title & body text shows as PayloadFactoryArgument

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3378]
**Description:**
1. add PayloadFactory mediator into the in- sequence 
2. click to add new argument 
3. window title and body needs to be changed

**Comment by prabushi** [comment]
Cannot be fixed as the name of the Class will be set as the title for the wizard [[1]](https://github.com/eclipse/eef/blob/master/plugins/org.eclipse.emf.eef.runtime/src/org/eclipse/emf/eef/runtime/ui/wizards/PropertiesEditionWizard.java#L100) from the EEF side.
