### ISSUE TITLE
[Tooling] Needs to add checkboxes for Proxy service transport  properties 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3379]
**Description:**
Needs to add checkboxes for Proxy service transport  properties. Currently it shows as a text field. we need to map those into checkboxes with all available transports
![Screen Shot 2019-03-19 at 2.17.54 PM.png](https://images.zenhubusercontent.com/5c906993aa8dca0a81398552/455af14d-9ab7-4ee1-8f53-366ae36a47d6)

**Comment by rosensilva** [comment]
We need to support custom transport types.
