### ISSUE TITLE
[Tooling] Available templates are not get listed on Call template mediator

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3381]
**Description:**
Available templates are not get listed on Call template mediator

**Steps to reproduce**
1. Add call template mediator
2. Create new sequence template 
3. Go back to call mediator properties
4. select "Available templates" 
5. Its empty

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/746
