### ISSUE TITLE
[Tooling] Loop back mediator place after drop mediator will create zombi element

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3382]
**Description:**
Loop back mediator place after drop mediator will create zombi element

**Steps to reproduce:**
1. add few mediators to the insequence
2. add drop mediator
3. try to add loopback mediator after that

![Screen Shot 2019-03-19 at 5.23.46 PM.png](https://images.zenhubusercontent.com/5c906993aa8dca0a81398552/f81417a4-ae3b-42ee-87a1-c6c2eaf2eb4f)

**Comment by rosensilva** [comment]
This will only reproduce when the call mediator is empty

**Comment by dakshika** [comment]
closing since the normal user wont try to add this without mapping endpoint to the call mediator
