### ISSUE TITLE
Evaluating the possibilities of installing BPMN features of BPS profile into wso2 EI integrator profile

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/product-ei#3385]
**Description:**
This issue is created for evaluating the possibility of installing BPMN features of BPS into the wso2 EI. If we can achieve this, we can use local transport to communicate between BPMN and EI since there is a single JVM with EI and BPMN. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
We have decided not to implement this feature after the evaluation. Hence I am resolving the issue.
