### ISSUE TITLE
[Documentation] Add content on how we can migrate EI analytics data.

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-ei#3390]
**Description:**
Document how we can migrate EI analytics data from 6.3.0 release to later releases (i.e., 6.4.0 onwards). 

This should cover how you to migrate analytics data based on DAS to SP

**Comment by RukshiW** [comment]
Not started yet. I will be working on this. Commenting on this issue because we are currently unable to assign it to me.

**Comment by sajithshn** [comment]
We need to have a migration client to proceed with this.

**Comment by RukshiW** [comment]
Added migration instructions for the Analytics profile [1]. Please review.

[1] https://docs.wso2.com/display/EI640/Upgrading+from+WSO2+EI+6.3.0#UpgradingfromWSO2EI6.3.0-Analyticsprofile
