### ISSUE TITLE
[Tooling] Label has to fix on sequence mediator 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3391]
**Description:**
Label has to fix on sequence mediator 

![Screen Shot 2019-03-21 at 4.46.10 PM.png](https://images.zenhubusercontent.com/5c906993aa8dca0a81398552/ae6854c7-83eb-423a-b887-408ab43bbc86)

**Steps to reproduce:**
1. Add sequence to the proxy or api
2. double click to view properties
3. need to fix dynamic reference key

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/736
