### ISSUE TITLE
[EI 6.1][Analytics]Total Request count is not static

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#341]
[Standalone pack]

Invoke a proxy when statistics are enabled. 
Count will be incremented by 1.
But stay for sometime and refresh the page and view the request count again for the particular proxy invocation. It will be decremented by 1. 
Again stay for sometimes and view. Then it will show incremented value.

Check the time and request count in the screenshot.
![screenshot from 2017-03-23 14-04-35](https://cloud.githubusercontent.com/assets/12966170/24238930/f072e132-0fd1-11e7-97dc-24f773d4fa0d.png)
![screenshot from 2017-03-23 14-04-05](https://cloud.githubusercontent.com/assets/12966170/24238932/f075269a-0fd1-11e7-8a76-0c7bd1f1c7e9.png)
![screenshot from 2017-03-23 14-03-10](https://cloud.githubusercontent.com/assets/12966170/24238931/f074c36c-0fd1-11e7-9aa5-96698e696a49.png)
![screenshot from 2017-03-23 14-02-20](https://cloud.githubusercontent.com/assets/12966170/24238933/f0785266-0fd1-11e7-8697-47a6b8268a05.png)

**Comment by sashikamw** [comment]
Observed this inconsistency in the Alpha pack (cluster) as well. The message counts shown in the 'Data Explorer' for specific tables are correct but the message counts appearing in the analytics dashboard change time to time. ( Counts displayed for last 30 days and last year was incorrect)

**Comment by nandika** [comment]
This is due to the intermediate results while the analytics scripts being run.

**Comment by sashikamw** [comment]
Verified this in the cluster setup. Final result shown in the cluster is incorrect. I have invoked the proxy 5 times, so the message count should be 5. But when we search the message count for the year it will displayed as 10. which is incorrect. 

![proxydetails](https://cloud.githubusercontent.com/assets/14962228/24494072/9a62e152-154e-11e7-83c2-8ca8108c7fea.png)


![lastyearmessagecount](https://cloud.githubusercontent.com/assets/14962228/24494055/8b677186-154e-11e7-9c6f-d8b23cf271d4.png)

**Comment by ushanib** [comment]
![screenshot from 2017-03-30 18-37-16](https://cloud.githubusercontent.com/assets/12966170/24505560/efd62bfc-1577-11e7-8f8a-fe1dde682bae.png)
![screenshot from 2017-03-30 18-37-14](https://cloud.githubusercontent.com/assets/12966170/24505561/efdb4a4c-1577-11e7-9537-c5064cd09fb4.png)
![screenshot from 2017-03-30 18-36-54](https://cloud.githubusercontent.com/assets/12966170/24505562/efe072d8-1577-11e7-823d-1ade86ea54df.png)
![screenshot from 2017-03-30 18-36-53](https://cloud.githubusercontent.com/assets/12966170/24505563/efe37cd0-1577-11e7-9b2d-239484a5f5d4.png)


This is reproducible. Stayed for 30 min still its reproducible.

**Comment by AnuGayan** [comment]
This one is fixed in EI 6.4.0
