### ISSUE TITLE
[Tooling] Drop mediator won't get add to existing flow from design view

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3410]
**Description:**
When User tries to add a drop mediator to the existing flow from design view by drag and drop the Drop mediator from the palette, it won't get added. Only the warning message displayed to the user.  Should be able to drag and drop the drop mediator to the design. This is working when the user tried to add the drop mediator from the source view. 

<img width="300" alt="Screen Shot 2019-03-25 at 3 06 43 PM" src="https://user-images.githubusercontent.com/40847371/54972363-45c73680-4fb1-11e9-8f87-b12b33bdd4a8.png">

**Suggested Labels:**
EI Tooling

**Steps to reproduce:**
Tried sample - https://docs.wso2.com/display/EI640/Drop+Mediator
- Drag and drop the Drop mediator to the else part

**Comment by dakshika** [comment]
this is the expected behavior. we can't add drop mediator between a mediation flow. normally drop will be the end of the flow
