### ISSUE TITLE
[Tooling] Drop mediator description wont get add if the user add from properties form in design view

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3411]
**Description:**
When the user adds a description to the drop mediator from property form in design view it won't get added. An error message displayed and after click "Ok" drop mediator disappear.

<img width="400" alt="Screen Shot 2019-03-25 at 3 17 51 PM" src="https://user-images.githubusercontent.com/40847371/54972639-79ef2700-4fb2-11e9-8052-e70c3c2cf59b.png">

**Expected Output**
The description should be added to the drop mediator and set in source view.

**Suggested Labels:**
EI Tooling
6.5.0

**Steps to reproduce:**
Tried sample - https://docs.wso2.com/display/EI640/Drop+Mediator
- Click on the drop mediator and add a description from the properties form.

**Comment by dakshika** [comment]
this is tried and seems working. Can you double check
