### ISSUE TITLE
[Doc] WSO2 EI documentation Sample running command need to be updated

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#342]
Sample starting command need to be updated on documentation

Shows following entries when search for "wso2esb-samples" term and those should be changed to "wso2ei-samples.sh"

https://docs.wso2.com/dosearchsite.action?queryString=wso2esb-samples&startIndex=0&where=EI600

**Comment by praneesha** [comment]
Did a search and replace using the tool, which is mentioned in the email thread in [1].

[1] Search and Replace Plugin for Confluence
