### ISSUE TITLE
[Tooling] Simplify developer studio dashboard 

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3421]
The current developer studio dashboard overly populated with artifacts that we can create. Can we simplify it so that we will just promote the artifacts that are mandatory for integration developers? 

<img width="672" alt="Screen Shot 2019-03-26 at 2 44 24 PM" src="https://user-images.githubusercontent.com/574041/55035865-42927180-4fd6-11e9-9b98-cde8eb8197bf.png">

**Comment by dakshika** [comment]
@kasun04 We are planning to remove this view, since we have HTML based dashboard view. Shall we close this
