### ISSUE TITLE
[Tooling] Proxy service UI : Make http the default transport and reorder them according to the usage

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3422]
<img width="502" alt="Screen Shot 2019-03-26 at 2 56 08 PM" src="https://user-images.githubusercontent.com/574041/55036355-9d789880-4fd7-11e9-9186-4c6e2cd3ee2a.png">

**Comment by dakshika** [comment]
@isudana Can you suggest the order

**Comment by isudana** [comment]
order should be,

http (selected by default)
https (selected by default)
jms
vfs
local
mailto
fix
hl7

**Comment by dakshika** [comment]
partially fixed with the order

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/812
