### ISSUE TITLE
Proxy Services PublishWSDL properties UX issues

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3431]
If wsdl type is INLINE, 
we need a text area to put the wsdl, currently, we have a text box there. 

If wsdl type is REGISTY_KEY,
wsdl key should appear just after the wsdl type dropbox (not after wsdl resources box).

Need to update labels 
Wsdl -> WSDL
WsdlURL -> WSDL URL
WSDL Type -> WSDL Type
Wsdl Key -> WSDL Key
WsdlXML -> WSDL XML
WsdlEndpoint -> WSDL Endpoint

**Comment by dinuish94** [comment]
Fixed in [#766](https://github.com/wso2/devstudio-tooling-esb/pull/766)
