### ISSUE TITLE
[Tooling] Add key/value of log properties in property view 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3438]
**Description:**

It is better if we display key and value of log properties in the table. Current icon is not informative. 

![image](https://user-images.githubusercontent.com/4967046/55147787-0a716700-516d-11e9-9d3d-3f653ad49790.png)

**Comment by rosensilva** [comment]
Assigned  to Praveen Nadarajah

**Comment by praveennadarajah** [comment]
This has been fixed. Please find the PR below
https://github.com/wso2/devstudio-tooling-esb/pull/786/files
