### ISSUE TITLE
[Tooling] Remove 'Open Dashboard ' menu form the developer studio menu bar

### ISSUE THREAD

**Issue by rosensilva** [wso2/product-ei#3439]
**Description:**

Latest Developer studio getting started page contains all the required items in the open dashboard.

![Screenshot from 2019 03 28 15 22 56](https://user-images.githubusercontent.com/13344872/55148062-89669f80-516d-11e9-817e-69838b3b1477.png)

**Comment by dakshika** [comment]
this is fixed in latest master
