### ISSUE TITLE
Correlate logs during timeouts

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-ei#3442]
**Description:**
There is a requirement to correlate logs printed during a timeout. Therefore for this we need to add the correlation id to the message context which is now created and added when correlation logs are enabled. correlation id needed to be added to the logs printed.

**Affected Product Version:**
apim 2.1, synapse 2.1.7-wso2v10

**Comment by sajithshn** [comment]
Closing the issues as the fixes are merged
