### ISSUE TITLE
 -Desb.debug=true argument doesn't work for windows

### ISSUE THREAD

**Issue by waqasalirazzaq** [wso2/product-ei#3446]
**Description:**
As per [documentation](https://docs.wso2.com/display/EI640/Debugging+Mediation)  `-Desb.debug=true` command line argument should be used to enable the mediation debugging while EI startup. 
But it doesn't seem to work unless explicitly add the argument in the integrator.bat file under `set CMD_LINE_ARGS=` section.
Actually it doesn't stop for debug connection as mentioned in the documentation. Seems like argument isnot handled in the bat file.

Can you guys please check? 

**Suggested Labels:**
wso2ei-6.4.0

**Suggested Assignees:**

**Affected Product Version:**
wso2ei-6.4.0
**OS, DB, other environment details and versions:**    
H2
**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
I have followed [documentation](https://docs.wso2.com/display/EI640/Debugging+Mediation)  on Windows 10 64 bit machine. The debug parameters are working when `-Desb.debug=true` parameter passed through the command line while starting the server `integrator.bat -Desb.debug=true`. Also, the debugger is working on Windows machine with the developer studio 6.4.0
