### ISSUE TITLE
[Tooling] XML open window is align with the palette window

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3450]
**Description:**
If the user opens a created xml, it's open in the incorrect position. Better if we can align its name with the view. 

<img width="200" alt="Screen Shot 2019-03-28 at 6 41 40 PM" src="https://user-images.githubusercontent.com/40847371/55209246-9768fe80-5207-11e9-9967-198ea821f0c6.png">

**Suggested Labels:**
EI Tooling
Improvment

**Comment by dakshika** [comment]
this is not a bug. its a expected behavior
