### ISSUE TITLE
[Tooling] Resources save in paths are empty

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3451]
**Description:**
If a user tries to save the resource in a different path, it's not showing the path list.

<img width="500" alt="Screen Shot 2019-03-29 at 9 40 59 AM" src="https://user-images.githubusercontent.com/40847371/55209380-3e4d9a80-5208-11e9-9af4-7d839d1f71f6.png">
  
**Suggested Labels:**
EI Tooling

**Steps to reproduce:**
- Right click on the any ESB project synapse config resource
- Click "New" and select the resource that you want to create
- Select Create new option and Click "Next"
- Add a name and click on Browse button in "Save in" option.
- Click on any ESB project to select a path

**Comment by dakshika** [comment]
this will automatically save in the right position. So no need to select the path. hence closing this. 

this needs to improve with some changes. so creating another issue with relevant suggestions 

https://github.com/wso2/product-ei/issues/3704
