### ISSUE TITLE
Response body is not received when call mediator is used in blocking mode

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#3469]
**Description:**
I have a Proxy which uses a blocking call mediator to call an HTTP endpoint. Eventhough the endpoint responds with a payload, I only get the status code not the body. 

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="ConflictEndpointProxy"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <log level="full"/>
         <call blocking="true">
            <endpoint>
               <http method="GET"
                     uri-template="http://www.mocky.io/v2/5c9ddf51330000b12c3f253a"/>
            </endpoint>
         </call>
         <loopback/>
      </inSequence>
      <outSequence>
         <log level="custom">
            <property name="outsequence" value="OutSequence"/>
         </log>
         <send/>
      </outSequence>
      <faultSequence>
         <log level="custom">
            <property name="faultsequence" value="FaultSequence"/>
         </log>
      </faultSequence>
   </target>
   <description/>
</proxy>
                                
```

**Comment by Vathsan** [comment]
As we are sending a GET request, NO_ENTITY_BODY property should be set if a user wants to generate a response from the ESB to a request without an entity body. Also we need to set the ContentType and messageType properties of the incoming request as well. To get the response, the above proxy should be modified as shown below,
```
<inSequence>
         <log level="full"/>
         <property action="remove" name="NO_ENTITY_BODY" scope="axis2"/>
         <property name="ContentType" scope="axis2" value="application/json"/>
         <property name="messageType" scope="axis2" value="application/json"/>
         <call blocking="true">
            <endpoint>
               <http method="GET"
                     uri-template="http://www.mocky.io/v2/5c9ddf51330000b12c3f253a"/>
            </endpoint>
         </call>
        <loopback/>
</inSequence>
```

**Comment by PetteriPertola** [comment]
Hi @Vathsan 
I am facing this exact issue, and your suggested solution does not work on **WSO2 Integrator version 6.6.0**
I have exactly the same configuration as you have above, with the addition of a log mediator after the blocking call. I do not see the response body:

```
<property name="RESPONSE" scope="default" type="STRING" value="true"/>
<log level="full">
    <property name="response-log" value="Received response"/>
    <property expression="$body" name="response-body"/>
    <property expression="json-eval($)" name="json-eval-body"/>
</log>
```

INFO {org.apache.synapse.mediators.builtin.LogMediator} - To: http://my-api/order-status, WSAction: urn:mediate, SOAPAction: urn:mediate, MessageID: ID:414d51204343494153303131202020209ca4175f58ac422e, Direction: response, response-log = Received response, response-body = <soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><jsonObject/></soapenv:Body>, json-eval-body = {}, Payload: {}

However if I do the same request via Postman, there definitely is a JSON response:
{
   "order_status": "NOT_FOUND"
}

There must be some other solution to this?

**Comment by Vathsan** [comment]
Hi @PetteriPertola,

Could you please share your synapse configuration and the wire logs?

**Comment by PetteriPertola** [comment]
Hi, I resolved it by removing the OUT_ONLY property that i had in a previous version of the flow. You can ignore this.
