### ISSUE TITLE
The link redirects to an older version of doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3472]
**Description:**
Document: https://docs.wso2.com/display/EI6xx/Aggregate+Mediator
Following links redirect to an older version (6.0.0) of the docs instead of redirecting to 6xx in the Sample section. 

Sample 62: Routing a Message to a Dynamic List of Recipients and Aggregating Responses
Sample 400: Message Splitting and Aggregating the Responses
Sample 751: Message Split Aggregate Using Templates

**Comment by nilminiwso2** [comment]
Fixed.
All mediator docs will be checked through [1].

[1] #3509
