### ISSUE TITLE
Make the resize line visible between editor and property panes

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#3478]
**Description:**
Currently the resize line is not visible between the property pane and the editor window. Make this line visible so that property windows can be adjusted easily
**Suggested Labels:**
![propertypaneseperator](https://user-images.githubusercontent.com/2908631/55234708-bbe9c880-5251-11e9-82e7-269bb97b9a64.png)

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
this is fixed in latest master
