### ISSUE TITLE
Provide the correct version of the link to redirect

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3493]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Call+Mediator

Sample 500: Call Mediator for Non-Blocking Service Invocation link redirects to an older version of the doc.

**Comment by nilminiwso2** [comment]
Fixed. 
Looking into broken links in other mediator docs through [1].
[1] https://github.com/wso2/product-ei/issues/3509
