### ISSUE TITLE
[EI][Tooling] Sample 600 : Simple Message Transformation - Rule Mediator for Message Transformation

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3495]
**Description:**

Use doc sample:  https://docs.wso2.com/display/EI6xx/Sample+600+%3A+Simple+Message+Transformation+-+Rule+Mediator+for+Message+Transformation

**Steps to Reproduce**
1. Create a main.xml inside the sequence folder.

copy paste the content
`<in>
 
            <rule xmlns="http://wso2.org/carbon/rules">
                <source>soapBody</source>
                <target action="replace" xmlns:m0="http://services.samples" resultXpath="//m0:symbol"
                        xpath="//m0:getQuote/m0:request/m0:symbol">soapBody</target>
                <ruleSet>
                    <properties/>
                    <rule resourceType="regular" sourceType="inline">
                        <![CDATA[ package SimpleRoutingRules;
 
                        rule InvokeIBM
                        when
                        symbol: String()
                        eval( symbol.equals("MSFT") || symbol.equals("SUN") )
                        then
                        update(drools.getWorkingMemory().getFactHandle(symbol),"IBM");
                        end
                        ]]>
                    </rule>
                </ruleSet>
                <input namespace="http://services.samples" wrapperElementName="getQuote">
                    <fact xmlns:m0="http://services.samples" elementName="symbol" namespace="http://services.samples"
                          type="java.lang.String" xpath="//m0:getQuote/m0:request/m0:symbol/child::text()"/>
                </input>
                <output namespace="http://services.samples" wrapperElementName="getQuote">
                    <fact elementName="symbol" namespace="http://services.samples" type="java.lang.String"/>
                </output>
            </rule>
            <send>
                <endpoint>
                    <address uri="http://localhost:9000/services/SimpleStockQuoteService"/>
                </endpoint>
            </send>
 
        </in>
        <out>
            <send/>
        </out>`

2. Save the file
3. switch to design view
4. switch to source again. Content has changed with some additional namespaces

`
<in>
        <brs:rule xmlns:brs="http://wso2.org/carbon/rules">
            <brs:source>soapBody</brs:source>
            <brs:target action="replace" resultXpath="//m0:symbol" xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol">soapBody</brs:target>
            <brs:ruleSet>
                <brs:properties/>
                <brs:rule resourceType="regular" sourceType="inline"><![CDATA[
                         package SimpleRoutingRules;
 
                        rule InvokeIBM
                        when
                        symbol: String()
                        eval( symbol.equals("MSFT") || symbol.equals("SUN") )
                        then
                        update(drools.getWorkingMemory().getFactHandle(symbol),"IBM");
                        end
                        
                    ]]></brs:rule>
            </brs:ruleSet>
            <brs:input namespace="http://services.samples" wrapperElementName="getQuote">
                <brs:fact elementName="symbol" namespace="http://services.samples" type="java.lang.String" xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol/child::text()"/>
            </brs:input>
            <brs:output namespace="http://services.samples" wrapperElementName="getQuote">
                <brs:fact elementName="symbol" namespace="http://services.samples" type="java.lang.String"/>
            </brs:output>
        </brs:rule>
        <send>
            <endpoint>
                <address uri="http://localhost:9000/services/SimpleStockQuoteService"/>
            </endpoint>
        </send>
    </in>
    <out>
        <send/>
    </out>`

**Comment by dinuish94** [comment]
The namespaces are required for the rule mediator.
