### ISSUE TITLE
Working with Analytics - Grammar

### ISSUE THREAD

**Issue by Maninda** [wso2/product-ei#3497]
**Description:**
"This Analytics profile is, by default, configured to monitor statistics..." can be changed as "This Analytics profile, by default, is configured to monitor statistics"

**Suggested Labels:**
Type/Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithshn** [comment]
Fixed in 6xx
