### ISSUE TITLE
[Critical] Cannot Upload webapps for tenant

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#35]
**Steps**

1. Login as a tenant admin.
2. Try to upload a .war.

**Issue**: CSRF filter blocks the file upload process. Following error observed in BE. The browser directs to a forbidden error page.

> [2017-01-25 04:22:28,185]  WARN - JavaLogger potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.112, method:POST, uri:/t/test.com/fileupload/webapp, error:required token is missing from the request)

**Comment by madhawa-gunasekara** [comment]
will fix it, Thanks for reporting

**Comment by chalitha87** [comment]
When we try to upload web app in BPS **super tenant** mode, Same issue can be seen in front-end and backend.

**Error**
Front-end  shows 403 forbidden page
Backend throws following warning
`[2017-01-25 15:24:01,702]  WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.5.45, method:POST, uri:/fileupload/webapp, error:required token is missing from the request)
`

**Comment by madhawa-gunasekara** [comment]
Fixed this issue. removed the webapp uploading feature in BPS.
