### ISSUE TITLE
6xx space contains links pointing to older space

### ISSUE THREAD

**Issue by tharinduwijewardane** [wso2/product-ei#3503]
https://docs.wso2.com/display/EI6xx/Sample+906%3A+Inbound+Endpoint+MQTT+Protocol+Sample page contains followings 

>Start the Broker profile of WSO2 EI. For instructions, see Starting the Message Broker profile.
>Start the ESB profile of WSO2 EI. For instructions, see Starting the ESB Profile.

which contains following links to the older space 6.2.0.

https://docs.wso2.com/display/EI620/Running+the+Product#RunningtheProduct-EI_BrokerStartingtheMessageBrokerprofile 
https://docs.wso2.com/display/EI620/Running+the+Product#RunningtheProduct-StartingtheESBprofile 

Further, 6xx space does not have such sections.

**Comment by Ibaqu** [comment]
Updated links 'see Starting the Message Broker Profile' and 'see Starting the ESB Profile' for both EI 6.x.x and 6.5.0
