### ISSUE TITLE
Correct the type of double quotes

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3506]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Call+Template+Mediator

When the provided the template is pasted, it does not allow to save the sequence. The double quotes in the doc is not accepted by the tooling. Please see the difference below. 

In the doc: 
`<property name=”GREETING_MESSAGE” expression=”$func:message” />`

Should be corrected as: 
 `<property expression="$func:message" name="GREETING_MESSAGE"/>
`

**Comment by Ibaqu** [comment]
Corrected for both EI 6.5.0 and E.I 6.x.x
