### ISSUE TITLE
Redirect to the correct version of the sample

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3509]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Callout+Mediator

Sample 430: Callout Mediator for Synchronous Service Invocation .redirects to an older version.

**Comment by nilminiwso2** [comment]
Fixed the 'Call Mediator' page.
Verifying links in other Mediator pages.

**Comment by nilminiwso2** [comment]
Fixed all links to samples from Mediators.
