### ISSUE TITLE
[Doc] Redirecting to older documentation for Identity server

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#3512]
**Description:**

**Doc :** https://docs.wso2.com/display/EI6xx/Applying+Security+to+an+API
"Getting OAuth Token" : (2) On the Main tab, click Add under Service Providers, and then add a service provider .

Redirects to older documentation for identity server

Must redirect to : https://docs.wso2.com/display/IS570/Adding+and+Configuring+a+Service+Provider

**Comment by nilminiwso2** [comment]
Fixed
