### ISSUE TITLE
WSO2 Developer Studio link does not work

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3513]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Class+Mediator
WSO2 Developer Studio link keeps hanging. (http://docs.wso2.org/developer-studio)

It should be corrected as below. 
https://wso2.com/products/developer-studio/

**Comment by nilminiwso2** [comment]
As Developer Studio is no longer a product, and since we have WSO2 EI Tooling in place, I have pointed the link to the Tooling installation page [1].

[1] https://docs.wso2.com/display/EI6xx/Class+Mediator

Please reopen if anything is out of place.
