### ISSUE TITLE
[Doc] Sample not working for 'Configuring non-HTTP endpoints'

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#3514]
**Description:**
Sample not working for "Configuring non-HTTP endpoints"

**Doc :** https://docs.wso2.com/display/EI6xx/Configuring+Specific+Use+Cases

**Suggested tags:** 
Type/Doc 6.5.0

**Comment by GDLMadushanka** [comment]
Changed the 6xx docs by escaping & => &amp;
