### ISSUE TITLE
Wrong proxy configuration in Sample 150, 152, 155

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#3517]
**Description:**
inSequence tag is missing from the proxy configurations of [Sample 150](https://docs.wso2.com/display/EI6xx/Sample+150%3A+Introduction+to+Proxy+Services),  [Sample 152](https://docs.wso2.com/display/EI6xx/Sample+152%3A+Switching+Transports+and+Message+Format+from+SOAP+to+REST+POX) and [Sample 155](https://docs.wso2.com/display/EI6xx/Sample+155%3A+Dual+Channel+Invocation+on+Both+Client+Side+and+Server+Side+of+Synapse+with+Proxy+Services)

**Comment by RidmiR** [comment]
Adding to this issue it better to update the document by describing how the file path getting set in xml WSDL. It confuses for a fresh user who is trying to use this example from where this "file" getting refer.
  
<publishWSDL uri="file:samples/service-bus/resources/proxy/sample_proxy_1.wsdl"/>

**Comment by nilminiwso2** [comment]
As discussed, will leave the sample docs unchanged for this EI version.

**Reason**: The docs currently carry the entire sample.xml file. This contains all the synapse artifacts included in the sample. When the sample is built, the missing tags are automatically added. Further, the sample works fine without any errors.

However, if a user tries to read the synapse config that is given in the doc (which is taken from the sample.xml file) and copy it to over to the product, it will not work. Although this is a drawback, the synapse configs given in the docs are not intended for this purpose, as it is shows the entire sample.xml file and not the individual artifacts separately.
