### ISSUE TITLE
Error is throwing when defining a sequence with a session mediator

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-ei#3519]
**Description:**
In[ Sample 54](https://docs.wso2.com/display/EI6xx/Sample+54%3A+Session+Affinity+Load+Balancing+between+Three+Endpoints) and [Sample 55](https://docs.wso2.com/display/EI6xx/Sample+55%3A+Session+Affinity+Load+Balancing+between+Failover+Endpoints) following error is throwing 

`Invalid mediator <loadbalance algorithm="org.apache.synapse.endpoints.algorithms.RoundRobin"/>`

**Comment by prabushi** [comment]
Sample 54 is working fine without any errors. However, a failover endpoint inside a failover endpoint in Sample 55 is not getting persisted at the moment.
