### ISSUE TITLE
[Tooling] Cannot Save Inline Ruby Script in Dev Studio

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#3527]
**Description:**
Following the doc [1], when defining a script mediator with ruby script and switch to source view, the script definition is marked as erroneous. It says 'Exception initializing inline script'.

![5](https://user-images.githubusercontent.com/8208020/55245580-6caf9200-5269-11e9-8fcd-9f380d42b2e3.png)

When switching pack to design view, tooling totally hangs. 

In the design view, selecting 'rb' as the script language itself is very slow, compared to selecting other languages.

[1] https://docs.wso2.com/display/EI640/Sample+354%3A+Using+Inline+Ruby+Scripts+for+Mediation

**Comment by dakshika** [comment]
Shall we bundle jruby-complete-1.3.0.wso2v1.jar this

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/wso2-synapse/commit/1999e7f323bc4a358d9054861b7d4fc31acae34e and https://github.com/wso2/devstudio-tooling-esb/pull/997.
