### ISSUE TITLE
[Doc] Setting up WSO2 EI and ActiveMQ old link

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#3528]
**Description:**
Setting up WSO2 EI and ActiveMQ links to the old documentation

Doc : JMS Synchronous Invocations : Quad Channel JMS-to-JMS : https://docs.wso2.com/display/EI6xx/JMS+Synchronous+Invocations+%3A+Quad+Channel+JMS-to-JMS

Suggested tags : Type/Docs 6.5.0

**Comment by nilminiwso2** [comment]
Fixed in the EI 6.4.0 and EI 6.5.0.
