### ISSUE TITLE
Improve clarity on startup log message when use start-all.sh script

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#353]
When checking the startup logs, Observed following concerns 
1. It has printed same details for each product. ex. Java Home details
2. Log messages of all product profiles has printed without any order, as a result it will be hard to troubleshoot startup errors etc
3. Mgt console UI list should be listed together so users have an idea where to start.

Suggestion:
Though we start servers parallel, print log messages sequentially

**Comment by nandika** [comment]
This script will be removed

**Comment by nandika** [comment]
https://github.com/wso2/product-ei/pull/367
