### ISSUE TITLE
Redirect to the correct versions of doc

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3530]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/DBLookup+Mediator#43863dca496e4451b8499cbda00015d4

Please redirect following sample docs to the 6xx versions. 

- Sample 360: Introduction to DBLookup Mediator
- Sample 362: DBReport and DBLookup Mediators Together
- Sample 363: Reusable Database Connection Pools

**Comment by nilminiwso2** [comment]
Fixed.
All mediator docs will be checked through [1].

[1] #3509
