### ISSUE TITLE
[Tooling] When saving json-eval expressions are giving errors in tooling.

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#3531]
**Description:**
When saving json-eval expressions are giving errors in tooling.

**Steps to reproduce:**
1) Add the following configuration in a sequence and try to save.
` <payloadFactory media-type="xml">
          <format>
              <Information xmlns="">
                  <Name>$1</Name>
                  <Last>$2</Last>
                  <High>$3</High>
                  <Low>$4</Low>
              </Information>
          </format>
          <args>
              <arg evaluator="json" expression="$.name"/>
              <arg evaluator="json" expression="$.last"/>
              <arg evaluator="json" expression="$.low"/>
              <arg evaluator="json" expression="$.high"/>
          </args>
      </payloadFactory>`
2) 
![Selection_005](https://user-images.githubusercontent.com/8251118/55246382-1fccbb00-526b-11e9-9569-3ce89040db60.png)

**Comment by sajithaliyanage** [comment]
Same error got when running the **Example 2: JSON** of PayloadFactory Mediator. 

```
<payloadFactory media-type="json">
            <format>
                {
    "coordinates": null,
    "created_at": "Fri Jun 24 17:43:26 +0000 2011",
    "truncated": false,
    "favorited": false,
    "id_str": "$1",
    "entities": {
        "urls": [
 
        ],
        "hashtags": [
            {
                "text": "$2",
                "indices": [
                    35,
                    45
                ]
            }
        ],
        "user_mentions": [
 
        ]
    },
    "in_reply_to_user_id_str": null,
    "contributors": null,
    "text": "$3",
    "retweet_count": 0,
    "id": "##",
    "in_reply_to_status_id_str": null,
    "geo": null,
    "retweeted": false,
    "in_reply_to_user_id": null,
 
    "source": "&lt;a
href=\"http://sites.google.com/site/yorufukurou/\"
rel=\"nofollow\"&gt;YoruFukurou&lt;/a&gt;",
    "in_reply_to_screen_name": null,
    "user": {
        "id_str": "##",
        "id": "##"
    },
    "place": null,
    "in_reply_to_status_id": null
}
            </format>
            <args>
               <arg expression="$.entities.hashtags[0].text" evaluator="json"/>
               <arg expression="//entities/hashtags/text"/>
               <arg expression="//user/id"/>
               <arg expression="//user/id_str"/>
               <arg expression="$.user.id" evaluator="json"/>
               <arg expression="$.user.id_str" evaluator="json"/>
            </args>
</payloadFactory>
