### ISSUE TITLE
[EI][Doc] Sample 360 has Mediation after a Send Mediator

### ISSUE THREAD

**Issue by ThishaniLucas** [wso2/product-ei#3532]
**Description:**
In the sample 360 [1], there is drop mediator after the send mediator. It is not recommended to have any mediators after the send mediator and Dev studio tooling will not allow having any mediator after the send mediator. This needs to be fixed in the doc as well as in the product.

```
<sequence name="myFaultHandler">
        <makefault>
            <code value="tns:Receiver" xmlns:tns="http://www.w3.org/2003/05/soap-envelope"/>
            <reason expression="get-property('ERROR_MESSAGE')"/>
        </makefault>
 
        <property name="RESPONSE" value="true"/>
        <header name="To" expression="get-property('ReplyTo')"/>
        <send/>
        <drop/>
    </sequence>
```

[1] https://docs.wso2.com/display/EI640/Sample+360%3A+Introduction+to+DBLookup+Mediator

**Comment by ThishaniLucas** [comment]
Same issue -
[1] https://docs.wso2.com/display/EI640/Sample+363%3A+Reusable+Database+Connection+Pools

**Comment by Ibaqu** [comment]
The document paths need to be updated. It is still using `<ESB_HOME>` paths instead of `<EI_HOME>`

`<ESB_HOME>/repository/samples` needs to be changed to `<EI_HOME>/samples/service-bus`

**Comment by Ibaqu** [comment]
Removed <drop/> after <send/> for sample [1]
Link to sample in product (synapse_sample_360.xml) has not been changed. 

[1] https://docs.wso2.com/display/EI640/Sample+360%3A+Introduction+to+DBLookup+Mediator
