### ISSUE TITLE
[Doc] Working with Sequences via Tooling

### ISSUE THREAD

**Issue by Nipunich** [wso2/product-ei#3533]
**Description:**

The steps given on creating a new sequence, importing a sequence are related to older EI Tooling versions. (eg. Open Dashboard etc. which is now not mandatory)
It's required to update the doc with new steps.

**Comment by nilminiwso2** [comment]
These updates should be done in all pages. 
In progress.

**Comment by nilminiwso2** [comment]
Updated all the ESB pages.
