### ISSUE TITLE
Error when trying out sample 57 source code

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#3536]
**Description:**
Sample 57 produces the error shown in the attached image
![sample57](https://user-images.githubusercontent.com/2908631/55248701-48a37f00-5270-11e9-8c33-3d7668ee1167.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
@nandika seems 
`
<membershipHandler class="org.apache.synapse.core.axis2.Axis2LoadBalanceMembershipHandler">
                            <property name="applicationDomain" value="apache.axis2.application.domain"/>
 </membershipHandler>
`

make this issue

**Comment by prabushi** [comment]
Since dynamicLoadbalance is not supported in synapse runtime, this will be removed from the documentation.
