### ISSUE TITLE
Example 1 in Store Mediator doesn't work

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/product-ei#3538]
**Description:**
I created a store mediator named "JMSMS" in message-stores. But however, it gives the following error when trying to save it.

Error: "Message Store mediator must have a Message store defined"

[Link to Doc](https://docs.wso2.com/display/EI6xx/Store+Mediator)

**Comment by dinuish94** [comment]
Fixed in docs.

**Comment by sajithshn** [comment]
Closing the issue as it's being already fixed. @dinuish94 Please re-open if there's more to be done.
