### ISSUE TITLE
Description tag within the main sequence is not persisted

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#3540]
**Description:**
"description" tag within the "main" sequence is not persisted from EI Tooling.

```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="main" xmlns="http://ws.apache.org/ns/synapse">
    <in>
         <log level="full"/>
         <filter source="get-property('To')" regex="http://localhost:9000.*">
            <send/>
         </filter>
      </in>
      <out>
         <send/>
      </out>
      <description>The main sequence for the message mediation</description>
</sequence> 
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Copy and paste the above mentioned configuration from the EI Tooling source view.
2. Close the tab and reopen the 'main' sequence artifact.
3. The tag, 'main' will not be persisted within the artifact.

**Related Issues:**

**Comment by dinuish94** [comment]
Description tag is not supported in sequences.
