### ISSUE TITLE
Relative URL for "Location" header fails in NHTTP transport

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-ei#3543]
**Description:**
For NHTTP transport, when we passed a relative URL for "Location" header, in org.apache.synapse.transport.nhttp.ClientWorker class, locationURI.getHost() return the relative URL and endpointURI.getHost() return absolute URL and NullPointerException occured when comparing them.

**Suggested Labels:**
ESB 5.0.0, NHTTP

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**
* Replace axis2.xml content with axis2_nhttp.xml content. 
* Create a mock soap backend with a header "Location" which has a value of a relative URL.
* Invoke the mock backend using a proxy and also passing the "Location" header.

**Comment by Shakila** [comment]
https://github.com/wso2-support/wso2-synapse/pull/570
