### ISSUE TITLE
Redirect to the correct version of docs

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3545]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/DB+Report+Mediator

- Sample 361: Introduction to DB Report Mediator
- Sample 362: DB Report and DBLookup Mediators Together
- Sample 363: Reusable Database Connection Pools
- Sample 271: File Processing (moves files into a database using the VFS transport and the DB Report mediator)

**Comment by nilminiwso2** [comment]
Fixed.
All mediator docs will be checked through [1].

[1] https://github.com/wso2/product-ei/issues/3509
