### ISSUE TITLE
[Docs][EI6xx] - Error in Code Snippet - Sample 252: Pure Text (Binary) and POX Message Support with JMS

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#3552]
**Description:**
This is regarding [Sample 252: Pure Text (Binary) and POX Message Support with JMS](https://docs.wso2.com/display/EI6xx/Sample+252%3A+Pure+Text+%28Binary%29+and+POX+Message+Support+with+JMS).

When I try to create a proxy service with the following configuration, an error is shown in dev studio (see image below).

```xml
<proxy name="JMSPoxProxy" transports="jms">
        <target inSequence="pox_proxy" outSequence="out">
                <faultSequence/>
        </target>
        <parameter name="transport.jms.ContentType">application/xml</parameter>
</proxy>
```

![image](https://user-images.githubusercontent.com/17300424/55277731-4e10d000-5329-11e9-80ff-181f98a85b52.png)

**Comment by praveennadarajah** [comment]
This issue can be overcomed by changing the content type by `xml` to `XML`
`<parameter name="transport.jms.ContentType">application/XML</parameter>`

**Comment by praveennadarajah** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/610 . Hence closing this issue
