### ISSUE TITLE
[Docs] Inaccurate/Out-of-date Instructions in Section "Configuring sample FIX applications"

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#3554]
## Description
The doc [Setting Up the ESB Samples](https://docs.wso2.com/display/EI6xx/Setting+Up+the+ESB+Samples) contains instructions under the sub-heading `Configuring sample FIX applications` (see image below) which do not seem to work.

<img width="1077" alt="Screen Shot 2019-03-31 at 1 11 34 AM" src="https://user-images.githubusercontent.com/17300424/55280908-22eea680-5352-11e9-9305-f6772670fa40.png">

I downloaded the latest release of QuickFIX/J from [this page](https://sourceforge.net/projects/quickfixj/files/).

### Listed below are the inaccuracies in the doc.
- There is no file named `quickfixj-examples.jar`. Instead, there are two files `quickfixj-examples-banzai-2.1.1.jar` and `quickfixj-examples-executor-2.1.1.jar`.
- The next instruction i.e. `execute the sample apps from <QFJ_HOME>/bin` is inaccurate as there is no `bin` directory in the downloaded QuickFIX/J distribution.

Following are the contents of the downloaded directory `org.quickfixj-2.1.1`.
```
.
├── LICENSE
├── README.md
├── doc
├── etc
├── lib
├── org.quickfixj-2.1.1-src.zip
├── quickfixj-all-2.1.1.jar
├── quickfixj-codegenerator-2.1.1.jar
├── quickfixj-core-2.1.1.jar
├── quickfixj-dictgenerator-2.1.1.jar
├── quickfixj-examples-banzai-2.1.1.jar
├── quickfixj-examples-executor-2.1.1.jar
├── quickfixj-examples-ordermatch-2.1.1.jar
├── quickfixj-messages-all-2.1.1.jar
├── quickfixj-messages-fix40-2.1.1.jar
├── quickfixj-messages-fix41-2.1.1.jar
├── quickfixj-messages-fix42-2.1.1.jar
├── quickfixj-messages-fix43-2.1.1.jar
├── quickfixj-messages-fix44-2.1.1.jar
├── quickfixj-messages-fix50-2.1.1.jar
├── quickfixj-messages-fix50sp1-2.1.1.jar
├── quickfixj-messages-fix50sp2-2.1.1.jar
└── quickfixj-messages-fixt11-2.1.1.jar

3 directories, 20 files

```

**Comment by KasunAratthanage** [comment]
Document updated [1].

[1] https://docs.wso2.com/display/EI6xx/Setting+Up+the+ESB+Samples

**Comment by KasunAratthanage** [comment]
@nilminiwso2 This issue can be closed.
