### ISSUE TITLE
[EI Tooling] Json support for property expression

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3556]
**Description:**

I wanted to enter below as my property expression. 

`json-eval($.hospital)`

When clicked on Expression box, it brings up a popup Which force me to evaluate an "XML expression". It supports only XPath. 
Also, if I need to copy expression, same box pops up. 

Can we support Json as well? Also, IMO, evaluation needs to be optional. I should not be forced for evaluation loading an input xml etc. 

![image](https://user-images.githubusercontent.com/4967046/55285025-869fc080-53a0-11e9-8f0a-fd6900af845c.png)

**Comment by dilee** [comment]
The JSON evaluator dialog view is already implemented in a separate development branch and is yet to be combined with the XPath view.

**Comment by dakshika** [comment]
closing this due to similar duplicate #3731
