### ISSUE TITLE
[EI Tooling] Property view warn does not clear even if updated correctly

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3557]
**Description:**

Even if i filled up values for property mediator, WARN stating it is not edited does not clear up. 
Please see below. It is there even if the configs are saved. 

![image](https://user-images.githubusercontent.com/4967046/55285077-9cfa4c00-53a1-11e9-9a12-a3fb524d1d0e.png)

**Comment by rosensilva** [comment]
Fixed in wso2/devstudio-tooling-platform#142
