### ISSUE TITLE
[EI Tooling] Cannot add any mediator after a property mediator with Json expression for the second resource of API

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3558]
**Description:**

Steps to reproduce (Extracted from [1])

1. Add a resource to an API with a url template
2. Add another resource to same API. 
3. Add property mediator to second resource with a Json eval expression. 
4. Save the config. 
5. Add a Switch mediator after the property mediator above. 

   Any mediator after property mediator cannot be added. 

[1]. https://docs.wso2.com/display/EI640/Routing+Requests+Based+on+Message+Content

![image](https://user-images.githubusercontent.com/4967046/55285781-9ffc3900-53af-11e9-92a3-3060f302305c.png)

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-platform/pull/142
