### ISSUE TITLE
[EI Tooling] Data mapper live review does not work

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3562]
**Description:**

I did a data mapper following [1]. It is a Json to Json transformation. When live preview was tried with input itself, it failed. 

Is there something I am missing here? 

![image](https://user-images.githubusercontent.com/4967046/55288373-4b1ee980-53d4-11e9-917b-d31b5889b781.png)

[1]. https://docs.wso2.com/display/EI640/Transforming+Message+Content

**Comment by abeykoon** [comment]
I had to save the config before trying the live preview. 
When clicked on "Try-out", shall we save it automatically by code, and then run?

**Comment by abeykoon** [comment]
It is a valid case that, user might try out without saving and finding live preview is not working. By above suggestion we can prevent that.

**Comment by dakshika** [comment]
+1 for the suggestion
