### ISSUE TITLE
Sequence content does not get saved after going to Design view in Tooling

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/product-ei#3563]
**Description:**
When adding the sample content in [1] to a sequence as below
![image](https://user-images.githubusercontent.com/29540334/55289514-65ad8e80-53e5-11e9-919d-dffa6ae0e8ce.png)

And it saves the content without error. But after switching from source-->Design-->Source view path the content is missing

![image](https://user-images.githubusercontent.com/29540334/55289539-b02f0b00-53e5-11e9-94b5-97492f56def0.png)

[1] - https://docs.wso2.com/display/EI6xx/CXF%20WS-RM%20Inbound%20Protocol

**Affected Product Version:**
EI tooling 

**OS, DB, other environment details and versions:**    
Ubuntu 16.04
Oracle JDK8

**Comment by dakshika** [comment]
@sameerawickramasekara To make this work you need to name sequence xml as "main.xml". then it will get saved.
