### ISSUE TITLE
Websocket inbound endpoint properties missing after switching to Design view

### ISSUE THREAD

**Issue by sameerawickramasekara** [wso2/product-ei#3564]
**Description:**
After adding the sample Websocket/Secure Websocket inbound endpoint if you switch to Design view and come back, some properties previously set are missing.

**Affected Product Version:**
Tooling

**OS, DB, other environment details and versions:**    
Ubuntu 16.04
Oracle JDK8

**Steps to reproduce:**
Add following endpoint in source view
`<inboundEndpoint name="WebSocketListenerEP" onError="fault" protocol="ws" sequence="TestIn" suspend="false">
  <parameters>
     <parameter name="inbound.ws.port">9091</parameter>
     <parameter name="ws.outflow.dispatch.sequence">TestOut</parameter>
     <parameter name="ws.client.side.broadcast.level">0</parameter>
     <parameter name="ws.outflow.dispatch.fault.sequence">fault</parameter>
  </parameters>
</inboundEndpoint>`

For Secure WebSockets add the following

`<inboundEndpoint name="SecureWebSocketEP" onError="fault" protocol="wss" sequence="TestIn" suspend="false">
  <parameters>
     <parameter name="inbound.ws.port">9091</parameter>
     <parameter name="ws.client.side.broadcast.level">0</parameter>
     <parameter name="ws.outflow.dispatch.sequence">TestOut</parameter>
     <parameter name="ws.outflow.dispatch.fault.sequence">fault</parameter>
     <parameter name="wss.ssl.key.store.file">repository/resources/security/wso2carbon.jks</parameter>
     <parameter name="wss.ssl.key.store.pass">wso2carbon</parameter>
     <parameter name="wss.ssl.trust.store.file">repository/resources/security/client-truststore.jks</parameter>
     <parameter name="wss.ssl.trust.store.pass">wso2carbon</parameter>
     <parameter name="wss.ssl.cert.pass">wso2</parameter>
   </parameters>
</inboundEndpoint>`

Save the content
Switch to Design view
Switch back to source view

**Related Issues:**
#3563

**Comment by dilee** [comment]
This happens when the Synapse namespace declaration is missing in the inbound endpoint definition. Properties will be preserved properly when the namespace declaration is present as shown below.

`<inboundEndpoint name="WSEndpoint" onError="fault" protocol="ws" sequence="TestIn" suspend="false" xmlns="http://ws.apache.org/ns/synapse">`
