### ISSUE TITLE
ViewPopTest failing intermittently

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3570]
**Description:**

The above test case is failing intermittently while building. 
https://wso2.org/jenkins/job/products/job/product-ei-mediation-profile/org.wso2.ei$org.wso2.carbon.ei.tests.transport/652/testReport/junit/org.wso2.carbon.esb.jms.ViewPopRedirectTests/ViewPopTest/testViewInMessageStore/

java.lang.AssertionError: Returned message is not the same as expected message. expected:<<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><m0:getQuote xmlns:m0="http://services.samples">
 <m0:request>IBM
 </m0:request>
   <m0:request>WSO2
 </m0:request>
</m0:getQuote></soapenv:Body></soapenv:Envelope>> but was:<null>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.wso2.carbon.esb.jms.ViewPopRedirectTests.ViewPopTest.testViewInMessageStore(ViewPopTest.java:110)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
https://github.com/wso2/product-ei/pull/3569

**Comment by Nirothipan** [comment]
https://github.com/wso2/product-ei/pull/3635

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/product-ei/pull/3689
