### ISSUE TITLE
[EI-Tooling] Display arguments in payload factory property view  

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3571]
**Description:**

The arguments are not displayed in a table. "payload Factory Argument expression" does not give any additional information. 

![image](https://user-images.githubusercontent.com/4967046/55311514-c5a54300-5480-11e9-9cdc-8f17dd4ebc56.png)

Expected something like 

![image](https://user-images.githubusercontent.com/4967046/55311566-e79ec580-5480-11e9-813a-d82781659f97.png)

**Comment by praveennadarajah** [comment]
This issue has been fixed. Please find the PR below
https://github.com/wso2/devstudio-tooling-esb/pull/788/files
