### ISSUE TITLE
Add 'Mediator Project' for Getting Started dashboard

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#3582]
**Description:**
$subject to allow the user with the capability to add a custom mediator via the 'Getting Started' dashboard.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
We can place it under Miscellaneous Project Types

**Comment by dakshika** [comment]
fixed with https://github.com/wso2/devstudio-tooling-esb/pull/781
