### ISSUE TITLE
Response does not send from respond mediator 

### ISSUE THREAD

**Issue by vithu30** [wso2/product-ei#3586]
**Description:**
Respond mediator does not send the respond to client when following property is not used:
`<property name="NO_ENTITY_BODY" scope="axis2" action="remove"/>`

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
EI-6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Add a sequence in governance registry which calls an endpoint that return 202 status code
2. Create an API by calling the sequence prior to respond mediator
3. Response body will be there in message context (can be observed through wire-logs)
4. But client does not get the response body
5. If we add following property mediator prior to respond mediator, it is working without issues.
`<property name="NO_ENTITY_BODY" scope="axis2" action="remove"/>`
6. If we add a template in governance registry which contains the similar logic as sequence mentioned in step -1 and call that template from API, it is working fine without adding the property mentioned in step -5

**Related Issues:**

**Comment by Nirothipan** [comment]
This issue is reproducible with following configuration.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="testReg"
       transports="http https"
       startOnLoad="true">
   <description/>
   <target>
      <inSequence>
         <log level="custom">
            <property name="== Proxy ===" value="===== Invoked ======"/>
         </log>
         <sequence key="gov:/regSeq"/>
         <property name="HTTP_SC" scope="axis2" action="remove"/>
         <property name="SC_ACCEPTED" value="false" scope="axis2" type="STRING"/>
         <property name="HTTP_SC" value="200" scope="axis2" type="STRING"/>
         <log level="full"/>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </target>
</proxy>
```
regSeq configuration.

```
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse">
    <property name="logServiceResponse" scope="default" type="OM">
        <root xmlns="">
            <we>are</we>
        </root>
    </property>
    <call>
        <endpoint>
            <http uri-template="http://www.mocky.io/v2/5ccbeffc3300008428e0194d"/>
        </endpoint>
    </call>
    <property name="messageType" scope="axis2" type="STRING" value="application/xml"/>
    <enrich>
        <source clone="true" property="logServiceResponse" type="property"/>
        <target action="replace" type="body"/>
    </enrich>
</sequence>
```

**Comment by Nirothipan** [comment]
This is happening because NO_ENTITY_BODY is not removed while enriching.
