### ISSUE TITLE
[EI Tooling] Defined EPs and transform mediator group are of same colour 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3588]
**Description:**

![image](https://user-images.githubusercontent.com/4967046/55382761-1fbb0c80-5544-11e9-8401-4c07dde748fd.png)

**Comment by abeykoon** [comment]
Shall we add grey for defined EPs? 
Also when dragged defined EP name should automatically appear.

**Comment by dakshika** [comment]
IMO this is ok with current designed color theme. hence closing the issue
