### ISSUE TITLE
[EI Tooling] Gmail connector Init function cannot be dragged to the design space

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3599]
**Description:**

Cannot drag and drop gmail connector "init" function to the design view of EI tooling. 

![image](https://user-images.githubusercontent.com/4967046/55457497-b3094600-5607-11e9-9eb3-992bdeb8626e.png)

**Comment by abeykoon** [comment]
Following was logged on the console

`ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.sun.script.sleep.SleepScriptEngineFactory not found`

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-platform/pull/142
