### ISSUE TITLE
[Blocker] Cannot start the EI pack on Windows

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#36]
**Environment**
OS-Windows 2008
JAVA-JDK 1.8.0_121
Default EI M1 pack

**Steps**
Start the pack using start_all.bat file

**Error**
Pop-up several terminals saying "System cannot find the file specified " and All files inside bin folder got hidden or deleted except yajsw folder.

Same behavior can be seen when starting integrator.bat file

**Comment by mpmunasinghe** [comment]
Fixed with https://github.com/wso2/product-ei/pull/84/commits/6146b84d301f7de3f1570c899c82f8a95844858b
