### ISSUE TITLE
When adding a registry resource to wso2 developer studio registry project, it sets the default media type values depending on the file extension.

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/product-ei#3607]
**Description:**

As mentioned above, when we are adding a registry resource from the file system to the wso2 developer studio registry project, it sets the default media type values depending on the file extension. This fact should be added to documentation in [1].

It was seen that the 'Media Type' of data mapper related files are setting as "text/plain" by default in the registry-info.xml file, which is apparently the supported type of the datamapper deployer. However, if we create a registry project and import those files, it sets the default media type values depending on the file extension. It throws an exception if we use those data mapper config for the data mapper.

So if someone creates the data mapper config separate as a registry project, they need to change the media-type as text/plain in the Resource Editor panel. This should be included to the documentation in [2].

[1]https://docs.wso2.com/display/EI640/Working+with+Registry+Artifacts#WorkingwithRegistryArtifacts-Importfromfilesystem

[2]https://docs.wso2.com/display/EI640/Data+Mapper+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
we cannot add a screenshot to explain this due to [4067](https://github.com/wso2/product-ei/issues/4067)
