### ISSUE TITLE
[EI6.1][Analytics]Eventhough the stats are disabled for an API, and when you enable for and EP which is used by that API, it will increment the count of stats

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#361]
[EI6.1][Analytics]Eventhough the stats are disabled for an API, and when you enable for and EP which is used by that API, it will increment the count of stats.

1. Globally stats are disabled.
2. Disable stats for an API and endpoint which is being used by that API.
3. Invoke API. Stats will not be published in both sides, which is correct.
4. Now enable stats only for the endpoint and invoke.
5. Only the endpoint should increment the count. But the API will also be incremented.

Please find the screenshots below.

![api_after_count](https://cloud.githubusercontent.com/assets/12966170/24287916/79b66d22-10a1-11e7-90c8-d96c6a6b1688.png)

![ep_after_count](https://cloud.githubusercontent.com/assets/12966170/24287913/79b61da4-10a1-11e7-97d0-412fa0bf6022.png)

![ep_before_count](https://cloud.githubusercontent.com/assets/12966170/24287918/79b75f84-10a1-11e7-8d2e-e2cb8e0d0b46.png)

![api_before_count](https://cloud.githubusercontent.com/assets/12966170/24287914/79b6298e-10a1-11e7-8c31-629f5d889346.png)

![pizzaep_stat_enabled](https://cloud.githubusercontent.com/assets/12966170/24287917/79b702d2-10a1-11e7-9a68-d9945dab9972.png)

![ushani_api_stat_disabled](https://cloud.githubusercontent.com/assets/12966170/24287915/79b62e52-10a1-11e7-9162-eddb66b165b6.png)

**Comment by ushanib** [comment]
For an API which uses endpoints configured outside the API, has got mismatched request total count.

Root cause can be same. Hence, reporting this issue as a comment. 


![screenshot from 2017-03-24 15-54-12](https://cloud.githubusercontent.com/assets/12966170/24290228/3241dd2e-10aa-11e7-8033-1c29ace99d38.png)
 

![screenshot from 2017-03-24 15-55-03](https://cloud.githubusercontent.com/assets/12966170/24290252/4b0141c4-10aa-11e7-9c4c-80a1d9c1ec79.png)

**Comment by milindaperera** [comment]
We need to check also if external EP if referred by 2 APIs or API + Proxy, ... invoke one API/Proxy and observe the stats of the other API/Proxy is effected by that. Let's test that too if you missed

**Comment by AnuGayan** [comment]
This was fixed in EI analytics 6.4.0
