### ISSUE TITLE
[EI Tooling] Debug - clear property during debug is not working

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3611]
**Description:**

During Debug, we can remove properties during Debug. 
Tooling does not allow to specify which property to remove. 

![image](https://user-images.githubusercontent.com/4967046/55531496-31c5b800-56c8-11e9-876b-95115ea979ae.png)

**Comment by praveennadarajah** [comment]
This issue is not reproducable in the latest pack.
