### ISSUE TITLE
[EI Tooling] when debugging toggle break points does not reflect on UI correctly

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3614]
**Description:**

Toggling break points sometimes work, sometimes does not. There is an intermittent issue. 

Please follow steps on issue [1] and toggle break points here and there. You will observe the issue. 

[1]. https://github.com/wso2/product-ei/issues/3613

![image](https://user-images.githubusercontent.com/4967046/55535184-08128e00-56d4-11e9-87f6-bb94d30b320e.png)

**Comment by dakshika** [comment]
cannot reproduced
