### ISSUE TITLE
Test EI tooling with tracking features tested 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3618]
**Description:**

Test EI tooling milestone pack with a document tracking which features tested.

**Comment by dakshika** [comment]
@abeykoon How the progress of this

**Comment by abeykoon** [comment]
The testing with new features are done. 
The issues under this epic is reported at [1]. About 10 issues are still to be worked on by the Tooling Team. 

[1]. https://github.com/wso2/product-ei/issues?q=is%3Aopen+is%3Aissue+author%3Aabeykoon+label%3A%22Integration+Studio%22

**Comment by abeykoon** [comment]
Closing the epic as the task is done.
