### ISSUE TITLE
[Tooling] Need to add key - value detail display on each mediators

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#3621]
**Description:**
1. Class
2. Switch
3. Validate
4. Command
5. EJB
6. Script
7. XQuery
8. XSLT
9. Builder
10. Publish Event

**Comment by praveennadarajah** [comment]
I have started working on this!

**Comment by praveennadarajah** [comment]
Please find the fix for Class mediator below
https://github.com/wso2/devstudio-tooling-esb/pull/790/files

**Comment by praveennadarajah** [comment]
Please find the fix for Validate mediator below
https://github.com/wso2/devstudio-tooling-esb/pull/792/files

**Comment by praveennadarajah** [comment]
Please find the fix for Command mediator below
https://github.com/wso2/devstudio-tooling-esb/pull/793/files

**Comment by praveennadarajah** [comment]
Please find the fix for EJB mediator
https://github.com/wso2/devstudio-tooling-esb/pull/794/files

**Comment by praveennadarajah** [comment]
Please find the fix for Script mediator
https://github.com/wso2/devstudio-tooling-esb/pull/795/files

**Comment by praveennadarajah** [comment]
Please find the fix for XQuery mediator
https://github.com/wso2/devstudio-tooling-esb/pull/797/files

**Comment by praveennadarajah** [comment]
Please find the fix for XSLT mediator
https://github.com/wso2/devstudio-tooling-esb/pull/798/files

**Comment by praveennadarajah** [comment]
Please find the fix for Builder mediator
https://github.com/wso2/devstudio-tooling-esb/pull/799/files

**Comment by praveennadarajah** [comment]
Please find the fix for PublishEvent mediator
https://github.com/wso2/devstudio-tooling-esb/pull/803/files

**Comment by dakshika** [comment]
thank you @praveennadarajah
