### ISSUE TITLE
[6.4.0][MTOM] Merge fix to MTOM messages when enabling DISABLE_CHUNKING or FORCE_HTTP_1_0 properties

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/product-ei#3624]
**Description:**
When the DISABLE_CHUNKING and/or FORCE_HTTP_1_0 properties are enabled, WSO2 will send an invalid MTOM message.

Details are explained in the following pull request : https://github.com/wso2/wso2-synapse/pull/1303

**Affected Product Version:**
WSO2 EI 6.4.0

**Steps to reproduce:**
Set the DISABLE_CHUNKING property to true in the inSequence of a proxy service.
Use the send mediator to send the message to an mtom optimized endpoint (default or address).

**Comment by Nirothipan** [comment]
Hi @mathieubouchard 

Thanks for contributing. The fix is merged now https://github.com/wso2/wso2-synapse/pull/1322

Thanks
Nirothipan
