### ISSUE TITLE
[EI Tooling] Additional red dot in create API window

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3625]
**Description:**

See below. Did we meant to insert an icon here? 

![image](https://user-images.githubusercontent.com/4967046/55663894-b9cfcd00-5842-11e9-9539-e3cbf5cad3b2.png)

**Comment by dakshika** [comment]
Currently this image is exist on the code. https://github.com/wso2/devstudio-tooling-esb/blob/master/plugins/org.wso2.developerstudio.eclipse.artifact.synapse.api/icons/synapseAPILarge.png 

Also, this is visible on eclipse runtime test.
