### ISSUE TITLE
[EI Tooling] graphical view does not show in seq and out seq when add defined sequences

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3626]
**Description:**

1. Define two sequences as inSeq and out Seq
2. Create an API and to the resource define them as in sequence and out sequence. 
3. Graphical view does not update with defined sequences. What if we drag mediators to the design view?

**Comment by dakshika** [comment]
@isudana Can you comment on this? 

IMO showing those details on graphical view may add additional complexities  to the user. WDYT?

**Comment by isudana** [comment]
Yes, I do not think we need to show the defined sequence in the graphical view.
