### ISSUE TITLE
[EI 6.1][Analytics]The auto selected request count for API/Proxies/EP for the last hour is wrong

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#363]
1. Invoke an API few times.
2. After few hours (a day), invoke it again
3. Check the count for the particular api selecting the api.
4. It will display the count and the time range is set as for last hour by default.This count is wrong. It will display the total count.
6. Now make change the time range as last 24 hours or 30 days and then select last hour again.
7. Then it will display the correct count.
 It should display the correct count for the last hour when you select the particular artifact.

![screenshot from 2017-03-24 16-35-33](https://cloud.githubusercontent.com/assets/12966170/24291739/39be1530-10b0-11e7-9881-1ebec971d8e6.png)

![screenshot from 2017-03-24 16-35-40](https://cloud.githubusercontent.com/assets/12966170/24291737/39b96b84-10b0-11e7-9ac1-057503456f9b.png)

**Comment by isurusuranga** [comment]
I have tested this and I'm not able to reproduce this similar issue. However, it will take time to summarize the result (Analytics script configure to execute every 2 minutes). In the mean time if you check the count for the particular api for last hour it will show the wrong count.

**Comment by isurusuranga** [comment]
But if refresh the UI after selected the time range for last hour or last 24 hours (by default it is set to Last 30 days in UI), it will show the total request count instead of appearing the correct count. This issue fix in the following PR.

https://github.com/wso2/product-ei/pull/420

**Comment by ushanib** [comment]
This is not fixed in alpha
