### ISSUE TITLE
[EI Tooling] WS-Policy links are not working 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3637]
**Description:**

Steps to reproduce: Please follow 
https://docs.wso2.com/display/EI640/Applying+Security+to+a+Proxy+Service

Links do not bring up anything. They supposed to bring up a description. 

![image](https://user-images.githubusercontent.com/4967046/55700625-a01eb900-59ed-11e9-9322-37ffbe0eb050.png)

Expected: 

![image](https://user-images.githubusercontent.com/4967046/55700659-be84b480-59ed-11e9-84fd-5ea47bccc43b.png)

**Comment by prabushi** [comment]
Click on the icon to the left of the radio button to get the descriptive image of each WS-policy. Clicking on the link will not pop up this image. It will only load the respective policy to the file.
