### ISSUE TITLE
API and API resource are not graphically emphasized

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3651]
<img width="1680" alt="Screen Shot 2019-04-08 at 2 04 14 PM" src="https://user-images.githubusercontent.com/574041/55760868-4aa8d300-5a12-11e9-8fa5-450b14fc42f2.png">
**Description:**
This is a problem that we already had in old releases as well as the ongoing 6.5. It's hard to distinguish the API (compartment) and resources. 
We need to graphically illustrate the API  along with the configuration of it. Then for each resource, we have to show the configuration of each resource. 

In the current design, there's a hidden (way down) arrow icon that represents the inbound and outbound traffic from the API.

**Comment by kasun04** [comment]
Also the tooltip 'API Compartment' has no notion in the configuration lang.

**Comment by kasun04** [comment]
**API resources improvements**

When we have multiple resources it's hard to uniquely identify them. So, we could possibly improve it by showing the URI mapping/template along with resource.

**Comment by dakshika** [comment]
similar duplicate https://github.com/wso2/product-ei/issues/2726
