### ISSUE TITLE
Simplify console output of 'Run' and 'Debug. 

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3653]
**Description:**
This should be done along with https://github.com/wso2/micro-integrator/issues/52 

**Related Issues:**
https://github.com/wso2/micro-integrator/issues/52

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/micro-integrator/issues/52 and https://github.com/wso2/carbon-mediation/pull/1234
