### ISSUE TITLE
Aggregate mediator - Completely disconnected from out sequence

### ISSUE THREAD

**Issue by kasun04** [wso2/product-ei#3661]
<img width="1156" alt="Screen Shot 2019-04-08 at 5 38 22 PM" src="https://user-images.githubusercontent.com/574041/55765816-53a39f80-5a26-11e9-94b8-0ebfd5b827a0.png">

**Comment by Drifftr** [comment]
We have tried to reproduce this behavior but couldn't. Can you attach the config or steps to reproduce?.

**Comment by dakshika** [comment]
Cannot reproduce
