### ISSUE TITLE
[EI Tooling] Property view is not user friendly for Json expressions

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3675]
**Description:**

1. The UI that pops up to enter expression for Json path does not has a Json flavour. 
2. There should be no push for user to evaluate the expression he enters. It should be optional. 
3. If we do not support evaluating Json we should disable evaluate button if someone enter a Json path. 

![image](https://user-images.githubusercontent.com/4967046/55851952-92e20580-5b78-11e9-8ce3-4c438d2f8dde.png)

**Comment by dakshika** [comment]
similar duplicate [Tooling] Expression evaluator needs to have JSON support #3731
