### ISSUE TITLE
[EI Tooling] Gmail connector parameters are not displayed on property view

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3676]
**Description:**

When properties are filled up for gmail connector init, they do not get showed up on the property view. 

![image](https://user-images.githubusercontent.com/4967046/55852260-d6893f00-5b79-11e9-8b89-b508e892b5d1.png)

**Comment by dakshika** [comment]
@praveennadarajah please have a look

**Comment by praveennadarajah** [comment]
I have fixed this issue. Please find the PR below
https://github.com/wso2/devstudio-tooling-esb/pull/813/files
