### ISSUE TITLE
[EI Tooling] Connector icons are not alined and look smaller 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3679]
**Description:**

Please see below. Need to fix the icons to match with the 

1. Overall theme
2. Size 

of other mediator icons. Also need to fix the alignments. 

![image](https://user-images.githubusercontent.com/4967046/55853753-118e7100-5b80-11e9-9804-f68cfe472dbf.png)

**Comment by dakshika** [comment]
We have to fix this in all 197 connectors

**Comment by dakshika** [comment]
we are planning to select top 20 connectors first and release them

**Comment by dakshika** [comment]
top 20 connectors are done and merge


https://github.com/wso2-extensions/esb-connector-file | https://github.com/wso2-extensions/esb-connector-file/pull/53 | Merged
-- | -- | --
https://github.com/wso2-extensions/esb-connector-kafka | https://github.com/wso2-extensions/esb-connector-kafka/pull/31 | Merged
https://github.com/wso2-extensions/esb-connector-googlefirebase | https://github.com/wso2-extensions/esb-connector-googlefirebase/pull/12 | Merged
https://github.com/wso2-extensions/esb-connector-salesforce | https://github.com/wso2-extensions/esb-connector-salesforce/pull/31 | Merged
https://github.com/wso2-extensions/esb-connector-gmail | https://github.com/wso2-extensions/esb-connector-gmail/pull/44 | Merged
https://github.com/wso2-extensions/esb-connector-salesforcerest | https://github.com/wso2-extensions/esb-connector-salesforcerest/pull/30 | Merged
https://github.com/wso2-extensions/esb-connector-amazons3 | https://github.com/wso2-extensions/esb-connector-amazons3/pull/32 | Merged
https://github.com/wso2-extensions/esb-connector-elasticsearch | https://github.com/wso2-extensions/esb-connector-elasticsearch/pull/12 | Merged
https://github.com/wso2-extensions/esb-connector-iso8583 | https://github.com/wso2-extensions/esb-connector-iso8583/pull/18 | Merged
https://github.com/wso2-extensions/esb-connector-msdynamics365 | https://github.com/wso2-extensions/esb-connector-msdynamics365/pull/2/ | Merged
https://github.com/wso2-extensions/esb-connector-outlookmail | https://github.com/wso2-extensions/esb-connector-outlookmail/pull/12 | Merged
https://github.com/wso2-extensions/esb-connector-amazonsqs | https://github.com/wso2-extensions/esb-connector-amazonsqs/pull/16 | Merged
https://github.com/wso2-extensions/esb-connector-bigquery | https://github.com/wso2-extensions/esb-connector-bigquery/pull/32 | Merged
https://github.com/wso2-extensions/esb-connector-magento | https://github.com/wso2-extensions/esb-connector-magento/pull/10 | Merged
https://github.com/wso2-extensions/esb-connector-fhir | https://github.com/wso2-extensions/esb-connector-fhir/pull/10 | Merged
https://github.com/wso2-extensions/esb-connector-sapbydesign | https://github.com/wso2-extensions/esb-connector-sapbydesign/pull/2 | Merged
https://github.com/wso2-extensions/esb-connector-ldap | https://github.com/wso2-extensions/esb-connector-ldap/pull/31 | Merged
https://github.com/wso2-extensions/esb-connector-googlespreadsheet | https://github.com/wso2-extensions/esb-connector-googlespreadsheet/pull/15 | Merged
https://github.com/wso2-extensions/esb-connector-jira | https://github.com/wso2-extensions/esb-connector-jira/pull/14 | Merged
https://github.com/wso2-extensions/esb-connector-jms | https://github.com/wso2-extensions/esb-connector-jms/pull/3 | Merged
