### ISSUE TITLE
Double click on sequence mediator in design view opens an empty design

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-ei#3682]
**Description:**
When double click on sequence mediator in navigation tree opens the expected design of the mediator. However, when double click on sequence mediator in design view opens an empty design. 

**Suggested Labels:**
EI 6.4.0 tooling

**Affected Product Version:**
EI 6.4.0 tooling (Version: Oxygen.3a Release (4.7.3a))

**Comment by prabushi** [comment]
Fixed for WSO2 EI Tooling 6.5.0 in https://github.com/wso2/devstudio-tooling-esb/commit/78aa0f081723e0d077af60eaec28c7cfce84631d#diff-0ecea56bde8ad6008d64e868419ad3b1

**Comment by dakshika** [comment]
fixed in latest master
