### ISSUE TITLE
[Migration] EI older versions to EI 6.5.0

### ISSUE THREAD

**Issue by samgnaniah** [wso2/product-ei#3685]
Need to test migration for EI 6.5.0 with older versions and add documentation.

Affects EI 6.5.0 and needs to be done prior to the release.

**Comment by malakaganga** [comment]
Please find the necessary changes to the docs in the following doc

https://docs.google.com/document/d/1qKKITHQcuWoCddSznbkVLz7S7YnYDpURBwTUx3oVeqo/edit?usp=sharing

**Comment by dulanjalidilmi** [comment]
Related PR https://github.com/wso2-support/product-ei/pull/198, https://github.com/wso2-support/product-ei/pull/199

**Comment by nilminiwso2** [comment]
Docs for the following migrations are updated [1]:
- ESB 5.0.0 to EI 6.5.0
- EI 6.4.0 to EI 6.5.0 (ESB, BP, and MB profiles only)
- MB 3.1.0 to EI 6.5.0
- BPS 3.6.0 to EI 6.5.0
- DSS 3.5.1 to EI 6.5.0

WIP:
EI 6.4.0 to EI 6.5.0 (Analytics profile)

[1] https://docs.wso2.com/display/EI6xx/Upgrading+from+a+Previous+Release

**Comment by nilminiwso2** [comment]
The following migration scenarios are updated with all the changes affecting the database upgrade.

[1] ESB 5.0.0 to ESB profile of EI 6.4.0
[2] ESB 5.0.0 to ESB profile of EI 6.5.0
[3] ESB profile of EI 6.1.1 to ESB profile of EI 6.2.0

[4] BPS 3.6.0 to BPS profile of EI 6.4.0
[5] BPS 3.6.0 to BPS profile of EI 6.5.0
