### ISSUE TITLE
[EI Tooling] Incomplete template design in few endpoints

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3688]
**Description:**
Following endpoint, template designs are showing as incomplete in design view.

<img width="300" alt="Screen Shot 2019-04-11 at 9 50 51 AM" src="https://user-images.githubusercontent.com/40847371/55930599-a5734200-5c3f-11e9-9c25-2450090fab23.png">

<img width="300" alt="Screen Shot 2019-04-11 at 9 50 32 AM" src="https://user-images.githubusercontent.com/40847371/55930602-aa37f600-5c3f-11e9-90de-46294a4b8888.png">

<img width="300" alt="Screen Shot 2019-04-11 at 9 50 14 AM" src="https://user-images.githubusercontent.com/40847371/55930607-aefcaa00-5c3f-11e9-81c3-b14011eb7bc0.png">

**Suggested Labels:**
EI Tooling

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dakshika** [comment]
this is fixed in latest master
