### ISSUE TITLE
Duplicate entry definition for key

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#3694]
**Description:**
Capp deployment errors when failed to uncheck the local entry initially. 

**Suggested Labels:**
Bug

**Affected Product Version:**
ESB 5.0.0

**Steps to reproduce:**

1) Create a ESB solution project with a proxy service and a local entry. (local entry will be referred in the proxy service).
2) Export a capp without adding the local entry and deploy it.
3) Invoke the proxy service. 
4) Export a new capp with the proxy service and the local entry.
5) Undeploy the previous capp and deploy the new one.

**Comment by prabushi** [comment]
Duplicate https://github.com/wso2/product-ei/issues/3233
