### ISSUE TITLE
[EI Tooling] Graphical Mapping getting disappear when adding a log mediator into a aggregate mediator

### ISSUE THREAD

**Issue by RidmiR** [wso2/product-ei#3703]
**Description:**
<img width="300" alt="Screen Shot 2019-04-12 at 12 45 32 PM" src="https://user-images.githubusercontent.com/40847371/56018872-ed1dca80-5d20-11e9-8235-513e73bf534a.png">

**Suggested Labels:**
EI Tooling

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create a Proxy
- Add aggregate mediator
- Add a log mediator

**Related Issues:**

**Comment by rosensilva** [comment]
Possible duplication https://github.com/wso2/product-ei/issues/3660
