### ISSUE TITLE
Datamapper diagram editor Input Output File loading not working

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3706]
When we start from a fresh DM mediator diagram editor, double-clicking on the Input or Output does not show the popup dialog box. To get it to work, first, we need to click somewhere else first.

![image](https://user-images.githubusercontent.com/748819/56022732-f9f2ec00-5d29-11e9-98fc-35552e963398.png)

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/836
