### ISSUE TITLE
Getting Started Dashboard not working when we switch workspace and restart

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3710]
The dashboard is only working when we shut down and start not when restarting with a new workspace. 
Looks like we are preserving some data which is required for the dashboard in the initial workspace.

**Comment by Drifftr** [comment]
Possible fix - https://github.com/wso2/devstudio-tooling-platform/pull/153

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/153
