### ISSUE TITLE
Datamapper XML transformation broken

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3711]
Not properly working when there are namespaces in the XML payload which is a basic scenario

**Comment by Drifftr** [comment]
Duplicate of https://github.com/wso2/product-ei/issues/3705

**Comment by isudana** [comment]
This is not working even in the latest pack. 
Realtime preview works fine, but generated xslt does not contain namespace declarations.

**Comment by Drifftr** [comment]
Added custom namespaces to XSLT style sheets https://github.com/wso2/devstudio-tooling-esb/pull/927

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/927
