### ISSUE TITLE
The Tooling 'perspective' does not change when a BPMN project is created

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#3724]
**Description:**
When we create a new BPMN project in Dev Studio, the 'BPMN project creation' dialog does not shut down after creating the project. There is also no indication that the project is created. The user has to manually close the dialog and switch to the project explorer in order to view the project.

Also, the complete folder structure doesn't seem to get created under the project name.

The system should automatically switch to the explorer view on creating the new project.
Note: Works for Human Task/BPEL projects.

**Suggested Assignees:**
@Drifftr 

**Affected Product Version:**
EI 6.5.0

**OS, DB, other environment details and versions:**    
Tested on MacOS.

**Steps to reproduce:**
1. Open Tooling.
2. Go to Miscellaneous -> Create New BPMN. A dialog opens.
3. Enter a name for the BPMN project and click Finish. 
Nothing happens! However, if we close the dialog box and go to the project explorer, the new project is created.
4. Open the project from the Project Explorer: The sub folders are not created.

**Related Issues:**

**Comment by Drifftr** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-platform/pull/154
