### ISSUE TITLE
InboundEndpoint vfs Fails to pull file from SFTP

### ISSUE THREAD

**Issue by dengrand** [wso2/product-ei#3725]
**Description:**
Hello,

I am using WSO2 EI 6.4.

I have an InboundEndpoint for polling files from a SFTP.

And I got this error : 
```
[2019-04-16 10:29:18,701] [] ERROR - FilePollingConsumer Error checking for existence and readability : sftp://admin":***@"10.0.0.2/IN
org.apache.commons.vfs2.FileSystemException: Could not determine if file "sftp://admin:***@10.0.0.2/IN" is readable.
        at org.apache.commons.vfs2.provider.AbstractFileObject.isReadable(AbstractFileObject.java:1494)
      (...)
Caused by: com.jcraft.jsch.JSchException: Could not get the groups id of the current user (error code: -1)
     ... 12 more
```

It seems to be related to https://issues.apache.org/jira/browse/VFS-617

Have you seen this error before ?

**Suggested Labels:**
ESB;EI;VFS;SFTP

**Suggested Assignees:**

**Affected Product Version:**
6.4

**OS, DB, other environment details and versions:**    
WSO2 EI on Windows 10
SFTP on windows server

**Steps to reproduce:**
Create an inbound with file polling
```
<inboundEndpoint name="FTP_POLL" onError="ErrorSequence" protocol="file" sequence="InSeq" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
(...)
<parameter name="transport.vfs.FileURI">sftp://admin:admin@10.0.0.2/IN</parameter>
(...)
```

**Related Issues:**
It seems to be related to https://issues.apache.org/jira/browse/VFS-617

**Comment by dengrand** [comment]
FYI : adding "transport.vfs.AvoidPermissionCheck=true" as query parameter seems to resolve the issue : 
<parameter name="transport.vfs.FileURI">sftp://admin:admin@10.0.0.2/IN?transport.vfs.AvoidPermissionCheck=true</parameter>

**Comment by GDLMadushanka** [comment]
Closing the issue since docs are updated with the above property
