### ISSUE TITLE
Update Business Process profile's documentation

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#3726]
The Business Process tutorials and other docs need to be checked again after the following issue [1] is resolved.

[1] https://github.com/wso2/product-ei/issues/3724

**Comment by RukshiW** [comment]
In Progress. Tested the first two tutorials.

**Comment by sameeragunarathne** [comment]
@RukshiW is this fixed?

**Comment by RukshiW** [comment]
Only the first two tutorials were tested and no required changes were identified for them.

**Comment by sameeragunarathne** [comment]
@RukshiW can we close this issue then?

**Comment by abeykoon** [comment]
As issue is regarding project creation, if it worked for the first two, it will work for the others as well. As no doc changes needed, resolving the issue.
