### ISSUE TITLE
Allow extensible data contracts as input in the datamapper mediator

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/product-ei#3729]
**Description:**
When using XML data with the datamapper mediator, all the XML tags sent in the message body must be found in the input schema of the datamapper configuration. Else, an exception will be throwned.

When using JSON data, the behavior is different.

The following pull request will fix the datamapper so that both XML and JSON extra data will be ignored : https://github.com/wso2/carbon-mediation/pull/1209

**Comment by Nirothipan** [comment]
Fix merged https://github.com/wso2/carbon-mediation/pull/1209
