### ISSUE TITLE
Update the EI analytics documentation to use active-active deployment pattern

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-ei#3736]
**Description:**
Going forward, the recommended deployment pattern for EI analytics will be Active-Active deployment of SP. Since EI analytics is stateless and does not hold an in-memory state we can easily move to Active-active setup from MinHA setup. Active-Active setup is very easy to configure and highly scalable as well has it has a high performance.

We have to,
- Remove all reference to MinHA setup in EI analytics documentation
- Provide a complete guide similar to current MinHA guide on setting up and active-active setup.

**Comment by samgnaniah** [comment]
Closing this since the original issue is fixed. Please open a new issue if there are more changes to be made for this page.

https://docs.wso2.com/display/EI6xx/Clustering+the+Analytics+Profile
