### ISSUE TITLE
[Doc] Error in "Clustering the Analytics Profile" documentation

### ISSUE THREAD

**Issue by IrushiL** [wso2/product-ei#3740]
**Description:**
The subsection "Configuring high availability” of the "Clustering the Analytics Profile” documentation [1] contains 2 parameters with the same name and description example. This should be edited with the correct values.

Duplicated Parameter Name - "minEvictableIdleTimeInMillis"
Duplicated Description Example - "minEvictableIdleTimeInMillis : 120000"

**Related Links:**
[1] https://docs.wso2.com/display/EI6xx/Clustering+the+Analytics+Profile
[2] https://docs.wso2.com/display/EI640/Minimum+High+Availability+Deployment

**Suggested Labels:**
Type/Docs, 6.5.0, 6.4.0

**Affected Product Version:**
EI-6.5.0, EI-6.4.0

**Comment by samgnaniah** [comment]
This page has changed now and this section does not exist anymore. Please check if this is still relevant and reopen or update this issue.

https://docs.wso2.com/display/EI6xx/Clustering+the+Analytics+Profile
