### ISSUE TITLE
[EI Tooling] There is no indication of selection when a connector operation icon is selected

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3747]
**Description:**

When a user clicks on connector operation icon, there is no indication that it is selected. For mediator icons, when selected there is a frame indicating that it is selected. 

Please see screenshot below. 

![image](https://user-images.githubusercontent.com/4967046/56347656-636b7280-61e2-11e9-980d-d213690b65fa.png)

**Comment by abeykoon** [comment]
This seems to be a rendering issue. When canvas is scrolled it appears.

**Comment by abeykoon** [comment]
This issue is common for mediator icons as well.

**Comment by abeykoon** [comment]
We can select multiple icons by pressing and hold "CMD" button. However, the indication what is selected is important for the user.

**Comment by dakshika** [comment]
@abeykoon this is known issue. normally we expect user to do double click on mediator to open property pane. this is due to user needs to double click on datamapper connector. hence reduce the severity
