### ISSUE TITLE
[EI Tooling] MSDynamics365 connector init not working on tooling pallet

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3752]
**Description:**

Drag and drop MSDynamics365 connector "init" operation. 
You will see some log mediator icon is appearing. 

Please refer to below screenshot. 

![image](https://user-images.githubusercontent.com/4967046/56356981-f06cf680-61f7-11e9-8fae-ca5859392cc3.png)

**Comment by abeykoon** [comment]
And no mediator can be dragged on to the design after this.

**Comment by kesavany** [comment]
Unable to reproduce this with the latest EI tooling.
![Screenshot from 2019-05-02 11-57-07](https://user-images.githubusercontent.com/1311321/57059221-d6d8ae00-6cd1-11e9-8ca1-19d2cd99eb7d.png)
