### ISSUE TITLE
[Doc] Mandatory parameters are not indicated for connectors 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3753]
**Description:**
When connector operations are configured, it is useful to know what is mandatory and what is not. EI tooling does not indicate what is mandatory and what is not. 

By going through documentation and examples only we can comprehend what is mandatory.

**Comment by praveennadarajah** [comment]
This can not be done from the tooling level unless it comes from the connector side. At the moment required fields are not specified within the connector zip. As per now, we can mention the mandatory fields in all connector docs.
