### ISSUE TITLE
Connector input parameters are not validated 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3754]
**Description:**

Input parameters for connector operations are not validated. It seems, not of the inputs for the connector operations are validated by EI tooling. 

Ex: File connector - create operation - encoding - any value is accepted
      File connector - create operation - setPassive - only "true"/"false" is accepted. As an improvement, we can place a radio button and generate the configuration accordingly. In current implementation any string is accepted.

**Comment by abeykoon** [comment]
![image](https://user-images.githubusercontent.com/4967046/56357932-bcdf9b80-61fa-11e9-8a8b-824cfc536c6c.png)

**Comment by praveennadarajah** [comment]
We have to modify the Call Template mediator to support validation for connector attributes. This has to be done at the synapse level as an improvement.
