### ISSUE TITLE
[EI Tooling] Google firebase connector has weird icons and arrows not aligned 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3755]
Please refer to below screenshot

![image](https://user-images.githubusercontent.com/4967046/56358844-85262300-61fd-11e9-99b8-78031f830ee3.png)

**Comment by dakshika** [comment]
fixed in latest master 
<img width="809" alt="Screen Shot 2019-04-29 at 1 35 20 PM" src="https://user-images.githubusercontent.com/6497326/56883235-af8ca180-6a83-11e9-871b-6723e41ec367.png">
