### ISSUE TITLE
[Synapse] add unit testing framework 

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/product-ei#3756]
**Description:**
Provide a built-in way to execute a unit test against a given synapse configuration artifact such as sequence, proxy, api, local entry, endpoint.

**Comment by sajithaliyanage** [comment]
Fixes are added in 
https://github.com/wso2/wso2-synapse/pull/1297
https://github.com/wso2/product-ei/pull/3604
https://github.com/wso2/micro-integrator/pull/94

**Comment by Nirothipan** [comment]
The Synapse PR is merged and other two are approved. Hence closing .

**Comment by sajithaliyanage** [comment]
Added a user guide for the synapse unit testing framework in
https://github.com/wso2/micro-integrator/pull/116
https://github.com/wso2/product-ei/pull/3797

**Comment by sajithaliyanage** [comment]
Changed the synapse unit test default port to **9008** and removed setting default port in synapse side and added it to the bash and batch files in scripts. Fixes are added in
https://github.com/wso2/micro-integrator/pull/120
https://github.com/wso2/product-ei/pull/3799
https://github.com/wso2/wso2-synapse/pull/1332

**Comment by sajithaliyanage** [comment]
Removed synapse unit testing framework parameters from script files. Fixes are done in
https://github.com/wso2/micro-integrator/pull/126
https://github.com/wso2/product-ei/pull/3804

Changed starting parameter as java property in docs - 
https://github.com/wso2/micro-integrator/pull/127
https://github.com/wso2/product-ei/pull/3805
