### ISSUE TITLE
Logging configurations' Persist All Configuration Changes button not working as expected

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-ei#3760]
**Description:**
WUM updated WSO2 ESB-5.0.0
**Persist All Configuration Changes** 
Despite un-checking this upon clicking the update, this will always be checked after the update. Further, a change done in global log level seems to be persisted as the changed log level remains intact even after a restart.

**Affected Product Version:**
ESB-5.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
WUM updated WSO2 ESB-5.0.0
**Persist All Configuration Changes** 
Despite un-checking this upon clicking the update, this will always stay checked after the update. Further, a change done in global log level seems to be persisted as the changed log level remains intact even after a restart.

**Comment by GDLMadushanka** [comment]
Fixed with https://github.com/wso2/carbon-commons/pull/359
