### ISSUE TITLE
Error while building Product EI - One or more certificates rejected. Cannot proceed with installation

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3763]
**Description:**

EI build fails with error 

`Maven build fails with the error One or more certificates rejected. Cannot proceed with installation`

**Affected Product Version:**

EI 6.5.0 M5

**OS, DB, other environment details and versions:**   

Latest JDK version 

**Steps to reproduce:**

Build product-ei from source. You will get
*Maven build fails with the error One or more certificates rejected. Cannot proceed with installation*

**Reason**

WSO2 EI includes the MSF4J profile. That profile make use of an old version of the Eclipse Equinox framework that is signed with a certificate that is not trusted by recent versions of Java.

**Resolution**

you have to manually import the certificate to the Java certificate store.

In that case, you can check what certificate is missing from the certificate store with the following command started from the root of the Product EI source directory:

jarsigner -verify ./p2-profile/msf4j-profile/target/p2-repo/plugins/org.eclipse.equinox.ds_(version).jar -verbose -certs

For example, you need to download the certificate with thumbprint 97817950D81C9670CC34D809CF794431367EF474 from the DigiCert website (https://www.digicert.com/digicert-root-certificates.htm). To import it, you need to run the following command as root from your Java security directory (ex: /usr/lib/jvm/java-8-oracle/jre/lib/security/):

keytool -import -file GTECyberTrustGlobalRoot.crt -keystore cacerts

Note: The default password for the certificate store is changeit

**Comment by Caltalys** [comment]
You can try building it with jdk8 update 141

**Comment by Nirothipan** [comment]
Related issue https://github.com/wso2/product-ei/issues/1011

**Comment by abeykoon** [comment]
Now EI 6.6.0 version would not pack MSF4j. 
So this build issue will not occur.
