### ISSUE TITLE
[EI Tooling]Unable to add the connector from store

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#3774]
**Description:**
Unable to add connectors from the store.

**Affected Product Version:**
WSO2-Developer-Studio-6.5.0-m5 
and also tested with the pack from https://jenkins-support-ei.wso2.com/jenkins/view/Developer%20Studio/job/devstudio-tooling-ei-weekly-release/ as well.

**OS, DB, other environment details and versions:**    
Tested in macOS High Sierra 10.13.2 

**Steps to reproduce:**
1. Create an ESB solution/ESB config project.
2. Right click on the project and click Add or Remove connector.
3. Select 'Add connector' option and click next
4.  Getting the following error message when I click on "Add connector".
<img width="537" alt="Screen Shot 2019-04-23 at 12 26 03 PM" src="https://user-images.githubusercontent.com/1663756/56560939-6344eb80-65c3-11e9-93f8-18e261ac2128.png">

**Comment by prabushi** [comment]
Probably due to multiple tooling instances in the same machine. It is not allowed to have multiple instances as the Jetty server binds to the same port.
