### ISSUE TITLE
Json message is logged as XML when log mediator is used 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3775]
**Description:**

Affected version: 6.5.0 - M7

Steps to reproduce: 

1. Deploy following API and send a request. 

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/analytics" name="analyticsAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST GET">
        <inSequence>
            <log description="log" level="full">
                <property name="STATUS" value="Message Received"/>
            </log>
            <call>
                <endpoint key="testEP"/>
            </call>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>

```

2. Json is logged as follows 

`[2019-04-23 12:33:20,948] [EI-Core]  INFO - LogMediator To: /analytics, MessageID: urn:uuid:6fc6cced-9ac3-4270-a116-bfa9202ecde1 correlation_id : ca7b6f06-2e89-408f-9e1d-ecf47832b5b4, Direction: request, STATUS = Message Received, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><test>abc</test></jsonObject></soapenv:Body></soapenv:Envelope>`

**Comment by Nirothipan** [comment]
This is happening in all versions of EI . In ESB only it was logged as json. 
Seems this is done intentionally 
https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java#L206

**Comment by isudana** [comment]
Intended to fix a different issue[1] but causes this regression with [2]. 

[1] https://wso2.org/jira/browse/ESBJAVA-5202
[2] https://github.com/wso2/wso2-synapse/pull/768/files
