### ISSUE TITLE
[DOC] How to run analytics profile and how to configure is missing 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3776]
**Description:**

Referring : https://docs.wso2.com/display/EI640/Working+with+Analytics

There is no information on 

1. How to run analytic profile (dashboard and worker)
2. What is dashboard and what is worker
3. how to point WSO2 EI to the analytics servers.

**Comment by abeykoon** [comment]
Config steps are there under "Configuring the ESB to publish data to the Analytics profile". 
This needs to come top.

**Comment by praveennadarajah** [comment]
The above changes have been made in the doc [1] and need to be reviewed.

[1] https://docs.wso2.com/display/EI6xx/Publishing+ESB+Data+to+the+Analytics+Profile

**Comment by KasunAratthanage** [comment]
@nilminiwso2 This issue can be closed.
