### ISSUE TITLE
Update documentation on deprecated features

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3785]
We need to update the documentation in every page related to deprecated features with a note. 
Discussion on the list of deprecated features is available at architecture@wso2.org mailing list topic "Deprecated features in EI 6.5.0"

**Comment by keerthu** [comment]
Also we need to update the samples as well. For example we need to remove in and out mediator for the samples mentioned in the doc.

**Comment by samgnaniah** [comment]
Status: Everything updated expect samples that have In and Out Mediator.
