### ISSUE TITLE
Remove usages of depreciated endpoint tag, 'suspendDurationOnFailure'

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#3786]
**Description:**
There are several usages of the depreciated endpoint tag named 'suspendDurationOnFailure' [[1]](https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionFactory.java#L244). It has been replaced with the following synapse syntax.
`<suspendOnFailure>
    <initialDuration>20000</initialDuration>
    <progressionFactor>1.0</progressionFactor>
</suspendOnFailure>`

Need to correct all the following usages,
1. https://docs.wso2.com/display/EI6xx/Sample+154%3A+Load+Balancing+with+Proxy+Services
2. https://docs.wso2.com/display/EI6xx/Sample+752%3A+Load+Balancing+Between+3+Endpoints+With+Endpoint+Templates
3. https://docs.wso2.com/display/EI6xx/WSDL+Endpoint 
4. https://docs.wso2.com/display/EI6xx/Sample+52%3A+Using+Load+Balancing+Endpoints+to+Handle+Peak+Loads
5. https://docs.wso2.com/display/EI6xx/Sample+53%3A+Using+Failover+Endpoints+to+Handle+Peak+Loads

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed all these pages. Thanks @prabushi
