### ISSUE TITLE
Exception is thrown during conversion from JSON to XML when invalid xml characters present in JSON payload

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#3789]
**Description:**
When an invalid XML character is present in the JSON payload, an exception will be thrown when converting from JSON to XML.

**Suggested Labels:**
ESB 5.0.0

**Suggested Assignees:**

**Affected Product Version:**
ESB 5.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-ei/issues/2932

**Comment by ThishaniLucas** [comment]
Re-opening this issue since the kernel version is not upgraded to 4.4.41.

**Comment by GDLMadushanka** [comment]
Closing the issue since kernel upgraded
