### ISSUE TITLE
Java2WSDL script doesn't work as expected 

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#379]
Getting below issue, when run the ./java2wsdl.sh available on EI_HOME/bin folder

asankav@asankav-ThinkPad-T540p:~/servers/releasetest/ei/23/profile/ana/wso2ei-6.1.0-SNAPSHOT/bin$ ./java2wsdl.sh /home/asankav/servers/releasetest/ei/23/profile/ana/wso2ei-6.1.0-SNAPSHOT/samples/axis2Server/repository/services/SimpleStockQuoteService.jar
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

BUILD SUCCESSFUL
Total time: 0 seconds
Error: Could not find or load main class org.apache.ws.java2wsdl.Java2WSDL

**Comment by nandika** [comment]
Fixed https://github.com/wso2/product-ei/pull/434
