### ISSUE TITLE
Cannot use start or stop commands for profiles from bin folder

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3802]
**Description:**

It is not possible to execute the following commands.

```
./bin/business-process.sh start
./bin/broker.sh start
```

The above commands start process in the foreground rather than in the background.

Please note that it is possible to go inside the profile directories (wso2/business-process etc) and run the above commands (./bin/wso2server.sh start) which works fine.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2ei-6.5.0-m6

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run the ./bin/business-process.sh start in the root directory.

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Closing the issue since it's recommended to creates profiles in the production environment.
