### ISSUE TITLE
Unable to add endpoint as the clone target in management console

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#3812]
**Description:**
When trying to add an endpoint as a clone target, it rejects the input data and shows empty tags.

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.5.0 m7

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
![screenshot](https://user-images.githubusercontent.com/8251118/56934590-0e94f980-6b0a-11e9-9297-c95d58de3a6f.png)
Add an endpoint as the clone target and try to save

**Comment by sdkottegoda** [comment]
The reason why this happens is because the radio button gets deselected after adding an endpoint configuration. If we select the radio button prior to updating the target configuration, the endpoint will get saved as expected. Hence, lowering the priority.

**Comment by sdkottegoda** [comment]
@Nirothipan Any reason to change the severity to critical?

**Comment by Nirothipan** [comment]
Added as this will block the use of clone using management console . We Can remove if that is okay .

**Comment by GDLMadushanka** [comment]
Issue still exists

**Comment by Vathsan** [comment]
We have fixed the radio button getting deselected after adding an endpoint configuration in https://github.com/wso2/carbon-mediation/pull/1252. If we go to the source view after adding an endpoint (we do not need to select the radio button again prior to updating the target configuration) the endpoint gets saved as expected.

This issue gets reproduced if we go to the source view immediately after adding an endpoint as a clone target. But this will not happen if we click on the target (child element) and go to the source view 

![Large GIF (1038x720)](https://user-images.githubusercontent.com/29911181/57621903-2ceb0280-75aa-11e9-9666-0ef2b950ec7c.gif)
