### ISSUE TITLE
Output schema is getting loaded instead of input schema when load input from connector - EI Tooling

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#3825]
**Description:**
When try to load the input from connector, output schema from "output_schema" folder is getting loaded instead of input schema and also when load the output schema input_schema is getting loaded.

**Suggested Labels:**
EI Tooling

**Affected Product Version:**
Tooling 6.4.0

**Steps to reproduce:**
Insert the datamapper into the flow
Try to load the input schema from the connector. For example, use listQueues from AmazonSQS connector input schema to load the input schema. ListQueueResponse is getting loaded which is from output schema(https://github.com/wso2-extensions/esb-connector-amazonsqs/blob/master/src/main/resources/amazonSQS-queue/output_schema/listQueues.json).
Try to load the output schema from connector(listQueues from AmazonSQS connector). input schema is getting loaded(https://github.com/wso2-extensions/esb-connector-amazonsqs/blob/master/src/main/resources/amazonSQS-queue/input_schema/listQueues.json) as shown below:
<img width="867" alt="Screen Shot 2019-04-30 at 4 08 11 PM" src="https://user-images.githubusercontent.com/1663756/56956578-3adc6480-6b62-11e9-93fd-5af0bd48c905.png">

**Comment by dakshika** [comment]
@keerthu : Is this 6.4 or latest tooling ?
