### ISSUE TITLE
When stopping profiles, terminal process does not quit

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3828]
**Description:**

When you start and stop a profile (BPS / Broker etc), the terminal process does not exit completely and it halts after the line `[EI-Core]  INFO - CarbonServerManager Halting JVM`. We need to manually press enter to get the terminal new line.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Start a profile. (BPS / Broker etc)
2. Stop the server. (Ctrcl + C)
 Process halts and new line terminal does not appear.

**Related Issues:**

**Comment by arunans23** [comment]
**Workaround :** Go to [EI-HOME]/wso2/[profile-name]/bin and start the wso2server.sh script directly.

**Comment by GDLMadushanka** [comment]
Closing since it's recommended create separate profiles for production deployments.
