### ISSUE TITLE
Incorrect folder structure in screenshot for BPMN tutorials

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3835]
**Description:**

https://docs.wso2.com/display/EI6xx/Working+with+Service+Tasks#WorkingwithServiceTasks-CreatingtheMavenproject

In the above documentation, under the title **Creating the Java Package for the Maven Project** the screenshot shows that the source folder should be `HelloWorldServiceTask/src`. But it should be `HelloWorldServiceTask/src/main/java`

The same issue exists under **Creating the Java Class for the Maven Project**

**Suggested Labels:**

Type/Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Ibaqu** [comment]
Added new screenshots with the source folder correctly showing `HelloWorldServiceTask/src/main/java`

**Comment by GDLMadushanka** [comment]
closing the issue referring to the above comment

**Comment by arunans23** [comment]
Can we fix this in 6.5.0 doc as well?

**Comment by Ibaqu** [comment]
Done
