### ISSUE TITLE
Wrong type of form property in BPMN Rest Task tutorial

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3837]
**Description:**

https://docs.wso2.com/display/EI6xx/Working+with+REST+Tasks#WorkingwithRESTTasks-ConfiguringtheUserTask

In the above tutorial, under Configuring the User Task, Step 4, the type of the value should be 'long'  not 'enum'. In the screenshot it is properly shown, but it is wrong in the table data.

**Suggested Labels:**

Type/Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Ibaqu** [comment]
Changed data type to 'long' in Table
