### ISSUE TITLE
When creating a data service with input validation, 'Add Validator' button redirects to wrong page

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#3840]
**Description:**
When creating a data service with input validation using management console, clicking 'Add Validator' after selecting particular validator redirects to the wrong page and we get HTTP ERROR 400. 
But we can use the back button in the browser to get back to our configuration wizard with the added validator. 
The same thing happens when deleting a validator as well.

![image](https://user-images.githubusercontent.com/29911181/57073285-42387500-6cfe-11e9-938c-0f0035e6ebf0.png)

![image](https://user-images.githubusercontent.com/29911181/57073091-9e4ec980-6cfd-11e9-8613-dbaf303c7968.png)

**Suggested Labels:**
DSS
Type/UX

**Affected Product Version:**
EI 6.5.0-m7 pack

**Steps to reproduce:**
Follow the steps mentioned in the sample[1]. You will get the error at defining a query with an input validator step.

[1] https://docs.wso2.com/display/EI640/Validating+Input+Values+in+a+Data+Request

Note: This works fine in EI 6.4.0

**Comment by sdkottegoda** [comment]
@SangeethKarunaratne can you please check on this?

**Comment by Vathsan** [comment]
Similar problem occurs when deleting a rest resource as well.

![image](https://user-images.githubusercontent.com/29911181/57271474-3574a200-70ad-11e9-93a2-4fea49ec8698.png)
