### ISSUE TITLE
[Tooling]Main config fields for set httpStatusVariable, errorMessageVariable registration for bpmn rest task

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-ei#3846]
**Description:**
Add config properties to set the HTTP status, error message for the BPMN Rest Task in EI tooling

**Suggested Labels:**

**Suggested Assignees:**
Improvement

**Affected Product Version:**
EI 6.5.0 onwards

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/631

**Comment by sameeragunarathne** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-ei/issues/631
