### ISSUE TITLE
[Tooling] Payload factory arguments are not displayed in readable manner

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3848]
Environment: 

Windows:10

**Description:**
Add an expression to a payload factory argument. 
It is not formatted as per screenshot below. 

![image](https://user-images.githubusercontent.com/4967046/57121392-d6edb200-6d94-11e9-851d-619e48901a13.png)

**Comment by prabushi** [comment]
@SangeethKarunaratne will work on this.
