### ISSUE TITLE
[Tooling] Header mediator name pops up for an expression 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3849]
Environment: 

Windows 10

**Description:**
Please see the screenshot below. 
Should we take header name as an expression? 

![image](https://user-images.githubusercontent.com/4967046/57121680-b3c40200-6d96-11e9-8cb7-aea4c8d8b55a.png)

**Comment by abeykoon** [comment]
This should ideally load known headers like "To", "Action" (like properties) and allow for custom headers.

**Comment by prabushi** [comment]
Header name can be a HTTP header or a SOAP header. Therefore, it is supported as a namespace editors in both Tooling and [management console](https://docs.wso2.com/display/EI640/Header+Mediator).
