### ISSUE TITLE
Verify funcationality of EI cluster

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#3850]
**Description:**
Verify funcationality of the mediation profile of an EI cluster.

**Comment by Nirothipan** [comment]
Setup a 2 node cluster with MySQL DB and verified the following.

-  Scheduled Tasks.

**Comment by Nirothipan** [comment]
Encountered a port offset  issue in Internal APIs https://github.com/wso2/carbon-mediation/pull/1241
