### ISSUE TITLE
Wrong Menu name in BPEL tutorial

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#3864]
**Description:**

https://docs.wso2.com/display/EI6xx/Echoing+a+Message+Using+Correlation#EchoingaMessageUsingCorrelation-CreatingtheCorrelationSet

In the above documentation, under Creating the Correlation Set, Step 2, `In WSO2 EI Tooling under the BankLoanProcess menu` should change to `In WSO2 EI Tooling under the EchoCorrelationProcess` menu.

**Suggested Labels:**

Type/Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed. Thanks for reporting!
