### ISSUE TITLE
Redesign Expression Evalutor

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3866]
![image](https://user-images.githubusercontent.com/748819/57128896-7cfbe500-6db2-11e9-9700-bea09d7e4a06.png)

- Main purpose of this dialog box is to provide a UI to define an expression. So 
Dialog box needs to be renamed to "Expression selector" or similar.
- Defining the expression and evaluate an xml has to be separated out with clear borders. Priority should give to defining the expressions. 
- Namespaces section should belong to defining the expression section but not to evaluating section. 
- Evaluate button need to come before the Output.
- Output shouldn't be editable.

**Comment by dakshika** [comment]
We will work on this

**Comment by prabushi** [comment]
Related issue https://github.com/wso2/product-ei/issues/3911

**Comment by dilee** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/925
