### ISSUE TITLE
Update MicroIntegrator documentation for EI 6.5.0

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#3869]
The MicroIntegrator profile is moved out of the EI 6.5.0 distribution. This profile is going to be introduced as an independent distribution. 
Documentation needs to be updated on all the related changes for the Micro Integrator profile.

[1] https://docs.wso2.com/display/EI6xx/Working+with+the+Micro+Integrator

**Comment by Nirothipan** [comment]
There is an issue already reported on this https://github.com/wso2/micro-integrator/issues/140

**Comment by nilminiwso2** [comment]
Lets continue to use this git issue to track the impact on EI documentation. Will refer **wso2/micro-integrator#140** for details.

**Comment by nilminiwso2** [comment]
Completed the main release docs [1].

[1] https://docs.wso2.com/display/EI650/WSO2+Micro+Integrator
