### ISSUE TITLE
Add and update mysql cluster scripts

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#3870]
**Description:**
There are few updates to be done in EI mysql cluster scripts

- Since group replication has been introduced after MySql 5.7.17 version, its a must to have primary keys in all tables. So in cluster scripts for mysql 5.7+ should be updated accordingly.

- Above mentioned update should be done for BPS sql 5.7 cluster scripts as well.

- Clustering scripts for mysql 5.7+ are only available from EI 6.2.0. Mysql 5.7+ cluster scripts should be added for EI 6.0.0, EI 6.1.0, EI 6.1.1.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
All EI Products

**OS, DB, other environment details and versions:**    
Mysql

**Steps to reproduce:**

**Related Issues:**

**Comment by sameeragunarathne** [comment]
This has been fixed with the latest kernel release since the mysql scripts are shipped with 5.7 syntax by default
