### ISSUE TITLE
[Tooling] Image tag name should be optional 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3873]
**Description:**

When creating a docker image from tooling the tag should be optional. 
If not given, it should assume "latest"

Currently, it is a mandatory field.

**Comment by abeykoon** [comment]
@a5anka , any thoughts on this?

**Comment by a5anka** [comment]
I suppose this is the tag of the resulting docker image. Yes. Even when you use `docker build` tag is optional.
