### ISSUE TITLE
Data service REST resources invocation url issue

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3880]
**Description:**

Steps to reproduce

1. Deploy below data service

     - make sure you create below table with proper permissions 

+-------+-------+------------+
| name  | field | hospital   |
+-------+-------+------------+
| David | skin  | Clemency   |
| Paul  | heart | Pine Vally |
| Brown | eyes  | Pine Vally |
+-------+-------+------------+

```
<data name="findDoctor" serviceGroup="" serviceNamespace="">
    <description/>
    <config id="doctorInformationStore">
        <property name="org.wso2.ws.dataservice.user">wso2</property>
        <property name="org.wso2.ws.dataservice.password">wso2</property>
        <property name="org.wso2.ws.dataservice.protocol">jdbc:mysql://localhost:3306/doctors</property>
        <property name="org.wso2.ws.dataservice.driver">com.mysql.jdbc.Driver</property>
    </config>
    <query id="queryDoctor" useConfig="doctorInformationStore">
        <sql>Select name, hospital from doctor where field=?</sql>
        <param name="field" paramType="SCALAR" sqlType="STRING" type="IN"/>
        <result element="doctors" rowName="doctor">
            <element column="name" name="name" xsdType="xs:string"/>
            <element column="hospital" name="hospital" xsdType="xs:string"/>
        </result>
    </query>
    <resource method="GET" path="doctor/{field}">
        <call-query href="queryDoctor">
            <with-param name="field" query-param="field"/>
        </call-query>
    </resource>
</data>
```

2. Invoke the service with following GET

`http://Hasithas-MacBook-Pro.local:8280/services/findDoctor/doctor/skin`

This is not working. 

To invoke this you need to use 

`http://Hasithas-MacBook-Pro.local:8280/services/findDoctor.HTTPEndpoint/doctor/skin`

Here '`HTTPEndpoint`' part is additional and it is not intuitive for a user.

**Comment by GDLMadushanka** [comment]
This is working when correctly invoked with a query parameter 
Ex:  http://lahiru-ThinkPad-X1-Carbon-4th:8280/services/ds1/test?age=30
