### ISSUE TITLE
Incorrect response formatting for JMS-based APIs

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-ei#3889]
**Description:**
When the client sends a request using a certain content-type (for example application/json) and the JMS producer responds a different content-type (for example application/xml). The response it converted to application/json and sent to the client where as the expected would be to send as application/xml.

**Affected Product Version:**
EI 6.4

**Comment by prasa7** [comment]
Public fixes were done using the following PRs

https://github.com/wso2/wso2-synapse/pull/2040
https://github.com/wso2/wso2-axis2-transports/pull/331
