### ISSUE TITLE
[Docs] [Configuring with HornetQ] Referring old jar 

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#389]
When referring docs configuring HornetQ, it refers hornet-all.jar. But when its comes to JMS 2.0 features like shared subscription [2], it refers latest hornet-all-new.jar. This can be conflicting and please update [1] with latest jar (hornet-all-new.jar)

[1] https://docs.wso2.com/display/EI600/Configure+with+HornetQ
[2] https://docs.wso2.com/display/EI600/Shared+Topic+Subscription+with+WSO2+EI

**Comment by praneesha** [comment]
Updated the following sentence in docs of EI 6.0.0, 6.1.0 & ESB 5.0.0 with the hornet-all-new.jar file attachment linked from it.

For an example, see [1].

"Download the hornet-all-new.jar﻿﻿ file and copy it into the <EI_HOME>/lib/ directory."

[1] https://docs.wso2.com/display/ESB500/Configure+with+HornetQ
