### ISSUE TITLE
[Doc] Sample Queries webpage is not loading properly

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#3890]
**Description:**
Sample 10: Defining named parameters and Sample 11: Grouping data into complex elements mentioned in [1] is not loading properly.

[1] https://docs.wso2.com/display/EI6xx/Sample+Queries

![image](https://user-images.githubusercontent.com/29911181/57232728-d70edb80-703a-11e9-811c-3a5db5b7e82c.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Fixed in 6xx doc space https://docs.wso2.com/display/EI6xx/Sample+Queries
