### ISSUE TITLE
Design to Source view removes the route while adding Conditional Router

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#3891]
**Description:**
Create a Conditional Router [1] via UI.
Add the route into the router and add the expression in the design view and then switch to source view. The route config will be removed in the source.
<img width="775" alt="Screen Shot 2019-05-06 at 9 01 02 PM" src="https://user-images.githubusercontent.com/2033965/57236416-a59a0e00-7042-11e9-9b46-931315dab4ea.png">

Please note that we couldn't create the proxy service with Conditional Router mediator via the design view.
<img width="1158" alt="Screen Shot 2019-05-06 at 9 09 22 PM" src="https://user-images.githubusercontent.com/2033965/57236665-3a9d0700-7043-11e9-85f0-14fc1ae457e6.png">

[1] https://docs.wso2.com/display/EI6xx/Conditional+Router+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by malakaganga** [comment]
Deprecated
