### ISSUE TITLE
[EI][Rule mediator]Content changed with additional namespaces

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#3893]
**Description:**
Rule mediator content is getting changed with additional namespaces

**Steps to reproduce:**

- Add rule mediator via design view(Use the sample from https://docs.wso2.com/display/EI6xx/Sample+600+%3A+Simple+Message+Transformation+-+Rule+Mediator+for+Message+Transformation).

- Save and close it.

- Re-open the sequence and switched to source view. Content has changed with some additional namespaces as below. 

```
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="main" xmlns="http://ws.apache.org/ns/synapse">
    <in>
        <brs:rule xmlns:brs="http://wso2.org/carbon/rules">
        <brs:source xpath="">soapBody</brs:source>
        <brs:target action="replace" resultXpath="//m0:symbol"
            xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol">soapBody</brs:target>
        <brs:ruleSet>
            <brs:properties/>
            <brs:rule resourceType="regular" sourceType="inline"><![CDATA[                                                package SimpleRoutingRules;
 
                        rule InvokeIBM
                        when
                        symbol: String()
                        eval( symbol.equals("MSFT") || symbol.equals("SUN") )
                        then
                        update(drools.getWorkingMemory().getFactHandle(symbol),"IBM");
                        end]]></brs:rule>
        </brs:ruleSet>
        <brs:input namespace="http://services.samples" wrapperElementName="getQuote">
            <brs:fact elementName="symbol"
                namespace="http://services.samples"
                type="java.lang.String"
                xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol/child::text()"/>
        </brs:input>
        <brs:output namespace="http://services.samples" wrapperElementName="getQuote">
            <brs:fact elementName="symbol"
                namespace="http://services.samples" type="java.lang.String"/>
        </brs:output>
    </brs:rule>
    <send>
            <endpoint>
                <http uri-template="http://localhost:9000/services/SimpleStockQuoteService"/>
            </endpoint>
        </send>
    </in>
    <description>The main sequence for the message mediation - this sequence will get invoked if there is no other        artifact to process the message</description>
</sequence>
```

**Related Issues:**
https://github.com/wso2/product-ei/issues/3495

**Comment by keerthu** [comment]
When we add the sequence via source view and re-open the sequence it has changed as follows:
`<?xml version="1.0" encoding="UTF-8"?>
<sequence name="testSeq" xmlns="http://ws.apache.org/ns/synapse">
    **<in>
        <brs:rule xmlns:brs="http://wso2.org/carbon/rules">
            <brs:source>soapBody</brs:source>
            <brs:target action="replace" resultXpath="//m0:symbol"
                xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol">soapBody</brs:target>
            <brs:ruleSet>
                <brs:properties/>
                <brs:rule resourceType="regular" sourceType="inline"><![CDATA[
                         package SimpleRoutingRules;
 
                        rule InvokeIBM
                        when
                        symbol: String()
                        eval( symbol.equals("MSFT") || symbol.equals("SUN") )
                        then
                        update(drools.getWorkingMemory().getFactHandle(symbol),"IBM");
                        end
                        
                    ]]></brs:rule>
            </brs:ruleSet>
            <brs:input namespace="http://services.samples" wrapperElementName="getQuote">
                <brs:fact elementName="symbol"
                    namespace="http://services.samples"
                    type="java.lang.String"
                    xmlns:m0="http://services.samples" xpath="//m0:getQuote/m0:request/m0:symbol/child::text()"/>
            </brs:input>
            <brs:output namespace="http://services.samples" wrapperElementName="getQuote">
                <brs:fact elementName="symbol"
                    namespace="http://services.samples" type="java.lang.String"/>
            </brs:output>
        </brs:rule>
        <send>
            <endpoint>
                <address uri="http://localhost:9000/services/SimpleStockQuoteService"/>
            </endpoint>
        </send>
    </in>**
    <out>
        <send/>
    </out>
</sequence>
`

**Comment by dinuish94** [comment]
This is not an issue. The namespaces are required for the rule mediator.
