### ISSUE TITLE
Unused expression option in Fault mediator

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#3898]
**Description:**
The **Detail** attribute in **Fault** mediator is provided with two options, value and expression, via the design view in management console.
![fault-mediator](https://user-images.githubusercontent.com/5234623/57270284-4ec71f80-70a8-11e9-803e-3a235b07c391.png)

Even though we add an expression, it will not set any value for the source. We can remove both value and expression options for 'Detail' as it always has a value.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2ei-6.5.0-m7-SNAPSHOT.zip

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
However, we have defined the expression option for POX type but not for SOAP 1.1 and SOAP 1.2 in the documentation.

**Comment by GDLMadushanka** [comment]
It's working when we change the proxy service manually.
Ex:-   <makefault version="soap11">
                <code xmlns:soap11Env="http://schemas.xmlsoap.org/soap/envelope/" value="soap11Env:VersionMismatch"/>
                <reason expression="$body//a/text()"/>
                <role/>
                <detail expression="$body//b/text()"/>
            </makefault>
