### ISSUE TITLE
[DOC] Update docs with feature installation details

### ISSUE THREAD

**Issue by MalshaL** [wso2/product-ei#3901]
**Description:**
In docs for [CXF WS-RM Inbound Protocol](https://docs.wso2.com/display/EI6xx/CXF+WS-RM+Inbound+Protocol) [1]:

- The link for 'Installing Features'  is not redirecting to a specific page. The document should be redirecting to new documentation with the content of page [2].

- The required feature id and version of the feature should be mentioned in [1]. The feature id and version of the latest feature is identified as:

            Id: org.wso2.carbon.inbound.endpoints.ext.wsrm.feature.group
            Version: 4.6.6

[1] https://docs.wso2.com/display/EI6xx/CXF+WS-RM+Inbound+Protocol
[2] https://docs.wso2.com/display/EI600/Installing+Features+Using+POM+Files

**Suggested Labels:**
Type/Docs, 6.5.0

**Comment by Nirothipan** [comment]
Please check the other doc space also

**Comment by menuka94** [comment]
The documentation for CXF WS-RM Inbound Protocol does not contain adequate information on how to invoke the endpoint or how to test out the configurations.

P.S. This is a good example: https://buddhimawijeweera.wordpress.com/2015/09/05/reliable-messaging-with-wso2-esb/
