### ISSUE TITLE
CApp is getting deployed with faulty services

### ISSUE THREAD

**Issue by pramodya1994** [wso2/product-ei#3902]
**Description:**
When deploying a CApp having a faulty service (Tested with missing WSDL), for the first time EI will throw an error and revert the deploying CApp as expected (expected behavior). But if we deploy this same CApp having a faulty service, we can see it is getting deployed successfully without any error (wrong behavior). If we deploy CApp again EI will throw an error and revert deploying CApp (expected behavior) and if we deploy CApp again it will be deployed successfully without any error (wrong behavior). This will continue as a loop.

**Suggested Labels:**
6.4.0, Priority/Normal, Type/Bug

**Affected Product Version:**
6.4.0 

**Steps to reproduce:**
(1) Create a CApp with the following proxy.
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="sample_proxy" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <endpoint name="sample_ep" template="sample_endpoint_template_v1" uri="http://sample/wsdl/uri"/>
        <inSequence/>
        <outSequence>
            <sequence key="sendFaultLogSequence"/>
        </outSequence>
        <faultSequence onError="sample_fatalerror">
            <sequence key="sample_esberror"/>
        </faultSequence>
    </target>
    <publishWSDL preservePolicy="true" uri="http://sample/wsdl/uri?wsdl"/>
    <parameter name="eam_provider">A1155</parameter>
    <parameter name="useOriginalwsdl">true</parameter>
</proxy>
```
(2) Start integrator and deploy the CApp.
(3) You will get the dployment error as expected.
(4) Deploy the CApp again.
(5) You will get logs saying CApp has sucessfully deployed (wrong behavior).

**Comment by sameerawickramasekara** [comment]
Fixed in master by enclosing the command in try-catch block and removing the proxy then and there [Code ](https://github.com/wso2/wso2-synapse/blob/1dbf17573d88f278a4548dc56f5432ebd9b45353/modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java#L109)
Hence closing the issue.
