### ISSUE TITLE
[EI Tooling] Some values are not persisting in Secure WebSocket Inbound Protocol

### ISSUE THREAD

**Issue by praveennadarajah** [wso2/product-ei#3906]
**Description:**
Steps to reproduce:
1. Copy the below example XML in source view
https://docs.wso2.com/display/EI611/Secure+WebSocket+Inbound+Protocol

2. Switch to design view and back to source view. We can see some of the parameters are not persisting in source view.

**Comment by dinuish94** [comment]
Updated Synapse configuration in docs by adding the namespace.

`<inboundEndpoint name="SecureWebSocketEP" onError="fault" protocol="wss" sequence="TestIn" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
    <parameters>
        <parameter name="inbound.ws.port">9091</parameter>
        <parameter name="ws.client.side.broadcast.level">0</parameter>
        <parameter name="ws.outflow.dispatch.sequence">TestOut</parameter>
        <parameter name="ws.outflow.dispatch.fault.sequence">fault</parameter>
        <parameter name="wss.ssl.key.store.file">repository/resources/security/wso2carbon.jks</parameter>
        <parameter name="wss.ssl.key.store.pass">wso2carbon</parameter>
        <parameter name="wss.ssl.trust.store.file">repository/resources/security/client-truststore.jks</parameter>
        <parameter name="wss.ssl.trust.store.pass">wso2carbon</parameter>
        <parameter name="wss.ssl.cert.pass">wso2</parameter>
        <parameter name="ws.use.port.offset">false</parameter>
    </parameters>
</inboundEndpoint>`
