### ISSUE TITLE
[EI Tooling] Vertical Scrolling does not work properly on Windows

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3909]
**Environment** 

Windows 

**Description:**

When scrolled through properties of a proxy service, vertical scrolling does not work properly on Windows. 

![image](https://user-images.githubusercontent.com/4967046/57314694-ca0fec00-710f-11e9-9e2a-2cf430622f05.png)

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/931
