### ISSUE TITLE
Sequence Template unusable

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3910]
![image](https://user-images.githubusercontent.com/748819/57315214-c335a900-7110-11e9-8414-370dfa5c2b26.png)

UI does not have a way to define parameters.

**Comment by prabushi** [comment]
Fixed value preserving issues in https://github.com/wso2/devstudio-tooling-esb/pull/908/commits/42e93b6f6a1de522800492a850566fdcbbf3da54
