### ISSUE TITLE
[EI Tooling] Expression window is not formatted properly

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3911]
**Description:**

1. Input has type "XML" and "Json". But what we input is an expression. It can be

1.1 - XPATH
1.2 - Json Eval expression
1.3 - synapse expression ($ctx: PROPERTY_NAME)

We can only evaluate a XPATH or a Json eval expression. We cannot do that for  synapse expressions. Also evaluation needs to be optional. 

![image](https://user-images.githubusercontent.com/4967046/57316052-8ff41980-7112-11e9-9686-0aa71b0f8fd8.png)

**Comment by dilee** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/925
