### ISSUE TITLE
[EI Tooling] Error while saving the configuration

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#3923]
**Description:**
Unable to save the configuration. It says that the file system is read-only.
<img width="1058" alt="Screen Shot 2019-05-08 at 11 25 58 AM" src="https://user-images.githubusercontent.com/2033965/57352906-71c70180-7184-11e9-8e12-892b26f4e363.png">

OS: MacOS
Note: When we start the tooling via the terminal it allows to save the config.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
This is because of the signing issue in Mac distribution. This will be resolved once we create the dmg with the GA release pack.

**Comment by dakshika** [comment]
Also application needs to be placed inside the application folder on mac.
