### ISSUE TITLE
Create FAQ doc for ei tool

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#3928]
**Description:**
Create an FAQ with the issues that customer could face frequently and add the following question since it is almost definite that this issue might occur.

- Question: MY project view suddenly went missing, how can I get it back?
- Answer: Navigate to `Window -> Perspective -> Reset Perspective` from the toolbar.

**Comment by samgnaniah** [comment]
Added this to the tooling troubleshooting documentation for now.

https://docs.wso2.com/display/EI6xx/Tooling+Troubleshooting+Guide
