### ISSUE TITLE
[Doc] Include from where the zookeeper should be started

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3930]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Sample+904%3A+Inbound+Endpoint+Kafka+Protocol+Sample
Please update the location of where the zookeeper should be started. It should be 
<Kafka_home>
```
bin/zookeeper-server-start.sh config/zookeeper.properties
```

**Comment by samgnaniah** [comment]
Fixed.
