### ISSUE TITLE
Error occurs when the zookeeper starts

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3931]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Sample+904%3A+Inbound+Endpoint+Kafka+Protocol+Sample

Steps to reproduce: 
1. Do the prerequisites in the document. 
2. Start the zookeeper server. 
```
bin/zookeeper-server-start.sh config/zookeeper.properties
```

Expected: zookeeper should be started
Actual: It gets the following log. 
`[2019-05-08 17:15:21,896] INFO Got user-level KeeperException when processing sessionid:0x16a973ab98e0000 type:create cxid:0x1a zxid:0xfffffffffffffffe txntype:unknown reqpath:n/a Error Path:/controller Error:KeeperErrorCode = NodeExists for /controller (org.apache.zookeeper.server.PrepRequestProcessor)`

**Comment by arunans23** [comment]
According to [Stackoverflow](https://stackoverflow.com/questions/43559328/got-user-level-keeperexception-when-processing), this is a known issue in Kafka and zookeeper. Even though the error is getting printed, Kafka works as expected.

I don't think we need to have an issue regarding this on our product.

**Comment by malakaganga** [comment]
Closed according to above comment
