### ISSUE TITLE
[Tooling] Developer studio - unable to add SQL statement for DB Lookup mediator / DB Report mediator

### ISSUE THREAD

**Issue by tharinduwijewardane** [wso2/product-ei#3936]
**Description:**
![image](https://user-images.githubusercontent.com/1345465/57374780-53c7c400-71b9-11e9-9c02-e5b5165b3ad8.png)

**Steps to reproduce:**
1. Add DB Lookup mediator
2. Click on + button to add a SQL statement
3. Add a simple SQL query
4. Click finish button 
The query is not getting saved

**Comment by prabushi** [comment]
@SangeethKarunaratne will work on this.
