### ISSUE TITLE
[EI-Tooling] InboundEndpoint Configurations do not persist

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#3938]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17300424/57377138-5200ff00-71bf-11e9-9481-e3144263beed.gif)
**Description:**
WebSocket Inbound Endpoint configurations do not get persisted.

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.5.0-m7

**OS, DB, other environment details and versions:**    
macOS Mojave 10.14.4

**Steps to reproduce:**
1. Create a new WebSocket Inbound Endpoint in EI Tooling
2. Change to the source view and copy/paste the configuration in the [WebSocket Inbound Protocol Documentation](https://docs.wso2.com/display/EI6xx/WebSocket+Inbound+Protocol)
3. Save the file
4. Change to the Design View
5. Change back to the Source View

**Related Issues:**
https://github.com/wso2/product-ei/issues/3906

**Comment by menuka94** [comment]
Replacing just the ```<parameter></parameter>``` element will persist the configuration, though.

**Comment by dinuish94** [comment]
Should contain the namespace. Updated the docs with the following configuration.

`<inboundEndpoint name="WebSocketListenerEP" onError="fault" protocol="ws" sequence="TestIn" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
  <parameters>
     <parameter name="inbound.ws.port">9091</parameter>
     <parameter name="ws.outflow.dispatch.sequence">TestOut</parameter>
     <parameter name="ws.client.side.broadcast.level">0</parameter>
     <parameter name="ws.outflow.dispatch.fault.sequence">fault</parameter>
  </parameters>
</inboundEndpoint>`
