### ISSUE TITLE
[Doc] Correction in Sample 5

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#3939]
**Description:**
Fault mediator configuration in [Sample 5](https://docs.wso2.com/display/EI6xx/Sample+5%3A+Creating+SOAP+Fault+Messages+and+Changing+the+Direction+of+a+Message) should be corrected as below.
```
            <makefault version="soap12">
                <code value="soap12Env:Receiver" xmlns:soap12Env="http://www.w3.org/2003/05/soap-envelope"/>
                <reason expression="get-property('ERROR_MESSAGE')"/>
            </makefault>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by samgnaniah** [comment]
Fixed.

https://docs.wso2.com/display/EI6xx/Sample+5%3A+Creating+SOAP+Fault+Messages+and+Changing+the+Direction+of+a+Message
