### ISSUE TITLE
Debugger Improvements

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3945]
- We need to switch back to the original perspective when debugging is stopped
- We need to terminate the running micro integrator instance when debugging is stopped

**Comment by ThishaniLucas** [comment]
Adding to the issue:
Cannot change default ports of the MicroEI debug profile. Although we edit the debug configuration and change the ports, still the older ports get effective. 

![debug](https://user-images.githubusercontent.com/8208020/57508413-141aec80-731f-11e9-9b9d-57f4f33a143c.png)

**Comment by dakshika** [comment]
@ThishaniLucas : this one is for internal embeded Profile. if you change ports this won't work. so you need to create your own profile for external MEI

**Comment by a5anka** [comment]
Maybe we need to improve UX not to show port details since this is embedded profile.
