### ISSUE TITLE
Mediator icons are not well aligned with arrows

### ISSUE THREAD

**Issue by Maninda** [wso2/product-ei#3948]
**Description:**
When a mediator is placed in a proxy service, arrows to the mediator and out from it, are not pointed to the mediator icon to the center of the icon and short in length. There is a larger space between arrow start/end with the mediator icons.
![arrow_not_aligned](https://user-images.githubusercontent.com/1393891/57430458-612e8e00-724d-11e9-884a-26fe1a72432d.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Add a mediator to a proxy service in EI Tooling. Screenshot is attached.

**Related Issues:**

**Comment by dakshika** [comment]
this was a UXD. so no need to center on icon.
