### ISSUE TITLE
A single mediator cannot be saved without completing others

### ISSUE THREAD

**Issue by Maninda** [wso2/product-ei#3952]
**Description:**
When few mediators are added to a proxy service (2 Log mediators and one Data Mapper mediator) and once one log mediator is configured and saved an error comes that another mediator configurations is empty. ("Data Mapper configuration is empty.")

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Explained in the Description.

**Related Issues:**

**Comment by prabushi** [comment]
This is the default behaviour of data mapper mediator. This error popup message comes only for the data mapper mediator to imply the user that he/she should double click on the mediator and create it's configuration via the data mapper editor.
