### ISSUE TITLE
Data Mapper Screenshots are outdated in docs

### ISSUE THREAD

**Issue by Maninda** [wso2/product-ei#3954]
**Description:**
Data Mapper screenshots are outdated in document https://docs.wso2.com/display/EI6xx/Data+Mapper+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
Updated the screenshots in 6.5.0 and 6.x.x.

[1] https://docs.wso2.com/display/EI650/Data+Mapper+Mediator
[2] https://docs.wso2.com/display/EIxx/Data+Mapper+Mediator
