### ISSUE TITLE
[EI Tooling] Vertical Scrolling does not work properly on Mac

### ISSUE THREAD

**Issue by IrushiL** [wso2/product-ei#3959]
**Description:**
Vertical scrolling in the Properties tab is sometimes unresponsive and not working properly on Mac.

<img width="1680" alt="Screen Shot 2019-05-09 at 12 09 41 PM" src="https://user-images.githubusercontent.com/17268934/57432384-570f8e00-7253-11e9-9c07-bf9d5c015de3.png">

**Suggested Labels:**
EI Tooling, 6.5.0

**Affected Product Version:**
Integration Studio 6.5.0

**Environment:**    
Mac

**Related Issues:**
https://github.com/wso2/product-ei/issues/3909

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/devstudio-tooling-esb/pull/931
