### ISSUE TITLE
[EI 6.1]Sample wsdl path should be corrected according to the new file structure in document samples

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#396]
Sample wsdl path should be corrected according to the new file structure in document samples.

https://docs.wso2.com/pages/viewpage.action?spaceKey=EI610&title=Sample+150%3A+Introduction+to+Proxy+Services

        <publishWSDL uri="file:repository/samples/resources/proxy/sample_proxy_1.wsdl"/>
   path should be samples/service-bus/resources/proxy/sample_proxy_1.wsdl

**Comment by ushanib** [comment]
Please fix all the occurrences of sample_proxy_1.wsdl and sample_proxy_2.wsdl in all samples

**Comment by ushanib** [comment]
All the referred resources path for the artifacts in wso2ei-6.1.0-SNAPSHOT/samples/service-bus/resources should be updated for the correct location.

**Comment by praneesha** [comment]
Added the following note in the Samples section in [1].

"Note that WSO2 EI is shipped with the following changes to what is mentioned in this documentation:
<PRODUCT_HOME>/repository/samples/ directory that includes all Integration profile samples is changed to <EI_HOME>/samples/service-bus/resources/.
<PRODUCT_HOME>/repository/samples/resources/ directory that includes all artifacts related to the Integration profile samples is changed to <EI_HOME>/samples/service-bus/resources/."

[1] https://docs.wso2.com/display/EI610/Integration+Profile+Samples
