### ISSUE TITLE
[EI Tooling] Sequence selected is not updated in source view (xml)

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3964]
**Description:**

1. Define a RabbitMQ inbound EP 
2. Update the sequence using "static reference key" in properties panel 
3. It is not set to the source. Instead it is set as "Sequence"

![image](https://user-images.githubusercontent.com/4967046/57440888-72d05f80-7266-11e9-8853-9082aa8dbe16.png)

**Comment by dinuish94** [comment]
Related issue: #3961
