### ISSUE TITLE
Adding Rabbitmq jar file is missing as a step in documentation 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3968]
**Description:**

Documentation page : https://docs.wso2.com/display/EI640/RabbitMQ+AMQP+Transport

To try this, we need to copy RabbitMQ client jar file into [EI_HOME]/lib folder. Downloaded from 
[1]. 

[1]. https://www.rabbitmq.com/java-client.html

**Comment by Ibaqu** [comment]
Added an extra step to 'Configuring the RabbitMQ AMQP Transport ; 
"Download the `amp-client-5.7.0.jar` and copy it into `<EI_HOME>/lib` folder"

Link redirects to rabbitmq java-client page to download the latest jar

**Comment by Ibaqu** [comment]
Change applied to 
- EI 640 : https://docs.wso2.com/display/EI640/RabbitMQ+AMQP+Transport
- EI 650 : https://docs.wso2.com/display/EI650/RabbitMQ+AMQP+Transport
and EI 6XX : https://docs.wso2.com/display/EI6xx/RabbitMQ+AMQP+Transport
