### ISSUE TITLE
Integration Studio menu cleanups 

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3971]
In the Integration Studio menu item,
- Remove WSO2 Plugin project
- Move Check for Updates to Help Menu
- Since we will end up in just Getting Started, move Getting Started as the Top menu item and remove Integration Studio menu

In the Help menu item,
- Remove eclipse check for updates
- Remove Install new software..

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/developer-studio/commit/33a9f8d0ef1f7830afe1c17836b7703e4e6b6c4d, https://github.com/wso2/developer-studio/commit/66e684bc51c10f719af75c4d4365a876c354b8a3
