### ISSUE TITLE
[EI Tooling] Null pointer while entering payload factory arguments 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3978]
**Description:**

1. Add a payload factory 
2. Add a parameter. 

Type - value
Value - type a value and backspace it until you delete all. Upon deleting last character you will receive below issue.

![image](https://user-images.githubusercontent.com/4967046/57467049-6ddbd200-729f-11e9-8b4e-db9b6683545f.png)

**Comment by prabushi** [comment]
Fixed in the latest build.
