### ISSUE TITLE
PayloadFactory has invalid evaluator

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#3979]
![image](https://user-images.githubusercontent.com/748819/57468389-f8bdcc00-72a1-11e9-9487-1325288fdbf5.png)
There is no evaluator called "text" in the runtime

**Comment by prabushi** [comment]
On hold as [document](https://docs.wso2.com/display/EI6xx/PayloadFactory+Mediator) contains 'text' evaluator for property argument expression.
