### ISSUE TITLE
[EI Tooling] Wizard issues on Windows 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3986]
**Platform**

Windows 10

**Description:**

Following issues were observed when loading expression view for properties on Windows. 

![Capture11](https://user-images.githubusercontent.com/4967046/57513770-a83f8080-732c-11e9-862a-ddd2db5f04b7.PNG)
![Capture13](https://user-images.githubusercontent.com/4967046/57513777-ad9ccb00-732c-11e9-9def-ebd39f05151f.PNG)
![Capture12](https://user-images.githubusercontent.com/4967046/57513789-b1305200-732c-11e9-8d3b-86b29ee6d2d4.PNG)

**Comment by dilee** [comment]
Fixed in:
-  https://github.com/wso2/devstudio-tooling-esb/pull/934
- https://github.com/wso2/devstudio-tooling-esb/commit/96ed20bc5c92e988b03a725931a6e2fa7ac6b681
