### ISSUE TITLE
[EI Tooling] drag and drop does not work inside filter mediator 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3988]
**Description:**

Inside a filter mediator, when other mediators are dragged and dropped they get broken and config not preserved. 

![Capture14](https://user-images.githubusercontent.com/4967046/57517445-7a5e3a00-7334-11e9-946b-3d0ecc8150ad.PNG)

**Comment by abeykoon** [comment]
What if we added a filter mediator inside another filter mediator ?

**Comment by dilee** [comment]
This issue is not reproducible and intermittent.

**Comment by dakshika** [comment]
similar issue https://github.com/wso2/product-ei/issues/4037

**Comment by rosensilva** [comment]
Cannot reproduce in the latest Integration Studio 6.5.0
