### ISSUE TITLE
[EI 6.1][Tooling] Developer studio dashboard should have a separate section as Integration server with integrator products

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#399]
Developer studio dashboard should have a separate section as Integration server with integrator products.

Currently it has different sub sections as before.

ESB, DSS etc

![screenshot from 2017-03-28 14-51-18](https://cloud.githubusercontent.com/assets/12966170/24398181/437bf362-13c6-11e7-848d-1c9d7686e944.png)

**Comment by prabushi** [comment]
We have restructured the Developer Studio 6.2.0 dashboard as follows. We have removed the Integration project, ESB Config Project, etc. and categorized artifacts under separate EI profiles.
![dashboard](https://user-images.githubusercontent.com/5234623/37466472-db291bae-2883-11e8-8da2-95eb74d4d17d.png)
.
