### ISSUE TITLE
[Doc]Typo error in Property Mediator sample

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#3996]
**Description:**
`<property name="symbol"
    expression="fn:concat("Normal Stock - ', //m0:getQuote/m0:request/m0:symbol)"
    xmlns:m0="http://services.samples/xsd"/>`

should be changed as,(double quote needs to be changed as single quote)
`<property name="symbol"
    expression="fn:concat('Normal Stock - ', //m0:getQuote/m0:request/m0:symbol)"
    xmlns:m0="http://services.samples/xsd"/>`
in the sample mentioned in https://docs.wso2.com/display/EI6xx/Property+Mediator#PropertyMediator-Example1:Settingandloggingandproperty

**Comment by samgnaniah** [comment]
Fixed. Thanks for reporting!
