### ISSUE TITLE
[EI 6.1][Tooling] Source view is not updated according to the Design View when you press Ctrl+Z

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#400]
1. Create a Rest api as pizzashop with context as /pizzashop
2. Insert a send mediator and endpoint in design view.
Your source view will be as below : 
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/pizzashop" name="pizzashop" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence>
            <send>
                <endpoint>
                    <http method="get" uri-template="http://10.100.0.24:9764/pizzashop-rs_1.0/services/menu/pizza/all"/>
                </endpoint>
            </send>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

3. Now Ctrl+Z several times and then design view will become blank. But source view will be as below 

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/pizzashop" name="pizzashop" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence/>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

4. Now if you try to include an api resource, it will not make any response.
5. Either it should not delete api resource in design view or update the source view accordingly. 

![screenshot from 2017-03-28 15-13-44](https://cloud.githubusercontent.com/assets/12966170/24399074/31278660-13c9-11e7-8b10-3a504d6ac8a6.png)
![screenshot from 2017-03-28 15-13-47](https://cloud.githubusercontent.com/assets/12966170/24399076/32753de6-13c9-11e7-90e7-e653135af4a7.png)

**Comment by sohaniwso2** [comment]
moved to tooling repo at https://github.com/wso2/devstudio-tooling-ei/issues/197

**Comment by Nirothipan** [comment]
Can be related to issue https://github.com/wso2/product-ei/issues/2460

**Comment by Nirothipan** [comment]
Moved to https://github.com/wso2/product-ei/issues/2441
