### ISSUE TITLE
[Docs] CXF WS-RM Inbound Protocol - Broken Link

### ISSUE THREAD

**Issue by menuka94** [wso2/product-ei#4009]
**Description:**
In the [documentation for CXF WS-RM Inbound Protocol](https://docs.wso2.com/display/EI6xx/CXF+WS-RM+Inbound+Protocol), the link for **Installing Features** is invalid.

It is not possible to try out the rest of the documentation as installing the CXF WS Reliable Messaging feature is a required step.

**Comment by Nirothipan** [comment]
Duplicate of https://github.com/wso2/product-ei/issues/3901
