### ISSUE TITLE
[EI 6.1] All the occurences of wso2ei-6.1.0-SNAPSHOT/samples/business-process sample zip .bar file locations should be updated in EI documentation according to the new folder structure

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#401]
[EI 6.1] All the occurences of wso2ei-6.1.0-SNAPSHOT/samples/business-process sample zip .bar file locations should be updated in EI documentation according to the new folder structure.

E.g.,In this doc https://docs.wso2.com/pages/viewpage.action?spaceKey=EI610&title=Claims+Approval+task+with+HT+Renderings+Sample

Under Deploy the sample, **<BPS_HOME>/repository/samples/bpel** path should be changed as **<EI_HOME>/samples/business-process/bpel**

The ClaimsApprovalProcess.zip BPEL package has to be deployed as mentioned in the ClaimApprovalTask sample page. This BPEL package can be found in the<BPS_HOME>/repository/samples/bpel directory.

**Comment by praneesha** [comment]
Added the following note in the BPS Sampels section in [1].

"Note that WSO2 EI is shipped with the following changes to what is mentioned in this documentation:
<PRODUCT_HOME>/repository/samples/ directory that includes all Business Process profile samples and their artifacts is changed to <EI_HOME>/samples/business-process/."

[1] https://docs.wso2.com/display/EI610/Business+Process+Profile+Samples
