### ISSUE TITLE
[Docs][Kerberos Mediator]Doc needs to be updated

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#4017]
**Description:**
Doc seems outdated. Needs to be updated according to the current implementation as in https://github.com/wso2/product-ei/issues/2539

**Comment by Nirothipan** [comment]
@keerthu Shall we provide the conf need to be updated please. The issue pointed doesn't have information on what to be updated

**Comment by keerthu** [comment]
The following details need to be added in the doc:
In order to use this mediator with the "Username Auth" flow, create the krb5.conf file and place it under {EI_HOME}/repository/resources/security folder. This file should contain the following minimal configuration:
 ` [libdefaults]
        default_realm = REALM
     [realms]
          REALM = {
               kdc = <name of the kdc>
          }
     [domain_realm]
          domain = REALM
          .domain = REALM
`
Sample file is given bellow:
`
[libdefaults]
           default_realm = WSO2.TEST
   [realms]
           WSO2.TEST = {
                   kdc = 192.1xx.xx.158:88
           }
 
   [domain_realm]
           .wso2.test = WSO2.TEST
           wso2.test = WSO2.TEST
`

**Comment by nilminiwso2** [comment]
Reducing the priority of this task and putting it on hold as discussed with the team. We will complete the docs for the Kerberos mediator when it is supported by WSO2 Integration Studio. 
The existing docs for kerberos mediator (in EI 6.4.0 and 6.5.0) is now hidden.
