### ISSUE TITLE
[Doc] Documentation changes for Enrich and Aggregate mediators

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4027]
**Description:**
We have introduced the native JSON support for Enrich, Iterate and Aggregate mediators. 
Changes for iterate mediator are already updated in docs.

We need to do the following changes for Enrich and Iterate mediators

**Aggregate mediator new syntax** 
```
<aggregate>
   <correlateOn expression="xpath | json-eval(JSON-Path)"/>?
   <completeCondition [timeout="time-in-seconds"]>
     <messageCount min="int-min" max="int-max"/>?
   </completeCondition>?
   <onComplete expression="xpath |  json-eval(JSON-Path)" [sequence="sequence-ref"]>
     (mediator +)?
   </onComplete>
</aggregate>
```

**Enrich mediator new syntax**
```
<enrich>
    <source [clone=true|false] [type=custom|envelope|body|property|inline] xpath | json-eval(JSON-Path)="" property="" />
    <target [action=replace|child|sibiling] [type=custom|envelope|body|property|inline] xpath | json-eval(JSON-Path)="" property="" />
</enrich>
```

- When using Enrich mediator with JSON payloads we need to highlight the following points.

- We only support the add child operation for JSON payloads. Add sibling operation can be achieved via add child indirectly. 
{ "Nimal" : { "student_Id" : "001" , "Marks" : [ 23, 34, 45, 56 ] } } Adding a sibling to $.Nimal.Marks[0] is equal to adding a child to $.Nimal.Marks

- When giving inline JSON payloads we can add JSON arrays, objects and primitives ( number, string, true, false ). But, when enriching the inline content to the body, that content should be either a JSON object or an array.

- We can add any JSON element (object, array, primitive) as a child if the target is a JSON array.

- We can only add a JSON object as a child if the target is a JSON object. 

- Clone true/false does not apply to JSON as they are applied to XML payloads. 

**Suggested Labels:**
Improvement

**Affected Product Version:**
EI 6.5.0

**OS, DB, other environment details and versions:**

**Comment by a5anka** [comment]
Can we incorporate these restrictions in tooling so that the users will not do these mistakes?

**Comment by sameeragunarathne** [comment]
@samgnaniah is this information is added to the docs?

**Comment by samgnaniah** [comment]
@sameeragunarathne yes, this was added for EI 6.5.0 [1] [2].

[1] - https://docs.wso2.com/display/EI650/Aggregate+Mediator
[2] - https://docs.wso2.com/display/EI650/Enrich+Mediator
