### ISSUE TITLE
[DOC]Sample 906: Inbound Endpoint MQTT Protocol Sample

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#4029]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/Sample+906%3A+Inbound+Endpoint+MQTT+Protocol+Sample#Sample906:InboundEndpointMQTTProtocolSample-Buildingthesample
Section: Building the sample
Step 8c
This should be corrected as Drop mediator. In the doc, it has been asked to add a property mediator. 

**Suggested Labels:**
type/docs

**Affected Product Version:**
EI 6xx docs

**Comment by Ibaqu** [comment]
Changed Step 8-C from Property mediator to drop mediator for version E.I 6.5.0 and 6.x.x
