### ISSUE TITLE
unable to add jms parameter in Inbound Endpoint (tooling)

### ISSUE THREAD

**Issue by SITRE** [wso2/product-ei#4031]
Cannot add parameter in inbound endpoint (jms).. when i add a parameter via properties tab ou source they just disappear.

reproduce the issue by just creating a new inbound endpoint and try to add Java Naming Factory Initial , Java Naming Provider Url, etc.. etc..

tooling 6.4

**Comment by dakshika** [comment]
This works fine in latest version 6.5.0

**Comment by dakshika** [comment]
@SITRE Can you try with latest release on https://github.com/wso2/product-ei/releases

**Comment by SITRE** [comment]
dakshika i dont find the 6.5.0 tooling. In the link you have provided is just 6.5.0 ei product . where is the tooling ?
