### ISSUE TITLE
Update the IS documentation link in OAuth mediator documentation

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#4033]
**Description:**

https://docs.wso2.com/display/EI6xx/OAuth+Mediator

In the above documentation link, the phrase **2-legged OAuth for Securing a RESTful Service** points to an old IS documentation link. It would be better if we can point it towards a latest IS release documentation.

**Suggested Labels:**

Type/Docs

**Comment by Ibaqu** [comment]
Changed Link to the latest IS Release documentation as requested.

**Comment by arunans23** [comment]
Fixed in the 6.5.0 and the latest 6xx as well. Hence closing this issue.
