### ISSUE TITLE
[Kerberos Mediator] Username Auth flow is not working

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#4034]
**Description:**
As per the current implementation, krb5.conf can be configured only for "Keytab Auth" flow which is also required for "Username Auth" flow. Due to this, username, password flow is not working with the current implementation. Getting the following error message:
`Direction: request, MESSAGE = Executing default 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Could not find the Kerberos configuration.`

**Comment by keerthu** [comment]
This issue is resolved by putting the krb5.conf file under {EI_HOME}/repository/resources/security folder. Need to update the doc with this info.
Since krb5.conf file is required for both flows, we can follow the same approach (ie, ask the user to place the file inside the resources/security folder instead of getting the krb5.conf path file from the user for one flow) for consistency.

**Comment by praveennadarajah** [comment]
krb5.conf file should be placed under  {EI_HOME}/repository/resources/security folder. This information is already present in the doc[1]. Hence closing the issue.

[1] https://docs.wso2.com/display/EI6xx/Kerberos+Mediator
