### ISSUE TITLE
[ Doc ] Update What's new in this release Section 6.5.0

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4035]
**Description**

Shall we update the section [1], to match with the information in [2]. We have some more key things to be mentioned in it.

### Integration Studio: The new IDE for EI configuration development

- Sleek design that gives a great graphical tooling experience.
- Enhanced developer experience with built-in testing and debugging support.
- Deploying in containers is made simple by providing a feature to create docker images from the studio itself.
- Seamless experience in deploying integration projects into the WSO2 Integration Cloud.

### Integration Runtime 

- A new mediator named **Property Group** that eases the usability by allowing you to configure multiple properties inside a single mediator.
- Native JSON support for Iterate, Aggregate and Enrich Mediators.
- Message Processor improvements to handle poison messages.
- Enhanced REST support for Data Service JSON payloads.
- OData Support for MongoDB.
- Support to monitor statistics with Prometheus.
- Architectural enhancements resulting in high scalability and improved performance of Analytics.

### Micro Integrator: Cloud-native version of the Integration Runtime

- Micro Integrator profile as a separate distribution. The directory structure of MI has also changed due to this.
- New Micro Integrator base Docker image.
- A CLI tool to get information on deployed artifacts in Micro Integrator.
- Improved REST API to get information on deployed artifacts.
- Support to monitor statistics with Prometheus [micro-integrator#141](https://github.com/wso2/micro-integrator/issues/141).
- Reduced distribution size to create more compact images.
- Endpoint URL look up through environment variables [product-ei#2735](https://github.com/wso2/product-ei/issues/2735). 

[1] - https://docs.wso2.com/display/EI6xx/About+this+Release#AboutthisRelease-What'snewinthisrelease
[2] - https://github.com/wso2/product-ei/releases/tag/v6.5.0-rc1

**Comment by Nirothipan** [comment]
Please remove "ESB artifacts option in Management console" from https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-Deprecatedfeatures . 

It was already removed and we have removed from the deprecated features in release notes in https://github.com/wso2/product-ei/pull/3933

**Comment by Nirothipan** [comment]
This section https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-Fixedissues addresses not only the fixed issue but also improvements . Hence we need to adjust the title to match it .

**Comment by Nirothipan** [comment]
@samgnaniah  / @nilminiwso2 Why we aren't having period at the end of each listings in https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-Deprecatedfeatures , is there any reason for it . We have it in https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-What'snewinthisrelease listings.

**Comment by Nirothipan** [comment]
In known issues section please include Micro integrator Issues too . https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-Knownissues

**Comment by samgnaniah** [comment]
@Nirothipan Ack. We are still working on refining this page.

**Comment by samgnaniah** [comment]
Updated this page.

https://docs.wso2.com/display/EI650/About+this+Release
