### ISSUE TITLE
[DOC] Add Property Group Mediator to docs

### ISSUE THREAD

**Issue by samgnaniah** [wso2/product-ei#4039]
Add Property Group mediator to the docs.

**Comment by Nirothipan** [comment]
This was introduced in https://github.com/wso2/wso2-synapse/pull/1241

**Comment by RukshiW** [comment]
Added the documentation in [1].
@praveennadarajah please review this page and let me know whether this issue can be closed.

[1] https://docs.wso2.com/display/EI650/Property+Group+Mediator

**Comment by RukshiW** [comment]
This page was reviewed by Praveen and the recommended changes were done.
