### ISSUE TITLE
Clicking on an inbound endpoint under capp directs to a blank page in Management Console

### ISSUE THREAD

**Issue by dinuish94** [wso2/product-ei#4046]
**Description:**
When an inbound endpoint is clicked under capp, it directs to a blank page.

<img width="1678" alt="Screen Shot 2019-05-17 at 3 27 50 PM" src="https://user-images.githubusercontent.com/16366956/57920380-827c2380-78b8-11e9-8ac6-ebf9c1e62ad9.png">

Prints the following error in the log.
`[EI-Core] ERROR - InboundManagementClient java.lang.NullPointerException`

**Suggested Labels:**
6.5.0 

**Steps to reproduce:**
1. List Carbon applications.
2. Select an application with inbound endpoints. 
3. Click on an inbound endpoint. This directs to a blank endpoint

**Comment by Nirothipan** [comment]
I tried this with a carbon app having inbound Ep and still was able to click and open the Inbound Ep from carbon app in Management Console. Attached the relevant capp.

[ESMasJMS_ProdandConsCompositeApplication_1.0.0.txt](https://github.com/wso2/product-ei/files/3193792/ESMasJMS_ProdandConsCompositeApplication_1.0.0.txt)

@dinuish94 Could you please attach the relevant carbon app you used.

**Comment by dinuish94** [comment]
Please find the car file I used below.

[testhelloCompositeApplication_1.0.0.txt](https://github.com/wso2/product-ei/files/3227363/testhelloCompositeApplication_1.0.0.txt)

**Comment by malakaganga** [comment]
Can not reproduce hence resolving
