### ISSUE TITLE
Why we have to delete variables?

### ISSUE THREAD

**Issue by amerireza** [wso2/product-ei#4049]
**Description:**
There are lines like [these](https://github.com/wso2/wso2-synapse/blob/9083d4f8a3afcde744cc7df5a320309a2f5b18d2/modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java#L87-L92) which are deleting some values from variables.
What is the reason to do that? These variables can be helpful in logs. Is there any security reason?

**Comment by ThishaniLucas** [comment]
These values will become problematic in case of a service chaining scenario where we call multiple endpoints one after the other. That's why we're flushing these values before calling an endpoint.

**Comment by amerireza** [comment]
There may be another way to flush the values? Can you tell me the exact problems or scenarios?
