### ISSUE TITLE
[Docs] Missing transaction information in DB Report Mediator

### ISSUE THREAD

**Issue by dilee** [wso2/product-ei#4050]
**Description:**
When transactions are enabled in the DB Report mediator, it is mandatory to create a new transaction before the DB Report mediator and commit the transaction afterwards. Refer to [1] for an example. This information should be present in [2] since missing this configuration could break the functionality of the DB Report mediator.

[1] - https://docs.wso2.com/display/EI640/Transaction+Mediator+Example
[2] - https://docs.wso2.com/display/EI640/DB+Report+Mediator

**Affected Product Version:**
All versions

**Comment by RukshiW** [comment]
Did the following changes in [1].

- Added the following note in the parameter description for **Use Transaction**

"If you click **Yes** to perform the database operation within a transaction, you need to ensure the following: The DBReport mediator configuration must be preceded by a Transaction Mediator configuration with  **new**  as the transaction action. The DBReport mediator configuration must be followed by a Transaction Mediator configuration with **commit** as the transaction action.
For detailed information about configuring Transaction mediators, see Transaction Mediator."
--



- Added a new example named **Performing a database write operation within a transaction**

[1] https://docs.wso2.com/display/EI6xx/DB+Report+Mediator#e342b8081d95442da9dc4f06c1ae734f

@dilee can you please review?
