### ISSUE TITLE
Clustering the Business Process Profile

### ISSUE THREAD

**Issue by Nipunich** [wso2/product-ei#4056]
**Description:**
1. Mounting the registry
We need to  change the location of registry.xml file given under " Mounting the registry"  to `<EI_HOME>/wso2/business-process/conf/registry.xml` .
               
<img width="1326" alt="Screen Shot 2019-05-21 at 11 36 05 AM" src="https://user-images.githubusercontent.com/41411909/58072234-ab542f80-7bbc-11e9-8e2c-7386b963efa4.png">

2. Configuring the business process profile node
  The configuration changes should be done in the file given below not in  
  "<EI_HOME>/conf/datasources/master-datasources.xml". 

    ` <EI_HOME>/wso2/business-process/conf/datasources/master-datasources.xml
`

**Comment by samgnaniah** [comment]
Fixed.

https://docs.wso2.com/display/EI650/Clustering+the+Business+Process+Profile
