### ISSUE TITLE
[Tooling] Add KeyStore parameter tags to the source of HTTPS Inbound endpoint

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/product-ei#4059]
**Description:**
When creating an HTTPS inbound endpoint in Integration studio, parameters for the KeyStore (following code segment) is not in the source. But to create an HTTPS inbound endpoint, KeyStore parameters are required thing. 
```
<parameter xmlns="" name="keystore">
            <KeyStore>
               <Location>repository/resources/security/wso2carbon.jks</Location>
               <Type>JKS</Type>
               <Password>wso2carbon</Password>
               <KeyPassword>wso2carbon</KeyPassword>
            </KeyStore>
</parameter>
```

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/634
