### ISSUE TITLE
Incomplete server startup goes unnoticed when RMIRegistry port has not been properly defined

### ISSUE THREAD

**Issue by IrushiL** [wso2/product-ei#4065]
**Description:**
Server initialization is not properly completed when RMIRegistry port has not been properly defined. However, this goes unnoticed with no record in the carbon logs. As a result of this incomplete server initialization, listeners of server startup are not notified. 

This issue was found when an RCA was done on a scenario where the scheduled tasks were not getting executed. Here, since the server startup listener (TaskStartupHandler) was not notified of the server initialization the scheduled tasks execution was not happening, even though nothing suspicious was seen in the carbon logs.

**Affected Product Version:**
All EI versions 

**Steps to Reproduce:**
If the JMX ports (RMIRegistryPort and RMIServerPort) are commented out in the <EI_HOME>/conf/carbon.xml file and if a log patch is added to the org.wso2.carbon.core jar with the following changes the issue could be reproduced.

- Place the contents of method [1] inside a try catch. 
- Catch a Throwable and log it.
- The following exception could be seen in the carbon logs,
`java.lang.RuntimeException: RMIRegistry port has not been properly defined in the jmx.xml or carbon.xml files`
- This is exception is not caught since [2] throws a new RuntimeException instead of a ServerException which is caught in [3]. 

[1] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/internal/StartupFinalizerServiceComponent.java#L163
[2] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/init/JMXServerManager.java#L86
[3] https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/internal/StartupFinalizerServiceComponent.java#L210

**Comment by sameeragunarathne** [comment]
already fixed
