### ISSUE TITLE
[JSON] Blank spaces should be preserved in the inbuilt JSON Formatter

### ISSUE THREAD

**Issue by dilee** [wso2/product-ei#4072]
**Description:**
XML elements with only spaces as the value are not getting preserved. Instead, they get trimmed when converted into JSON. Refer to the following example.

Request sent:
```
<coordinates>
	<location>
       <name>                     </name>
       <n>25.0000</n>
       <w>71.0000</w>
    </location>
 </coordinates>
```

Expected output:
```
{
    "coordinates": {
        "location": {
            "name": "                     ",
            "n": 25,
            "w": 71
        }
    }
}
```

Actual output:
```
{
    "coordinates": {
        "location": {
            "name": null,
            "n": 25,
            "w": 71
        }
    }
}
```

While keeping this current behaviour as the default behaviour, we should provide a property to enable the preservation of spaces whenever needed.

**Affected Product Version:**
6.5.0

**Comment by pramodya1994** [comment]
https://github.com/wso2/wso2-synapse/pull/1349
