### ISSUE TITLE
New property introduced to preserve blank spaces values of XML elements when converting to JSON.

### ISSUE THREAD

**Issue by pramodya1994** [wso2/product-ei#4074]
**Description:**
XML elements with only spaces as the value are not getting preserved. Instead, they get trimmed when converted into JSON. While keeping this current behavior as the default behavior, we have introduced a new property to enable the preservation of spaces whenever needed.
New property introduced to preserve blank spaces values of XML elements when converting to JSON mentioned below.
```
<property name="PRESERVE_SPACES" value="true" scope="axis2"/>
```
**API**
```
<api xmlns="http://ws.apache.org/ns/synapse" name="Test2" context="/full_xml">
   <resource methods="POST GET">
      <inSequence>
         <log level="full">
            <property name="log" value="invoked."/>
         </log>
         <property name="PRESERVE_SPACES" value="true" scope="axis2"/>
         <property name="messageType" value="application/json" scope="axis2"/>
         <respond/>
      </inSequence>
      <outSequence/>
   </resource>
</api> 
```
**XML request body**
```
<Results>
	<element1>123</element1>
	<element2>             </element2>
</Results>
```
**JSON responce without property**
```
{
    "Results": {
        "element1": 123,
        "element2": ""
    }
}
```
**JSON responce with property**
```
{
    "Results": {
        "element1": 123,
        "element2": "             "
    }
}
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI-6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Add above-mentioned API and send a request with the given XML as the body. You will get the JSON response without the blank spaces.

**Related Issues:**
https://github.com/wso2/product-ei/issues/4072

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/wso2-synapse/commit/47ed7225aefed61a662d2c65b67389ffd0a7d8f9

**Comment by GDLMadushanka** [comment]
Added the property to the documentation
https://docs.wso2.com/display/EI6xx/Working+with+JSON+Message+Payloads
