### ISSUE TITLE
Include Management Console & MSF4J Profile to Deprecated List

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4076]
**Description:**
$subject.

Please Include the following entry to the https://docs.wso2.com/display/EI650/About+this+Release#AboutthisRelease-Deprecatedfeatures list

- Management Console ( UI )

**Comment by Nirothipan** [comment]
@isudana  - Could you please confirm on the format the entry this added above.

**Comment by Nirothipan** [comment]
It would be better if we remove these steps like UI configuration or add a banner in these page that this Management console will be deprecated it will bring more attention.

For eg : https://docs.wso2.com/display/EI650/In+Memory+Message+Store

@isudana / @nandika  suggestions please

**Comment by Nirothipan** [comment]
Please include the following entry as well.

- MSF4J Profile

**Comment by Nirothipan** [comment]
@samgnaniah / @nilminiwso2  / @RukshiW Shall we give more priority to this please. Since we have announced the release already this is kind of high priority now.

**Comment by Nirothipan** [comment]
also Please remove the "**ESB artifacts option in Management console**" option from the deprecated list. It was removed in some previous releases itself and it is not there in 6.5.0.

**Comment by samgnaniah** [comment]
Updated. Please check.

https://docs.wso2.com/display/EI650/About+this+Release

**Comment by Nirothipan** [comment]
It would be great if we can include following short descriptions also for them

Current Management Console ( UI ) ( This  will be replaced with an alternative monitoring mechanism in a future release ).

MSF4J Profile. ( Compelling reason for this is because we see more value to users from WSO2 MSF4J github project and its artifacts since most of the micro service developers will use it as a dependency rather than a server runtime. Hence, we believe MSF4J is more useful to developers in its github based release cycle rather than packaging it in the WSO2 Enterprise Integrator ).

**Comment by samgnaniah** [comment]
Updated with those descriptions. Please check and close. 

https://docs.wso2.com/display/EI650/About+this+Release
