### ISSUE TITLE
[EI 6.1.0][Analytics][Inbounds] Request Count is wrong

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#408]
**Environment**
Operating Systems : Redhat and Debian
Java Version : JDK1.8
Packs : EI610 PreAlpha Pack
EI Setup: Cluster (3 nodes)
Analytics Setup: Cluster (2 nodes)
DB - Oracle 12c

**Preconditions**
Enabled publishing statistics in global level

**Steps to reproduce**
1. Add inbound endpoint
2. Enable statistics in inbound endpoint
3. Invoke inbound endpoint
  
**Expected Result**
Statistics should be published.

**Actual Result**
Request count of exact inbound is incorrect.

Refer following screen shots. (For last month its show as 35 while 18 for last year)

![screenshot from 2017-03-28 18-44-22](https://cloud.githubusercontent.com/assets/8134384/24407108/9a528c84-13e7-11e7-916c-b8f484473be7.png)
![screenshot from 2017-03-28 18-44-32](https://cloud.githubusercontent.com/assets/8134384/24407107/9a426a98-13e7-11e7-89a3-66be498d91f2.png)

**Comment by nandika** [comment]
This issue seems an intermediate result.  Expectation is the the final results show after the run is complete should be correct. ESB Analytics produces correct result on that aspect. Hence this should be ok

**Comment by AnuGayan** [comment]
This was fixed in EI-Analytics 6.4.0
