### ISSUE TITLE
Unable to redeploy .car with API Version

### ISSUE THREAD

**Issue by ggianoglio** [wso2/product-ei#4091]
**Description:**
It's not possible to redeploy Carbon Applications that contain API with a version defined. When the CAPP is removed from the Enterprise Integrator instance the API is still visible in the API list from the carbon console.
The only solution is stop and restart the instance and deploy the newer version of the CAPP.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Enterprise Integrator 6.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. From EI Tooling create an API with a version defined
2. Create the CAPP for the API defined at point 1.
3. Deploy the CAPP on the EI instance
4. Delete the CAPP from the EI instance
5. Deploy again the CAPP on the EI instance

**Related Issues:**

**Comment by GDLMadushanka** [comment]
This is not reproducible in the latest version
