### ISSUE TITLE
Documentation for clustering configuration for the broker is incorrect

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#4095]
**Description:**
The definition for the **nodeId** is incorrect in
``` https://docs.wso2.com/display/MB320/Clustered+Deployment#ClusteredDeployment-RDBMS_clusteringConfiguringclustercoordination.```

The node id is created in the following way:
`NODE:localMemberHost:localMemberPort`
The point to note here is that, the localMemeberHost will be the hostname if, the hostname can be mapped with the provided IP. Otherwise, it would be the ip address it self.

**Affected Versions:**
All versions of WSO2EI and WSO2MB 3.2.0

**Comment by nilminiwso2** [comment]
Updated the docs for MB 320, EI 620 to EI 650. Solution discussed in mail thread [1].

[1] "MB: Another node with the same node id found in the cluster"
