### ISSUE TITLE
Unable to start EI integrator profile in MacOS after the installation

### ISSUE THREAD

**Issue by jrathnayake** [wso2/product-ei#4118]
**Description:**
Downloaded EI 6.5.0 installer (.dmg) from wso2.com web site and installed. When try to run get the following error and not able to run the EI.

EI server but would not start with the error: OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /Library/WSO2/EnterpriseIntegrator/6.5.0/repository/logs/wso2carbon.log (Permission denied)

I changed the EI installation folder permissions manually to Read-Write and it worked.

**Suggested Labels:**
Installation, MacOS, Priority/High

**Suggested Assignees:**

**Affected Product Version:**
Enterprise Integrator 6.5.0

**OS, DB, other environment details and versions:**    
MacOS

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Hi @jrathnayake 

As you have identified, this has happened due to the permission issue.
To overcome this, we need to start the server with sudo as mentioned in the https://docs.wso2.com/display/EI650/Quick+Start+Guide

```
sudo wso2ei-6.5.0-integrator
```
Thanks

**Comment by Nirothipan** [comment]
Hi @jrathnayake 

As you have identified, this has happened due to the permission issue.
To overcome this, we need to start the server with sudo as mentioned in the https://docs.wso2.com/display/EI650/Quick+Start+Guide

```
sudo wso2ei-6.5.0-integrator
```

If not you might need to change the ownership of the product distribution to default user with "**chown**" command.

Thanks

**Comment by jrathnayake** [comment]
Thanks.
