### ISSUE TITLE
Can't redeploy failed Car file

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#4119]
**Description:**
When Car file is deployed by copying to the carbonapps folder and the deployment fails, it is not possible to force redeployment from the carbon console. Re-deploy option is missing in the UI on the list of failed Carbon applications.

The only way to force redeployment is to trigger the restart the EI, which is not acceptable solution.

Note: Reasoning for the request is that sometimes Car deployment fails due to the order in which Car files are deployed, and simple redeploy make the previously failed Car file to deploy successfully.

**Affected Product Version:**
6.5.0

**Comment by nandika** [comment]
Hi Markocic,

You can 'touch' the failed car file on the filesystem to update its last modified timestamp and the car file will get redeployed automatically. So you will not require a server restart for redeployment.

Nandika

**Comment by markokocic** [comment]
hi @nandika 

the problem with this approach is that in general deployment by copying files is done by the automation scripts, and developers don't have ssh access to the deployment server.

Being able to just click on "redeploy" would be real time saver. The other alternative would be to download the car file and then re-upload it again, but the usability of this solution is not that great.

**Comment by GDLMadushanka** [comment]
This feature is available in the latest releases.
