### ISSUE TITLE
wso2 maven plugins are not thread safe

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#4129]
**Description:**
When running maven parallel build using e.g. `mvn -T 4 install` maven complains that wso2 plugins are not marked as @theradsafe and that build could possibly be wrong.

**Suggested Labels:**
Type/Bug
Not sure if this is the correct place to report tooling problems.

**Affected Product Version:**
All plugin versions defined in pom.xml files when creating any type of wso2 project.

**Steps to reproduce:**
1. Create one sample wso2 project of any type.
2. Run `mvn -T 2 install`
3. Observe build warnings reported by maven about thread safety

Expected: Build works successfully without warnings.

** Reasoning **
Build of the wso2 artifacts takes too much time already, due to proliferation of projects. Enabling thread safety in wso2 plugins would enable build process to bee significantly faster.

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/641
