### ISSUE TITLE
WSO2 ESB Inbound JMS Endpoint Clustering Issue

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4141]
**Description:**

- Following property has been used in order to force the execution of the Inbound Endpoint in just one of the worker nodes of a cluster. If the selected node is down, then another worker node will start the Inbound Endpoint

`<parameter name="coordination">true</parameter>`

- In a cluster with two worker nodes and one manager node. The cluster is configured following the AWS Mode instructions and it works fine. I have a JMS Inbound Endpoint too, configured this way

```
<inboundEndpoint name="INB_Q1" onError="ARQ.ERROR" protocol="jms" sequence="INB_Q1_FunINB" suspend="false" xmlns="http://ws.apache.org/ns/synapse">
<parameters>
<parameter name="interval">100</parameter>
<parameter name="sequential">true</parameter>
<parameter name="coordination">true</parameter>
<parameter name="transport.jms.Destination">INB_Q1</parameter>
<parameter name="transport.jms.CacheLevel">3</parameter>
<parameter name="transport.jms.ConnectionFactoryJNDIName">QueueConnectionFactory</parameter>
<parameter name="java.naming.factory.initial">org.apache.activemq.jndi.ActiveMQInitialContextFactory</parameter>
<parameter name="java.naming.provider.url">@activemq_failover</parameter>
<parameter name="transport.jms.SessionAcknowledgement">AUTO_ACKNOWLEDGE</parameter>
<parameter name="transport.jms.SessionTransacted">false</parameter>
<parameter name="transport.jms.ConnectionFactoryType">queue</parameter>
<parameter name="transport.jms.ContentType">application/json</parameter>
<parameter name="transport.jms.SharedSubscription">false</parameter>
</parameters>
```

- When the cluster is started, everything works fine. Scheduled task for the Polling (JMS) Endpoint starts in just one node, and only one consumer is available in ActiveMQ queue.

- Then I shut down the node executing the task, the cluster gets notified and the scheduled task starts in the remaining active node. It keeps working fine.

- When the previously shutdown node is restarted, the node starts the scheduled task again, the two workers execute the same Inbound Endpoint and I have two consumers for the same queue.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
**This issue has been attempted to be reproduced and failed**

**OS, DB, other environment details and versions:** 
Amazon Linux
Cluster AWS Mode
1 Manager Node, 2 worker nodes
Apache ActiveMQ 5.14.5   

**Steps to reproduce:**

**Related Issues:**

**Comment by sachithKay** [comment]
This issue has been attempted to be reproduced by @Nirothipan as follows.
1. created an Inbound endpoint with coordination true as follows.
```
<?xml version="1.0" encoding="UTF-8"?>
<inboundEndpoint xmlns="http://ws.apache.org/ns/synapse"
                 name="testJMSClustering"
                 sequence="sendOut"
                 onError="onError"
                 protocol="jms"
                 suspend="false">
   <parameters>
      <parameter name="interval">1000</parameter>
      <parameter name="sequential">true</parameter>
      <parameter name="coordination">true</parameter>
      <parameter name="java.naming.factory.initial">org.wso2.andes.jndi.PropertiesFileInitialContextFactory</parameter>
      <parameter name="java.naming.provider.url">conf/jndi.properties</parameter>
      <parameter name="transport.jms.ConnectionFactoryJNDIName">QueueConnectionFactory</parameter>
      <parameter name="transport.jms.ConnectionFactoryType">queue</parameter>
      <parameter name="transport.jms.Destination">JMSMS</parameter>
      <parameter name="transport.jms.SessionAcknowledgement">AUTO_ACKNOWLEDGE</parameter>
      <parameter name="transport.jms.CacheLevel">3</parameter>
      <parameter name="transport.jms.SubscriptionDurable">false</parameter>
      <parameter name="transport.jms.ContentType">application/xml</parameter>
      <parameter name="transport.jms.SharedSubscription">false</parameter>
   </parameters>
</inboundEndpoint>
```
2. With 2 worker nodes, when started both, only one subscription was added.

3. After putting one node and making it up also, the issue was not reproducible. Only Single subscription was found in the broker.

4. This was tested with WSO2 broker packed with EI 6.1.1 update 22.

**Comment by malakaganga** [comment]
Resolving according to above comment
