### ISSUE TITLE
Remove Old Stats configurations and feature

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4170]
**Description:**
In ESB 5 we can still see old stats related configuration in carbon.xml etc. These should be removed along with UI options.
```
<!--Disabling statistics reporter by default-->
    <StatisticsReporterDisabled>false</StatisticsReporterDisabled>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Invalid requirement
