### ISSUE TITLE
Performance of Data Service Exposing OData

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#4182]
**Description:**

After using data services in order to expose data over OData protocol i have encountered bad performance issues when using tables with over 500 000 records.
The system takes too long to respond when making some paginated queries 
(?$top=10&$skip=200)
It seems the queries are not limited even thought there is $top parameter. 
The reduced set of records is manipulated after getting all the results which is wrong on performance point of view.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

https://wso2.org/jira/browse/DS-1284

**Comment by AlbanaCelepija** [comment]
Hello,
Regarding this issue, which was initially created in Jira, we would be interested in the contribution for fixing performance issues related to OData requests (for RDBMS data sources). Does this mean we have to send the Pull Request to the repository of https://github.com/wso2/carbon-data?

**Comment by chanikag** [comment]
This is fixed by https://github.com/wso2/micro-integrator/pull/2765
