### ISSUE TITLE
Add Splunk connector for wso2 ESB

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#4185]
**Description:**
This produces software for searching, monitoring, and analyzing machine-generated big data, via a web-style interface.Splunk (the product) captures, indexes and correlates real-time data in a searchable repository from which it can generate graphs, reports, alerts, dashboards and visualizations.Splunk has a mission of making machine data accessible across an organization by identifying data patterns, providing metrics, diagnosing problems and providing intelligence for business operations. Splunk is a horizontal technology used for application management, security and compliance, as well as business and web analytics.

API Provider   :      http://splunk.com
API Homepage :-  http://dev.splunk.com/
API:- Splunk Enterprise REST API
           Splunk SDK for java

Types of Splunk software:-  Splunk Enterprise, Splunk Free, Splunk Trial.

Splunk Enterprise for free:-When you download Splunk Enterprise for free, you get a Splunk Enterprise license for 60 days that lets you index up to  500 megabytes of data per day.When the free trial ends, you can convert to a perpetual Free license or purchase an Enterprise license to continue using the expanded functionality designed for multi-user deployments.
Splunk Enterprise
For the full-featured version of Splunk Enterprise, pricing is based on the amount of data indexed per day.
Splunk installation
To install Splunk Enterprise on a Linux system, expand the tar file into an appropriate directory using the tar command: tar xvzf splunk_package_name.tgz

The default installation directory is splunk in the current working directory. To install into /opt/splunk, use the following command: tar xvzf splunk_package_name.tgz -C /opt

Start Splunk
To start Splunk Enterprise from the command-line interface, run the following command from $SPLUNK_HOME/bin directory, where $SPLUNK_HOME is the directory where Splunk is installed:  
 ./splunk start

Launch Splunk Web and log in
After you start Splunk and accept the license agreement,

1. In a browser window, access Splunk Web at http://<hostname>:port.
	         hostname is the host machine.
                         port is the port you specified during the installation (the default port is 8000).
2. Splunk Web prompts you for login information (default, username admin and password changeme) before it launches. If you switch to Splunk Free, you will bypass this logon page in future sessions.
Authentication and authorization
Username and password authentication is required for most endpoints and REST operations. Additional capability or role-based authorization may also be required, particularly for POST or DELETE operations.
The default authenticated session timeout is one hour, which is configurable using the session Timeout setting in the server.conf file [general] stanza.

About the REST API Reference
http://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog

System requirements
-Platform:-  Linux,Windows, Solaris, Mac Os,FreeBSD, AIX

**Comment by GDLMadushanka** [comment]
This connector is now available in the store
