### ISSUE TITLE
When cache mediator place inside iterator, tenant not set error occured

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4209]
**Description:**
When creating a sequence and use iterate mediator with sequential="false", Inside iterator mediate with a non-blocking call mediator to invoke a service endpoint. But on execution, it throws exception "Tenant does not set in carbon Context".
But if iterator is sequential (sequential="true", then no issue occurred.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sachithKay** [comment]
An issue related to setting tenant id is has been fixed by following PR:
https://github.com/wso2/wso2-synapse/pull/1356

**Comment by isudana** [comment]
Originally reported at https://wso2.org/jira/browse/ESBJAVA-5305 by Ramu P.
