### ISSUE TITLE
'Event Streams' permission duplicate in the ESB permission model

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4212]
**Description:**
In the ESB permission model, two permissions are appearing with the same name as 'Event Streams' as shown in the below image.
![ESB500](https://user-images.githubusercontent.com/22365810/59373463-59d83400-8d67-11e9-911a-501cab502c5e.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**   
wso2esb-5.0.0.1511862690460.zip 

**Steps to reproduce:**

**Related Issues:**

**Comment by sameeragunarathne** [comment]
Not observed in Latest EI
