### ISSUE TITLE
[Improvement] Get the Inbound Endpoint parameters from environment variables	

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4216]
**Description:**
It would be great to implement the feature to get the Inbound Endpoint parameter values from environment variables as we get from the registry properties.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5198

**Comment by malakaganga** [comment]
Fixed
