### ISSUE TITLE
[Improvement] Empty Optional Objects on Datamapper

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4219]
**Description:**
Data Mapper is not removing the optional elements from the output mapping. Suppose we are doing xml to json transformation using Data Mapper. 
Consider the below input and the output.
**scenario 1**

- input

```
<input>
<id>1</id>
<repeatingValues>
<value>1</value>
</repeatingValues>
<repeatingValues>
<value>3</value>
</repeatingValues>
<singleValue>
<value>4</value>
</singleValue>
</input>
```

- output

```
{
"id": "1",
"repeatingValues": [

{ "value": "1" }
,

{ "value": "3" }
],
"singleValue":

{ "value": "4" }
}
```

**scenario 2**

- input

```
<input>
<id>2</id>
</input>
```

- output

```
{
"id": "2",
"repeatingValues": [],
"singleValue": {}
}
```

According to the above, the empty elements are coming in the scenario 2.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5091

**Comment by riibeirogabriel** [comment]
I have the same problem.
