### ISSUE TITLE
[EI 61]https://docs.wso2.com/display/Carbon4410 documents should be updated according to the EI folder structure and product structure where it is applicable

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#422]
[EI 61]https://docs.wso2.com/display/Carbon4410 documents should be updated according to the EI folder structure where it is applicable.

E.g., 
https://docs.wso2.com/display/Carbon4410/Enabling+Cipher+Tool+for+Password+Encryption 

In this documentation, folder structure should be updated according to the new structure. 
E.g., `<PRODUCT_HOME>/repsoistory/conf/security`

Another example is, 
https://docs.wso2.com/display/Carbon4410/Creating+New+Server+Profiles
In here it talks about WSO2 Application Server. 

Those should be updated.

If we are not going to provide reference to this document, there should be separate documents for other scenarios in EI docs. 
E.g., Separate doc for  https://docs.wso2.com/display/Carbon4410/Enabling+Cipher+Tool+for+Password+Encryption

**Comment by praneesha** [comment]
Added the page [1] in the Common Admin Guide and added the following note in [2] to link to it.

"Note that WSO2 EI is shipped with a few changes to the general directory structure of WSO2 products. For information on these folder structure changes, go to Directory Structure of WSO2 Products in the WSO2 Administration Guide."

[1] https://docs.wso2.com/display/ADMIN44x/Directory+Structure+of+WSO2+Products
[2] https://docs.wso2.com/display/EI610/Product+Administration
