### ISSUE TITLE
[Docs][Clustering the Message Broker Profile] Update docs with correct configs

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#423]
1. In the doc [1], there is a section which will update MB_DB. Following part not need
```
mysql> create database userdb;
mysql> use userdb;
mysql> source <EI_HOME>/dbscripts/mysql.sql;
mysql> grant all on userdb.* TO username@localhost identified by "password";
  
mysql> create database regdb;
mysql> use regdb;
mysql> source <EI_HOME>/dbscripts/mysql.sql;
mysql> grant all on regdb.* TO username@localhost identified by "password";
```
2. We don't need rsync in clustering. Remove following part from the doc.

Deploying artifacts across the nodes

Note: verify from the team

3. Repeated same configurations. Update accordingly.

Add the following configuration in the <EI_HOME>/wso2/broker/conf/user-mgt.xml file to configure the user stores. 

Update the dataSource property in all nodes in the <EI_HOME>/wso2/broker/conf/user-mgt.xml file as shown below to configure the datasource: <Property name="dataSource">jdbc/WSO2UMDB</Property>

[1] https://docs.wso2.com/display/EI600/Clustering+the+Message+Broker+Profile

**Comment by praneesha** [comment]
Updated the above in MB clustering docs of EI 6.0.0 & 6.1.0.
