### ISSUE TITLE
Aggregate Mediator Does Not Work If Proxy Service Called As local:// service

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4230]
**Description:**
Calling a proxy service that has an iterate in the in sequence and an aggregate on an out sequence from another proxy service using the local:// transport results in the aggregate mediator hanging and the call timing out. When changed to use a reference  such as hostname the aggregate mediator works.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Mac OSX

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5012

**Comment by isudana** [comment]
Originally reported by  Sami Elhini at https://wso2.org/jira/browse/ESBJAVA-5012
