### ISSUE TITLE
API_LOGGER not propagated to iterate mediator

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4232]
**Description:**
File: log4j.properties
```
log4j.category.API_LOGGER.api_logging_test=INFO, API_LOGGING_TEST_APPENDER
log4j.additivity.API_LOGGER.api_logging_test=false
log4j.appender.API_LOGGING_TEST_APPENDER=org.apache.log4j.DailyRollingFileAppender
log4j.appender.API_LOGGING_TEST_APPENDER.File=$

{carbon.home}
/repository/logs/$

{instance.log}/wso2-esb-api_logging_test${instance.log}
.log
log4j.appender.API_LOGGING_TEST_APPENDER.Append=true
log4j.appender.API_LOGGING_TEST_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.API_LOGGING_TEST_APPENDER.layout.ConversionPattern=%d

{ISO8601}
[%X

{ip}
-%X

{host}
] [%t] %5p %c

{1}
%m%n
```
File: api_logging_test.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse" context="/esb/v1/api_logging_test" name="api_logging_test">
  <resource faultSequence="seq_logging_test_fault" methods="OPTIONS POST" protocol="http" url-mapping="/*">
    <inSequence>
      <sequence key="seq_logging_test"/>
    </inSequence>
    <outSequence/>
  </resource>
</api>
```

File: seq_logging_test.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="seq_logging_test" onError="seq_logging_test_fault" trace="disable">
  <log description="Log message" level="custom">
    <property name="Development logging: " value="Message reaching seq_logging_test"/>
  </log>
  <sequence description="Process" key="seq_logging_test_processor"/>
  <header action="remove" name="To" scope="default"/>
  <property name="RESPONSE" scope="default" type="STRING" value="true"/>
  <property name="SC_ACCEPTED" scope="axis2" type="STRING" value="false"/>
  <property name="NO_ENTITY_BODY" scope="axis2" type="BOOLEAN" value="true"/>
  <property name="HTTP_SC" scope="axis2" type="STRING" value="200"/>
  <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
  <payloadFactory media-type="xml">
    <format>
      <response>
        <result>OK</result>
      </response>
    </format>
    <args/>
  </payloadFactory>
  <send/>
</sequence>
```

File: seq_logging_test_processor.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<sequence xmlns="http://ws.apache.org/ns/synapse" name="seq_logging_test_processor" onError="seq_logging_test_processor_fault" trace="disable">
  <log description="Log message" level="custom">
    <property name="Development logging: " value="Message reaching seq_logging_test_processor"/>
  </log>
  <iterate continueParent="true" expression="//jsonObject/event" sequential="true">
    <target>
      <sequence>
        <log description="Log message" level="custom">
          <property name="Development logging: " value="Message reaching seq_logging_test_processor iterator sequence"/>
        </log>
      </sequence>
    </target>
  </iterate>
  <log description="Log message" level="custom">
    <property name="Development logging: " value="Ending seq_logging_test_processor"/>
  </log>
</sequence>
```

The expected outcome (as I see it) would be to see the following output in wso2-esb-api_logging_test.log:
{{
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Message reaching seq_logging_test
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Message reaching seq_logging_test_processor
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-3] INFO api_logging_test Development logging: = Message reaching seq_logging_test_processor iterator sequence
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Ending seq_logging_test_processor
}}

However, the actual output is:
{{
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Message reaching seq_logging_test
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Message reaching seq_logging_test_processor
2017-xx-xx xx:xx:xx,xxx [-] [PassThroughMessageProcessor-2] INFO api_logging_test Development logging: = Ending seq_logging_test_processor
}}

That is, any and all logging appearing within the iterator's sequence is dropped (the message 'Message reaching seq_logging_test_processor iterator sequence' here). This is probably due to the fact that the log context is not (or incorrectly) propagated to the iterator's sequence.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
- [ ] /opt/java/bin/java -version
- [ ] java version "1.7.0_80"
- [ ] Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
- [ ] Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5010

**Comment by sachithKay** [comment]
Following suggestion has been made:
A suggestion is to propagate the service or api specific logger in the following method:

org.apache.synapse.util.MessageHelper.cloneMessageContext(MessageContext, boolean)

That methods seems to set up the cloned context for the iterator's inner sequence.

**Comment by malakaganga** [comment]
Log4j is no longer supported
