### ISSUE TITLE
Configuration values specified inside the call mediator of a sequence gets removed once you restart the Integration Studio

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-ei#4233]
**Description:**
Endpoint configuration values specified inside the call mediator of a sequence gets removed once you restart the Integration Studio

A CAR file was created after adding the endpoint information to the call mediator. This was deployed in EI using the management console. The sequence that was packed in the CAR file did not have the endpoint configurations.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.5.0

**OS, DB, other environment details and versions:**    
Ubuntu 18.04.2 LTS 

**Steps to reproduce:**

1. Create a ESB project from Integration Studio
2. Add a sequence
3. Add a call mediator and add endpoint information
4. Save the sequence
5. Close the IDE and open it again
6. The endpoint configurations will be missing from the call mediator

**Related Issues:**

**Comment by prabushi** [comment]
Related configuration. However, this was not reproducible on Ubuntu 16.04 with the latest Integration studio 6.5.0.
```
<api xmlns="http://ws.apache.org/ns/synapse" name="ResyncWithBank.xml" context="/resync">
   <resource methods="GET" url-mapping="/accounts">
      <inSequence>
         <call>
            <endpoint>
               <http method="GET" uri-template="http://localhost:8280/services/AccountDataService/accounts/updated"/>
            </endpoint>
         </call>
         <clone>
            <target>
               <sequence>
                  <call>
                     <endpoint>
                        <http method="GET" uri-template="http://localhost:8280/services/AccountDataService/accounts/updateflag"/>
                     </endpoint>
                  </call>
               </sequence>
            </target>
            <target>
               <sequence>
                  <property name="ContentType" value="application/json" scope="axis2" type="STRING"/>
                  <property name="messageType" value="application/json" scope="axis2" type="STRING"/>
                   <respond/>
                    </sequence>
                </target>
            </clone>
        </inSequence>
        <outSequence>
            <send/>
        </outSequence>
        <faultSequence/>
    </resource>
</api>
```
