### ISSUE TITLE
Unable to pick passwords from secure vault, when having multiple concurrent requests

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4238]
**Description:**
"wso2:vault-lookup('test.password')" is occasionally returning an empty string when concurrent requests are sent to the API.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
WSO2 ESB 4.8.1 Cluster (One Manager, Two Workers)
Java Version 1.7.0_79
OS - Linux
Shared Registry Database - MariaDB 10.1 / MYSQL 5.7

**Steps to reproduce:**

- [ ] Set up an ESB (Version:4.8.1) cluster with a manager node and two worker nodes. Use MariaDB for the database with default configurations.
- [ ] Add a password to the secure vault
- [ ] Write an API to retrieve and log the password specified in step 2.
- [ ] Write and execute a JMeter script to invoke the API specified in step 3. Use a thread group of 800 threads and set the ramp up period to two seconds.

Issue is reproducible with MuSQL database as well. 

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4956

**Comment by malakaganga** [comment]
Can not reproduce hence closing
