### ISSUE TITLE
[Improvement] In Validate mediator, Dynamic registry values not working with the resource attribute. Only work with Schema attribute.

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4242]
**Description:**
Used validate mediator by using the dynamic registry values for schema and resource attribute. But when we using the dynamic registry values
for schema attribute it worked properly as below.
```
<property name="xsdSchema" scope="axis2" type="STRING" value="gov:/TestSchema.xsd"/>  
<validate>
        <schema key="{$axis2:xsdSchema}"/>
        <resource key="gov:/referenceSchema.xsd" location="referenceSchema.xsd"/>
```

But if we use dynamic registry values for the resource attribute it didn't work properly and provided the 
error as below.
```
<property name="xsdSchema" value="gov:/TestSchema.xsd" scope="axis2" type="STRING"/>
<property name="xsdSchema" value="gov:/referenceSchema.xsd" scope="axis2" type="STRING"/>
<validate>
        <schema key="{$axis2:xsdSchema}"/>
        <resource key="{$axis2:xsdResource}" location="referenceSchema.xsd"/>
```

Error when using the above scenario.
```
[2016-10-11 15:42:10,134] ERROR - ResourceMap Registry item '{$axis2:xsdResource}' for location 'referenceSchema.xsd' is not an OMElement
[2016-10-11 15:42:10,134] ERROR - ValidateMediator Error creating a new schema objects for schemas : [Value {name ='null', expression =$axis2:xsdSchema}]
org.apache.synapse.SynapseException: Registry item '{$axis2:xsdResource}' for location 'referenceSchema.xsd' is not an OMElement
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tomas-Mrazek** [comment]
It should be working, according to [recent issue](https://github.com/wso2/product-ei/issues/2832)

But, it does not work for me on EI 6.4.0 for whatever reason...
