### ISSUE TITLE
Incorrect behavior of json-eval()

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4264]
**Description:**
Lets say we have following JSON payload

```
{
"objectIdFieldName":"OBJECTID",
"globalIdFieldName":"",
"fields":[

{ "name":"OBJECTID", "alias":"OBJECTID", "type":"esriFieldTypeOID" }
],
"features":[
{
"attributes":

{ "OBJECTID":2445710 }
}
]
}
```

Now, "json-eval($.features[0].attributes.OBJECTID)" correctly returns 2445710.

But when the features array is empty like below, the above JSON Path returns "[]" which is an incorrect behavior. IMO, it should return null or undefined.

```
{
"objectIdFieldName":"OBJECTID",
"globalIdFieldName":"",
"fields":[

{ "name":"OBJECTID", "alias":"OBJECTID", "type":"esriFieldTypeOID" }
],
"features":[
]
}
```

**Note**
We are using "com.jayway.jsonpath_0.8.1.wso2v1" bundle for handling json path in the ESB. Returns "[]" is the default behavior of the underlining library. However, we can upgrade this underlining library for the latest one.
However, With the current implementation, due to the underlying library, we cannot fix this issue without a major change.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4460

**Comment by GDLMadushanka** [comment]
jsonpath library upgraded to the latest version and it returns an empty string for not matching paths.
