### ISSUE TITLE
Issue while using the special characters in HTTP endpoint

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4269]
**Description:**
We need to send text containing characters such as "@" and "#".
Eg: "test tweet #wso2_esb @wso2_cep"

I created uri.var.status property and used the property in url-template with legacy encoding. Remaining part of URL is removed with the special character. Same issue occurs without the legacy-encoding also.

```
<call>
<endpoint>
<http method="post"
uri-template="legacy-encoding:

{uri.var.apiUrl}
/1.1/statuses/update.json?

{uri.var.status}
"/>
</endpoint>
</call>
```

Request - sample #test

Output

```
[2015-12-18 16:45:47,269] DEBUG - wire << "POST /1.1/statuses/update.json?status=sample%20 HTTP/1.1[\r][\n]"
[2015-12-18 16:45:47,269] DEBUG - wire << "Accept-Language: en-US,en;q=0.8[\r][\n]"
```

Expected output

```
[2015-12-18 16:45:47,269] DEBUG - wire << "POST /1.1/statuses/update.json?status=sample%20%23test HTTP/1.1[\r][\n]"
[2015-12-18 16:45:47,269] DEBUG - wire << "Accept-Language: en-US,en;q=0.8[\r][\n]"
```

The legacy and other encoding didn't support for special characters in HTTP Endpoint. Temporarily I was able to resolve by replacing the special character with encoded values.

https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java

```
@@ -246,6 +246,22 @@ public class HTTPEndpoint extends AbstractEndpoint {
try {
URI uri = new URI(template.expand());
evaluatedUri = uri.toString();
+ StringBuilder buf = null;
+ if (evaluatedUri != null) {
+ buf = new StringBuilder(evaluatedUri.length());
+ char focus;
+ for (int i = 0; i < evaluatedUri.length(); i++) {
+ focus = evaluatedUri.charAt;
+ if (focus == '#')

{ + buf.append("%23"); + }
else if (focus == '@')

{ + buf.append("%40"); + }
else

{ + buf.append(focus); + }
+ }
+ evaluatedUri = buf.toString();
+ }
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4395

**Comment by shafquatullah** [comment]
Do we have update on this issue.
The tweets with hash and @ symbol is not getting post

**Comment by lkokila** [comment]
A similar discussion is available in https://github.com/wso2/micro-integrator/issues/1968.

Adding + prior to the URI parameters {+uri.var.apiUrl} {+uri.var.status} should address the issue.
