### ISSUE TITLE
[Doc][Clustering the Message Broker Profile] Add time sync in to docs

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#428]
According to broker profile clustering coordinator needs time sync, it should be added to docs. Other wise it will have member reconnecting issue.

Please add a special note regarding that [1].

[1] https://docs.wso2.com/display/EI600/Clustering+the+Message+Broker+Profile

**Comment by praneesha** [comment]
Added the following note in the MB clustering doc of EI 6.0.0 & 6.1.0.

"It is vital to synchronize time across all the Broker nodes in the cluster to make them function properly."
