### ISSUE TITLE
JSON <-> XML conversion; handling null vs empty string

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4280]
**Description:**
Currently, ESB treats both null and empty strings in JSON values the same way. Look below
```json
{"test":null}
```
```json
{"test":""}
```
Both get converted into
```xml
<test/>
```
But the null value must be converted into XML Schema defined null value mentioned here [1]. ie into,
```xml
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" ></test>
```
[1] http://www.w3.org/TR/xmlschema-1/#xsi_nil

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-3491

**Comment by GDLMadushanka** [comment]
property combination is provided in https://wso2.org/jira/browse/ESBJAVA-3491
