### ISSUE TITLE
[MB 3.2.0][UI] When there's a large number of enqueue/dequeue values, numbers get overlapped

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4305]
**Description:**
Pre-Condition:-
A large number of enqueue/dequeue values should exist

1. Login to Analytics dashboard and view the Enqueue/Dequeue values

Expected Results:-

As the number grows the enqueue/dequeue values should be handled so that it won't overlap
Actual Results:-

Numbers get overlapped as the value grows (screenshot attached)
![Selection_045](https://user-images.githubusercontent.com/22365810/59484334-ecbfbe00-8e8e-11e9-9d98-17303e19c527.jpg)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Pack: MB 3.2.0 - M3
Setup: 2 MB Nodes and 2 Analytic Nodes
DB: PostgreSql
JDK: Oracle 1.8
Browser: Any

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYMB-19

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
