### ISSUE TITLE
[MB 3.2.0]Analytics Dashboard not implemented for tenant domain

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4306]
**Description:**
Steps to recreate the issue
1) Create a tenant user
2) Log in to Analytics Portal

Dashboard is not available in the Analytics Portal

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**   
JDK - IBM-JDK 8
OS - MB:Windows 2012 server, Analytics:RedHat 7
DB - Oracle 12c
Set up - 3 MB node cluster connected to 2 Analytics nodes 

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYMB-17

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
