### ISSUE TITLE
[MB 3.2.0] Inconsistent Enqueue and Dequeue counts in Analytics Dashboard

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4307]
**Description:**
Steps to recreate the issue
---------------------------------------
1) Configure analytics and MB 
2) Create a queue
3) Connect a subscriber and pubish data to that queue
4) Verify the message enqueue and dequeue count over time

Observations
--------------------
Observed an inconsistency in message counts, when filtering message counts by different time intervals ('Last Hour', Last Month' etc).

Example: Different enqueue and dequeue message counts appeared at each click on 'Last Month' filter as in the attached images.

![Stats01](https://user-images.githubusercontent.com/22365810/59484571-f269d380-8e8f-11e9-82e8-11d9b0e247a1.png)
![Stats2](https://user-images.githubusercontent.com/22365810/59484572-f269d380-8e8f-11e9-8e67-64684635f7ad.png)
![Stats3](https://user-images.githubusercontent.com/22365810/59484574-f269d380-8e8f-11e9-9625-13b688d18261.png)
![stats4](https://user-images.githubusercontent.com/22365810/59484575-f3026a00-8e8f-11e9-9848-0b27160b93eb.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
JDK - IBM-JDK 8
OS - MB:Windows 2012 server, Analytics:RedHat 7
DB - Oracle 12c
Set up - 3 MB node cluster connected to 2 Analytics nodes

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYMB-16

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
