### ISSUE TITLE
[EI61][DSS] Odata not functioning properly

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#431]
**Environment**
OS - ubuntu 15.10
JAVA -jdk 1.7
EI610 Alpha Pack
DB - H2
(Verified in the cluster as well)

**Steps**
1. Invoke an odata service ( http://ei.wso2.com:80/odata/mysqltest/persdb )

**Observation**
1. Reseived empty response to the client.
2. Observed following in the terminal
`TID: [-1234] [] [2017-03-30 12:45:38,761]  INFO {org.apache.synapse.mediators.builtin.LogMediator} -  To: /odata/mysqltest/persdb, MessageID: urn:uuid:ab423d7b-88e4-4e7f-b7e0-7ae8d550ce38, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body><xformValues/></soapenv:Body></soapenv:Envelope> {org.apache.synapse.mediators.builtin.LogMediator}`

**Comment by prabushi** [comment]
Fix in https://github.com/wso2/product-ei/pull/452 by VijithaE.
