### ISSUE TITLE
Wrong content in  log4j.properties file in saprk folder.

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4310]
**Description:**
Content in  *log4j.properties.template* file must be replace with the content in [1]
`HOME/repository/conf/analytics/spark/  `

[1] https://github.com/apache/spark/blob/branch-1.6/conf/log4j.properties.template

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYESB-211

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
