### ISSUE TITLE
Searching for messages

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4311]
**Description:**
1. In ESB Analytics selects a sequence.
2. Search a message using a query.
3. The query will give results if the attribute value contains in the first mediator of the sequence.
4. if the attribute contains in following mediators, results not get generates.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYESB-209

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
