### ISSUE TITLE
[RC4] Iterator mediator

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4312]
**Description:**
Iterator mediator splits the original payload into few payloads.
But in the esb analytics, message tracer view shows only the first payload out from iterator mediator.Not showing other payloads.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYESB-208

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
