### ISSUE TITLE
[RC4] Error while looking up Table Schema: [-1234:ORG_WSO2_ESB_ANALYTICS_STREAM_STATPERDAY] does not exist

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#4313]
**Description:**
I got following errors when i use the enterprise integrator analysics dashboard function .  

Failed to perform search on table: org_wso2_esb_analytics_stream_StatPerDAY: Error in index search: Error while looking up Table Schema: [-1234:ORG_WSO2_ESB_ANALYTICS_STREAM_STATPERDAY] does not exist	
Failed to perform search with aggregate on multiple tables: Error in index search: Error while looking up Table Schema: [-1234:ORG_WSO2_ESB_ANALYTICS_STREAM_STATPERHOUR] does not exist	

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**   
wso2ei-6.2.0 windows 64ibit  

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ANLYESB-212

**Comment by GDLMadushanka** [comment]
Analytics upgraded to a new product (Stream Processor)
