### ISSUE TITLE
Cannot redeploy artifacts as redeploy button is disabled

### ISSUE THREAD

**Issue by SangeethKarunaratne** [wso2/product-ei#4319]
**Description:**
When clicking on the selected composite application project, the redeploy button is disabled. See the attached image. It would be better to simply enable redeploy button all the time.

![redeploydisabled](https://user-images.githubusercontent.com/32442096/59501351-f78f4880-8eb8-11e9-8f82-2709d0f1fa02.png)

**References**
https://wso2.org/jira/browse/DEVTOOLEI-779

**Comment by rosensilva** [comment]
Duplicate https://github.com/wso2/product-ei/issues/4351
