### ISSUE TITLE
[Docs] [Configure with WSO2 Message Broker] Update correct configs 

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#432]
Please update doc [1] as follows;

1. Term "ESB" should be replaced with "Integration server"
2. Term "MB" should be replaced with "Broker"
3. Term "andes-client-3.0.1.jar" Replace with "andes-client-3.2.4.jar"
4. Update doc with MB cluster connection (Failover connection). Even though its available separately in MB docs, it should be included within EI documentation. Refer [2,3]

Sample config:

`connectionfactory.QueueConnectionFactory = amqp://admin:admin@clientID/carbon?failover='roundrobin'&cyclecount='2'&brokerlist='tcp://localhost:5673? retries='5'&connectdelay='50';tcp://localhost:5674?retries='5'&connectdelay='50';tcp://localhost:5675?retries='5'&connectdelay='50''`

**5. Update config path correctly**
Change "repository/conf/jndi.properties" as "conf/jndi.properties"

[1] https://docs.wso2.com/display/EI600/Configure+with+WSO2+Message+Broker
[2] https://docs.wso2.com/display/MB310/Handling+Failover
[3] https://www.yenlo.com/blog/a-clustered-setup-with-wso2mb-and-wso2esb

**Comment by praneesha** [comment]
Updated the following pages in EI 6.0.0 & 6.1.0 docs.

[1] https://docs.wso2.com/display/EI610/Configuring+with+the+Broker+Profile
[2] https://docs.wso2.com/display/EI610/Handling+Failover
