### ISSUE TITLE
One-way messaging scenario to consume messages from amazonMQ through [amqps], amqp 1.0, transport scheme then send it through a proxy service to a backend service 

### ISSUE THREAD

**Issue by issararab** [wso2/product-ei#4324]
**Description:**

Well I have a clear and easy scenario however I cannot find a way to make it work through the documentation. I have a service running somewhere producing Json messages to a queue in amazonMQ, an activeMQ broker deployed in AWS. in order to connect to this amazonMQ I have to use the amqps trqnsport scheme but this doesn't seem to be supported yet or I missing sthg in the documentation, the exmaple provided in the documentation only covers connection through tcp transport scheme and this is useless in this scenario. Then once the message consumed I want to send it through a proxy service to a backend service after parsing the payload to a certain data format.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
OS: Windows 10
WSO2 ei: version 6.5.0 
Integration Studio Editor: Integration Studio win64_6.5.0
  
**Steps to reproduce:**

No steps to mention, but I just tried to reproduce the scenario documented here: https://docs.wso2.com/display/EI640/Using+the+ESB+as+a+JMS+Consumer

just for testing, where I succeeded to deploy everything including the composite application of the proxy service. However, once I want to have a look at the list of services in WSO2ei dashboard, I keep receiving this message: 

ERROR - ServiceAdmin Unable to retrieve CApp file path 
java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/WSO2/Enterprise Integrator/6.5.0/repository/deployment/server/axis2services/Version.aar 

But this documented scenario has nothing to do with what I real want to run.

**Related Issues:**

**Comment by rstasiuliony** [comment]
How did you resolve this issue?
