### ISSUE TITLE
Remove old file-based registry samples from the documentation

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#4325]
**Description:**
We need to remove old file-based registry samples from the documentation.

Example:
 https://docs.wso2.com/display/EI650/Sample+11%3A+Using+a+Full+Registry-Based+Configuration+and+Sharing+a+Configuration+Between+Multiple+Instances

**Comment by nilminiwso2** [comment]
Removed the doc from EI 6.5.0 and EI 6.x.x docs.
