### ISSUE TITLE
Can not remove the default content type header added by call mediator in blocking mode with the property NoDefaultContentType

### ISSUE THREAD

**Issue by dilan-premarathna** [wso2/product-ei#4330]
The NoDefaultContentType property was introduced to remove the default content type added by the call mediator in blocking mode. In EI 6.4.0 we can not remove the ContentType header with the NoDefaultContentType property.

`<property name="NoDefaultContentType" value="true" scope="axis2"/>`

**Comment by apercova** [comment]
Hi @milindaperera 
I'm updating my wso2am-2.0.6 environment and this change is part of full update summary.
Does this change applies to am-2.6.0? if so,  could you help me to figure out where should I put the property change as update sumary description stands out.

![issue-ei-4330](https://user-images.githubusercontent.com/14076184/65474404-4d24ab00-de41-11e9-92c7-6fd6a37beb8a.png)

Thanks in advance.

**Comment by milindaperera** [comment]
Hi @apercova ,

Sorry for late reply. Hopefully you found the solution already.
Just for the record, you can use such parameters in APIM, by adding custom mediation sequence by following instructions in [1]

[1] https://docs.wso2.com/display/AM260/Adding+Mediation+Extensions#AddingMediationExtensions-CreatinganduploadingmanuallyintheAPIPublisher

Thanks,

**Comment by sajithaliyanage** [comment]
Added the above synapse fix(#642) to the support-2.1.7-wso2v111 branch(EI 6.5.0) and master of the wso2-synapse.
