### ISSUE TITLE
Property mediator does not build the payload when $body is used

### ISSUE THREAD

**Issue by NipunaDilhara** [wso2/product-ei#4341]
**Description:**
When a property mediator is used to capture the request payload body with expression="$body", scope="default" and type="OM" the property mediator does not recognize $body as content aware and hence won't built the payload. So the property mediator will not capture the body of request payload.

**Affected Product Version:**
ESB-4.9-wum, ESB-5.0, EI-6.4   

**Steps to reproduce:**
1. Create a proxy with a property mediator with expression="$body".
`<property name="requestXml"expression="$body"
                   scope="default"
                   type="OM"
                   description="requestXml"/>`
2. Use a log mediator to print the captured property
`<log level="custom">
          <property name="log" expression="get-property('requestXml')"/>
</log>`

**Comment by MH11097** [comment]
does this bug have solution? I faced it in EI-6.6.0
