### ISSUE TITLE
Update deployment diagrams to reflect the latest deployment patterns for the Analytics profile

### ISSUE THREAD

**Issue by RukshiW** [wso2/product-ei#4347]
Update the diagrams in [1] to reflect the change in the analytics profile (moving from being DAS-based to SP-based).

[1] https://docs.wso2.com/display/EI650/Clustering+the+Analytics+Profile

**Comment by sameeragunarathne** [comment]
@RukshiW is this added to the docs?

**Comment by RukshiW** [comment]
This is not yet done.

**Comment by RukshiW** [comment]
Sorry, the above comment is incorrect. The current documentation for 6.5.0 as well as 6.6.0 (including the diagram) describes how to set up the SP -based EI analytics cluster. Hence closing this.
