### ISSUE TITLE
Build the content awareness of the call template mediator dynamically

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#4354]
**Description:**
Call template mediator does not need to be content aware everytime. It should check whether any content aware mediator is available to build the content awareness. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/product-apim/issues/4486

**Comment by milindaperera** [comment]
This fix is absolutely wrong. Please revisit

**Comment by sameeragunarathne** [comment]
Adding more context,

connector template parameters are not evaluated for any of the xpaths or json paths if there is no any content aware mediation happens.

**Comment by milindaperera** [comment]
Connectors should be conditionally content aware and should check for parameters containing expressions.

**Comment by GDLMadushanka** [comment]
Please consider this issue also, when reverting https://github.com/wso2/product-ei/issues/3015
