### ISSUE TITLE
[EI61][Broker][JMS Message store]Message store queue will not create automatically

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#436]
**Environment**
Operating Systems : Redhat and Debian
Java Version : JDK1.8
Packs : EI610 Alpha Pack
Integration Server Setup: Cluster
Broker Setup: Cluster
DB - Oracle 12c

**Preconditions**
Broker should be configured with EI

**Steps to reproduce**
1. Create a jms message store in integration server and refer it via proxy/inbound
2. Invoke proxy/inbound

**Expected Result**
Message should store in JMS message store successfully

**Actual Result**
Messages not going to store in message store. Because queue is not available. Giving following error:
`
TID: [-1] [] [2017-03-30 17:00:30,184] ERROR {org.wso2.andes.client.AMQConnection} -  Throwable Received but no listener set: org.wso2.andes.client.AMQNoRouteException: Error: No Route for message [error code 312: no route] {org.wso2.andes.client.AMQConnection}`

**Note**: User should create queue in Broker and give the destination in message store. If this is expected behavior in broker, it should mention in doc [1].

[1] https://docs.wso2.com/display/EI600/JMS+Message+Store

**Comment by erandacr** [comment]
Statement similar to following should be added to [1] when configuring with WSO2 MB profile.
 "Queue named JMSMS should be created if you are using WSO2 MB"

[1] https://docs.wso2.com/pages/viewpage.action?spaceKey=EI610&title=Store+and+Forward+Using+JMS+Message+Stores

**Comment by praneesha** [comment]
Added the following note in both EI 6.0.0 & 6.1.0 docs in [1].

"Set the value of the the <java.naming.provider.url>  property to point to the jndi.properties file. In this case, <store.jms.destination> is a mandatory parameter. If you are using the Broker profile of WSO2 EI, you need to create a queue named 'JMSMS' using the Broker profile (i.e., the value you specify for the store.jms.destination). For instructions on creating the queue, see Managing Queues﻿."

[1] https://docs.wso2.com/display/EI610/Store+and+Forward+Using+JMS+Message+Stores
