### ISSUE TITLE
Update documentation on native JSON support for foreach mediator

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#4367]
**Description:**

Native JSON support is introduced in foreach mediator. wso2/wso2-synapse#1377 Adhering to this, we should update the Foreach mediator documentation.
https://docs.wso2.com/display/EI6xx/Foreach+Mediator

**New syntax :**
```
<foreach expression="xpath|jsonpath" [sequence="sequence_ref"] [id="foreach_id"] >
    <sequence>
      (mediator)+
    </sequence>?
</foreach>
```

**Opening sentence should change as follows.**
The ForEach mediator requires an XPath/JSONPath expression and a sequence (inline or referred). It splits the message into a number of different messages derived from the original message by finding matching elements for the XPath/JSONPath expression specified.

**Under configuration table, the row Expression should be changed as follows.**

The XPath/JSONPath expression with which different messages are derived by splitting the parent message. This expression should have matching elements based on which the splitting is carried out.

**Add the following under example (similar to [Iterate mediator](https://docs.wso2.com/display/EI6xx/Iterate+Mediator#IterateMediator-Examples)):**

Example  - 
```
<foreach id="foreach_1" expression="json-eval($.getQuote.request)">
        <sequence>
             <log level="full"/>
        </sequence>
</foreach>

```
Suggested Labels:

Type/Improvement

Related Issues:

#4121

**Comment by GDLMadushanka** [comment]
Changed the doc
