### ISSUE TITLE
Give a possibility to add variables in endpoints before "://" formula.

### ISSUE THREAD

**Issue by nowakowskiDev** [wso2/product-ei#4369]
**Description:**
There is very nice feature to add values through the variables in uri-template (in endpoint files). It's enough to define variable in sequence with "uri.var." prefix and we can use it in our endpoint, but **only** after the "**http://**" formula. Sometimes it is necessary to manipulate the type of your protocol: **HTTP** or **HTTPS**. It would be flexible and very helpful enabler to give possibility to add variables before "://" formula, for example:

http{+pref.var.protocol}://host-name{+uri.var.path}
... where pref.var.protocol contains "s" letter, or is empty depends on our need.

                                              **OR**

{pref.var.protocol}://host-name{+uri.var.path}
... where pref.var.protocol contains "https", or http depends on our need too.

**Affected Product Version:**
Version 6.2.0

**Steps to reproduce:**
Give a possibility to add variables in endpoints before "://" formula.

**Comment by Posejdon23** [comment]
+1 for this feature.

**Comment by Nirothipan** [comment]
Hi @nowakowskiDev 

This is still achievable with present configurations itself. For eg, you can define something like uri.var.protocol and configure it before the ://.

Please refer below 

```
<api xmlns="http://ws.apache.org/ns/synapse" name="testpath" context="/te">
   <resource methods="POST PUT GET">
      <inSequence>
         <property name="uri.var.protocol" value="http"/>
         <call>
            <endpoint>
               <http uri-template="{+uri.var.protocol}://www.mocky.io/v2/56f84ee5240000d1127866c8"/>
            </endpoint>
         </call>
         <respond/>
      </inSequence>
   </resource>
</api>
```

Thanks

**Comment by malakaganga** [comment]
Answered hence resolving
