### ISSUE TITLE
[EI 6.1][Analytics]Header shows carbon logo in tenant mode

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#437]
![screenshot from 2017-03-30 18-12-10](https://cloud.githubusercontent.com/assets/12966170/24504585/76775efa-1574-11e7-9978-808c7d4b0bee.png)

**Comment by isurusuranga** [comment]
I have tested in a latest pack and this issue is no longer reproduced.

**Comment by himasha** [comment]
Closing as per previous comment.
