### ISSUE TITLE
[ BPS ]Update Working with REST Tasks 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4370]
**Description:**
In the documentations of creating rest tasks, parameters we can only define either of the parameters,
 **Output Variable Name** or  **Output Variable Mapping** and Output Variable Name get higher precedence over the other.

We need to update all the documents and the screen shots ( tooling )related to this.

For eg:- https://docs.wso2.com/display/EI640/Working+with+REST+Tasks

**Comment by Nirothipan** [comment]
Eg:- https://docs.wso2.com/display/EI611/Invoking+a+REST+Endpoint+from+a+BPMN+Workflow#InvokingaRESTEndpointfromaBPMNWorkflow-AddingaRESTtasktoaprocess

**Comment by KasunAratthanage** [comment]
This issue can be closed. This page already deleted from EI 66x doc space,
