### ISSUE TITLE
Improve Script Mediator docs

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#4380]
We should improve our documentation around the available APIs in the script mediator with proper examples.

Related issue for EI7.

[1] https://docs.wso2.com/display/EI650/Script+Mediator
[2] https://github.com/wso2/docs-ei/issues/354

**Comment by chanikag** [comment]
We have introduced GraalVM as the default JS engine for the js language. The MI doc is changed according to that. https://mi.docs.wso2.com/en/latest/reference/mediators/script-mediator/#examples 
Hence this improvement is invalid now.
