### ISSUE TITLE
Event simualator Send button is not working in ESB-Analytics-5.0.0. latest WUM updated pack

### ISSUE THREAD

**Issue by praveennadarajah** [wso2/product-ei#4394]
Steps to reproduce:

- Start the latest WSO2 ESB Analytics 5.0.0. WUM updated pack.

- Create an event stream(Go to Main -> Stream -> Add Event streams)

- Fill the relevant information and click "Add Event Stream"

- Go to Main -> Stream and click "Simulate" action of the created stream.

- Enter the relevant information in the pop-up window and click "Send" button.

- We can see the message sent successfully pop window is not appearing.

Here the "Send" button is not working. So that unable to send messages.

**Comment by Ibaqu** [comment]
<img width="1743" alt="Screen Shot 2019-07-20 at 12 22 03 PM" src="https://user-images.githubusercontent.com/43578935/61623282-f1e50980-ac93-11e9-8564-e00cf88320fe.png">

**Comment by Ibaqu** [comment]
Releavant Repo : Carbon Analytics Common.
