### ISSUE TITLE
Expression view popup not shown properly on windows machines

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4398]
**Description:**

Please refer below screenshot. Expression view is not appearing and cannot type the expression. Changing resolution seems not working as well. 

![Image 818008178183](https://user-images.githubusercontent.com/4967046/61727467-1a483300-ad7c-11e9-896c-0aff950bdd28.png)

**Affected Product Version:**

Integration Studio with EI 6.5.0

**OS, DB, other environment details and versions:**   

Windows 10
Desktop machines with monitors.  

**Steps to reproduce:**

**Comment by rosensilva** [comment]
@abeykoon this happens due to the low resolution of the display. Can you please share the display resolution of this computer?
