### ISSUE TITLE
Error when exporting project as a CAR file

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4399]
**Description:**

Please see below screenshot. 

![2019-07-23](https://user-images.githubusercontent.com/4967046/61727872-c0943880-ad7c-11e9-9eda-34d458e02994.png)

**Affected Product Version:**

Integration studio with EI 6.5.0 

**OS, DB, other environment details and versions:**  

Windows 10  

**Steps to reproduce:**

Please follow steps at [1], and at the end try to export artifacts as a .CAR file. 

[1]. https://docs.wso2.com/display/EI650/Exposing+Several+Services+as+a+Single+Service

**Comment by prabushi** [comment]
@abeykoon 
We were able to reproduce this error when there is an xml error in the capp pom file. Please validate, correct and save the xml content on the file, and try to reopen the pom file again. 
You can use following steps to correct the pom,
1. Right click on the pom file -> Open With -> Text Editor.
2. Correct the xml content, save it, and close the window.
3. Re-open the pom file.

As an improvement, we will try to validate the xml content on the capp pom at the save operation.
