### ISSUE TITLE
can't deploy spring boot 2

### ISSUE THREAD

**Issue by abrostamian** [wso2/product-ei#4414]
**Description:**

because of spring boot 2.1.6 use tomcat version 8.5 i can't deploy my app in wso2ei server that use tomcat version 7
**Suggested Labels:**

spring boot 2.1.6
tomcat 8.5
tomcat 7
**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
tomcat 7 and tomcat 8.5
**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Closing since depricated
