### ISSUE TITLE
Dynamic parameters in connector are disappear when switch to design view

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4419]
In ejb2.0 connector, we have a requirement to add dynamic properties. When we add the parameters in the source view and switch to design view all the dynamic parameters disappear.

![ejb1](https://user-images.githubusercontent.com/6497326/62025649-6967eb00-b1f6-11e9-8c9e-00c4359ca703.png)
![ejb2](https://user-images.githubusercontent.com/6497326/62025650-6967eb00-b1f6-11e9-9e0d-573dfccfe706.png)
![ejb3](https://user-images.githubusercontent.com/6497326/62025651-6a008180-b1f6-11e9-89fe-7a3beea1bee7.png)

reference https://wso2.org/jira/browse/DEVTOOLEI-782

**Comment by GDLMadushanka** [comment]
moved to https://github.com/wso2/devstudio-tooling-ei/issues/647
