### ISSUE TITLE
remove wso2carbon-version.txt, version.txt files from profiles

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#442]
Currently broker, analytics, business-process profiles list wso2carbon-version.txt, version.txt files on bin folder.
Ex. wso2ei-6.1.0-ALPHA/wso2/broker/bin/version.txt

Since we have same files available on EI_HOME\bin folder, it looks like file duplicate. Better we remove these files from profiles

**Comment by milindaperera** [comment]
these version.txt files are used by wso2server.sh hence we need them in bin folder

**Comment by nandika** [comment]
There are required
