### ISSUE TITLE
Salesforce Connector UX is bad

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4422]
In Salesforce Connector, properties section, I cannot pick from available configs.

There is also a UX issue,

When I write the Config Ref other ways to fill the Configurations must be disabled

**Comment by dakshika** [comment]
https://wso2.org/jira/browse/DEVTOOLEI-333

**Comment by GDLMadushanka** [comment]
moved from https://github.com/wso2/devstudio-tooling-ei/issues/435
