### ISSUE TITLE
[Tooling] [DSS] Developer experience of creating a data service is not intuitive

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4426]
You need to know detailed information about the schema and exact output message/format you want to generate in order to create a data service. If there's a default mode where, a user cloud introspect the DB/table, select columns or specify the custom query (should be the last resort) and then automatically create an output mapping this will enhance developer experience quite a bit.

Creating an output mapping and ability to change your own message should be the last option for advanced users.

jira: https://wso2.org/jira/browse/DEVTOOLEI-1139

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/311
