### ISSUE TITLE
Remove unwanted files from profile/bin folders and Update the README files

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#443]
Remove unwanted files from broker, analytics, business-process profiles
Ex Should remove java2wsdl.sh, tcpmon.bat, java2wsdl.bat, wso2server.sh, wso2server.bat

README files on profile/bin folders should be updated with latest changes, those files still mention about wso2server.sh & wso2server.bat files

**Comment by nandika** [comment]
There files are required.
