### ISSUE TITLE
Clearer Error Message logs for JSON Schema Validation

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#4433]
**Description:**
When using the Validation Mediator, the validation errors being displayed lack information. Validation mediator needs to display more detailed error messages when using properties. 

**Affected Product Version:** 6.5.0

**Steps to reproduce:**
Step 1 : Create a proxy with a validation mediator. 
Step 2 : Upload a schema to validate a payload. 
Step 3 : Send the payload to the proxy

**Comment by Ibaqu** [comment]
Support Branch : https://github.com/wso2-support/wso2-synapse/pull/660
Public Branch : https://github.com/wso2/wso2-synapse/pull/1383

**Comment by GDLMadushanka** [comment]
fixed in https://github.com/wso2/wso2-synapse/pull/1383
