### ISSUE TITLE
Evaluating the possibility of changing the backend certificates depend on the request information

### ISSUE THREAD

**Issue by JanakaPushpakumara** [wso2/product-ei#4435]
**Description:**
 This issue created to evaluate the possibility of selecting the backend certificates for single backend depends on the request data coming from their client applications.

Ex: 
If the incoming request contains the element `<code>1<code>` we have to invoke the remote service https://remote.host/soap with the client certifkatce1, if the incoming request contains the element `<code>2<code>`we have to invoke the remote service https://remote.host/soap (same backend service) with the client certifkatce2 and so on.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
I don't think this is a common requirement. Usually, transport-level information like client certificate is related between the client and server host involved in the connection.
Also in the implementation, it's not straight forward for us to implement this as transport-level low-level connection establishment parameters cannot be controlled from the mediation logic.

**Comment by GDLMadushanka** [comment]
Closing the issue referring to the above comment
