### ISSUE TITLE
[DOC] Update the rsync location paths in the BPS cluster 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#445]
Locations provided for the rsync [1] should be corrected according to the BPS profile.

ex: 
1. ei_server_dir=~/wso2ei-6.0.0/wso2/repository/deployment/server/ should be corrected as "bps_server_dir=~/wso2ei-6.0.0/wso2/business-process/repository/deployment/server/

2. Tenant path should be corrected as " <EI_HOME>/wso2/business-process/repository/tenants"

[1] https://docs.wso2.com/display/EI600/Clustering+the+Business+Process+Profile#ClusteringtheBusinessProcessProfile-Deployingartifactsacrossthenodes

**Comment by praneesha** [comment]
Updated clustering docs of WSO2 EI 6.0.0 & 6.1.0 on the above.
