### ISSUE TITLE
[Tooling] Using bpel:doXslTransform in assign\copy action cause an error appearance in BPEL Editor

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4460]
for this assign action
```
<bpel:assign validate="no" name="XSLTans">
<bpel:copy>
<bpel:from>
<![CDATA[bpel:doXslTransform("xsltOne.xsl", $MainPartnerLinkRequest.payload)]]>
</bpel:from>
<bpel:to part="payload" variable="TransformedRequest"></bpel:to>
</bpel:copy>
</bpel:assign>
```
i have error

"The first argument ("xsltOne.xsl") to function doXslTransform in "bpel:doXslTransform("xsltOne.xsl", $MainPartnerLinkRequest.payload)" must be a literal (string)."

Process deploys and works fine, though. Error only appears in Problems View. Screenshot added.

![11 09](https://user-images.githubusercontent.com/6497326/62200164-79243280-b3a2-11e9-830f-ec6e837cb009.png)

**Comment by dakshika** [comment]
jira https://wso2.org/jira/browse/DEVTOOLEI-1098

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/639
