### ISSUE TITLE
[Tooling] Add support for custom XPath functions of ODE(BPEL)

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4462]
Add support for custom ODE XPath functions. Currently the source view of a BPEL sequence shows an error when custom ODE function is used.

For and example if we use following code snippet which used $ode:pid custom function,
```
<bpel:copy>
                <bpel:from expressionLanguage="urn:oasis:names:tc:wsbpel:2.0:sublang:xpath1.0">
                    <![CDATA[$ode:pid]]>
                </bpel:from>
                <bpel:to part="payload" variable="output">
                    <bpel:query queryLanguage="urn:oasis:names:tc:wsbpel:2.0:sublang:xpath1.0"><![CDATA[tns:result]]></bpel:query>
                </bpel:to>
</bpel:copy>
```
it shows a validation error saying

```
!!XPATH_INVALID_VARREF_PREFIX! [0=ode:pid, 1={1} ,2={2}, 3={3}, 4={4}, 5={5}]
```
![Screenshot](https://user-images.githubusercontent.com/6497326/62202801-99a2bb80-b3a7-11e9-9e77-4a9af18b7d73.jpg)

jira : https://wso2.org/jira/browse/DEVTOOLEI-1096

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/640
