### ISSUE TITLE
[Tooling] Adding option to create a registry resource of type XML

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4469]
**Description:**
Currently, we can add XSD, XSL and XSLT but not XML

**Suggested Labels:**
Improvement

**Affected Product Version:**
Integration Studio 6.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/DEVTOOLEI-829

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/637
