### ISSUE TITLE
[Tooling] Endpoint for Proxy shows as Anonymous even though an endpoint exists	

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4477]
**Description:**
Currently, when an endpoint type (e.g. Named endpoint) is saved through properties it's added to the UI as well as the source in properties view, the endpoint is still shown as Anonymous. Please refer attached

![Proxy_1](https://user-images.githubusercontent.com/8251118/62211997-84388c00-b3bd-11e9-903b-0f1697061f00.png)
![Proxy_2](https://user-images.githubusercontent.com/8251118/62211998-84d12280-b3bd-11e9-940d-d4d004e7bf62.png)
![Proxy_3](https://user-images.githubusercontent.com/8251118/62211999-84d12280-b3bd-11e9-96bd-09fbfbb1336c.png)

**Suggested Labels:**
Bug

**Affected Product Version:**
Integration Studio 6.5.0

**Steps to reproduce:**
1. Create proxy
2. Add endpoint from the registry
3. Save and close
4. Re-open -> endpoint type will be changed back to anonymous. 

**Related Issues:**
https://wso2.org/jira/browse/DEVTOOLEI-418

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/635
