### ISSUE TITLE
[Tooling] JWT parser 

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-ei#4479]
**Description:**
We are getting more request to support JWT to secure DSS and backend services. As of now, to parsing JWT we need to build a custom mediator and extract users information as user name, roles, DOB, etc.
It would be helpful if we could have OOTB mediator that could extract this information from JWT token with configurable properties like a path to value that we are looking for and use it for security purpose.

**Comment by GDLMadushanka** [comment]
moved to https://github.com/wso2/devstudio-tooling-ei/issues/644
