### ISSUE TITLE
Change delete caption to 'Delete from artifact.xml'

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4489]
Delete caption need to be changed to 'Delete from artifact.xml' instead of 'ESB artifact.xml file delete' see the attached screenshot

![deleteProxy](https://user-images.githubusercontent.com/6497326/62256966-102fcf80-b421-11e9-921c-87efe9c7be13.png)

**Comment by dakshika** [comment]
https://wso2.org/jira/browse/DEVTOOLEI-879

**Comment by GDLMadushanka** [comment]
moved to https://github.com/wso2/devstudio-tooling-ei/issues/643
