### ISSUE TITLE
Faulty proxy service doesn't show on the UI

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#449]
Steps:
1. Deploy a passthrough proxy service pointing to SimpleStcockeQuote axis2 service
Use axis2 service WSDL as publishin WSDL
2. Down the integrator and SimpleStcockeQuote axis2 service
3. Start the integrator
4. Check the stack trace - proxyservice deployment issue shows on the stack trace
5. Check the UI

Issue:
Faulty proxy service doesn't show on the UI. 
Note : ProxyService available on EI_HOME/repository/deployment/server/synapse-configs/default/proxy-services

**Comment by nandika** [comment]
Same behavior in ESB 5.0.0

**Comment by gvasanka** [comment]
DSS services shows as faulty services on the UI, check below image. But still faulty proxy services doesn't show on the UI. So Its better to have a consistency about how we show faulty services. Hence reopening.

![selection_216](https://cloud.githubusercontent.com/assets/3368635/24793298/23b93b9e-1b9f-11e7-9738-556f18f68c0b.png)

**Comment by VijithaEkanayake** [comment]
Hi Asanka,

Please see the resolution of https://wso2.org/jira/browse/CARBON-5368. The Same explanation applies here as well.
