### ISSUE TITLE
[Doc][JMS] Two way HTTP Back-end Call sample - proxy name change

### ISSUE THREAD

**Issue by jagathsisira** [wso2/product-ei#450]
In the below page, proxy name should be "Proxy1" in given command.

https://docs.wso2.com/pages/viewpage.action?spaceKey=EI610&title=WSO2+EI+as+a+JMS+Consumer

Two-way HTTP Back-end Call

Existing command:

ant stockquote -Dsymbol=WSO2 -Dtrpurl="jms:/JMStoHTTPStockQuoteProxy?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory&java.naming.provider.url=tcp://localhost:61616&transport.jms.ContentTypeProperty=Content-Type&transport.jms.DestinationType=queue&transport.jms.ReplyDestination=ResponseQueue" 

Correct Command: (JMStoHTTPStockQuoteProxy ==> Proxy1)

ant stockquote -Dsymbol=WSO2 -Dtrpurl="jms:/Proxy1?transport.jms.ConnectionFactoryJNDIName=QueueConnectionFactory&java.naming.factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory&java.naming.provider.url=tcp://localhost:61616&transport.jms.ContentTypeProperty=Content-Type&transport.jms.DestinationType=queue&transport.jms.ReplyDestination=ResponseQueue"

**Comment by nandika** [comment]
Fixed
