### ISSUE TITLE
[Doc][OdataSamples] Invocation URLs are not correct in Odata sample doc

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/product-ei#451]
In the sample requests provided in Odata samples mentions https as the protocol as below.
https://localhost:8280/odata/ODataSampleService/default/ACCOUNTS

It should be corrected as below for all the URLs
http://localhost:8280/odata/ODataSampleService/default/ACCOUNTS

https://docs.wso2.com/display/EI600/OData+Sample

**Comment by praneesha** [comment]
Updated the "OData Sample" doc in EI 6.0.0 & 6.1.0 docs as for an example in [1].

[1] https://docs.wso2.com/display/EI610/OData+Sample
