### ISSUE TITLE
[Tooling] Have an embedded tool or UI based utility to validate RXTs against schema

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4522]
**Description:**
I was adding a RXT definition and it kept on throwing "ERROR

{org.wso2.carbon.governance.generic.util.GenericArtifactUtil}
- Error occurred while installing the RXT configuration null
org.wso2.carbon.registry.core.exceptions.RegistryException: Violation of RXT definition in configuration file, follow the schema correctly..!!" error when I tried to save it.

Can we have a tool or something in RXT config UI to validate RXT against the schema on-the-fly?

**Suggested Labels:**
Improvement

**Related Issues:**
https://wso2.org/jira/browse/DEVTOOLEI-1076

**Comment by prabushi** [comment]
GREG artifacts such as RXTs are not supported in Integration Studio.
