### ISSUE TITLE
Security Policy filed should be mandatory for creating Secure Proxy type

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#4536]
**Description:**
Originally reported in https://wso2.org/jira/browse/DEVTOOLEI-982

Need to make the policy resource mandatory for the secured proxy in the proxy creation wizard.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/642
