### ISSUE TITLE
[EI 6.1][Analytics]Cannot start Analytics server in windows

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#454]
WINDOWS 7
JDK 1.8
Alpha pack

C:\Users\wso2\Desktop\61_secure\wso2ei-6.1.0-ALPHA\wso2ei-6.1.0-ALPHA\wso2\analytics\bin>wso2server.bat
The system cannot find the file specified.
JAVA_HOME environment variable is set to C:\Program Files (x86)\Java\jdk1.8.0_121
CARBON_HOME environment variable is set to C:\Users\wso2\Desktop\61_SEC~1\WSO2EI~1.0-A\WSO2EI~1.0-A\wso2\ANALYT~1\bin\..
Loading spark environment variables
Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

![image](https://cloud.githubusercontent.com/assets/12966170/24546503/2e5231b2-1629-11e7-95d0-b9344901581a.png)

**Comment by ushanib** [comment]
Same issue is there for Broker as well

**Comment by ushanib** [comment]
Same issue comes for ms4j and it mentions carbon_home is set incorrectly.

**Comment by ushanib** [comment]
Issue exists in Mar 30th Jenkin build as well

**Comment by nandika** [comment]
try with a fresh instance of cmd. Checked this and it works fine.

**Comment by nandika** [comment]
Checked this and works fine. snappy-java jar should be copied to avoid the snappy class not found exception.
