### ISSUE TITLE
[EI 6.1][BPS]ciphertool.bat file does not run in Windows.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#455]
WINDOWS 7
JDK 1.8
Alpha pack

C:\Users\wso2\Desktop\61_secure\wso2ei-6.1.0-ALPHA\wso2ei-6.1.0-ALPHA\wso2\business-process\bin>ciphertool.bat -Dconfigure
'ant' is not recognized as an internal or external command,
operable program or batch file.
Using CARBON_HOME:   C:\Users\wso2\Desktop\61_SEC~1\WSO2EI~1.0-A\WSO2EI~1.0-A\wso2\BUSINE~1\bin\..
Using JAVA_HOME:    C:\Program Files (x86)\Java\jdk1.8.0_121
Error: Could not find or load main class org.wso2.ciphertool.CipherTool

![image 1](https://cloud.githubusercontent.com/assets/12966170/24546862/c20d412a-162a-11e7-84cf-a11b16342d8f.png)

**Comment by ushanib** [comment]
Issue is there for all profiles when you run from outside the bin. broker, analytics, integrator

**Comment by ushanib** [comment]
Issue exists in Mar 30th Jenkin build as well

**Comment by nandika** [comment]
Check whether the ciphertool.bat file is same as https://github.com/wso2/product-ei/blob/master/distribution/src/scripts/profiles/ciphertool.bat.

This is the bat file that gets packaged into the latest build and issue does not exist with this script. also the unused ant build script executed is also removed now from script
