### ISSUE TITLE
Carbon UI bundle wizard not allow to finish , import existing project 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-ei#4555]
1.Select Carbon UI bundle project from Dashboard
2. Select Import Carbon UI bundle from workspace 
after proceed to next wizard page, following error occur and page not allow to perform finish.

"add execution Linstnerorg.eclipse.swt.SWTException: Widget is disposed"

https://wso2.org/jira/browse/DEVTOOLEI-1012

**Comment by rosensilva** [comment]
Not supported in Integration Studio 6.5.0 onwards
