### ISSUE TITLE
[Tooling] Docker Image Generation Fails in OS X With Docker Desktop

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-ei#4561]
**Description:**

Docker Image generation fails in OS X with Docker Desktop when "securely store Docker logins in mac OS key chain" checkbox is selected from Docker Desktop preferences.

Workaround is to uncheck the said checkbox.

**Suggested Labels:**

Integration Studio, Docker

**Suggested Assignees:**

**Affected Product Version:**
6.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Check the Docker Desktop preference "securely store Docker logins in mac OS key chain" 
- Try to build a docker image using a composite app project.
- It'll fail with bunch of errors.

**Related Issues:**

**Comment by prabushi** [comment]
Need to add this to documents https://medium.com/@dakshika/error-creating-the-docker-image-on-macos-wso2-enterprise-integrator-tooling-dfb5b537b44e
