### ISSUE TITLE
Coding consistency issue with BPMN development tooling

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4569]
**Description:**
Copying a service node in BPMN will remove the class attribute from the definition. Need to manually add the definition every time or recreate the whole service node.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.5.0 Integration Studio

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/633
