### ISSUE TITLE
[Docs]Elaborate a bit more on step 3 in creating a BPMN project in EI 6.5.0 docs

### ISSUE THREAD

**Issue by gayanlggd** [wso2/product-ei#4588]
**Description:**
Refer to step 3 in https://docs.wso2.com/display/EI650/Configuring+the+Start+Event+to+Submit+Data#ConfiguringtheStartEventtoSubmitData-CreatingaBPMNProject . It talks about selecting a reference project from the existing workspace, but for a beginner it might be a bit confusing. Additional explanation would be helpful.

**Suggested Labels:**
EI-6.5.0, Docs

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Updated the documentation
