### ISSUE TITLE
Proxy-Authorization Header Gets Corrupted on Concurrent Access

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#4589]
**Description:**
When using proxy profiles in EI and call an https backend service via proxy, sometimes ESB sender will inject Proxy-Authorization Header containing wrong credentials.
The Proxy-Authorization header generated by Apache HttpClient's BasicScheme.authenticate() [1][2] gets corrupted under extreme concurrent conditions (reproduced with JMeter using 10,000 threads) 

[1] https://github.com/apache/httpcomponents-client/blob/4.3.x/httpclient/src/main/java/org/apache/http/impl/auth/BasicScheme.java#L153
[2] https://github.com/wso2-support/wso2-synapse/blob/support-2.1.7-wso2v7/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ProfileProxyAuthenticator.java#L55

**Affected Product Version:**
ESB-5.0.0

**Steps to reproduce:**

Add the following proxy profile
```
<transportSender name="http" class="org.apache.synapse.transport.passthru.PassThroughHttpSender">
        <parameter name="non-blocking" locked="false">true</parameter>
        <parameter name="proxyProfiles">
            <profile>
                <targetHosts>*</targetHosts>
                <proxyHost>localhost</proxyHost>
                <proxyPort>3128</proxyPort>
                <proxyUserName>admin</proxyUserName>
                <proxyPassword>admin</proxyPassword>
            </profile>
        </parameter> 
```

And configure a squid proxy server on port 3128

Then do a load test with 10000 concurrent threads using JMeter.

**Comment by GDLMadushanka** [comment]
Closing hence fixed in the latest versions
