### ISSUE TITLE
[EI 61][Tooling] Cannot start tooling pack in windows when JDK is set to 1.8

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#459]
Pack : developer-studio-ei-eclipse-jee-mars-2-win64-x86_64-1.1.0.zip
JDK 1.8
Windows 7

![jdktooling](https://cloud.githubusercontent.com/assets/12966170/24550102/3b0f6724-163a-11e7-87f0-d94429f91201.png)

**Comment by nandika** [comment]
Please recheck. Tooling packs require JDK 8 (some functionality missing in 7 ) and works fine with JDK 8
