### ISSUE TITLE
[Doc] Image shows a bpelProject instead of a EchoAsyncProject in BPEL tutorial

### ISSUE THREAD

**Issue by gayanlggd** [wso2/product-ei#4597]
**Description:**
The image https://docs.wso2.com/display/EI650/Echoing+a+Message+Using+a+Simple+BPEL+Process?preview=/119133109/119133116/BPEL-diagram.png#EchoingaMessageUsingaSimpleBPELProcess-DeployingtheBPELWorkflow does not seem to be inline with the description where it shows a bpelProject instead of a EchoAsync Project.

**Suggested Labels:**
EI-6.5.0,BPEL,Doc

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nandika** [comment]
Attached a corrected image for the doc
![EchoAsyncProcess](https://user-images.githubusercontent.com/2908631/63768099-f208a280-c8ec-11e9-80ed-c96a4fb0b74d.png)

**Comment by GDLMadushanka** [comment]
Changed the doc.
