### ISSUE TITLE
Remove profile-creator.sh file from pack generated using profile-creator.sh command

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#461]
Steps:
1. Generated broker pack using profile-creator.sh file
2. Unzip the created broker pack and check the bin folder

Issue:
profile-creator.sh file exist on bin folder and better to remove it unless user can run it again

![selection_214](https://cloud.githubusercontent.com/assets/3368635/24551124/dde78b62-163e-11e7-837d-c79c630e81a9.png)

**Comment by nandika** [comment]
Improvement for next release

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/product-ei/pull/949.
