### ISSUE TITLE
EI Secure Vault credentials have limitation of max 30 characters - (via configuring the management console)

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/product-ei#4611]
**Description:**
When we are configuring the Secure Vault credentials via the management console it not allowing to enter more than 30 characters.

Need to make the regular expression configurable which is used to validate the password.

(We have provided that fix for the WSO2 EI 6.2.0 (wum updated pack) and EI 6.4.0 (already included) product versions in UI level validation )

**Suggested Labels:**
Secure Vault

**Suggested Assignees:**

**Affected Product Version:**
WSO2 EI 6.3.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**
Enter more than 30 characters password in the Secure Vault credentials via the management console.

Actual output : The Password length should be within 5 to 30 characters.
Expected output : Successfully update the password.

**Related Issues:**
https://github.com/wso2/product-ei/issues/2396

**Comment by GDLMadushanka** [comment]
Closing the issue since fixed in the latest release
