### ISSUE TITLE
[Doc][EI 6.5.0] Clustering Business Process Profile

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-ei#4629]
Hi,

The Nginx configurations described in [1] for clustering business process profile seems to be incorrect. The configurations of upstream ports for HTTP (ei.http.conf) is routing to port 8280 and the HTTPS configuration (ei.https.conf) is routing to the port 8243, which are not related to the Business Process profile.

The correct ports should be as follow

    HTTP (ei.http.conf) : 9765
    HTTPS (ei.https.conf) : 9445 (since the BP is having offset of 2)
    Can refer to older documentation, to make necessary changes [2][3].

Also, please make a note on the URLs defined for the Management console in the Nginx configurations section.

Configure Nginx to access the Management Console as https://mgt.as.wso2.com/carbon via HTTPS 443 port. To do this, create a VHost file (ui.as.https.conf) in the /etc/nginx/conf.d/ directory and add the following configurations into it

* The Management console URL will be as : https://ui.ei.wso2.com/carbon
* VHost file name will be as : ui.ei.https.conf

**References**
[1] : https://docs.wso2.com/display/EI650/Clustering+the+Business+Process+Profile
[2] : https://docs.wso2.com/display/CLUSTER44x/Clustering+Business+Process+Server+3.5.0%2C+3.5.1+and+3.6.0
[3] : https://docs.wso2.com/display/CLUSTER44x/Configuring+NGINX

**Comment by praveennadarajah** [comment]
The above changes are made in EI-6.5.0[1] and EI-6.x.x document space.

[1] https://docs.wso2.com/display/EI650/Clustering+the+Business+Process+Profile
[2] https://docs.wso2.com/display/EI6xx/Clustering+the+Business+Process+Profile
