### ISSUE TITLE
Changing default 8243 port for EI Management Console doesn't work

### ISSUE THREAD

**Issue by rissato** [wso2/product-ei#465]
Changed the catalina-server.xml default port to move it back to 9443 in 6.0.0:

`<Connector  protocol="org.apache.coyote.http11.Http11NioProtocol"
                port="9443"
                proxyPort="9443"`

I can see the startup message in the log file:

`[2017-04-01 11:57:56,087] [EI-Core]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://192.168.89.1:9443/carbon/`

But management console is not reachable in the specified address. The address is not reachable at all, no messages displayed in wso2carbon.log

**Comment by nandika** [comment]
Hi Rissato, 

Please try the EI 6.1 alpha pack.

**Comment by nandika** [comment]
EI 6.1 will be using 9443 port.

**Comment by rissato** [comment]
Ok, but that's not an option for production deployment. Should I go back to ESB 5.0.0 then?

**Comment by nandika** [comment]
Hi Rissato,

Are you in production deployment already ?. If you are going to deploy, please wait will EI 6.1.0 which will be released before 7th.

Regards
Nandika

**Comment by madhawa-gunasekara** [comment]
Hi Rissato, 

I guess your requirement is to separate management console from the passthru transport. If so you can follow the below instructions. 

1) First, you need to disable starting the random port in integrator.sh/integrator.bat
    `-Dtomcat.random.port.enable=false` 
2) Second, remove the Integrator Valve from the catalina-server.xml file
`<!--Valve className="org.wso2.carbon.integrator.core.IntegratorValve"/-->`
3) remove the proxy port in catalina server.xml file 
`proxyPort="8243"`

Thanks,
Madhawa

**Comment by nandika** [comment]
Resolving the issue as instructions have been provided

**Comment by rissato** [comment]
Just confirmed the solution above and it works. Were able to access EI mgt console remotely.
