### ISSUE TITLE
Aggregate Mediator doesn't work properly for filter values using "correlateOn" property.

### ISSUE THREAD

**Issue by pedroaoguimaraes** [wso2/product-ei#4654]
**Description:**
I was using the Aggregate mediator to filter some results. But for the cases where I had a **false** and **true** results from a boolean xpath. The elements which result in a false validation kept been introduced in my final result when they should be filtered based on **correlation expression** defined.

I checked the synapse code and I didn't found any code related to skip the aggregation where the correlation expression resulted in false. Link https://github.com/wso2/wso2-synapse/blob/8f71b387353b0b8d2a3e49ab8091dec7eec108be/modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java#L207

PS: I didn't check the old and new versions. I just made the test in the 6.4.0 and 6.4.x with wum update 1567533393735)

**Suggested Labels:**
Aggregate Mediator

**Affected Product Version:**
EI-6.4.0. 

**Steps to reproduce:**
1. Use iterate Mediator to call any service
2. Use the **Aggregate Mediator** and define the **Correlation Expression** to filter empty values. Ex: boolean($body//item/text())
3. The expression which results in false or true will be added and it will not be filtered as it should be. (https://docs.wso2.com/display/EI640/Aggregate+Mediator#AggregateMediator-Configuration)

**Comment by keerthu** [comment]
Fixed in latest branch. https://github.com/wso2/wso2-synapse/pull/1398
