### ISSUE TITLE
Wrong folder mentioned to add groovy jar when creating script task

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#4655]
**Description:**
When you follow the script task documentation, it mentions the wrong the folder to put the groovy jar.
https://docs.wso2.com/display/EI640/Script+Task

> JDK comes with default support for JavaScript. However, to execute Groovy, you need to add the JAR file for the Groovy Engine to the <EI_HOME>/wso2/lib/endorsed directory and restart the Business Process profile of WSO2 EI to try this sample.

In the above, **<EI_HOME>/wso2/lib/endorsed** should be changed to **<EI_HOME>/wso2/lib/bps-endorsed**

Please change the 6.5.0 documentation as well.

**Suggested Labels:**

Documentation

**Comment by arunans23** [comment]
We need to replace the jar as well. The documentation points to an older version of the jar.
The following jar should be added. (groovy-all_2.4.7.jar) (Please rename the below .zip to .jar)
[groovy-all_2.4.7.zip](https://github.com/wso2/product-ei/files/3595954/groovy-all_2.4.7.zip)

**Comment by praveennadarajah** [comment]
The above changes are made in EI-6.4.0[1], EI-6.5.0[2] and EI-6.x.x[3] document space. Hence closing the issue.

[1] https://docs.wso2.com/display/EI640/Script+Task
[2] https://docs.wso2.com/display/EI650/Script+Task
[3] https://docs.wso2.com/display/EI6xx/Script+Task
