### ISSUE TITLE
[EI610][msf4j][Windows] MSF4J not going to start in windows

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#467]
**Environment**
Operating Systems : Windows 8
Java Version : JDK1.8
Packs : EI610 30th jenkins build pack
EI Setup: Standalone
DB - H2 (Default)

**Steps to reproduce**
  Start msf4j in windows.

**Expected Result**
  MSF4J should be started

**Actual Result**
  Getting an error:

`CARBON_HOME is set incorrectly or CARBON could not be located. Please set CARBON_HOME.`

**Comment by erandacr** [comment]
This issue was fixed with https://github.com/wso2/product-ei/commit/bc0504a2be84d36b78f0395fb82944b55b9250d7

You can go ahead with EI-MSF4J testing using this build [1]

[1]. https://wso2.org/jenkins/job/products/job/product-ei/67/org.wso2.ei$wso2ei/
