### ISSUE TITLE
Deadlock in WSO2 MB Client

### ISSUE THREAD

**Issue by Ibaqu** [wso2/product-ei#4684]
**Description:**
Threads have deadlocked due to the fact that JMS transport and Andes client implementation both lock on JMS session.

Fix has to be ported from Andes 3.3.4
https://github.com/wso2/andes/pull/973/commits/93b3972ccc6f70e1f07bde2730d50902372a67b2

**Comment by sameeragunarathne** [comment]
Closing since this is fixed in latest andes
