### ISSUE TITLE
max.store.connection.attempts config is missing for sampling processor

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#4690]
**Description:**
JMS message forwarding processor has a config to retry to connect to JMS broker upon a temporary failure called max.store.connection.attempts. By default it is -1, which means if JMS broker went down or disconnected, it will retry in an exponential backoff manner forever until it get successfully connected to the configured message store (Broker) [1].

However, this feature is not available in message sampling processor [2]. If a production customer faced an temporary connection break to the broker, until someone manually reactivate the message processor, messages are not processed. Customer will notice it usually after an escalation.

Shall we implement the feature?
This includes

1. WEB UI development to add the new parameter
2. Adding parameter to Integration Studio
3. Modify synapse schema to validate new property

[1]. https://docs.wso2.com/display/EI640/Scheduled+Message+Forwarding+Processor
[2]. https://docs.wso2.com/display/EI640/Message+Sampling+Processor

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 6.4.0

**Comment by abeykoon** [comment]
This is fixed by https://github.com/wso2/wso2-synapse/pull/1425
