### ISSUE TITLE
[Doc] Add property "reverseProxyMode

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/product-ei#4691]
**Description:**
Modify the documentation to add the "reverseProxyMode" property under **Configuring passthru-http.properties** property table in [https://docs.wso2.com/display/EI650/Tuning+the+HTTP+Transport](https://docs.wso2.com/display/EI650/Tuning+the+HTTP+Transport)

| Property  | Description |
| ------------- | ------------- |
| reverseProxyMode  | This reverseProxyMode was introduced to avoid the Load Balance exposing for its own web service when REST call was initiated  |

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sameeragunarathne** [comment]
fixed the doc.
