### ISSUE TITLE
Docker project create docker image icon too small

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4696]
**Description:**
Docker project create docker image icon is too small and is positioned to the top righthand corner and hence difficult to locate.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

Integration Studio 7.0.0 

**Steps to reproduce:**

**Related Issues:**

![Docker](https://user-images.githubusercontent.com/2908631/66321930-f3db7200-e93e-11e9-9acd-69508b470952.png)

**Comment by prabushi** [comment]
Moved to https://github.com/wso2/devstudio-tooling-ei/issues/607
