### ISSUE TITLE
EI7 Platform-Independend distribution not available

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#4698]
**Description:**
There's no freely available zip file which can be downloaded and unpacked in order to try out EI7. Only OS specific installers are available. Typical developer without Administrator access to his working machine is not able to install EI7.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI7

**OS, DB, other environment details and versions:**    
All OS

**Steps to reproduce:**
Go to WSO2 download page.
Try to find Zip distribution.
Nothing is there.

**Related Issues:**

**Comment by isudana** [comment]
Hi Marko,

EI 7.0.0 consists of 3 different approaches to doing the integration. In the Enterprise Integrator home page, we have given the option to install all 3 components of EI through the installer. Binaries of individual components can be found from the dedicated web page for each component. 

The following are the links.

**Ballerina Integrator**
https://wso2.com/integration/ballerina-integrator/

Ballerina is a programing language but not a server runtime. So we need to use the installer to install it into the development environment. The runtime binary will be generated when the integration developer compiles the written code.

**Micro Integrator**
Download binary from;
https://wso2.com/integration/micro-integrator

**Streaming Integrator**
Download binary from;
https://wso2.com/integration/streaming-integrator

**Comment by isudana** [comment]
Please re-open if you need further information on this.
