### ISSUE TITLE
NullPointer Exception when using fn:replace() in EI-6.1.1

### ISSUE THREAD

**Issue by praveennadarajah** [wso2/product-ei#4701]
**Steps to reproduce:**

1. enable XPath 2.0 in synapse.properties file
2.Create a proxy using replace function as below
```
<?xml version="1.0" encoding="UTF-8"?><proxy xmlns="http://ws.apache.org/ns/synapse" name="Issue01" startOnLoad="true" statistics="disable" trace="disable" transports="http,https">
    <target>
        <inSequence>
            <log>
                <property xmlns:fn="http://www.w3.org/2005/xpath-functions" expression="fn:replace('Bella Italia', 'l', '*')" name="fn:replace() =="/>
            </log>
            <drop/>
        </inSequence>
    </target>
    <description/>
</proxy>
```

3. Invoke the proxy.

Following error will be thrown

TID: [-1234] [] [2019-10-08 05:39:19,344] ERROR {org.apache.synapse.util.xpath.SynapseXPath} -  Evaluation of the XPath expression fn:replace(syn:get-property('responseResourceUrl'), '^.*/', '') resulted in an error {org.apache.synapse.util.xpath.SynapseXPath}TID: [-1234] [] [2019-10-08 05:39:19,344] ERROR {org.apache.synapse.util.xpath.SynapseXPath} -  Evaluation of the XPath expression fn:replace(syn:get-property('responseResourceUrl'), '^.*/', '') resulted in an error {org.apache.synapse.util.xpath.SynapseXPath}
javax.xml.transform.TransformerException: java.lang.NullPointerException at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204) at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208) at org.apache.xpath.XPath.execute(XPath.java:337) at org.apache.xpath.XPath.execute(XPath.java:303) at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121) at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91) at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176) at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221) at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533) at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367) at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:346) at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:108) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37) at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69) at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:260) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:775) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:282) at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554) at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)Caused by: java.lang.NullPointerException at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197) ... 32 more--------------- linked to ------------------javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: java.lang.NullPointerException at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:189) at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:221) at org.apache.synapse.util.xpath.SynapseXPath.evaluateDOMXPath(SynapseXPath.java:533) at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:367) at org.apache.synapse.mediators.builtin.PropertyMediator.getResultValue(PropertyMediator.java:346) at org.apache.synapse.mediators.builtin.PropertyMediator.mediate(PropertyMediator.java:108) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37) at org.apache.synapse.config.xml.SwitchCase.mediate(SwitchCase.java:69) at org.apache.synapse.mediators.filters.SwitchMediator.mediate(SwitchMediator.java:134) at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:260) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.mediateFromContinuationStateStack(Axis2SynapseEnvironment.java:775) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:282) at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:554) at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:188) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:262) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)Caused by: javax.xml.transform.TransformerException: java.lang.NullPointerException at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:204) at org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208) at org.apache.xpath.XPath.execute(XPath.java:337) at org.apache.xpath.XPath.execute(XPath.java:303) at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121) at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91) at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176) ... 26 moreCaused by: java.lang.NullPointerException at org.apache.xpath.jaxp.JAXPExtensionsProvider.extFunction(JAXPExtensionsProvider.java:197) ... 32 more

**Comment by wandaPriatna** [comment]
how can you solve this issue cause i still got same error
