### ISSUE TITLE
Unable to consume messages from a MB queue

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4704]
**Description:**

This is a known issue in WSO2 MB 3.1.0. Stale subscriber is created for the queue restricting consumers to read off a queue. That is, subscription objects retained in `AndesSubstriptionStore` even if the subscription is removed (connection is closed). 

As a fix, a scheduled thread is introduced to clean off such objects. This will prevent messages being accumulated in such invalid objects. 

Affected version : MB 3.1.0

**Comment by abeykoon** [comment]
To test this, using a similar scheduled task, made active subscriptions stale by setting `hasExternalSubscription = false`. The solution should remove them with a WARN.

**Comment by abeykoon** [comment]
This is fixed with subscription store re-write of MB 3.2.0

**Comment by abeykoon** [comment]
For 3.1.0 fixed with PR: https://github.com/wso2-support/andes/pull/199

**Comment by sameeragunarathne** [comment]
Closing this issue since this is fixed with MB 3.2.0 onwards.
