### ISSUE TITLE
SERVER_IP, SERVER_HOST properties cannot be read from $ctx

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#4720]
**Description:**

In a mediation flow, SERVER_IP and SERVER_HOST are set as local Registry entries. Hence we cannot retrieve those values using $ctx. Rather we have to use get-property() method to retrieve those values.

In the [documentation](https://docs.wso2.com/display/EI650/Generic+Properties#GenericProperties-SERVER_IP), the property SERVER_IP is mentioned with the scope 'synapse'. It might be confusing for the user. Hence it should be changed properly to convey the message that it is a registry local entry and can only be retrieved with get-property('SERVER_IP') or get-property('registry', 'SERVER_IP').

**Comment by GDLMadushanka** [comment]
Closing the issue since we are not recommending to use $ctx in new releases.

**Comment by GDLMadushanka** [comment]
Changed the documentation
