### ISSUE TITLE
[DOC]  Log4j2 Scenario configurations User Guide[EI 6.6.0 ]

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/product-ei#4722]
**Description:**
This documentation should need to review.

https://docs.google.com/document/d/1huB8LcM--anl9H3sz-579qEtiWoEYYkhiPvY-_nrBIQ/edit?usp=sharing

**Suggested Labels:**
log4j2.properties /  logs

**Suggested Assignees:**	
Nilmini Perera

**Affected Product Version:**
WSO2 EI 6.6.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Comment by sameeragunarathne** [comment]
@KasunAratthanage is this added to the docs now?

**Comment by KasunAratthanage** [comment]
Yes. You can find the documentation in EI 6.6.0 doc space. Please find the following links.

Enable wire logs in Log4j2 properties 
https://docs.wso2.com/display/EI660/Logs+in+WSO2+EI+6.6.0

Enable correlation logs in Log4j2 properties 
https://docs.wso2.com/display/EI660/Working+with+Observability

Enable Log4j2 properties per Proxy services
https://docs.wso2.com/display/EI660/Enabling+per-Service+Logs+for+Services

Enable Log4j2 properties per APIs
https://docs.wso2.com/display/EI660/Enabling+per-API+Logs+for+APIs
