### ISSUE TITLE
Latency due to HostName Resolving

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#4723]
**Description:**
Synapse runtime uses InetSocketAddress.getHostName() method, which triggers a name service reverse lookup if the address was created with a literal IP address. Because of this, latency is observed in EI hosted services.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
All upto 6.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Reopened the issue since we need to address the latency during resolving hostname in [1]
[1] https://github.com/wso2/wso2-synapse/blame/master/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java#L84
