### ISSUE TITLE
Environment variable support for configuration files

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#4724]
**Description:**
Currently following files support parameterize  configurations with system properties:
1. axis2.xml
2. carbon.xml
3. master-datasource.xml

example: 
```xml
<HostName>${system_server_hostname}</HostName>
```

To make EI more container friendly we **must** support to parameterize over environment variables as well.
Precedence should be as follows: Environment variable, System property, Hard coded value
 
This is small fix to support above listed files. 
Ultimately we need to support this for all the configurations files that might be changed per environment.

Following files are must:
1. axis2.xml
2. carbon.xml
3. master-datasource.xml (files in datasource directory)
4. user-mgt.xml
5. jndi.properties

Optionally:
1. carbon.properties (optional)

**Comment by abeykoon** [comment]
We have some capabilities in MI. @malakaganga can provide details. 
By the way, EI is not container friendly. If you go with containers, MI needs to be the choice.

**Comment by milindaperera** [comment]
In terms of server configuration both EI and MI not container friendly. Hence we need to ability to parameterize config (not synapse configuration) with above method
