### ISSUE TITLE
Add webhooks support for EI

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4726]
Webhooks is a popular way to notify events in REST way. 
EI should be able to act as a `webhooks provider` (notifier) as well as `webhooks listener`. 
 
https://culttt.com/2014/01/22/webhooks/
https://snipcart.com/blog/what-are-webhooks-explained-example

**Comment by stefanonegri** [comment]
hi, any update on this; will this feature be part of one of the next release?

**Comment by abeykoon** [comment]
@Nirothipan @sajithshn We are developing some framework around this right? Could you please provide an update?

**Comment by Nirothipan** [comment]
APIM 4.0 will support this. Please refer http://wso2-oxygen-tank.10903.n7.nabble.com/APIM-Streaming-API-support-in-APIM-4-0-0-Webhooks-td162257.html
