### ISSUE TITLE
In a clustered environment, shutting down one node will deactivate message processors scheduled in the second node

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#4744]
**Affected Product Version:**
EI. 6.4.0

**Steps to reproduce:**

1. Create a 2 node cluster
2. Set hazelcast.shutdownhook.enabled=false
3. Sync deployment folder in 2 nodes
4. Add a message processor to node 1
5. Start node1 and wait till all the tasks get scheduled in node1
6. Open mgt console and check whether the message processor is activated.
6. Start node2 and once started successfully shut down the same node.
7. Refresh mgt console

**Comment by VirajHasitha** [comment]
Duplicated git issue can found in https://github.com/wso2/product-ei/issues/2999

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1220/files
