### ISSUE TITLE
Dropping payload of "multipart/form-data" by ESB in mediation

### ISSUE THREAD

**Issue by keerthu** [wso2/product-ei#4750]
**Description:**
When sending the MIME message (Multipart/form-data) with HttpCoreNIOListener enabled, unable to fetch the contents of the file inside SOAP body. The message body which relies in message context is an empty message without soap body.

**Affected Product Version:**
ESB 5.0.0

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1018
