### ISSUE TITLE
Endpoint $SYSTEM resolver is not working correctly for System variables containing "." in the name

### ISSUE THREAD

**Issue by fjunior87** [wso2/product-ei#4759]
**Description:**
If we try to use the $SYSTEM resolver with a System variable like this: "app.ep.myep", it fails with an Exception saying the Environment Variable is not found.

**Works**
```
<endpoint xmlns="http://ws.apache.org/ns/synapse" name="JSON_EP">
  <address uri="$SYSTEM:VAR"/>
</endpoint>
```

**Does not Work**
```
<endpoint xmlns="http://ws.apache.org/ns/synapse" name="JSON_EP">
  <address uri="$SYSTEM:apps.ep.myep"/>
</endpoint>
```

As I could see the issue is because the ResolverFactory is using a Regex to get the Resolver, and it is not considering the special chars.

**Suggested Labels:**
BUG

**Suggested Assignees:**

**Affected Product Version:**
Tested on WSO2 EI 6.5.0
**OS, DB, other environment details and versions:**

**Comment by malakaganga** [comment]
In shell variables in UNIX, the name of a variable can contain only letters (a to z or A to Z), numbers ( 0 to 9) or the underscore character ( _). So we are only supporting these characters as variable names

You can change the name into apps_ep_myep
