### ISSUE TITLE
Problem with Ballerina documentation

### ISSUE THREAD

**Issue by igkononov** [wso2/product-ei#4767]
To whom it may concern,

I visited ballerina integrator documentation - https://ei.docs.wso2.com/en/latest/ballerina-integrator/get-started/introduction/.

And in this documentation there are any descriptions about next steps after creating Ballerina service.
E.g., as a developer, I would like to know, how to deploy Ballerina service into API Management Gateway or MicroGateway. Is it possible or not. Or there is only possibility to deploy Ballerina service as common API and publish this API in API Manager.

Can you, please, clarify this situation.

Thanks in advance.

**Comment by arunans23** [comment]
@igkononov 
As you know, [Ballerina ](https://ballerina.io/) is a language, and it is our code driven approach to integration. Via Ballerina Integrator, we are providing the environment (connectors and developer tools) to enhance the capabilities of the language. Here we are mainly concerned about how you can write services using Ballerina and how you can run and deploy them. 

If you want to deploy the ballerina services using MicroGateway, you need to have a look at MicroGateway documentation. https://docs.wso2.com/display/MG300/API+Microgateway+Documentation
