### ISSUE TITLE
Enterprise Integrator 7.0.0 and ESB

### ISSUE THREAD

**Issue by igkononov** [wso2/product-ei#4768]
Hello!

I downloaded WSO2 Enterprise Integrator 7.0.0 and installed on my MacOS.
But what I can see - there is only micro-integrator. Where I can find ESB?

Is in API Manager 3.0.0 has embedded EI? If YES, could you, please, add this info to documentation.

Thanks in advance.

**Comment by Nirothipan** [comment]
Hi @igkononov 

Basically, Micro Integrator is the cloud native version of ESB or simply a containerized version of ESB.

APIM is a different product which you need to install and it is not included in EI

**Comment by igkononov** [comment]
Hi @Nirothipan 

Thanks for your answer.
