### ISSUE TITLE
Integration Studio - problem with documentation

### ISSUE THREAD

**Issue by igkononov** [wso2/product-ei#4770]
Hello.

I try to use Integration Studio documentation - https://ei.docs.wso2.com/en/latest/micro-integrator/develop/WSO2-Integration-Studio/.

But there is any information about deploying created services to API Manager Gateway.
Is it possible to do it, or there is only possibility to run created service in micro-integrator and publish it in API Manager as common API?

Can you, please, clarify this question.

Thanks in advance.

**Comment by Nirothipan** [comment]
Integration Studio is specially designed to develop the artifacts related with ESB . i.e you might deploy the artifacts to Enterprise Integrator or Micro Integrator ad not for APIM. APIM is another WSO2 product.

**Comment by igkononov** [comment]
Hi @Nirothipan 

Thanks for your answer.
