### ISSUE TITLE
SecureVault username password encryption not supported with RabbitMQStore

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/product-ei#4772]
When we use secure vault to encrypt the username/ password fields when configuring RabbitMQMessageStore as bellow, It is not decrypting the values as expected.

   <parameter name="store.rabbitmq.username">{wso2:vault-lookup('MQ.username')}</parameter>
   <parameter name="store.rabbitmq.password">{wso2:vault-lookup('MQ.Password')}</parameter>

**Comment by malakaganga** [comment]
Duplicate: https://github.com/wso2/product-ei/issues/4761
Fixed with: https://github.com/wso2/wso2-synapse/pull/1441
