### ISSUE TITLE
Cannot login to management console after MacOS catalina update

### ISSUE THREAD

**Issue by arunans23** [wso2/product-ei#4775]
**Description:**

After Mac Catalina OS upgrade, cannot login to management console.
![image](https://user-images.githubusercontent.com/17047910/68935204-3e61d100-07be-11ea-8e6b-8835772b259b.png)

This behaviour could be because Apple has added new requirements for trusted certificates.
TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

**Related Issues:**

https://github.com/wso2/carbon-kernel/issues/2320

**Comment by malakaganga** [comment]
Fixed with kernel 4.5.3
