### ISSUE TITLE
[Doc] Synapse unit test framework docs

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-ei#4787]
**Description:**
This issue is to add the docs for the synapse unit test framework implemented with https://github.com/wso2/product-ei/issues/3756. need to add confluence docs as same content as https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-unit-test-suite/

**Comment by praveennadarajah** [comment]
Synapse unit test framework implementation details added to [1]. Hence closing the issue.

[1] https://docs.wso2.com/display/EI6xx/Working+with+WSO2+Integration+Studio#WorkingwithWSO2IntegrationStudio-TestingESBartifacts
