### ISSUE TITLE
Add docs how to enable wirelogs in bps profile

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/product-ei#4803]
**Description:**
We need to register the **httpclient-wire-content** logger in the loggers section in the log4j2.properties file in order to enable the wirelogs in the bps profile. 
```
logger.httpclient-wire-content.name=org.apache.http.wire
logger.httpclient-wire-content.level=DEBUG
```

**Comment by GDLMadushanka** [comment]
Updated the documentation in https://docs.wso2.com/display/EI6xx/Troubleshooting+the+Business+Process+Management+Profile
