### ISSUE TITLE
Latency calculation in Synapse has error.

### ISSUE THREAD

**Issue by AathmanT** [wso2/product-ei#4808]
**Description:**
The latency calculated in synapse has significant difference when compared to Jmeter. This is not due to network latency but, due to a calculation error.

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
All upto 6.5.x

**OS, DB, other environment details and versions:**    
OS - Ubuntu 18.04 64 bit
WSO2-EI 6.5.0

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
Could you please elaborate more on how to reproduce this issue?
Did you use get-property('SYSTEM_TIME') to take time stamps and then subtract start from the end?

**Comment by AathmanT** [comment]
**Steps to reproduce**
1. Send requests to EI from Jmeter 
2. Monitor the Avg Latency value displayed by Jmeter and the Avg Latency exposed in the MBean.
You will notice both values differ drastically.

The time values are taken from System.currentTimeMillis() method.
The implementation is already there in Synapse. They are calculating a value called Latency and another value called Backend latency. In order to get the total latency, the value from Backend latency should be added to the Latency variable.

**Comment by isudana** [comment]
Here we are measuring the latency added by the ESB. In Jmeter you are measuring the complete round trip time. So it is expected to see a difference.

**Comment by malakaganga** [comment]
Reverted with:
https://github.com/wso2/wso2-synapse/pull/1468

**Comment by AathmanT** [comment]
What I did was calculating the total latency (ESB+backend) so it is wrong.
latency variable represents, only the ESB latency.

But if we use the following formula to calculate only the ESB latency then there is still a value difference.
latency = (tResDeparture - tReqArrival) - backendLatency;

If we use the above formula we get only the ESB latency.
So, ESB latency + backend latency should be equal to the Jmeter latency.

But there is difference of another backend latency. If we want to match with Jmeter latency. Then we should use the following formula.
Jmeter latency = ESB latency + backend latency +backend latency;

Therefore ESB latency should be
latency = (tResDeparture - tReqArrival);

and not 
latency = (tResDeparture - tReqArrival) - backendLatency;

Correct me if I am wrong.
