### ISSUE TITLE
Change log4j.properties to log4j2 in BPS docs

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/product-ei#4813]
**Description:**
https://docs.wso2.com/display/EI6xx/Troubleshooting+the+Business+Process+Management+Profile
The above page contains some configurations done for log4j.properties file. We need to update them with log4j2 configs.

**Comment by sameeragunarathne** [comment]
fixed in 6.6.0 documentation: https://docs.wso2.com/display/EI660/Troubleshooting+the+Business+Process+Management+Profile
