### ISSUE TITLE
[Swagger] Update swagger related documentation

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#4822]
**Description:**
1. Remove or Update swagger enable doc [1]. Now swagger is enable by default. So we just need to explain for what this configuration is used only. (Related PR: #4820)

2. Add steps and instructions to use swagger editor (refer attached pdf
[Swagger Generation & TryIt Feature for WSO2 EI.pdf](https://github.com/wso2/product-ei/files/3902494/Swagger.Generation.TryIt.Feature.for.WSO2.EI.pdf)
)

3. Add steps and instructions to generate api template from swagger definition. (refer attached pfd [Swagger Generation & TryIt Feature for WSO2 EI.pdf](https://github.com/wso2/product-ei/files/3902494/Swagger.Generation.TryIt.Feature.for.WSO2.EI.pdf))

[1] https://docs.wso2.com/display/EI650/Working+with+APIs#WorkingwithAPIs-GeneratingSwaggerdocumentsfortheAPIs

**Comment by milindaperera** [comment]
Retaled: 
https://github.com/wso2/product-ei/issues/4365
https://github.com/wso2/product-ei/issues/4820

**Comment by praveennadarajah** [comment]
Updated doc[1] with the information saying that this feature is enabled by default from EI-6.6.0 onwards. Created a new page with all information needed to generate an API using swagger in [2]. Hence closing the issue.

[1] https://docs.wso2.com/display/EI6xx/Working+with+APIs#WorkingwithAPIs-GeneratingSwaggerdocumentsfortheAPIs
[2] https://docs.wso2.com/display/EI6xx/Generating+an+API+using+Swagger
