### ISSUE TITLE
Corrections for ESB sample 271

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#483]
[1] - https://docs.wso2.com/display/ESB500/Sample+271%3A+File+Processing#Sample271:FileProcessing-FileProxyStep

When we use sample.zip file attached in [1], we get the error mentioned in http://stackoverflow.com/questions/40334175/using-wso2-esb-for-file-processing.
sample.zip file requires following changes.

1. "<resource>org.milyn.csv.CSVParser</resource>" to "<resource>org.milyn.csv.CSVReader</resource>" inside sample/resources/smooks-config.xml

2. "<sql>insert into INFO values (?, ?, ?)</sql>" to "<sql>insert into info values (?, ?, ?)</sql>" inside sample/conf/synapse-config/sequences/databaseSequence.xml

3. And, within the xml configuration of databaseSequence shown in the page [1], line 
"<sql>insert into userdetails values (?, ?, ?, ?, ?)</sql>" should be changed to 
"<sql>insert into info values (?, ?, ?)</sql>"

**Comment by praneesha** [comment]
Corrected the above in ESB 5.0.0 and EI 6.0.0 and 6.1.0 docs as for example in [1].

[1] https://docs.wso2.com/display/esb500/Sample+271%3A+File+Processing
