### ISSUE TITLE
[Doc] JSON Transform mediator documentation

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#4836]
**Description:**
Update documentation with information about JSON Transform
Include:

1. Syntax
2. How it works. 
3. Using Management console 
4. Tooling (Depends on: https://github.com/wso2/devstudio-tooling-ei/issues/668)
5. Samples
6. Quick start basic tutorial on writing JSON schema.

Initial implementation issue: https://github.com/wso2/product-ei/issues/4377

**Comment by arunans23** [comment]
Please find the WIP documentation https://docs.google.com/document/d/1cPkzKIx_na7NopG8jpW3l8lwljPvLrt43oQx1R371ic/edit?usp=sharing

**Comment by GDLMadushanka** [comment]
Official doc created in https://docs.wso2.com/display/EI660/JSON+Transform+Mediator
