### ISSUE TITLE
[Doc] Injecting Parameters using a file

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/product-ei#4839]
**Description:**
Update documentation for EI 6.6.0 RC1 release with the information about Injecting Parameters using a file. The feature description and usage information included in the attached file. 

[File_property_feature.pdf](https://github.com/wso2/product-ei/files/3914891/File_property_feature.pdf)

**Comment by VirajHasitha** [comment]
Please refer the google doc https://docs.google.com/document/d/1ZXZJyL4f7WyJEt6yq11hk8fBaL25R7BHu91pQk4ml8A/edit?usp=sharing

**Comment by praveennadarajah** [comment]
The above details have been added to EI-6.x.x documentation space [1]. Hence closing the issue.

[1] https://docs.wso2.com/display/EI6xx/Injecting+Parameters+using+a+file

**Comment by praveennadarajah** [comment]
Doc update with all the relevant details in [1] and [2].
[1]https://docs.wso2.com/display/EI6xx/Injecting+Parameters+using+a+file
[2]https://docs.wso2.com/display/EI6xx/Injecting+Parameters+as+Environment+Variables
