### ISSUE TITLE
[EI61][Tenant] Client received connection time out when "returnRequestStatus" property is not defined for the rest resource

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#485]
**Environment**
OS -redhat6, redhat7, debian
JAVA -jdk 1.8
DB - oracle12c
Pack - 03/04/2017 snapshot

**Steps**
1. Create a tenant and log in to tenant user
2. Create a data service with rest resources for insert query

```
<query id="addperson" useConfig="persdb">
      <sql>INSERT INTO Persons (PersonID,LastName,FirstName,Address,City) VALUES (:id,:Lname,:Fname,:Address,:city);</sql>
      <param name="id" sqlType="INTEGER"/>
      <param name="Lname" sqlType="STRING">
         <validateLength maximum="20" minimum="10"/>
      </param>
      <param name="Fname" sqlType="STRING"/>
      <param name="Address" sqlType="STRING">
         <validateLength maximum="10" minimum="5"/>
      </param>
      <param name="city" sqlType="STRING"/>
   </query>

   <resource method="POST" path="test/addperson">
      <call-query href="addperson">
         <with-param name="id" query-param="id"/>
         <with-param name="Lname" query-param="Lname"/>
         <with-param name="Fname" query-param="Fname"/>
         <with-param name="Address" query-param="Address"/>
         <with-param name="city" query-param="city"/>
      </call-query>
   </resource>
```
3. Invoke the service as follows

POST http://ei.wso2.com/services/t/etenant.com/mysqltest/test/addperson
content-type application/xml
payload - <Person><id>123</id><Lname>samplencuuuuu</Lname><Fname>sirimannesir</Fname><Address>addressa</Address><city>citysample</city></Person>

**Observation**
1. Data added to the db successfully
2. Client received connection timeout
3. Following exception observed time to time

```
TID: [-1] [] [2017-04-04 21:49:13,618]  INFO {org.apache.synapse.transport.passthru.SourceHandler} -  Writer null when calling informWriterError {org.apache.synapse.transport.passthru.SourceHandler}
TID: [-1] [] [2017-04-04 21:49:13,618]  WARN {org.apache.synapse.transport.passthru.SourceHandler} -  Connection time out after request is read: http-incoming-65 Socket Timeout : 180000 Remote Address : ui.ei.wso2.com/192.168.48.132:55359 {org.apache.synapse.transport.passthru.SourceHandler}
```

![timeout](https://cloud.githubusercontent.com/assets/14962228/24667249/74aeeb0a-1980-11e7-944b-c89ccd42b495.png)

**Note** - 
1. This behavior did not observe for tenant user when the "returnRequestStatus="true"" is set in the rest resource. 
2. Did not observe this behavior for carbon super user even with out the "returnRequestStatus="true"" property for the rest resource

**Comment by Subasinghe** [comment]
This issue has eliminated with the Kernel patch.

**Comment by sashikamw** [comment]
This issue did not observe in the latest pack shared on 07/04/2017  with the patch consists following jars
org.wso2.carbon.core_4.4.15.jar
org.wso2.carbon.dataservices.core_4.4.5.jar
org.wso2.carbon.integrator.core_6.1.0-SNAPSHOT.jar

**Comment by nandika** [comment]
Resolving as per last comment
