### ISSUE TITLE
Foreach mediator together with PayloadFactory mediator are producing incorrect result - submessages merged under incorrect parent

### ISSUE THREAD

**Issue by VleoniAnovin** [wso2/product-ei#4861]
**Description:**
In my scenario i need to process certain nodes in the XML payload and change their structure.
Combination of `Foreach` mediator and `PayloadFactory` are producing unexpected result. It seems that the `ForEach` mediator is incorrectly aggregating the sub-messages under the hood.

Following the documentation: [https://docs.wso2.com/display/EI640/ForEach+Mediator](url)

> The ForEach mediator requires an XPath expression and a sequence (inline or referred). It splits the message into a number of different messages derived from the original message by finding matching elements for the XPath expression specified. Based on the matching elements, new messages are created for each iteration and processed sequentially. The processing is carried out based on a specified sequence. The behaviour of ForEach mediator is similar to a generic loop. **After mediation, the sub-messages are merged back to their original parent element in the original message sequentially.**

The last part is done incorrectly.

**Suggested Labels:**
6.4.0, BUG

**Affected Product Version:**
6.4.0

**OS, DB, other environment details and versions:**    
`OS Name`:	Linux
`OS Version`:	3.10.0-862.14.4.el7.x86_64
`Java Version`:	1.8.0_131
`Java Vendor`:	Oracle Corporation
`Java VM Version`:	25.131-b11
`DBMS`:	MySQL
`DBMS Version`:	5.7.23
`DBMS Driver`:	MySQL Connector Java
`DBMS Driver Version`:	mysql-connector-java-5.1.45 ( Revision: 9131eefa398531c7dc98776e8a3fe839e544c5b2 )

**Steps to reproduce:**

1. Create `REST API` like:
```xml
<api xmlns="http://ws.apache.org/ns/synapse" name="test" context="/test">
   <resource methods="POST">
      <inSequence>
         <foreach id="test" expression="//entry">
            <sequence>
               <payloadFactory media-type="xml">
                  <format>
                     <adr xmlns="">
                        <type>$1</type>
                     </adr>
                  </format>
                  <args>
                     <arg evaluator="xml" expression="//entry/@Type"/>
                  </args>
               </payloadFactory>
            </sequence>
         </foreach>
         <loopback/>
      </inSequence>
      <outSequence>
         <respond/>
      </outSequence>
   </resource>
</api>                        
```

2. POST payload to `/test`:
```xml
<root>
    <first_level x="foo">
        <second_level>  
            <entry Type="A">1</entry>    
        </second_level>
    </first_level>
    <first_level x="bar">
        <second_level>
            <entry Type="B">2</entry>
            <entry Type="C">3</entry>
            <entry Type="D">4</entry>
            <entry Type="E">5</entry>
        </second_level>
    </first_level>
       <first_level x="kek">
        <second_level>
            <entry Type="F">6</entry>            
        </second_level>
    </first_level>
</root>
```

3. Expected response:
```xml
<root>
    <first_level x="foo">
        <second_level>
            <adr>
                <type>A</type>
            </adr>
        </second_level>
    </first_level>
    <first_level x="bar">
        <second_level>
            <adr>
                <type>B</type>
            </adr>
            <adr>
                <type>C</type>
            </adr>
            <adr>
                <type>D</type>
            </adr>
            <adr>
                <type>E</type>
            </adr>
        </second_level>
    </first_level>
    <first_level x="kek">
        <second_level>
            <adr>
                <type>F</type>
            </adr>
        </second_level>
    </first_level>
</root>
```
Actual response:
```xml
<root>
   <first_level x="foo">
      <second_level>
         <adr>
            <type>A</type>
         </adr>
         <adr>
            <type>B</type>
         </adr>
         <adr>
            <type>C</type>
         </adr>
         <adr>
            <type>D</type>
         </adr>
         <adr>
            <type>E</type>
         </adr>
         <adr>
            <type>F</type>
         </adr>
      </second_level>
   </first_level>
   <first_level x="bar">
      <second_level></second_level> //missing children - connected to wrong parent
   </first_level>
   <first_level x="kek">
      <second_level></second_level> //missing children - connected to wrong parent
   </first_level>
</root>
```

**Comment by arunans23** [comment]
Analysing the [code](https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java#L367), it seems that the first node's parent is set as the parent for all the detached nodes. Hence, when reattaching, the nodes are attached to the first node's parent.
