### ISSUE TITLE
[Docs] Working with OpenTracing should be documented

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-ei#4869]
**Description:**
Working with OpenTracing should be documented.

**Suggested Labels:**
Type/Docs

**Suggested Assignees:**
@senthuran16

**Comment by praveennadarajah** [comment]
Related information added in [1]. Hence closing the issue

[1] https://docs.wso2.com/display/EI6xx/Viewing+Message+Flow+Traces+in+Jaeger+UI
