### ISSUE TITLE
Server Role is Not Getting removed from the worker nodes

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#49]
*Steps*

1. Create an Integrator cluster.
2. Create a CApp with ESB and DSS artefacts. (Make sure you have set the server role for the artefact)
3. Login to Integrator Mgt console and delete the DSS server role.
4. Deploy the Capp.

**Issue:** DSS artefacts will get deployed on the worker node. It will not be deleted in the manager node. Is there a way to delete the Workers server role?

**Comment by madhawa-gunasekara** [comment]
change the server role in carbon.xml file in worker node as well :)

**Comment by yasassri** [comment]
This is also due to the registry mounting issue, The issue is fixed when properly configured.
