### ISSUE TITLE
Document on Integrating Microsoft Azure Service Bus with WSO2 Enterprise Integrator

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#4922]
**Description:**

Add document on how to configure WSO2 EI with `Microsoft Azure Service Bus`. 
Link on the blog is below. 

https://medium.com/@shefandarren.173/integrating-microsoft-azure-service-bus-with-wso2-enterprise-integrator-b504895ccfe6 

**Affected Product Version:**

All supported versions (QA need to test and report)

**OS, DB, other environment details and versions:**    

N/A

**Comment by kvansaders** [comment]
@abeykoon , 
Thanks for posting the article.  Is there any plan for a native Azure Service Bus connector or a connection via AMQP?
