### ISSUE TITLE
How to enable system logs on EI 6.6 management console?

### ISSUE THREAD

**Issue by Sankey52** [wso2/product-ei#4925]
I have been trying several methods to enable logs under monitor section in EI 6.6 but not able to get system logs like the previous releases. Please suggest a way using which I can enable logs on the console or is it depreciated?

Thanks,
Sanketh

**Comment by Nirothipan** [comment]
Enabling logs in the Management Console is no more supported from 6.6.0.  If needed, you will have to enable them in log4j2.properties file found in conf directory.

**Comment by hejunchen** [comment]
does WSO2 EI 6.6.0 have the system logs GUI page at all? why does it get removed? What's the point?

**Comment by Nirothipan** [comment]
From EI 6.6.0 we have migrated to log4j2. You can edit in the log4j2.properties file itself and the changes will be applied in the run time without restart.

**Comment by hejunchen** [comment]
Well, I think from a system configrator's point of view, there is no GUI to bring up the system logs anymore. How do I see the system logs from the web page GUI without going to the server back-end?

**Comment by uarulraj** [comment]
How to enable system logs in WSO2 EI 6.6 management console

**Comment by hejunchen** [comment]
I am tired of this meaningless Q&A here.
Here is the screenshot from 6.5.0 and 6.6.0 Monitor tab.
In 6.5.0 and earlier version, we still have "System Logs" option to view the current system logs.
In 6.6.0, there is no such link, so while some keep saying the logging is migrated to log4j2 etc. etc., where is the original feature of System Logs page? If this page has been removed for EI 6.6.0, where does it get mentioned? In release note? WHERE? SHOW ME?

![image](https://user-images.githubusercontent.com/6847102/75287843-ffd1ae80-57cf-11ea-9940-df510f0fc18b.png)

![image](https://user-images.githubusercontent.com/6847102/75288007-4de6b200-57d0-11ea-9e93-65d13a89b704.png)

**Comment by GDLMadushanka** [comment]
We released the log view feature as a WUM update.
A note is added at the end of the docs in [1]

Quote

> With the introduction of log4j2, Log view and change log level features in the management console were removed in EI 6.6.0. Only the log view feature is released back as a product update on the 09/04/2020. You can get the latest updates using WSO2 Update Manager

[1] [https://docs.wso2.com/display/EI660/Logs+in+WSO2+EI+6.6.0](https://docs.wso2.com/display/EI660/Logs+in+WSO2+EI+6.6.0)
