### ISSUE TITLE
Masking Message Store parameter values using secure-vault

### ISSUE THREAD

**Issue by Nipunich** [wso2/product-ei#4936]
**Description:**
In the message store (Ex MB Message Store) we can define 
`amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5675'` URI for the connection factory parameter. However, in the above URL, we can not mask the username, password, brokerlist url using the secure-valut. (or the whole URL).

**Affected Product Version:**

All EI Versions

**Steps to reproduce:**
1. Start the Message Broker
2. Start the EI server
3. Create a password called 'connection' using Secure Vault tool.
4. Add the following message store configuration
```
<messageStore name="simple" class="org.apache.synapse.message.store.impl.jms.JmsStore" xmlns="http://ws.apache.org/ns/synapse">
   <parameter name="java.naming.factory.initial">org.wso2.andes.jndi.PropertiesFileInitialContextFactory</parameter>
   <parameter name="connectionfactory.QueueConnectionFactory">{wso2:vault-lookup('connection')}</parameter>
   <parameter name="store.jms.destination">smsstore</parameter>
   <parameter name="store.jms.JMSSpecVersion">1.1</parameter>
   <parameter name="store.producer.guaranteed.delivery.enable">false</parameter>
   <parameter name="store.failover.message.store.name">simple</parameter>
```
Then an illegal name exception is thrown.

**Comment by RiAlGueFor** [comment]
Hi, currently I have some issues trying to use the hashicorp vault

`<messageStore name="simple" class="org.apache.synapse.message.store.impl.jms.JmsStore" xmlns="http://ws.apache.org/ns/synapse">
   <parameter name="java.naming.factory.initial">org.wso2.andes.jndi.PropertiesFileInitialContextFactory</parameter>
   <parameter name="connectionfactory.QueueConnectionFactory">{hashicorp:vault-lookup('secret/TEST', 'connection')}</parameter>
   <parameter name="store.jms.destination">smsstore</parameter>
   <parameter name="store.jms.JMSSpecVersion">1.1</parameter>
   <parameter name="store.producer.guaranteed.delivery.enable">false</parameter>
   <parameter name="store.failover.message.store.name">simple</parameter>`

Is it possible to use hashicorp on this?

Thanks in advance.
