### ISSUE TITLE
EI 6.6.0 Download generates incorrect Email content

### ISSUE THREAD

**Issue by joyrathnayake** [wso2/product-ei#4954]
**Description:**
When we download EI 6.6.0 from wso2.com download page, it sends a confirmation email with incorrect content. 
![Capture](https://user-images.githubusercontent.com/56345571/73627121-64866700-4671-11ea-8228-65eabc7d2f0e.JPG)

**Suggested Labels:**
EI, EI 6.6.0

**Suggested Assignees:**

**Affected Product Version:**
EI 6.6.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
This is fixed now. 

<img width="425" alt="Screenshot 2020-02-19 at 10 53 32" src="https://user-images.githubusercontent.com/17047910/74804376-137ba180-5306-11ea-8765-901d3f8f1a70.png">
