### ISSUE TITLE
[EI 6.1]Feature installation via pom.xml failed

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#497]
I created my pom.xml as below using https://docs.wso2.com/display/EI610/Installing+Features+Using+POM+Files documentation and replacing the correct folder path for wso2ei-6.1.0.

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.wso2.sample</groupId>
  <artifactId>sample-feature-installation</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <name>New feature</name>
  <url>http://wso2.org</url>
  <build>
    <plugins>
      <plugin>
        <groupId>org.wso2.maven</groupId>
        <artifactId>carbon-p2-plugin</artifactId>
        <version>1.5.4</version>
        <executions>
          <execution> 
            <id>feature-install</id>
            <phase>package</phase>
            <goals>
              <goal>p2-profile-gen</goal>
            </goals> 
            <configuration>
              <profile>default</profile>
              <metadataRepository>http://product-dist.wso2.com/p2/carbon/releases/wilkes/</metadataRepository>
              <artifactRepository>http://product-dist.wso2.com/p2/carbon/releases/wilkes/</artifactRepository>
              <destination>wso2ei-6.1.0/wso2/components</destination>
              <deleteOldProfileFiles>false</deleteOldProfileFiles>
              <features>
                <feature>
                  <id>org.wso2.carbon.hl7.feature.group</id>
                  <version>4.6.6</version>
                </feature>
              </features>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <configuration>
              <tasks>
                <replace token="false" value="true" dir="wso2ei-6.1.0/wso2/components/default/configuration/org.eclipse.equinox.simpleconfigurator">
                  <include name="**/bundles.info"/>
                </replace>
              </tasks>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <repositories>
    <repository>
      <id>wso2-nexus</id>
      <name>WSO2 internal Repository</name>
      <url>http://maven.wso2.org/nexus/content/groups/wso2-public/</url>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
        <checksumPolicy>ignore</checksumPolicy>
      </releases>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>wso2-maven-releases-repository</id>
      <url>http://maven.wso2.org/nexus/content/repositories/releases/</url>
    </pluginRepository>
    <pluginRepository>
      <id>wso2-maven-snapshots-repository</id>
      <url>http://maven.wso2.org/nexus/content/repositories/snapshots/</url>
    </pluginRepository>
  </pluginRepositories>
</project>`

It gives the below exception.

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building New feature 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ sample-feature-installation ---
[INFO] 
[INFO] --- carbon-p2-plugin:1.5.4:p2-profile-gen (feature-install) @ sample-feature-installation ---
[INFO] Running Equinox P2 Director Application
[INFO] Command line:
	/bin/sh -c cd /home/ushani/WSO2_WORK/Products/EI/6.1.0-Release/3-April-localybuild/wso2ei-6.1.0/wso2/components/default/configuration/org.eclipse.equinox.simpleconfigurator && /home/ushani/Software/jdk1.8.0_60/jre/bin/java -jar /home/ushani/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/plugins/org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.director -metadataRepository http://product-dist.wso2.com/p2/carbon/releases/wilkes/ -artifactRepository http://product-dist.wso2.com/p2/carbon/releases/wilkes/ -profileProperties org.eclipse.update.install.features=true -installIU org.wso2.carbon.hl7.feature.group/4.6.6, -bundlepool wso2ei-6.1.0/wso2/components -shared wso2ei-6.1.0/wso2/components/p2 -destination wso2ei-6.1.0/wso2/components/default -profile default -roaming
Installing org.wso2.carbon.hl7.feature.group 4.6.6.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
 Missing requirement: axiom 1.2.11.wso2v10 (axiom 1.2.11.wso2v10) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v11 (axiom 1.2.11.wso2v11) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v6 (axiom 1.2.11.wso2v6) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v9 (axiom 1.2.11.wso2v9) requires 'package javax.xml 0.0.0' but it could not be found
 Cannot satisfy dependency:
  From: org.wso2.carbon.business.messaging.hl7.message 4.6.6 (org.wso2.carbon.business.messaging.hl7.message 4.6.6)
  To: package org.apache.axiom.om [1.2.11,1.3.0)
 Cannot satisfy dependency:
  From: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
  To: org.wso2.carbon.business.messaging.hl7.message [4.6.6]
Application failed, log file location: /home/ushani/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/configuration/1491385210795.log

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:38.546s
[INFO] Finished at: Wed Apr 05 15:11:48 IST 2017
[INFO] Final Memory: 10M/145M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (feature-install) on project sample-feature-installation: P2 publisher return code was 13 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by prabushi** [comment]
"Installing features using a pom file" functionality is working fine with a newly built wso2ei-6.1.0-SNAPSHOT.zip pack. I tested the product name as wso2ei-6.1.0-SNAPSHOT, and wso2ei-6.1.0 as done in the above scenario. In both cases we can get the feature installed products without the error.

**Comment by ushanib** [comment]
Hi Prabushi, Can you please confirm the given pom.xml has got any issue? This was taken from the documentation.

**Comment by prabushi** [comment]
I tested with the same pom.xml. Just renamed the product directory to wso2ei-6.1.0. It's building successfully. I can reproduce the error, when I have two different names in the pom file, and the actual product directory.

**Comment by ushanib** [comment]
Hi Prabushi,

I tried cleaning .m2 and re installing., Still I get the issue. I get the issue in EI 6.0 as well. 
My JDK 1.8, OS : fedora

`Downloading: http://maven.wso2.org/nexus/content/repositories/releases/org/eclipse/tycho/org.eclipse.tycho.p2.resolver.impl/0.13.0/org.eclipse.tycho.p2.resolver.impl-0.13.0.jar
Downloading: http://maven.wso2.org/nexus/content/repositories/snapshots/org/eclipse/tycho/org.eclipse.tycho.p2.resolver.impl/0.13.0/org.eclipse.tycho.p2.resolver.impl-0.13.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.resolver.impl/0.13.0/org.eclipse.tycho.p2.resolver.impl-0.13.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.resolver.impl/0.13.0/org.eclipse.tycho.p2.resolver.impl-0.13.0.jar (118 KB at 31.3 KB/sec)
Downloading: http://maven.wso2.org/nexus/content/repositories/releases/org/eclipse/tycho/org.eclipse.tycho.p2.maven.repository/0.13.0/org.eclipse.tycho.p2.maven.repository-0.13.0.jar
Downloading: http://maven.wso2.org/nexus/content/repositories/snapshots/org/eclipse/tycho/org.eclipse.tycho.p2.maven.repository/0.13.0/org.eclipse.tycho.p2.maven.repository-0.13.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.maven.repository/0.13.0/org.eclipse.tycho.p2.maven.repository-0.13.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.maven.repository/0.13.0/org.eclipse.tycho.p2.maven.repository-0.13.0.jar (66 KB at 81.6 KB/sec)
Downloading: http://maven.wso2.org/nexus/content/repositories/releases/org/eclipse/tycho/org.eclipse.tycho.p2.tools.impl/0.13.0/org.eclipse.tycho.p2.tools.impl-0.13.0.jar
Downloading: http://maven.wso2.org/nexus/content/repositories/snapshots/org/eclipse/tycho/org.eclipse.tycho.p2.tools.impl/0.13.0/org.eclipse.tycho.p2.tools.impl-0.13.0.jar
Downloading: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.tools.impl/0.13.0/org.eclipse.tycho.p2.tools.impl-0.13.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/eclipse/tycho/org.eclipse.tycho.p2.tools.impl/0.13.0/org.eclipse.tycho.p2.tools.impl-0.13.0.jar (21 KB at 27.1 KB/sec)
[INFO] Command line:
	/bin/sh -c cd /home/ushani/WSO2_WORK/Products/EI/6.1.0-Release/3-April-localybuild/wso2ei-6.1.0/wso2/components/default/configuration/org.eclipse.equinox.simpleconfigurator && /home/ushani/Software/jdk1.8.0_60/jre/bin/java -jar /home/ushani/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/plugins/org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.director -metadataRepository http://product-dist.wso2.com/p2/carbon/releases/wilkes/ -artifactRepository http://product-dist.wso2.com/p2/carbon/releases/wilkes/ -profileProperties org.eclipse.update.install.features=true -installIU org.wso2.carbon.hl7.feature.group/4.6.6, -bundlepool wso2ei-6.1.0/wso2/components -shared wso2ei-6.1.0/wso2/components/p2 -destination wso2ei-6.1.0/wso2/components/default -profile default -roaming
Installing org.wso2.carbon.hl7.feature.group 4.6.6.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
 Missing requirement: axiom 1.2.11.wso2v10 (axiom 1.2.11.wso2v10) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v11 (axiom 1.2.11.wso2v11) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v6 (axiom 1.2.11.wso2v6) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v9 (axiom 1.2.11.wso2v9) requires 'package javax.xml 0.0.0' but it could not be found
 Cannot satisfy dependency:
  From: org.wso2.carbon.business.messaging.hl7.message 4.6.6 (org.wso2.carbon.business.messaging.hl7.message 4.6.6)
  To: package org.apache.axiom.om [1.2.11,1.3.0)
 Cannot satisfy dependency:
  From: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
  To: org.wso2.carbon.business.messaging.hl7.message [4.6.6]
Application failed, log file location: /home/ushani/.m2/repository/org/eclipse/tycho/tycho-p2-runtime/0.13.0/eclipse/configuration/1491538809076.log

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:36.654s
[INFO] Finished at: Fri Apr 07 09:50:35 IST 2017
[INFO] Final Memory: 9M/110M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (feature-install) on project sample-feature-installation: P2 publisher return code was 13 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by nandika** [comment]
This works fine. Test with clean repo also
