### ISSUE TITLE
[Critical] Cannot Invoke WebApps when clustered

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#50]
*Steps*

1. Create a cluster of Integrator.
2. Upload a WebApp and try to invoke it.

**Issue:** The invocation fails with the following warning in the BE. It seems the server is using the HostName instead of localhost to call the WebApp EP.

> TID: [-1] [] [2017-01-26 03:34:32,863]  WARN {org.apache.synapse.transport.passthru.ConnectCallback} -  Connection refused or failed for : ei6.wso2.com:9763 {org.apache.synapse.transport.passthru.ConnectCallback}

**Comment by madhawa-gunasekara** [comment]
Fixed this
