### ISSUE TITLE
[Jaeger Tracing] Add transport headers as span tags

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-ei#5012]
**Description:**
In the current implementation, transport headers are not added as span tags. Adding transport headers will be useful to further understand how a message had transformed.

This should be possible by doing the following:
1. Refactoring [this](https://github.com/wso2/wso2-synapse/blob/43f1015df2c8c24dc05dff26d91042f895dda49a/modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/stores/SpanStore.java#L120) method to accept message context as 
```
public void finishSpan(SpanWrapper spanWrapper, MessageContext synCtx) {
   ...
}
```
2. Passing the message context in [this](https://github.com/wso2/wso2-synapse/blob/43f1015df2c8c24dc05dff26d91042f895dda49a/modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java#L237) line as `spanStore.finishSpan(spanWrapper, synCtx);`

3. Refactoring [this](https://github.com/wso2/wso2-synapse/blob/43f1015df2c8c24dc05dff26d91042f895dda49a/modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/SpanTagger.java#L45) method to accept message context as
```
public static void setSpanTags(SpanWrapper spanWrapper, BasicStatisticDataUnit basicStatisticDataUnit, MessageContext synCtx) {
   ...
}
```
4. Add implementation in the above method to extract transport headers, something like: 
```
synCtx.getAxis2MessageContext().getProperty(org.apache.axis2.context.MessageContext.TRANSPORT_HEADERS);
```

5. Modify [this](https://github.com/wso2/wso2-synapse/blob/43f1015df2c8c24dc05dff26d91042f895dda49a/modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/stores/SpanStore.java#L123) line as 
```
SpanTagger.setSpanTags(spanWrapper, spanWrapper.getStatisticDataUnit(), synCtx);
````

**Suggested Labels:**
Improvement

**Comment by martinfar** [comment]
Hi, 
      Is there any news about this feature ?

**Comment by Vathsan** [comment]
We need to implement a feature to add custom span tags during the mediation process. We may introduce a synapse property to add custom tags from synapse configuration.
