### ISSUE TITLE
How to do a datamapper transaformation is Integrator 6.6.0 management console design view

### ISSUE THREAD

**Issue by uarulraj** [wso2/product-ei#5019]
**Description:**

I am planning to do json to json transformation using Datamapper mediator in Integrator 6.6.0 Management console design view. I am unable to do this Can you please help me on this

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GDLMadushanka** [comment]
We cannot use the management console to configure the data-mapper mediator. We must use the Integration Studio instead.  
You can download the Integration Studio from here. https://wso2.com/integration/integration-studio/
