### ISSUE TITLE
An easy and intuitive way to create data-services in the Integration Studio

### ISSUE THREAD

**Issue by shazni** [wso2/product-ei#5032]
**Description:**
An easy and intuitive way to create data-services in the Integration Studio is essential. Today creating a dataservice in the integration studio requires directly working with the XML or requires specific unintuitive steps to be taken to create a dataservice. It would be great to have the developer walked through a set of dialog boxes to create a data-service

**Suggested Labels:**
New Integration Studio feature

**Comment by Nirothipan** [comment]
With the latest [release](https://github.com/wso2/devstudio-tooling-ei/releases/tag/v7.0.2-rc3), DSS editor has included a significant revamp. Please try it out and report issues [here](https://github.com/wso2/devstudio-tooling-ei/issues) if any.
