### ISSUE TITLE
Can't checkout source code on windows

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#5055]
**Description:**
I'm pulled the source code from git since long time, and have local only 7.0.x branch checkouted. When I try to switch to the release-6.6.0 branch, I get error from git.

The error is:
```schell
C:\src\cvstree\wso2\product-ei>git checkout -b release-6.6.0 origin/release-6.6.0
error: invalid path 'product-scenarios/2-Bridging-systems-that-communicate-in-different-protocols/2.7-FTP-transport-listener-to-mail-transport-sender./2.7.1-vfs-transport-invocation/readme.md'
```
It's probably because of the invalid file name under Windows for `2.7-FTP-transport-listener-to-mail-transport-sender.`

Note the trailing `.` (dot) at the end of the file name. Windows doesn't allow files ending with dot.

The solution would be to rename file to valid Windows file name.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
source code

**OS, DB, other environment details and versions:**    
Windows 10, x64

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/product-ei/pull/5108
