### ISSUE TITLE
[EI610][MSF4J] MSF4J not going to start

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#507]
Environment
Operating Systems : Ubuntu/Windows
Java Version : JDK1.8
Packs : EI610 07/04/2017 pack
ESB Setup: Standalone/Cluster
DB - Oracle 12c

**Steps to reproduce**
Start MSF4J.

**Expected Result**
MSF4J should start.

**Actual Result**
MSF4J not going to start

![msf4j](https://cloud.githubusercontent.com/assets/8134384/24786147/bf1820f0-1b7c-11e7-8309-4dafa8610b0a.png)

**Comment by erandacr** [comment]
We have identified the issue, its with kernel 5.1.0.
Kernel team is doing another c5 and msf4j release. Will be able to verify after that.

**Comment by erandacr** [comment]
Fixed with C5 kernel 5.1.1 and msf4j 2.2.2 update
