### ISSUE TITLE
Swagger UI does not show all the resources defined in an API

### ISSUE THREAD

**Issue by Vathsan** [wso2/product-ei#5074]
**Description:**
When we have multiple resources defined with same uri-template in an API definition, the swagger UI shows only the last defined resource.

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.6.0

**Steps to reproduce:**
1. Deploy the following API
```
<api xmlns="http://ws.apache.org/ns/synapse" name="test" context="/swagger">
   <resource methods="GET" uri-template="/orders" faultSequence="fault">
      <inSequence>
         <log level="custom">
            <property name="InsideInSequence" value="FirstResource"/>
         </log>
      </inSequence>
   </resource>
   <resource methods="POST" url-mapping="/orders" faultSequence="fault">
      <inSequence>
         <log level="custom">
            <property name="InsideInSequence" value="SecondResource"/>
         </log>
      </inSequence>
   </resource>
   <resource methods="PUT" url-mapping="/orders" faultSequence="fault">
      <inSequence>
         <log level="custom">
            <property name="InsideInSequence" value="ThirdResource"/>
         </log>
      </inSequence>
   </resource>
</api>
```
                        
2. Click on 'Try This API'  from the UI of API list
![image](https://user-images.githubusercontent.com/29911181/80761426-2c9b9c80-8b58-11ea-8c3f-0b855ddaa77c.png)

**Comment by rosensilva** [comment]
We can reproduce this issue in the micro-integrator by deploying the above artifact and invoking the API with http://localhost:8290/test?swagger.json
