### ISSUE TITLE
Sequence mediator not invoking onError sequence on failure within class mediator

### ISSUE THREAD

**Issue by Sankey52** [wso2/product-ei#5087]
Hi, 
 
 **Scenario**: I have defined a proxy which is calling class mediator. Class mediator in turn does some processing and calls a sequence. This sequence is working fine for success scenarios. But when there's an error, it's not able to call onError sequence. I have assigned an onError sequence within that sequence.

Questions:
1. Is it not possible to invoke onError sequence when a sequence is called within class mediator?
2. If not, then is there a workaround to call error sequence when the sequence within class mediator fails?

Thanks,
Sanketh

**Comment by Sankey52** [comment]
> Hi,
> 
> **Scenario**: I have defined a proxy which is calling class mediator. Class mediator in turn does some processing and calls a sequence. This sequence is working fine for success scenarios. But when there's an error, it's not able to call onError sequence. I have assigned an onError sequence within that sequence.
> 
> Questions:
> 
> 1. Is it not possible to invoke onError sequence when a sequence is called within class mediator?
> 2. If not, then is there a workaround to call error sequence when the sequence within class mediator fails?
> 
> Thanks,
> Sanketh

**Comment by Sankey52** [comment]
Kindly look into this.

**Comment by arunans23** [comment]
It is possible to do this within class mediator. Without seeing your class mediator implementation, it is hard to guess on what has gone wrong. However, you can look at the Sequence mediator implementation and get an idea of how to properly assign an onError sequence within the class mediator. https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java#L132
