### ISSUE TITLE
Rabbitmq transport issue on autodeclare

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-ei#5093]
**Description:**
Hi, i was not able to create a queue on Rabbitmq even if i set rabbitmq.queue.autodeclare to true; is there any other parameter i have to set?
EI version 6.6
Rabbitmq version: 3.8.3

**Suggested Labels:**
rabbitmq

**Suggested Assignees:**

**Affected Product Version:**
EI 6.6
**OS, DB, other environment details and versions:**    
Rabbitmq 3.8.3
**Steps to reproduce:**
i create a simple proxy:
<?xml version="1.0" encoding="UTF-8"?><proxy xmlns="http://ws.apache.org/ns/synapse" name="GetMQMsg" startOnLoad="true" statistics="disable" trace="disable" transports="rabbitmq">
    <target>
        <inSequence>
            <log level="full"/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
    <parameter name="rabbitmq.queue.name">hello</parameter>
    <parameter name="rabbitmq.connection.factory">AMQPConnectionFactory</parameter>
    <parameter name="rabbitmq.queue.autodeclare">true</parameter>
    <description/>
</proxy>

when i deploy it, it fails as the queue does not exist

**Related Issues:**

**Comment by indikasampath2000** [comment]
@stefanonegri No, there aren't any other parameters. Could you please copy the entire synapse config? What is the value you have set for the **transports** attribute in the proxy service?

**Comment by stefanonegri** [comment]
<parameter name="rabbitmq.queue.autodeclare">true</parameter>

**Comment by indikasampath2000** [comment]
Did you mean the value of the **transports** attribute is **true**? Typically it should be something like below. Please check.

```xml
<proxy xmlns="http://ws.apache.org/ns/synapse" name="ListenerProxy" transports="rabbitmq" startOnLoad="true">
...
</proxy>
```

**Comment by stefanonegri** [comment]
sorry, i thought i pasted the whole property; i mean i set it as true, like this:
<parameter name="rabbitmq.queue.autodeclare">true</parameter>

**Comment by stefanonegri** [comment]
"<parameter name="rabbitmq.queue.autodeclare">true</parameter>"

**Comment by stefanonegri** [comment]
<target>
    <inSequence>
        <log level="full"/>
    </inSequence>
    <outSequence/>
    <faultSequence/>
</target>
<parameter name="rabbitmq.queue.name">hello</parameter>
<parameter name="rabbitmq.connection.factory">AMQPConnectionFactory</parameter>
**<parameter name="rabbitmq.queue.autodeclare">true</parameter>**
<description/>

**Comment by stefanonegri** [comment]
i mean i set the param like this:

`<parameter name="rabbitmq.queue.autodeclare">true</parameter>`

**Comment by indikasampath2000** [comment]
Please share the proxy service. Then we will be able to reproduce the issue locally.

**Comment by stefanonegri** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<proxy name="GetMQMsg" startOnLoad="true" transports="rabbitmq" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="full"/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
    <parameter name="rabbitmq.queue.name">hello</parameter>
    <parameter name="rabbitmq.connection.factory">AMQPConnectionFactory</parameter>
    <parameter name="rabbitmq.queue.autodeclare">true</parameter>
</proxy>`

**Comment by stefanonegri** [comment]
any update?

**Comment by stefanonegri** [comment]
any update?
