### ISSUE TITLE
Empty content when creating registry files via property mediator

### ISSUE THREAD

**Issue by pumudu88** [wso2/product-ei#5099]
**Description:**
Always set value empty when create registry files via property mediator. 

**Suggested Labels:**
EI, EI-6.6.0

**Affected Product Version:**
EI 6.6.0

**OS, DB, other environment details and versions:**    
Issue is independent of environment specs.

**Steps to reproduce:**
1. Create following EI API.

`
<api xmlns="http://ws.apache.org/ns/synapse" name="testApi" context="/testReg">
   <resource methods="POST" url-mapping="/test-post">
      <inSequence>
         <log level="full">
            <property name="test" value="test POST"/>
         </log>
         <log>
            <property name="inbound-value : " expression="json-eval($.testValue)"/>
         </log>
         <property name="conf:customresource/test-file-2.txt@abc" expression="json-eval($.testValue)" scope="registry" type="STRING"/>
         <property name="conf:customresource/test-file-1.xml" expression="json-eval($.testValue)" scope="registry" type="STRING"/>
         <log>
            <property name="inbound value from reg file : " expression="get-property('registry', 'conf:customresource/test-file-1.xml')"/>
            <property name="inbound value from collection : " expression="get-property('registry', 'conf:customresource/test-file-2.txt@abc')"/>
         </log>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
`

2. Invoke above created api.

`curl --header "Content-Type: application/json" --request POST --data '{"testValue":"testvalue24"}' https://dockerhost:8243/testReg/test-post -H "accept: */*" -k`

3. Check content of the registry entry "conf:/customresource/test-file-1.xml". Content is set to empty.

**Related Issues:**
https://github.com/wso2/product-ei/issues/1226

**Comment by pumudu88** [comment]
https://github.com/wso2/wso2-synapse/pull/1538

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1538
