### ISSUE TITLE
WARN when generating a Data service

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#51]
Following WARN was observed when generating a Data service.

> TID: [-1234] [] [2017-01-26 03:53:31,764]  WARN {org.wso2.carbon.dataservices.core.script.DSGenerator} -  Primary key does not exists {org.wso2.carbon.dataservices.core.script.DSGenerator}

**Comment by madhawa-gunasekara** [comment]
This isn't an issue. If there isn't a primary key in the table this warning will appear only in Data Service Generation. because In Data Service Generation, we generate the SQL Query
