### ISSUE TITLE
[EI61] Restresource path should be send as the parent tag of the xml POST body

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#510]
**Environment**
Setup - 3 node cluster fronted by nginx
OS -redhat6, redhat7, debian
JAVA -jdk 1.8
DB - oracle12c
Pack - 07/04/2017 snapshot + last shared patch

**Steps**
1. Create a datasource with rest resource POST method
```
<data disableLegacyBoxcarringMode="true" enableBatchRequests="true" enableBoxcarring="true" name="mysqltest" transports="http https local">
   <config enableOData="true" id="persdb">
   </config>
 <query id="addperson" useConfig="persdb">
      <sql>INSERT INTO Persons (PersonID,LastName,FirstName,Address,City) VALUES (:id,:Lname,:Fname,:Address,:city);</sql>
      <param name="id" sqlType="INTEGER"/>
      <param name="Lname" sqlType="STRING">
         <validateLength maximum="20" minimum="10"/>
      </param>
      <param name="Fname" sqlType="STRING"/>
      <param name="Address" sqlType="STRING">
         <validateLength maximum="10" minimum="5"/>
      </param>
      <param name="city" sqlType="STRING"/>
   </query>

  <operation name="AddPerson" returnRequestStatus="true">
      <call-query href="addperson">
         <with-param name="id" query-param="id"/>
         <with-param name="Lname" query-param="Lname"/>
         <with-param name="Fname" query-param="Fname"/>
         <with-param name="Address" query-param="Address"/>
         <with-param name="city" query-param="testcity"/>
      </call-query>
   </operation>

   <resource method="POST" path="test/addperson">
      <call-query href="addperson">
         <with-param name="id" query-param="id"/>
         <with-param name="Lname" query-param="Lname"/>
         <with-param name="Fname" query-param="Fname"/>
         <with-param name="Address" query-param="Address"/>
         <with-param name="city" query-param="city"/>
      </call-query>
   </resource>
```

2. Invoke the rest resource as below

```
POST http://ei.wso2.com:80/services/mysqltest/test/addperson

POST data:
<Person><id>110</id><Lname>samplencssssss</Lname><Fname>sirimannesir</Fname><Address>addressa</Address><city>citysample</city></Person>

[no cookies]

Request Headers:
Connection: keep-alive
content-type: application/xml
Content-Length: 135
Host: ei.wso2.com:80
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_66)
```

**Observations**
`
<axis2ns47:DataServiceFault xmlns:axis2ns47="http://ws.wso2.org/dataservice"><axis2ns47:ds_code>UNKNOWN_ERROR</axis2ns47:ds_code></axis2ns47:DataServiceFault>`

```
TID: [-1234] [] [2017-04-07 14:34:02,221] ERROR {org.apache.synapse.transport.passthru.ServerWorker} -  Error processing POST request for : /services/mysqltest/test/addperson {org.apache.synapse.transport.passthru.ServerWorker}
org.apache.axis2.AxisFault: DS Fault Message: Input Message and _posttest_addperson Axis Operation didn't match.
DS Code: UNKNOWN_ERROR

	at org.wso2.carbon.dataservices.core.DBUtils.createAxisFault(DBUtils.java:742)
	at org.wso2.carbon.dataservices.core.DBInOnlyMessageReceiver.invokeBusinessLogic(DBInOnlyMessageReceiver.java:58)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:326)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:372)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Note** - 
1. This issue did not observe when the payload is provided as below

`<_posttest_addperson><id>115</id><Lname>updatedsamplenc</Lname><Fname>efgt</Fname><Address>addressa</Address><city>citysample</city></_posttest_addperson>`

2. Verified this with DSS 351 pack as well. It accepts the payload without considering the parent xml tag. 
This might become an issue for a migration scenario.

```
POST http://10.100.11.26:9763/services/mysqltest/test/addperson

POST data:
<Person><id>111</id><Lname>samplencssssss</Lname><Fname>sirimannesir</Fname><Address>addressa</Address><city>citysample</city></Person>

[no cookies]

Request Headers:
Connection: keep-alive
content-type: application/xml
Content-Length: 135
Host: 10.100.11.26:9763
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_66)
```

**Comment by Subasinghe** [comment]
This is due to DSS 351 did not have the validation so it takes any wrapper element with the payload.

**Comment by sashikamw** [comment]
If we are changing the validation we should add this to the documentation as we mentioned it for json [1]. Also we should update rest resource sample [2] with correct invocation details.

[1] https://docs.wso2.com/display/EI600/Using+JSON+Messages+with+RESTful+Services
[2] https://docs.wso2.com/display/EI600/REST-Style+Resources+Sample

**Comment by praneesha** [comment]
Added a note in [1] in docs of all WSO2 EI versions.

[1] https://docs.wso2.com/display/EI620/Using+JSON+Messages+with+RESTful+Services

**Comment by fshomou** [comment]
Hello,

1- Im using WSO2 EI 6.1.0, and  I have the a datasource with rest resource PUT method :
<query id="MyQry" useConfig="H2UtilisateurDataSource" returnUpdatedRowCount="true">
        <sql>UPDATE UTILISATEUR  SET NAME=:NAME WHERE ID=:ID</sql>
        <param name="NAME" paramType="SCALAR" sqlType="STRING"/>
        <param name="ID" paramType="SCALAR" sqlType="INTEGER"/>
    </query>
	
	 <resource method="PUT" path="utilisateur" returnRequestStatus="true">
        <call-query href="MyQry">
            <with-param name="NAME" query-param="NAME"/>
            <with-param name="ID" query-param="ID"/>
        </call-query>
    </resource>
	
2- Invoke the rest resource as below via SoapUI with JSON paylaod
http://M77972:8280/services/DemoService.HTTPEndpoint/utilisateur

JSON paylaod:
{
    "_pututilisateur" :{
        "ID":1,
        "NOM": "test"
    }
}

3- Im getting this error :
ServerWorker Error processing PUT request for : /services/GX.GestionClient.HTTPEndpoint/utilisateur
org.apache.axis2.AxisFault: DS Fault Message: Input Message and _pututilisateur Axis Operation didn't match.
DS Code: UNKNOWN_ERROR

4- With XML payload the call is working fine
<axis2ns544:REQUEST_STATUS xmlns:axis2ns544="http://ws.wso2.org/dataservice">SUCCESSFUL</axis2ns544:REQUEST_STATUS>


5- Can we send a JSON payload to a Data service with REST resource ?
