### ISSUE TITLE
DataMapper mediator performance issues with Nashron JS implementation

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-ei#5102]
**Description:**
I did a performance test to compare the performance in different scripting languages running in the Script mediator and the DataMapper mediator. According to the results, when payload size is getting larger, the DataMapper mediator takes more time to execute than a Nashrone js script in the script mediator. 
DataMapper mediator is also executing on JavaScript, but not on Nashrone engine. DataMapper mediator implementation may need to change to Nashrone Js to overcome this performance issue.

In the performance test, DataMapper mediator took an average of 40 ms to process a JSON payload ( a JSON array of 500 elements). In comparison, Javascript running on Nashorn Js took 16 ms.

**Comment by rosensilva** [comment]
Data mapper is not using pre-compiles scripts and it is not passing the data using native bindings to the nashorn engine

**Comment by Vathsan** [comment]
Public fix: https://github.com/wso2/carbon-mediation/pull/1484
