### ISSUE TITLE
Need to update JMS Support related axis2.xml location path for BPS 

### ISSUE THREAD

**Issue by himasha** [wso2/product-ei#512]
In JMS Support configuration docs such as [1] , we are only stating to set the listeners and senders for EI ( <EI_HOME>/conf/axis2/axis2.xml file.)  It will be clear if we can add a note that the user needs to update  <EI_HOME>/wso2/business-process/conf/axis2/axis2.xml file if he needs JMS enabled in business process component.

[1] https://docs.wso2.com/display/EI600/Configure+with+ActiveMQ

**Comment by praneesha** [comment]
Added the following note in all versions of WSO2 EI docs in all subpages of the section [1].

"From the below configurations, do the ones in the axis2.xml file based on the profile you use as follows:
To enable the JMS transport in the Integration profile, edit the <EI_HOME>/conf/axis2/axis2.xml file.
To enable the JMS transport in other profiles, edit the <EI_HOME>/wso2/<PROFILE_HOME>/conf/axis2/axis2.xml file. <PROFILE_HOME> refers to the main directory of the profile inside the WSO2 EI distribution. For example, to enable the JMS transport in the Business Process profile, edit the <EI_HOME>/wso2/business-process/conf/axis2/axis2.xml file"

[1] https://docs.wso2.com/display/EI620/JMS+Transport
