### ISSUE TITLE
WSO2 Integrator Scheduler for Task not working with some cron patterns

### ISSUE THREAD

**Issue by falaknaaz92** [wso2/product-ei#5132]
**Description:**
The WSO2 Integrator scheduler is not working for some cron patterns like:
0 0 01 * * ?
0 0 1 * * ?

Objective is to create a task to be scheduled at 1:00 am in the morning everyday. 
I tried the cron variable 0 0 10 * * ? which successfully schedules for 10:00am but after changing to 0 0 1 * * ? or 0 0 01 * * ? it does not work.

Can you recommend the correct pattern to be used in this case.
Version of product Used is EI 6.5.0

**Comment by arunans23** [comment]
Are you getting any errors thrown in carbon logs?

**Comment by falaknaaz92** [comment]
There are no errors thrown in carbon logs.
