### ISSUE TITLE
[FEATURE] Inline JSON support for Property mediator

### ISSUE THREAD

**Issue by dineshjweerakkody** [wso2/product-ei#5136]
**Description:**
Currently we can write inline xml content in property mediator and work with that property using xpath. Can we provide similar capability to work with JSON content so that we can write inline JSON content and run json-path against the property
e.g.:
<property name="jsonContent"  type="JSON">
    {"key","value"}
</property>

<property name="someName" expression="json-eval($ctx:jsonContent.$.key)" />

**Comment by GDLMadushanka** [comment]
This feature is developed and added to master in https://github.com/wso2/wso2-synapse/pull/1634
Will be released with the next MI version. 

Sample syntax =  json-eval($ctx:prop.student.name)
