### ISSUE TITLE
Option to disable restart/shutdown option from management console

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#5147]
**Description:**
There is no available option for the user to enable/disable the restart/shutdown options from the management console. When we use the password-tmp file to provide Keystore passwords, the user should not use re-start option from the management console because password-tmp file is deleted when server restart.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by milindaperera** [comment]
Please create a doc issue linked to this since we need to document new properties
