### ISSUE TITLE
[FEATURE] Mediator to delete elements from XML or JSON payloads

### ISSUE THREAD

**Issue by dineshjweerakkody** [wso2/product-ei#5148]
**Description:**
A new mediator or update for an existing mediator to remove elements from XML or JSON payloads with the given path

**Comment by GDLMadushanka** [comment]
This feature was introduced to EI 6.6.0 via a WUM update
https://docs.wso2.com/display/EI660/Enrich+Mediator (sample 07)
Not closing this issue since it still works for JSON only.
Related issue https://github.com/wso2/product-ei/issues/5199
