### ISSUE TITLE
[EI610][Integrator with broker] Guaranteed delivery not going to work as expected.

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#515]
**Environment**
Operating Systems : Redhat and Debian
Java Version : JDK1.8
Packs : EI610 07/04/2017 snapshot
ESB Setup: Cluster (3 nodes)
DB - Oracle 12c
Broker setup - Cluster (2 nodes)

**Steps to reproduce**
Configure guaranteed delivery scenario as in [1].
Shut down the broker and publish messages to proxy.

**Actual Results**
All publishing messages not going to publish in to failover message store.
Even though broker started, all messages in failover not going to publish to original message store. 

[1] https://docs.wso2.com/display/EI600/Guaranteed+Delivery+with+Failover+Message+Store+and+Scheduled+Failover+Message+Forwarding+Processor

Attached CAPP:
[CAPP.zip](https://github.com/wso2/product-ei/files/905597/CAPP.zip)

**Comment by ThishaniLucas** [comment]
Same thing happens with ActiveMQ broker as well. After a broker restart, first few messages get ignored. But after sometime, all the messages are processed at once.

**Comment by a5anka** [comment]
This is expected when we do not have publisher transactions.
