### ISSUE TITLE
Add tag to track property of Property Mediator with Jaeger tracing

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/product-ei#5152]
**Description:**
In Jaeger tracing users unable to check the properties set by the Property Mediator. In EI need to add a new tag for message tracing to add a new property for the Property Mediator.

**Affected Product Version:**
EI 6.6.0

**Comment by madushadhanushka** [comment]
Fixed with https://github.com/wso2-support/wso2-synapse/pull/808

**Comment by malakaganga** [comment]
Duplicate with https://github.com/wso2/product-ei/issues/5218
