### ISSUE TITLE
"Exposing CSV Data as a Data Service" doc page required minor changes

### ISSUE THREAD

**Issue by gvasanka** [wso2/product-ei#516]
In [1] 
https://docs.wso2.com/display/EI600/Exposing+CSV+Data+as+a+Data+Service, tables content should be updated as below
Sample CSV file provided have column as "Classification" not as "Category"

![selection_219](https://cloud.githubusercontent.com/assets/3368635/24802001/f47e970a-1bc3-11e7-90da-3894fef62392.png)

Update the "Add a CSV file as the datasource" section content as matching to the below image
![selection_220](https://cloud.githubusercontent.com/assets/3368635/24802569/110828f8-1bc6-11e7-83e9-cb40851b019e.png)

**Comment by praneesha** [comment]
Corrected in all versions of WSO2 EI.
