### ISSUE TITLE
EI 6.6.0: integrator.bat --> Classpath issue

### ISSUE THREAD

**Issue by Sankey52** [wso2/product-ei#5176]
Hi,
  I have been facing class path issue while starting EI 6.6.0 in windows.
After some RCA, I was found out the below is set to wrong path: 
**FOR %%D in ("%CARBON_HOME%\wso2\lib\*.jar") DO set CARBON_CLASSPATH=!CARBON_CLASSPATH!;".wso2\lib\%%~nD%%~xD"**

Can you let me know whether it should be .\lib or .wso2\lib?

Thanks,
Sanketh

**Comment by Nirothipan** [comment]
It should be  .wso2\lib and the scripts seems to be correct. The other .\lib will be converted to osgi bundles ( to dropins ) and will be added to the OSGi environment. Could you elaborate error you are getting.

**Comment by Sankey52** [comment]
I have deleted few files from wso2 package to reduce it's size and was running fine in Linux OS. But when I ran the same package in Windows, it threw file not found exception for classpath ".wso2\lib". But when i changed classpath to ".\wso2\lib", it running alright. I had add "\" to get it working.

Thanks,
Sanketh
