### ISSUE TITLE
[Critical] Datasources are not getting synced with the worker nodes

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#52]
**Steps**

1. Create an Integrator cluster.
2. Login to Management console and create a new datasource.
3. With the created datasource, try to create a data service.

*Issue* : When the service in synced to the worker following error is thrown. It seems the Datasource is not getting synced to the worker nodes.

> ERROR {org.wso2.carbon.dataservices.core.DBDeployer} -  The Orders_DataService.dbs service, which is not valid, caused {1} {org.wso2.carbon.dataservices.core.DBDeployer}
> DS Fault Message: The Carbon data source 'LocalMySQL' cannot be found
> DS Code: UNKNOWN_ERROR
> Source Data Service:-
> Name: Orders_DataService
> Location: /Orders_DataService.dbs
> Description: N/A
> Default Namespace: http://ws.wso2.org/dataservice
> 
> 	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.getCarbonDataSourceConfig(ConfigFactory.java:169)
> 	at org.wso2.carbon.dataservices.core.description.config.ConfigFactory.createConfig(ConfigFactory.java:76)
> 	at org.wso2.carbon.dataservices.core.DataServiceFactory.createDataService(DataServiceFactory.java:159)
> 	at org.wso2.carbon.dataservices.core.DBDeployer.createDBService(DBDeployer.java:797)
> 	at org.wso2.carbon.dataservices.core.DBDeployer.processService(DBDeployer.java:1152)
> 	at org.wso2.carbon.dataservices.core.DBDeployer.deploy(DBDeployer.java:201)
> 	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
> 	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
> 	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
> 	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
> 	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
> 	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
> 	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
> 	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
> 	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
> 	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
>

**Comment by madhawa-gunasekara** [comment]
Did you share the registry ?

**Comment by yasassri** [comment]
@madhawa-gunasekara It seems there was a misconfiguration in my registry mounting, Please disregard this issue.
