### ISSUE TITLE
Default endpoint support for Mock services.

### ISSUE THREAD

**Issue by NikithaUdeshana** [wso2/product-ei#5225]
**Description:**
Default endpoint support has not been provided for Mock services in the WSO2 micro integrator. 
However, this functionality is required to mimic the dynamic endpoints behaviors where the URL is defined in the To header.

**Suggested Labels:**
Type/Improvement, Micro Integrator, Integration Studio

**Affected Product Version:**
Integration Studio 7.0.2, MI 1.1.0

**Comment by sajithaliyanage** [comment]
The issue has been fixed for MI 1.1.0 (https://github.com/wso2-support/wso2-synapse/pull/873) and MI 1.2.0 (https://github.com/wso2-support/wso2-synapse/pull/894)
