### ISSUE TITLE
Error: Could not find or load main class org.wso2.carbon.secvault.ciphertool.CipherToolInitializer

### ISSUE THREAD

**Issue by uarulraj486** [wso2/product-ei#5238]
**Description:**
Streaming Integrator 1.0.0

Unable to start the ciphertool.bat

I tried to start the StreamingIntegrator  ciphertool.bat
I got the below error 
\wso2ei-7.0.2\streaming-integrator\bin>ciphertool -runtime server
JAVA_HOME environment variable is set to \Java\jdk-11.0.7
CARBON_HOME environment variable is set to WSO2EI~1.2\STREAM~1\bin\..
**_Error: Could not find or load main class org.wso2.carbon.secvault.ciphertool.CipherToolInitializer_**

How to resolve the error and proceed furthur

**Comment by lkokila** [comment]
The is a problem in the ciphertool.bat. The java -cp command needs to be updated with the correct path to the <Product_Home>\bin\tools directory. 

`java -cp "\bin\tools\*" -Dcarbon.home="%CARBON_HOME%" org.wso2.carbon.secvault.ciphertool.CipherToolInitializer %*`
