### ISSUE TITLE
EI 6.6.0 - JVM Full Load of Processors

### ISSUE THREAD

**Issue by LLC-BigInt** [wso2/product-ei#5240]
Enterprise Integrator 6.6.0.
OS: Ubuntu (8 Core, 24Gb Mem)
DB: PostgreSQL
Used near 300 resource (100 API (3 resource in every API))

For a month I have been observing the loading of processors at 100%. Reboot (integrator.sh stop/start) helps for a few hours - after 100% again
I Tried:
1. deleted all the API.
2. to replace
JVM_MEM_OPTS="-Xms2048m -Xmx10G -XX:MaxPermSize=256m -XX:-UseGCOverheadLimit"
to
JVM_MEM_OPTS="-Xms10g -Xmx10g -XX:MaxPermSize=512m -XX:-UseGCOverheadLimit -XX:+UseG1GC -XX:+UseStringDeduplication"

The load still remains.

Any ideas?
I will be very grateful

**Comment by Vathsan** [comment]
Hi @LLC-BigInt, we have fixed a CPU hike issue mentioned in https://github.com/wso2/product-apim/issues/8908, for EI 6.6.0. Please verify if it is the same. The particular fix is available as a WUM update(released on 08/14/2020).

**Comment by LLC-BigInt** [comment]
> Hi @LLC-BigInt, we have fixed a CPU hike issue mentioned in [wso2/product-apim#8908](https://github.com/wso2/product-apim/issues/8908), for EI 6.6.0. Please verify if it is the same. The particular fix is available as a WUM update(released on 08/14/2020).

How I can take only one this file? the problem is to update the entire platform, but the specific problem is resolved

**Comment by Vathsan** [comment]
> > Hi @LLC-BigInt, we have fixed a CPU hike issue mentioned in [wso2/product-apim#8908](https://github.com/wso2/product-apim/issues/8908), for EI 6.6.0. Please verify if it is the same. The particular fix is available as a WUM update(released on 08/14/2020).
> 
> How I can take only one this file? the problem is to update the entire platform, but the specific problem is resolved

WUM downloads all the available updates. We do not support providing a patch for EI 6.6.0 version.

**Comment by LLC-BigInt** [comment]
switched to JAVA 8, works well
on JAVA11 works not good (even after updating)
