### ISSUE TITLE
Relese tag for 7.0 and 7.1 releases not available

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#5249]
**Description:**
Can't fing a release tag for versions 7.0 and 7.1. The latest tagged release is 6.6.0

**Suggested Labels:**
EI7, 7.0, 7.1

**Suggested Assignees:**

**Affected Product Version:**
7.0, 7.1

**OS, DB, other environment details and versions:**    
all

**Steps to reproduce:**
Go to https://github.com/wso2/product-ei and try to find 7.0 or 7.1 relase tag or branch.

**Related Issues:**

**Comment by Nirothipan** [comment]
Hi @markokocic 

EI  7 is a combination of Micro Integrator and Streaming Integrator. Please check the individual repos of them https://github.com/wso2/micro-integrator & https://github.com/wso2/streaming-integrator

EI 7    = MI 1.1.0 + SI 1.0.0
EI 7.1 = MI 1.2.0 + SI 1.1.0

Thanks

**Comment by markokocic** [comment]
Then "Github Community" link on the EI 7 dowload page https://wso2.com/integration/ needs to point to either micro-integrator or streaming-integrator Github project, with the explanation how to build the 7.x distribution.

Right now link points to product-ei project, which seems to be used to release only 6.x branch.

**Comment by Nirothipan** [comment]
We updated the link in above said pages with more clarity.

**Comment by markokocic** [comment]
Thanks, this makes it more clear. Although it would be better to have direct link to the github release page than the project page.
