### ISSUE TITLE
Missing application logs and system logs

### ISSUE THREAD

**Issue by markokocic** [wso2/product-ei#5250]
**Description:**
Under monitoring tab in carbon the option to see application and system logs is missing.
It was available in EI 6.5.0

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
6.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Try to find system and application logs in carbon console.

**Related Issues:**

**Comment by Nirothipan** [comment]
Hi @markokocic 

This was removed in 6.6.0. Please refer https://github.com/wso2/product-ei/issues/4925 for more details
