### ISSUE TITLE
Unexpected EOF in prolog error occurs while getting HTTP 201 response in blocking mode

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#5251]
**Description:**
The exception "org.apache.axiom.om.OMException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog"  occurs when calling an HTTP PUT request in the blocking mode and when the corresponding response contains,

201-Created HTTP response code.
No entity/payload.
No Content-Type header.

Since the call mediator in blocking mode is content-aware, the ESB tries to build the response message based on the Content-Type header in the response. Whenever there is no Content-Type header specified, the StAXOMBuilder will be executed by default to build the response message. But in this case, since there is no entity/content in the response to build, the StAXOMBuilder will fail with the following stack trace while trying to build an empty stream.

**Affected Product Version:**
wso2esb-5.0.0

**Steps to reproduce:**
Use the following api as the backend

```
<api xmlns="http://ws.apache.org/ns/synapse" name="sampleApi" context="/samplePutReq">
   <resource methods="PUT">
      <inSequence> 	
         <property name="ContentType" scope="axis2" action="remove"/>
         <property name="NO_ENTITY_BODY" value="true" scope="axis2" type="BOOLEAN"/>
         <property name="HTTP_SC" value="201" scope="axis2" type="STRING" description="Set HTTP_HC 201"/>
         <respond/>
      </inSequence>
      <outSequence/>
      <faultSequence/>
   </resource>
</api>
```

And the following API to call it

```
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns="http://ws.apache.org/ns/synapse" name="testingApi" context="/test">
   <resource methods="GET">
      <inSequence>
         <payloadFactory media-type="json">
            <format>{"state":"UploadComplet"}</format>
            <args />
         </payloadFactory>
         <call blocking="true">
            <endpoint>
               <http method="PUT" uri-template="http://localhost:8281/samplePutReq" />
            </endpoint>
         </call>
         <respond />
      </inSequence>
      <outSequence />
      <faultSequence />
   </resource>
</api>
```

**Related Issues:**
https://github.com/wso2/product-ei/issues/4695
https://github.com/wso2/product-ei/issues/4811

**Comment by Vathsan** [comment]
The same error is thrown when receiving an empty payload with HTTP 200 as well. Improved the fix via https://github.com/wso2/wso2-axis2/pull/225
