### ISSUE TITLE
WSO2 EI 6.5.0 Send Email With Attachment

### ISSUE THREAD

**Issue by Sovereignsun** [wso2/product-ei#5252]
**Description:**
I am trying to send an email to my personal email account with an attachment via the WSO2 EI 6.5.0 API. The problem is that the attachment file always comes as an "Untitled.bin" file whatever file I send. I want it to be the correct name and extension.

**Suggested Labels:**
wso2, wso2 ei, wso2 smtp, mail with attachment, wso2 email

**Affected Product Version:**
WSO2 EI 6.5.0

**OS, DB, other environment details and versions:**

Windows 7 x64, Fiddler    

**Steps to reproduce:**
--

API:

`<api xmlns="http://ws.apache.org/ns/synapse" name="EMailAPI" context="/email_api" version="1.0" version-type="context">
   <resource methods="POST" uri-template="/test_send_attachment">
      <inSequence>
         <property name="FORCE_ERROR_ON_SOAP_FAULT" value="true" scope="default" type="STRING"/>
         <payloadFactory media-type="xml">
            <format>
               <ns:binary xmlns:ns="http://ws.apache.org/commons/ns/payload">$1</ns:binary>
            </format>
            <args>
               <arg evaluator="xml" expression="//*[local-name()='binary']/text()"/>
            </args>
         </payloadFactory>
         <log level="custom">
            <property name="[Email_API].test_send_attachment Resource" expression="/"/>
         </log>
         <script language="js">var binaryNode=mc.getEnvelope().getBody().getFirstElement().getFirstOMChild();binaryNode.setBinary(true);</script>
         <log level="custom">
            <property name="[Email_API].test_send_file binary" expression="/"/>
         </log>
         <property name="Subject" value="Testing WSO2 EI File" scope="transport"/>
         <property name="transport.mail.bodyWhenAttached" value="Check the attachment" scope="axis2"/>
         <property name="messageType" value="image/jpeg" scope="axis2"/>
         <property name="ContentType" value="image/jpeg" scope="axis2"/>
         <property name="FORCE_SC_ACCEPTED" value="true" scope="axis2"/>
         <property name="OUT_ONLY" value="true"/>
         <send>
            <endpoint name="FileEndpoint">
               <address uri="mailto:<email_address>"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence/>
   </resource>
</api>`

change email_address to whatever email eddress

AXIS2:

`<messageFormatters>
	    <messageFormatter contentType="image/jpeg"
                        class="org.wso2.carbon.relay.ExpandingMessageFormatter"/>`

`<messageBuilders>
	    <messageBuilder contentType="image/jpeg"
                        class="org.wso2.carbon.relay.BinaryRelayBuilder"/>`

FIDDLER TELERIK:

`POST http://localhost:8280/email_api/test_send_attachment HTTP/1.1
User-Agent: Fiddler
Host: 10.15.2.9:8280
Content-Length: 266276

<binary data>`

In binary data just send some binary file

**Comment by Sovereignsun** [comment]
What way can I send files over smtp in WSO2 EI 6.5.0, files like pdf/jpg/png/xml and others?

The idea is to be able to post a file into the API for it to be sent.

**Comment by Vathsan** [comment]
Hey @Sovereignsun, Please try the following sample and see if that solves the issue. You can deploy the sample and use SOAP UI to send a message with attachment (eg.dfcc.jpg). Make sure to update the attachment file in the configuration.

Note that we have added the property `<property name="enableSwA" value="true" scope="axis2"/>`so that the incoming SwA messages are automatically identified by EI.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="sampleService"
       transports="http"
       startOnLoad="true">
   <description/>
   <target>
      <inSequence>
         <log level="custom">
            <property name="sequence" value="sendMailSequence"/>
         </log>
         <property name="transport.mail.Format" value="Attachment" scope="axis2"/>
         <property name="AttachmentFile" value="dfcc.jpg" scope="axis2"/>
         <property name="Subject" value="File Received" scope="transport"/>
         <property name="OUT_ONLY" value="true" scope="default" type="STRING"/>
         <send>
            <endpoint name="FileEpr">
               <address uri="mailto:srivathsan@wso2.com"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <send/>
      </outSequence>
   </target>
</proxy>
```
I tried the sample for jpg and pdf files and was able to successfully send over smtp. You may refer [1] for more details regarding content optimization.

[1] https://docs.wso2.com/pages/viewpage.action?pageId=59577164

**Comment by Sovereignsun** [comment]
It does work in a way... Now how to understand the way it works?

I send binary data via Fiddler and for instance the name of the file and extension are always different, should I always update the property "<property name="AttachmentFile" value="dfcc.jpg" scope="axis2"/>"?

What does <property name="transport.mail.Format" value="Attachment" scope="axis2"/> stand for?

Is there a way I can include text in the message together with an attachment?

**Comment by Vathsan** [comment]
> It does work in a way... Now how to understand the way it works?

MTOM/SWA message is a mechanism to attach a file in an existing SOAP message. It sort of provides the knowledge to EI to transfer the response back to the client in the same format as the original request.

You may refer [1], [2] for more explanation.

> I send binary data via Fiddler and for instance the name of the file and extension are always different, should I always update the property `<property name="AttachmentFile" value="dfcc.jpg" scope="axis2"/>`?

You may remove this property, as the original name,  extension will be preserved.

> What does `<property name="transport.mail.Format" value="Attachment" scope="axis2"/>` stand for?

This parameter sets the format of the outgoing mail. As we are sending a message with an attachment it should be either Attachment/Multipart. You may refer [3] for all available parameters.

> Is there a way I can include text in the message together with an attachment?

You may use the parameter **transport.mail.bodyWhenAttached** to set the content of the message body.
Eg:. `<property name="transport.mail.bodyWhenAttached" expression="$ctx:body/*" scope="axis2"/>`

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/endpoint_examples/mtom-swa-with-endpoints/
[2] https://www.yenlo.com/blog/handling-mtom-and-swa-messages-in-wso2-esb#:~:text=MTOM%2FSWA%20message%20is%20a,divided%20by%20using%20a%20boundary.
[3] https://docs.wso2.com/display/EI650/MailTo+Transport

**Comment by Sovereignsun** [comment]
Well, interestingly I get a somewhat odd behaviour. I send this request:

`POST http://localhost:8280/services/SWAService HTTP/1.1
SOAPAction: "urn:mediate"
Content-Type: multipart/related; boundary=MIME; type="text/xml"; start="<MimeStart>"
Connection: Keep-Alive
Host: 10.15.2.9:8280
Content-Length: 2505

--MIME
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit
Content-ID: <MimeStart>

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body/>
</soapenv:Envelope>

--MIME

Content-Type: image/x-png; name=exit_icon.png
Content-Transfer-Encoding: binary
Content-Disposition: attachment; name="exit_icon.png"; filename="exit_icon.png"
Content-ID:<exit_icon.png>

iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAFwUlEQVR42rWWaWxUVRTHz3nLvJl5nZkuTBcoVHYqixpMUBCDRgUpoEBcQkICo2DZGmyjCRqEgKBWC9awFdLGhJCoIahoUBMNGjYDJBIRKpCCNKW0pdN2On2zvveO591SLKQf/KA3uTNz37v3/M4593/PHYT/uaHz0ZSXJ8l5ebPNWGy6nUpJfS/pnsk0wPN7n6Gq2m6v9xiFw0cKm5ttAbhRXDxX37z5q87mZslKp/vmY7+12M9g31h80z1zGEDZBQVkbNjw/LCLF78RD//IyfmQysoqaPDg/yYtiQQkN26sejgcfkMATsvyNlixYq0yapQYW0RU39WFI3w+8CrKXRHAPRHETBOuRqNUnJmJMoppRLEYRtev3z7DssrFk1Oy/DEtXVomDx+ONo/bcnPpkXnz8PeTJ0G7cIE0xAEBSSJMjh8Pk6ZOpV8PH8bctjbgDSQ0TYxs2lT9tGWtFQuPSdIn9qJFq6WiIkDu4xYsAEVR2BWCc8ePc4inQbHtu9KQZiZOmQIPTJsGkiSByZHUHzoEcP06KPwusnXrjlm2XSYARyVph71w4UqpsBBVXYdxoRDJWVlos1HLsujS2bOYPHoUZDbieG4pCrpmzKAxkyejLMuOM2R1duKfdXWQNgxSNQ27Kit3zrHt1QLwI+Iua86cUiwoEGOXz0fFpaUoZWYKAHdsPH8e4t9/K1TkmVmCQydMIPZcALC7m+prajAVjQoH3H4/dlZV7X6OaCVWcT7HA+yyZs58DYLBOynQ/D4Yv2YNUEBAwInm1pVLIm05I0eDsy1OapSeKNTv3AnJ7uidtTrbCW/fXtMNsBI/YsA4gD3Wk08sY2MiAgmBVAXQmx2A0avLKe0L9KXLAYhN5kaaEcWru6sh1hGhtAmo6BngCgQo1tKC8YMH9zKyFCt58liAvcb9xa8Ae+vSvaB5FHCpnCoFwJudCUNWvAkJPSCicLrD0M0khA/UQE9LKySMJBgRA8INjdDZcBXUDB0G9Ri1BsByfJcBxQD72gO+UDQSRbdHBp9fowy/G726Cuj3kfXqOhzz6OMiAmdPuGHzuTMU27wKKRqDeAoonuQzkQBIpoG0TD/6u7prOYJlAsAR7OvICYRinRH0utlrN5CuAcp+D5irNtODJfPRMe5I0QFwFOhQGk/9glC9DsxIjGIMMBjAEFKzM1Fv73Ii6AWMZkAkLzuU6OjADA9vkgbkyvKiWvEBTJw1T6jIMa53NglA2DNIAFwuFzafOQHGe+WU6jSQMwU9cSA5Jxs9LR21sT7AKAZEhwwKpdrbwQF4snXI2lANE54pgT7PPeHrIFW+4BQCSLx+ALoyCoABoGkaNJ0+DjfXlUIs3OMAQA4OAqWpvS7RBxjBgHhRbijV2oZ6MAOKKnfTRNb6beOktl5FeH8+uONtQucJTxDTFV9QMjgcb0Po2omfsX7VEui5FSU5Pxfhr7baZB/gPgakRuaFks2tyKcYHtqyTUhRKObGFYq9Mxc9iTbQ3b21iHONcS1I7o1fozR0LPBhI0e3v71dDvW1taQOyUOrobU2RbcBRQwwx+SH4o0t4PerMK1mP2Q/+SxYjZehpaIENPbcw8bdau9BSvCVEXcU4wlCftURkIeNgY6j38GJ5YuhuzsNWlE+mJdb6u4AhjLALi4IGQ03Uec98PlUGhsqxehPn4HLuEWsKtRcAKrcG0HaAkyyNFkxmPIGwffUy3Spbg9Go2kweJO9o/IxXd9Sm3YAWxyAqu6BSYXLOs5dEwBHRY5RIVn+7WHJOgdP7r1MybLZcPq29pO90nRgjoocQOaEQkxfuLk3ZVqlojR8qbkWp2ZP/zTR1IASn1AuE3d1hT3nsuOUENFs3iGGgGlx2Tb/6SnuJnCZ92eR/8SFJS+a1n6x5AeuCoamvtQF9JiZNuWBLvqB/gQM1GRZsgIEx/2m/fksZva/qWCro5x/aWjAu9gplNzf6mfib96T0koiuIbpAAAAAElFTkSuQmCC

--MIME--`

And receive an email with two attachments, one of which is the **exit_icon.png** file, which is readable and viewable, while the other is an _untitled attachment with a random number_ in a _txt_ extension containing the text of the value of the parameter **transport.mail.bodyWhenAttached**

My proxy is:

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="SWAService"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http">
   <target>
      <inSequence>
         <property name="enableSwA" scope="axis2" type="STRING" value="true"/>
         <log level="custom">
            <property name="[SWAService] Initialize" value="SendMailSequence"/>
         </log>
         <property name="transport.mail.Format" scope="axis2" value="Multipart"/>
         <property name="Subject" scope="transport" value="WSO2 EI SWA Testing"/>
         <property name="OUT_ONLY" scope="default" type="STRING" value="true"/>
         <property name="FORCE_SC_ACCEPTED" scope="axis2" value="true"/>
         <log level="custom">
            <property expression="/" name="[SWAService] Before Send"/>
         </log>
         <property name="transport.mail.bodyWhenAttached"
                   scope="axis2"
                   value="This message was sent to you by Alex"/>
         <send>
            <endpoint name="FileEP">
               <address optimize="swa" uri="mailto:<email>"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence/>
   </target>
   <description/>
</proxy>
```
                                
![Email Screenshot](https://user-images.githubusercontent.com/35687591/92579827-5ac38280-f296-11ea-9083-75c56c2050b5.JPG)

**Comment by Sovereignsun** [comment]
Oh, I got it:

```
POST http://itprog10:8280/email/send HTTP/1.1
Content-Type: multipart/related; type="text/xml"; start="<rootpart@soapui.org>"; boundary="----=_Part_18_553009174.1599641679220"
SOAPAction: "urn:mediate"
MIME-Version: 1.0
Content-Length: 2640
Host: itprog10:8280

------=_Part_18_553009174.1599641679220
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit
Content-ID: <rootpart@soapui.org>

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body>
<message>Testing file sending</message>
</soapenv:Body></soapenv:Envelope>

------=_Part_18_553009174.1599641679220
Content-Type: image/x-png; name=exit_icon.png
Content-Transfer-Encoding: base64
Content-ID: <exit_icon.png>
Content-Disposition: attachment; name="exit_icon.png"; filename="exit_icon.png"

iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAFwUlEQVR42rWWaWxUVRTHz3nLvJl5nZkuTBcoVHYqixpMUBCDRgUpoEBcQkICo2DZGmyjCRqEgKBWC9awFdLGhJCoIahoUBMNGjYDJBIRKpCCNKW0pdN2On2zvveO591SLKQf/KA3uTNz37v3/M4593/PHYT/uaHz0ZSXJ8l5ebPNWGy6nUpJfS/pnsk0wPN7n6Gq2m6v9xiFw0cKm5ttAbhRXDxX37z5q87mZslKp/vmY7+12M9g31h80z1zGEDZBQVkbNjw/LCLF78RD//IyfmQysoqaPDg/yYtiQQkN26sejgcfkMATsvyNlixYq0yapQYW0RU39WFI3w+8CrKXRHAPRHETBOuRqNUnJmJMoppRLEYRtev3z7DssrFk1Oy/DEtXVomDx+ONo/bcnPpkXnz8PeTJ0G7cIE0xAEBSSJMjh8Pk6ZOpV8PH8bctjbgDSQ0TYxs2lT9tGWtFQuPSdIn9qJFq6WiIkDu4xYsAEVR2BWCc8ePc4inQbHtu9KQZiZOmQIPTJsGkiSByZHUHzoEcP06KPwusnXrjlm2XSYARyVph71w4UqpsBBVXYdxoRDJWVlos1HLsujS2bOYPHoUZDbieG4pCrpmzKAxkyejLMuOM2R1duKfdXWQNgxSNQ27Kit3zrHt1QLwI+Iua86cUiwoEGOXz0fFpaUoZWYKAHdsPH8e4t9/K1TkmVmCQydMIPZcALC7m+prajAVjQoH3H4/dlZV7X6OaCVWcT7HA+yyZs58DYLBOynQ/D4Yv2YNUEBAwInm1pVLIm05I0eDsy1OapSeKNTv3AnJ7uidtTrbCW/fXtMNsBI/YsA4gD3Wk08sY2MiAgmBVAXQmx2A0avLKe0L9KXLAYhN5kaaEcWru6sh1hGhtAmo6BngCgQo1tKC8YMH9zKyFCt58liAvcb9xa8Ae+vSvaB5FHCpnCoFwJudCUNWvAkJPSCicLrD0M0khA/UQE9LKySMJBgRA8INjdDZcBXUDB0G9Ri1BsByfJcBxQD72gO+UDQSRbdHBp9fowy/G726Cuj3kfXqOhzz6OMiAmdPuGHzuTMU27wKKRqDeAoonuQzkQBIpoG0TD/6u7prOYJlAsAR7OvICYRinRH0utlrN5CuAcp+D5irNtODJfPRMe5I0QFwFOhQGk/9glC9DsxIjGIMMBjAEFKzM1Fv73Ii6AWMZkAkLzuU6OjADA9vkgbkyvKiWvEBTJw1T6jIMa53NglA2DNIAFwuFzafOQHGe+WU6jSQMwU9cSA5Jxs9LR21sT7AKAZEhwwKpdrbwQF4snXI2lANE54pgT7PPeHrIFW+4BQCSLx+ALoyCoABoGkaNJ0+DjfXlUIs3OMAQA4OAqWpvS7RBxjBgHhRbijV2oZ6MAOKKnfTRNb6beOktl5FeH8+uONtQucJTxDTFV9QMjgcb0Po2omfsX7VEui5FSU5Pxfhr7baZB/gPgakRuaFks2tyKcYHtqyTUhRKObGFYq9Mxc9iTbQ3b21iHONcS1I7o1fozR0LPBhI0e3v71dDvW1taQOyUOrobU2RbcBRQwwx+SH4o0t4PerMK1mP2Q/+SxYjZehpaIENPbcw8bdau9BSvCVEXcU4wlCftURkIeNgY6j38GJ5YuhuzsNWlE+mJdb6u4AhjLALi4IGQ03Uec98PlUGhsqxehPn4HLuEWsKtRcAKrcG0HaAkyyNFkxmPIGwffUy3Spbg9Go2kweJO9o/IxXd9Sm3YAWxyAqu6BSYXLOs5dEwBHRY5RIVn+7WHJOgdP7r1MybLZcPq29pO90nRgjoocQOaEQkxfuLk3ZVqlojR8qbkWp2ZP/zTR1IASn1AuE3d1hT3nsuOUENFs3iGGgGlx2Tb/6SnuJnCZ92eR/8SFJS+a1n6x5AeuCoamvtQF9JiZNuWBLvqB/gQM1GRZsgIEx/2m/fksZva/qWCro5x/aWjAu9gplNzf6mfib96T0koiuIbpAAAAAElFTkSuQmCC
------=_Part_18_553009174.1599641679220--
```

This works correctly when I set `<property name="transport.mail.bodyWhenAttached" expression="$ctx:body/*" scope="axis2"/>` and `<property name="transport.mail.Format" value="Text" scope="axis2"/>`

I guess I am making progress in grasping the hang of it!

**Comment by Sovereignsun** [comment]
Is there a way to go past the send mediator in this particular case and send a payload of my own in a response? I mean go to the outSequence?

Somehow whatever I try the request just hangs and doesn't go on unless I say `<property name="FORCE_SC_ACCEPTED" value="true" scope="axis2"/>`

**Comment by Vathsan** [comment]
The OUT_ONLY property indicates that no response message is expected (we do not receive any response for sending the mail). So, we use FORCE_SC_ACCEPTED property to stop the client waiting for a response.
As an alternative, you may use the clone mediator and send one message to the mailto transport endpoint and send the other one to a sequence or to a default send (which returns back to the client).

**Comment by Vathsan** [comment]
@Sovereignsun: Closing this issue as the configuration for the required scenario is provided. Please re-open if you need further assistance.
