### ISSUE TITLE
The vault-lookup function is not working in the latest EI 6.6.0

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#5256]
**Description:**

The vault-lookup function is not working in the latest WUM updated EI 6.6.0 version. The consumer.secret and the corresponding password value is added through the UI. This is then retrieved in the mediation. But the resulting value is empty.
```
<log level="custom">
                <property expression="wso2:vault-lookup('consumer.secret')" name="app.clientSecret"/>
 </log>
[2020-09-04 13:29:30,198]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - app.clientSecret =

```

The same is working in the fresh EI 6.6.0 version.

**Comment by nirmal070125** [comment]
This fix has introduced a backward incompatible change. All the custom xpath extensions are broken with this change. @malakaganga @sajithaliyanage
