### ISSUE TITLE
Add OAuth 2.0 token revocation mechanism and client-credentials flow to the connector core 

### ISSUE THREAD

**Issue by Shakila** [wso2/product-ei#5263]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

ESB 4.9.0 and all WSO2 EI versions. 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Shakila** [comment]
https://github.com/wso2-support/carbon-mediation/pull/416

**Comment by abeykoon** [comment]
We need to fix it in public mater branch and refer that PR here as well to close the issue. Could you please point to public fix?
