### ISSUE TITLE
DSS Error for Stored Procedures when Correlation logging is Enabled.

### ISSUE THREAD

**Issue by sachithKay** [wso2/product-ei#5281]
**Description:**
When invoking a stored procedure using DSS (with correlation logging enabled in the server), it causes an DSS Fault.
Given below is a sample data service.
```
<data name="sampledss" transports="http https local">
   <config enableOData="false" id="dss">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
      <property name="url">jdbc:mysql://localhost:3306/dss?&amp;useSSL=false</property>
      <property name="username">root</property>
      <property name="password">root</property>
   </config>
   <query id="spquery" useConfig="dss">
      <sql>call GET_STUDENT()</sql>
      <result outputType="json">{"students": {"student":[{"fistName": "$first_name","last_name": "$last_name","Email": "$email"}]}}</result>
   </query>
   <operation name="spqueryOp">
      <call-query href="spquery"/>
   </operation>
   <resource method="GET" path="spquery">
      <call-query href="spquery"/>
   </resource>
</data>
```

The stored procedure in question is as follows.

```
CREATE PROCEDURE GET_STUDENT()
BEGIN
   SELECT 
      FIRST_NAME, LAST_NAME, EMAIL
   FROM 
      STUDENT;
END
```

**Comment by ismailazerty** [comment]
Hello @sachithKay ,

   I have seen your correction for this problem in carbon-kernel, but I didn't find it in any tag.
   Is there a way to override just the classe CorrelationLogInterceptor in wso2 6.6.0 ?

thank you

**Comment by sachithKay** [comment]
@ismailazerty, I have added the fix to the public branch of the carbon-kernel. You can reach out to WSO2 support and obtain the U2 update fixing this issue. If you are a community user, you can extract the fix and build the carbon-kernel  version relevant to EI-6.6.0 locally, and patch your existing product distribution.
