### ISSUE TITLE
Is there a way to start and stop the scheduled tasks in WSO2 mi 1.1.0

### ISSUE THREAD

**Issue by meenak89** [wso2/product-ei#5283]
How to start and stop the scheduled tasks in WSO2 mi 1.1.0 or wso2 mi 1.2.0 using management dashboard or CLI commands

**Comment by BeParis** [comment]
Hi,

Using APIM 3.2 I very often get this message box when finishing edit process in
Home<https://test.api.sgsi.ucl.ac.be:9443/carbon/admin/index.jsp>        > Identity      > Identity Providers    > List  then  Identity provider > Edit


[cid:5032C333-9AB8-4ED5-937D-7B521A585420@home]


Bernard
