### ISSUE TITLE
PayloadFactory mediator converting array to an object when there is only one element in the array

### ISSUE THREAD

**Issue by vinay-centime** [wso2/product-ei#5286]
**Description:**
While using PayloadFactory with a JSON message format, the mediator is automatically converting single-value JSON arrays to JSON objects. For example when my message format is `{"testArr":["some text"]}` it is automatically converted to `{"testArr":"some text"}` and passed on forward

**Suggested Labels:**
ESB, PayloadFactory

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
macOS Catalina 10.15.7
Integration Studio 7.1.0

**Steps to reproduce:**

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-4750

**Comment by arunans23** [comment]
Can you provide the synapse artifacts in which you encountered this issue?

**Comment by vinay-centime** [comment]
@arunans23 It is a simple PayloadFactory mediator. Below is the definition of the sequence - 
`<?xml version="1.0" encoding="UTF-8"?>
<sequence name="TestSequence" trace="disable" xmlns="http://ws.apache.org/ns/synapse">
    <payloadFactory media-type="json">
        <format>{"testArr":["some text"]}</format>
        <args/>
    </payloadFactory>
    <log level="full" separator=",">
        <property expression="json-eval($)" name="json"/>
    </log>
</sequence>
`
This sequence is connected to a simple REST API. Please let me know if you need any other information.

P.S: I am still a beginner at WSO2 and learning all the concepts

**Comment by arunans23** [comment]
What is the version of the runtime are you using? In the latest versions, ideally, it should not happen. For some reason, if it happens, you should be able to correct the payload information with JSON Transform mediator. https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/json-Transform-Mediator/#converting-an-array-of-one-from-xml-to-json

**Comment by vinay-centime** [comment]
If you are referring to the version of of Micro Integrator Server, it is 1.2.0

As per the JIRA story - https://wso2.org/jira/browse/ESBJAVA-4750 this issue has been fixed right? Can you re-open that issue?

**Comment by arunans23** [comment]
We are no longer maintaining issues in JIRA. We use Github to track our issues. Hence we can keep this issue open and track the issue. 

But in your case, I tried to reproduce with the following API, but it worked perfectly.

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/hello" name="HelloWorld" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence>
            <payloadFactory media-type="json">
                <format>{"testArr":["some text"]}</format>
                <args/>
            </payloadFactory>
            <log level="full" separator=",">
                <property expression="json-eval($)" name="json"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

I got a JSON response with an array and the Log mediator printed the following.

`[2020-10-14 22:44:14,549]  INFO {LogMediator} - {api:HelloWorld} To: /hello,MessageID: urn:uuid:90dc0194-b769-46d5-911a-61457bf4bb37,Direction: request,json = {"testArr":["some text"]},Payload: {"testArr":["some text"]}`

**Comment by vinay-centime** [comment]
I modified your API a bit as below - 

`<?xml version="1.0" encoding="UTF-8"?>
<api context="/hello" name="HelloWorld" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <payloadFactory media-type="json">
                <format>{"testArr":["some text"]}</format>
                <args/>
            </payloadFactory>
            <log level="full" separator=",">
                <property expression="json-eval($)" name="json"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>`

Observe the `resource method` in the above XML.
Below is the log response - 

`[2020-10-14 23:55:03,895]  INFO {LogMediator} - {api:HelloWorld} To: /hello,MessageID: urn:uuid:43d88a1b-257f-4100-8001-da6c06422c19,Direction: request,json = {"testArr":"some text"},Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><jsonObject><testArr>some text</testArr></jsonObject></soapenv:Body></soapenv:Envelope>
`

Can you tell us why a POST request is resulting in this behaviour?

**Comment by arunans23** [comment]
I think you are sending a non-JSON Content-Type to this API. In that case, try adding messageType property inside your sequence.

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/hello" name="HelloWorld" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence>
            <payloadFactory media-type="json">
                <format>{"testArr":["some text"]}</format>
                <args/>
            </payloadFactory>
            <property name="messageType" value="application/json" scope="axis2"/>
            <log level="full" separator=",">
                <property expression="json-eval($)" name="json"/>
            </log>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

**Comment by vinay-centime** [comment]
Yes, when I explicitly mention `application/json` as the `Content-Type` in the HTTP Request headers, I am seeing the expected behaviour. But I have another use case wherein I have a Kafka based input endpoint. How do I set this content type in this case?

**Comment by arunans23** [comment]
Since you have explicitly created a JSON payload with PayloadFactory, you can set the messageType property inside the sequence.

**Comment by vinay-centime** [comment]
Thank you @arunans23 We also have a couple of queries regarding the best practices for project structure and micro services implementation. We need your guidance on the same. How can we reach out to you for this consultation?

**Comment by arunans23** [comment]
Please visit our slack channel https://ei-slack.wso2.com/. Or you can take our official subscription and get guaranteed responses. https://wso2.com/subscription/
