### ISSUE TITLE
Add FreeMarker template support for PayloadFactory mediator 

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-ei#5295]
**Description:**
The current PayloadFactory implementation has limitations such as,

- Unable to access payload and properties directly.
- Can't implement loops.
- Unable to implement conditions. 

Because of these limitations, it is hard to perform complex transformations using the PayloadFactory mediator. Plus many users are facing performance issues on Datamapper mediator. To overcome those limitations, I suggest implementing support for  Apache FreeMarker (https://freemarker.apache.org/) in the PayloadFactory mediator. In the FreeMarker script, users should be able to use the payload, properties, and arguments. 
But for backward compatibility, we should preserve the current implementation and add FreeMarker as a second option. And add an attribute to the payload factory to allow switching between template types.

**Comment by tharakamd** [comment]
Added FreeMarker support for the PayloadFactory with this pull,
https://github.com/wso2/wso2-synapse/pull/1653

**Comment by chetan018** [comment]
I am using wso2ei 6.6,how to implement freemarker in 6.6 version,can you please guide on this.

**Comment by dilan-iit** [comment]
@chetan018 ,
FreeMarker templating support is only available in MI versions after MI 1.2.0. (in MI 1.2.0 and MI 4.0.0 only)

**Comment by tharakamd** [comment]
@chetan018 ,
FreeMarker templating is only available in MI 1.2.0 and MI 4.0.0 version only

**Comment by insaovisal26** [comment]
@tharakamd
