### ISSUE TITLE
Class Mediator Properties cannot have empty values for "value" attribute

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/product-ei#5306]
**Description:**
Earlier it was possible to have empty values for "value" attribute in Class Mediator Properties. 

```
<class name="com.sample.custom">
         <property name="jsonPath" value=""/>
</class>
```
But with the fix done here in https://github.com/wso2-support/carbon-mediation/pull/378 and https://github.com/wso2-support/wso2-synapse/pull/821, we have accidentally removed that capability while adding properties support. 

**Affected Product Version:**
EI-6.1.1

**Comment by LLC-BigInt** [comment]
Yes, I confirm in EI 6.6.0 this mestake too
If i Add properties into class
```
<class name="ua.com.infotech.RSAUtil">
                    	<property name="privateKey" expression="$ctx:privateKey"/>
                    </class>
```
I get "ERROR - PropertyHelper Error invoking setter method named" in wso2carbo.log
