### ISSUE TITLE
EI Analytics 6.1.0 error on startup when installed as Windows service

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#531]
I have installed EI Analytics as service on Windows Server 2016, 8 Gb ram.
When the service start thorw the follow error:
`ERROR {org.wso2.carbon.event.application.deployer.EventProcessingAppDeployer} -  Deployment is failed due to No extension exist for StreamFunctionExtension{namespace='esbAnalytics'}  in execution plan "EsbAnalytics-ExecutionPlan-statistic"`
After the startup, in the Analytics dashboards  i see "No dashboards found" message.

Logfile:
[log_wso2-Analytics610-service.txt](https://github.com/wso2/product-ei/files/918931/log_wso2-Analytics610-service.txt)

wrapper.conf:

[wrapper.conf.txt](https://github.com/wso2/product-ei/files/919016/wrapper.conf.txt)

**Comment by Thierry32** [comment]
I think you should add the components/plugins folder to your classpath in the wrapper.conf. 
wrapper.java.classpath.3 = ${carbon_home}\\..\\components\\plugins
Maybe also this one:
wrapper.java.classpath.4 = ${carbon_home}\\..\\lib\\commons-lang*.jar
In this case (wso2 analytics), the ${carbon_home} folder is the analytics folder (//wso2ei-6.1.0/wso2/analytics).

**Comment by marcses** [comment]
Thanks Thierry32. 
Now it seems to work. 
Only problem is the following exception:`ERROR {org.apache.hadoop.util.Shell} -  Failed to locate the winutils binary in the hadoop binary path {org.apache.hadoop.util.Shell}
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.`

[log_wsoEI610-Analytics-as-service-win.txt](https://github.com/wso2/product-ei/files/957950/log_wsoEI610-Analytics-as-service-win.txt)

**Comment by slawomirkisiel** [comment]
Similar issue is in Identity Server (v5.7.0) running as a service. We got
`java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils`

After adding 
`wrapper.java.classpath.3 = ${carbon_home}\..\lib\commons-lang*.jar`
everything works well.

This line should be added into installation package (IS-5.7.0 doesn't have one).
