### ISSUE TITLE
No proper way to provide additional fields to a output schema that are not in the input schema when doing transformations with the data mapper

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-ei#5317]
**Description:**
Currently, when using the data mapper to do transformations if you want to have additional fields/properties in the output schema which are not in the input schema then there is no proper way to map it to the output. The only way to do it is by creating constants for those fields and then map them back to the output schema. This doesn't seem feasible when you have a large no. of fields that are in the output schema and not in the input schema.

An example is as follows:
![Screenshot from 2020-11-25 15-20-23](https://user-images.githubusercontent.com/13446645/100211257-ebbf0700-2f31-11eb-8cdc-c31facf86af5.png)

**Suggested Labels:**
Improvement

**Affected Product Version:**
WSO2 Micro Integrator 1.2.0

**Comment by nadeesha5814** [comment]
Alternative option for this is to allow bulk mapping (mapping more than 1 element at a time), currently Bulk mapping is not supported.
