### ISSUE TITLE
postman enable to verify the first certificate

### ISSUE THREAD

**Issue by fugitivaLaMadrid** [wso2/product-ei#5329]
**Description:**

Hi, Im using Integration studio 7.0 and i download the wso2ei 6.6.0 zip file IM trying to run in postman my api from the tutorial:
https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/storing-and-forwarding-messages/

Running the server from integratio studio work fine under: http://localhost:8290/healthcare/categories/surgery/reserve

But when I run from <installation_home>bin/wso2ei-6.6.0\bin\integration.bat
and add this at postman:
https://localhost:9443/healthcare/ categories/surgery/reserve

![image](https://user-images.githubusercontent.com/14073940/102397012-9ed4ca80-3fdd-11eb-8442-21b7506708d9.png)

![image](https://user-images.githubusercontent.com/14073940/102397122-c0ce4d00-3fdd-11eb-9b74-0acf611f7999.png)
 and in soapUi
i got 403 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
This https://localhost:9443/healthcare/categories/surgery/reserve is tomcat https url, hence to invoke it via postman you can do either one of the following
- you need to import ei certs to postman
- disable certificate validation in postman

Alternatively, you can try invoking it via http ( 9763 ) http://localhost:9763/healthcare/categories/surgery/reserve

**Comment by fugitivaLaMadrid** [comment]
Thank you for your reply, about:
1. "you need to import ei certs to postman" --> do you mean the public certificate it? if yes I did and now im getting 403 error
![image](https://user-images.githubusercontent.com/14073940/102499096-0f7df480-407b-11eb-9678-e1ecae32b4fc.png)

![image](https://user-images.githubusercontent.com/14073940/102498789-b2823e80-407a-11eb-8596-364fe5ea56e6.png)
![image](https://user-images.githubusercontent.com/14073940/102498852-c463e180-407a-11eb-965a-c364a22a2b55.png)
![image](https://user-images.githubusercontent.com/14073940/102498938-e2c9dd00-407a-11eb-9679-bfc9199ae78e.png)
![image](https://user-images.githubusercontent.com/14073940/102499007-f70dda00-407a-11eb-8d82-738dc65958b5.png)

**Comment by fugitivaLaMadrid** [comment]
2. " disable certificate validation in postman" ---> do you mean the ssl?? I did that
3. 
![image](https://user-images.githubusercontent.com/14073940/102499230-376d5800-407b-11eb-963f-228f0d1f8dd0.png)

**Comment by fugitivaLaMadrid** [comment]
About:
"Alternatively, you can try invoking it via http ( 9763 ) http://localhost:9763/healthcare/categories/surgery/reserve" --> I also tried and getting same error "Unable"



![image](https://user-images.githubusercontent.com/14073940/102499342-566bea00-407b-11eb-91d7-68ea7c07c9e1.png)
![image](https://user-images.githubusercontent.com/14073940/102499583-a8ad0b00-407b-11eb-82f9-858843ef2f8c.png)
thanks in advance

**Comment by fugitivaLaMadrid** [comment]
Last thing not sure its relevant to this..when i tried to click on the links nothing happens
![image](https://user-images.githubusercontent.com/14073940/102499730-d2fec880-407b-11eb-9f3d-4515f656b11b.png)

**Comment by Nirothipan** [comment]
@fugitivaLaMadrid 
I was saying the above, thinking it as a proxy service. Since this is an API,  if you need https can you try access it via port 8243 with any of the above option https://localhost:8243/healthcare/categories/surgery/reserve

**Comment by fugitivaLaMadrid** [comment]
Thank you! its working! (Still the warning but i can see my response)
![image](https://user-images.githubusercontent.com/14073940/102529397-1bc87880-40a0-11eb-9bb0-3c3d21489b0d.png)
