### ISSUE TITLE
Business Process Server profile version shows as 3.6.0 in EI 6.1.0

### ISSUE THREAD

**Issue by hasithaa** [wso2/product-ei#533]
See bellow Image. Showing 3.6.0 is wrong IMO, because BPS 3.6.0 is released, as a sperate product. 

![screenshot from 2017-04-17 10-21-57](https://cloud.githubusercontent.com/assets/1356214/25080018/0a250bbe-235f-11e7-960d-65cd83bdbfb5.png)

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/product-ei/pull/933.
