### ISSUE TITLE
Provide WSO2 vault-lookup functionality for Data sources

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/product-ei#5335]
**Description:**
When creating a data source or data service using the EI tooling with secrets enabled, it is required to manually run the cipher tool and get a plain password encrypted and add the encrypted value into the cipher-text.properties file with an alias. This alias can be added to the data source as follows.

```
<property xmlns:svns="http://org.wso2.securevault/configuration" name="password" svns:secretAlias="mongodatasource.database.password" />
```
However, when changing the cipher-text.properties files to manually encrypt the password, it is required to restart the server for each data source with encrypted passwords.

We can avoid this burden if we have {wso2:vault-lookup('alias')} support enabled for datasources and dataservices. 

**Affected Product Version:**
EI-6.x

**Comment by Shakila** [comment]
Doc Issue: https://github.com/wso2/docs-ei/issues/2689
