### ISSUE TITLE
EI660. Critical Error when redeploy API with CustomMediator (Java Class)

### ISSUE THREAD

**Issue by LLC-BigInt** [wso2/product-ei#5338]
**Description:**
Can't deploy API with Java Class (mediator)
ERROR {org.apache.synapse.config.SynapseConfiguration} - Duplicate resource definition by the name

**Suggested Labels:**
Error. EI660

**Affected Product Version:**
OS: Centos 8
DB: PostgreSql
EI: 6.6.0

**Steps to reproduce:**
1. Export *.car with Java Abstract Mediator from Developer Studio (include *.jar)
2. Deploy to server. Success
3. Deploy to server. Duplicate resource definition by the name
4. Remove *.car from server. API allready exists (not undeploy)

Please, Help!!!

**Comment by paindg93** [comment]
Quick workaround:
Create separate sequence in project, put class mediator there, and call created sequence from API.

**Comment by paindg93** [comment]
Problem lays in handling class mediator in API Mediator Factory

Quick workaround:
Shutdown integrator, clean tmp dirs.

Create separate sequence in project, put calling class mediator there and call created sequence from API mediator.
Create and deploy new car, problem should be gone.

Error exists also in version 6.5.0

Possible duplicate: #5336

**Comment by LLC-BigInt** [comment]
Hi
We are check all our *.car (included JAR)

Thank you very much @paindg93 !
