### ISSUE TITLE
EI Performance Issues in PayloadFactory

### ISSUE THREAD

**Issue by tharakamd** [wso2/product-ei#5345]
**Description:**
The PayloadFactory mediator is lagging down in performance compared to ESB 5.0.0. After analyzing the JFR reports, the performance issue is in the synchronized block in the getXmlVersion method of the PayloadFactory class.

**Affected Product Version:**
EI - 6.5.0

**Steps to reproduce:**
- Create a meditation flow with multiple PayloadFactory mediators
- Perform a load test with multiple threads

**Comment by TomasTokaMrazek** [comment]
Could this help?

https://github.com/wso2/product-ei/issues/5046#issuecomment-755258951
