### ISSUE TITLE
[Docs][EI 6.0.0] Update samples with correct file paths.

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#535]
Please add a note regarding path changes in samples. Update EI 600 [1] docs as in EI 610 [2]

[1] https://docs.wso2.com/display/EI600/Sample+268%3A+Proxy+Services+with+the+Local+Transport
[2] https://docs.wso2.com/display/EI610/Sample+268%3A+Proxy+Services+with+the+Local+Transport

**Comment by praneesha** [comment]
Added the following note in all sub pages of the section [1] in EI 6.0.0 docs also.

"Note that WSO2 EI is shipped with the following changes to what is mentioned in this documentation:
<PRODUCT_HOME>/repository/samples/ directory that includes all Integration profile samples is changed to <EI_HOME>/samples/service-bus/.
<PRODUCT_HOME>/repository/samples/resources/ directory that includes all artifacts related to the Integration profile samples is changed to <EI_HOME>/samples/service-bus/resources/."

[1] https://docs.wso2.com/display/EI600/Integrator+Samples
