### ISSUE TITLE
Unable to change the encrypted password using -Dchange 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#537]
**Environment**
OS - Ubuntu 15.10
JDK - 1.8
EI 6.1.0

**Steps**
1) Run "./ciphertool.sh -Dconfigure" to encrypt the passwords
2) Then run "./ciphertool.sh -Dchange" to change the password

**Observation**
After providing the number not prompting to provide a new password.
![dchange](https://cloud.githubusercontent.com/assets/14962228/25178290/e133100a-2522-11e7-8927-4b6c25be4921.png)

Note - verified this issue with ESB500 and ESB490 same issue observed.

**Comment by abeykoon** [comment]
This is not reproducible in 6.5.0 M4 pack. Hence closing.
