### ISSUE TITLE
WSO2 EI does not validate the JMS connection when the connection is closed by the broker

### ISSUE THREAD

**Issue by shefandarren** [wso2/product-ei#5388]
**Description:**
In a JMS publisher scenario, if the broker closes the connection due to a problem in the broker side (network issue, broker is down, etc), the connection establishment fails. This is due to a limitation in the JMS API to check the connection validity. 

Here an error is thrown and the message is lost unless it is handled in the fault sequence using one of the following approaches. 

1) Propagate the error to the client side and make the client retry the failed message
2) Implement a mediation logic to resend the message to the relevant JMS destination

**Suggested Labels:** Improvement

**Affected Product Version:** WSO2 EI 6.6.0

**Steps to reproduce:**
1) Deploy a JMS publisher in WSO2 EI
2) Simulate a load test using Jmeter
3) Disrupt the connection to the broker

**Comment by v-scottbechtel** [comment]
+1
