### ISSUE TITLE
File Inbound fails when moving folders with meta characters in the URI

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/product-ei#5453]
**Description:**
When one of the following characters ` [ ] { } ( ) \ ^ $ | ? * +` are present in the URI, move operations related to sub directories fails. Need to escape these characters.

**Affected Product Version:**
EI 6.6.0

**Comment by LLC-BigInt** [comment]
Hi
That is not working?

https://dzone.com/articles/handling-special-characters-in-urls-with-wso2-esb
<resource faultSequence="fault" methods="GET" protocol="http" uri-template="/sendsms*">
<resource faultSequence="fault" methods="GET" uri-template="/send?phone={+phone}&text={message}">
/queries?* — Allows any query parameters
/queries — Allows without query parameters
