### ISSUE TITLE
JSPException when adding users EI610 - as windows service

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#548]
For EI 6.1.0 installed as windows service (work id EI in started from script)
Get the following error when trying to add users from the wizard: JSPException while including path '/user/add-step2.jsp'
[log_wso2_add_user_win-service.txt](https://github.com/wso2/product-ei/files/961814/log_wso2_add_user_win-service.txt)
![tomcat_work_dir](https://cloud.githubusercontent.com/assets/26251486/25487448/8cbdef84-2b64-11e7-91a2-d85d56536df1.PNG)

Steps to reproduce.
1. Install EI as windows service.
2. Go to user creation wizard.
3. Give username and password and click or next, then you get the below exception in back end with an empty page in the console.

**Workaround**
Add manually the files [add_002dstep2_jsp.java, add_002dstep2_jsp.class] from another working instance in wso2ei-6.1.0\wso2\lib\tomcat\work\Catalina\localhost\_\proxytemp\hc_********\org\apache\jsp\user resolve the problem.

**Comment by Miggleness** [comment]
The fix for this is to update the Integration profile's wrapper.conf file and and set STRICT_QUOTE_ESCAPING=false and encoding=UTF8

Reference: https://wso2.org/jira/browse/ML-130
[wrapper.conf.txt](https://github.com/wso2/product-ei/files/1879355/wrapper.conf.txt)
