### ISSUE TITLE
Content type is missing when invoking a tenant data-service via EI servlet transport

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/product-ei#5481]
**Description:**
When invoking a tenant data-service via EI servlet transport, the content type is missing in the response payload. 

**Affected Product Version:**
EI 6.6.0

**Steps to reproduce:**

1. Create a tenant
2. login with tenat
3. Create a dataservice
4. Set "Accept" header to "application/json". Invoke the data-service via servlet transport. You will see the content-type is missing in the response header.

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/3034
