### ISSUE TITLE
[Doc][Broker Profile]Add note on tenant specific durable subscription

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#551]
When we are going to subscribe to a topic in tenants, we have to give subscription name with tenant domain.

Ex:
String subscriptionName ="dilshani.wso2.com/subscription1";

Otherwise, it will give an error. Please update doc [1]

[1] https://docs.wso2.com/display/EI610/Managing+Subscriptions

**Comment by praneesha** [comment]
Added the following note in docs of all WSO2 EI versions, and in WSO2 MB 3.1.0 & above.

"When you subscribe to a topic in tenants, give the subscription name with the tenant domain. For example, if the subscription name is subscription1 and the tenant domain is bob.wso2.com, give the the subscription name as follows: String subscriptionName ="bob.wso2.com/subscription1";"

[1] https://docs.wso2.com/display/EI620/Managing+Subscriptions
