### ISSUE TITLE
SSL Support for MongoDB Dataservice

### ISSUE THREAD

**Issue by akAsara** [wso2/product-ei#5526]
**Description:**
There is no option to enable SSL support when configuring a MongoDB data service. Hence connection is not Establishing due to unavailability of setting below two Properties in Data Source configurations.

`ssl=true&authSource=admin `

**Affected Product Version:**
WSO2EI-6.5

**OS, DB, other environment details and versions:**    
Mongo DB 4.4

**Comment by LLC-BigInt** [comment]
Hi
Can you sow DataService and what driver are you use?
