### ISSUE TITLE
ORA-01400: cannot insert NULL in EI Analytics 6.5.0 for inbound endpoints

### ISSUE THREAD

**Issue by ug205** [wso2/product-ei#5527]
**Description:**
ORA-01400: cannot insert NULL exceptions in EI Analytics 6.5.0 for inbound endpoints for the columns ENTRYPOINT and COMPONENTNAME.

**Suggested Labels:**
ei-analytics
ei-analytics-6.5.0

**Affected Product Version:**
ei-analytics-6.5.0

**Steps to reproduce:**
Set up EI Analytics, analytics database pointed to Oracle database.
Create a DB Event Inbound Endpoint.
Update the respective database table.
Observe the said errors for MEDIATORSTATAGG and ESBSTATAGG tables.

**Comment by dilini-muthumala** [comment]
Fixed with https://github.com/wso2-extensions/esb-inbound-dbevent/pull/26 hence closing the issue.
