### ISSUE TITLE
Override the caching time of oauth mediator

### ISSUE THREAD

**Issue by jithma95** [wso2/product-ei#5531]
**Description:**

 Token expires in 10 mins (599 s) but the OAuth mediator caches the token for 50 minutes (static constant in code). Is it possible to override the cache expiry time via a configuration or a property ?

When debugging the code, we came across the following constant where the token cache is set for 50mins [1]:

   
// Timeout in minutes to invalidate the tokens in the cache public static final int TOKEN_CACHE_TIMEOUT = 50;

The usage of the above constant is as follows [2]:
  
private final Cache<String, String> tokenMap = CacheBuilder.newBuilder().expireAfterWrite(OAuthConstants.TOKEN_CACHE_TIMEOUT, TimeUnit.MINUTES).build();
Hence, requesting a mechanism to configure this value.

[1] https://github.com/wso2/wso2-synapse/blob/5debdfd925874ad568f0ecec7dc778996ddebae2/modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java#L73
[2] https://github.com/wso2/wso2-synapse/blob/5debdfd925874ad568f0ecec7dc778996ddebae2/modules/core/src/main/java/org/apache/synapse/endpoints/oauth/TokenCache.java#L36

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Enterprise Integrator-6.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
https://github.com/wso2/product-ei/issues/5530 - duplicate issue
