### ISSUE TITLE
how to make wso2ei 6.6.0 to use http2 protocl?

### ISSUE THREAD

**Issue by gennosuke** [wso2/product-ei#5547]
I'm using wso2ei 6.6.0 and my manager wants to set all requests to use http2 protocol, but I can't find a way how to make wso2 use the http2. I'm aware that I can use a web server or load balancer such as haproxy between them but I need to make passthrough to listen on http2 protocol.also  I need to send all requests to the backend on http2 protocol any idea how I can handle this situation?!

**Comment by gennosuke** [comment]
> I think this is question actual for APIM too

maybe but i need this on wso2ei. do you have any idea how can i handle this?!

**Comment by LLC-BigInt** [comment]
Can you add a test case or something else? (where can be view message or error)

**Comment by gennosuke** [comment]
actually i have no idea how to put this through , i just tried to make tomcat to listen on http2 and it wotked. in $HOME/repository/conf/tomcat/catalina-server.xml ,  (<UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />) but when i set a port listener in $HOME/repository/conf/axis2/axis2.xml in      section ,i can't set any http2 protocol or at least i can't find a way .
when i curl using (curl --http2 -I -v mydomain.com) it won't accept http2.
could i make my point or should i explain it in another way?
