### ISSUE TITLE
Issue when restarting the message broker

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/product-ei#5569]
**Description:**
When the message broker is down, we send a request, and the message can’t be handled by the original message store. The message is stored in the failure message store table. Then we checked the EI console and identified that the Failover Message Forwarding Processor was deactivated.

After that, we start the message broker and try to activate the message broker. In that case, we received a warning message like below.

`WARN {org.apache.synapse.message.store.impl.jms.JmsProducer} - [wms-inventory-adjustments-v1-message-store-P-2]. Ignored MessageID : urn:uuid:52CE9E9E7235D98F71279144645406271-35766514​`

We tried multiple times to activate the failover message forwarding processor, and it keeps deactivating. Then we send a new request to and activate the message forwarding processor. Then the message forwarding processor is activated and both requests are stored in the original message store. 

**Affected Product Version:**
Enterprise Integrator 6.6.0

**Steps to reproduce:**

- First create an Original Store (active-MQ) and configure JDBC messag store as FailOverStore 
- Deploy the Capp and test the scenario by publishing a message to Original store
- The shutdown the ActiveMQ broker and send few messages to OriginalStore
- Then the messages will be directed to FailoverStore
- When checking the EI management console the failover message forwarding processor is deactivated.
- Again start the activeMq and try to activate the failover message forwarding processor.

**Comment by DaniduWijendra** [comment]
Hi team,
Do you have any update on this? The best case is passed 4 days ago.
Thanks,
Danidu

**Comment by hisanhunais** [comment]
Issue is fixed in Public Repo with https://github.com/wso2/wso2-synapse/pull/1577
