### ISSUE TITLE
No artifacts found to be deployed in this server. Ignoring Carbon Application. APIM4

### ISSUE THREAD

**Issue by ali-ghazi78** [wso2/product-ei#5578]
Hi,

I want to deploy my car file in wso2 carbon but I get this error. 
```No artifacts found to be deployed in this server. Ignoring Carbon Application```

**Comment by LLC-BigInt** [comment]
maybe you forgot to activate the artifacts so that they are included in the car file? Or check rights to folder, files

**Comment by ali-ghazi78** [comment]
> maybe you forgot to activate the artifacts so that they are included in the car file? Or check rights to folder, files

No, I checked all the checked boxes.

**Comment by paindg93** [comment]
@ali-ghazi78 give some more details.

Plese include content listing of the generated car,  some pieces of the pom.xml and artifact.xml files, base on which your artifacts should be generated into car.

Quoted error from ESB is not very helpful to understand what is going on ; )

**Comment by ali-ghazi78** [comment]
@paindg93 I confused EI with api manager 4 . may I know if it is possible to upload a car file directly inside api manager or not?

**Comment by paindg93** [comment]
Did you try to change the server role of each artifact in car to be API Manager?

https://docs.wso2.com/m/mobile.action#page/34611390

**Comment by dulanjalidilmi** [comment]
Hi,

Thank you for reporting this. In order to investigate the issue more, please provide us with following information.

1. Product and Product Version
2. The use case and steps to reproduce
3. Full stack-trace 

Best Regards
Dilmi
