### ISSUE TITLE
JSON parse fails when payload contains whitespace

### ISSUE THREAD

**Issue by NivethGoutham** [wso2/product-ei#5582]
**Problem:**
When JSON payload contains whitespaces as below, it throws a class cast exception since whitespaces are not allowed in primitives [1].

`"spo_emad_spo_srs" : "abc.dey@ab.bc.uk; def.fig@ab.bc.uk"`

Error:

> ERROR {org.apache.synapse.config.xml.AnonymousListMediator} - class org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to class org.apache.axiom.om.OMNode (org.apache.synapse.core.axis2.Axis2MessageContext is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @257f53cd; org.apache.axiom.om.OMNode is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @75c5d780) java.lang.ClassCastException: class org.apache.synapse.core.axis2.Axis2MessageContext cannot be cast to class org.apache.axiom.om.OMNode (org.apache.synapse.core.axis2.Axis2MessageContext is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @257f53cd; org.apache.axiom.om.OMNode is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @75c5d780)
> at org.apache.axiom.om.xpath.DocumentNavigator.getDocumentNode(DocumentNavigator.java:602)
> at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:102)
> at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
> at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
> at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
> at org.jaxen.BaseXPath.selectSingleNode(BaseXPath.java:236)
> at org.apache.synapse.mediators.elementary.Target.insert(Target.java:120)
> at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:224)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
> at org.apache.synapse.config.xml.AnonymousListMediator.mediate(AnonymousListMediator.java:37)
> at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:205)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:108)
> at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
> at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
> at org.apache.synapse.rest.Resource.process(Resource.java:331)
> at org.apache.synapse.rest.API.process(API.java:442)
> at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:135)
> at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:113)
> at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
> at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:328)
> at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
> at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:376)
> at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:435)
> at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:183)
> at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:829)

**Solution:**
Wrap the string in quotes. 

`"\"abc.dey@ab.bc.uk; def.fig@ab.bc.uk\"",`

[1] [https://www.rfc-editor.org/rfc/rfc7159.html]

**Comment by Tharsanan1** [comment]
Could not reproduce it on latest versions
