### ISSUE TITLE
integration with elastic apm

### ISSUE THREAD

**Issue by ismailazerty** [wso2/product-ei#5586]
Hello,
   We want to integrate wso2-ei 6.6.0 with elastic apm.
   to view transactions and spans.
   and to view errors.

   Is there any documentation for that.

thank you

**Comment by LLC-BigInt** [comment]
Are you sure that github is for such tasks? (documentation is usually enough to solve such tasks)
we could consider options for helping office@bigint.pro

**Comment by ismailazerty** [comment]
I searched the documentation for it but no reference.
https://docs.wso2.com/display/ESB490/Getting+Started

could you please add this as a new feature ?
