### ISSUE TITLE
Jaggery apps deployment in WSO2 EI

### ISSUE THREAD

**Issue by robeth** [wso2/product-ei#559]
I developed jaggery apps in WSO2 developer studio & successfully create zip which ready to be deployed.

However, I couldn't find jaggery menu in carbon dashboard (WSO2 EI v6.0.0). 

![ei dont have jaggery menu](https://cloud.githubusercontent.com/assets/1451171/25883782/83a27dbc-3577-11e7-9125-bc87d1270d52.PNG)

Unlike in WSO2 application server [docs](https://docs.wso2.com/display/AS521/Jaggery), there is a dedicated menu to upload jaggery apps. I also tried to copy `zip` file into `<EI_HOME>/repository/deployment/server/jaggeryapps` but no success.

Is jaggery apps deployment supported in WSO2 EI 6.0.0?

Thanks :)

**Comment by himasha** [comment]
Jaggery app deployment is not supported in EI.
