### ISSUE TITLE
Forbidden error when browsing the last messages in a queue

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#56]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
DB - mysql 5.6.31
EI M1 snapshot pack

**Steps**
1. Start the Broker
2. Create a queue and publish around 50 messages to the queue
3. Browse the queue using the Management Console and click the "more" option to view the message

**Observations**
1. Directs to "Error 403 - Forbidden" page
2. This is the same issue that is reported in https://wso2.org/jira/browse/MB-1729

**Comment by himasha** [comment]
Fixed issue with commit https://github.com/wso2/carbon-business-messaging/commit/50821685ec80b68f9cba4ca8e2940e8180b92f20.

**Comment by sashikamw** [comment]
Verified the fix in 27/01/2017 Jenkins Build.
