### ISSUE TITLE
WSO2 EI 6.1.0 start integrator.sh with worker profile

### ISSUE THREAD

**Issue by klev2004** [wso2/product-ei#561]
Hi,
I found the next issue:
1. Unpack clear WSO2 EI 6.1.0 archive;
2. Change bin/integrator.sh: -DworkerNode set to true;
3. Change permissions to the WSO2 EI 6.1.0 home folder and all of child objects to 777;
4. Change owner of the WSO2 EI 6.1.0 home folder and all of child objects to a needed user;
3. Start WSO2 EI 6.1.0 instance.
You will get the error message: FATAL {org.wso2.carbon.server.Main} -  OSGi runtime worker profile not found {org.wso2.carbon.server.Main}

As solution:
1. You should start WSO2 EI 6.1.0 instance as not workerNode profile: -DworkerNode set to false;
2. Then the name of the folder wso2/components/default you should change to wso2/components/worker.

**Comment by nandika** [comment]
Hi Klev,

We have removed the concept of worker manager profile from EI. Hence we no longer use -DworkerNode flag. 

Regards
Nandika

**Comment by miltoncabral** [comment]
Hello Nandika,
Please clarify me how I can solve this situation. I'm trying to configure the worker/manager nodes (WSo2 EI 6.4.0) but seems like all nodes are standalone. I've seen your answer but it's not clear for me... what's the approach to making this configuration in this product version?
Thanks in advance. 
Milton Cabral
