### ISSUE TITLE
[Integrator Profile 6.1.1]The bind-address feature was not implemented for Pass-through transport - wrong solution in ESBJAVA-3117

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#564]
The bind-address feature was not implemented for Pass-through transport - wrong solution in ESBJAVA-3117

Fix ix in https://wso2.org/jira/browse/ESBJAVA-4973

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/741
