### ISSUE TITLE
Fix DB Mediator deployment issues related to tenant reloading

### ISSUE THREAD

**Issue by isudana** [wso2/product-ei#569]
ServiceBusInitializer is having a dependency to DataSourceAxis2ConfigurationContextObserver during runtime and TenantAxisUtils is not aware of such dependencies (or any such inter dependencies between the observers) as it just invokes each and every observer to intialize when tenant gets loaded. 

When tenant is getting loaded, if DataSourceAxis2ConfigurationContextObserver is loaded before ServiceBusInitializer, a artifact which has a DB mediator (DBReport or DBLookup) get deployed without a problem. But if ServiceBusInitializer is loaded before the 
 DataSourceAxis2ConfigurationContextObserver, deployment of the artfact fails because it cannot find the Datasource.

**Comment by prabushi** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/743
