### ISSUE TITLE
axis2Server.bat file does not start

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#570]
It gives the following error

C:\ESB\wso2ei-6.1.0\samples\axis2Server>axis2server.bat
"Starting Sample Axis2 Server ..."
Using AXIS2_HOME: C:\ESB\WSO2EI~1.0\samples\AXIS2S~1\
Using JAVA_HOME: C:\Program Files\Java\jdk1.8.0_45
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
Server could not start due to class loading issue java.lang.NoSuchMethodException: samples.util.SampleAxis2Server.startServer([Ljava.lang.String)

**Comment by madhawa-gunasekara** [comment]
Fixed with https://github.com/wso2/product-ei/pull/584
