### ISSUE TITLE
When endpoint timeout happens fault sequence is executed as well as outsequence

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#574]
Affected version: ESB 4.9.0
Component: Synapse-core

Steps to reproduce: 

1. setup a mock service (which accept GET) with onrequest delay 10 s
2. Create a proxy to forward message to BE (GET request)
3. Using Jmeter perform a load test to hit the proxy thread count=50 loopcount=3 

If you log the correlation id along with service logs at fault sequence and out sequence, it is able to see same message has hit to fault sequence due to timeout and then it has reached out sequence too. This is a bug.

**Comment by abeykoon** [comment]
This happen very rarely during a load test.

**Comment by isudana** [comment]
PR to fix this https://github.com/wso2/wso2-synapse/pull/742
