### ISSUE TITLE
[EI6.1.1] API being removed only with server restart

### ISSUE THREAD

**Issue by gabrielpolo** [wso2/product-ei#575]
I have a .CAR package that contains an API, and the deploy occurs with success.

When I remove this .CAR package, the API continues there. If I restart the server, the API is removed.

I'm using EI6.1.1.

**Comment by a5anka** [comment]
@gabrielpolo I tested with the attached CAR file and could not observe an issue. Normally it takes few seconds to do the undeployment. Can that be the issue?
 
[TestApiDeploymentCompositeApplication_1.0.0.zip](https://github.com/wso2/product-ei/files/1259148/TestApiDeploymentCompositeApplication_1.0.0.zip)
Note: Please extract before use.

Please reopen with the CAR file if you observe the issue again.

**Comment by gabrielpolo** [comment]
@a5anka I tried with your package and it works, but with with my package the problem happens.

[MyApiConfigApplication_1.0.0.car.zip](https://github.com/wso2/product-ei/files/1319223/MyApiConfigApplication_1.0.0.car.zip)
