### ISSUE TITLE
[Docs][EI 6.1.1] Update syntax for Iterate Mediator

### ISSUE THREAD

**Issue by rodrigopk** [wso2/product-ei#586]
In EI 6.1.1 documentation page for [Iterate Mediator](https://docs.wso2.com/display/EI611/Iterate+Mediator), there is no reference for the sequential mediation parameter in the syntax description. It should be updated to include the sequential parameter as in the example below:

		<iterate [continueParent=(true | false)] [sequential=(true | false)] [preservePayload=(true | false)] (attachPath="xpath")? expression="xpath">
		   <target [to="uri"] [soapAction="qname"] [sequence="sequence_ref"] [endpoint="endpoint_ref"]>
		     <sequence>
		       (mediator)+
		     </sequence>?
		     <endpoint>
		       endpoint
		     </endpoint>?
		   </target>+
		</iterate>

**Comment by praneesha** [comment]
Updated in all versions of WSO2 EI and ESB docs.
