### ISSUE TITLE
Cannot invoke proxy services when a Web app is deployed with /services context

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#60]
**Steps**

1. Create a webapp with /service context and deploy it.
2. Try to invoke a proxy service.

*Issue* : Unable to invoke Proxy services.

**Comment by madhawa-gunasekara** [comment]
This is a known issue in AS as well. In AS we can't invoke axis2 services when we deploy a webapp in services context. 

Need to add into documentations. Thanks for reporting

**Comment by nilminiwso2** [comment]
This issue doesn't exist in EI 610. 
EI 600: We have not documented AS functionality as it is not a main use case. Therefore, closing this.
