### ISSUE TITLE
[Improvement]Display broker, bps and analytics URL when using the start-all.sh script

### ISSUE THREAD

**Issue by gilliandass** [wso2/product-ei#61]
When running the start-all.sh script only the URL for the Integrator management console is displayed. Good if URLs for the other runtimes can be displayed in the terminal.

**Comment by mpmunasinghe** [comment]
With the fix to issue https://github.com/wso2/product-ei/issues/29 we have improved the console logs to print in foreground https://github.com/wso2/product-ei/pull/46/commits/d1b50dcfddb870e6ffdc6d6c6e5a62d321427c1b
