### ISSUE TITLE
EI611 JVM Performance Tuning refers to APIM

### ISSUE THREAD

**Issue by mathieubouchard** [wso2/product-ei#611]
At the end of the following page :
https://docs.wso2.com/display/EI611/Java+Virtual+Machine+Performance+Tuning

It is written to update the file <APIM_HOME>/bin/wso2server.sh.

It should refer to <EI_HOME>/bin/integrator.sh or just say to add the -DentityExpansionLimit=10000 value to the command line instead.

**Comment by praneesha** [comment]
Fixed this in both WSO2 EI & ESB docs.
