### ISSUE TITLE
[Broker] Available queues do not listed property to reroute messages in the DLC

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#62]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89, Firefix 47.0
DB - mysql 5.6.31
EI M1 snapshot pack

**Steps**
1. Prerequisite - Messages should exists in the DLC queue
2. Select a message and click the "Reroute" option

**Observations**
1. Available queues do not listed correctly 

![reroute](https://cloud.githubusercontent.com/assets/14962228/22325531/81502f7c-e3d4-11e6-86aa-91a420de8138.png)

**Comment by sashikamw** [comment]
The same issue observed in EI 6.0.0 Alpha pack

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/carbon-business-messaging/commit/80932a844605e0c4b208f6a1be287e51b51cca47

**Comment by sashikamw** [comment]
Verified the fix in 17/02/2017 wso2ei-6.0.0-SNAPSHOT pack
