### ISSUE TITLE
[Doc] Add BPMN Rest API doc for EI

### ISSUE THREAD

**Issue by milindaperera** [wso2/product-ei#629]
Seems we haven't added BPMN REST API docs to EI docs. Shall we add BPMN Rest API Doc from [1] to EI 6.X.X

[1] https://docs.wso2.com/display/BPS360/BPMN+REST+API

**Comment by praneesha** [comment]
Added the BPMN REST API Guide in all versions of WSO2 Ei docs.

See [1] for an example.

[1] https://docs.wso2.com/display/EI620/BPMN+REST+API
