### ISSUE TITLE
[Crtical] Webapps are not functioning properly

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#65]
Session aware webapps are not functioning properly. When there are internal redirects in webapps it seems to not function properly. Please refer the attached webapp.

[bodgeit.zip](https://github.com/wso2/product-ei/files/732144/bodgeit.zip)

**Comment by madhawa-gunasekara** [comment]
@yasassri As far I remember this issue is fixed right.

**Comment by yasassri** [comment]
Yes, we can close this now..
