### ISSUE TITLE
[DataMapper] JS script engines are not getting released when exceptions thrown at expression evaluation 

### ISSUE THREAD

**Issue by erandacr** [wso2/product-ei#650]
Default script engine pool size is 20.
If JSON evaluation throws an exception from script engine, it won't get released. And after such 20 requests, DataMapper excursions will fail and this will lead to all Passthrough thread getting waited at the 'take' of the script engine pool.

To reproduce, create a JSON to JSON mapping and send an invalid JSON message. Eg: {"aa":a}

**Comment by sohaniwso2** [comment]
Fixed https://github.com/wso2/carbon-mediation/commit/f40799ddd96b4306817dbdf8dd78dfd1c814b969
