### ISSUE TITLE
am1985

### ISSUE THREAD

**Issue by am1985** [wso2/product-ei#653]
Issue with axis2 JMSUtil where a JMS Text Message with null body causes connection to close and restart because the getMessageSize method fails..

Suggested fix:
    public static long getMessageSize(Message message) throws JMSException {
        if (message instanceof BytesMessage) {
            return JMSUtils.getBodyLength((BytesMessage) message);
        } else if (message instanceof TextMessage) {
            // TODO: Converting the whole message to a byte array is too much overhead just to determine the message size.
            //       Anyway, the result is not accurate since we don't know what encoding the JMS provider uses.
            if(((TextMessage) message).getText() == null)
				return 0;
            else
            	return ((TextMessage) message).getText().getBytes().length;
        } else if (message instanceof MapMessage) {
            return JMSUtils.getBodyLength((MapMessage) message);
        } else {
            log.warn("Can't determine size of JMS message; unsupported message type : "
                    + message.getClass().getName());
            return 0;
        }
    }

**Comment by vinok88** [comment]
Thanks for reporting the issue. The fix is merged in PR https://github.com/wso2/wso2-axis2-transports/pull/124.
