### ISSUE TITLE
[Doc] Repeated line in description for aggregate mediator for EI 611

### ISSUE THREAD

**Issue by rodrigopk** [wso2/product-ei#657]
In the [Aggregate Mediator Doc](https://docs.wso2.com/display/EI611/Aggregate+Mediator) the following quote

> Note that the responses are not necessarily aggregated in the same order that the requests were sent, even if you set the sequential attribute to true on the Iterate mediator.

Is repeated twice in the first paragraph. The repeated statement should be removed.

**Comment by praneesha** [comment]
Checked and corrected in all versions of WSO2 EI and ESB docs.
