### ISSUE TITLE
[EI 6.1.0][Analytics]Generate a Gadget Error

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#678]
I'm try to generate new gadget in Analytics dashboard but something goes wrong.
1) In the Anaytics Dashboard, click the menu icon and then click Gadgets to open the Gadgets page
2) Click GENERATE GADGET to open the Generate a Gadget wizard
3) Select Provider : Relational Database Source
4) Insert Database URL, Table name, ecc...
5) Test connection: OK
6) Show Data: OK (1 row)
![immagine](https://user-images.githubusercontent.com/26251486/27287519-4369f9c6-5504-11e7-8723-6dd1ab5f2333.png)
7) Press Next and no Chart Type is selectable
![immagine](https://user-images.githubusercontent.com/26251486/27287622-abc58544-5504-11e7-865b-c11aa44cbe57.png)
8) Press Add To Store and get an error:
![immagine](https://user-images.githubusercontent.com/26251486/27287737-f68f6612-5504-11e7-9d4c-96bb18669714.png)
[log_createGadget.txt](https://github.com/wso2/product-ei/files/1085075/log_createGadget.txt)

**Comment by sajithshn** [comment]
EI analytics servers are not meant to be generating gadgets since it's not recommended to edit or top up the out of the box features. However, widget generation in EI analytics 6.5.0-m5 works fine. Therefore, closing the issue.
