### ISSUE TITLE
Create Data Service (UI Error)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#68]
There is an unnecessary wording (Param NameParam Value) printed as shown in the screenshot. This maybe not an EI error, but hope it can be fixed.

![screen shot 2017-01-26 at 7 28 05 pm](https://cloud.githubusercontent.com/assets/21237558/22333760/af0bc16e-e3fd-11e6-94e1-c7630620b007.png)

**Comment by madhawa-gunasekara** [comment]
Fixed it. https://github.com/wso2/carbon-data/pull/135

**Comment by madhawa-gunasekara** [comment]
Fix will add to alpha release
