### ISSUE TITLE
[Docs] URL of analytics dashboard is wrong

### ISSUE THREAD

**Issue by sajhak** [wso2/product-ei#680]
URL of analytics dashboard given in following page is wrong
https://docs.wso2.com/display/EI611/Running+the+Product#RunningtheProduct-EI_AnalyticsStartingtheAnalyticsprofile
 
URL mentioned in the doc https://localhost:9444/dashboard

It needs to be corrected as https://localhost:9444/portal/dashboards

**Comment by praneesha** [comment]
Corrected in all versions of WSO2 EI docs.
