### ISSUE TITLE
Implement web socket to TCP integration in WSO2 EI

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/product-ei#681]
Following changes needs to be incorporated in relevant repositories to support web socket to TCP integration.

1. axis2-transport - https://github.com/wso2/wso2-axis2-transports/pull/113
2. carbon-mediation - https://github.com/wso2/carbon-mediation/pull/771/
3. wso2-synapse - https://github.com/wso2-support/wso2-synapse/pull/107

**Comment by sdkottegoda** [comment]
https://github.com/wso2/wso2-axis2-transports/pull/113 was closed since it is not a generic solution. It can be used as a basis for the complete implementation.

**Comment by chanikag** [comment]
Fixed and the PRs are in https://wso2.org/jira/browse/ESBJAVA-5075
