### ISSUE TITLE
Make it configurable to stop or continue the flow on cache hit

### ISSUE THREAD

**Issue by raj-rajaratnam** [wso2/product-ei#695]
Cache mediator terminates the flow on cache hit, it doesn't execute the rest of the mediators in the flow. There are usecases where we need to continue the execution. So please include this feature and make it configurable as mentioned below, note the continueExecution element. 

```
<cache [id="string"] [hashGenerator="class"] [timeout="seconds"] [scope=(per-host | per-mediator)]
     collector=(true | false) [maxMessageSize="in-bytes"]>
   <onCacheHit [sequence="key"] [continueExecution=(true | false)]>
     (mediator)+
   </onCacheHit>?
   <implementation type=(memory | disk) maxSize="int"/>
</cache>
```

**Comment by lpsandaruwan** [comment]
Experiencing the same issue when creating a seperate sequence for caching. Cache hit breaks the flow. Any update or a workaround for this?
