### ISSUE TITLE
Modification of carbon datasource not reflected into the data services which are using.

### ISSUE THREAD

**Issue by chamarasilva** [wso2/product-ei#697]
When we modify the configuration of a datasource that is used in several data services, these data services do not use the new datasource configuration until the data services are redeployed.

**Comment by madhawa-gunasekara** [comment]
Chamara, what we can easily do is the redeploy the service. or otherwise, we can restart the server. then it will effect all the data services

Thanks,
Madhawa

**Comment by chamarasilva** [comment]
Hi Madhawa,
This is not practical in a production environment. Let say one data source uses 100+ data services, It is not practical to redeploy all services or restart all nodes in prod environment.
Thanks,
Chamara Silva
