### ISSUE TITLE
DBLookup, DBReport mediator should update with externalised configuration improvements

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#706]
Documentation should be updated with the enhancements done in https://wso2.org/jira/browse/ESBJAVA-5056. Refer
[RegistrybasedDBmediatorconfigs.pdf](https://github.com/wso2/product-ei/files/1124128/RegistrybasedDBmediatorconfigs.pdf) for content.

**Comment by praneesha** [comment]
Added a note in [1] and [2]. This is applicable only to WSO2 EI 6.2.0 docs.

[1] https://docs.wso2.com/display/EI620/DBLookup+Mediator
[2] https://docs.wso2.com/display/EI620/DB+Report+Mediator
