### ISSUE TITLE
[Docs][EI][6.1.0][]6.1.1]Missing images in the docs

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#714]
Image attachments are missing in this document.
https://docs.wso2.com/display/EI610/Working+with+Mediators+via+Tooling

Issue is there in 6.0.0, 6.1.0, 6.1.1. Should be fixed for 6.2.0 as well.

**Comment by praneesha** [comment]
Updated the info as for example in [1] in all respective versions of WSO2 Dev Studio, ESB and EI docs.

[1] https://docs.wso2.com/display/EI600/Working+with+Mediators+via+Tooling
