### ISSUE TITLE
[EI611] Build failed when deploy the back-end services FastStockQuoteService, LoadbalanceFailoverService and MTOMSwASampleService.

### ISSUE THREAD

**Issue by jananithangavel** [wso2/product-ei#735]
In build.xml file we need to change the path to the plugin directory as follows
`<include name="repository/components/plugins/*.jar"/>` to
`<include name="wso2/components/plugins/*.jar"/>`

**Comment by himasha** [comment]
Already fixed with https://github.com/wso2/product-ei/commit/e23a87ec285d7459c4d848db9669501d33f49fa1. Cannot reproduce in EI 6.2.0-M3 pack.
