### ISSUE TITLE
Most of the Sample Documentations are not working

### ISSUE THREAD

**Issue by madhawa-gunasekara** [wso2/product-ei#738]
I have checked following sample and fixed relevant changes.
https://docs.wso2.com/display/EI611/JSON+Mapping+Sample

Therefore We should verify all the sample documentations before we do 6.2.0 release. Some ports are wrong. We have check all the samples. found broken documentations.
https://docs.wso2.com/display/EI611/REST-Style+Resources+Sample

We have to fix in previous releases as well.
https://docs.wso2.com/display/EI610/
https://docs.wso2.com/display/EI600/

**Comment by nilminiwso2** [comment]
The following Message Mediation samples are currently being corrected:
1. Sample 0 - Sample 5 : Praneesha
2. Sample 6 -  Sample 11 : Nisrin
3. Sample 12 - Sample 18 : Nilmini

**Comment by praneesha** [comment]
Checked Sample 0 - Sample 5

**Comment by nilminiwso2** [comment]
Checked Sample 12- Sample 18.
4. Sample 50 - Sample 62 (In progress)

**Comment by Nashaath** [comment]
Checked Sample 6- Sample 11

**Comment by nilminiwso2** [comment]
A product issue has been created related to the data integration samples: https://github.com/wso2/product-ei/issues/1008

**Comment by nilminiwso2** [comment]
The URL paths are fixed in all the ESB samples of WSO2 EI 6.1.1 [1]
[1] https://docs.wso2.com/display/EI611/ESB+Profile+Samples
