### ISSUE TITLE
[Question]Issue of killing processors using ctrl+c

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#74]
**Enviornment**
OS-ubuntu 14.04
JAVA-jdk 1.7.0_51
wso2ei-6.0.0-SNAPSHOT 17th of Jan pack

**Steps**
Start the pack with ./start_all.sh
Once all processors got started, kill the processors by entering ctrl+c

**Expected behavior**
All the processors should get killed

**Actual behavior**
Any of the processors didn't get killed

Are we going to support [ctrl+c] for terminating processors?

**Comment by mpmunasinghe** [comment]
Fixed with https://github.com/wso2/product-ei/pull/84/commits/6146b84d301f7de3f1570c899c82f8a95844858b
