### ISSUE TITLE
[Analytics] Delay in updating some statistics components in "Last 5 Minutes" window

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#741]
**Environment**
Pack - EI 6.2.0 Snapshot (with Analytics Improvements)
DB - mysql 5.6
JDK - 1.8.0_101
OS - Ubuntu 15.10

**Steps to reproduce the issue**
1. Configure Analytics with EI profile
2. Create a proxy in the EI
3. Invoke the Proxy
4. Log in to Analytics UI
5. Verify the statistics for "**Last 5 Minutes**"

**Observation**
It takes some time to stabilise the message count of all windows. Initially the 
**"Overall Message Count"** updated correctly but the other statistics such as "request count" updated after some time.

Ex: In the below image "Total Requests" = 1 , but the "Overall Message Count" = 2.

![last5minstats](https://user-images.githubusercontent.com/14962228/28164495-45a5163e-67ed-11e7-8b4f-8410cbb837dc.png)

**Comment by sajithshn** [comment]
Fixed in 6.5.0-M5. However, there can be a delay of a few seconds as the widgets are loaded independently to improve the performance.
