### ISSUE TITLE
Unable to get the durable topic pending message by clicking the 'Refresh' icon

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#75]
**Environment**

OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI M1 Jenkins Build (27/01/2017)

**Prerequisites**
1. EI-Broker should be up and running
2. Inactive durable topic subscriber should exists

**Steps**
1. Publish 10 messages to the above durable inactive durable topic
2. Go to 'Topic Subscriptions' and click 'Refresh' icon

**Observations**
1. pending message count not displayed 

Note - Fix for the issue is included in "https://wso2.org/jira/browse/MB-1765"

**Comment by sashikamw** [comment]
The same issue observed in EI 6.0.0 Alpha pack

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/carbon-business-messaging/commit/80932a844605e0c4b208f6a1be287e51b51cca47

**Comment by sashikamw** [comment]
Verified the fix in 17/02/2017 wso2ei-6.0.0-SNAPSHOT pack
