### ISSUE TITLE
[6.2.0]Sometimes stylesheet tags are being populated in notifications

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#754]
m1, JDK 1.8, Fedora 23

Sometimes stylesheet tags are being populated in notifications. E.g., < br >, < strong >
Search for text in registry.
Try to add a password in secure vault management tool.

Check the screenshot

this issue cannot be seen in ESB 5.0
![screenshot from 2017-07-14 17-43-27](https://user-images.githubusercontent.com/12966170/28211800-1b2523c0-68bc-11e7-8dcd-c4fe00bbadd0.png)
![screenshot from 2017-07-14 17-43-11](https://user-images.githubusercontent.com/12966170/28211801-1b254a26-68bc-11e7-9a39-71d1356683fa.png)

**Comment by ushanib** [comment]
https://github.com/wso2/product-ei/issues/806 Fix this issue as well while fixing the same

**Comment by himasha** [comment]
Closing as per previous comment.
