### ISSUE TITLE
[EI620] Remove the 'ApplicationServer' server role from carbon.xml

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#757]
**Environement**
Pack - EI 620 M1

Since we do not bundle Application Server functionality with EI, we should remove the 'ApplicationServer' server role from the carbon.xml file.

Following are the server roles defined in the carbon.xml

 ```
<ServerRoles>
        <Role>EnterpriseIntegrator</Role>
        <Role>EnterpriseServiceBus</Role>
        <Role>DataServicesServer</Role>
        <Role>ApplicationServer</Role>
    </ServerRoles>
```

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/product-ei/pull/933.
