### ISSUE TITLE
Cannot unsubscribe or close the durable topic subscriptions

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#76]
**Environment**

OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
EI M1 Jenkins Build (27/01/2017)
DB - mysql 5.6.31

**Prerequisites**
1. EI-Broker should be up and running
2. Inactive and active durable topic subscribers should exists

**Steps**
1. Click the 'unsubscribe' icon to unsubscribe inactive durable topic subscriber
2. Click the 'close' icon to close the active durable topic subscriber

**Observations**
1. unsubscribe and close options not working

**Comment by sashikamw** [comment]
The same issue observed in EI 6.0.0 Alpha pack. Below warning message observed in the terminal.

[2017-02-13 12:17:15,275] [EI-Broker]  WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.11.26, method:POST, uri:/carbon/subscriptions/subscriptions_close_ajaxprocessor.jsp, error:required token is missing from the request)

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/carbon-business-messaging/commit/80932a844605e0c4b208f6a1be287e51b51cca47

**Comment by sashikamw** [comment]
Verified the fix in 20/02/2017 latest build pack. Close and unsubscribe operations works successfully
