### ISSUE TITLE
Update axis2.xml to mention broker profile.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#762]
In axis2.xml of Integrator profile, update the below comment. wso2ei-6.2.0-m1/conf/axis2/axis2.xml
 < !-- Uncomment this and configure as appropriate for JMS transport support with WSO2 MB 2.x.x  -- >
   
as 

 < !-- Uncomment this and configure as appropriate for JMS transport support with WSO2 EI Broker Profile -- >
   
This should also be updated in the docs. [1]
[1] https://docs.wso2.com/pages/viewpage.action?spaceKey=EI620&title=Configuring+with+the+Broker+Profile

**Comment by pamod** [comment]
Fixed with PR [1] and did the relevant correction in the document as well. 

[1] https://github.com/wso2/product-ei/pull/941
