### ISSUE TITLE
[Doc]Update docs with latest andes.jar version

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#764]
https://docs.wso2.com/pages/viewpage.action?spaceKey=EI620&title=Configuring+with+the+Broker+Profile

In the 3 rd step,
Copy the following JAR files from the <EI_HOME>/wso2/broker/clent-lib/ directory to the <EI_HOME>/lib/ directory.
andes-client-3.2.4.jar
geronimo-jms_1.1_spec-1.1.0.wso2v1.jar
org.wso2.securevault-1.0.0-wso2v2.jar

andes-client-3.2.4.jar jar should be andes-client-3.2.19.jar

**Comment by praneesha** [comment]
Got the following verified with Ushani and updated the docs accordingly:

- 6.0.0 -> andes-client-3.2.14.jar
- 6.1.0 -> andes-client-3.2.13.jar
- 6.1.1 -> andes-client-3.2.19.jar
- 6.2.0 -> andes-client-3.2.19.jar
