### ISSUE TITLE
Messages not listed when the DLC contains more than 100 messages

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#77]
**Environment**
OS -ubuntu 15.10
JAVA -jdk 1.7.0_65
Browser-chrome version 53.0.2785.89
DB - mysql 5.6.31
EI M1 snapshot pack

**Prerequisites**
1. around 150 messages should exists in the DLC

**Steps**
1. Go to 'DLC' -> 'Browse' to view the messages

**Observations**
1. Only the first 100 messages listed in the UI
2. Even when the user clicks 'Next' to view the remaining messages, only the first 100 messages are visible to the users

**Comment by sashikamw** [comment]
The same issue observed in the EI 6.0.0 Alpha pack as well

**Comment by himasha** [comment]
Fixed with https://github.com/wso2/andes/commit/64d0bfba1a46063c0ac0a892be5833cc52fa21bf

**Comment by sashikamw** [comment]
Verified the fix in 17/02/2017 wso2ei-6.0.0-SNAPSHOT pack
