### ISSUE TITLE
[EI620] Graph for the 'Last Year' appeared with '5.30' in time axis

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#770]
**Environment**
OS - Windows Server 2012 R2
JAVA - JDK 1.8
Browser - Chrome Version 58.0.3029.96 (64-bit)
Pack - EI M1

Counts for the Yearly statistics appeared as "5.30" 
![analyticsstats](https://user-images.githubusercontent.com/14962228/28304688-6b1171ac-6bb6-11e7-81ef-4934c8c6f4f2.png)

Note - Windows Server is running in an open stack machine, where the time stamp different is 5h and 30 min. If the dashboard is accessed via the same machine this graphical issue won't be there.

**Comment by sajithshn** [comment]
Overall TPS widget is being upgraded with 6.5.0-M5. Now the X-axis is shown according to the selected date range(i.e., years, or months, or days ..) and the labels to be shown in X-Axis is calculated accordingly. Therefore, this is fixed in 6.5.0-M5
