### ISSUE TITLE
[EI620] Statistics not visible in the EI Browser

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#773]
**Environment**
OS - Windows Server 2012 R2
JAVA - JDK 1.8
Browser - EI 11.096
Pack - EI M1

**Issue**
Statistics not listed for the Proxy, Sequence, Inbound EP, Endpoints, and APIs. But available for the 'Overview'

![ei](https://user-images.githubusercontent.com/14962228/28309590-7153bb5e-6bc7-11e7-8d0f-842d20601220.png)

**Comment by sajithshn** [comment]
Could not be reproduced in 6.4.0. Please re-open if this is reproducible.
