### ISSUE TITLE
[DOC] Add config to enable PIs in synapse.properties

### ISSUE THREAD

**Issue by vinok88** [wso2/product-ei#782]
The property "synapse.json.to.xml.processing.instruction.enabled=true" should be added to enable Processing Instructions in json to xml conversions. Default is false. This should be added in docs.

**Comment by praneesha** [comment]
Added the property in [1] and updated [2] with this info.

[1] https://docs.wso2.com/display/EI620/Configuring+synapse.properties
[2] https://docs.wso2.com/display/EI620/About+this+Release
