### ISSUE TITLE
[6.2.0] Add New Password to encrypt and store link is not visible for the users other than admin with admin privileges.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#798]
1. Enable secure vault.
2. Add a new user with admin rights or add a secondary user store and login with a user with admin rights.
3. They cannot view the Add New Password to encrypt and store link

![screenshot from 2017-07-20 14-20-56](https://user-images.githubusercontent.com/12966170/28408943-b277bc1c-6d56-11e7-8b18-8be53a7ce86a.png)

**Comment by praveennadarajah** [comment]
This issue not reproducible in the latest EI-6.2.0 WUM updated pack.
