### ISSUE TITLE
[Critical] Some of the JARs missing in the EI-Broker client-lib birectory

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#80]
**Environment**
EI M1 Jenkins Build (27/01/2017)

**Issue**
andes-client-3.1.1.jar and the geronimo-jms_1.1_spec-1.1.1.wso2v1.jar JARs not included in the <EI_HOME>/wso2/broker/client-lib directory.

**Comment by himasha** [comment]
This is fixed and not reproducible in the latest packs.

**Comment by sashikamw** [comment]
"geronimo-jms_1.1_spec-1.1.1.wso2v1.jar" not included in the EI 6.0.0 Alpha pack

**Comment by himasha** [comment]
Thanks for reporting. Geronimo dependency was fixed with https://github.com/wso2/product-ei/pull/164/commits/2a47e17773fed05f50d32e4d585d3f0faca0146b
