### ISSUE TITLE
Additional "<br />" tag in the registry resource selection window

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#806]
UI issue in the pop up windows provided to select the registry resource.

**Steps to recreate the issue**
1. Go to inbound endpoints
2. Select Configure registry or Governance registry from the UI and click 'ok' without selecting a resource

**Observations**
Warning is poped up as "The required field Picked Path has not been filled in.**<br />**". Where the "<br />" should be removed.
![error](https://user-images.githubusercontent.com/14962228/28464874-7c3bba24-6e44-11e7-8c03-f68a4ce72148.png)

**Comment by ushanib** [comment]
Duplicate issue of [https://github.com/wso2/product-ei/issues/754]
