### ISSUE TITLE
[Improvement] Improve the structuring of the documentation 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#808]
Improve the documentation on following aspects
1. Structuring of the documentation should be improved in a way that a new person can identify the supported features within limited time (Due to the current structure it is quite difficult to search the required content from the docs)
ex: Reduce the need to browse through several pages to get the required info (ciphertool -> There's a manual with steps. It should give 1)A complete reference 2)a manual and/or some examples 3) where it will be useful (usecase)
2. Provide more detail information and samples for the mediators supported by the ESB/EI (Most of the times content in the documentation is not enough so that user need to google to find some examples )
example: trying to access the gov reg from a property (perhaps make an 'expression' page with a list of all accessible items using xpath, how to access registry items etc and reference it from every page that allows for expressions?)
3.

**Comment by nilminiwso2** [comment]
doc jiras are already created for this. Therefore, closing this git issue.
[1] https://wso2.org/jira/browse/DOCUMENTATION-4680
[2] https://wso2.org/jira/browse/DOCUMENTATION-4682
[3] https://wso2.org/jira/browse/DOCUMENTATION-4681
