### ISSUE TITLE
Need a best practices guide specific to Timeout configurations in EI

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-ei#810]
Specifically; 
1. http.socket.timeout
2. endpoint timeout duration
3. synapse.timeout_handler_interval 

We have docs which have explained what each and every configuration value means and the default configurations. But we do not have a best practices guide on which values are suitable in which scenarios and how to avoid error-nous conditions.

**Comment by praneesha** [comment]
This information is included in the Best Practices Guide[1] now.

[1] https://docs.wso2.com/display/EI620/WSO2+Enterprise+Integrator+Best+Practices
