### ISSUE TITLE
[Docs]Include documentation regarding profile-creator.sh and profile-creator.bat file functionality in bin folder

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#811]
[Docs]Include documentation regarding profile-creator.sh and profile-creator.bat file functionality in bin folder

**Comment by praneesha** [comment]
Added the following note in [1].

"If you want to optimize the size of the distribution and run a selected profile, execute the following scripts:
On Linux/Mac OS: sh profile-creator.sh
On Windows: profile-creator.bat
However, this creates a distribution of the selected profile in the <EI_HOME> directory and deletes all the files that are not required to run the selected profile. Therefore, you may loose any changes you did to the other profiles."

[1] https://docs.wso2.com/display/EI620/Running+the+Product
