### ISSUE TITLE
'Test' option in the URI Template gives 'Malformed host address $uri'

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#816]
**Environment**
OS - Ubuntu 15.10
JAVA - JDK 8
Pack - EI 620 - M1

**Steps to recreate the issue**
1. Log in to EI server
2. Go to Templates and create an HTTP template endpoint
3. Click "Test" button

**Observation**
1. "Malformed host address $uri" appeared in the UI

![url](https://user-images.githubusercontent.com/14962228/28605730-e3015606-71f0-11e7-934a-89dc14506593.png)

**Question**
What is the purpose of having a "Test" option for the 'URI Template'?
If this is not required we should remove this from the UI.

**Comment by a5anka** [comment]
We can specify an actual URL as well as a URL with variables in when defining the URL template. The 'Test' button can be useful especially when and static URL is used.
