### ISSUE TITLE
Incorrect configuration details in "Securing Datasource Password" section

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#817]
The documentation for securing data source password [1] should be updated accordingly for the inline data source. 

When defining the data source via "Configure -> DataSources" there is no option to add a secret alias. Therefore the documentation should be updated as documented in [2]

[1] https://docs.wso2.com/display/EI611/Securing+Datasource+Password
[2] https://docs.wso2.com/display/DSS322/Securing+Datasource+Password

**Comment by praneesha** [comment]
Updated the page "https://docs.wso2.com/display/DSS321/Securing+Datasource+Password" with the above information.

This is done in WSO2 DSS 3.2.2 and above and in all WSO2 EI versions. For example, see [1].

[1] https://docs.wso2.com/display/EI620/Securing+Datasource+Password
