### ISSUE TITLE
[BPS]When we retire an added bpel task, it will redirect to a Blank page

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#82]
**Environment**

- OS-Ubuntu 14.04
- JAVA- jdk 1.7.0_51 
- Browser-chrome 51.04,firefox 47
- wso2ei-6.0.0-SNAPSHOT 27th of JAN pack

**Steps**

1. Start the BPS management console.
2. Login to console and add a BPEL process.
3. Then retire the process by clicking the retire button.

**Error**
It will redirect to a blank page  and state will not change to retire state

**Comment by himasha** [comment]
Fixed with commit https://github.com/wso2/carbon-business-process/commit/b37ab99a4d5c035ad0eba908e768d789fa9f978a
