### ISSUE TITLE
Add information to docs on using the script mediator to add custom SOAP headers

### ISSUE THREAD

**Issue by Nashaath** [wso2/product-ei#822]
Update [1] with the option of using script mediator to add custom SOAP headers? Currently, it only contains payload mediator option.

[1] https://docs.wso2.com/display/EI611/Custom+SOAP+Headers

Created this issue based on a mail sent by Himasha.

**Comment by praneesha** [comment]
Updated this info in WSO2 EI & ESB docs as in [1] for example.

[1] https://docs.wso2.com/display/Ei620/Custom+SOAP+Headers
