### ISSUE TITLE
[6.2.0]& should be allowed in endpoint in synapse level. User should explicitly escape it

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#824]
http://demo2424780.mockable.io/test?ush=1&a=2 should be given as below when defining an endpoint http://demo2424780.mockable.io/test?ush=1&amp;a=2

**Comment by ushanib** [comment]
If you allow it via UI, it should also escape when going via EI.

**Comment by ushanib** [comment]
Same issue is there in Dev studio. It does not allow to add an endpoint with & sign, it should be escaped 
&amp;

**Comment by Drifftr** [comment]
Cannot Reproduce in 6.5.0
