### ISSUE TITLE
Extend the DSS rest reource sample for batch request scenarios

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#825]
Extend the REST-Style resource sample [1]  by enabling batch request and document the rest resource invocation steps for XML and JSON payloads.

[1] https://docs.wso2.com/display/EI611/REST-Style+Resources+Sample

**Note** - User should be able to identify the mechanism of using batch requests with REST resources for both XML and JSON payloads

XML example:
Endpoint - https://localhost:8243/services/mysqldss/person/addperson_batch_req
<_post_person_addperson_batch_req>
	<_post_person_addperson>
		<id>1130</id>
		<Lname>Testfname</Lname>
		<Fname>fname</Fname>
		<Address>addresstest</Address>
		<city>citytest</city>
	</_post_person_addperson>
	<_post_person_addperson>
		<id>1131</id>
		<Lname>Testlname</Lname>
		<Fname>fname</Fname>
		<Address>addressa</Address>
		<city>citysample</city>
	</_post_person_addperson>
</_post_person_addperson_batch_req>

JSON example:
Endpoint - https://localhost:8243/services/mysqldss/person/addperson_batch_req
{
    "_post_person_addperson_batch_req": {
        "_post_person_addperson": [
            {
                "id" : 1141,
    "Lname": "Lname",
    "Fname": "Fname",
    "Address": "Address1",
    "city": "City1"
            },
            {
                "id" : 1142,
    "Lname": "Lname",
    "Fname": "Fname",
    "Address": "Address2",
    "city": "City1"
            }
        ]
    }
}

**Comment by praneesha** [comment]
Added this content in an info macro at the end of the page in all versions of WSO2 EI & DSS.

For example, see [1].

[1] https://docs.wso2.com/display/EI620/REST-Style+Resources+Sample
