### ISSUE TITLE
[6.2.0]Endpoint Test functionality does not work properly when used in a call mediator

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#829]
Endpoint Test functionality does not work properly when used in a call mediator.
Give a fake endpoint and click on Test button. It will give a success message. When you click on Switch to Source view it will not switch to that mode.

![screenshot from 2017-07-28 11-12-49](https://user-images.githubusercontent.com/12966170/28704046-bca01786-7385-11e7-9241-6d45d3981077.png)

Deployed the api in a capp

`<?xml version="1.0" encoding="UTF-8"?>
<inSequence xmlns="http://ws.apache.org/ns/synapse">
    <log level="custom">
        <property name="MESSAGE" value="+++++++++++++++++++++++++++++++++++++++++++++++++++++++ Hit IN Sequence +++++++++++++++++++++++++++++++++++++++++++"/>
    </log>
    <call>
        <endpoint>
            <http method="GET" uri-template="http://ushanifake.com"/>
        </endpoint>
    </call>
    <log level="custom">
        <property name="MESSAGE1" value="+++++++++++++++++++++++++++++++++++++++++++++++++++++++ Hit After Call +++++++++++++++++++++++++++++++++++++++++++"/>
    </log>
    <respond/>
</inSequence>`

**Comment by a5anka** [comment]
Tested the scenario with EI 6.2.0 M3, but could not reproduce.
 
![screenshot-product-ei-829](https://user-images.githubusercontent.com/1148405/29857872-721ea076-8d78-11e7-870c-31318f424a7d.png)
