### ISSUE TITLE
[BPS] User signup workflow doesn't work as expected when integrating with BPS and apim

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#83]
**Environment**
OS-ubuntu 14.04
JAVA-jdk 1.7.0_51
Browser-Chrome 51.04, firefox 47.0
wso2ei-6.0.0-SNAPSHOT 27th of JAN pack

**Steps**

1. Copy <AM_HOME>/business-process/epr folder into the wso2ei-6.0.0-SNAPSHOT/wso2/business-process/conf folder and start the server
2. Log into the BPS management Console 
3. Deploy Human Task Zip file and the Business Process zip file from the <AM_Home>/business-process/user-signup .
4. Log into the management console in WSO2 API Manager and Edit  /_system/governance/apimgt/applicationdata/workflow-extensions.xml and change the user signup configurations according to following workflow-extensions.xml
5. Login to the APIM store and make user sign up

**Expected behavior**
When you click the User signup button you could see a message saying "User account awaiting Administration approval"
Then you can see all the approval tasks in APIM admin dashboard

**Actual behavior**
When you click the User signup button you could see a message saying "User account awaiting Administration approval"
You cannot  see any of the approval tasks in APIM admin dashboard

**Note**
When you click the human task in BPS, it will redirect to a black page as well.

**Comment by himasha** [comment]
Tested with latest fixes (https://github.com/wso2/carbon-business-process/commit/b37ab99a4d5c035ad0eba908e768d789fa9f978a)  following steps in https://docs.wso2.com/display/AM200/Adding+an+API+Subscription+Workflow.
