### ISSUE TITLE
Transports are not configured for the sample data services bundled with EI

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#830]
**Environment**
Pack - EI620 M1
JAVA - JDK 1.8
OS - Ubuntu

**Steps to recreate the issue**
1. Deploy the data service samples
2. Access the data services

**Observation**
1. Transports are not added to the data services
2. Users should manually enable to the transports to work with the data services

![transport2](https://user-images.githubusercontent.com/14962228/28712156-bc3004ce-73a7-11e7-98e4-4c5f706bff8a.png)

![transports](https://user-images.githubusercontent.com/14962228/28712160-be9cc83c-73a7-11e7-88a3-6d341c11621f.png)

**Comment by arukshani** [comment]
Tried this in M3 pack. Cannot reproduce this anymore.
