### ISSUE TITLE
Update MB fail over handling page with correct product location ad ports

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#831]
Update the configuration details in MB Failover handling page [1] to compatible with the EI MB profile.

Change following;
1. Product location 
2. Ports

[1] https://docs.wso2.com/display/EI611/Handling+Failover

**Comment by praneesha** [comment]
Nilmini has updated this page in docs of all WOS2 EI versions. Confirmed with Sashika also.

Therefore, I am closing this.
