### ISSUE TITLE
Timezone adjustments added for the 'DATE' and 'DATETIME' sql types

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#833]
**Environment**
OS - Ubuntu 15.10
JAVA - JDK 1.8
Pack - EI 620 M1

**Steps to recreate the issue**
1. Create a database in mysql with 'DATE' and TIMESTAMP' sql types

```
CREATE TABLE Student (
    Student_ID int NOT NULL,
    Student_Name varchar(255),
    Advisor_ID int,
    BirthDay DATE,
    added TIMESTAMP,
    PRIMARY KEY (Student_ID)
);
```

2. Create a data service to select data from this database

  <query id="select_students" useConfig="mysqlid">
      <sql>select * from Student where Student_ID =:StudentID</sql>
      <result element="StudentDetails" rowName="students">
         <element column="Student_Name" name="Student_Name" xsdType="string"/>
         <element column="Advisor_ID" name="Advisor_ID" xsdType="integer"/>
         <element column="BirthDay" name="BirthDay" xsdType="date"/>
         <element column="added" name="Added" xsdType="dateTime"/>
         <attribute column="Student_ID" name="StudentID" xsdType="integer"/>
      </result>
      <param name="StudentID" sqlType="INTEGER"/>
   </query>

3. Invoke the operation

**Observations**
1. Timezone adjustment (+5.30) is added to the results

<StudentDetails xmlns="http://ws.wso2.org/dataservice">
   <students StudentID="1">
      <Student_Name>Tom B. Erichsen</Student_Name>
      <Advisor_ID>1001</Advisor_ID>
      <BirthDay>1989-12-31**+05:30**</BirthDay>
      <Added>2017-07-28T16:06:26.000**+05:30**</Added>
   </students>
</StudentDetails>

My requirement is to get the details as below. I have added the following [1] property as mentioned in the doc [2] (verified with 'true' and 'false') but it did not give the expected outcome.

[1] -Ddss.legacy.timezone.mode=true
[2] https://docs.wso2.com/display/DSS351/Timestamp+Conversion+for+RDBMS

![testquery](https://user-images.githubusercontent.com/14962228/28718033-d47d23e4-73c1-11e7-82c9-700f817584b3.png)

**Comment by a5anka** [comment]
Here the timezone value is added by the database server when the data is retrieved which is the expected behaviour. If we have a requirement to remove the timezone from the timestamp, we can use an ESB proxy or API to do the data transformation.
