### ISSUE TITLE
Content-Type header gets overridden in SOAP11<->SOAP12 conversion

### ISSUE THREAD

**Issue by 0h41** [wso2/product-ei#834]
When Axis2Sender converts message between SOAP11 and SOAP12 formats, response messageType and ContentType parameters are overriden by protocol's relative hard-coded entries. This causes malfunctions in workflows where Content-Type header is an essential part of the message (MTOM for example).
This also prevents http.headers.preserve=Content-Type parameter in passthru-http.properties from working correctly.

https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java#L356
https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java#L376

**Comment by vinok88** [comment]
There are defined content-types for SOAP based on the version from the specification. That is the reason to set it explicitly from hardcoded values. We do not do such conversions for MTOM. Try adding the property " <property name="enableSwA" value="true" scope="axis2"/>" if not working for MTOM. 
Please share a sample synapse config that is not working and reopen the issue, then we can fix it.

**Comment by 0h41** [comment]
You are right, Content-Type is defined by specification for SOAP messages.
As for MTOM, it didn't work for me back then for some reason, but now it works fine. 
Although, because we are not living in a perfect world, sometimes you need to do things "not right" or "ugly". "http.headers.preserve=Content-Type" parameter doesn't work as intended in this case in my opinion.
