### ISSUE TITLE
Security is not enabled by default for the SecureDataService sample

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#839]
**Environement**
OS - Ubuntu 15.10
JAVA - JDK 1.8
Pack - EI 620 M1

**Steps to recreate the issue**
1. Deploy the data services samples
2. samples/SecureDataService is deployed with out security enabled

**Observations**
1. According to the sample (https://docs.wso2.com/display/EI611/Secure+Data+Service+Sample) instructed the user to set usernametoken security using UI, which is not valid now.

2. It would be better to provide a UsernameToken secured data service as for this sample

**Comment by ezleyton** [comment]
I know this is old, but as the problem continues, did you have any success with this? happening to me with 6.4
