### ISSUE TITLE
[6.2.0] <messageType> used after payload factory mediator converts long scientific in to decimal number

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#840]
<property name="messageType" scope="axis2" value="application/xml"/>
used after payload factory mediator converts long scientific in to decimal number

Sample backend payload returns 
===========================
{
	"name": "John",
	"age": 30,
 "children": [],
  "spouse": null,
	"cars": [{
			"name": "Ford",
			"models": ["Fiesta", "Focus", "Mustang"]
		},
		{
			"name": "BMW",
			"models": ["320", "X3", "X5"]
		},
		{
			"name": "Fiat",
			"models": ["500", "Panda"]
		}
	],
	"address": {
		"streetAddress": "naist street",
		"city": "Nara",
		"postalCode": "630-0192",
		"contact": [{
				"home": "+9477263645",
				"emailadds": ["ushanib@gmail.com", "ushi324@gmail.com", "ub@yahoo.co.uk"]
			},
			{
				"office": "+942823456",
				"emailadds": ["ushani@wso2.com"]
			}

		],
		  "dosageInfo": [
        {
            "drugId": 4044,
            "gpi": "02100015102125454545454",
            "ageInDaysFrom": "+94772364545",
            "ageInDaysThru": 59,
            "lowDosageQuantity": 0.01,
            "highDosageQuantity": 0.09,
            "lowDosageDuration": 1,
            "highDosageDuration": 42
        },
        {
            "drugId": 4044,
            "gpi": **2.100015102125454545454e+21**,
            "ageInDaysFrom": 60,
            "ageInDaysThru": 89,
            "lowDosageQuantity": 0.01,
            "highDosageQuantity": 0.1,
            "lowDosageDuration": 1,
            "highDosageDuration": 42
        },
        {
            "drugId": 4044,
            "gpi": "02100015102125",
            "ageInDaysFrom": 90,
            "ageInDaysThru": 119,
            "lowDosageQuantity": 0.01,
            "highDosageQuantity": 0.12,
            "lowDosageDuration": 1,
            "highDosageDuration": 42
        },
        {
            "drugId": 4044,
            "gpi": 21000151021000000000000000000000000999999999999999999999999999999999999999999990000000000000000000000000000000025,
            "ageInDaysFrom": 120,
            "ageInDaysThru": "text/xml",
            "lowDosageQuantity": 0.01,
            "highDosageQuantity": 0.13,
            "lowDosageDuration": 1,
            "highDosageDuration": 42
        }
    ]
	}
}

2.100015102125454545454e+21 value is converted to decimal number when used after payload factory mediator.

Sample proxy using a payload fatory mediator
 
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="payload2"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <send>
            <endpoint>
               <address uri="http://demo2424780.mockable.io/test"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <payloadFactory media-type="json">
            <format>{ "Profile": 
            { "source": "mockable", "contact":" $1" ,  "Username": $2 , "Cars": "$3" }}
             
             </format>
            <args>
               <arg evaluator="json" expression="$.name"/>
               <arg evaluator="json" expression="$.address.dosageInfo"/>
               <arg evaluator="json" expression="$.spouse"/>
            </args>
         </payloadFactory>
         <property name="messageType" scope="axis2" value="application/xml"/>
         <send/>
      </outSequence>
   </target>
   <description/>
</proxy>
                                
Response : 

`<jsonObject>
    <Profile>
        <source>mockable</source>
        <contact> John</contact>
        <Username>
            <gpi>02100015102125454545454</gpi>
            <highDosageDuration>42</highDosageDuration>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.09</highDosageQuantity>
            <ageInDaysThru>59</ageInDaysThru>
            <drugId>4044</drugId>
            <ageInDaysFrom>+94772364545</ageInDaysFrom>
            <lowDosageDuration>1</lowDosageDuration>
        </Username>
        <Username>
            <gpi>**2100015102125454545454**</gpi>
            <highDosageDuration>42</highDosageDuration>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.1</highDosageQuantity>
            <ageInDaysThru>89</ageInDaysThru>
            <drugId>4044</drugId>
            <ageInDaysFrom>60</ageInDaysFrom>
            <lowDosageDuration>1</lowDosageDuration>
        </Username>
        <Username>
            <gpi>02100015102125</gpi>
            <highDosageDuration>42</highDosageDuration>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.12</highDosageQuantity>
            <ageInDaysThru>119</ageInDaysThru>
            <drugId>4044</drugId>
            <ageInDaysFrom>90</ageInDaysFrom>
            <lowDosageDuration>1</lowDosageDuration>
        </Username>
        <Username>
            <gpi>* Connection #0 to host localhost.localdomain left intact
21000151021000000000000000000000000999999999999999999999999999999999999999999990000000000000000000000000000000025</gpi>
            <highDosageDuration>42</highDosageDuration>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.13</highDosageQuantity>
            <ageInDaysThru>text/xml</ageInDaysThru>
            <drugId>4044</drugId>
            <ageInDaysFrom>120</ageInDaysFrom>
            <lowDosageDuration>1</lowDosageDuration>
        </Username>
        <Cars>null</Cars>
    </Profile>
</jsonObject>`

When use without a payload factory :

`<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="payload3"
       startOnLoad="true"
       statistics="disable"
       trace="disable"
       transports="http,https">
   <target>
      <inSequence>
         <send>
            <endpoint>
               <address uri="http://demo2424780.mockable.io/test"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <property name="messageType" scope="axis2" value="application/xml"/>
         <send/>
      </outSequence>
   </target>
   <description/>
</proxy>
                                `

Respone -

`<jsonObject>
    <name>John</name>
    <age>30</age>
    <spouse/>
    <cars>
        <name>Ford</name>
        <models>Fiesta</models>
        <models>Focus</models>
        <models>Mustang</models>
    </cars>
    <cars>
        <name>BMW</name>
        <models>320</models>
        <models>X3</models>
        <models>X5</models>
    </cars>
    <cars>
        <name>Fiat</name>
        <models>500</models>
        <models>Panda</models>
    </cars>
    <address>
        <streetAddress>naist street</streetAddress>
        <city>Nara</city>
        <postalCode>630-0192</postalCode>
        <contact>
            <home>+9477263645</home>
            <emailadds>ushanib@gmail.com</emailadds>
            <emailadds>ushi324@gmail.com</emailadds>
            <emailadds>ub@yahoo.co.uk</emailadds>
        </contact>
        <contact>
            <office>+942823456</office>
            <emailadds>ushani@wso2.com</emailadds>
        </contact>
        <dosageInfo>
            <drugId>4044</drugId>
            <gpi>02100015102125454545454</gpi>
            <ageInDaysFrom>+94772364545</ageInDaysFrom>
            <ageInDaysThru>59</ageInDaysThru>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.09</highDosageQuantity>
            <lowDosageDuration>1</lowDosageDuration>
            <highDosageDuration>42</highDosageDuration>
        </dosageInfo>
        <dosageInfo>
            <drugId>4044</drugId>
            <gpi>**2.100015102125454545454e+21**</gpi>
            <ageInDaysFrom>60</ageInDaysFrom>
            <ageInDaysThru>89</ageInDaysThru>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.1</highDosageQuantity>
            <lowDosageDuration>1</lowDosageDuration>
            <highDosageDuration>42</highDosageDuration>
        </dosageInfo>
        <dosageInfo>
            <drugId>4044</drugId>
            <gpi>02100015102125</gpi>
            <ageInDaysFrom>90</ageInDaysFrom>
            <ageInDaysThru>119</ageInDaysThru>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.12</highDosageQuantity>
            <lowDosageDuration>1</lowDosageDuration>
            <highDosageDuration>42</highDosageDuration>
        </dosageInfo>
        <dosageInfo>
            <drugId>4044</drugId>
            <gpi>21000151021000000000000000000000000999999999999999999999999999999999999999999990000000000000000000000000000000025</gpi>
            <ageInDaysFrom>120</ageInDaysFrom>
            <ageInDaysThru>text/xml</ageInDaysThru>
            <lowDosageQuantity>0.01</lowDosageQuantity>
            <highDosageQuantity>0.13</highDosageQuantity>
            <lowDosageDuration>1</lowDosageDuration>
            <highDosageDuration>42</highDosageDuration>
        </dosageInfo>
    </address>
</jsonObject>`

Attaching issue in a notepad since this has some style issues. 
[issue.txt](https://github.com/wso2/product-ei/files/1187142/issue.txt)

**Comment by vinok88** [comment]
Can you please try this with JsonBuilder and JsonFormatter enabled in axis2.xml. I believe you are using default streaming builders. This has to be due to the way the formatter interpreted it, which is out of synapse's control.

**Comment by pamod** [comment]
When payload factory is used the message get's built, given it's not the PT use case. When the message get's built it get's converted to it's primitive alternative. Which will be the reason to experience the conversion of the values. 

You should be able to control the conversion by using the following property,

synapse.commons.json.output.disableAutoPrimitive.regex

Where specifying the regex would omit the automatic conversion.

Please try the above approach and re-open if it doesn't work for your use case.

**Comment by ushanib** [comment]
Is this issue related to https://wso2.org/jira/browse/ESBJAVA-4983 ?
