### ISSUE TITLE
Update certificate in keystore since the existing one is expried

### ISSUE THREAD

**Issue by Manuri** [wso2/product-ei#841]
Please refer https://github.com/wso2/carbon-kernel/issues/1442

Need to update kernel version in master branch.

**Comment by a5anka** [comment]
Closing the issue since already fixed.

**Comment by Manuri** [comment]
Kernel version needs to be upgraded to 4.4.17.

**Comment by manoramahp** [comment]
Upgraded kernel version : https://github.com/wso2/product-ei/pull/980
