### ISSUE TITLE
[Doc]Improve Enrich mediator documentation with different types of examples.

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#846]
[Doc]Improve Enrich mediator documentation with different types of examples. Doc [1] is not enough at all.

Better to have sample for  different types source and target

[1] https://docs.wso2.com/display/EI610/Enrich+Mediator

**Comment by abeykoon** [comment]
As per @GDLMadushanka following blog has some detail on Json. 
lahirumadushankablog.wordpress.com/2018/12/12/enriching-json-payloads-in-wso2-ei/

**Comment by KasunAratthanage** [comment]
I have tested and added different types source and target samples to the documentation using the mentioned blog in the previous comment.

Please refer the following documentation.

https://docs.wso2.com/display/EI6xx/Enrich+Mediator
Example 5 - Enriching in JSON format

**Comment by abeykoon** [comment]
This is resolved as per above comment. Examples added.
