### ISSUE TITLE
[Doc][AS4] AS4 connector documentation

### ISSUE THREAD

**Issue by manoramahp** [wso2/product-ei#856]
[WSO2 ESB AS4 Connector.docx](https://github.com/wso2/product-ei/files/1216968/WSO2.ESB.AS4.Connector.docx)

Related git issue : https://github.com/wso2/product-ei/issues/852

**Comment by Nashaath** [comment]
I've created [1] based on the content that was shared. 
The page is visible to WSO2 folks only. I need the download location to include in the doc. Therefore I'll publish the doc once the connector is added to the store

[1] https://docs.wso2.com/display/ESBCONNECTORS/AS4+Connector

**Comment by Nashaath** [comment]
Since the connector has been added to the store I have updated [1] with the download link.
[1] https://docs.wso2.com/display/ESBCONNECTORS/AS4+Connector
