### ISSUE TITLE
[Doc] Update the java version to be used with EI 6.2.0 in docs.

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#868]
Due to a jdk bug [1] to use Nashorn Java Script engine with Script Mediator, user need to have jdk 8 update 112 or later version. So need to update the version to be used with EI 6.2.0 to jdk 8 update 112 or later in docs.

[1] http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8157160

**Comment by praneesha** [comment]
Edited the note in [1] as follows:

"To launch WSO2 Enterprise Integrator, you need to have Oracle JDK 1.8.* . However, to have the Nashorn JavaScript engine support for the Script Mediator, you need to use JDK 8 version update 112 or later. "

[1] https://docs.wso2.com/display/EI620/Installation+Prerequisites
