### ISSUE TITLE
Cannot add webapps although add permission is given

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#90]
I have created a user and given Add permission to Module, Services, Webapps. Put Webadd adding menu is not shown to the user.

Permissions.

![screenshot from 2017-01-30 16-30-33](https://cloud.githubusercontent.com/assets/7681361/22420842/45f09e06-e70a-11e6-9265-f1733a4745c6.png)

Loaded UI for the new user

![screenshot from 2017-01-30 16-30-45](https://cloud.githubusercontent.com/assets/7681361/22420846/4ae556d6-e70a-11e6-9d1e-1949345acf0a.png)

**Comment by himasha** [comment]
The Same behavior can be seen in AS 5.3.0 as well. You need to select both 'Add' and 'Configure' options of 'Manage' in order to get 'Web Applications' UI.

<img width="324" alt="permissions" src="https://cloud.githubusercontent.com/assets/9687840/23011961/cb0e992a-f449-11e6-869a-dc9b19854469.png">
