### ISSUE TITLE
"buildMessage" attribute in failover and loadbalance endpoint is not supported from the management console.

### ISSUE THREAD

**Issue by Bhashinee** [wso2/product-ei#909]
Create a loadbalance or a failover endpoint.
In the design view there is no attribute named buildMessage to select.
Go to the source view and try adding buildMessage = "true" attribute. It can not be saved.

**Comment by manoramahp** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/808, https://github.com/wso2/carbon-mediation/pull/860
