### ISSUE TITLE
CApps and connectors need to have fine grained permission

### ISSUE THREAD

**Issue by inoshperera** [wso2/product-ei#932]
In ESB 4.9.0, to view the connectors and CApps, it is necessery to provide Manage/ root permission and if there is any permission under manage permission needs to be unchecked, it will cause the CApps and connectors lists to be hidden.

**Comment by baahmi** [comment]
Can you add this fix to WUM for the EI ?

**Comment by prabushi** [comment]
This fix will be available in the upcoming EI 6.2.0 release. 
Closing the issue since the fix is already merged.

**Comment by Nirothipan** [comment]
This fixed is added to EI 6.1.1 as well. WIll be available via WUM in few more days.

**Comment by baahmi** [comment]
Thanx!
