### ISSUE TITLE
MySQL Driver location should be "<PRODUCT_HOME>/lib" in the doc "Monitoring the ESB Profile with EI Analytics in a Multi-tenant Environment"

### ISSUE THREAD

**Issue by arukshani** [wso2/product-ei#940]
Link to the doc >> https://docs.wso2.com/display/EI611/Monitoring+the+ESB+Profile+with+EI+Analytics+in+a+Multi-tenant+Environment

**Comment by praneesha** [comment]
Checked with Rukshani. This is fixed now.
