### ISSUE TITLE
SOAP envelope removed when the response taken from the cache

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#943]
**Environment**
Pack - EI620 M3
JAVA - JDK 1.8
OS - Ubuntu 15.10

**Steps to recreate the issue**
1. Create an API with cache mediator as below

```
<api xmlns="http://ws.apache.org/ns/synapse" name="StockQuoteAPI" context="/stockquote">
   <resource methods="GET" uri-template="/view/{symbol}">
      <inSequence>
         <payloadFactory media-type="xml">
            <format>
               <m0:getQuote xmlns:m0="http://services.samples">
                  <m0:request>
                     <m0:symbol>$1</m0:symbol>
                  </m0:request>
               </m0:getQuote>
            </format>
            <args>
               <arg evaluator="xml" expression="get-property('uri.var.symbol')"/>
            </args>
         </payloadFactory>
         <header name="Action" value="urn:getQuote"/>
         <log level="full"/>
         <cache collector="false" timeout="5000">
            <protocol type="HTTP">
               <methods>*</methods>
               <headersToExcludeInHash/>
               <responseCodes>.*</responseCodes>
               <hashGenerator>org.wso2.carbon.mediator.cache.digest.HttpRequestHashGenerator</hashGenerator>
            </protocol>
         </cache>
         <log level="full"/>
         <send>
            <endpoint>
               <address uri="http://192.168.48.217:9000/services/SimpleStockQuoteService" format="soap11"/>
            </endpoint>
         </send>
      </inSequence>
      <outSequence>
         <log level="full"/>
         <cache collector="true"/>
         <log level="full"/>
         <respond/>
      </outSequence>
   </resource>
</api>
```

2. Invoke the API twice
http://localhost:8280/stockquote/view/IBM

**Observations**
1. When the API is invoked for the first time,  response was taken from the backend and the response contains the SOAP envelope
ex:
`<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><ns:getQuoteResponse xmlns:ns="http://services.samples"><ns:return xmlns:ax21="http://services.samples/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:GetQuoteResponse"><ax21:change>-2.430505876329506</ax21:change><ax21:earnings>12.771947824922636</ax21:earnings><ax21:high>58.061937356237436</ax21:high><ax21:last>56.05347664434554</ax21:last><ax21:lastTradeTimestamp>Tue Aug 29 09:09:49 UTC 2017</ax21:lastTradeTimestamp><ax21:low>-55.910989032371894</ax21:low><ax21:marketCap>1.4374355628649648E7</ax21:marketCap><ax21:name>test7 Company</ax21:name><ax21:open>58.135422888844985</ax21:open><ax21:peRatio>23.869663513831757</ax21:peRatio><ax21:percentageChange>-3.8290261011081856</ax21:percentageChange><ax21:prevClose>63.47582419524578</ax21:prevClose><ax21:symbol>test7</ax21:symbol><ax21:volume>5430</ax21:volume></ns:return></ns:getQuoteResponse></soapenv:Body></soapenv:Envelope>`

When the API is invoked the for the second time, response was taken from the cache, but the SOAP envelope is missing in the response

ex: 
`<ns:getQuoteResponse xmlns:ns="http://services.samples"><ns:return xmlns:ax21="http://services.samples/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:GetQuoteResponse"><ax21:change>-2.430505876329506</ax21:change><ax21:earnings>12.771947824922636</ax21:earnings><ax21:high>58.061937356237436</ax21:high><ax21:last>56.05347664434554</ax21:last><ax21:lastTradeTimestamp>Tue Aug 29 09:09:49 UTC 2017</ax21:lastTradeTimestamp><ax21:low>-55.910989032371894</ax21:low><ax21:marketCap>1.4374355628649648E7</ax21:marketCap><ax21:name>test7 Company</ax21:name><ax21:open>58.135422888844985</ax21:open><ax21:peRatio>23.869663513831757</ax21:peRatio><ax21:percentageChange>-3.8290261011081856</ax21:percentageChange><ax21:prevClose>63.47582419524578</ax21:prevClose><ax21:symbol>test7</ax21:symbol><ax21:volume>5430</ax21:volume></ns:return></ns:getQuoteResponse>`

**Comment by milanperera** [comment]
Since it's producing a regression issue, it is reopened.
Failing ESBJAVA4721PIWithCacheTestCase

**Comment by riyafa** [comment]
Need to be fixed as it was reverted. Solution PRs: https://github.com/wso2/carbon-mediation/pull/961
https://github.com/wso2/carbon-mediation/pull/965
