### ISSUE TITLE
ProxyContextPath is not getting appended to service URLs

### ISSUE THREAD

**Issue by yasassri** [wso2/product-ei#95]
*Steps*

1. Configure ProxyContextPath in carbon.xml.
2. Restart the server and check service URLs.

**Issue:** The ProxyContextPath is not added to service URLs.

**Comment by himasha** [comment]
This is a known issue in ESB 5.0.0.  https://wso2.org/jira/browse/ESBJAVA-5020

**Comment by vinok88** [comment]
This functionality is working fine. <MgtProxyContextPath> should be used for manager nodes and <ProxyContextPath> should be used for worker nodes.  However, this context path change is not reflected in the management console UI. Reported Jira[1] for carbon-kernel to fix it.

[1] - https://wso2.org/jira/browse/CARBON-16111

**Comment by nandika** [comment]
Closing issue as it is duplicated in carbon kernel jira
