### ISSUE TITLE
Upgrade Commons-VFS version to 2.1 or higher

### ISSUE THREAD

**Issue by pamod** [wso2/product-ei#956]
Given there're a list of improvements made in the newer version. It would be appropriate to upgrade the commons-vfs library version to the latest.

**Comment by malakaganga** [comment]
Fixed isuues with following pr's:

https://github.com/wso2/wso2-commons-vfs/pull/45
https://github.com/wso2/wso2-commons-vfs/pull/46
https://github.com/wso2/wso2-commons-vfs/pull/47
https://github.com/wso2/wso2-commons-vfs/pull/48/files
https://github.com/wso2/wso2-commons-vfs/pull/49
