### ISSUE TITLE
DSS SPARQL insert

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#964]
There was an issue reported in support some time back requesting for the $Subject feature. The requirement was to "get data set from a RDBMS, transform them to RDF and insert to a SPARQL endpoint."

This needs to be documented after implementing.

**Comment by praneesha** [comment]
Closing the doc issue of this in [1] since this is yet to be implemented and there is no need to have a duplicate issue.

Please create a doc issue or reopen this once this is implemented in the product.

[1] https://github.com/wso2/product-ei/issues/965
