### ISSUE TITLE
Can not remove the initial value assigned to the Maximum message size property in cache mediator 

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#971]
**Environment**
Pack - EI 620 M3
OS - Ubuntu 15.10
JAVA - JDk 1.8

**Steps to reproduce the issue**
1. Create an API with cache mediator by defining a value for '**Maximum message size**' and '**Maximum size**'
2. Remove the values added for 'Maximum Message Size' and 'Maximum size' properties and save the API

**Observation**
Message size value did not get removed, when the value is removed and saved

**Expected Behaviour**
Should be able to remove the values and save. When the value is not specified a default value should be picked for these properties

**Comment by riyafa** [comment]
I hope you tested this in the management console

**Comment by sashikamw** [comment]
Yes this was tested in management console
