### ISSUE TITLE
References to ESB in files

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#98]
Some files (specially in Analytics) in the EI distribution refers to ESB. See the attached screenshots.

![screen shot 2017-01-31 at 1 44 43 pm](https://cloud.githubusercontent.com/assets/21237558/22457009/a1eb46a0-e7bb-11e6-85be-c309fa6367af.png)

![screen shot 2017-01-31 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/21237558/22457028/ad1b5196-e7bb-11e6-92af-e3db9bef278c.png)

![screen shot 2017-01-31 at 1 45 02 pm](https://cloud.githubusercontent.com/assets/21237558/22457035/b1c3446a-e7bb-11e6-8bdb-ba06b1b38405.png)

![screen shot 2017-01-31 at 1 43 40 pm](https://cloud.githubusercontent.com/assets/21237558/22457040/b6360f82-e7bb-11e6-86d3-2fb70e1a5377.png)

![screen shot 2017-01-31 at 1 45 13 pm](https://cloud.githubusercontent.com/assets/21237558/22457047/bfab393e-e7bb-11e6-92e9-af6248f7ba29.png)

**Comment by mpmunasinghe** [comment]
With the commit https://github.com/wso2/product-ei/commit/ed2444b0d6360d23cf9ed526b32b563b02f052e9 changed the ESB references in Dashboard.
